using System;
using System.Collections;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;

namespace System.Data
{
	// Token: 0x0200009E RID: 158
	[DefaultEvent("CollectionChanged")]
	[Editor("Microsoft.VSDesigner.Data.Design.ConstraintsCollectionEditor, Microsoft.VSDesigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Drawing.Design.UITypeEditor, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
	public sealed class ConstraintCollection : InternalDataCollectionBase
	{
		// Token: 0x060007F6 RID: 2038 RVA: 0x00056CA0 File Offset: 0x000560A0
		internal ConstraintCollection(DataTable table)
		{
			this.table = table;
		}

		// Token: 0x17000122 RID: 290
		// (get) Token: 0x060007F7 RID: 2039 RVA: 0x00056CCC File Offset: 0x000560CC
		protected override ArrayList List
		{
			get
			{
				return this.list;
			}
		}

		// Token: 0x17000123 RID: 291
		public Constraint this[int index]
		{
			get
			{
				if (index >= 0 && index < this.List.Count)
				{
					return (Constraint)this.List[index];
				}
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
		}

		// Token: 0x17000124 RID: 292
		// (get) Token: 0x060007F9 RID: 2041 RVA: 0x00056D18 File Offset: 0x00056118
		internal DataTable Table
		{
			get
			{
				return this.table;
			}
		}

		// Token: 0x17000125 RID: 293
		public Constraint this[string name]
		{
			get
			{
				int num = this.InternalIndexOf(name);
				if (num == -2)
				{
					throw ExceptionBuilder.CaseInsensitiveNameConflict(name);
				}
				if (num >= 0)
				{
					return (Constraint)this.List[num];
				}
				return null;
			}
		}

		// Token: 0x060007FB RID: 2043 RVA: 0x00056D64 File Offset: 0x00056164
		public void Add(Constraint constraint)
		{
			this.Add(constraint, true);
		}

		// Token: 0x060007FC RID: 2044 RVA: 0x00056D7C File Offset: 0x0005617C
		internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.FindConstraint(constraint) != null)
			{
				throw ExceptionBuilder.DuplicateConstraint(this.FindConstraint(constraint).ConstraintName);
			}
			if (1 < this.table.NestedParentRelations.Length && !this.AutoGenerated(constraint))
			{
				throw ExceptionBuilder.CantAddConstraintToMultipleNestedTable(this.table.TableName);
			}
			if (constraint is UniqueConstraint)
			{
				if (((UniqueConstraint)constraint).bPrimaryKey && this.Table.primaryKey != null)
				{
					throw ExceptionBuilder.AddPrimaryKeyConstraint();
				}
				this.AddUniqueConstraint((UniqueConstraint)constraint);
			}
			else if (constraint is ForeignKeyConstraint)
			{
				ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraint;
				if (addUniqueWhenAddingForeign && foreignKeyConstraint.RelatedTable.Constraints.FindKeyConstraint(foreignKeyConstraint.RelatedColumnsReference) == null)
				{
					if (constraint.ConstraintName.Length == 0)
					{
						constraint.ConstraintName = this.AssignName();
					}
					else
					{
						this.RegisterName(constraint.ConstraintName);
					}
					UniqueConstraint constraint2 = new UniqueConstraint(foreignKeyConstraint.RelatedColumnsReference);
					foreignKeyConstraint.RelatedTable.Constraints.Add(constraint2);
				}
				this.AddForeignKeyConstraint((ForeignKeyConstraint)constraint);
			}
			this.BaseAdd(constraint);
			this.ArrayAdd(constraint);
			this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, constraint));
			if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).bPrimaryKey)
			{
				this.Table.PrimaryKey = ((UniqueConstraint)constraint).ColumnsReference;
			}
		}

		// Token: 0x060007FD RID: 2045 RVA: 0x00056EDC File Offset: 0x000562DC
		public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, columns);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = columns;
			}
			return uniqueConstraint;
		}

		// Token: 0x060007FE RID: 2046 RVA: 0x00056F08 File Offset: 0x00056308
		public Constraint Add(string name, DataColumn column, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, column);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = uniqueConstraint.ColumnsReference;
			}
			return uniqueConstraint;
		}

		// Token: 0x060007FF RID: 2047 RVA: 0x00056F3C File Offset: 0x0005633C
		public Constraint Add(string name, DataColumn primaryKeyColumn, DataColumn foreignKeyColumn)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumn, foreignKeyColumn);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		// Token: 0x06000800 RID: 2048 RVA: 0x00056F5C File Offset: 0x0005635C
		public Constraint Add(string name, DataColumn[] primaryKeyColumns, DataColumn[] foreignKeyColumns)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumns, foreignKeyColumns);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		// Token: 0x06000801 RID: 2049 RVA: 0x00056F7C File Offset: 0x0005637C
		public void AddRange(Constraint[] constraints)
		{
			if (this.table.fInitInProgress)
			{
				this.delayLoadingConstraints = constraints;
				this.fLoadForeignKeyConstraintsOnly = false;
				return;
			}
			if (constraints != null)
			{
				foreach (Constraint constraint in constraints)
				{
					if (constraint != null)
					{
						this.Add(constraint);
					}
				}
			}
		}

		// Token: 0x06000802 RID: 2050 RVA: 0x00056FC8 File Offset: 0x000563C8
		private void AddUniqueConstraint(UniqueConstraint constraint)
		{
			DataColumn[] columnsReference = constraint.ColumnsReference;
			for (int i = 0; i < columnsReference.Length; i++)
			{
				if (columnsReference[i].Table != this.table)
				{
					throw ExceptionBuilder.ConstraintForeignTable();
				}
			}
			constraint.ConstraintIndexInitialize();
			if (!constraint.CanEnableConstraint())
			{
				constraint.ConstraintIndexClear();
				throw ExceptionBuilder.UniqueConstraintViolation();
			}
		}

		// Token: 0x06000803 RID: 2051 RVA: 0x0005701C File Offset: 0x0005641C
		private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
		{
			if (!constraint.CanEnableConstraint())
			{
				throw ExceptionBuilder.ConstraintParentValues();
			}
			constraint.CheckCanAddToCollection(this);
		}

		// Token: 0x06000804 RID: 2052 RVA: 0x00057040 File Offset: 0x00056440
		private bool AutoGenerated(Constraint constraint)
		{
			ForeignKeyConstraint foreignKeyConstraint = constraint as ForeignKeyConstraint;
			if (foreignKeyConstraint != null)
			{
				return XmlTreeGen.AutoGenerated(foreignKeyConstraint, false);
			}
			UniqueConstraint unique = (UniqueConstraint)constraint;
			return XmlTreeGen.AutoGenerated(unique);
		}

		// Token: 0x14000002 RID: 2
		// (add) Token: 0x06000805 RID: 2053 RVA: 0x0005706C File Offset: 0x0005646C
		// (remove) Token: 0x06000806 RID: 2054 RVA: 0x00057090 File Offset: 0x00056490
		public event CollectionChangeEventHandler CollectionChanged
		{
			add
			{
				this.onCollectionChanged = (CollectionChangeEventHandler)Delegate.Combine(this.onCollectionChanged, value);
			}
			remove
			{
				this.onCollectionChanged = (CollectionChangeEventHandler)Delegate.Remove(this.onCollectionChanged, value);
			}
		}

		// Token: 0x06000807 RID: 2055 RVA: 0x000570B4 File Offset: 0x000564B4
		private void ArrayAdd(Constraint constraint)
		{
			this.List.Add(constraint);
		}

		// Token: 0x06000808 RID: 2056 RVA: 0x000570D0 File Offset: 0x000564D0
		private void ArrayRemove(Constraint constraint)
		{
			this.List.Remove(constraint);
		}

		// Token: 0x06000809 RID: 2057 RVA: 0x000570EC File Offset: 0x000564EC
		internal string AssignName()
		{
			string result = this.MakeName(this.defaultNameIndex);
			this.defaultNameIndex++;
			return result;
		}

		// Token: 0x0600080A RID: 2058 RVA: 0x00057118 File Offset: 0x00056518
		private void BaseAdd(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.ConstraintName.Length == 0)
			{
				constraint.ConstraintName = this.AssignName();
			}
			else
			{
				this.RegisterName(constraint.ConstraintName);
			}
			constraint.InCollection = true;
		}

		// Token: 0x0600080B RID: 2059 RVA: 0x00057164 File Offset: 0x00056564
		private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
		{
			int num = 0;
			for (int i = 0; i < oldLength; i++)
			{
				bool flag = false;
				for (int j = num; j < newLength; j++)
				{
					if (oldArray[i] == newArray[j])
					{
						if (num == j)
						{
							num++;
						}
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					this.BaseRemove(oldArray[i]);
					this.List.Remove(oldArray[i]);
				}
			}
			for (int k = 0; k < newLength; k++)
			{
				if (!newArray[k].InCollection)
				{
					this.BaseAdd(newArray[k]);
				}
				this.List.Add(newArray[k]);
			}
		}

		// Token: 0x0600080C RID: 2060 RVA: 0x000571F0 File Offset: 0x000565F0
		private void BaseRemove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.Table != this.table)
			{
				throw ExceptionBuilder.ConstraintRemoveFailed();
			}
			this.UnregisterName(constraint.ConstraintName);
			constraint.InCollection = false;
			if (constraint is UniqueConstraint)
			{
				for (int i = 0; i < this.Table.ChildRelations.Count; i++)
				{
					DataRelation dataRelation = this.Table.ChildRelations[i];
					if (dataRelation.ParentKeyConstraint == constraint)
					{
						dataRelation.SetParentKeyConstraint(null);
					}
				}
				((UniqueConstraint)constraint).ConstraintIndexClear();
				return;
			}
			if (constraint is ForeignKeyConstraint)
			{
				for (int j = 0; j < this.Table.ParentRelations.Count; j++)
				{
					DataRelation dataRelation2 = this.Table.ParentRelations[j];
					if (dataRelation2.ChildKeyConstraint == constraint)
					{
						dataRelation2.SetChildKeyConstraint(null);
					}
				}
			}
		}

		// Token: 0x0600080D RID: 2061 RVA: 0x000572C8 File Offset: 0x000566C8
		public bool CanRemove(Constraint constraint)
		{
			return this.CanRemove(constraint, false);
		}

		// Token: 0x0600080E RID: 2062 RVA: 0x000572E0 File Offset: 0x000566E0
		internal bool CanRemove(Constraint constraint, bool fThrowException)
		{
			return constraint.CanBeRemovedFromCollection(this, fThrowException);
		}

		// Token: 0x0600080F RID: 2063 RVA: 0x000572F8 File Offset: 0x000566F8
		public void Clear()
		{
			if (this.table != null)
			{
				this.table.PrimaryKey = null;
				for (int i = 0; i < this.table.ParentRelations.Count; i++)
				{
					this.table.ParentRelations[i].SetChildKeyConstraint(null);
				}
				for (int j = 0; j < this.table.ChildRelations.Count; j++)
				{
					this.table.ChildRelations[j].SetParentKeyConstraint(null);
				}
			}
			if (this.table.fInitInProgress && this.delayLoadingConstraints != null)
			{
				this.delayLoadingConstraints = null;
				this.fLoadForeignKeyConstraintsOnly = false;
			}
			int count = this.List.Count;
			Constraint[] array = new Constraint[this.List.Count];
			this.List.CopyTo(array, 0);
			try
			{
				this.BaseGroupSwitch(array, count, null, 0);
			}
			catch (Exception e)
			{
				if (ADP.IsCatchableOrSecurityExceptionType(e))
				{
					this.BaseGroupSwitch(null, 0, array, count);
					this.List.Clear();
					for (int k = 0; k < count; k++)
					{
						this.List.Add(array[k]);
					}
				}
				throw;
			}
			this.List.Clear();
			this.OnCollectionChanged(InternalDataCollectionBase.RefreshEventArgs);
		}

		// Token: 0x06000810 RID: 2064 RVA: 0x0005744C File Offset: 0x0005684C
		public bool Contains(string name)
		{
			return this.InternalIndexOf(name) >= 0;
		}

		// Token: 0x06000811 RID: 2065 RVA: 0x00057468 File Offset: 0x00056868
		internal bool Contains(string name, bool caseSensitive)
		{
			if (!caseSensitive)
			{
				return this.Contains(name);
			}
			int num = this.InternalIndexOf(name);
			return num >= 0 && name == ((Constraint)this.List[num]).ConstraintName;
		}

		// Token: 0x06000812 RID: 2066 RVA: 0x000574AC File Offset: 0x000568AC
		public void CopyTo(Constraint[] array, int index)
		{
			if (array == null)
			{
				throw ExceptionBuilder.ArgumentNull("array");
			}
			if (index < 0)
			{
				throw ExceptionBuilder.ArgumentOutOfRange("index");
			}
			if (array.Length - index < this.list.Count)
			{
				throw ExceptionBuilder.InvalidOffsetLength();
			}
			for (int i = 0; i < this.list.Count; i++)
			{
				array[index + i] = (Constraint)this.list[i];
			}
		}

		// Token: 0x06000813 RID: 2067 RVA: 0x0005751C File Offset: 0x0005691C
		internal Constraint FindConstraint(Constraint constraint)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (((Constraint)this.List[i]).Equals(constraint))
				{
					return (Constraint)this.List[i];
				}
			}
			return null;
		}

		// Token: 0x06000814 RID: 2068 RVA: 0x00057570 File Offset: 0x00056970
		internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && ConstraintCollection.CompareArrays(uniqueConstraint.Key.ColumnsReference, columns))
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000815 RID: 2069 RVA: 0x000575C4 File Offset: 0x000569C4
		internal UniqueConstraint FindKeyConstraint(DataColumn column)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && uniqueConstraint.Key.ColumnsReference.Length == 1 && uniqueConstraint.Key.ColumnsReference[0] == column)
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000816 RID: 2070 RVA: 0x00057628 File Offset: 0x00056A28
		internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				ForeignKeyConstraint foreignKeyConstraint = this.List[i] as ForeignKeyConstraint;
				if (foreignKeyConstraint != null && ConstraintCollection.CompareArrays(foreignKeyConstraint.ParentKey.ColumnsReference, parentColumns) && ConstraintCollection.CompareArrays(foreignKeyConstraint.ChildKey.ColumnsReference, childColumns))
				{
					return foreignKeyConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000817 RID: 2071 RVA: 0x00057694 File Offset: 0x00056A94
		private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
		{
			if (a1.Length != a2.Length)
			{
				return false;
			}
			for (int i = 0; i < a1.Length; i++)
			{
				bool flag = false;
				for (int j = 0; j < a2.Length; j++)
				{
					if (a1[i] == a2[j])
					{
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x06000818 RID: 2072 RVA: 0x000576DC File Offset: 0x00056ADC
		public int IndexOf(Constraint constraint)
		{
			if (constraint != null)
			{
				int count = this.Count;
				for (int i = 0; i < count; i++)
				{
					if (constraint == (Constraint)this.List[i])
					{
						return i;
					}
				}
			}
			return -1;
		}

		// Token: 0x06000819 RID: 2073 RVA: 0x00057718 File Offset: 0x00056B18
		public int IndexOf(string constraintName)
		{
			int num = this.InternalIndexOf(constraintName);
			if (num >= 0)
			{
				return num;
			}
			return -1;
		}

		// Token: 0x0600081A RID: 2074 RVA: 0x00057734 File Offset: 0x00056B34
		internal int InternalIndexOf(string constraintName)
		{
			int num = -1;
			if (constraintName != null && 0 < constraintName.Length)
			{
				int count = this.List.Count;
				for (int i = 0; i < count; i++)
				{
					Constraint constraint = (Constraint)this.List[i];
					int num2 = base.NamesEqual(constraint.ConstraintName, constraintName, false, this.table.Locale);
					if (num2 == 1)
					{
						return i;
					}
					if (num2 == -1)
					{
						num = ((num == -1) ? i : -2);
					}
				}
			}
			return num;
		}

		// Token: 0x0600081B RID: 2075 RVA: 0x000577AC File Offset: 0x00056BAC
		private string MakeName(int index)
		{
			if (1 == index)
			{
				return "Constraint1";
			}
			return "Constraint" + index.ToString(CultureInfo.InvariantCulture);
		}

		// Token: 0x0600081C RID: 2076 RVA: 0x000577DC File Offset: 0x00056BDC
		private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
		{
			if (this.onCollectionChanged != null)
			{
				this.onCollectionChanged(this, ccevent);
			}
		}

		// Token: 0x0600081D RID: 2077 RVA: 0x00057800 File Offset: 0x00056C00
		internal void RegisterName(string name)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (base.NamesEqual(name, ((Constraint)this.List[i]).ConstraintName, true, this.table.Locale) != 0)
				{
					throw ExceptionBuilder.DuplicateConstraintName(((Constraint)this.List[i]).ConstraintName);
				}
			}
			if (base.NamesEqual(name, this.MakeName(this.defaultNameIndex), true, this.table.Locale) != 0)
			{
				this.defaultNameIndex++;
			}
		}

		// Token: 0x0600081E RID: 2078 RVA: 0x0005789C File Offset: 0x00056C9C
		public void Remove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.CanRemove(constraint, true))
			{
				this.BaseRemove(constraint);
				this.ArrayRemove(constraint);
				if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).IsPrimaryKey)
				{
					this.Table.PrimaryKey = null;
				}
				this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, constraint));
			}
		}

		// Token: 0x0600081F RID: 2079 RVA: 0x00057900 File Offset: 0x00056D00
		public void RemoveAt(int index)
		{
			Constraint constraint = this[index];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
			this.Remove(constraint);
		}

		// Token: 0x06000820 RID: 2080 RVA: 0x00057928 File Offset: 0x00056D28
		public void Remove(string name)
		{
			Constraint constraint = this[name];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintNotInTheTable(name);
			}
			this.Remove(constraint);
		}

		// Token: 0x06000821 RID: 2081 RVA: 0x00057950 File Offset: 0x00056D50
		internal void UnregisterName(string name)
		{
			if (base.NamesEqual(name, this.MakeName(this.defaultNameIndex - 1), true, this.table.Locale) != 0)
			{
				do
				{
					this.defaultNameIndex--;
				}
				while (this.defaultNameIndex > 1 && !this.Contains(this.MakeName(this.defaultNameIndex - 1)));
			}
		}

		// Token: 0x06000822 RID: 2082 RVA: 0x000579B0 File Offset: 0x00056DB0
		internal void FinishInitConstraints()
		{
			if (this.delayLoadingConstraints == null)
			{
				return;
			}
			for (int i = 0; i < this.delayLoadingConstraints.Length; i++)
			{
				if (this.delayLoadingConstraints[i] is UniqueConstraint)
				{
					if (!this.fLoadForeignKeyConstraintsOnly)
					{
						UniqueConstraint uniqueConstraint = (UniqueConstraint)this.delayLoadingConstraints[i];
						if (uniqueConstraint.columnNames == null)
						{
							this.Add(uniqueConstraint);
						}
						else
						{
							int num = uniqueConstraint.columnNames.Length;
							DataColumn[] array = new DataColumn[num];
							for (int j = 0; j < num; j++)
							{
								array[j] = this.table.Columns[uniqueConstraint.columnNames[j]];
							}
							if (uniqueConstraint.bPrimaryKey)
							{
								if (this.table.primaryKey != null)
								{
									throw ExceptionBuilder.AddPrimaryKeyConstraint();
								}
								this.Add(uniqueConstraint.ConstraintName, array, true);
							}
							else
							{
								UniqueConstraint constraint = new UniqueConstraint(uniqueConstraint.constraintName, array);
								if (this.FindConstraint(constraint) == null)
								{
									this.Add(constraint);
								}
							}
						}
					}
				}
				else
				{
					ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)this.delayLoadingConstraints[i];
					if (foreignKeyConstraint.parentColumnNames == null || foreignKeyConstraint.childColumnNames == null)
					{
						this.Add(foreignKeyConstraint);
					}
					else if (this.table.DataSet == null)
					{
						this.fLoadForeignKeyConstraintsOnly = true;
					}
					else
					{
						int num = foreignKeyConstraint.parentColumnNames.Length;
						DataColumn[] array = new DataColumn[num];
						DataColumn[] array2 = new DataColumn[num];
						for (int k = 0; k < num; k++)
						{
							if (foreignKeyConstraint.parentTableNamespace == null)
							{
								array[k] = this.table.DataSet.Tables[foreignKeyConstraint.parentTableName].Columns[foreignKeyConstraint.parentColumnNames[k]];
							}
							else
							{
								array[k] = this.table.DataSet.Tables[foreignKeyConstraint.parentTableName, foreignKeyConstraint.parentTableNamespace].Columns[foreignKeyConstraint.parentColumnNames[k]];
							}
							array2[k] = this.table.Columns[foreignKeyConstraint.childColumnNames[k]];
						}
						this.Add(new ForeignKeyConstraint(foreignKeyConstraint.constraintName, array, array2)
						{
							AcceptRejectRule = foreignKeyConstraint.acceptRejectRule,
							DeleteRule = foreignKeyConstraint.deleteRule,
							UpdateRule = foreignKeyConstraint.updateRule
						});
					}
				}
			}
			if (!this.fLoadForeignKeyConstraintsOnly)
			{
				this.delayLoadingConstraints = null;
			}
		}

		// Token: 0x040002E2 RID: 738
		private readonly DataTable table;

		// Token: 0x040002E3 RID: 739
		private readonly ArrayList list = new ArrayList();

		// Token: 0x040002E4 RID: 740
		private int defaultNameIndex = 1;

		// Token: 0x040002E5 RID: 741
		private CollectionChangeEventHandler onCollectionChanged;

		// Token: 0x040002E6 RID: 742
		private Constraint[] delayLoadingConstraints;

		// Token: 0x040002E7 RID: 743
		private bool fLoadForeignKeyConstraintsOnly;
	}
}
