using System;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.ComponentModel.Design.Serialization;
using System.Design;
using System.Drawing;
using System.Windows.Forms.Design.Behavior;

namespace System.Windows.Forms.Design
{
	// Token: 0x02000360 RID: 864
	internal class ToolStripMenuItemDesigner : ToolStripDropDownItemDesigner
	{
		// Token: 0x1700076C RID: 1900
		// (get) Token: 0x0600230B RID: 8971 RVA: 0x000D98AC File Offset: 0x000D7AAC
		public override ICollection AssociatedComponents
		{
			get
			{
				ArrayList arrayList = new ArrayList();
				if (this.MenuItem.DropDown.IsAutoGenerated)
				{
					foreach (object obj in this.MenuItem.DropDownItems)
					{
						ToolStripItem toolStripItem = (ToolStripItem)obj;
						if (!(toolStripItem is DesignerToolStripControlHost))
						{
							arrayList.Add(toolStripItem);
						}
					}
				}
				return arrayList;
			}
		}

		// Token: 0x1700076D RID: 1901
		// (get) Token: 0x0600230C RID: 8972 RVA: 0x000D9934 File Offset: 0x000D7B34
		// (set) Token: 0x0600230D RID: 8973 RVA: 0x000D994B File Offset: 0x000D7B4B
		private bool CheckOnClick
		{
			get
			{
				return (bool)base.ShadowProperties["CheckOnClick"];
			}
			set
			{
				base.ShadowProperties["CheckOnClick"] = value;
			}
		}

		// Token: 0x1700076E RID: 1902
		// (get) Token: 0x0600230E RID: 8974 RVA: 0x000D9963 File Offset: 0x000D7B63
		// (set) Token: 0x0600230F RID: 8975 RVA: 0x000D997A File Offset: 0x000D7B7A
		private bool DoubleClickEnabled
		{
			get
			{
				return (bool)base.ShadowProperties["DoubleClickEnabled"];
			}
			set
			{
				base.ShadowProperties["DoubleClickEnabled"] = value;
			}
		}

		// Token: 0x1700076F RID: 1903
		// (get) Token: 0x06002310 RID: 8976 RVA: 0x000D9992 File Offset: 0x000D7B92
		// (set) Token: 0x06002311 RID: 8977 RVA: 0x000D999C File Offset: 0x000D7B9C
		private ToolStripDropDown DropDown
		{
			get
			{
				return this.customDropDown;
			}
			set
			{
				this.dropDownSetFailed = false;
				if (this.IsParentDropDown(value))
				{
					this.dropDownSetFailed = true;
					throw new ArgumentException(SR.GetString("InvalidArgument", new object[]
					{
						"DropDown",
						value.ToString()
					}));
				}
				if (this.MenuItem.DropDown != null)
				{
					this.RemoveTypeHereNode(this.MenuItem);
					if (this.MenuItem.DropDown.IsAutoGenerated && this.MenuItem.DropDownItems.Count > 0)
					{
						ComponentSerializationService componentSerializationService = this.GetService(typeof(ComponentSerializationService)) as ComponentSerializationService;
						if (componentSerializationService != null)
						{
							this.serializedDataForDropDownItems = componentSerializationService.CreateStore();
							foreach (object obj in this.MenuItem.DropDownItems)
							{
								ToolStripItem toolStripItem = (ToolStripItem)obj;
								if (!(toolStripItem is DesignerToolStripControlHost))
								{
									componentSerializationService.Serialize(this.serializedDataForDropDownItems, toolStripItem);
								}
							}
							this.serializedDataForDropDownItems.Close();
						}
						ToolStripItem[] array = new ToolStripItem[this.MenuItem.DropDownItems.Count];
						this.MenuItem.DropDownItems.CopyTo(array, 0);
						foreach (ToolStripItem toolStripItem2 in array)
						{
							this.MenuItem.DropDownItems.Remove(toolStripItem2);
							this.designerHost.DestroyComponent(toolStripItem2);
						}
					}
					this.MenuItem.HideDropDown();
				}
				this.MenuItem.DropDown = value;
				this.customDropDown = value;
				if (value == null && !this.dropDownSet && this.serializedDataForDropDownItems != null)
				{
					try
					{
						ToolStripDesigner._autoAddNewItems = false;
						this.CreatetypeHereNode();
						ComponentSerializationService componentSerializationService2 = this.GetService(typeof(ComponentSerializationService)) as ComponentSerializationService;
						if (componentSerializationService2 != null)
						{
							componentSerializationService2.Deserialize(this.serializedDataForDropDownItems);
							this.serializedDataForDropDownItems = null;
						}
					}
					finally
					{
						ToolStripDesigner._autoAddNewItems = true;
					}
				}
				this.MenuItem.DropDown.OwnerItem = this.MenuItem;
				this.MenuItem.DropDown.Disposed += this.OnDropDownDisposed;
				if (this.MenuItem.Equals(this.selSvc.PrimarySelection))
				{
					this.InitializeDropDown();
				}
			}
		}

		// Token: 0x17000770 RID: 1904
		// (get) Token: 0x06002312 RID: 8978 RVA: 0x000D9BF8 File Offset: 0x000D7DF8
		// (set) Token: 0x06002313 RID: 8979 RVA: 0x000D9C1E File Offset: 0x000D7E1E
		internal override ToolStripTemplateNode Editor
		{
			get
			{
				if (base.Editor != null)
				{
					return base.Editor;
				}
				if (this.commitedTemplateNode != null)
				{
					return this.commitedTemplateNode;
				}
				return this.typeHereTemplateNode;
			}
			set
			{
				this.commitedTemplateNode = value;
			}
		}

		// Token: 0x17000771 RID: 1905
		// (get) Token: 0x06002314 RID: 8980 RVA: 0x000D9C28 File Offset: 0x000D7E28
		private bool IsOnContextMenu
		{
			get
			{
				ToolStrip mainToolStrip = this.GetMainToolStrip();
				return mainToolStrip == null || mainToolStrip.Site == null || mainToolStrip is ContextMenuStrip;
			}
		}

		// Token: 0x17000772 RID: 1906
		// (get) Token: 0x06002315 RID: 8981 RVA: 0x000D9C52 File Offset: 0x000D7E52
		private ToolStripDropDownItem MenuItem
		{
			get
			{
				return base.ToolStripItem as ToolStripDropDownItem;
			}
		}

		// Token: 0x17000773 RID: 1907
		// (get) Token: 0x06002316 RID: 8982 RVA: 0x000D9C60 File Offset: 0x000D7E60
		private bool MenuItemSelected
		{
			get
			{
				if (this.selSvc != null)
				{
					object obj = this.selSvc.PrimarySelection;
					ToolStripItem toolStripItem;
					if (obj == null)
					{
						if (this.KeyboardHandlingService != null)
						{
							obj = this.KeyboardHandlingService.SelectedDesignerControl;
						}
						toolStripItem = (obj as ToolStripItem);
					}
					else
					{
						toolStripItem = (obj as ToolStripItem);
					}
					if (toolStripItem != null)
					{
						if (this.designerHost != null)
						{
							ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
							if (toolStripItemDesigner != null && toolStripItemDesigner.dummyItemAdded)
							{
								return toolStripItem == this.MenuItem;
							}
						}
						if (toolStripItem.IsOnDropDown && toolStripItem.Owner is ToolStripDropDown)
						{
							ToolStripDropDownItem toolStripDropDownItem = ((ToolStripDropDown)toolStripItem.Owner).OwnerItem as ToolStripDropDownItem;
							return toolStripDropDownItem == this.MenuItem;
						}
						return toolStripItem == this.MenuItem;
					}
					else if (obj is ContextMenuStrip && ((ContextMenuStrip)obj).OwnerItem == base.Component && this.MenuItem.DropDown == obj)
					{
						return true;
					}
				}
				return false;
			}
		}

		// Token: 0x17000774 RID: 1908
		// (get) Token: 0x06002317 RID: 8983 RVA: 0x000D9D4A File Offset: 0x000D7F4A
		private ToolStripKeyboardHandlingService KeyboardHandlingService
		{
			get
			{
				if (this.keyboardHandlingService == null)
				{
					this.keyboardHandlingService = (this.GetService(typeof(ToolStripKeyboardHandlingService)) as ToolStripKeyboardHandlingService);
				}
				return this.keyboardHandlingService;
			}
		}

		// Token: 0x17000775 RID: 1909
		// (get) Token: 0x06002318 RID: 8984 RVA: 0x000D9D78 File Offset: 0x000D7F78
		protected override IComponent ParentComponent
		{
			get
			{
				if (base.ToolStripItem != null)
				{
					if (!base.ToolStripItem.IsOnOverflow && base.ToolStripItem.IsOnDropDown)
					{
						ToolStripDropDown toolStripDropDown = this.MenuItem.Owner as ToolStripDropDown;
						if (toolStripDropDown != null)
						{
							if (toolStripDropDown.IsAutoGenerated)
							{
								return toolStripDropDown.OwnerItem;
							}
							return toolStripDropDown;
						}
					}
					return base.ParentComponent;
				}
				return null;
			}
		}

		// Token: 0x06002319 RID: 8985 RVA: 0x000D9DD4 File Offset: 0x000D7FD4
		internal void AddNewTemplateNode(ToolStripDropDown dropDown)
		{
			foreach (object obj in dropDown.Items)
			{
				ToolStripItem toolStripItem = (ToolStripItem)obj;
				if (toolStripItem is DesignerToolStripControlHost)
				{
					this.typeHereNode = (DesignerToolStripControlHost)toolStripItem;
				}
			}
			if (this.typeHereNode != null)
			{
				dropDown.Items.Remove(this.typeHereNode);
			}
			this.typeHereTemplateNode = new ToolStripTemplateNode(base.Component, SR.GetString("ToolStripDesignerTemplateNodeEnterText"), null);
			int width = this.typeHereTemplateNode.EditorToolStrip.Width;
			this.typeHereNode = new DesignerToolStripControlHost(this.typeHereTemplateNode.EditorToolStrip);
			this.typeHereTemplateNode.ControlHost = this.typeHereNode;
			this.typeHereNode.AutoSize = false;
			this.typeHereNode.Width = width;
			dropDown.Items.Add(this.typeHereNode);
		}

		// Token: 0x0600231A RID: 8986 RVA: 0x000D9ED4 File Offset: 0x000D80D4
		internal void AddItemBodyGlyph(ToolStripItem item)
		{
			if (item != null)
			{
				ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripItemDesigner != null)
				{
					Rectangle glyphBounds = toolStripItemDesigner.GetGlyphBounds();
					Behavior b = new ToolStripItemBehavior();
					ToolStripItemGlyph toolStripItemGlyph = new ToolStripItemGlyph(item, toolStripItemDesigner, glyphBounds, b);
					toolStripItemDesigner.bodyGlyph = toolStripItemGlyph;
					if (this.toolStripAdornerWindowService != null)
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Insert(0, toolStripItemGlyph);
					}
				}
			}
		}

		// Token: 0x0600231B RID: 8987 RVA: 0x000D9F38 File Offset: 0x000D8138
		private void AddBodyGlyphs(ToolStripDropDownItem item)
		{
			if (item != null)
			{
				ToolStripMenuItemDesigner toolStripMenuItemDesigner = (ToolStripMenuItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripMenuItemDesigner != null)
				{
					foreach (object obj in item.DropDownItems)
					{
						ToolStripItem item2 = (ToolStripItem)obj;
						this.AddItemBodyGlyph(item2);
					}
				}
			}
		}

		// Token: 0x0600231C RID: 8988 RVA: 0x000D9FAC File Offset: 0x000D81AC
		internal override void CommitEdit(Type type, string text, bool commit, bool enterKeyPressed, bool tabKeyPressed)
		{
			base.IsEditorActive = false;
			if (!(this.MenuItem.Owner is ToolStripDropDown) && base.Editor != null)
			{
				base.CommitEdit(type, text, commit, enterKeyPressed, tabKeyPressed);
				return;
			}
			if (commit)
			{
				int num = -1;
				bool dummyItemAdded = this.dummyItemAdded;
				this.dummyItemAdded = false;
				this.MenuItem.DropDown.SuspendLayout();
				if (this.commitedEditorNode != null)
				{
					num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
					ToolStripItem toolStripItem = this.MenuItem.DropDownItems[num + 1];
					this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
					if (this.commitedTemplateNode != null)
					{
						this.commitedTemplateNode.CloseEditor();
						this.commitedTemplateNode = null;
					}
					if (this.commitedEditorNode != null)
					{
						this.commitedEditorNode.Dispose();
						this.commitedEditorNode = null;
					}
					if (text == "-")
					{
						ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
						if (toolStripItemDesigner == null)
						{
							goto IL_28C;
						}
						try
						{
							toolStripItem = toolStripItemDesigner.MorphCurrentItem(typeof(ToolStripSeparator));
							this.RemoveItemBodyGlyph(toolStripItem);
							goto IL_28C;
						}
						catch
						{
							if (this.newMenuItemTransaction != null)
							{
								try
								{
									this.newMenuItemTransaction.Cancel();
								}
								catch
								{
								}
								this.newMenuItemTransaction = null;
							}
							goto IL_28C;
						}
						finally
						{
							if (this.newMenuItemTransaction != null)
							{
								this.newMenuItemTransaction.Commit();
								this.newMenuItemTransaction = null;
							}
						}
					}
					if (dummyItemAdded)
					{
						try
						{
							this.dummyItemAdded = true;
							this.CreateNewItem(type, num, text);
							this.designerHost.DestroyComponent(toolStripItem);
							if (enterKeyPressed)
							{
								this.typeHereNode.SelectControl();
							}
							goto IL_28C;
						}
						catch
						{
							if (this.newMenuItemTransaction != null)
							{
								try
								{
									this.newMenuItemTransaction.Cancel();
								}
								catch
								{
								}
								this.newMenuItemTransaction = null;
							}
							goto IL_28C;
						}
						finally
						{
							if (this.newMenuItemTransaction != null)
							{
								this.newMenuItemTransaction.Commit();
								this.newMenuItemTransaction = null;
							}
							this.dummyItemAdded = false;
						}
					}
					toolStripItem.Visible = true;
					DesignerTransaction designerTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripItemPropertyChangeTransaction"));
					try
					{
						PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(toolStripItem)["Text"];
						string b = (string)propertyDescriptor.GetValue(toolStripItem);
						if (propertyDescriptor != null && text != b)
						{
							propertyDescriptor.SetValue(toolStripItem, text);
						}
						goto IL_28C;
					}
					catch
					{
						if (designerTransaction != null)
						{
							designerTransaction.Cancel();
							designerTransaction = null;
						}
						goto IL_28C;
					}
					finally
					{
						if (designerTransaction != null)
						{
							designerTransaction.Commit();
							designerTransaction = null;
						}
					}
				}
				num = this.MenuItem.DropDownItems.IndexOf(this.typeHereNode);
				try
				{
					this.dummyItemAdded = true;
					this.CreateNewItem(type, num, text);
				}
				finally
				{
					this.dummyItemAdded = false;
				}
				this.typeHereNode.SelectControl();
				IL_28C:
				this.MenuItem.DropDown.ResumeLayout(true);
				this.MenuItem.DropDown.PerformLayout();
				this.ResetGlyphs(this.MenuItem);
				if (this.selSvc != null)
				{
					if (enterKeyPressed)
					{
						ToolStripItem toolStripItem2;
						if ((this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight) && num >= 1)
						{
							toolStripItem2 = this.MenuItem.DropDownItems[num - 1];
						}
						else
						{
							toolStripItem2 = this.MenuItem.DropDownItems[num + 1];
						}
						if (this.KeyboardHandlingService != null)
						{
							if (toolStripItem2 != null)
							{
								ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDownItems[num] as ToolStripDropDownItem;
								if (toolStripDropDownItem != null)
								{
									toolStripDropDownItem.HideDropDown();
								}
							}
							if (toolStripItem2 == this.typeHereNode)
							{
								this.KeyboardHandlingService.SelectedDesignerControl = toolStripItem2;
								this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
								return;
							}
							this.KeyboardHandlingService.SelectedDesignerControl = null;
							this.selSvc.SetSelectedComponents(new object[]
							{
								toolStripItem2
							});
							return;
						}
					}
					else if (tabKeyPressed)
					{
						this.selSvc.SetSelectedComponents(new object[]
						{
							this.MenuItem.DropDownItems[num]
						}, SelectionTypes.Replace);
						return;
					}
				}
			}
			else if (this.commitedEditorNode != null)
			{
				this.MenuItem.DropDown.SuspendLayout();
				bool flag = this.dummyItemAdded;
				this.dummyItemAdded = false;
				int num2 = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				ToolStripItem toolStripItem3 = this.MenuItem.DropDownItems[num2 + 1];
				this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
				toolStripItem3.Visible = true;
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
				if (flag)
				{
					this.MenuItem.DropDownItems.Remove(toolStripItem3);
					try
					{
						this.designerHost.DestroyComponent(toolStripItem3);
					}
					catch
					{
						if (this.newMenuItemTransaction != null)
						{
							try
							{
								this.newMenuItemTransaction.Cancel();
							}
							catch
							{
							}
							this.newMenuItemTransaction = null;
						}
					}
					toolStripItem3 = null;
				}
				this.MenuItem.DropDown.ResumeLayout();
				if (toolStripItem3 != null)
				{
					this.AddItemBodyGlyph(toolStripItem3);
				}
				if (flag)
				{
					SelectionManager selectionManager = (SelectionManager)this.GetService(typeof(SelectionManager));
					selectionManager.NeedRefresh = false;
					if (this.newMenuItemTransaction != null)
					{
						try
						{
							this.dummyItemAdded = true;
							this.newMenuItemTransaction.Cancel();
							this.newMenuItemTransaction = null;
							if (this.MenuItem.DropDownItems.Count == 0)
							{
								this.CreatetypeHereNode();
							}
						}
						finally
						{
							this.dummyItemAdded = false;
						}
					}
					flag = false;
				}
				this.MenuItem.DropDown.PerformLayout();
			}
		}

		// Token: 0x0600231D RID: 8989 RVA: 0x000DA59C File Offset: 0x000D879C
		private void CreatetypeHereNode()
		{
			if (this.typeHereNode == null)
			{
				this.AddNewTemplateNode(this.MenuItem.DropDown);
				if (this.MenuItem.DropDown.Site == null)
				{
					this.MenuItem.DropDown.Text = this.MenuItem.Name + ".DropDown";
				}
			}
			else if (this.typeHereNode != null && this.MenuItem.DropDownItems.IndexOf(this.typeHereNode) == -1)
			{
				this.MenuItem.DropDown.Items.Add(this.typeHereNode);
				this.typeHereNode.Visible = true;
			}
			this.MenuItem.DropDown.PerformLayout();
		}

		// Token: 0x0600231E RID: 8990 RVA: 0x000DA654 File Offset: 0x000D8854
		private void CreateDummyMenuItem(ToolStripItem item, string text, Image image)
		{
			this.commitedTemplateNode = new ToolStripTemplateNode(base.Component, text, image);
			this.commitedTemplateNode.ActiveItem = item;
			int width = this.commitedTemplateNode.EditorToolStrip.Width;
			this.commitedEditorNode = new DesignerToolStripControlHost(this.commitedTemplateNode.EditorToolStrip);
			this.commitedEditorNode.AutoSize = false;
			this.commitedEditorNode.Width = width;
		}

		// Token: 0x0600231F RID: 8991 RVA: 0x000DA6C0 File Offset: 0x000D88C0
		private ToolStripItem CreateDummyItem(Type t, int dummyIndex)
		{
			if (this.designerHost == null)
			{
				return null;
			}
			ToolStripItem toolStripItem = null;
			if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
			{
				dummyIndex++;
			}
			try
			{
				ToolStripDesigner._autoAddNewItems = false;
				this.indexToInsertNewItem = dummyIndex;
				try
				{
					if (this.newMenuItemTransaction == null)
					{
						this.newMenuItemTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripCreatingNewItemTransaction"));
					}
					this.fireComponentChanged = true;
					toolStripItem = (ToolStripItem)this.designerHost.CreateComponent(t);
				}
				finally
				{
					this.fireComponentChanged = false;
				}
				ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
				try
				{
					toolStripItemDesigner.InternalCreate = true;
					if (toolStripItemDesigner != null)
					{
						toolStripItemDesigner.InitializeNewComponent(null);
					}
				}
				finally
				{
					toolStripItemDesigner.InternalCreate = false;
				}
			}
			catch (InvalidOperationException ex)
			{
				this.CommitInsertTransaction(false);
				if (this.newMenuItemTransaction != null)
				{
					this.newMenuItemTransaction.Cancel();
					this.newMenuItemTransaction = null;
				}
				IUIService iuiservice = (IUIService)this.GetService(typeof(IUIService));
				iuiservice.ShowError(ex.Message);
			}
			finally
			{
				ToolStripDesigner._autoAddNewItems = true;
				this.indexToInsertNewItem = -1;
			}
			return toolStripItem;
		}

		// Token: 0x06002320 RID: 8992 RVA: 0x000DA808 File Offset: 0x000D8A08
		private ToolStripItem CreateNewItem(Type t, int dummyIndex, string newText)
		{
			if (this.designerHost == null)
			{
				return null;
			}
			ToolStripItem toolStripItem = null;
			if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
			{
				dummyIndex++;
			}
			DesignerTransaction designerTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripCreatingNewItemTransaction"));
			try
			{
				ToolStripDesigner._autoAddNewItems = false;
				this.indexToInsertNewItem = dummyIndex;
				try
				{
					this.fireComponentChanged = true;
					toolStripItem = (ToolStripItem)this.designerHost.CreateComponent(t, ToolStripDesigner.NameFromText(newText, t, this.MenuItem.Site));
				}
				finally
				{
					this.fireComponentChanged = false;
				}
				ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
				try
				{
					if (!string.IsNullOrEmpty(newText) || this.addingDummyItem)
					{
						toolStripItemDesigner.InternalCreate = true;
					}
					if (toolStripItemDesigner != null)
					{
						toolStripItemDesigner.InitializeNewComponent(null);
					}
				}
				finally
				{
					toolStripItemDesigner.InternalCreate = false;
				}
				if (toolStripItem != null)
				{
					PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(toolStripItem)["Text"];
					if (propertyDescriptor != null && !string.IsNullOrEmpty(newText))
					{
						propertyDescriptor.SetValue(toolStripItem, newText);
					}
				}
			}
			catch
			{
				this.CommitInsertTransaction(false);
				if (designerTransaction != null)
				{
					designerTransaction.Cancel();
					designerTransaction = null;
				}
			}
			finally
			{
				if (designerTransaction != null)
				{
					designerTransaction.Commit();
					designerTransaction = null;
				}
				ToolStripDesigner._autoAddNewItems = true;
				this.indexToInsertNewItem = -1;
			}
			return toolStripItem;
		}

		// Token: 0x06002321 RID: 8993 RVA: 0x000DA964 File Offset: 0x000D8B64
		private bool CheckSameOwner(ToolStripDropDownItem lastSelected, ToolStripDropDownItem currentSelected)
		{
			if (lastSelected != null && currentSelected != null && lastSelected.Owner is ToolStripDropDown && currentSelected.Owner is ToolStripDropDown)
			{
				ToolStripItem ownerItem = ((ToolStripDropDown)lastSelected.Owner).OwnerItem;
				ToolStripItem ownerItem2 = ((ToolStripDropDown)currentSelected.Owner).OwnerItem;
				return ownerItem == ownerItem2;
			}
			return false;
		}

		// Token: 0x06002322 RID: 8994 RVA: 0x000DA9BC File Offset: 0x000D8BBC
		internal void Commit()
		{
			if (this.commitedTemplateNode != null && this.commitedTemplateNode.Active)
			{
				int num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				this.commitedTemplateNode.Commit(false, false);
				if (num != -1 && this.MenuItem.DropDownItems.Count > num)
				{
					ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDownItems[num] as ToolStripDropDownItem;
					if (toolStripDropDownItem != null)
					{
						toolStripDropDownItem.HideDropDown();
					}
				}
			}
			else if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.Commit(false, false);
			}
			ToolStripDropDownItem toolStripDropDownItem2 = this.MenuItem;
			while (toolStripDropDownItem2 != null && toolStripDropDownItem2.Owner is ToolStripDropDown)
			{
				toolStripDropDownItem2 = (ToolStripDropDownItem)((ToolStripDropDown)toolStripDropDownItem2.Owner).OwnerItem;
				if (toolStripDropDownItem2 != null)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = (ToolStripMenuItemDesigner)this.designerHost.GetDesigner(toolStripDropDownItem2);
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.Commit();
					}
				}
			}
		}

		// Token: 0x06002323 RID: 8995 RVA: 0x000DAAAC File Offset: 0x000D8CAC
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (this.selSvc != null)
				{
					this.selSvc.SelectionChanged -= this.OnSelectionChanged;
				}
				if (this.undoEngine != null)
				{
					this.undoEngine.Undoing -= this.OnUndoing;
					this.undoEngine.Undone -= this.OnUndone;
				}
				if (this.MenuItem != null && this.MenuItem.HasDropDown)
				{
					this.MenuItem.DropDown.Hide();
					this.UnHookEvents();
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService = null;
				}
				IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
				if (componentChangeService != null)
				{
					componentChangeService.ComponentRemoved -= this.ComponentChangeSvc_ComponentRemoved;
					componentChangeService.ComponentRemoving -= this.ComponentChangeSvc_ComponentRemoving;
					componentChangeService.ComponentAdding -= this.ComponentChangeSvc_ComponentAdding;
					componentChangeService.ComponentAdded -= this.ComponentChangeSvc_ComponentAdded;
				}
				if (this.typeHereTemplateNode != null)
				{
					this.typeHereTemplateNode.RollBack();
					this.typeHereTemplateNode.CloseEditor();
					this.typeHereTemplateNode = null;
				}
				if (this.typeHereNode != null)
				{
					this.typeHereNode.Dispose();
					this.typeHereNode = null;
				}
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.RollBack();
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
				if (this.parentItem != null)
				{
					this.parentItem = null;
				}
			}
			base.Dispose(disposing);
		}

		// Token: 0x06002324 RID: 8996 RVA: 0x000DAC43 File Offset: 0x000D8E43
		private void DropDownClick(object sender, EventArgs e)
		{
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.TemplateNodeActive)
			{
				this.KeyboardHandlingService.ActiveTemplateNode.CommitAndSelect();
			}
		}

		// Token: 0x06002325 RID: 8997 RVA: 0x000DAC6C File Offset: 0x000D8E6C
		private void DropDownPaint(object sender, PaintEventArgs e)
		{
			if (this.selSvc != null && this.MenuItem != null)
			{
				foreach (object obj in this.MenuItem.DropDownItems)
				{
					ToolStripItem toolStripItem = (ToolStripItem)obj;
					if (toolStripItem.Visible && this.selSvc.GetComponentSelected(toolStripItem))
					{
						ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
						if (toolStripItemDesigner != null)
						{
							Rectangle glyphBounds = toolStripItemDesigner.GetGlyphBounds();
							ToolStripDesignerUtils.GetAdjustedBounds(toolStripItem, ref glyphBounds);
							glyphBounds.Inflate(2, 2);
							BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
							if (behaviorService != null)
							{
								behaviorService.ProcessPaintMessage(glyphBounds);
							}
						}
					}
					DesignerToolStripControlHost designerToolStripControlHost = toolStripItem as DesignerToolStripControlHost;
					if (designerToolStripControlHost != null)
					{
						designerToolStripControlHost.Control.Refresh();
					}
				}
			}
		}

		// Token: 0x06002326 RID: 8998 RVA: 0x000DAD60 File Offset: 0x000D8F60
		private void DropDownLocationChanged(object sender, EventArgs e)
		{
			ToolStripDropDown toolStripDropDown = sender as ToolStripDropDown;
			if (toolStripDropDown.Visible)
			{
				BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
				if (behaviorService != null)
				{
					behaviorService.Invalidate();
				}
			}
		}

		// Token: 0x06002327 RID: 8999 RVA: 0x000DAD9C File Offset: 0x000D8F9C
		private void DropDownItem_DropDownOpening(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (this.toolStripAdornerWindowService != null)
			{
				toolStripDropDownItem.DropDown.TopLevel = false;
				toolStripDropDownItem.DropDown.Parent = this.toolStripAdornerWindowService.ToolStripAdornerWindowControl;
			}
		}

		// Token: 0x06002328 RID: 9000 RVA: 0x000DADDC File Offset: 0x000D8FDC
		private void DropDownItem_DropDownOpened(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (toolStripDropDownItem != null)
			{
				this.ResetGlyphs(toolStripDropDownItem);
			}
			Control dropDown = toolStripDropDownItem.DropDown;
			if (dropDown != null)
			{
				ControlDesigner controlDesigner = this.designerHost.GetDesigner(this.designerHost.RootComponent) as ControlDesigner;
				if (controlDesigner != null)
				{
					this.rootControlGlyph = new ToolStripMenuItemDesigner.ToolStripDropDownGlyph(dropDown.Bounds, new ToolStripMenuItemDesigner.DropDownBehavior(controlDesigner, this));
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Add(this.rootControlGlyph);
				}
			}
		}

		// Token: 0x06002329 RID: 9001 RVA: 0x000DAE60 File Offset: 0x000D9060
		private void DropDownItem_DropDownClosed(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (toolStripDropDownItem != null)
			{
				if (this.toolStripAdornerWindowService != null && this.rootControlGlyph != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(this.rootControlGlyph))
				{
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(this.rootControlGlyph);
				}
				this.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
				this.initialized = false;
				this.UnHookEvents();
				if (toolStripDropDownItem.DropDown.Site != null || toolStripDropDownItem.DropDownItems.Count == 1)
				{
					this.RemoveTypeHereNode(toolStripDropDownItem);
					return;
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService.Invalidate(toolStripDropDownItem.DropDown.Bounds);
				}
			}
		}

		// Token: 0x0600232A RID: 9002 RVA: 0x000DAF18 File Offset: 0x000D9118
		private void DropDownResize(object sender, EventArgs e)
		{
			ToolStripDropDown toolStripDropDown = sender as ToolStripDropDown;
			if (!this.dummyItemAdded)
			{
				if (toolStripDropDown != null && toolStripDropDown.Visible && this.toolStripAdornerWindowService != null && (toolStripDropDown.Width < this.dropDownSizeToInvalidate.Width || toolStripDropDown.Size.Height < this.dropDownSizeToInvalidate.Height))
				{
					using (Region region = new Region(this.dropDownSizeToInvalidate))
					{
						region.Exclude(toolStripDropDown.Bounds);
						this.toolStripAdornerWindowService.Invalidate(region);
						BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
						if (behaviorService != null)
						{
							behaviorService.Invalidate(region);
						}
					}
				}
				if (this.toolStripAdornerWindowService != null)
				{
					if (this.rootControlGlyph != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(this.rootControlGlyph))
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(this.rootControlGlyph);
					}
					ControlDesigner controlDesigner = this.designerHost.GetDesigner(this.designerHost.RootComponent) as ControlDesigner;
					if (controlDesigner != null)
					{
						this.rootControlGlyph = new ToolStripMenuItemDesigner.ToolStripDropDownGlyph(toolStripDropDown.Bounds, new ToolStripMenuItemDesigner.DropDownBehavior(controlDesigner, this));
					}
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Add(this.rootControlGlyph);
				}
			}
			this.dropDownSizeToInvalidate = toolStripDropDown.Bounds;
		}

		// Token: 0x0600232B RID: 9003 RVA: 0x000DB08C File Offset: 0x000D928C
		internal void EditTemplateNode(bool clicked)
		{
			if (this.typeHereNode == null)
			{
				return;
			}
			this.typeHereNode.RefreshSelectionGlyph();
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.TemplateNodeActive)
			{
				this.KeyboardHandlingService.ActiveTemplateNode.CommitAndSelect();
			}
			if (clicked && this.MenuItem == null)
			{
				return;
			}
			try
			{
				ToolStripDesigner.editTemplateNode = true;
				this.selSvc.SetSelectedComponents(new object[]
				{
					this.MenuItem
				}, SelectionTypes.Replace);
			}
			finally
			{
				ToolStripDesigner.editTemplateNode = false;
			}
			ToolStripDropDownItem toolStripDropDownItem = null;
			if (this.selSvc.PrimarySelection == null && this.KeyboardHandlingService != null)
			{
				ToolStripItem toolStripItem = this.KeyboardHandlingService.SelectedDesignerControl as ToolStripItem;
				if (toolStripItem != null)
				{
					toolStripDropDownItem = (((ToolStripDropDown)toolStripItem.Owner).OwnerItem as ToolStripDropDownItem);
				}
			}
			else
			{
				toolStripDropDownItem = (this.selSvc.PrimarySelection as ToolStripDropDownItem);
			}
			if (toolStripDropDownItem != null && toolStripDropDownItem != this.MenuItem)
			{
				this.HideSiblingDropDowns(toolStripDropDownItem);
			}
			this.MenuItem.DropDown.SuspendLayout();
			this.dummyItemAdded = true;
			int dummyIndex = this.MenuItem.DropDownItems.IndexOf(this.typeHereNode);
			ToolStripItem toolStripItem2 = null;
			try
			{
				this.addingDummyItem = true;
				toolStripItem2 = this.CreateDummyItem(typeof(ToolStripMenuItem), dummyIndex);
			}
			catch (CheckoutException ex)
			{
				if (!ex.Equals(CheckoutException.Canceled))
				{
					throw;
				}
				this.CommitInsertTransaction(false);
				if (this.newMenuItemTransaction != null)
				{
					this.newMenuItemTransaction.Cancel();
					this.newMenuItemTransaction = null;
				}
			}
			finally
			{
				this.dummyItemAdded = (toolStripItem2 != null);
				this.addingDummyItem = false;
			}
			this.MenuItem.DropDown.ResumeLayout();
			if (toolStripItem2 != null)
			{
				ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(toolStripItem2) as ToolStripMenuItemDesigner;
				if (toolStripMenuItemDesigner != null)
				{
					toolStripMenuItemDesigner.InitializeDropDown();
					toolStripMenuItemDesigner.ShowEditNode(clicked);
				}
			}
		}

		// Token: 0x0600232C RID: 9004 RVA: 0x000DB268 File Offset: 0x000D9468
		private void EnterInSituMode()
		{
			if (this.MenuItem.Owner is ToolStripDropDown)
			{
				ToolStripItem ownerItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
				if (this.designerHost != null)
				{
					IDesigner designer = this.designerHost.GetDesigner(ownerItem);
					if (designer is ToolStripMenuItemDesigner)
					{
						this.MenuItem.HideDropDown();
						((ToolStripMenuItemDesigner)designer).EnterInSituEdit(this.MenuItem);
					}
				}
			}
		}

		// Token: 0x0600232D RID: 9005 RVA: 0x000DB2D8 File Offset: 0x000D94D8
		internal void EnterInSituEdit(ToolStripItem toolItem)
		{
			this.MenuItem.DropDown.SuspendLayout();
			this.RemoveItemBodyGlyph(toolItem);
			if (toolItem == null)
			{
				return;
			}
			if (base.IsEditorActive)
			{
				return;
			}
			this.CreateDummyMenuItem(toolItem, toolItem.Text, toolItem.Image);
			int index = this.MenuItem.DropDownItems.IndexOf(toolItem);
			this.MenuItem.DropDownItems.Insert(index, this.commitedEditorNode);
			if (toolItem is ToolStripControlHost)
			{
				((ToolStripControlHost)toolItem).Control.Visible = false;
			}
			toolItem.Visible = false;
			this.MenuItem.DropDown.ResumeLayout();
			if (this.commitedTemplateNode != null)
			{
				this.commitedTemplateNode.FocusEditor(toolItem);
			}
			ToolStripDropDownItem toolStripDropDownItem = toolItem as ToolStripDropDownItem;
			if (!(toolStripDropDownItem.Owner is ToolStripDropDownMenu) && toolStripDropDownItem != null && toolStripDropDownItem.Bounds.Width < this.commitedEditorNode.Bounds.Width)
			{
				toolStripDropDownItem.Width = this.commitedEditorNode.Width;
				toolStripDropDownItem.DropDown.Location = new Point(toolStripDropDownItem.DropDown.Location.X + this.commitedEditorNode.Bounds.Width - toolStripDropDownItem.Bounds.Width, toolStripDropDownItem.DropDown.Location.Y);
			}
			base.IsEditorActive = true;
		}

		// Token: 0x0600232E RID: 9006 RVA: 0x000DB43C File Offset: 0x000D963C
		private int GetItemInsertionIndex(ToolStripDropDown wb, Point ownerClientAreaRelativeDropPoint)
		{
			for (int i = 0; i < wb.Items.Count; i++)
			{
				Rectangle bounds = wb.Items[i].Bounds;
				bounds.Inflate(wb.Items[i].Margin.Size);
				if (bounds.Contains(ownerClientAreaRelativeDropPoint))
				{
					return wb.Items.IndexOf(wb.Items[i]);
				}
			}
			return -1;
		}

		// Token: 0x0600232F RID: 9007 RVA: 0x000DB4B4 File Offset: 0x000D96B4
		protected override Component GetOwnerForActionList()
		{
			return this.MenuItem;
		}

		// Token: 0x06002330 RID: 9008 RVA: 0x000DB4BC File Offset: 0x000D96BC
		internal override ToolStrip GetMainToolStrip()
		{
			ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
			ToolStripItem toolStripItem = (firstDropDown == null) ? null : firstDropDown.OwnerItem;
			if (toolStripItem != null)
			{
				return toolStripItem.Owner;
			}
			return this.MenuItem.Owner;
		}

		// Token: 0x06002331 RID: 9009 RVA: 0x000DB4F8 File Offset: 0x000D96F8
		private void HideAllDropDowns(ToolStripDropDownItem item)
		{
			try
			{
				if (this.MenuItem.Owner is ToolStripDropDown)
				{
					ToolStripItem ownerItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
					while (item != ownerItem)
					{
						if (item.DropDown.Visible)
						{
							item.HideDropDown();
						}
						if (!(item.Owner is ToolStripDropDown))
						{
							break;
						}
						item = (ToolStripDropDownItem)((ToolStripDropDown)item.Owner).OwnerItem;
					}
				}
			}
			catch (Exception ex)
			{
				if (ClientUtils.IsCriticalException(ex))
				{
					throw;
				}
			}
		}

		// Token: 0x06002332 RID: 9010 RVA: 0x000DB590 File Offset: 0x000D9790
		private void HideSiblingDropDowns(ToolStripDropDownItem item)
		{
			try
			{
				ToolStripItem menuItem = this.MenuItem;
				while (item != menuItem)
				{
					item.HideDropDown();
					if (!(item.Owner is ToolStripDropDown))
					{
						break;
					}
					item = (ToolStripDropDownItem)((ToolStripDropDown)item.Owner).OwnerItem;
				}
			}
			catch (Exception ex)
			{
				if (ClientUtils.IsCriticalException(ex))
				{
					throw;
				}
			}
		}

		// Token: 0x06002333 RID: 9011 RVA: 0x000DB5F8 File Offset: 0x000D97F8
		internal void HookEvents()
		{
			if (this.MenuItem != null)
			{
				this.MenuItem.DropDown.Closing += this.OnDropDownClosing;
				this.MenuItem.DropDownOpening += this.DropDownItem_DropDownOpening;
				this.MenuItem.DropDownOpened += this.DropDownItem_DropDownOpened;
				this.MenuItem.DropDownClosed += this.DropDownItem_DropDownClosed;
				this.MenuItem.DropDown.Resize += this.DropDownResize;
				this.MenuItem.DropDown.ItemAdded += this.OnItemAdded;
				this.MenuItem.DropDown.Paint += this.DropDownPaint;
				this.MenuItem.DropDown.Click += this.DropDownClick;
				this.MenuItem.DropDown.LocationChanged += this.DropDownLocationChanged;
			}
		}

		// Token: 0x06002334 RID: 9012 RVA: 0x000DB700 File Offset: 0x000D9900
		public override void Initialize(IComponent component)
		{
			base.Initialize(component);
			base.Visible = true;
			this.DoubleClickEnabled = this.MenuItem.DoubleClickEnabled;
			this.selSvc = (ISelectionService)this.GetService(typeof(ISelectionService));
			if (this.selSvc != null)
			{
				this.selSvc.SelectionChanged += this.OnSelectionChanged;
			}
			this.toolStripAdornerWindowService = (ToolStripAdornerWindowService)this.GetService(typeof(ToolStripAdornerWindowService));
			this.designerHost = (IDesignerHost)this.GetService(typeof(IDesignerHost));
			this.MenuItem.DoubleClickEnabled = true;
			IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
			if (componentChangeService != null)
			{
				componentChangeService.ComponentRemoved += this.ComponentChangeSvc_ComponentRemoved;
				componentChangeService.ComponentRemoving += this.ComponentChangeSvc_ComponentRemoving;
				componentChangeService.ComponentAdding += this.ComponentChangeSvc_ComponentAdding;
				componentChangeService.ComponentAdded += this.ComponentChangeSvc_ComponentAdded;
			}
			if (this.undoEngine == null)
			{
				this.undoEngine = (this.GetService(typeof(UndoEngine)) as UndoEngine);
				if (this.undoEngine != null)
				{
					this.undoEngine.Undoing += this.OnUndoing;
					this.undoEngine.Undone += this.OnUndone;
				}
			}
		}

		// Token: 0x06002335 RID: 9013 RVA: 0x000DB862 File Offset: 0x000D9A62
		internal void InitializeBodyGlyphsForItems(bool addGlyphs, ToolStripDropDownItem item)
		{
			if (addGlyphs)
			{
				this.AddBodyGlyphs(item);
				return;
			}
			this.RemoveBodyGlyphs(item);
		}

		// Token: 0x06002336 RID: 9014 RVA: 0x000DB878 File Offset: 0x000D9A78
		internal void InitializeDropDown()
		{
			ToolStrip mainToolStrip = this.GetMainToolStrip();
			ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
			if (firstDropDown != null)
			{
				ToolStripItem ownerItem = firstDropDown.OwnerItem;
				if (ownerItem != null && ownerItem.GetCurrentParent() is ToolStripOverflow && !mainToolStrip.CanOverflow)
				{
					return;
				}
			}
			if (!this.initialized)
			{
				this.initialized = true;
				ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDown.OwnerItem as ToolStripDropDownItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem != this.MenuItem)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(toolStripDropDownItem) as ToolStripMenuItemDesigner;
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.RemoveTypeHereNode(toolStripDropDownItem);
					}
					toolStripDropDownItem.HideDropDown();
				}
				if (this.MenuItem.DropDown.Site != null)
				{
					ToolStripDropDownDesigner toolStripDropDownDesigner = this.designerHost.GetDesigner(this.MenuItem.DropDown) as ToolStripDropDownDesigner;
					if (toolStripDropDownDesigner != null)
					{
						toolStripDropDownDesigner.currentParent = (this.MenuItem as ToolStripMenuItem);
					}
				}
				this.CreatetypeHereNode();
				this.MenuItem.DropDown.TopLevel = false;
				this.MenuItem.DropDown.AllowDrop = true;
				this.HookEvents();
				this.MenuItem.DropDown.AutoClose = false;
				this.MenuItem.ShowDropDown();
				this.ShowOwnerDropDown(this.MenuItem);
				this.ResetGlyphs(this.MenuItem);
				if (!this.IsOnContextMenu && !this.dummyItemAdded)
				{
					SelectionManager selectionManager = (SelectionManager)this.GetService(typeof(SelectionManager));
					if (selectionManager != null)
					{
						selectionManager.Refresh();
					}
				}
				BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
				if (behaviorService != null)
				{
					behaviorService.Invalidate(this.MenuItem.Owner.Bounds);
				}
			}
		}

		// Token: 0x06002337 RID: 9015 RVA: 0x000DBA20 File Offset: 0x000D9C20
		private bool IsParentDropDown(ToolStripDropDown currentDropDown)
		{
			if (currentDropDown != null)
			{
				ToolStripDropDown toolStripDropDown = this.MenuItem.Owner as ToolStripDropDown;
				while (toolStripDropDown != null && toolStripDropDown != currentDropDown)
				{
					ToolStripDropDownItem toolStripDropDownItem = toolStripDropDown.OwnerItem as ToolStripDropDownItem;
					if (toolStripDropDownItem != null)
					{
						toolStripDropDown = (toolStripDropDownItem.Owner as ToolStripDropDown);
					}
					else
					{
						toolStripDropDown = null;
					}
				}
				return toolStripDropDown != null;
			}
			return false;
		}

		// Token: 0x06002338 RID: 9016 RVA: 0x000DBA74 File Offset: 0x000D9C74
		internal override ToolStripItem MorphCurrentItem(Type t)
		{
			Rectangle bounds = this.MenuItem.GetCurrentParent().Bounds;
			Rectangle bounds2 = this.MenuItem.DropDown.Bounds;
			this.InitializeBodyGlyphsForItems(false, this.MenuItem);
			Rectangle rect = Rectangle.Union(bounds, bounds2);
			ToolStripAdornerWindowService toolStripAdornerWindowService = this.toolStripAdornerWindowService;
			ToolStripItem result = base.MorphCurrentItem(t);
			if (toolStripAdornerWindowService != null)
			{
				toolStripAdornerWindowService.Invalidate(rect);
			}
			return result;
		}

		// Token: 0x06002339 RID: 9017 RVA: 0x000DBAD8 File Offset: 0x000D9CD8
		private void ComponentChangeSvc_ComponentAdded(object sender, ComponentEventArgs e)
		{
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
			if (toolStripItem != null && this.componentAddingFired && (this.MenuItemSelected || this.fireComponentChanged))
			{
				this.componentAddingFired = false;
				try
				{
					if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
					{
						if (componentChangeService != null)
						{
							MemberDescriptor member = TypeDescriptor.GetProperties(this.MenuItem.DropDown)["Items"];
							componentChangeService.OnComponentChanging(this.MenuItem.DropDown, member);
						}
					}
					else
					{
						base.RaiseComponentChanging(TypeDescriptor.GetProperties(this.MenuItem)["DropDownItems"]);
					}
					int count = this.MenuItem.DropDownItems.Count;
					if (this.indexToInsertNewItem != -1)
					{
						if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
						{
							this.MenuItem.DropDown.Items.Insert(this.indexToInsertNewItem, toolStripItem);
						}
						else
						{
							this.MenuItem.DropDownItems.Insert(this.indexToInsertNewItem, toolStripItem);
						}
					}
					else
					{
						ToolStripItem toolStripItem2 = this.selSvc.PrimarySelection as ToolStripItem;
						if (toolStripItem2 != null && toolStripItem2 != this.MenuItem)
						{
							int num = this.MenuItem.DropDownItems.IndexOf(toolStripItem2);
							if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
							{
								if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
								{
									this.MenuItem.DropDown.Items.Insert(num + 1, toolStripItem);
								}
								else
								{
									this.MenuItem.DropDownItems.Insert(num + 1, toolStripItem);
								}
							}
							else if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
							{
								this.MenuItem.DropDown.Items.Insert(num, toolStripItem);
							}
							else
							{
								this.MenuItem.DropDownItems.Insert(num, toolStripItem);
							}
						}
						else if (count > 0)
						{
							if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight)
							{
								if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
								{
									this.MenuItem.DropDown.Items.Insert(count - 1, toolStripItem);
								}
								else
								{
									this.MenuItem.DropDownItems.Insert(count - 1, toolStripItem);
								}
							}
						}
						else if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
						{
							this.MenuItem.DropDown.Items.Add(toolStripItem);
						}
						else
						{
							this.MenuItem.DropDownItems.Add(toolStripItem);
						}
					}
					if (this.undoingCalled && this.selSvc != null)
					{
						this.selSvc.SetSelectedComponents(new IComponent[]
						{
							toolStripItem
						}, SelectionTypes.Replace);
					}
					this.ResetGlyphs(this.MenuItem);
				}
				catch
				{
					this.CommitInsertTransaction(false);
				}
				finally
				{
					if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
					{
						if (componentChangeService != null)
						{
							MemberDescriptor member2 = TypeDescriptor.GetProperties(this.MenuItem.DropDown)["Items"];
							componentChangeService.OnComponentChanged(this.MenuItem.DropDown, member2, null, null);
						}
					}
					else
					{
						base.RaiseComponentChanged(TypeDescriptor.GetProperties(this.MenuItem)["DropDownItems"], null, null);
					}
					this.CommitInsertTransaction(true);
				}
			}
		}

		// Token: 0x0600233A RID: 9018 RVA: 0x000DBEA0 File Offset: 0x000DA0A0
		private void CommitInsertTransaction(bool commit)
		{
			if (!this.IsOnContextMenu)
			{
				ToolStrip mainToolStrip = this.GetMainToolStrip();
				ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
				if (toolStripDesigner != null && toolStripDesigner.InsertTansaction != null)
				{
					if (commit)
					{
						toolStripDesigner.InsertTansaction.Commit();
					}
					else
					{
						toolStripDesigner.InsertTansaction.Cancel();
					}
					toolStripDesigner.InsertTansaction = null;
					return;
				}
			}
			else if (this.insertMenuItemTransaction != null)
			{
				if (commit)
				{
					this.insertMenuItemTransaction.Commit();
				}
				else
				{
					this.insertMenuItemTransaction.Cancel();
				}
				this.insertMenuItemTransaction = null;
			}
		}

		// Token: 0x0600233B RID: 9019 RVA: 0x000DBF28 File Offset: 0x000DA128
		private void ComponentChangeSvc_ComponentAdding(object sender, ComponentEventArgs e)
		{
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.CopyInProgress)
			{
				return;
			}
			if (e.Component is ToolStripItem && (this.MenuItemSelected || this.fireComponentChanged))
			{
				if (!this.IsOnContextMenu)
				{
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null && !toolStripDesigner.EditingCollection && toolStripDesigner.InsertTansaction == null)
					{
						this.componentAddingFired = true;
						toolStripDesigner.InsertTansaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripInsertingIntoDropDownTransaction"));
						return;
					}
				}
				else
				{
					ToolStripItem toolStripItem = e.Component as ToolStripItem;
					if (toolStripItem != null && toolStripItem.Owner == null)
					{
						this.componentAddingFired = true;
						this.insertMenuItemTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripInsertingIntoDropDownTransaction"));
					}
				}
			}
		}

		// Token: 0x0600233C RID: 9020 RVA: 0x000DC000 File Offset: 0x000DA200
		private void ComponentChangeSvc_ComponentRemoved(object sender, ComponentEventArgs e)
		{
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			if (toolStripItem != null && toolStripItem.IsOnDropDown)
			{
				ToolStripDropDown toolStripDropDown = toolStripItem.Owner as ToolStripDropDown;
				if (toolStripDropDown != null)
				{
					ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)((ToolStripDropDown)toolStripItem.Owner).OwnerItem;
					if (toolStripDropDownItem != null && toolStripDropDownItem == this.MenuItem)
					{
						int num = toolStripDropDownItem.DropDownItems.IndexOf(toolStripItem);
						try
						{
							if (num != -1)
							{
								toolStripDropDownItem.DropDownItems.Remove(toolStripItem);
								base.RaiseComponentChanged(TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
							}
						}
						finally
						{
							if (this._pendingTransaction != null)
							{
								this._pendingTransaction.Commit();
								this._pendingTransaction = null;
							}
						}
						this.ResetGlyphs(toolStripDropDownItem);
						if (toolStripDropDownItem.DropDownItems.Count > 1)
						{
							num = Math.Min(toolStripDropDownItem.DropDownItems.Count - 1, num);
							num = Math.Max(0, num);
						}
						else
						{
							num = -1;
						}
						if (this.toolStripAdornerWindowService != null && this.boundsToInvalidateOnRemove != Rectangle.Empty)
						{
							using (Region region = new Region(this.boundsToInvalidateOnRemove))
							{
								region.Exclude(this.MenuItem.DropDown.Bounds);
								this.toolStripAdornerWindowService.Invalidate(region);
								this.boundsToInvalidateOnRemove = Rectangle.Empty;
							}
						}
						if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.CutOrDeleteInProgress && this.selSvc != null && !this.dummyItemAdded)
						{
							IComponent component2;
							if (num != -1)
							{
								IComponent component = toolStripDropDownItem.DropDownItems[num];
								component2 = component;
							}
							else
							{
								IComponent component = toolStripDropDownItem;
								component2 = component;
							}
							IComponent component3 = component2;
							if (component3 is DesignerToolStripControlHost)
							{
								this.KeyboardHandlingService.SelectedDesignerControl = component3;
								this.KeyboardHandlingService.OwnerItemAfterCut = this.MenuItem;
								this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
								return;
							}
							this.selSvc.SetSelectedComponents(new IComponent[]
							{
								component3
							}, SelectionTypes.Replace);
						}
					}
				}
			}
		}

		// Token: 0x0600233D RID: 9021 RVA: 0x000DC1FC File Offset: 0x000DA3FC
		private void ComponentChangeSvc_ComponentRemoving(object sender, ComponentEventArgs e)
		{
			if (this.dummyItemAdded)
			{
				return;
			}
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			if (toolStripItem != null && toolStripItem.IsOnDropDown && toolStripItem.Placement == ToolStripItemPlacement.Main)
			{
				ToolStripDropDown toolStripDropDown = toolStripItem.Owner as ToolStripDropDown;
				if (toolStripDropDown != null)
				{
					ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)((ToolStripDropDown)toolStripItem.Owner).OwnerItem;
					if (toolStripDropDownItem != null && toolStripDropDownItem == this.MenuItem)
					{
						this.RemoveItemBodyGlyph(toolStripItem);
						this.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
						this.boundsToInvalidateOnRemove = toolStripDropDownItem.DropDown.Bounds;
						ToolStripDropDownItem toolStripDropDownItem2 = toolStripItem as ToolStripDropDownItem;
						if (toolStripDropDownItem2 != null)
						{
							this.boundsToInvalidateOnRemove = Rectangle.Union(this.boundsToInvalidateOnRemove, toolStripDropDownItem2.DropDown.Bounds);
						}
						try
						{
							this._pendingTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripDesignerTransactionRemovingItem"));
							base.RaiseComponentChanging(TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
						}
						catch
						{
							if (this._pendingTransaction != null)
							{
								this._pendingTransaction.Cancel();
								this._pendingTransaction = null;
							}
						}
					}
				}
			}
		}

		// Token: 0x0600233E RID: 9022 RVA: 0x000D0D27 File Offset: 0x000CEF27
		private void OnDropDownClosing(object sender, ToolStripDropDownClosingEventArgs e)
		{
			e.Cancel = (e.CloseReason == ToolStripDropDownCloseReason.ItemClicked);
		}

		// Token: 0x0600233F RID: 9023 RVA: 0x000DC31C File Offset: 0x000DA51C
		private void OnDropDownDisposed(object sender, EventArgs e)
		{
			if (this.MenuItem != null)
			{
				if (this.MenuItem.DropDown != null)
				{
					this.MenuItem.DropDown.Disposed -= this.OnDropDownDisposed;
				}
				this.MenuItem.DropDown = null;
			}
		}

		// Token: 0x06002340 RID: 9024 RVA: 0x000DC35C File Offset: 0x000DA55C
		private void OnItemAdded(object sender, ToolStripItemEventArgs e)
		{
			if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight && this.typeHereNode != null && e.Item != this.typeHereNode)
			{
				int num = this.MenuItem.DropDown.Items.IndexOf(this.typeHereNode);
				if (num >= 0 && num < this.MenuItem.DropDown.Items.Count - 1)
				{
					this.MenuItem.DropDown.ItemAdded -= this.OnItemAdded;
					this.MenuItem.DropDown.SuspendLayout();
					this.MenuItem.DropDown.Items.Remove(this.typeHereNode);
					this.MenuItem.DropDown.Items.Add(this.typeHereNode);
					this.MenuItem.DropDown.ResumeLayout();
					this.MenuItem.DropDown.ItemAdded += this.OnItemAdded;
					return;
				}
				this.CreatetypeHereNode();
			}
		}

		// Token: 0x06002341 RID: 9025 RVA: 0x000DC47C File Offset: 0x000DA67C
		private void OnUndone(object source, EventArgs e)
		{
			if (this.undoingCalled)
			{
				if (this.dropDownSet && this.MenuItem.DropDown.IsAutoGenerated)
				{
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null && toolStripDesigner.CacheItems)
					{
						foreach (object obj in toolStripDesigner.Items)
						{
							ToolStripItem value = (ToolStripItem)obj;
							this.MenuItem.DropDownItems.Insert(0, value);
						}
						toolStripDesigner.CacheItems = false;
					}
					this.ResetGlyphs(this.MenuItem);
				}
				if (this.MenuItem != null && this.selSvc.GetComponentSelected(this.MenuItem))
				{
					this.InitializeDropDown();
					this.MenuItem.DropDown.PerformLayout();
				}
				this.undoingCalled = false;
				this.dropDownSet = false;
			}
			if (this.selSvc.GetComponentSelected(this.MenuItem) && !this.dropDownSetFailed)
			{
				this.InitializeDropDown();
			}
		}

		// Token: 0x06002342 RID: 9026 RVA: 0x000DC5A8 File Offset: 0x000DA7A8
		private void OnUndoing(object source, EventArgs e)
		{
			if (this.dummyItemAdded)
			{
				return;
			}
			if (!this.IsOnContextMenu && this.MenuItem.DropDown.Visible)
			{
				this.MenuItem.HideDropDown();
				if (!this.MenuItem.DropDown.IsAutoGenerated)
				{
					this.dropDownSet = true;
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null)
					{
						toolStripDesigner.CacheItems = true;
						toolStripDesigner.Items.Clear();
					}
				}
				this.undoingCalled = true;
			}
		}

		// Token: 0x06002343 RID: 9027 RVA: 0x000DC634 File Offset: 0x000DA834
		private void OnSelectionChanged(object sender, EventArgs e)
		{
			if (this.MenuItem == null)
			{
				return;
			}
			ISelectionService selectionService = sender as ISelectionService;
			if (selectionService == null)
			{
				return;
			}
			if (this.commitedTemplateNode != null && this.commitedTemplateNode.Active)
			{
				this.commitedTemplateNode.Commit(false, false);
			}
			else if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.Commit(false, false);
			}
			if (this.MenuItem.Equals(selectionService.PrimarySelection))
			{
				ArrayList arrayList = ToolStripDesignerUtils.originalSelComps;
				if (arrayList != null)
				{
					ToolStripDesignerUtils.InvalidateSelection(arrayList, this.MenuItem, this.MenuItem.Site, false);
				}
				if (this.IsOnContextMenu && !this.MenuItem.Owner.Visible)
				{
					ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
					ToolStripDropDownDesigner toolStripDropDownDesigner = this.designerHost.GetDesigner(firstDropDown) as ToolStripDropDownDesigner;
					if (toolStripDropDownDesigner != null)
					{
						this.InitializeDropDown();
						toolStripDropDownDesigner.ShowMenu();
						toolStripDropDownDesigner.AddSelectionGlyphs();
					}
				}
				else
				{
					this.InitializeDropDown();
				}
				ICollection c = null;
				if (this.selSvc != null)
				{
					c = selectionService.GetSelectedComponents();
				}
				arrayList = new ArrayList(c);
				if (arrayList.Count == 0 && this.KeyboardHandlingService != null && this.KeyboardHandlingService.SelectedDesignerControl != null)
				{
					arrayList.Add(this.KeyboardHandlingService.SelectedDesignerControl);
				}
				if (arrayList.Count > 0)
				{
					ToolStripDesignerUtils.originalSelComps = arrayList;
					return;
				}
			}
			else
			{
				object obj = ((ISelectionService)sender).PrimarySelection;
				if (obj == null && this.KeyboardHandlingService != null)
				{
					obj = this.KeyboardHandlingService.SelectedDesignerControl;
				}
				ToolStripItem toolStripItem = obj as ToolStripItem;
				if (toolStripItem != null)
				{
					for (ToolStripDropDown toolStripDropDown = toolStripItem.Owner as ToolStripDropDown; toolStripDropDown != null; toolStripDropDown = (toolStripDropDown.OwnerItem.Owner as ToolStripDropDown))
					{
						if (toolStripDropDown.OwnerItem == this.MenuItem || toolStripDropDown.OwnerItem == null)
						{
							return;
						}
					}
				}
				if (this.MenuItem.DropDown.Visible)
				{
					ToolStripDropDown toolStripDropDown2 = obj as ToolStripDropDown;
					if (toolStripDropDown2 != null && this.MenuItem.DropDown == toolStripDropDown2)
					{
						return;
					}
					ToolStripItem toolStripItem2 = obj as ToolStripItem;
					if (toolStripItem2 != null)
					{
						for (ToolStripDropDown toolStripDropDown3 = toolStripItem2.Owner as ToolStripDropDown; toolStripDropDown3 != null; toolStripDropDown3 = (toolStripDropDown3.OwnerItem.Owner as ToolStripDropDown))
						{
							if (toolStripDropDown3 == this.MenuItem.DropDown)
							{
								return;
							}
						}
					}
					if (this.MenuItem.DropDown.OwnerItem == this.MenuItem)
					{
						this.MenuItem.HideDropDown();
					}
				}
			}
		}

		// Token: 0x06002344 RID: 9028 RVA: 0x000DC894 File Offset: 0x000DAA94
		protected override void PreFilterProperties(IDictionary properties)
		{
			base.PreFilterProperties(properties);
			string[] array = new string[]
			{
				"Visible",
				"DoubleClickEnabled",
				"CheckOnClick",
				"DropDown"
			};
			Attribute[] attributes = new Attribute[0];
			for (int i = 0; i < array.Length; i++)
			{
				PropertyDescriptor propertyDescriptor = (PropertyDescriptor)properties[array[i]];
				if (propertyDescriptor != null)
				{
					properties[array[i]] = TypeDescriptor.CreateProperty(typeof(ToolStripMenuItemDesigner), propertyDescriptor, attributes);
				}
			}
		}

		// Token: 0x06002345 RID: 9029 RVA: 0x000DC910 File Offset: 0x000DAB10
		private void ResetDoubleClickEnabled()
		{
			this.DoubleClickEnabled = false;
		}

		// Token: 0x06002346 RID: 9030 RVA: 0x000DC919 File Offset: 0x000DAB19
		private void ResetCheckOnClick()
		{
			this.CheckOnClick = false;
		}

		// Token: 0x06002347 RID: 9031 RVA: 0x000DC922 File Offset: 0x000DAB22
		private void ResetDropDown()
		{
			this.DropDown = null;
		}

		// Token: 0x06002348 RID: 9032 RVA: 0x000D660D File Offset: 0x000D480D
		private void ResetVisible()
		{
			base.Visible = true;
		}

		// Token: 0x06002349 RID: 9033 RVA: 0x000DC92B File Offset: 0x000DAB2B
		private void RestoreVisible()
		{
			this.MenuItem.Visible = base.Visible;
		}

		// Token: 0x0600234A RID: 9034 RVA: 0x000DC940 File Offset: 0x000DAB40
		internal void RemoveTypeHereNode(ToolStripDropDownItem ownerItem)
		{
			Rectangle bounds = ownerItem.DropDown.Bounds;
			if (ownerItem.DropDownItems.Count > 0 && ownerItem.DropDownItems[0] is DesignerToolStripControlHost)
			{
				ownerItem.DropDownItems.RemoveAt(0);
			}
			if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.RollBack();
				this.typeHereTemplateNode.CloseEditor();
				this.typeHereTemplateNode = null;
			}
			if (this.typeHereNode != null)
			{
				this.typeHereNode.Dispose();
				this.typeHereNode = null;
			}
			if (this.toolStripAdornerWindowService != null)
			{
				this.toolStripAdornerWindowService.Invalidate(bounds);
			}
		}

		// Token: 0x0600234B RID: 9035 RVA: 0x000DC9E8 File Offset: 0x000DABE8
		private void RollBack()
		{
			if (this.commitedEditorNode != null)
			{
				int num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)this.MenuItem.DropDownItems[num + 1];
				if (toolStripDropDownItem != null)
				{
					toolStripDropDownItem.Visible = true;
				}
				this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.RollBack();
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
			}
		}

		// Token: 0x0600234C RID: 9036 RVA: 0x000DCA94 File Offset: 0x000DAC94
		private void RemoveBodyGlyphs(ToolStripDropDownItem item)
		{
			if (item != null)
			{
				foreach (object obj in item.DropDownItems)
				{
					ToolStripItem component = (ToolStripItem)obj;
					ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(component);
					if (toolStripItemDesigner != null)
					{
						ControlBodyGlyph bodyGlyph = toolStripItemDesigner.bodyGlyph;
						if (bodyGlyph != null && this.toolStripAdornerWindowService != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(bodyGlyph))
						{
							this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(bodyGlyph);
							toolStripItemDesigner.bodyGlyph = null;
						}
					}
				}
			}
		}

		// Token: 0x0600234D RID: 9037 RVA: 0x000DCB4C File Offset: 0x000DAD4C
		internal void RemoveItemBodyGlyph(ToolStripItem item)
		{
			if (item != null)
			{
				ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripItemDesigner != null)
				{
					ControlBodyGlyph bodyGlyph = toolStripItemDesigner.bodyGlyph;
					if (bodyGlyph != null && this.toolStripAdornerWindowService != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(bodyGlyph))
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(bodyGlyph);
						toolStripItemDesigner.bodyGlyph = null;
					}
				}
			}
		}

		// Token: 0x0600234E RID: 9038 RVA: 0x000DCBB8 File Offset: 0x000DADB8
		internal void ResetGlyphs(ToolStripDropDownItem item)
		{
			if (item.DropDown.Visible)
			{
				this.InitializeBodyGlyphsForItems(false, item);
				this.InitializeBodyGlyphsForItems(true, item);
			}
		}

		// Token: 0x0600234F RID: 9039 RVA: 0x000DCBD8 File Offset: 0x000DADD8
		internal override bool SetSelection(bool enterKeyPressed)
		{
			if (enterKeyPressed)
			{
				if (!this.initialized)
				{
					this.InitializeDropDown();
				}
				if (this.selSvc != null && this.KeyboardHandlingService != null)
				{
					int num = 0;
					if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight)
					{
						num = this.MenuItem.DropDownItems.Count;
						num--;
					}
					this.selSvc.SetSelectedComponents(new object[]
					{
						this.MenuItem
					}, SelectionTypes.Replace);
					if (num >= 0)
					{
						this.KeyboardHandlingService.SelectedDesignerControl = this.MenuItem.DropDownItems[num];
						this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
					}
				}
				return true;
			}
			return false;
		}

		// Token: 0x06002350 RID: 9040 RVA: 0x000D9963 File Offset: 0x000D7B63
		private bool ShouldSerializeDoubleClickEnabled()
		{
			return (bool)base.ShadowProperties["DoubleClickEnabled"];
		}

		// Token: 0x06002351 RID: 9041 RVA: 0x000D9934 File Offset: 0x000D7B34
		private bool ShouldSerializeCheckOnClick()
		{
			return (bool)base.ShadowProperties["CheckOnClick"];
		}

		// Token: 0x06002352 RID: 9042 RVA: 0x000DCC89 File Offset: 0x000DAE89
		private bool ShouldSerializeDropDown()
		{
			return this.customDropDown != null;
		}

		// Token: 0x06002353 RID: 9043 RVA: 0x000D6804 File Offset: 0x000D4A04
		private bool ShouldSerializeVisible()
		{
			return !base.Visible;
		}

		// Token: 0x06002354 RID: 9044 RVA: 0x000DCC94 File Offset: 0x000DAE94
		internal override void ShowEditNode(bool clicked)
		{
			if (this.MenuItem == null)
			{
				return;
			}
			try
			{
				if (this.MenuItem.Owner is ToolStripDropDown)
				{
					this.parentItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
					if (this.designerHost != null)
					{
						IDesigner designer = this.designerHost.GetDesigner(this.parentItem);
						if (designer is ToolStripMenuItemDesigner)
						{
							((ToolStripMenuItemDesigner)designer).EnterInSituEdit(this.MenuItem);
						}
					}
				}
				else
				{
					base.ShowEditNode(clicked);
				}
			}
			catch (CheckoutException ex)
			{
				if (!ex.Equals(CheckoutException.Canceled))
				{
					throw;
				}
			}
		}

		// Token: 0x06002355 RID: 9045 RVA: 0x000DCD38 File Offset: 0x000DAF38
		private void SelectItems(ToolStripDropDownItem oldSelection, ISelectionService selSvc)
		{
			ToolStripDropDown toolStripDropDown = (ToolStripDropDown)this.MenuItem.Owner;
			int num = Math.Max(toolStripDropDown.Items.IndexOf(oldSelection), toolStripDropDown.Items.IndexOf(this.MenuItem));
			int i = Math.Min(toolStripDropDown.Items.IndexOf(oldSelection), toolStripDropDown.Items.IndexOf(this.MenuItem));
			ToolStripItem[] array = new ToolStripItem[num - i + 1];
			int num2 = 0;
			while (i <= num)
			{
				array[num2] = toolStripDropDown.Items[i];
				num2++;
				i++;
			}
			selSvc.SetSelectedComponents(array);
		}

		// Token: 0x06002356 RID: 9046 RVA: 0x000DCDD4 File Offset: 0x000DAFD4
		internal void ShowOwnerDropDown(ToolStripDropDownItem currentSelection)
		{
			while (currentSelection != null && currentSelection.Owner is ToolStripDropDown)
			{
				ToolStripDropDown toolStripDropDown = (ToolStripDropDown)currentSelection.Owner;
				currentSelection = (ToolStripDropDownItem)toolStripDropDown.OwnerItem;
				if (currentSelection != null && !currentSelection.DropDown.Visible)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(currentSelection) as ToolStripMenuItemDesigner;
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.InitializeDropDown();
					}
				}
				else if (toolStripDropDown is ContextMenuStrip && !toolStripDropDown.Visible)
				{
					ToolStripDropDownDesigner toolStripDropDownDesigner = (ToolStripDropDownDesigner)this.designerHost.GetDesigner(toolStripDropDown);
					if (toolStripDropDownDesigner != null)
					{
						toolStripDropDownDesigner.ShowMenu(null);
					}
				}
			}
		}

		// Token: 0x06002357 RID: 9047 RVA: 0x000DCE68 File Offset: 0x000DB068
		internal void UnHookEvents()
		{
			if (this.MenuItem != null)
			{
				this.MenuItem.DropDown.Closing -= this.OnDropDownClosing;
				this.MenuItem.DropDownOpening -= this.DropDownItem_DropDownOpening;
				this.MenuItem.DropDownOpened -= this.DropDownItem_DropDownOpened;
				this.MenuItem.DropDownClosed -= this.DropDownItem_DropDownClosed;
				this.MenuItem.DropDown.Resize -= this.DropDownResize;
				this.MenuItem.DropDown.ItemAdded -= this.OnItemAdded;
				this.MenuItem.DropDown.Paint -= this.DropDownPaint;
				this.MenuItem.DropDown.LocationChanged -= this.DropDownLocationChanged;
				this.MenuItem.DropDown.Click -= this.DropDownClick;
			}
		}

		// Token: 0x040019E5 RID: 6629
		private const int GLYPHINSET = 2;

		// Token: 0x040019E6 RID: 6630
		private DesignerToolStripControlHost typeHereNode;

		// Token: 0x040019E7 RID: 6631
		private ToolStripTemplateNode typeHereTemplateNode;

		// Token: 0x040019E8 RID: 6632
		private DesignerToolStripControlHost commitedEditorNode;

		// Token: 0x040019E9 RID: 6633
		private ToolStripTemplateNode commitedTemplateNode;

		// Token: 0x040019EA RID: 6634
		private IDesignerHost designerHost;

		// Token: 0x040019EB RID: 6635
		private ToolStripItem parentItem;

		// Token: 0x040019EC RID: 6636
		private ToolStripAdornerWindowService toolStripAdornerWindowService;

		// Token: 0x040019ED RID: 6637
		private ToolStripKeyboardHandlingService keyboardHandlingService;

		// Token: 0x040019EE RID: 6638
		private ISelectionService selSvc;

		// Token: 0x040019EF RID: 6639
		private DesignerTransaction _pendingTransaction;

		// Token: 0x040019F0 RID: 6640
		private bool fireComponentChanged;

		// Token: 0x040019F1 RID: 6641
		private bool componentAddingFired;

		// Token: 0x040019F2 RID: 6642
		private int indexToInsertNewItem = -1;

		// Token: 0x040019F3 RID: 6643
		private DesignerTransaction insertMenuItemTransaction;

		// Token: 0x040019F4 RID: 6644
		private DesignerTransaction newMenuItemTransaction;

		// Token: 0x040019F5 RID: 6645
		private Rectangle dropDownSizeToInvalidate = Rectangle.Empty;

		// Token: 0x040019F6 RID: 6646
		private Rectangle boundsToInvalidateOnRemove = Rectangle.Empty;

		// Token: 0x040019F7 RID: 6647
		private ToolStripMenuItemDesigner.ToolStripDropDownGlyph rootControlGlyph;

		// Token: 0x040019F8 RID: 6648
		private bool initialized;

		// Token: 0x040019F9 RID: 6649
		private UndoEngine undoEngine;

		// Token: 0x040019FA RID: 6650
		private bool undoingCalled;

		// Token: 0x040019FB RID: 6651
		private bool addingDummyItem;

		// Token: 0x040019FC RID: 6652
		private ToolStripDropDown customDropDown;

		// Token: 0x040019FD RID: 6653
		private bool dropDownSet;

		// Token: 0x040019FE RID: 6654
		private SerializationStore serializedDataForDropDownItems;

		// Token: 0x040019FF RID: 6655
		private bool dropDownSetFailed;

		// Token: 0x0200059B RID: 1435
		internal class ToolStripDropDownGlyph : Glyph
		{
			// Token: 0x06003351 RID: 13137 RVA: 0x00118526 File Offset: 0x00116726
			internal ToolStripDropDownGlyph(Rectangle bounds, Behavior b) : base(b)
			{
				this._bounds = bounds;
			}

			// Token: 0x06003352 RID: 13138 RVA: 0x00118536 File Offset: 0x00116736
			public override Cursor GetHitTest(Point p)
			{
				if (this._bounds.Contains(p))
				{
					return Cursors.Default;
				}
				return null;
			}

			// Token: 0x06003353 RID: 13139 RVA: 0x00003937 File Offset: 0x00001B37
			public override void Paint(PaintEventArgs pe)
			{
			}

			// Token: 0x0400225E RID: 8798
			private Rectangle _bounds;
		}

		// Token: 0x0200059C RID: 1436
		internal class DropDownBehavior : ControlDesigner.TransparentBehavior
		{
			// Token: 0x06003354 RID: 13140 RVA: 0x0011854D File Offset: 0x0011674D
			internal DropDownBehavior(ControlDesigner designer, ToolStripMenuItemDesigner menuItemDesigner) : base(designer)
			{
				this.menuItemDesigner = menuItemDesigner;
			}

			// Token: 0x06003355 RID: 13141 RVA: 0x00118560 File Offset: 0x00116760
			public override void OnDragEnter(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					e.Effect = ((Control.ModifierKeys == Keys.Control) ? DragDropEffects.Copy : DragDropEffects.Move);
					return;
				}
				base.OnDragEnter(g, e);
			}

			// Token: 0x06003356 RID: 13142 RVA: 0x0011859C File Offset: 0x0011679C
			public override void OnDragOver(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					e.Effect = ((Control.ModifierKeys == Keys.Control) ? DragDropEffects.Copy : DragDropEffects.Move);
					return;
				}
				base.OnDragOver(g, e);
			}

			// Token: 0x06003357 RID: 13143 RVA: 0x001185D8 File Offset: 0x001167D8
			public override void OnDragDrop(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					ToolStripItem toolStripItem = toolStripItemDataObject.PrimarySelection;
					IDesignerHost designerHost = (IDesignerHost)toolStripItem.Site.GetService(typeof(IDesignerHost));
					ToolStripDropDown toolStripDropDown = toolStripItem.GetCurrentParent() as ToolStripDropDown;
					ToolStripDropDownItem toolStripDropDownItem = null;
					if (toolStripDropDown != null)
					{
						toolStripDropDownItem = (toolStripDropDown.OwnerItem as ToolStripDropDownItem);
					}
					if (toolStripDropDownItem != null && designerHost != null)
					{
						ArrayList arrayList = toolStripItemDataObject.DragComponents;
						int num = -1;
						bool flag = e.Effect == DragDropEffects.Copy;
						string @string;
						if (arrayList.Count == 1)
						{
							string text = TypeDescriptor.GetComponentName(arrayList[0]);
							if (text == null || text.Length == 0)
							{
								text = arrayList[0].GetType().Name;
							}
							@string = SR.GetString(flag ? "BehaviorServiceCopyControl" : "BehaviorServiceMoveControl", new object[]
							{
								text
							});
						}
						else
						{
							@string = SR.GetString(flag ? "BehaviorServiceCopyControls" : "BehaviorServiceMoveControls", new object[]
							{
								arrayList.Count
							});
						}
						DesignerTransaction designerTransaction = designerHost.CreateTransaction(@string);
						try
						{
							IComponentChangeService componentChangeService = (IComponentChangeService)toolStripItem.Site.GetService(typeof(IComponentChangeService));
							if (componentChangeService != null)
							{
								componentChangeService.OnComponentChanging(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
							}
							if (flag)
							{
								if (toolStripItem != null)
								{
									num = arrayList.IndexOf(toolStripItem);
								}
								ToolStripKeyboardHandlingService toolStripKeyboardHandlingService = (ToolStripKeyboardHandlingService)toolStripItem.Site.GetService(typeof(ToolStripKeyboardHandlingService));
								if (toolStripKeyboardHandlingService != null)
								{
									toolStripKeyboardHandlingService.CopyInProgress = true;
								}
								arrayList = (DesignerUtils.CopyDragObjects(arrayList, toolStripItem.Site) as ArrayList);
								if (toolStripKeyboardHandlingService != null)
								{
									toolStripKeyboardHandlingService.CopyInProgress = false;
								}
								if (num != -1)
								{
									toolStripItem = (arrayList[num] as ToolStripItem);
								}
							}
							if (e.Effect == DragDropEffects.Move || flag)
							{
								foreach (object obj in arrayList)
								{
									ToolStripItem value = (ToolStripItem)obj;
									toolStripDropDown.Items.Add(value);
								}
								ToolStripDropDownItem toolStripDropDownItem2 = toolStripItem as ToolStripDropDownItem;
								if (toolStripDropDownItem2 != null)
								{
									ToolStripMenuItemDesigner toolStripMenuItemDesigner = designerHost.GetDesigner(toolStripDropDownItem2) as ToolStripMenuItemDesigner;
									if (toolStripMenuItemDesigner != null)
									{
										toolStripMenuItemDesigner.InitializeDropDown();
									}
								}
								this.menuItemDesigner.selSvc.SetSelectedComponents(new IComponent[]
								{
									toolStripItem
								}, SelectionTypes.Replace | SelectionTypes.Click);
							}
							if (componentChangeService != null)
							{
								componentChangeService.OnComponentChanged(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
							}
							if (flag && componentChangeService != null)
							{
								componentChangeService.OnComponentChanging(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
								componentChangeService.OnComponentChanged(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
							}
							if (toolStripDropDownItem != null)
							{
								ToolStripMenuItemDesigner toolStripMenuItemDesigner2 = designerHost.GetDesigner(toolStripDropDownItem) as ToolStripMenuItemDesigner;
								if (toolStripMenuItemDesigner2 != null)
								{
									toolStripMenuItemDesigner2.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
									toolStripMenuItemDesigner2.InitializeBodyGlyphsForItems(true, toolStripDropDownItem);
								}
							}
							BehaviorService behaviorService = (BehaviorService)toolStripItem.Site.GetService(typeof(BehaviorService));
							if (behaviorService != null)
							{
								behaviorService.SyncSelection();
							}
						}
						catch
						{
							if (designerTransaction != null)
							{
								designerTransaction.Cancel();
								designerTransaction = null;
							}
						}
						finally
						{
							if (designerTransaction != null)
							{
								designerTransaction.Commit();
							}
							designerTransaction = null;
						}
					}
				}
			}

			// Token: 0x0400225F RID: 8799
			private ToolStripMenuItemDesigner menuItemDesigner;
		}
	}
}
