using System;
using System.Collections;
using System.ComponentModel;

namespace System.Windows.Forms.Design
{
	// Token: 0x02000357 RID: 855
	internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner
	{
		// Token: 0x06002267 RID: 8807 RVA: 0x000D3340 File Offset: 0x000D1540
		public override void Initialize(IComponent component)
		{
			base.Initialize(component);
		}

		// Token: 0x1700074A RID: 1866
		// (get) Token: 0x06002268 RID: 8808 RVA: 0x000D334C File Offset: 0x000D154C
		public override ICollection AssociatedComponents
		{
			get
			{
				ToolStripDropDownItem toolStripDropDownItem = base.Component as ToolStripDropDownItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem.DropDown.IsAutoGenerated)
				{
					return toolStripDropDownItem.DropDownItems;
				}
				return base.AssociatedComponents;
			}
		}
	}
}
