(function(b,a){a("kendo.breadcrumb",["kendo.core"],b);
}(function(){var a={id:"breadcrumb",name:"Breadcrumb",category:"web",description:"The Breadcrumb widget displays navigation breadcrumb.",depends:["core"]};
(function(b,r){var o=window.kendo,s=o.ui.Widget,l=b.extend,n=b.isPlainObject,q=b.proxy,g=".kendoBreadcrumb",c="aria-hidden",d="aria-label",j="click",m="focus",e="blur",p="keydown",i="change",k=".";
var h={widget:"k-widget k-breadcrumb",overlay:"k-breadcrumb-container",textbox:"k-textbox",link:"k-breadcrumb-link",item:"k-breadcrumb-item",delimiter:"k-breadcrumb-delimiter-icon",rootItem:"k-breadcrumb-root-item",rootLink:"k-breadcrumb-root-link",overflowIcon:"k-breadcrumb-overflow-icon",focused:"k-state-focused",hidden:"k-hidden",inputWrapper:"k-breadcrumb-input-container"};
var f=s.extend({init:function(t,u){var v=this;
u=u||{};
s.fn.init.call(v,t,u);
v._wrapper();
if(u.editable){v._editable();
v._tabindex();
}v.wrapper.on(j+g,"a:not(.k-state-disabled)",q(v._click,v));
if(u.value||u.bindToLocation||!u.items){v._value();
}else{if(u.items){v.items(u.items);
}}v._resizeHandler=o.onResize(function(){v.resize(true);
});
},options:{editable:false,navigational:false,bindToLocation:false,items:null,name:"Breadcrumb",gap:0,rootIcon:"home",delimiterIcon:"arrow-chevron-right",messages:{rootTitle:"Go to root"}},events:[i,j],destroy:function(){var t=this;
s.fn.destroy.call(t);
o.unbindResize(t._resizeHandler);
t.wrapper.add(t.wrapper.find("input")).add(t.wrapper.find("a")).off(g);
},items:function(t){var u=this;
if(t===r){return u.options.items;
}u.options.items=t;
u._segments=t;
u.refresh();
},_update:function(u){var t=this;
if(u!==t.value()){t._generateSegments(u);
t.refresh();
t.trigger(i,{sender:this,value:u});
}},_generateSegments:function(z){var y=this,v=y.options,u=v.items,w,x;
x=y._split(z);
if(!u){y.options.items=y._segments=x;
return;
}y._segments=[];
for(var t=0;
t<x.length;
t++){w=y._path(u.slice(0,t+1));
if(w!==""&&z.indexOf(w)>-1&&u[t]&&u[t].text===x[t]){y._segments.push(u[t]);
}else{y._segments.push(x[t]);
}}},_click:function(t){var A=this,v=A.options,u=b(t.target).closest(k+h.item),x=u.prevAll().addBack(),y=A._getItems(x),w=A._path(y),z=A._segments[u.index()];
if(!v.navigational){t.preventDefault();
}if(!A.trigger(j,{sender:A,originalEvent:t,isRoot:z.type==="rootitem",item:z})){A._update(w);
}},_getItems:function(t){var u=this;
return b.map(t,function(v){return u._segments[b(v).index()]||v.innerText;
});
},_edit:function(){var u=this,t=u.input;
u.oldValue=u.value();
u.inputWrapper.css("height",u.wrapper.height());
u.overlay.hide();
u.input.val(u.value());
u.input.attr(c,false);
u.inputWrapper.show();
setTimeout(function(){t.select();
});
},_blur:function(w){var x=this,t=x.input,u=x.inputWrapper,z=x.wrapper,v=x.overlay,y=t.val().replace(/\/{2,}/g,"/");
if(v.is(":visible")){return;
}if(w){y=x.oldValue;
}t.attr(c,true);
u.hide();
v.show();
t.val("");
x._update(y);
z.removeClass(h.focused);
},_keydown:function(t){var x=this,w=t.keyCode,u=w===o.keys.ENTER,v=w===o.keys.ESC;
if(u||v){x._blur(v);
setTimeout(function(){x.overlay.find("a:first").focus();
});
}},isNavigational:function(u){var t=u.hasClass(h.textbox)||u.closest(k+h.item);
if(u[0]===this.wrapper[0]){return false;
}return t&&!u.hasClass("k-breadcrumb-last-item");
},_wrapperKeydown:function(t){var w=this,v=b(t.target),u=w.isNavigational(v);
if(t.keyCode===o.keys.ENTER&&!u){w._edit();
}},_wrapperClick:function(t){var w=this,v=b(t.target),u=w.isNavigational(v);
if(!u){this._edit();
}},_wrapperFocus:function(t){b(t.target).addClass(h.focused);
},_wrapperBlur:function(t){b(t.target).removeClass(h.focused);
},_wrapper:function(){var v=this,t=this.element,u=t.is("input");
v.wrapper=u?t.wrap(b("<nav />")).parent():t;
if(u){v.element.wrap(b("<div />").addClass(h.inputWrapper)).addClass(h.textbox).parent().hide();
v.inputWrapper=v.wrapper.find(k+h.inputWrapper);
}else{v.inputWrapper=v.wrapper.append(b("<div />").addClass(h.inputWrapper)).find(k+h.inputWrapper).hide();
}v.wrapper.addClass(h.widget);
v.wrapper.attr(d,"Breadcrumb");
v.overlay=v.wrapper.append(b("<ol />").addClass(h.overlay)).find(k+h.overlay);
},_editable:function(){var v=this,t=v.element,u=t.is("input");
if(u){v.input=v.element;
}else{v.input=b("<input />");
}v.inputWrapper.append(v.input);
v.input.addClass(h.textbox).attr(c,true);
v.input.on(e+g,q(v._blur,v,false)).on(p+g,q(v._keydown,v));
v.wrapper.on(m+g,q(v._wrapperFocus,v)).on(e+g,q(v._wrapperBlur,v)).on(p+g,q(v._wrapperKeydown,v)).on(j+g,q(v._wrapperClick,v));
},_value:function(){var u=this,t=u.options;
if(t.value){u.value(t.value);
}else{if(t.bindToLocation){u.value(window.location.href.replace(/http(s?):\/\//,"").replace(/\/$/,""));
}else{u.value("");
}}},_split:function(t){return t.split("/").filter(function(v,u){if(u>0&&v===""){return false;
}return true;
});
},isRtl:function(){return o.support.isRtl(this.wrapper);
},refresh:function(){var F=this,B=F.options,A=B.messages,t=F.options.delimiterIcon,v="",u="",y=F.value()==="",D=F._segments,C,w,z,x;
if(t=="arrow-chevron-right"&&F.isRtl()){t="arrow-chevron-left";
}for(w=0,z=D.length;
w<z;
w++){C=D[w];
x=w===D.length-1;
if(C!==r){if(!v){u="/";
}else{u+=C.text||C||"";
}if(typeof C==="string"){C={type:!v?"rootitem":"item",href:B.navigational?u:"#",text:C,title:!v?A.rootTitle:C,showIcon:!v,showText:!!v,icon:!v?B.rootIcon:"",itemClass:!v?"k-breadcrumb-root-item":"",linkClass:!v?h.rootLink:"",delimiterIcon:t,renderDelimiter:!x&&!y,lastSegment:x,iconClass:"",disabled:false,};
F._segments.splice(w,1,C);
}else{if(n(C)){C=l({},C,{type:C.type?C.type.toLowerCase():"item"});
C=l({},C,{text:C.text||"",title:C.title||C.text||"",icon:C.icon||(C.type==="rootitem"?B.rootIcon:""),iconClass:C.iconClass||"",lastSegment:x,renderDelimiter:!x&&D.length>1,href:B.navigational?C.href:"#",delimiterIcon:t,itemClass:C.itemClass||"",linkClass:C.linkClass||"",disabled:C.disabled==true,showIcon:C.showIcon===r?C.type==="rootitem"&&C.type!=="item":C.showIcon,showText:C.showText===r?C.type==="item"&&C.type!=="rootitem":C.showText});
if(C.type==="rootitem"){C.itemClass+=" k-breadcrumb-root-item";
C.linkClass+=" "+h.rootLink;
}}}if(C.type==="rootitem"&&C.title===""){C.title=A.rootTitle;
}u+=u.match(/\/$/)?"":"/";
var E=this.itemTemplate;
if(this.options&&this.options.itemTemplate){E=this.options.itemTemplate;
}v+=o.template(E)(C);
}}this.overlay.empty().append(b(v));
this.resize(true);
},itemTemplate:'<li class="k-breadcrumb-item #:itemClass# #if(lastSegment){#k-breadcrumb-last-item#}#"><a href="#:href#" class="#:linkClass# #if(type !== "rootitem"){# k-breadcrumb-link#}##if(showText && showIcon){# k-breadcrumb-icontext-link#}##if(showIcon && !showText){# k-breadcrumb-icon-link#}##if((lastSegment && type !== "rootitem") || disabled){# k-state-disabled#}#"#if((lastSegment && type !== "rootitem") || disabled){# aria-disabled="true"#}#"#if(lastSegment){# aria-current="page"#}# title="#:title || text#">#if(showIcon) {#<span class="#if(icon){#k-icon k-i-#:icon##}# #:iconClass#"></span>#}##if(showText) {##:text##}#</a>#if(renderDelimiter) {#<span class="k-breadcrumb-delimiter-icon k-icon k-i-#:delimiterIcon#" aria-hidden="true"></span>#}##if(type === "rootitem" && renderDelimiter) {#<span class="k-breadcrumb-delimiter-icon k-hidden k-icon k-i-#:delimiterIcon#" aria-hidden="true"></span>#}#</li>',_displayOverflowIcons:function(v){var u=this,t=u.wrapper.find(k+h.rootItem);
if(v){t.find(k+h.delimiter).addClass(h.overflowIcon).removeClass(h.hidden);
}else{t.find(k+h.overflowIcon).removeClass(h.overflowIcon).last().addClass(h.hidden);
}},_shrinkItems:function(){var y=this,z=y.wrapper,x=y.overlay,w=y.overlay.find(k+h.item+":visible:not(.k-breadcrumb-root-item)"),t=z.width()-y.options.gap,v;
if(w.length==1){return;
}for(var u=0;
u<w.length;
u+=1){v=b(w[u]);
if(o._outerWidth(x)>=t){if(u==w.length-1){break;
}v.hide();
y._displayOverflowIcons(true);
}}},_showItem:function(u,v,t){if(u.length&&t>v+o._outerWidth(u,true)){u.show();
return true;
}return false;
},_stretchItems:function(){var z=this,A=z.wrapper,x=z.overlay,w=z.overlay.find(k+h.item+":hidden:not(.k-breadcrumb-root-item)"),t=A.width()-z.options.gap,v,y;
if(!w.length){z._displayOverflowIcons(false);
}for(var u=w.length-1;
u>=0;
u--){v=b(w[u]);
y=o._outerWidth(x);
if(y>t||!this._showItem(v,y,t)){break;
}}},_resize:function(){this._shrinkItems();
this._stretchItems();
},getSize:function(){return o.dimensions(this.wrapper);
},value:function(u){var t=this;
if(u!==r){t._generateSegments(u);
t.refresh();
return;
}return t._path(t._segments);
},_path:function(x){var v=[];
for(var t=0;
t<x.length;
t++){var u=x[t];
var w=n(u)?u.text:u;
v.push(w==="/"?"":w);
}return v.join("/");
}});
o.ui.plugin(f);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
