(function(b,a){a("kendo.color",["kendo.core"],b);
}(function(){var a={id:"color",name:"Color utils",category:"framework",advanced:true,description:"Color utilities used across components",depends:["core"]};
window.kendo=window.kendo||{};
var d=kendo.Class;
var l={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgrey:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"778899",lightslategrey:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"};
var k=function(o){var p=Object.keys(l);
p.push("transparent");
var q=new RegExp("^("+p.join("|")+")(\\W|$)","i");
k=function(r){return q.exec(r);
};
return q.exec(o);
};
var b=d.extend({init:function(){},toHSV:function(){return this;
},toRGB:function(){return this;
},toHex:function(){return this.toBytes().toHex();
},toBytes:function(){return this;
},toCss:function(){return"#"+this.toHex();
},toCssRgba:function(){var o=this.toBytes();
return"rgba("+o.r+", "+o.g+", "+o.b+", "+parseFloat(Number(this.a).toFixed(3))+")";
},toDisplay:function(){return this.toCssRgba();
},equals:function(o){return o===this||o!==null&&this.toCssRgba()===m(o).toCssRgba();
},diff:function(q){if(q===null){return NaN;
}var o=this.toBytes();
var p=q.toBytes();
return Math.sqrt(Math.pow((o.r-p.r)*0.3,2)+Math.pow((o.g-p.g)*0.59,2)+Math.pow((o.b-p.b)*0.11,2));
},clone:function(){var o=this.toBytes();
if(o===this){o=new c(o.r,o.g,o.b,o.a);
}return o;
}});
var n=b.extend({init:function(s,q,p,o){b.fn.init.call(this);
this.r=s;
this.g=q;
this.b=p;
this.a=o;
},toHSV:function(){var y=this;
var x=y.r;
var q=y.g;
var o=y.b;
var w=Math.min(x,q,o);
var u=Math.max(x,q,o);
var p=u-w;
var A=u;
var t,z;
if(p===0){return new i(0,0,A,this.a);
}if(u!==0){z=p/u;
if(x===u){t=(q-o)/p;
}else{if(q===u){t=2+(o-x)/p;
}else{t=4+(x-q)/p;
}}t*=60;
if(t<0){t+=360;
}}else{z=0;
t=-1;
}return new i(t,z,A,this.a);
},toHSL:function(){var y=this;
var x=y.r;
var q=y.g;
var o=y.b;
var v=Math.max(x,q,o);
var w=Math.min(x,q,o);
var t,z,u=(v+w)/2;
if(v===w){t=z=0;
}else{var p=v-w;
z=u>0.5?p/(2-v-w):p/(v+w);
switch(v){case x:t=(q-o)/p+(q<o?6:0);
break;
case q:t=(o-x)/p+2;
break;
case o:t=(x-q)/p+4;
break;
default:break;
}}return new h(t*60,z*100,u*100,this.a);
},toBytes:function(){return new c(this.r*255,this.g*255,this.b*255,this.a);
}});
var c=n.extend({init:function(s,q,p,o){n.fn.init.call(this,Math.round(s),Math.round(q),Math.round(p),o);
},toRGB:function(){return new n(this.r/255,this.g/255,this.b/255,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toHSL:function(){return this.toRGB().toHSL();
},toHex:function(){return g(this.r,2)+g(this.g,2)+g(this.b,2);
},toBytes:function(){return this;
}});
function g(o,r,p){if(p===void 0){p="0";
}var q=o.toString(16);
while(r>q.length){q=p+q;
}return q;
}var i=b.extend({init:function(p,q,r,o){b.fn.init.call(this);
this.h=p;
this.s=q;
this.v=r;
this.a=o;
},toRGB:function(){var C=this;
var x=C.h;
var D=C.s;
var F=C.v;
var B,w,o;
if(D===0){B=w=o=F;
}else{x/=60;
var y=Math.floor(x);
var u=x-y;
var z=F*(1-D);
var A=F*(1-D*u);
var E=F*(1-D*(1-u));
switch(y){case 0:B=F;
w=E;
o=z;
break;
case 1:B=A;
w=F;
o=z;
break;
case 2:B=z;
w=F;
o=E;
break;
case 3:B=z;
w=A;
o=F;
break;
case 4:B=E;
w=z;
o=F;
break;
default:B=F;
w=z;
o=A;
break;
}}return new n(B,w,o,this.a);
},toHSL:function(){return this.toRGB().toHSL();
},toBytes:function(){return this.toRGB().toBytes();
}});
var h=b.extend({init:function(p,r,q,o){b.fn.init.call(this);
this.h=p;
this.s=r;
this.l=q;
this.a=o;
},toRGB:function(){var u=this.h/360;
var z=this.s/100;
var v=this.l/100;
var y,t,o;
if(z===0){y=t=o=v;
}else{var x=v<0.5?v*(1+z):v+z-v*z;
var w=2*v-x;
y=j(w,x,u+1/3);
t=j(w,x,u);
o=j(w,x,u-1/3);
}return new n(y,t,o,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toBytes:function(){return this.toRGB().toBytes();
}});
function j(o,r,u){var v=u;
if(v<0){v+=1;
}if(v>1){v-=1;
}if(v<1/6){return o+(r-o)*6*v;
}if(v<1/2){return r;
}if(v<2/3){return o+(r-o)*(2/3-v)*6;
}return o;
}function m(s,r){var p,q;
if(s==null||s==="none"){return null;
}if(s instanceof b){return s;
}var o=s.toLowerCase();
if(p=k(o)){if(p[1]==="transparent"){o=new n(1,1,1,0);
}else{o=m(l[p[1]],r);
}o.match=[p[1]];
return o;
}if(p=/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})\b/i.exec(o)){q=new c(parseInt(p[1],16),parseInt(p[2],16),parseInt(p[3],16),1);
}else{if(p=/^#?([0-9a-f])([0-9a-f])([0-9a-f])\b/i.exec(o)){q=new c(parseInt(p[1]+p[1],16),parseInt(p[2]+p[2],16),parseInt(p[3]+p[3],16),1);
}else{if(p=/^rgb\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/.exec(o)){q=new c(parseInt(p[1],10),parseInt(p[2],10),parseInt(p[3],10),1);
}else{if(p=/^rgba\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9.]+)\s*\)/.exec(o)){q=new c(parseInt(p[1],10),parseInt(p[2],10),parseInt(p[3],10),parseFloat(p[4]));
}else{if(p=/^rgb\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*\)/.exec(o)){q=new n(parseFloat(p[1])/100,parseFloat(p[2])/100,parseFloat(p[3])/100,1);
}else{if(p=/^rgba\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9.]+)\s*\)/.exec(o)){q=new n(parseFloat(p[1])/100,parseFloat(p[2])/100,parseFloat(p[3])/100,parseFloat(p[4]));
}}}}}}if(q){q.match=p;
}else{if(!r){throw new Error("Cannot parse color: "+o);
}}return q;
}var f=180;
var e=d.extend({init:function(w){var v=this;
if(arguments.length===1){var q=e.formats;
var u=this.resolveColor(w);
for(var r=0;
r<q.length;
r++){var p=q[r].re;
var t=q[r].process;
var s=p.exec(u);
if(s){var o=t(s);
v.r=o[0];
v.g=o[1];
v.b=o[2];
}}}else{this.r=arguments[0];
this.g=arguments[1];
this.b=arguments[2];
}this.r=this.normalizeByte(this.r);
this.g=this.normalizeByte(this.g);
this.b=this.normalizeByte(this.b);
},toHex:function(){var q=this.padDigit;
var s=this.r.toString(16);
var p=this.g.toString(16);
var o=this.b.toString(16);
return"#"+q(s)+q(p)+q(o);
},resolveColor:function(p){var o=p||"black";
if(o.charAt(0)==="#"){o=o.substr(1,6);
}o=o.replace(/ /g,"");
o=o.toLowerCase();
o=e.namedColors[o]||o;
return o;
},normalizeByte:function(o){if(o<0||isNaN(o)){return 0;
}return o>255?255:o;
},padDigit:function(o){return o.length===1?"0"+o:o;
},brightness:function(p){var o=Math.round;
this.r=o(this.normalizeByte(this.r*p));
this.g=o(this.normalizeByte(this.g*p));
this.b=o(this.normalizeByte(this.b*p));
return this;
},percBrightness:function(){return Math.sqrt(0.241*this.r*this.r+0.691*this.g*this.g+0.06800000000000001*this.b*this.b);
},isDark:function(){return this.percBrightness()<f;
}});
e.fromBytes=function(s,q,p,o){return new c(s,q,p,o!=null?o:1);
};
e.fromRGB=function(s,q,p,o){return new n(s,q,p,o!=null?o:1);
};
e.fromHSV=function(p,q,r,o){return new i(p,q,r,o!=null?o:1);
};
e.fromHSL=function(p,r,q,o){return new h(p,r,q,o!=null?o:1);
};
e.formats=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(o){return[parseInt(o[1],10),parseInt(o[2],10),parseInt(o[3],10)];
}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(o){return[parseInt(o[1],16),parseInt(o[2],16),parseInt(o[3],16)];
}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(o){return[parseInt(o[1]+o[1],16),parseInt(o[2]+o[2],16),parseInt(o[3]+o[3],16)];
}}];
e.namedColors=l;
kendo.deepExtend(kendo,{parseColor:m,namedColors:l,Color:e});
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
