(function(b,a){a("kendo.datepicker",["kendo.calendar","kendo.popup","kendo.dateinput"],b);
}(function(){var a={id:"datepicker",name:"DatePicker",category:"web",description:"The DatePicker widget allows the user to select a date from a calendar or by direct input.",depends:["calendar","popup"]};
(function(b,S){var y=window.kendo,R=y.ui,U=R.Widget,H=y.parseDate,z=y.keys,P=y.support,Q=y.template,c=y._activeElement,q="<div />",N="<span />",F=".kendoDatePicker",j="click"+F,T=P.mouseAndTouchPresent?y.applyEventMap("up",F.slice(1)):j,G="open",k="close",i="change",p="disabled",K="readonly",o="k-state-default",s="k-state-focused",M="k-state-selected",O="k-state-disabled",t="k-state-hover",u="mouseenter"+F+" mouseleave"+F,D="mousedown"+F,v="id",B="min",A="max",C="month",d="aria-disabled",g="aria-readonly",e="aria-expanded",f="aria-hidden",h=y.calendar,x=h.isInRange,L=h.restrictValue,w=h.isEqualDatePart,r=b.extend,J=b.proxy,l=Date;
function E(W){var X=W.parseFormats,V=W.format;
h.normalize(W);
X=b.isArray(X)?X:[X];
if(!X.length){X.push("yyyy-MM-dd");
}if(b.inArray(V,X)===-1){X.splice(0,0,W.format);
}W.parseFormats=X;
}function I(V){V.preventDefault();
}var n=function(Y){var Z=this,X,V=document.body,W=b(q).attr(f,"true").addClass("k-calendar-container");
Z.options=Y=Y||{};
X=Y.id;
if(!Y.omitPopup){W.appendTo(V);
Z.popup=new R.Popup(W,r(Y.popup,Y,{name:"Popup",isRtl:y.support.isRtl(Y.anchor)}));
}else{W=Y.dateDiv;
}if(X){X+="_dateview";
W.attr(v,X);
Z._dateViewID=X;
}Z.div=W;
Z.value(Y.value);
};
n.prototype={_calendar:function(){var Y=this;
var V=Y.calendar;
var X=Y.options;
var W;
if(!V){W=b(q).attr(v,y.guid()).appendTo(X.omitPopup?X.dateDiv:Y.popup.element).on(D,I).on(j,"td:has(.k-link)",J(Y._click,Y));
Y.calendar=V=new R.Calendar(W,{componentType:X.componentType});
Y._setOptions(X);
V.navigate(Y._value||Y._current,X.start);
Y.value(Y._value);
}},_setOptions:function(V){this.calendar.setOptions({focusOnNav:false,change:V.change,culture:V.culture,dates:V.dates,depth:V.depth,footer:V.footer,format:V.format,max:V.max,min:V.min,month:V.month,weekNumber:V.weekNumber,start:V.start,disableDates:V.disableDates});
},setOptions:function(X){var W=this.options;
var V=X.disableDates;
if(V){X.disableDates=h.disabled(V);
}this.options=r(W,X,{change:W.change,close:W.close,open:W.open});
if(this.calendar){this._setOptions(this.options);
}},destroy:function(){if(this.popup){this.popup.destroy();
}},open:function(){var W=this;
var V;
W._calendar();
V=W.popup._hovered;
W.popup._hovered=true;
W.popup.open();
setTimeout(function(){W.popup._hovered=V;
},1);
},close:function(){this.popup.close();
},min:function(V){this._option(B,V);
},max:function(V){this._option(A,V);
},toggle:function(){var V=this;
V[V.popup.visible()?k:G]();
},move:function(W){var aa=this,Y=W.keyCode,V=aa.calendar,Z=W.ctrlKey&&Y==z.DOWN||Y==z.ENTER,X=false;
if(W.altKey){if(Y==z.DOWN){aa.open();
W.preventDefault();
X=true;
}else{if(Y==z.UP){aa.close();
W.preventDefault();
X=true;
}}}else{if(aa.popup&&aa.popup.visible()){if(Y==z.ESC||Z&&V._cell.hasClass(M)){aa.close();
W.preventDefault();
return true;
}if(Y!=z.SPACEBAR){aa._current=V._move(W);
}X=true;
}}return X;
},current:function(V){this._current=V;
if(this.calendar){this.calendar._focus(V);
}},value:function(Z){var Y=this,V=Y.calendar,X=Y.options,W=X.disableDates;
if(W&&W(Z)){Z=null;
}Y._value=Z;
Y._current=new l(+L(Z,X.min,X.max));
if(V){V.value(Z);
}},_click:function(V){if(V.currentTarget.className.indexOf(M)!==-1){this.calendar.trigger("change");
this.close();
}},_option:function(W,Y){var X=this;
var V=X.calendar;
X.options[W]=Y;
if(V){V[W](Y);
}}};
n.normalize=E;
y.DateView=n;
var m=U.extend({init:function(Y,Z){var aa=this,V,W;
U.fn.init.call(aa,Y,Z);
Y=aa.element;
Z=aa.options;
Z.disableDates=y.calendar.disabled(Z.disableDates);
Z.min=H(Y.attr("min"))||H(Z.min);
Z.max=H(Y.attr("max"))||H(Z.max);
E(Z);
aa._initialOptions=r({},Z);
aa._wrapper();
aa.dateView=new n(r({},Z,{id:Y.attr(v),anchor:aa.wrapper,change:function(){aa._change(this.value());
aa.close();
},close:function(ab){if(aa.trigger(k)){ab.preventDefault();
}else{Y.attr(e,false);
W.attr(f,true);
}},open:function(ac){var ad=aa.options,ab;
if(aa.trigger(G)){ac.preventDefault();
}else{if(aa.element.val()!==aa._oldText){ab=H(Y.val(),ad.parseFormats,ad.culture);
aa.dateView[ab?"current":"value"](ab);
}Y.attr(e,true);
W.attr(f,false);
aa._updateARIA(ab);
}}}));
W=aa.dateView.div;
aa._icon();
try{Y[0].setAttribute("type","text");
}catch(X){Y[0].type="text";
}Y.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":aa.dateView._dateViewID,autocomplete:"off"});
aa._reset();
aa._template();
V=Y.is("[disabled]")||b(aa.element).parents("fieldset").is(":disabled");
if(V){aa.enable(false);
}else{aa.readonly(Y.is("[readonly]"));
}aa._createDateInput(Z);
aa._old=aa._update(Z.value||aa.element.val());
aa._oldText=Y.val();
y.notify(aa);
},events:[G,k,i],options:{name:"DatePicker",value:null,footer:"",format:"",culture:"",parseFormats:[],min:new Date(1900,0,1),max:new Date(2099,11,31),start:C,depth:C,animation:{},month:{},dates:[],disableDates:null,ARIATemplate:'Current focused date is #=kendo.toString(data.current, "D")#',dateInput:false,weekNumber:false,componentType:"classic"},setOptions:function(V){var W=this;
var X=W._value;
U.fn.setOptions.call(W,V);
V=W.options;
V.min=H(V.min);
V.max=H(V.max);
E(V);
W.dateView.setOptions(V);
W._createDateInput(V);
if(!W._dateInput){W.element.val(y.toString(X,V.format,V.culture));
}if(X){W._updateARIA(X);
}},_editable:function(Y){var aa=this,X=aa._dateIcon.off(F),W=aa.element.off(F),ab=aa._inputWrapper.off(F),Z=Y.readonly,V=Y.disable;
if(!Z&&!V){ab.addClass(o).removeClass(O).on(u,aa._toggleHover);
if(W&&W.length){W[0].removeAttribute(p);
W[0].removeAttribute(K);
}W.attr(d,false).attr(d,false).on("keydown"+F,J(aa._keydown,aa)).on("focusout"+F,J(aa._blur,aa)).on("focus"+F,function(){aa._inputWrapper.addClass(s);
});
X.on(T,J(aa._click,aa)).on(D,I);
}else{ab.addClass(V?O:o).removeClass(V?o:O);
W.attr(p,V).attr(K,Z).attr(d,V).attr(g,Z);
}},readonly:function(V){this._editable({readonly:V===S?true:V,disable:false});
if(this._dateInput){this._dateInput._editable({readonly:V===S?true:V,disable:false});
}},enable:function(V){this._editable({readonly:false,disable:!(V=V===S?true:V)});
if(this._dateInput){this._dateInput._editable({readonly:false,disable:!(V=V===S?true:V)});
}},destroy:function(){var V=this;
U.fn.destroy.call(V);
V.dateView.destroy();
V.element.off(F);
V._dateIcon.off(F);
V._inputWrapper.off(F);
if(V._form){V._form.off("reset",V._resetHandler);
}},open:function(){this.dateView.open();
},close:function(){this.dateView.close();
},min:function(V){return this._option(B,V);
},max:function(V){return this._option(A,V);
},value:function(W){var V=this;
if(W===S){return V._value;
}V._old=V._update(W);
if(V._old===null&&!V._dateInput){V.element.val("");
}V._oldText=V.element.val();
},_toggleHover:function(V){b(V.currentTarget).toggleClass(t,V.type==="mouseenter");
},_blur:function(){var V=this,W=V.element.val();
V.close();
if(W!==V._oldText){V._change(W);
if(!W){V.dateView.current(y.calendar.getToday());
}}V._inputWrapper.removeClass(s);
},_click:function(V){var W=this;
W.dateView.toggle();
W._focusElement(V.type);
},_focusElement:function(W){var V=this.element;
if((!P.touch||P.mouseAndTouchPresent&&!(W||"").match(/touch/i))&&V[0]!==c()){V.trigger("focus");
}},_change:function(Z){var Y=this,W=Y.element.val(),V;
Z=Y._update(Z);
V=!y.calendar.isEqualDate(Y._old,Z);
var aa=V&&!Y._typing;
var X=W!==Y.element.val();
if(aa||X){Y.element.trigger(i);
}if(V){Y._old=Z;
Y._oldText=Y.element.val();
Y.trigger(i);
}Y._typing=false;
},_keydown:function(W){var Y=this,V=Y.dateView,Z=Y.element.val(),X=false;
if(!V.popup.visible()&&W.keyCode==z.ENTER&&Z!==Y._oldText){Y._change(Z);
}else{X=V.move(W);
Y._updateARIA(V._current);
if(!X){Y._typing=true;
}else{if(Y._dateInput&&W.stopImmediatePropagation){W.stopImmediatePropagation();
}}}},_icon:function(){var X=this,V=X.element,W;
W=V.next("span.k-select");
if(!W[0]){W=b('<span unselectable="on" class="k-select" aria-label="select"><span class="k-icon k-i-calendar"></span></span>').insertAfter(V);
}X._dateIcon=W.attr({role:"button","aria-controls":X.dateView._dateViewID});
},_option:function(V,Y){var X=this,W=X.options;
if(Y===S){return W[V];
}Y=H(Y,W.parseFormats,W.culture);
if(!Y){return;
}W[V]=new l(+Y);
X.dateView[V](Y);
},_update:function(ad){var ac=this,ab=ac.options,aa=ab.min,Z=ab.max,V=ac._value,W=H(ad,ab.parseFormats,ab.culture),Y=W===null&&V===null||W instanceof Date&&V instanceof Date,X;
if(ab.disableDates(W)){W=null;
if(!ac._old&&!ac.element.val()){ad=null;
}}if(+W===+V&&Y){X=y.toString(W,ab.format,ab.culture);
if(X!==ad&&!(ac._dateInput&&!W)){ac.element.val(W===null?ad:X);
}return W;
}if(W!==null&&w(W,aa)){W=L(W,aa,Z);
}else{if(!x(W,aa,Z)){W=null;
}}ac._value=W;
ac.dateView.value(W);
if(ac._dateInput&&W){ac._dateInput.value(W||ad);
}else{ac.element.val(y.toString(W||ad,ab.format,ab.culture));
}ac._updateARIA(W);
return W;
},_wrapper:function(){var W=this,V=W.element,X;
X=V.parents(".k-datepicker");
if(!X[0]){X=V.wrap(N).parent().addClass("k-picker-wrap k-state-default");
X=X.wrap(N).parent();
}X[0].style.cssText=V[0].style.cssText;
V.css({width:"100%",height:V[0].style.height});
W.wrapper=X.addClass("k-widget k-datepicker").addClass(V[0].className).removeClass("input-validation-error");
W._inputWrapper=b(X[0].firstChild);
},_reset:function(){var ad=this,W=ad.element,Y=W.attr("form"),aa=ad.options,V=aa.disableDates,ac=aa.parseFormats.length?aa.parseFormats:null,ab=ad._initialOptions.value,X=Y?b("#"+Y):W.closest("form"),Z=W[0].defaultValue;
if(ab&&(V&&V(ab))){ab=null;
}if((!Z||!y.parseDate(Z,ac,aa.culture))&&ab){W.attr("value",y.toString(ab,aa.format,aa.culture));
}if(X[0]){ad._resetHandler=function(){ad.value(ab||W[0].defaultValue);
ad.max(ad._initialOptions.max);
ad.min(ad._initialOptions.min);
};
ad._form=X.on("reset",ad._resetHandler);
}},_template:function(){this._ariaTemplate=Q(this.options.ARIATemplate);
},_createDateInput:function(V){if(this._dateInput){this._dateInput.destroy();
this._dateInput=null;
}if(V.dateInput){this._dateInput=new R.DateInput(this.element,{culture:V.culture,format:V.format,min:V.min,max:V.max});
}},_updateARIA:function(X){var W;
var Y=this;
var V=Y.dateView.calendar;
if(Y.element&&Y.element.length){Y.element[0].removeAttribute("aria-activedescendant");
}if(V){W=V._cell;
W.attr("aria-label",Y._ariaTemplate({current:X||V.current()}));
Y.element.attr("aria-activedescendant",W.attr("id"));
}}});
R.plugin(m);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
