(function(b,a){a("kendo.datetimepicker",["kendo.datepicker","kendo.timepicker"],b);
}(function(){var a={id:"datetimepicker",name:"DateTimePicker",category:"web",description:"The DateTimePicker allows the end user to select a value from a calendar or a time drop-down list.",depends:["datepicker","timepicker"]};
(function(b,V){var A=window.kendo,S=A.TimeView,J=A.parseDate,R=A.support,c=A._activeElement,t=A._extractFormat,j=A.calendar,z=j.isInRange,M=j.restrictValue,y=j.isEqualDatePart,v=S.getMilliseconds,U=A.ui,X=U.Widget,I="open",m="close",k="change",H=".kendoDateTimePicker",l="click"+H,W=R.mouseAndTouchPresent?A.applyEventMap("up",H.slice(1)):l,r="disabled",L="readonly",q="k-state-default",u="k-state-focused",w="k-state-hover",Q="k-state-disabled",x="mouseenter"+H+" mouseleave"+H,F="mousedown"+H,E="month",O="<span/>",d="aria-activedescendant",f="aria-expanded",g="aria-hidden",h="aria-owns",e="aria-disabled",i="aria-readonly",n=Date,D=new n(1800,0,1),C=new n(2099,11,31),p={view:"date"},T={view:"time"},s=b.extend,N='<div class="k-date-tab k-datetime-wrap"><div class="k-datetime-buttongroup"><div class="k-button-group k-button-group-stretched"><button class="k-button k-state-active k-group-start">#=messages.date#</button><button class="k-button k-group-end">#=messages.time#</button></div></div><div class="k-datetime-selector"><div class="k-datetime-calendar-wrap"></div><div class="k-datetime-time-wrap"></div></div><div class="k-datetime-footer k-action-buttons"><button class="k-button k-time-cancel" title="Cancel" aria-label="Cancel">#=messages.cancel#</button><button class="k-time-accept k-button k-primary" title="Set" aria-label="Set">#=messages.set#</button></div></div>',P="k-state-active";
var o=X.extend({init:function(aa,ab){var ac=this,Y;
ab=ab||{};
ab.componentType=ab.componentType||"classic";
X.fn.init.call(ac,aa,ab);
aa=ac.element;
ab=ac.options;
ab.disableDates=A.calendar.disabled(ab.disableDates);
ab.min=J(aa.attr("min"))||J(ab.min);
ab.max=J(aa.attr("max"))||J(ab.max);
if(+ab.max!=+C||+ab.min!=+D){this._specifiedRange=true;
}G(ab);
ac._initialOptions=s({},ab);
ac._wrapper();
if(ab.singlePopup){ac._popup();
}ac._views();
ac._icons();
ac._reset();
ac._template();
try{aa[0].setAttribute("type","text");
}catch(Z){aa[0].type="text";
}aa.addClass("k-input").attr({role:"combobox","aria-expanded":false,autocomplete:"off"});
ac._midnight=ac._calculateMidnight(ab.min,ab.max);
Y=aa.is("[disabled]")||b(ac.element).parents("fieldset").is(":disabled");
if(Y){ac.enable(false);
}else{ac.readonly(aa.is("[readonly]"));
}ac._createDateInput(ab);
ac._old=ac._update(ab.value||ac.element.val());
ac._oldText=aa.val();
A.notify(ac);
},options:{name:"DateTimePicker",value:null,format:"",timeFormat:"",culture:"",parseFormats:[],dates:[],disableDates:null,min:new n(D),max:new n(C),interval:30,height:200,footer:"",start:E,depth:E,animation:{},month:{},ARIATemplate:'Current focused date is #=kendo.toString(data.current, "d")#',dateButtonText:"Open the date view",timeButtonText:"Open the time view",dateInput:false,weekNumber:false,messages:{set:"Set",cancel:"Cancel",hour:"hour",minute:"minute",second:"second",millisecond:"millisecond",now:"Now",date:"Date",time:"Time",today:"Today"},componentType:"classic"},events:[I,m,k],componentTypes:{classic:{singlePopup:false,timeView:{list:"list"}},modern:{singlePopup:true,timeView:{list:"scroll"}}},setOptions:function(ab){var ac=this,ad=ac._value,aa,Z,Y;
X.fn.setOptions.call(ac,ab);
ab=ac.options;
ab.min=aa=J(ab.min);
ab.max=Z=J(ab.max);
G(ab);
ac._midnight=ac._calculateMidnight(ab.min,ab.max);
Y=ab.value||ac._value||ac.dateView._current;
if(aa&&!y(aa,Y)){aa=new n(D);
}if(Z&&!y(Z,Y)){Z=new n(C);
}ac.dateView.setOptions(ab);
ac.timeView.setOptions(s({},ab,{format:ab.timeFormat,min:aa,max:Z}));
ac._createDateInput(ab);
if(!ac._dateInput){ac.element.val(A.toString(ad,ab.format,ab.culture));
}if(ad){ac._updateARIA(ad);
}},_editable:function(ab){var ad=this,aa=ad.element.off(H),Y=ad._dateIcon.off(H),ae=ad._timeIcon.off(H),af=ad._inputWrapper.off(H),ac=ab.readonly,Z=ab.disable;
if(!ac&&!Z){af.addClass(q).removeClass(Q).on(x,ad._toggleHover);
if(aa&&aa.length){aa[0].removeAttribute(r);
aa[0].removeAttribute(L,false);
aa[0].removeAttribute(e,false);
aa[0].removeAttribute(i,false);
}aa.on("keydown"+H,b.proxy(ad._keydown,ad)).on("focus"+H,function(){ad._inputWrapper.addClass(u);
}).on("focusout"+H,function(){ad._inputWrapper.removeClass(u);
if(aa.val()!==ad._oldText){ad._change(aa.val());
if(!aa.val()){ad.dateView.current(A.calendar.getToday());
}}if(ad.options.singlePopup){return;
}ad.close("date");
ad.close("time");
});
Y.on(F,K).on(W,function(ag){ad.toggle("date");
ad._focusElement(ag.type);
});
ae.on(F,K).on(W,function(ag){ad.toggle("time");
ad._focusElement(ag.type);
});
}else{af.addClass(Z?Q:q).removeClass(Z?q:Q);
aa.attr(r,Z).attr(L,ac).attr(e,Z).attr(i,ac);
}},_focusElement:function(Z){var Y=this.element;
if((!R.touch||R.mouseAndTouchPresent&&!(Z||"").match(/touch/i))&&Y[0]!==c()){Y.trigger("focus");
}},readonly:function(Y){this._editable({readonly:Y===V?true:Y,disable:false});
},enable:function(Y){this._editable({readonly:false,disable:!(Y=Y===V?true:Y)});
},destroy:function(){var Y=this;
X.fn.destroy.call(Y);
Y.dateView.destroy();
Y.timeView.destroy();
if(Y.options.singlePopup){Y.popup.element.off(H);
Y.popup.destroy();
}Y.element.off(H);
Y._dateIcon.off(H);
Y._timeIcon.off(H);
Y._inputWrapper.off(H);
if(Y._form){Y._form.off("reset",Y._resetHandler);
}},close:function(Y){if(this.options.singlePopup){this.popup.close();
}else{if(Y!=="time"){Y="date";
}this[Y+"View"].close();
}},open:function(aa){var Z=this;
var Y;
if(Z.options.singlePopup){Z.dateView._calendar();
if(Z.timeView.ul.find("li").length<1){Z.timeView.bind();
}Y=Z.popup._hovered;
Z.popup._hovered=true;
Z.popup.open();
if(aa==="time"){Z._switchToTimeView();
}else{Z._switchToDateView();
}this._dateIcon.toggle(aa!=="time");
this._timeIcon.toggle(aa==="time");
setTimeout(function(){Z.popup._hovered=Y;
},1);
}else{if(aa!=="time"){aa="date";
}this[aa+"View"].open();
}},min:function(Y){return this._option("min",Y);
},max:function(Y){return this._option("max",Y);
},toggle:function(Z){if(this.options.singlePopup){if(this.popup.visible()){this.close();
}else{this.open(Z);
}}else{var Y="timeView";
if(Z!=="time"){Z="date";
}else{Y="dateView";
}this[Z+"View"].toggle();
this[Y].close();
}},value:function(Z){var Y=this;
if(Z===V){return Y._value;
}Y._old=Y._update(Z);
if(Y._old===null){Y.element.val("");
}Y._oldText=Y.element.val();
},_change:function(ac){var ab=this,Z=ab.element.val(),Y;
ac=ab._update(ac);
Y=+ab._old!=+ac;
var ad=Y&&!ab._typing;
var aa=Z!==ab.element.val();
if(ad||aa){ab.element.trigger(k);
}if(Y){ab._old=ac;
ab._oldText=ab.element.val();
ab.trigger(k);
}ab._typing=false;
},_option:function(ab,ag){var ad=this;
var ac=ad.options;
var ae=ad.timeView;
var af=ae.options;
var Y=ad._value||ad._old;
var aa;
var Z;
if(ag===V){return ac[ab];
}ag=J(ag,ac.parseFormats,ac.culture);
af.maxSet=false;
if(!ag){return;
}if(ac.min.getTime()===ac.max.getTime()){af.dates=[];
}ac[ab]=new n(ag.getTime());
ad.dateView[ab](ag);
ad._midnight=ad._calculateMidnight(ac.min,ac.max);
if(Y){aa=y(ac.min,Y);
Z=y(ac.max,Y);
}if(aa||Z){af[ab]=ag;
if(aa&&!Z){af.max=B(ac.interval);
}if(Z){if(ad._midnight){ae.dataBind([C]);
return;
}else{if(!aa){af.min=D;
af.maxSet=true;
}}}}else{af.max=C;
af.min=D;
}ae.bind();
},_toggleHover:function(Y){b(Y.currentTarget).toggleClass(w,Y.type==="mouseenter");
},_update:function(am){var aj=this,ag=aj.options,ae=ag.min,ad=ag.max,aa=ag.dates,ak=aj.timeView,Y=aj._value,Z=J(am,ag.parseFormats,ag.culture),ac=Z===null&&Y===null||Z instanceof Date&&Y instanceof Date,ah,al,af,ai,ab;
if(ag.disableDates&&ag.disableDates(Z)){Z=null;
if(!aj._old&&!aj.element.val()){am=null;
}}if(+Z===+Y&&ac){ab=A.toString(Z,ag.format,ag.culture);
if(ab!==am){aj.element.val(Z===null?am:ab);
if(am instanceof String){aj.element.trigger(k);
}}return Z;
}if(Z!==null&&y(Z,ae)){Z=M(Z,ae,ad);
}else{if(!z(Z,ae,ad)){Z=null;
}}aj._value=Z;
ak.value(Z);
aj.dateView.value(Z);
if(Z){af=aj._old;
al=ak.options;
al.maxSet=false;
if(aa[0]){aa=b.grep(aa,function(an){return y(Z,an);
});
if(aa[0]){ak.dataBind(aa);
ai=true;
}}if(!ai){if(y(Z,ae)){al.min=ae;
al.max=B(ag.interval);
ah=true;
}if(y(Z,ad)){if(aj._midnight){ak.dataBind([C]);
ai=true;
}else{al.max=ad;
al.maxSet=true;
if(!ah){al.min=D;
}ah=true;
}}}if(!ai&&(!af&&ah||af&&!y(af,Z))){if(!ah){al.max=C;
al.min=D;
}ak.bind();
}}if(aj._dateInput&&Z){aj._dateInput.value(Z||am);
}else{aj.element.val(A.toString(Z||am,ag.format,ag.culture));
}aj._updateARIA(Z);
return Z;
},_keydown:function(Z){var ac=this,Y=ac.dateView,ad=ac.timeView,ae=ac.element.val(),aa=ac.options.singlePopup?ac.popup.visible():Y.popup.visible();
var ab=ac._dateInput&&Z.stopImmediatePropagation;
if(Z.altKey&&Z.keyCode===A.keys.DOWN){ac.toggle(aa?"time":"date");
}else{if(aa){Y.move(Z);
ac._updateARIA(Y._current);
}else{if(!ac.options.singlePopup&&ad.popup.visible()){ad.move(Z);
}else{if(Z.keyCode===A.keys.ENTER&&ae!==ac._oldText){ac._change(ae);
}else{ac._typing=true;
ab=false;
}}}}if(ab){Z.stopImmediatePropagation();
}},_views:function(){var ag=this,ab=ag.element,af=ag.options,ac=ab.attr("id"),Z,ai,aa,ak,ad,Y,ah,ae,aj;
if(af.singlePopup){af.dateDiv=ag.popup.element.find(".k-datetime-calendar-wrap");
ah=ag.popup.element.find(".k-datetime-time-wrap");
af.omitPopup=ae=true;
aj=af.timeView;
}ag.dateView=Z=new A.DateView(s({},af,{id:ac,anchor:ag.wrapper,change:function(){var al=ag._applyDateValue();
if(af.singlePopup){if(!ag.timeView._currentlySelected){ag.timeView._currentlySelected=new Date();
}ag.timeView._currentlySelected.setFullYear(al.getFullYear());
ag.timeView._currentlySelected.setMonth(al.getMonth());
ag.timeView._currentlySelected.setDate(al.getDate());
ag._switchToTimeView();
ag._toggleIcons();
}else{ag._change(al);
ag.close("date");
}},close:function(al){if(ag.trigger(m,p)){al.preventDefault();
}else{ab.attr(f,false);
aa.attr(g,true);
if(!ag.options.singlePopup&&!ai.popup.visible()){if(ab&&ab.length){ab[0].removeAttribute(h);
}}}},open:function(al){if(ag.trigger(I,p)){al.preventDefault();
}else{if(ab.val()!==ag._oldText){Y=J(ab.val(),af.parseFormats,af.culture);
ag.dateView[Y?"current":"value"](Y);
}aa.attr(g,false);
ab.attr(f,true).attr(h,Z._dateViewID);
ag._updateARIA(Y);
}}}));
aa=Z.div;
ad=af.min.getTime();
ag.timeView=ai=new S({id:ac,value:af.value,anchor:ag.wrapper,animation:af.animation,format:af.timeFormat,culture:af.culture,height:af.componentType==="modern"?null:af.height,interval:af.interval,min:af.componentType==="modern"?af.min:new n(D),max:af.componentType==="modern"?af.max:new n(C),dates:ad===af.max.getTime()?[new Date(ad)]:[],parseFormats:af.parseFormats,validateDate:true,change:function(am,al){am=ag._applyTimeValue(am);
if(al){ag._timeSelected=true;
ag._change(am);
}else{ab.val(A.toString(am,af.format,af.culture));
Z.value(am);
ag._updateARIA(am);
}},close:function(al){if(ag.trigger(m,T)){al.preventDefault();
}else{ak.attr(g,true);
ab.attr(f,false);
if(!Z.popup.visible()){if(ab&&ab.length){ab[0].removeAttribute(h);
}}}},open:function(al){if(ag.options.componentType!=="modern"){ai._adjustListWidth();
}else{ag.timeView._updateTitle();
}if(ag.trigger(I,T)){al.preventDefault();
}else{if(ab.val()!==ag._oldText){Y=J(ab.val(),af.parseFormats,af.culture);
ag.timeView.value(Y);
}ak.attr(g,false);
ab.attr(f,true).attr(h,ai._timeViewID);
ai.options.active(ai.current());
}},active:function(al){if(ab&&ab.length){ab[0].removeAttribute(d);
}if(al){ab.attr(d,ai._optionID);
}},popup:af.popup,useValueToRender:true,specifiedRange:ag._specifiedRange,omitPopup:ae,timeDiv:ah,timeView:aj,messages:ag.options.messages});
ak=ai.ul;
},_applyDateValue:function(){var af=this;
var ae=af.options;
var aa=af.dateView;
var ag=aa.calendar.value();
var ad=+ag;
var ac=+ae.min;
var ab=+ae.max;
var Z,Y;
if(ad===ac||ad===ab){Z=ad===ac?ac:ab;
Z=new n(af._value||Z);
Z.setFullYear(ag.getFullYear(),ag.getMonth(),ag.getDate());
if(z(Z,ac,ab)){ag=Z;
}}if(af._value){Y=A.date.setHours(new Date(ag),af._value);
if(z(Y,ac,ab)){ag=Y;
}}return ag;
},_applyTimeValue:function(aa){var Z=this.timeView;
var Y=this.options;
aa=Z._parse(aa);
if(aa<Y.min){aa=new n(+Y.min);
Z.options.min=aa;
}else{if(aa>Y.max){aa=new n(+Y.max);
Z.options.max=aa;
}}return aa;
},_icons:function(){var ab=this;
var Y=ab.element;
var aa=ab.options;
var Z;
Z=Y.next("span.k-select");
if(!Z[0]){Z=b('<span unselectable="on" class="k-select"><span class="k-link k-link-date" aria-label="'+aa.dateButtonText+'"><span unselectable="on" class="k-icon k-i-calendar"></span></span><span class="k-link k-link-time" aria-label="'+aa.timeButtonText+'"><span unselectable="on" class="k-icon k-i-clock"></span></span></span>').insertAfter(Y);
}Z=Z.children();
ab._dateIcon=Z.eq(0).attr("aria-controls",ab.dateView._dateViewID);
ab._timeIcon=Z.eq(1).attr("aria-controls",ab.timeView._timeViewID);
if(aa.singlePopup){ab._timeIcon.hide();
}},_wrapper:function(){var Z=this,Y=Z.element,aa;
aa=Y.parents(".k-datetimepicker");
if(!aa[0]){aa=Y.wrap(O).parent().addClass("k-picker-wrap k-state-default");
aa=aa.wrap(O).parent();
}aa[0].style.cssText=Y[0].style.cssText;
Y.css({width:"100%",height:Y[0].style.height});
Z.wrapper=aa.addClass("k-widget k-datetimepicker").addClass(Y[0].className).removeClass("input-validation-error");
Z._inputWrapper=b(aa[0].firstChild);
},_reset:function(){var ag=this,Z=ag.element,ab=Z.attr("form"),aa=ab?b("#"+ab):Z.closest("form"),ad=ag.options,Y=ad.disableDates,af=ad.parseFormats.length?ad.parseFormats:null,ae=ag._initialOptions.value,ac=Z[0].defaultValue;
if(ae&&(Y&&Y(ae))){ae=null;
}if((!ac||!A.parseDate(ac,af,ad.culture))&&ae){Z.attr("value",A.toString(ae,ad.format,ad.culture));
}if(aa[0]){ag._resetHandler=function(){ag.value(ae||Z[0].defaultValue);
ag.max(ag._initialOptions.max);
ag.min(ag._initialOptions.min);
};
ag._form=aa.on("reset",ag._resetHandler);
}},_template:function(){this._ariaTemplate=A.template(this.options.ARIATemplate);
},_createDateInput:function(Y){if(this._dateInput){this._dateInput.destroy();
this._dateInput=null;
}if(Y.dateInput){this._dateInput=new U.DateInput(this.element,{culture:Y.culture,format:Y.format,min:Y.min,max:Y.max,interval:Y.interval});
}},_calculateMidnight:function(Z,Y){return v(Z)+v(Y)===0;
},_updateARIA:function(aa){var Z;
var ab=this;
var Y=ab.dateView.calendar;
if(ab.element&&ab.element.length){ab.element[0].removeAttribute(d);
}if(Y){Z=Y._cell;
Z.attr("aria-label",ab._ariaTemplate({current:aa||Y.current()}));
ab.element.attr(d,Z.attr("id"));
}},_popup:function(){var aa=this;
var Z=aa.options;
var Y=b("<div></div>").attr(g,"true").addClass("k-datetime-container k-group k-reset").appendTo(document.body);
Y.append(A.template(N)(aa.options));
aa.popup=new U.Popup(Y,s(Z.popup,Z,{name:"Popup",isRtl:A.support.isRtl(aa.wrapper),anchor:aa.wrapper,activate:function(){if(aa.options.timeView&&aa.options.timeView.list==="scroll"){aa.timeView.addTranslate();
aa.timeView.applyValue(aa._value);
aa.timeView._updateRanges();
}},open:function(){aa.timeView._updateTitle();
}}));
Y.on(l+H,".k-datetime-buttongroup .k-button",b.proxy(aa._groupChangeClick,aa));
Y.on(l+H,".k-datetime-footer button.k-time-cancel",b.proxy(aa._cancelClickHandler,aa));
Y.on(l+H,".k-datetime-footer button.k-time-accept",b.proxy(aa._setClickHandler,aa));
},_groupChangeClick:function(Z){K(Z);
var Y=b(Z.currentTarget);
var aa=Y.index();
if(aa){this._switchToTimeView();
}else{this._switchToDateView();
}this._toggleIcons();
},_switchToDateView:function(){this.popup.element.find(".k-group-start, .k-group-end").removeClass(P).eq(0).addClass(P);
this.popup.element.find(".k-datetime-wrap").removeClass("k-time-tab").addClass("k-date-tab");
},_switchToTimeView:function(){this.timeView._updateRanges();
this.popup.element.find(".k-group-start, .k-group-end").removeClass(P).eq(1).addClass(P);
this.popup.element.find(".k-datetime-wrap").removeClass("k-date-tab").addClass("k-time-tab");
},_toggleIcons:function(){this._dateIcon.toggle();
this._timeIcon.toggle();
},_cancelClickHandler:function(){if(this._value){this.value(this._value);
this.dateView.value(this._value);
}this.popup.close();
},_setClickHandler:function(){var Z=this._applyDateValue();
var Y=this.timeView._currentlySelected||new Date();
Z=Z||new Date();
this.timeView._updateCurrentlySelected();
Z.setHours(Y.getHours());
Z.setMinutes(Y.getMinutes());
Z.setSeconds(Y.getSeconds());
Z=this._applyTimeValue(Z);
this._change(Z);
this.popup.close();
}});
function B(Z){var Y=new Date(2100,0,1);
Y.setMinutes(-Z);
return Y;
}function K(Y){Y.preventDefault();
}function G(Y){var aa=A.getCulture(Y.culture).calendars.standard.patterns,Z=!Y.parseFormats.length,ab;
Y.format=t(Y.format||aa.g);
Y.timeFormat=ab=t(Y.timeFormat||aa.t);
A.DateView.normalize(Y);
if(Z){Y.parseFormats.unshift("yyyy-MM-ddTHH:mm:ss");
}if(b.inArray(ab,Y.parseFormats)===-1){Y.parseFormats.push(ab);
}}U.plugin(o);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
