(function(b,a){a("kendo.drawer",["kendo.userevents"],b);
}(function(){var a={id:"drawer",name:"Drawer",category:"web",description:"The Kendo Drawer widget provides slide to reveal sidebar",depends:["userevents"]};
(function(b,r){var g=window.kendo,q=g.ui,s=q.Widget,o="show",e="hide",j=".kendoDrawer",d="k-state-focused",h=g.keys,f="itemClick",p="tabIndex",l=b.proxy,m="push",k="overlay",i="left",n="right";
var c=g.ui.Widget.extend({init:function(t,u){var v=this;
var w;
s.fn.init.call(this,t,u);
u=v.options;
v._element(t);
v._wrapper(t);
v._navigatable();
v.position();
v._mode();
if(u.mini){v._miniMode();
}v._initDrawerItems();
if(u.mini&&u.mode!=m){v._setBodyOffset();
}w=this.userEvents=new g.UserEvents(u.mode!=m?b(document.body):this.drawerContainer,{fastTap:true,allowSelection:true});
v.tap=function(x){if(b.contains(v.drawerItemsWrapper[0],x.event.target)){v._itemClick(x);
}if(v.visible&&!v.trigger("hide",{sender:this})){v.hide();
x.preventDefault();
}};
if(this.options.swipeToOpen){w.bind("start",function(x){v._start(x);
});
w.bind("move",function(x){v._update(x);
});
w.bind("end",function(x){v._end(x);
});
w.bind("tap",v.tap);
}else{w.bind("press",v.tap);
}if(u.minHeight&&u.mode==m){v.drawerContainer.css("min-height",u.minHeight);
}},_element:function(){var w=this;
var u=w.element;
var v=w.options;
var t=w.contentElement=u.children().first();
w.drawerElement=b(v.template);
t.addClass("k-drawer-content");
u.addClass("k-widget k-drawer");
},_navigatable:function(){if(!this.options.navigatable){return;
}var u=this;
var t=u.element;
t.attr(p,0).attr("role","tablist").attr("aria-orientation","vertical");
t.on("focus"+j,l(u._focus,u)).on("focusout"+j,l(u._blur,u)).on("keydown"+j,u,l(u._keyDown,u));
},_blur:function(){var t=this;
if(t._current){t._current.removeClass(d);
}},_focus:function(){var t=this;
t._setCurrent(t._current?t._current:t.drawerItemsWrapper.find("[data-role='drawer-item']").eq(0));
},_setCurrent:function(t){var w=this;
var u=g.guid();
var v=b(t);
if(w._current){b(w._current).removeClass(d).removeAttr("id");
w.element.removeAttr("aria-activedescendant");
}v.attr("id",u).addClass(d);
w.element.attr("aria-activedescendant",u);
w._current=v;
},_keyDown:function(u){var x=this;
var v=false;
var t=x._current;
var w;
if(u.keyCode==h.UP){v=true;
w=t.prevAll("[data-role='drawer-item']:first");
if(w.length){x._setCurrent(w);
}else{x._setCurrent(t.parent().find("[data-role='drawer-item']:last"));
}}if(u.keyCode==h.DOWN){v=true;
w=t.nextAll("[data-role='drawer-item']:first");
if(w.length){x._setCurrent(w);
}else{x._setCurrent(t.parent().find("[data-role='drawer-item']:first"));
}}if(u.keyCode==h.HOME){v=true;
x._setCurrent(x.drawerItemsWrapper.find("[data-role='drawer-item']").eq(0));
}if(u.keyCode==h.END){v=true;
x._setCurrent(x.drawerItemsWrapper.find("[data-role='drawer-item']:last"));
}if(u.keyCode==h.SPACEBAR||u.keyCode==h.ENTER){v=true;
x.tap({event:{target:t[0]},preventDefault:b.noop});
}if(u.keyCode==h.ESC){v=true;
x.hide();
}if(v){u.preventDefault();
}},_wrapper:function(){var z=this.options;
var v=this.drawerElement;
var y=this.element;
var t=this.contentElement;
var w=this.drawerItemsWrapper=v.wrapAll("<div class='k-drawer-items'></div>").parent();
var x=this.drawerWrapper=w.wrap("<div class='k-drawer-wrapper'></div>").parent();
var u=this.drawerContainer=y.wrap("<div class='k-drawer-container'></div>").parent();
if(z.mini){if(z.mini.width){x.width(z.mini.width);
}}else{x.width(0);
}if(z.mode===m){u.append(t);
}else{if(z.mode===k){u.after(t);
b(document.body).prepend(u);
}}y.append(x);
},_setBodyOffset:function(){var t=this.element.outerWidth();
if(this.leftPositioned){b(document.body).css("padding-left",t);
}else{b(document.body).css("padding-right",t);
}},_initDrawerItems:function(){var u=this.drawerItemsWrapper;
var t=u.find("[data-role='drawer-item']");
var v=u.find("[data-role='drawer-separator']");
t.addClass("k-drawer-item");
v.addClass("k-drawer-item k-drawer-separator");
if(this._selectedItemIndex>=0){t.removeClass("k-state-selected");
t.eq(this._selectedItemIndex).addClass("k-state-selected");
}if(this.options.navigatable){t.attr("aria-selected",false);
}},_mode:function(){var u=this.options;
var t=this.drawerContainer;
var v;
if(u.mode==m){t.addClass("k-drawer-"+m);
}else{t.addClass("k-drawer-"+k);
v=this.overlayContainer=b('<div class="k-overlay"></div>');
v.hide();
t.prepend(v);
}},_miniMode:function(){var y=this.options;
var t=this.drawerContainer;
var x=y.mini.width;
var w=this._miniTemplate=y.mini.template&&b(y.mini.template);
var u=this.drawerItemsWrapper;
var v=this.drawerWrapper;
t.addClass("k-drawer-mini");
if(w){u.html(w);
}if(x){v.width(x);
}this.minWidth=y.mini.width||this.drawerWrapper.width();
},show:function(){var w=this.drawerWrapper;
var t=this.drawerContainer;
var z=this.options;
var x=t.hasClass("k-drawer-expanded");
var y=this._miniTemplate;
var u=this.drawerElement;
var v=this.drawerItemsWrapper;
if(!x){t.addClass("k-drawer-expanded");
this.visible=true;
}if(y){v.html(u);
this._initDrawerItems();
this._selectItem();
}w.width(z.width);
if(z.mode===k){this.overlayContainer.show();
this.visible=true;
}},hide:function(){var z=this;
var v=z.drawerWrapper;
var t=z.drawerContainer;
var y=this.options;
var u=this.drawerItemsWrapper;
var w=this._miniTemplate;
var x=y.mini&&y.mini.width;
if(this._miniTemplate){u.html(w);
z._initDrawerItems();
this._selectItem();
}if(y.mini){if(x){v.width(x);
}else{v.width("");
}}else{v.width(0);
}if(this.visible){t.removeClass("k-drawer-expanded");
this.visible=false;
}if(y.mode===k){this.overlayContainer.hide();
}},position:function(x){var w=this;
var u=w.options;
var v=x||u.position;
var t=w.drawerContainer;
if(v==n){t.removeClass("k-drawer-"+i);
t.addClass("k-drawer-"+n);
}else{t.removeClass("k-drawer-"+n);
t.addClass("k-drawer-"+i);
}this.leftPositioned=v===i;
},_start:function(v){var x=this;
var w=this.options;
var u=this.drawerWrapper;
var t=this.drawerItemsWrapper;
var y=v.sender;
if(Math.abs(v.x.velocity)<Math.abs(v.y.velocity)||g.triggeredByInput(v.event)){y.cancel();
return;
}if(this.drawerMini){t.html(x.drawerElement);
}u.css("transition","none");
if(w.mode!=m){this.overlayContainer.show();
}},_update:function(t){var v=this.options;
var u=v.mode;
if(u==m){this._push(t);
}else{this._overlay(t);
}},_end:function(u){var z=u.x.velocity;
var w=this.options;
var t=this.drawerWrapper;
var v=t.width();
var x=v>w.width/2;
var A=0.8;
var y;
t.css("transition","all .3s ease-out");
if(this.leftPositioned){y=z>-A&&(z>A||x);
}else{y=z<A&&(z<-A||x);
}if(y){if(this.trigger("show",{sender:this})){u.preventDefault();
this.hide();
}else{this.show();
}}else{if(this.trigger("hide",{sender:this})){u.preventDefault();
this.show();
}else{this.hide();
}}},_overlay:function(x){var y=this.options;
var w=y.mini&&y.mini.width||this.minWidth||0;
var t=this.drawerWrapper;
var u=t.width();
var v;
var z;
z=u+(this.leftPositioned?x.x.delta:-x.x.delta);
v=Math.min(Math.max(z,w),y.width);
x.event.preventDefault();
x.event.stopPropagation();
t.width(v);
},_push:function(x){var y=this.options;
var w=y.mini&&y.mini.width||this.minWidth||0;
var t=this.drawerWrapper;
var u=t.width();
var v;
var z;
z=u+(this.leftPositioned?x.x.delta:-x.x.delta);
v=Math.min(Math.max(z,w),y.width);
x.event.preventDefault();
x.event.stopPropagation();
t.width(v);
},_selectItem:function(t){var u;
if(t){t.addClass("k-state-selected");
this.trigger("itemClick",{item:t,sender:this});
this._selectedItemIndex=t.index();
return;
}u=this._selectedItemIndex;
if(u){this.drawerItemsWrapper.find("[data-role='drawer-item']").eq(u).addClass("k-state-selected");
}},_itemClick:function(t){var w=this;
var u;
var v;
if(b(t.event.target).find(".k-drawer-item").length>0){u=b(t.event.target).find(".k-drawer-item");
}else{if(b(t.event.target).closest(".k-drawer-item").length>0){u=b(t.event.target).closest(".k-drawer-item");
}else{if(b(t.event.target).hasClass(".k-drawer-item")){u=b(t.event.target);
}}}v=w.drawerItemsWrapper.find(".k-drawer-item").removeClass("k-state-selected");
w._selectItem(u);
if(w.options.navigatable){v.attr("aria-selected",false);
u.attr("aria-selected",true);
w._setCurrent(u);
}},destroy:function(){var t=this.options;
if(t.mode!=m){if(this.leftPositioned){b(document.body).css("padding-left",0);
}else{b(document.body).css("padding-right",0);
}}s.fn.destroy.call(this);
this.userEvents.destroy();
g.destroy(this.element);
this.element=this.drawerWrapper=this.drawerElement=this.drawerContainer=this.drawerItemsWrapper=this._miniTemplate=null;
},options:{name:"Drawer",position:i,mode:"overlay",swipeToOpen:true,width:280,mini:false,navigatable:false,template:""},events:[e,o,f]});
g.ui.plugin(c);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
