(function(b,a){a("kendo.editable",["kendo.dropdownlist","kendo.datepicker","kendo.numerictextbox","kendo.validator","kendo.binder"],b);
}(function(){var a={id:"editable",name:"Editable",category:"framework",depends:["dropdownlist","datepicker","numerictextbox","validator","binder"],hidden:true};
(function(b,B){var t=window.kendo,A=t.ui,C=A.Widget,n=b.extend,r=t.isFunction,s=b.isPlainObject,q=b.inArray,x=".",e="off",w=/("|\%|'|\[|\]|\$|\.|\,|\:|\;|\+|\*|\&|\!|\#|\(|\)|<|>|\=|\?|\@|\^|\{|\}|\~|\/|\||`)/g,m='<div class="k-tooltip k-tooltip-error k-validator-tooltip"><span class="k-tooltip-icon k-icon k-i-warning"></span><span class="k-tooltip-content">#= message #</span><span class="k-callout k-callout-n"></span></div>',f="change";
var l="equalSet";
var z=["url","email","number","date","boolean"];
function o(D){D=D!=null?D:"";
return D.type||b.type(D)||"string";
}function h(D){D.find(":input:not(:button, .k-combobox .k-input, .k-checkbox-list .k-checkbox, .k-radio-list .k-radio, ["+t.attr("role")+"=listbox], ["+t.attr("role")+"=upload], ["+t.attr("skip")+"], [type=file])").each(function(){var E=t.attr("bind"),F=this.getAttribute(E)||"",G=this.type==="checkbox"||this.type==="radio"?"checked:":"value:",H=this.name;
if(F.indexOf(G)===-1&&H){F+=(F.length?",":"")+G+H;
b(this).attr(E,F);
}});
}function i(L){var J=(L.model.fields||L.model)[L.field],P=o(J),Q=J?J.validation:{},F=J?J.attributes:{},N,I=t.attr("type"),G=t.attr("bind"),M,D={id:L.id||L.field,name:L.field,title:L.title?L.title:L.field};
for(N in Q){M=Q[N];
if(q(N,z)>=0){D[I]=N;
}else{if(!r(M)){var H=t.getCulture();
if(typeof M==="number"&&H.name.length){var K=H.numberFormat;
var O=M.toString().replace(x,K[x]);
D[N]=O;
}else{D[N]=s(M)?M.value||N:M;
}}}D[t.attr(N+"-msg")]=M.message;
D.autocomplete=e;
}for(var E in F){D[E]=F[E];
}if(q(P,z)>=0){D[I]=P;
}D[G]=(P==="boolean"?"checked:":"value:")+L.field;
return D;
}function c(E,D){var F=E.attr("id");
if(F){D.id=F;
E.removeAttr("id");
}return D;
}function g(F){var D,G,E,J,I,H;
if(F&&F.length){H=[];
for(D=0,G=F.length;
D<G;
D++){E=F[D];
I=E.text||E.value||E;
J=E.value==null?E.text||E:E.value;
H[D]={text:I,value:J};
}}return H;
}function p(F,D){var E;
if(!F.length){return;
}if(F==="DropDownTree"&&D&&D.checkboxes||F==="MultiSelect"){E="<select />";
}else{if(F==="RadioGroup"||F==="CheckBoxGroup"){E="<ul />";
}else{E=F==="Editor"?"<textarea />":"<input />";
}}return E;
}var u=["AutoComplete","CheckBoxGroup","ColorPicker","ComboBox","DateInput","DatePicker","DateTimePicker","DropDownTree","Editor","MaskedTextBox","MultiColumnComboBox","MultiSelect","NumericTextBox","RadioGroup","Rating","Slider","Switch","TimePicker","DropDownList"];
var k={number:function(E,F){var D=i(F);
b('<input type="text"/>').attr(D).appendTo(E).kendoNumericTextBox({format:F.format});
b("<span "+t.attr("for")+'="'+F.field+'" class="k-invalid-msg k-hidden"/>').appendTo(E);
},date:function(E,G){var D=i(G),F=G.format;
if(F){F=t._extractFormat(F);
}D[t.attr("format")]=F;
b('<input type="text"/>').attr(D).appendTo(E).kendoDatePicker({format:G.format});
b("<span "+t.attr("for")+'="'+G.field+'" class="k-invalid-msg k-hidden"/>').appendTo(E);
},string:function(E,F){var D=i(F);
b('<input type="text" />').attr(D).addClass("k-textbox").appendTo(E);
},"boolean":function(E,G){var D=i(G);
var F=b('<input type="checkbox" />').attr(D).addClass("k-checkbox").appendTo(E);
y(F,E,G);
},values:function(E,G){var D=i(G);
var F=t.stringify(g(G.values));
b("<select "+t.attr("text-field")+'="text"'+t.attr("value-field")+'="value"'+t.attr("source")+"='"+(F?F.replace(/\'/g,"&apos;"):F)+"'"+t.attr("role")+'="dropdownlist"/>').attr(D).appendTo(E);
b("<span "+t.attr("for")+'="'+G.field+'" class="k-invalid-msg  k-hidden"/>').appendTo(E);
},kendoEditor:function(E,I){var D=i(I);
var K=I.editor;
var F="kendo"+K;
var G=I.editorOptions;
var J=p(K,G);
var H=b(J).attr(D).appendTo(E)[F](G);
y(H,E,I);
}};
var v={number:function(E,F){var D=i(F);
D=c(E,D);
b('<input type="number"/>').attr(D).appendTo(E);
},date:function(E,F){var D=i(F);
D=c(E,D);
b('<input type="date"/>').attr(D).appendTo(E);
},string:function(E,F){var D=i(F);
D=c(E,D);
b('<input type="text" />').attr(D).appendTo(E);
},"boolean":function(E,F){var D=i(F);
D=c(E,D);
b('<input type="checkbox" />').attr(D).appendTo(E);
},values:function(E,H){var D=i(H);
var G=H.values;
var I=b("<select />");
D=c(E,D);
for(var F in G){b('<option value="'+G[F].value+'">'+G[F].text+"</option>").appendTo(I);
}I.attr(D).appendTo(E);
}};
function d(E,G){var H=E?E.validation||{}:{},F,D;
for(F in H){D=H[F];
if(s(D)&&D.value){D=D.value;
}if(r(D)){G[F]=D;
}}}function y(G,E,F){var D=F?F.shouldRenderHidden||false:false;
if(D){G.val(true);
E.append(b("<input type='hidden' name='"+F.field+"' value='false' data-skip='true' data-validate='false'/>"));
}}var j=C.extend({init:function(D,E){var F=this;
if(E.target){E.$angular=E.target.options.$angular;
if(E.target.pane){F._isMobile=true;
}}C.fn.init.call(F,D,E);
F._validateProxy=b.proxy(F._validate,F);
F.refresh();
},events:[f],options:{name:"Editable",editors:k,mobileEditors:v,clearContainer:true,validateOnBlur:true,validationSummary:false,errorTemplate:m,skipFocus:false},editor:function(G,N){var O=this,F=O._isMobile?v:O.options.editors,K=s(G),H=K?G.field:G,M=O.options.model||{},L=K&&G.values,P=L?"values":o(N),I=K&&G.editor,J=K&&b.inArray(G.editor,u)!==-1,E=I?G.editor:F[P],D=O.element.find("["+t.attr("container-for")+"="+H.replace(w,"\\$1")+"]");
E=E?E:F.string;
if(J){E=F.kendoEditor;
}else{if(I&&typeof G.editor==="string"){E=function(Q){Q.append(G.editor);
};
}}D=D.length?D:O.element;
E(D,n(true,{},K?G:{field:H},{model:M}));
},_validate:function(F){var J=this,H,K=F.value,I=J._validationEventInProgress,L={},D=t.attr("bind"),G=F.field.replace(w,"\\$1"),E=new RegExp("(value|checked)\\s*:\\s*"+G+"\\s*(,|$)");
L[F.field]=F.value;
H=b(":input["+D+'*="'+G+'"]',J.element).filter("["+t.attr("validate")+"!='false']").filter(function(){return E.test(b(this).attr(D));
});
if(H.length>1){H=H.filter(function(){var M=b(this);
return !M.is(":radio")||M.val()==K;
});
}try{J._validationEventInProgress=true;
if(!J.validatable.validateInput(H)||!I&&J.trigger(f,{values:L})){F.preventDefault();
}}finally{J._validationEventInProgress=false;
}},end:function(){return this.validatable.validate();
},destroy:function(){var D=this;
D.angular("cleanup",function(){return{elements:D.element};
});
C.fn.destroy.call(D);
D.options.model.unbind("set",D._validateProxy);
D.options.model.unbind(l,D._validateProxy);
t.unbind(D.element);
if(D.validatable){D.validatable.destroy();
}t.destroy(D.element);
D.element.removeData("kendoValidator");
if(D.element.is("["+t.attr("role")+"=editable]")){D.element.removeAttr(t.attr("role"));
}},refresh:function(){var O=this,H,J,G=O.options.fields||[],D=O.options.clearContainer?O.element.empty():O.element,K=O.options.model||{},N={},E,I,F,L,M;
if(!b.isArray(G)){G=[G];
}for(H=0,J=G.length;
H<J;
H++){E=G[H];
I=s(E);
F=I?E.field:E;
L=(K.fields||K)[F];
d(L,N);
O.editor(E,L);
}if(O.options.target){O.angular("compile",function(){return{elements:D,data:D.map(function(){return{dataItem:K};
})};
});
}if(!J){M=K.fields||K;
for(F in M){d(M[F],N);
}}h(D);
if(O.validatable){O.validatable.destroy();
}t.bind(D,O.options.model);
if(O.options.validateOnBlur){O.options.model.unbind("set",O._validateProxy).bind("set",O._validateProxy);
O.options.model.unbind(l,O._validateProxy).bind(l,O._validateProxy);
}O.validatable=new t.ui.Validator(D,{validateOnBlur:O.options.validateOnBlur,validationSummary:O.options.validationSummary,errorTemplate:O.options.errorTemplate||B,rules:N});
if(!O.options.skipFocus){D.find(":kendoFocusable").eq(0).focus();
}}});
A.plugin(j);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
