(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.gantt",["kendo.data","kendo.resizable","kendo.switch","kendo.gantt.data","kendo.gantt.editors","kendo.gantt.list","kendo.gantt.timeline","kendo.pdf"],b);
}(function(){var a={id:"gantt",name:"Gantt",category:"web",description:"The Gantt component.",depends:["data","resizable","switch","gantt.data","gantt.editors","gantt.list","gantt.timeline","pdf"]};
(function(b,O){var v=window.kendo,w=b.extend({F10:121},v.keys),J="matchMedia" in window,x=v.support.mobileOS,Q=v.ui.Widget,A=v.data.ObservableObject,z=v.data.ObservableArray,F=v.data.Query,s=b.isArray,r=b.inArray,t=v.isFunction,E=b.proxy,m=b.extend,u=b.isPlainObject,C=v._outerWidth,B=v._outerHeight,j=3,y=".kendoGantt",D="p0",K="tabIndex",g="click",I="string",d="aria-activedescendant",e="aria-label",c="gantt_active_cell",l=".",L="Are you sure you want to delete this task?",k="Are you sure you want to delete this dependency?",M=v.template('<button class="#=styles.buttonToggle#" type="button" '+e+'="Toggle"><span class="#=styles.iconToggle#"></span></button>'),f='<button class="#=styles.button# #=className#" type="button" #if (action) {#data-action="#=action#"#}#><span class="#=iconClass#"></span><span class="k-button-text">#=text#</span></button>',h='<a class="#=className#" #=attr# href="\\#">#=text#</a>',P=v.template('<select class="k-dropdown #= styles.viewsDropdown #">#for(var view in views){#<option value="#=view#">#=views[view].title#</option>#}#</select>'),q=v.template('<div class="#=styles.viewsWrapper#"><span class="k-button-group #=styles.views#">#for(var view in views){#<button type="button" class="#=styles.button# #=styles.viewButton#-#= view.toLowerCase() #" data-#=ns#name="#=view#"><span class="k-button-text">#=views[view].title#</span></button>#}#</span></div>');
var p={wrapper:"k-widget k-gantt",plannedTasks:"k-gantt-planned",rowHeight:"k-gantt-rowheight",content:"k-gantt-content",listWrapper:"k-gantt-treelist",list:"k-gantt-treelist",timelineWrapper:"k-gantt-timeline",timeline:"k-gantt-timeline",splitBarWrapper:"k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal",splitBar:"k-splitbar",splitBarHover:"k-splitbar-horizontal-hover",popupWrapper:"k-list-container",popupList:"k-list k-reset",resizeHandle:"k-resize-handle",icon:"k-icon",item:"k-item",line:"k-gantt-line",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"k-primary",hovered:"k-state-hover",selected:"k-state-selected",focused:"k-state-focused",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasks:"k-gantt-tasks",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"k-gantt-header k-toolbar k-gantt-toolbar",footerWrapper:"k-gantt-footer k-toolbar k-gantt-toolbar",toolbar:"k-gantt-toolbar",views:"k-gantt-views",viewsWrapper:"k-gantt-views-wrapper",viewsDropdown:"k-views-dropdown",button:"k-button k-button-icontext",buttonToggle:"k-button k-button-icon k-gantt-toggle",iconPlus:"k-icon k-i-plus",iconPdf:"k-icon k-i-file-pdf",iconToggle:"k-icon k-i-layout-1-by-4",viewButtonDefault:"k-state-default",viewButton:"k-view",link:"k-link",pdfButton:"k-gantt-pdf",appendButton:"k-gantt-create"}};
function H(R){return"["+v.attr("uid")+(R?"='"+R+"']":"]");
}function N(R){delete R.name;
delete R.prefix;
delete R.remove;
delete R.edit;
delete R.add;
delete R.navigate;
return R;
}function n(V,R){var W=V.parents("["+v.attr("role")+'="gantt"]');
var U=[];
var T=G(W);
V.attr(K,0);
if(R){T.each(function(X,Y){U[X]=b(Y).scrollTop();
});
}try{V[0].setActive();
}catch(S){V[0].focus();
}if(R){T.each(function(X,Y){b(Y).scrollTop(U[X]);
});
}}function G(R){return b(R).parentsUntil("body").filter(function(U,T){var S=v.getComputedStyles(T,["overflow"]);
return S.overflow!="visible";
}).add(window);
}var i;
var o=Q.extend({init:function(R,T,S){if(s(T)){T={dataSource:T};
}i={append:{text:"Add Task",action:"add",className:o.styles.toolbar.appendButton,iconClass:o.styles.toolbar.iconPlus},pdf:{text:"Export to PDF",className:o.styles.toolbar.pdfButton,iconClass:o.styles.toolbar.iconPdf}};
Q.fn.init.call(this,R,T);
if(S){this._events=S;
}this._wrapper();
this._resources();
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}this._timeline();
this._toolbar();
this._footer();
this._adjustDimensions();
this._preventRefresh=true;
this.view(this.timeline._selectedViewName);
this._preventRefresh=false;
this._dataSource();
this._assignments();
this._dropDowns();
this._list();
this._dependencies();
this._resizable();
this._scrollable();
this._dataBind();
this._attachEvents();
this._createEditor();
v.notify(this);
},events:["dataBinding","dataBound","add","edit","remove","cancel","save","change","navigate","moveStart","move","moveEnd","resizeStart","resize","resizeEnd","columnHide","columnReorder","columnResize","columnShow","togglePlannedTasks"],options:{name:"Gantt",autoBind:true,navigatable:false,selectable:true,editable:true,resizable:false,columnResizeHandleWidth:j,columns:[],views:[],dataSource:{},dependencies:{},resources:{},assignments:{},taskTemplate:null,messages:{save:"Save",cancel:"Cancel",destroy:"Delete",deleteTaskConfirmation:L,deleteDependencyConfirmation:k,deleteTaskWindowTitle:"Delete task",deleteDependencyWindowTitle:"Delete dependency",views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"},actions:{append:"Add Task",addChild:"Add Child",insertBefore:"Add Above",insertAfter:"Add Below",pdf:"Export to PDF"},editor:{editorTitle:"Task",resourcesEditorTitle:"Resources",title:"Title",start:"Start",end:"End",plannedStart:"Planned Start",plannedEnd:"Planned End",percentComplete:"Complete",resources:"Resources",assignButton:"Assign",resourcesHeader:"Resources",unitsHeader:"Units"},plannedTasks:{switchText:"Planned Tasks",offsetTooltipAdvanced:"Met deadline earlier",offsetTooltipDelay:"Delay",seconds:"seconds",minutes:"minutes",hours:"hours",days:"days"}},showWorkHours:true,showWorkDays:true,toolbar:null,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,snap:true,height:600,listWidth:"30%",rowHeight:null,showPlannedTasks:false},select:function(S){var R=this.list;
if(!S){return R.select();
}if(typeof S===I){S=R.content.find(S);
}R.select(S);
this.list.element.find("table[role=treegrid]").focus();
return;
},clearSelection:function(){this.list.clearSelection();
},destroy:function(){Q.fn.destroy.call(this);
if(this.dataSource){this.dataSource.unbind("change",this._refreshHandler);
this.dataSource.unbind("progress",this._progressHandler);
this.dataSource.unbind("error",this._errorHandler);
}if(this.dependencies){this.dependencies.unbind("change",this._dependencyRefreshHandler);
this.dependencies.unbind("error",this._dependencyErrorHandler);
}if(this.timeline){this.timeline.unbind();
this.timeline.destroy();
}if(this.list){this.list.unbind();
this.list.destroy();
}if(this.footerDropDown){this.footerDropDown.destroy();
}if(this.headerDropDown){this.headerDropDown.destroy();
}if(this._editor){this._editor.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}this.toolbar.off(y);
if(J){this._mediaQuery.removeListener(this._mediaQueryHandler);
this._mediaQuery=null;
}b(window).off("resize"+y,this._resizeHandler);
b(this.wrapper).off(y);
this.toolbar=null;
this.footer=null;
v.destroy(this.element);
},setOptions:function(T){var S=v.deepExtend({},this.options,T);
var R=this._events;
if(!T.views){var U=this.view().name;
S.views=b.map(this.options.views,function(X){var V=u(X);
var W=V?typeof X.type!=="string"?X.title:X.type:X;
if(U===W){if(V){X.selected=true;
}else{X={type:W,selected:true};
}}else{if(V){X.selected=false;
}}return X;
});
}if(!T.dataSource){S.dataSource=this.dataSource;
}if(!T.dependencies){S.dependencies=this.dependencies;
}if(!T.resources){S.resources=this.resources;
}if(!T.assignments){S.assignments=this.assignments;
}this.destroy();
this.element.empty();
this.options=null;
this.init(this.element,S,R);
Q.fn._setEvents.call(this,S);
},_attachEvents:function(){this._resizeHandler=E(this.resize,this,false);
b(window).on("resize"+y,this._resizeHandler);
if(J&&this._mediaQuery.matches===true){this._mediaQueryHandler({matches:true});
}},_wrapper:function(){var R=o.styles;
var U=[R.icon,R.resizeHandle].join(" ");
var T=this.options;
var S=T.height;
var V=T.width;
this.wrapper=this.element.addClass(R.wrapper);
this.layout=b("<div class='"+R.content+"' />").appendTo(this.wrapper).append("<div class='"+R.listWrapper+"'><div></div></div>").append("<div class='"+R.splitBarWrapper+"'><div class='"+U+"'></div></div>").append("<div class='"+R.timelineWrapper+"'><div></div></div>");
if(T.showPlannedTasks){this.wrapper.addClass(R.plannedTasks);
}if(S){this.wrapper.css("height",S);
}if(V){this.wrapper.css("width",V);
}if(T.rowHeight){this.wrapper.addClass(R.rowHeight);
}this.treelistWrapper=this.wrapper.find(l+R.list);
this.splitbar=this.wrapper.find(l+R.splitBar);
this.timelineWrapper=this.wrapper.find(l+R.timeline);
this.treelistWrapper.css("width",T.listWidth);
this.timelineWrapper.css("width",this.wrapper.width()-this.treelistWrapper.outerWidth()-this.splitbar.outerWidth());
},_toolbar:function(){var X=this;
var T=o.styles;
var ag=l+T.toolbar.views+" > button";
var af=l+T.toolbar.viewsDropdown;
var V=l+T.toolbar.pdfButton;
var aa=l+T.buttonToggle;
var S=l+T.gridContent;
var W=X.splitbar;
var ac=X.treelistWrapper;
var Y=X.timelineWrapper;
var R=this.options.toolbar;
var ab;
var ad;
var Z;
var U=function(ah){if(ah.matches){ac.addClass("k-hidden");
W.addClass("k-hidden");
ac.width("100%");
}else{ac.removeClass("k-hidden");
W.removeClass("k-hidden");
Y.removeClass("k-hidden");
ac.width(ac.outerWidth());
X.refresh();
Y.find(S).scrollTop(X.scrollTop);
}X._resize();
};
if(!t(R)){R=typeof R===I?R:this._actions(R);
R=E(v.template(R),this);
}Z=b(M({styles:T.toolbar}));
ad=b(q({ns:v.ns,views:this.timeline.views,styles:T.toolbar}));
ab=b("<div class='"+T.toolbar.headerWrapper+"'>").append(Z).append(R({})).append("<span class='k-spacer k-toolbar-spacer' />").append(ad);
if(ad.find("button").length>1){var ae=b(P({ns:v.ns,views:this.timeline.views,styles:T.toolbar}));
ae.addClass("k-dropdown-wrap k-button");
ad.prepend(ae);
}if(this.toggeSwitchWrap){this.toggeSwitchWrap.insertBefore(ad);
}this.wrapper.prepend(ab);
this.toolbar=ab;
if(J){this._mediaQueryHandler=E(U,this);
this._mediaQuery=window.matchMedia("(max-width: 480px)");
this._mediaQuery.addListener(this._mediaQueryHandler);
}ab.on("change"+y,af,function(){var ah=X.list;
var ai=b(this).val();
if(ah.editable&&ah.editable.trigger("validate")){return;
}if(!X.trigger("navigate",{view:ai})){X.view(ai);
}X.toolbar.find(l+T.focused).removeClass(T.focused);
}).on(g+y,ag,function(ah){ah.preventDefault();
var ai=X.list;
var aj=b(this).attr(v.attr("name"));
if(ai.editor&&!ai.editor.end()){return;
}if(!X.trigger("navigate",{view:aj})){X.view(aj);
}X.toolbar.find(l+T.focused).removeClass(T.focused);
}).on("keydown"+y,ag,function(ah){var aj=b(l+T.toolbar.views).children(":not(.k-current-view)");
var ai=aj.index(X._focusedView&&X._focusedView[0]||aj.closest(l+T.selected)[0]);
if(ah.keyCode===w.RIGHT){b(X.toolbar.find(l+T.focused)).removeClass(T.focused);
X._focusedView=ai+1===aj.length?b(aj[0]):b(aj[ai+1]);
X._focusedView.focus().addClass(T.focused);
ah.preventDefault();
}else{if(ah.keyCode===w.LEFT){b(X.toolbar.find(l+T.focused)).removeClass(T.focused);
X._focusedView=ai===0?b(aj[aj.length-1]):b(aj[ai-1]);
X._focusedView.focus().addClass(T.focused);
ah.preventDefault();
}else{if((ah.keyCode===w.ENTER||ah.keyCode===w.SPACEBAR)&&X._focusedView){X.view(X._focusedView.text().toLowerCase());
ah.preventDefault();
}else{if(ah.keyCode>=49&&ah.keyCode<=57){X.view(X.timeline._viewByIndex(ah.keyCode-49));
}}}}}).on(g+y,V,function(ah){ah.preventDefault();
X.saveAsPDF();
}).on(g+y,aa,function(ah){ah.preventDefault();
if(ac.is(":visible")){ac.addClass("k-hidden");
Y.removeClass("k-hidden");
X.refresh();
Y.find(S).scrollTop(X.scrollTop);
}else{ac.removeClass("k-hidden");
Y.addClass("k-hidden");
ac.find(S).scrollTop(X.scrollTop);
}X._resize();
});
this.wrapper.on("focusout"+y,function(ah){if(!b(ah.relatedTarget).closest(l+T.toolbar.toolbar).length){X.toolbar.find(l+T.focused).removeClass(T.focused);
}if(!b(ah.relatedTarget).closest(l+T.toolbar.views).length){X.toolbar.find(l+T.toolbar.views).removeClass(T.toolbar.expanded);
}});
},_actions:function(){var X=this.options;
var T=X.editable;
var S=X.toolbar;
var U="";
var R;
if(!s(S)){if(T&&T.create!==false){S=["append"];
}else{return U;
}}for(var V=0,W=S.length;
V<W;
V++){R=S[V];
if(R==="plannedTasks"||R.name==="plannedTasks"){this._createPlannedTasksSwitch();
continue;
}U+=this._createButton(R);
}return U;
},_footer:function(){var S=this.options.editable;
if(!S||S.create===false){return;
}var U=o.styles.toolbar;
var V=this.options.messages.actions;
var R=b(v.template(f)(m(true,{styles:U},i.append,{text:V.append})));
var T=b("<div class='"+U.footerWrapper+"'>").append(R);
this.wrapper.append(T);
this.footer=T;
},_createButton:function(S){var W=S.template||f;
var U=this.options.messages.actions;
var T=typeof S===I?S:S.name||S.text;
var R=i[T]?i[T].className:"k-gantt-"+(T||"").replace(/\s/g,"");
var V={iconClass:"",action:"",text:T,className:R,styles:o.styles.toolbar};
if(!T&&!(u(S)&&S.template)){throw new Error("Custom commands should have name specified");
}V=m(true,V,i[T],{text:U[T]});
if(u(S)){if(S.className&&r(V.className,S.className.split(" "))<0){S.className+=" "+V.className;
}V=m(true,V,S);
}return v.template(W)(V);
},_adjustDimensions:function(){var R=this.element;
var V=B(this.toolbar);
var S=this.footer?B(this.footer):0;
var W=R.height();
var X=R.width();
var T=this.splitbar.is(":visible")?C(this.splitbar):0;
var Y=this.treelistWrapper.is(":visible")?C(this.treelistWrapper):0;
var U=X-(Y+T);
this.layout.children().height(W-(V+S));
this.timelineWrapper.width(U);
if(X<Y+T){this.treelistWrapper.width(X-T);
}},_scrollTo:function(X){var Y=this.timeline.view();
var U=this.list;
var S=v.attr("uid");
var T=typeof X==="string"?X:X.closest("tr"+H()).attr(S);
var R;
var W;
var V=function(){if(W.length!==0){R();
}};
if(Y.content.is(":visible")){W=Y.content.find(H(T));
R=function(){Y._scrollTo(W);
};
}else{W=U.element.find(H(T));
R=function(){W.get(0).scrollIntoView();
};
}V();
},_dropDowns:function(){var V=this;
var S=l+o.styles.toolbar.appendButton;
var R=this.options.messages.actions;
var W=this.timeline;
var T=this.options.editable;
var U=function(Y){var ag=Y.type;
var ab;
var X=V.dataSource;
var af=X._createNewModel({});
var ad=V.dataItem(V.select());
var ac=X.taskParent(ad);
var aa=W.view()._timeSlots()[0];
var ae=ag==="add"?ad:ac;
var Z=V.list.editor;
if(Z&&Z.trigger("validate")){return;
}af.set("title","New task");
if(ae){af.set("parentId",ae.get("id"));
af.set("start",ae.get("start"));
af.set("end",ae.get("end"));
af.set("plannedStart",ae.get("plannedStart"));
af.set("plannedEnd",ae.get("plannedEnd"));
}else{af.set("start",aa.start);
af.set("end",aa.end);
}if(ag!=="add"){ab=ad.get("orderId");
ab=ag==="insert-before"?ab:ab+1;
}V._createTask(af,ab);
};
if(!T||T.create===false){return;
}this.footerDropDown=new v.gantt.TaskDropDown(this.footer.children(S).eq(0),{messages:{actions:R},direction:"up",animation:{open:{effects:"slideIn:up"}},navigatable:V.options.navigatable});
this.headerDropDown=new v.gantt.TaskDropDown(this.toolbar.children(S).eq(0),{messages:{actions:R},navigatable:V.options.navigatable});
this.footerDropDown.bind("command",U);
this.headerDropDown.bind("command",U);
},_getListEditable:function(){var R=false,S=this.options;
if(S.editable!==false){R="incell";
if(S.editable&&S.editable.update===false){R=false;
}else{if(!S.editable||S.editable.reorder!==false){R={mode:"incell",move:{reorderable:true}};
}}}return R;
},_getListOptions:function(){var U=this.options,R=this._getListEditable(),T=this.wrapper.find(l+p.list),S={columns:U.columns||[],dataSource:this.dataSource,selectable:U.selectable,reorderable:U.reorderable,editable:R,resizable:U.resizable,filterable:U.filterable,columnMenu:U.columnMenu,columnResizeHandleWidth:this.options.columnResizeHandleWidth,listWidth:C(T),resourcesField:this.resources.field,rowHeight:this.options.rowHeight};
return S;
},_attachResourceEditor:function(S){var R;
for(var T=0;
T<S.length;
T++){R=S[T];
if(R.field===this.resources.field&&typeof R.editor!=="function"){R.editor=E(this._createResourceEditor,this);
}}},_attachListEvents:function(){var T=this,R=T.options.navigatable,U=this.wrapper.find(l+o.styles.toolbar.toolbar+" "+l+o.styles.toolbar.appendButton),S=function(){var V;
if(R&&T._cachedCurrent){V=T.list.content.find("tr").eq(T._cachedCurrent.rowIndex).find("td").eq(T._cachedCurrent.columnIndex);
T._current(V);
n(T.list.content.find("table"),true);
}delete T._cachedCurrent;
};
T.list.bind("columnShow",function(V){T.trigger("columnShow",{column:V.column});
}).bind("columnHide",function(V){T.trigger("columnHide",{column:V.column});
}).bind("columnReorder",function(V){T.trigger("columnReorder",{column:V.column,oldIndex:V.oldIndex,newIndex:V.newIndex});
}).bind("columnResize",function(V){T.trigger("columnResize",{column:V.column,oldWidth:V.oldWidth,newWidth:V.newWidth});
}).bind("render",function(){T._navigatable();
},true).bind("beforeEdit",function(V){T._cachedCurrent={rowIndex:V.container.closest("tr").index(),columnIndex:V.container.index()};
if(T.trigger("edit",{task:V.model,container:V.container})){V.preventDefault();
}}).bind("cancel",function(V){if(T.trigger("cancel",{task:V.model,container:V.cell})){V.preventDefault();
return;
}T._preventItemChange=true;
T.list.closeCell(true);
S();
}).bind("save",function(V){var W=V.values;
T._preventRefresh=true;
if(T.updateDuration===null||T.updateDuration===O){T.updateDuration=V.model.duration();
}if(W.hasOwnProperty("start")){W.end=new Date(W.start.getTime()+T.updateDuration);
}T.updatedValues=W;
}).bind("itemChange",function(V){var Z=T.updatedValues;
var Y=V.data;
var X=T.resources.field;
if(T._preventItemChange){T._preventItemChange=false;
return;
}var W=T.element.get(0).control;
if(W._postBackOnTaskUpdate){T.dataSource.transport.set_postback(true);
if(T.dependencies.transport.set_postback){T.dependencies.transport.set_postback(true);
}if(T.assignments.dataSource.transport.set_postback){T.assignments.dataSource.transport.set_postback(true);
}}if(!T.trigger("save",{task:Y,values:Z})){if(Z){T._preventRefresh=true;
T.dataSource.update(Y,Z);
if(Z[X]){T._updateAssignments(Y.get("id"),Z[X]);
}}T._preventRefresh=false;
T._requestStart();
T.dataSource.sync().then(function(){S();
});
var W=T.element.get(0).control;
if(W._postBackOnTaskUpdate&&W._commandsCache){W._commandsCache.commandName="Postback";
W.postback(W._commandsCache);
}}else{if(T.dataSource.hasChanges()){T.dataSource.cancelChanges();
T._preventRefresh=false;
T.refresh();
}}T.updatedValues=null;
T.updateDuration=null;
}).bind("change",function(){T.trigger("change");
var V=T.list.select();
if(V.length){U.removeAttr("data-action","add");
T.timeline.select("[data-uid='"+V.attr("data-uid")+"']");
}else{U.attr("data-action","add");
T.timeline.clearSelection();
}}).bind("collapse",function(V){V.preventDefault();
var W=T.list.element.find("tr[data-uid='"+V.model.uid+"']");
V.model.set("expanded",false);
T._cachedCurrent={rowIndex:W.index(),columnIndex:W.find(".k-state-focused").index()};
S();
}).bind("expand",function(V){V.preventDefault();
var W=T.list.element.find("tr[data-uid='"+V.model.uid+"']");
V.model.set("expanded",true);
T._cachedCurrent={rowIndex:W.index(),columnIndex:W.find(".k-state-focused").index()};
S();
}).bind("dragend",function(W){var V=T.dataSource,Y,Z;
if(W.position==="over"){Z={parentId:W.source.parentId};
V.cancelChanges();
Y=V.get(W.source.id);
var X=T.element.get(0).control;
if(X._postBackOnTaskUpdate){T.dataSource.transport.set_postback(true);
if(T.dependencies.transport.set_postback){T.dependencies.transport.set_postback(true);
}if(T.assignments.dataSource.transport.set_postback){T.assignments.dataSource.transport.set_postback(true);
}}if(!T.trigger("save",{task:Y,values:Z})){V.update(Y,Z);
}}V.sync();
var X=T.element.get(0).control;
if(X._postBackOnTaskUpdate&&X._commandsCache){X._commandsCache.commandName="Postback";
X.postback(X._commandsCache);
}}).bind("dataBound",function(){if(T.dataSource.sort().length===0){T.dataSource.sort([{field:"orderId",dir:"asc"}]);
}}).bind("reorder",function(V){T._updateTask(V.task,V.updateInfo);
S();
});
},_list:function(){var R=o.styles,U=this.wrapper.find(l+R.list),S=U.find("> div"),T=this._getListOptions();
this._attachResourceEditor(T.columns);
this.list=new v.ui.GanttList(S,T);
this._attachListEvents();
},_timeline:function(){var U=this;
var S=o.styles;
var T=N(m(true,{resourcesField:this.resources.field},this.options));
var R=this.wrapper.find(l+S.timeline+" > div");
this.timeline=new v.ui.GanttTimeline(R,T);
this.timeline.bind("navigate",function(V){var W=V.view.replace(/\./g,"\\.").toLowerCase();
U.toolbar.find(l+S.toolbar.views+" > button").removeClass(S.selected).end().find(l+S.toolbar.viewButton+"-"+W).addClass(S.selected);
U.toolbar.find(l+S.toolbar.viewsDropdown).val(W);
U.refresh();
}).bind("moveStart",function(V){var W=U.list.editor;
if(W&&!W.end()){V.preventDefault();
return;
}if(U.trigger("moveStart",{task:V.task})){V.preventDefault();
}}).bind("move",function(V){var Y=V.task;
var X=V.start;
var W=new Date(X.getTime()+Y.duration());
if(U.trigger("move",{task:Y,start:X,end:W})){V.preventDefault();
}}).bind("moveEnd",function(V){var Y=V.task;
var X=V.start;
var W=new Date(X.getTime()+Y.duration());
if(!U.trigger("moveEnd",{task:Y,start:X,end:W})){U._updateTask(U.dataSource.getByUid(Y.uid),{start:X,end:W});
}}).bind("resizeStart",function(V){var W=U.list.editor;
if(W&&!W.end()){V.preventDefault();
return;
}if(U.trigger("resizeStart",{task:V.task})){V.preventDefault();
}}).bind("resize",function(V){if(U.trigger("resize",{task:V.task,start:V.start,end:V.end})){V.preventDefault();
}}).bind("resizeEnd",function(V){var W=V.task;
var X={};
if(V.resizeStart){X.start=V.start;
}else{X.end=V.end;
}if(!U.trigger("resizeEnd",{task:W,start:V.start,end:V.end})){U._updateTask(U.dataSource.getByUid(W.uid),X);
}}).bind("percentResizeStart",function(V){var W=U.list.editor;
if(W&&!W.end()){V.preventDefault();
}}).bind("percentResizeEnd",function(V){U._updateTask(U.dataSource.getByUid(V.task.uid),{percentComplete:V.percentComplete});
}).bind("dependencyDragStart",function(V){var W=U.list.editor;
if(W&&!W.end()){V.preventDefault();
}}).bind("dependencyDragEnd",function(W){var V=U.dependencies._createNewModel({type:W.type,predecessorId:W.predecessor.id,successorId:W.successor.id});
U._createDependency(V);
}).bind("select",function(V){var W=U.list.editor;
if(W){W.end();
}U.select("[data-uid='"+V.uid+"']");
}).bind("editTask",function(V){var W=U.list.editor;
if(W&&!W.end()){return;
}U.editTask(V.uid);
}).bind("clear",function(){U.clearSelection();
}).bind("removeTask",function(V){var W=U.list.editor;
if(W&&!W.end()){return;
}U.removeTask(U.dataSource.getByUid(V.uid));
}).bind("removeDependency",function(V){var W=U.list.editor;
if(W&&!W.end()){return;
}U.removeDependency(U.dependencies.getByUid(V.uid));
});
},_dataSource:function(){var S=this.options;
var R=S.dataSource;
R=s(R)?{data:R}:R;
if(this.dataSource&&this._refreshHandler){this.dataSource.unbind("change",this._refreshHandler).unbind("progress",this._progressHandler).unbind("error",this._errorHandler);
}else{this._refreshHandler=E(this.refresh,this);
this._progressHandler=E(this._requestStart,this);
this._errorHandler=E(this._error,this);
}this.dataSource=v.data.GanttDataSource.create(R).bind("change",this._refreshHandler).bind("progress",this._progressHandler).bind("error",this._errorHandler);
},_dependencies:function(){var S=this.options.dependencies||{};
var R=s(S)?{data:S}:S;
if(this.dependencies&&this._dependencyRefreshHandler){this.dependencies.unbind("change",this._dependencyRefreshHandler).unbind("error",this._dependencyErrorHandler);
}else{this._dependencyRefreshHandler=E(this.refreshDependencies,this);
this._dependencyErrorHandler=E(this._error,this);
}this.dependencies=v.data.GanttDependencyDataSource.create(R).bind("change",this._dependencyRefreshHandler).bind("error",this._dependencyErrorHandler);
},_resources:function(){var S=this.options.resources;
var R=S.dataSource||{};
this.resources={field:"resources",dataTextField:"name",dataColorField:"color",dataFormatField:"format"};
m(this.resources,S);
this.resources.dataSource=v.data.DataSource.create(R);
},_assignments:function(){var R=this.options.assignments;
var S=R.dataSource||{};
if(this.assignments){this.assignments.dataSource.unbind("change",this._assignmentsRefreshHandler);
}else{this._assignmentsRefreshHandler=E(this.refresh,this);
}this.assignments={dataTaskIdField:"taskId",dataResourceIdField:"resourceId",dataValueField:"value"};
m(this.assignments,R);
this.assignments.dataSource=v.data.DataSource.create(S);
this.assignments.dataSource.bind("change",this._assignmentsRefreshHandler);
},_createEditor:function(){var S=this;
var R=this._editor=new v.gantt.PopupEditor(this.wrapper,m({},this.options,{target:this,resources:{field:this.resources.field,editor:E(this._createResourceEditor,this)},createButton:E(this._createPopupButton,this)}));
R.bind("cancel",function(T){var U=S.dataSource.getByUid(T.model.uid);
if(S.trigger("cancel",{container:T.container,task:U})){T.preventDefault();
return;
}S.cancelTask();
}).bind("edit",function(T){var U=S.dataSource.getByUid(T.model.uid);
if(S.trigger("edit",{container:T.container,task:U})){T.preventDefault();
}}).bind("save",function(T){var U=S.dataSource.getByUid(T.model.uid);
S.saveTask(U,T.updateInfo);
}).bind("remove",function(T){S.removeTask(T.model.uid);
}).bind("close",S._onDialogClose);
},_onDialogClose:function(){},_createResourceEditor:function(S,X){var Z=this;
var W=X instanceof A?X:X.model;
var U=W.get("id");
var V=this.options.messages;
var Y=this.resources.field;
var aa={step:0.01};
var R=this.assignments.dataSource.options.schema.model;
if(R&&R.fields.Units&&R.fields.Units.validation){m(true,aa,R.fields.Units.validation);
}var T=this._resourceEditor=new v.gantt.ResourceEditor(S,{resourcesField:Y,unitsValidation:aa,data:this._wrapResourceData(U),model:W,messages:m({},V.editor),buttons:[{name:"update",text:V.save,className:o.styles.primary},{name:"cancel",text:V.cancel}],createButton:E(this._createPopupButton,this),save:function(ab){Z._updateAssignments(ab.model.get("id"),ab.model.get(Y));
}});
T.open();
},_createPopupButton:function(R){var S=R.name||R.text;
var T={className:o.styles.popup.button+" k-gantt-"+(S||"").replace(/\s/g,""),text:S,attr:""};
if(!S&&!(u(R)&&R.template)){throw new Error("Custom commands should have name specified");
}if(u(R)){if(R.className){R.className+=" "+T.className;
}T=m(true,T,R);
}return v.template(h)(T);
},view:function(R){return this.timeline.view(R);
},range:function(S){var R=this.dataSource;
var U=this.view();
var T=this.timeline;
if(S){U.options.range={start:S.start,end:S.end};
T._render(R.taskTree());
T._renderDependencies(this.dependencies.view());
}return{start:U.start,end:U.end};
},date:function(R){var S=this.view();
if(R){S.options.date=R;
S._scrollToDate(R);
}return S.options.date;
},dataItem:function(T){if(!T){return null;
}var S=this.list;
var R=S.element.find(T);
return S._modelFromElement(R);
},setDataSource:function(R){this.options.dataSource=R;
this._dataSource();
this.list.setDataSource(this.dataSource);
if(this.options.autoBind){R.fetch();
}},setDependenciesDataSource:function(R){this.options.dependencies=R;
this._dependencies();
if(this.options.autoBind){R.fetch();
}},items:function(){return this.wrapper.children(".k-task");
},_updateAssignments:function(W,ac){var T=this.assignments.dataSource;
var ad=this.assignments.dataTaskIdField;
var ab=this.assignments.dataResourceIdField;
var U=false;
var S=new F(T.view()).filter({field:ad,operator:"eq",value:W}).toArray();
var R;
var aa;
var ae;
while(S.length){R=S[0];
for(var V=0,Y=ac.length;
V<Y;
V++){aa=ac[V];
if(R.get(ab)===aa.get("id")){ae=ac[V].get("value");
this._updateAssignment(R,ae);
ac.splice(V,1);
U=true;
break;
}}if(!U){this._removeAssignment(R);
}U=false;
S.shift();
}for(var X=0,Z=ac.length;
X<Z;
X++){aa=ac[X];
this._createAssignment(aa,W);
}T.sync();
},cancelTask:function(){var S=this._editor;
var R=S.container;
if(R){S.close();
}},editTask:function(T){var R=typeof T==="string"?this.dataSource.getByUid(T):T;
if(!R){return;
}var S=this.dataSource._createNewModel(R.toJSON());
S.uid=R.uid;
this.cancelTask();
this._editTask(S);
},_editTask:function(R){this._editor.editTask(R,this.options.editable.plannedTasks);
},saveTask:function(U,V){var T=this._editor;
var R=T.container;
var S=T.editable;
if(R&&S&&S.end()){this._updateTask(U,V);
}},_updateTask:function(S,U){var T=this;
var R=T.resources.field;
if(!T.trigger("save",{task:S,values:U})){if(U){T._preventRefresh=true;
T.dataSource.update(S,U);
if(U[R]){T._updateAssignments(S.get("id"),U[R]);
}}T._syncDataSource();
}else{if(T.dataSource.hasChanges()){T.dataSource.cancelChanges();
T._preventRefresh=false;
T.refresh();
}}},_updateAssignment:function(R,T){var S=this.assignments.dataValueField;
R.set(S,T);
},removeTask:function(T){var S=this;
var R=typeof T==="string"?this.dataSource.getByUid(T):T;
if(!R){return;
}this._taskConfirm(function(U){if(!U){S._removeTask(R);
}},R);
},_createTask:function(T,S){if(!this.trigger("add",{task:T,dependency:null})){var R=this.dataSource;
this._preventRefresh=true;
if(S===O){R.add(T);
}else{R.insert(S,T);
}this._scrollToUid=T.uid;
this._syncDataSource();
}},_createDependency:function(R){if(!this.trigger("add",{task:null,dependency:R})){this._preventDependencyRefresh=true;
this.dependencies.add(R);
this._preventDependencyRefresh=false;
this.dependencies.sync();
}},_createAssignment:function(V,U){var S=this.assignments;
var T=S.dataSource;
var Y=S.dataTaskIdField;
var W=S.dataResourceIdField;
var X=S.dataValueField;
var R=T._createNewModel();
R[Y]=U;
R[W]=V.get("id");
R[X]=V.get("value");
T.add(R);
},removeDependency:function(T){var S=this;
var R=typeof T==="string"?this.dependencies.getByUid(T):T;
if(!R){return;
}this._dependencyConfirm(function(U){if(!U){S._removeDependency(R);
}},R);
},_removeTaskDependencies:function(U,R){this._preventDependencyRefresh=true;
for(var S=0,T=R.length;
S<T;
S++){this.dependencies.remove(R[S]);
}this._preventDependencyRefresh=false;
this.dependencies.sync();
},_removeTaskAssignments:function(W){var S=this.assignments.dataSource;
var R=S.view();
var T={field:this.assignments.dataTaskIdField,operator:"eq",value:W.get("id")};
R=new F(R).filter(T).toArray();
this._preventRefresh=true;
for(var U=0,V=R.length;
U<V;
U++){S.remove(R[U]);
}this._preventRefresh=false;
S.sync();
},_removeTask:function(S){var R=this.dependencies.dependencies(S.id);
if(!this.trigger("remove",{task:S,dependencies:R})){this._removeTaskDependencies(S,R);
this._removeTaskAssignments(S);
this._preventRefresh=true;
if(this.dataSource.remove(S)){this._syncDataSource();
}this._preventRefresh=false;
}},_removeDependency:function(R){if(!this.trigger("remove",{task:null,dependencies:[R]})){if(this.dependencies.remove(R)){this.dependencies.sync();
}}},_removeAssignment:function(R){this.assignments.dataSource.remove(R);
},_taskConfirm:function(R,T){var S=this.options.messages;
this._confirm(R,{model:T,text:S.deleteTaskConfirmation,title:S.deleteTaskWindowTitle});
},_dependencyConfirm:function(R,S){var T=this.options.messages;
this._confirm(R,{model:S,text:T.deleteDependencyConfirmation,title:T.deleteDependencyWindowTitle});
},_confirm:function(S,V){var T=this.options.editable;
var U;
var R;
if(T===true||T.confirmation!==false){U=this.options.messages;
R=[{name:"delete",text:U.destroy,className:o.styles.primary,click:function(){S();
}},{name:"cancel",text:U.cancel,click:function(){S(true);
}}];
this.showDialog(m(true,{},V,{buttons:R}));
}else{S();
}},showDialog:function(R){this._editor.showDialog(R);
},refresh:function(){if(this._preventRefresh||!this.list||this.list.editor){return;
}this._progress(false);
var U=this.dataSource;
var W=U.taskTree();
var V=this._scrollToUid;
var T;
var S;
var R=-1;
if(this.current){S=this.current.closest("tr").attr(v.attr("uid"));
R=this.current.index();
}if(this.trigger("dataBinding")){return;
}if(this.resources.dataSource.data().length!==0){this._assignResources(W);
}if(this._editor){this._editor.close();
}this.clearSelection();
this.list._renderTree(W);
this.timeline._render(W);
this.timeline._renderDependencies(this.dependencies.view());
if(V){this._scrollTo(V);
this.select(H(V));
}if((V||S)&&R>=0){T=this.list.element.find("tr"+H(V||S)+" > td:eq("+R+")");
this._current(T);
}this._scrollToUid=null;
this.trigger("dataBound");
},refreshDependencies:function(){if(this._preventDependencyRefresh){return;
}if(this.trigger("dataBinding")){return;
}this.timeline._renderDependencies(this.dependencies.view());
this.trigger("dataBound");
},_assignResources:function(Y){var X=this.resources;
var T=this.assignments;
var U=function(){var aa=T.dataSource.view();
var ab={field:T.dataTaskIdField};
aa=new F(aa).group(ab).toArray();
return aa;
};
var S=U();
var R=function(ad,aa){var ae=ad.get("id");
v.setter(X.field)(ad,new z([]));
for(var ab=0,ac=S.length;
ab<ac;
ab++){if(S[ab].value===ae){aa(ad,S[ab].items);
}}};
var Z=function(ai,ac){for(var ad=0,ae=ac.length;
ad<ae;
ad++){var ab=ac[ad];
var af=X.dataSource.get(ab.get(T.dataResourceIdField));
var ah=ab.get(T.dataValueField);
var ag=ab.get(T.dataResourceIdField);
var aj=af.get(X.dataFormatField)||D;
var aa=v.toString(ah,aj);
ai[X.field].push(new A({id:ag,name:af.get(X.dataTextField),color:af.get(X.dataColorField),value:ah,formatedValue:aa}));
}};
for(var V=0,W=Y.length;
V<W;
V++){R(Y[V],Z);
}},_wrapResourceData:function(T){var Z=this;
var X=[];
var V;
var W=this.resources.dataSource.view();
var R=this.assignments.dataSource.view();
var Y=new F(R).filter({field:Z.assignments.dataTaskIdField,operator:"eq",value:T}).toArray();
var aa=function(ab){var ac=null;
new F(Y).filter({field:Z.assignments.dataResourceIdField,operator:"eq",value:ab}).select(function(ad){ac+=ad.get(Z.assignments.dataValueField);
});
return ac;
};
for(var S=0,U=W.length;
S<U;
S++){V=W[S];
X.push({id:V.get("id"),name:V.get(Z.resources.dataTextField),format:V.get(Z.resources.dataFormatField)||D,value:aa(V.id)});
}return X;
},_syncDataSource:function(){this._preventRefresh=false;
this._requestStart();
this.dataSource.sync();
},_requestStart:function(){this._progress(true);
},_error:function(){this._progress(false);
},_progress:function(R){v.ui.progress(this.element,R);
},_resizable:function(){var T=this;
var Z=this.wrapper;
var S=o.styles;
var R=l+S.gridContent;
var Y=Z.find(l+S.list);
var W=Z.find(l+S.timeline);
var X;
var V;
var U;
this._resizeDraggable=Z.find(l+S.splitBar).height(Y.height()).hover(function(){b(this).addClass(S.splitBarHover);
},function(){b(this).removeClass(S.splitBarHover);
}).end().kendoResizable({orientation:"horizontal",handle:l+S.splitBar,start:function(){X=Y.width();
V=W.width();
U=v.scrollLeft(W.find(R));
},resize:function(ab){var aa=ab.x.initialDelta;
if(v.support.isRtl(Z)){aa*=-1;
}if(X+aa<0||V-aa<0){return;
}Y.width(X+aa);
W.width(V-aa);
v.scrollLeft(W.find(R),U+aa);
T.timeline.view()._renderCurrentTime();
}}).data("kendoResizable");
},_scrollable:function(){var V=this;
var S=o.styles;
var U=v.ui.GanttList.listStyles;
var R=l+S.gridContent;
var T=l+S.gridHeaderWrap;
var X=this.timeline.element.find(T);
var W=this.timeline.element.find(R);
var Z=this.list.element.find("."+U.gridHeaderWrap);
var Y=this.list.element.find("."+U.gridContent);
if(x){Y.css("overflow-y","auto");
}W.on("scroll",function(){V.scrollTop=this.scrollTop;
v.scrollLeft(X,this.scrollLeft);
Y.scrollTop(this.scrollTop);
});
Y.on("scroll",function(){v.scrollLeft(Z,this.scrollLeft);
}).on("DOMMouseScroll"+y+" mousewheel"+y,function(ab){var ac=W.scrollTop();
var aa=v.wheelDeltaY(ab);
if(aa){ab.preventDefault();
b(ab.currentTarget).one("wheel"+y,false);
W.scrollTop(ac+-aa);
}});
},_navigatable:function(){var ai=this;
var ae=this.options.navigatable;
var W=this.options.editable;
var Y=o.styles;
var T=l+v.ui.GanttList.styles.gridContent;
var Z=l+Y.gridHeaderWrap;
var aa=this.list.element.find(Z).find("table");
var U=this.list.element.find(T).find("table");
var ab=v.support.isRtl(this.wrapper);
var aj=this.timeline.element.find(l+Y.gridContent);
var ah=aa.add(U);
var R=H();
var S;
var X={collapse:false,expand:true};
var af=function(al){var am=ai.timeline.view()._timeSlots()[0].offsetWidth;
v.scrollLeft(aj,v.scrollLeft(aj)+(al?-am:am));
};
var ag=function(am){var al=ai.timeline.view()._rowHeight;
aj.scrollTop(aj.scrollTop()+(am?-al:al));
};
var ad=function(am){var an=ai.current.parent("tr"+H());
var al=ai.current.index();
var ao=an[am]("tr:visible").first();
if(ai.select().length!==0){ai.clearSelection();
}if(ao.length!==0){ai._current(ao.children("td:eq("+al+")"));
ai._scrollTo(ai.current);
}else{if(ai.current.is("td")&&am=="prevAll"){n(aa);
}else{if(ai.current.is("th")&&am=="nextAll"){n(U);
}}}};
var ac=function(al){var am=ai.current[al]();
if(am.length!==0){ai._current(am);
S=ai.current.index();
}};
var ak=function(am){var al=ai.dataItem(ai.current);
if(al.summary&&al.expanded!==am){al.set("expanded",am);
}};
var V=function(){var al=ai.options.editable;
if(!al||al.destroy===false||ai.list.editor){return;
}var am=ai.select();
var an=v.attr("uid");
if(am.length){ai.removeTask(am.attr(an));
}};
b(this.wrapper).on("mousedown"+y,"tr"+R+", div"+R+":not("+l+Y.line+")",function(an){var am=b(an.currentTarget);
var ao=b(an.target).is(":button,a,:input,a>.k-icon,textarea,span.k-icon:not(.k-i-none),span.k-link,.k-input,.k-multiselect-wrap");
var al;
if(an.ctrlKey){return;
}if(ae){if(am.is("tr")){al=b(an.target).closest("td");
}else{al=ai.list.content.find("tr"+H(am.attr(v.attr("uid")))+" > td:first");
}ai._current(al);
}if((ae||W)&&!ao){ai._focusTimeout=setTimeout(function(){n(ai.list.content.find("table"),true);
},2);
}}).on("keydown"+y,function(al){var ap=al.keyCode;
var aq=this;
var am=b(aq._getToolbarItems());
var an=am.index(aq.toolbar.find(l+Y.focused)[0]);
if(an===-1&&b(al.target).closest(l+Y.toolbar.views).length){an=am.index(aq.toolbar.find(".k-gantt-views > .k-state-selected:visible, .k-views-dropdown:visible")[0]);
}var ao=al.shiftKey?am[an-1]:am[an+1];
if(ap===w.F10){aq.toolbar.find(".k-button:visible:first").addClass(Y.focused).focus();
al.preventDefault();
}else{if(ap==w.TAB&&b(al.target).closest(l+Y.toolbar.toolbar).length){aq.toolbar.find(l+Y.focused).removeClass(Y.focused).blur();
if(ao){b(ao).addClass(Y.focused).focus();
al.preventDefault();
return;
}if(this.list.element.is(":visible")){this.list.element.find("table[role=treegrid]").focus();
}else{this.element.find(l+Y.tasks)[0].focus();
}al.preventDefault();
}}}.bind(this));
if(ae!==true){U.on("keydown"+y,function(al){if(al.keyCode==w.DELETE){V();
}});
return;
}ah.on("focus"+y,function(){var an=this===U.get(0)?"td":"th";
var am=ai.select();
var al=ai.current||b(am.length?am:this).find(an+":eq("+(S||0)+")");
ai._current(al);
b(ai.toolbar.find(l+Y.focused)).removeClass(Y.focused);
}).on("blur"+y,function(){ai._current();
if(this==aa){b(this).attr(K,-1);
}}).on("keydown"+y,function(al){var an=al.keyCode;
var am;
if(!ai.current){return;
}am=ai.current.is("td");
switch(an){case w.RIGHT:al.preventDefault();
if(al.altKey){af();
}else{if(al.ctrlKey){ak(ab?X.collapse:X.expand);
}else{ac(ab?"prev":"next");
}}break;
case w.LEFT:al.preventDefault();
if(al.altKey){af(true);
}else{if(al.ctrlKey){ak(ab?X.expand:X.collapse);
}else{ac(ab?"next":"prev");
}}break;
case w.UP:al.preventDefault();
if(al.altKey){ag(true);
}else{ad("prevAll");
}break;
case w.DOWN:al.preventDefault();
if(al.altKey){ag();
}else{ad("nextAll");
}break;
case w.SPACEBAR:al.preventDefault();
if(am){ai.select(ai.current.closest("tr"));
}break;
case w.ENTER:al.preventDefault();
if(am){if(ai.options.editable&&ai.options.editable.update!==false){ai.list._startEditHandler(ai.current);
b(this).one("keyup",function(ao){ao.stopPropagation();
});
}}else{ai.current.children("a.k-link").click();
}break;
case w.DELETE:if(am){V();
}break;
default:if(an>=49&&an<=57&&al.target.tagName.toLowerCase()!=="input"){ai.view(ai.timeline._viewByIndex(an-49));
}break;
}});
},_getToolbarItems:function(){return this.toolbar.find("> .k-button:visible").toArray().concat(this.toolbar.find(".k-views-dropdown:visible").toArray(),this.toolbar.find(".k-gantt-views > .k-state-selected:visible").toArray());
},_current:function(S){var T=o.styles;
var R;
if(this.current&&this.current.length){this.current.removeClass(T.focused).removeAttr("id");
}if(S&&S.length){this.current=S.addClass(T.focused).attr("id",c);
R=b(v._activeElement());
if(R.is("table")&&this.wrapper.find(R).length>0){R.removeAttr(d).attr(d,c);
}}else{this.current=null;
}},_dataBind:function(){var S=this;
if(S.options.autoBind){this._preventRefresh=true;
this._preventDependencyRefresh=true;
var R=b.map([this.dataSource,this.dependencies,this.resources.dataSource,this.assignments.dataSource],function(T){return T.fetch();
});
b.when.apply(null,R).done(function(){S._preventRefresh=false;
S._preventDependencyRefresh=false;
S.refresh();
});
}},_resize:function(){this._adjustDimensions();
this.timeline.view()._adjustHeight();
this.timeline.view()._renderCurrentTime();
this.list._adjustHeight();
},_createPlannedTasksSwitch:function(){var T=this;
var S=T.options.messages.plannedTasks.switchText;
var U=b("<span class='k-gantt-planned-wrap'><label>"+S+"</label></span>");
var R=new v.ui.Switch(b("<input id='planned-switch' class='k-gantt-planned-switch'>"),{checked:T.options.showPlannedTasks,change:E(T._togglePlannedTasks,T),messages:{checked:"",unchecked:""}});
U.append(R.wrapper);
T.toggeSwitchWrap=U;
T.toggleSwitch=R;
},_togglePlannedTasks:function(R){var S=this.timeline;
if(!this.trigger("togglePlannedTasks",{showPlannedTasks:!S.options.showPlannedTasks})){this.wrapper.toggleClass(p.plannedTasks);
S._setPlanned(!S.options.showPlannedTasks);
S._render(this.dataSource.taskTree());
S._renderDependencies(this.dependencies.view());
}else{R.preventDefault();
}}});
if(v.PDFMixin){v.PDFMixin.extend(o.fn);
o.fn._drawPDF=function(){var S=o.styles;
var T=this.wrapper.find(".rgtTreelistContent >table").width();
var R=this.wrapper.clone();
R.find(l+S.list).css("width",T);
return this._drawPDFShadow({content:R},{avoidLinks:this.options.pdf.avoidLinks});
};
}v.ui.plugin(o);
m(true,o,{styles:p});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
