(function(b,a){a("kendo.list",["kendo.data","kendo.popup"],b);
}(function(){var a={id:"list",name:"List",category:"framework",depends:["data","popup"],hidden:true};
(function(b,U){var x=window.kendo,T=x.ui,G=x._outerHeight,I=/^\d+(\.\d+)?%$/i,W=T.Widget,y=x.keys,S=x.support,r=x.htmlEncode,c=x._activeElement,H=x._outerWidth,E=x.data.ObservableArray,s="id",h="change",l="k-state-focused",q="k-state-hover",C="k-i-loading",o=".k-group-header",w=".k-item",z="_label",F="open",i="close",g="cascade",O="select",P="selected",N="requestStart",M="requestEnd",e="blur",k="focus",m="focusout",j=b.extend,J=b.proxy,t=b.isArray,f=S.browser,p="k-hidden",X="width",u=f.msie,K=/"/g,d={ComboBox:["DropDownList","MultiColumnComboBox"],DropDownList:["ComboBox","MultiColumnComboBox"],MultiColumnComboBox:["ComboBox","DropDownList"]};
var B=x.ui.DataBoundWidget.extend({init:function(Y,ab){var ac=this,aa=ac.ns,Z;
W.fn.init.call(ac,Y,ab);
Y=ac.element;
ab=ac.options;
ac._isSelect=Y.is(O);
if(ac._isSelect&&ac.element[0].length){if(!ab.dataSource){ab.dataTextField=ab.dataTextField||"text";
ab.dataValueField=ab.dataValueField||"value";
}}ac.ul=b('<ul unselectable="on" class="k-list k-reset"/>').attr({tabIndex:-1,"aria-hidden":true});
ac.list=b("<div class='k-list-container'/>").append(ac.ul).on("mousedown"+aa,J(ac._listMousedown,ac));
Z=Y.attr(s);
if(!Z){Z=x.guid();
}ac.list.attr(s,Z+"-list");
ac.ul.attr(s,Z+"_listbox");
if(ab.columns&&ab.columns.length){ac.ul.removeClass("k-list").addClass("k-grid-list");
ac._columnsHeader();
}ac._header();
ac._noData();
ac._footer();
ac._accessors();
ac._initValue();
},options:{valuePrimitive:false,footerTemplate:"",headerTemplate:"",noDataTemplate:true,messages:{noData:"No data found.",clear:"clear"}},setOptions:function(Y){W.fn.setOptions.call(this,Y);
if(Y&&Y.enable!==U){Y.enabled=Y.enable;
}if(Y.columns&&Y.columns.length){this._columnsHeader();
}this._header();
this._noData();
this._footer();
this._renderFooter();
this._renderNoData();
},focus:function(){this._focused.focus();
},readonly:function(Y){this._editable({readonly:Y===U?true:Y,disable:false});
},enable:function(Y){this._editable({readonly:false,disable:!(Y=Y===U?true:Y)});
},_header:function(){var aa=this;
var Y=b(aa.header);
var ab=aa.options.headerTemplate;
this._angularElement(Y,"cleanup");
x.destroy(Y);
Y.remove();
if(!ab){aa.header=null;
return;
}var Z=typeof ab!=="function"?x.template(ab):ab;
Y=b(Z({}));
aa.header=Y[0]?Y:null;
aa.list.prepend(Y);
this._angularElement(aa.header,"compile");
},_columnsHeader:function(){var ag=this;
var Z=b(ag.columnsHeader);
this._angularElement(Z,"cleanup");
x.destroy(Z);
Z.remove();
var ae="<div class='k-grid-header'><div class='k-grid-header-wrap'><table role='presentation'>";
var Y="<colgroup>";
var ah="<tr>";
for(var af=0;
af<this.options.columns.length;
af++){var ab=this.options.columns[af];
var aj=ab.title||ab.field||"";
var ai=ab.headerTemplate||aj;
var aa=typeof ai!=="function"?x.template(ai):ai;
var ac=ab.width;
var ad=parseInt(ac,10);
var ak="";
if(ac&&!isNaN(ad)){ak+="style='width:";
ak+=ad;
ak+=I.test(ac)?"%":"px";
ak+=";'";
}Y+="<col "+ak+"/>";
ah+="<th class='k-header'>";
ah+=aa(ab);
ah+="</th>";
}Y+="</colgroup>";
ah+="</tr>";
ae+=Y;
ae+=ah;
ae+="</table></div></div>";
ag.columnsHeader=Z=b(ae);
ag.list.prepend(Z);
this._angularElement(ag.columnsHeader,"compile");
},_noData:function(){var Y=this;
var Z=b(Y.noData);
var aa=Y.options.noDataTemplate===true?Y.options.messages.noData:Y.options.noDataTemplate;
Y.angular("cleanup",function(){return{elements:Z};
});
x.destroy(Z);
Z.remove();
if(!aa){Y.noData=null;
return;
}Y.noData=b('<div class="k-nodata" style="display:none"><div></div></div>').appendTo(Y.list);
Y.noDataTemplate=typeof aa!=="function"?x.template(aa):aa;
},_footer:function(){var Z=this;
var Y=b(Z.footer);
var aa=Z.options.footerTemplate;
this._angularElement(Y,"cleanup");
x.destroy(Y);
Y.remove();
if(!aa){Z.footer=null;
return;
}Z.footer=b('<div class="k-footer"></div>').appendTo(Z.list);
Z.footerTemplate=typeof aa!=="function"?x.template(aa):aa;
},_listOptions:function(ab){var ac=this;
var Z=ac.options;
var ad=Z.virtual;
var Y={change:J(ac._listChange,ac)};
var aa=J(ac._listBound,ac);
ad=typeof ad==="object"?ad:{};
ab=b.extend({autoBind:false,selectable:true,dataSource:ac.dataSource,click:J(ac._click,ac),activate:J(ac._activateItem,ac),columns:Z.columns,deactivate:J(ac._deactivateItem,ac),dataBinding:function(){ac.trigger("dataBinding");
},dataBound:aa,height:Z.height,dataValueField:Z.dataValueField,dataTextField:Z.dataTextField,groupTemplate:Z.groupTemplate,fixedGroupTemplate:Z.fixedGroupTemplate,template:Z.template},ab,ad,Y);
if(!ab.template){ab.template="#:"+x.expr(ab.dataTextField,"data")+"#";
}if(Z.$angular){ab.$angular=Z.$angular;
}return ab;
},_initList:function(){var Z=this;
var Y=Z._listOptions({selectedItemChange:J(Z._listChange,Z)});
if(!Z.options.virtual){Z.listView=new x.ui.StaticList(Z.ul,Y);
}else{Z.listView=new x.ui.VirtualList(Z.ul,Y);
}Z.listView.bind("listBound",J(Z._listBound,Z));
Z._setListValue();
},_setListValue:function(Y){Y=Y||this.options.value;
if(Y!==U){this.listView.value(Y).done(J(this._updateSelectionState,this));
}},_updateSelectionState:b.noop,_listMousedown:function(Y){if(!this.filterInput||this.filterInput[0]!==Y.target){Y.preventDefault();
}},_isFilterEnabled:function(){var Y=this.options.filter;
return Y&&Y!=="none";
},_hideClear:function(){var Y=this;
if(Y._clear){Y._clear.addClass(p);
}},_showClear:function(){if(this._clear){this._clear.removeClass(p);
}},_clearValue:function(){this._clearText();
this._accessor("");
this.listView.value([]);
if(this._isSelect){this._customOption=U;
}if(this._isFilterEnabled()&&!this.options.enforceMinLength){this._filter({word:"",open:false});
if(this.options.highlightFirst){this.listView.focus(0);
}}this._change();
},_clearText:function(){this.text("");
},_clearFilter:function(){if(!this.options.virtual){this.listView.bound(false);
}this._filterSource();
},_filterSource:function(ab,ac){var ai=this;
var af=ai.options;
var ad=af.filterFields&&ab&&ab.logic&&ab.filters&&ab.filters.length;
var Y=ai.dataSource;
var aa=j({},Y.filter()||{});
var ah=ab||aa.filters&&aa.filters.length&&!ab;
var ag=L(aa,af.dataTextField);
this._clearFilterExpressions(aa);
if((ab||ag)&&ai.trigger("filtering",{filter:ab})){return b.Deferred().reject().promise();
}var ae={filters:[],logic:"and"};
if(ad){ae.filters.push(ab);
}else{this._pushFilterExpression(ae,ab);
}if(v(aa)){if(ae.logic===aa.logic){ae.filters=ae.filters.concat(aa.filters);
}else{ae.filters.push(aa);
}}if(ai._cascading){this.listView.setDSFilter(ae);
}var Z=j({},{page:ah?1:Y.page(),pageSize:ah?Y.options.pageSize:Y.pageSize(),sort:Y.sort(),filter:Y.filter(),group:Y.group(),aggregate:Y.aggregate()},{filter:ae});
return Y[ac?"read":"query"](Y._mergeState(Z));
},_pushFilterExpression:function(Z,Y){if(v(Y)&&Y.value!==""){Z.filters.push(Y);
}},_clearFilterExpressions:function(Y){if(!Y.filters){return;
}var Z;
for(var aa=0;
aa<Y.filters.length;
aa++){if("fromFilter" in Y.filters[aa]){Z=aa;
}}if(!isNaN(Z)){Y.filters.splice(Z,1);
}},_angularElement:function(Z,Y){if(!Z){return;
}this.angular(Y,function(){return{elements:Z};
});
},_renderNoData:function(){var Y=this;
var Z=Y.noData;
if(!Z){return;
}this._angularElement(Z,"cleanup");
Z.children(":first").html(Y.noDataTemplate({instance:Y}));
this._angularElement(Z,"compile");
},_toggleNoData:function(Y){b(this.noData).toggle(Y);
},_toggleHeader:function(Z){var Y=this.listView.content.prev(o);
Y.toggle(Z);
},_renderFooter:function(){var Z=this;
var Y=Z.footer;
if(!Y){return;
}this._angularElement(Y,"cleanup");
Y.html(Z.footerTemplate({instance:Z}));
this._angularElement(Y,"compile");
},_allowOpening:function(){return this.options.noDataTemplate||this.dataSource.flatView().length;
},_initValue:function(){var Y=this,Z=Y.options.value;
if(Z!==null){Y.element.val(Z);
}else{Z=Y._accessor();
Y.options.value=Z;
}Y._old=Z;
},_ignoreCase:function(){var aa=this,Z=aa.dataSource.reader.model,Y;
if(Z&&Z.fields){Y=Z.fields[aa.options.dataTextField];
if(Y&&Y.type&&Y.type!=="string"){aa.options.ignoreCase=false;
}}},_focus:function(Y){return this.listView.focus(Y);
},_filter:function(ac){var ad=this;
var ae=ad.options;
var af=ac.word;
var aa=ae.filterFields;
var Z=ae.dataTextField;
var Y;
if(aa&&aa.length){Y={logic:"or",filters:[],fromFilter:true};
for(var ab=0;
ab<aa.length;
ab++){this._pushFilterExpression(Y,ad._buildExpression(af,aa[ab]));
}}else{Y=ad._buildExpression(af,Z);
}ad._open=ac.open;
ad._filterSource(Y);
},_buildExpression:function(ac,Z){var ab=this;
var ad=ab.options;
var aa=ad.ignoreCase;
var Y=ab.dataSource.options.accentFoldingFiltering;
return{value:aa?Y?ac.toLocaleLowerCase(Y):ac.toLowerCase():ac,field:Z,operator:ad.filter,ignoreCase:aa};
},_clearButton:function(){var Z=this;
var Y=Z.options.messages.clear;
if(!Z._clear){Z._clear=b('<span unselectable="on" class="k-clear-value" title="'+Y+'"><span class="k-icon k-i-x"></span></span>').attr({role:"button",tabIndex:-1});
}if(!Z.options.clearButton){Z._clear.remove();
}this._hideClear();
},search:function(Z){var Y=this.options;
Z=typeof Z==="string"?Z:this._inputValue();
clearTimeout(this._typingTimeout);
if(!Y.enforceMinLength&&!Z.length||Z.length>=Y.minLength){this._state="filter";
if(this.listView){this.listView._emptySearch=!x.trim(Z).length;
}if(!this._isFilterEnabled()){this._searchByWord(Z);
}else{this._filter({word:Z,open:true});
}}},current:function(Y){return this._focus(Y);
},items:function(){return this.ul[0].children;
},destroy:function(){var Z=this;
var Y=Z.ns;
W.fn.destroy.call(Z);
Z._unbindDataSource();
Z.listView.destroy();
Z.list.off(Y);
Z.popup.destroy();
if(Z._form){Z._form.off("reset",Z._resetHandler);
}},dataItem:function(Y){var Z=this;
if(Y===U){return Z.listView.selectedDataItems()[0];
}if(typeof Y!=="number"){if(Z.options.virtual){return Z.dataSource.getByUid(b(Y).data("uid"));
}Y=b(Z.items()).index(Y);
}return Z.dataSource.flatView()[Y];
},_activateItem:function(){var Y=this.listView.focus();
if(Y){this._focused.add(this.filterInput).attr("aria-activedescendant",Y.attr("id"));
}},_deactivateItem:function(){this._focused.add(this.filterInput).removeAttr("aria-activedescendant");
},_accessors:function(){var ac=this;
var Y=ac.element;
var aa=ac.options;
var Z=x.getter;
var ab=Y.attr(x.attr("text-field"));
var ad=Y.attr(x.attr("value-field"));
if(!aa.dataTextField&&ab){aa.dataTextField=ab;
}if(!aa.dataValueField&&ad){aa.dataValueField=ad;
}ac._text=Z(aa.dataTextField);
ac._value=Z(aa.dataValueField);
},_aria:function(Z){var ab=this,aa=ab.options,Y=ab._focused.add(ab.filterInput);
if(aa.suggest!==U){Y.attr("aria-autocomplete",aa.suggest?"both":"list");
}Z=Z?Z+" "+ab.ul[0].id:ab.ul[0].id;
Y.attr("aria-owns",Z);
ab.ul.attr("aria-live",!ab._isFilterEnabled()?"off":"polite");
ab._ariaLabel();
},_ariaLabel:function(){var af=this;
var aa=af._focused;
var ab=af.element;
var ac=ab.attr("id");
var ad=b('label[for="'+ac+'"]');
var Y=ab.attr("aria-label");
var Z=ab.attr("aria-labelledby");
if(aa===ab){return;
}if(Y){aa.attr("aria-label",Y);
}else{if(Z){aa.attr("aria-labelledby",Z);
}else{if(ad.length){var ae=ad.attr("id")||af._generateLabelId(ad,ac||x.guid());
aa.attr("aria-labelledby",ae);
}}}},_generateLabelId:function(Z,Y){var aa=Y+z;
Z.attr("id",aa);
return aa;
},_blur:function(){var Y=this;
Y._change();
Y.close();
Y._userTriggered=false;
},_isValueChanged:function(Y){return Y!==V(this._old,typeof Y);
},_change:function(){var aa=this;
var Y=aa.selectedIndex;
var Z=aa.options.value;
var ac=aa.value();
var ab;
if(aa._isSelect&&!aa.listView.bound()&&Z){ac=Z;
}if(aa._isValueChanged(ac)){ab=true;
}else{if(aa._valueBeforeCascade!==U&&aa._valueBeforeCascade!==V(aa._old,typeof aa._valueBeforeCascade)&&aa._userTriggered){ab=true;
}else{if(Y!==U&&Y!==aa._oldIndex&&!aa.listView.isFiltered()){ab=true;
}}}if(ab){if(aa._old===null||aa._old===""||ac===""){aa._valueBeforeCascade=aa._old=ac;
}else{if(aa.dataItem()){aa._valueBeforeCascade=aa._old=aa.options.dataValueField?aa.dataItem()[aa.options.dataValueField]:aa.dataItem();
}else{aa._valueBeforeCascade=aa._old=null;
}}aa._oldIndex=Y;
if(!aa._typing){aa.element.trigger(h);
}aa.trigger(h);
}aa.typing=false;
},_data:function(){return this.dataSource.view();
},_enable:function(){var aa=this,Z=aa.options,Y=aa.element.is("[disabled]");
if(Z.enable!==U){Z.enabled=Z.enable;
}if(!Z.enabled||Y){aa.enable(false);
}else{aa.readonly(aa.element.is("[readonly]"));
}},_dataValue:function(Y){var Z=this._value(Y);
if(Z===U){Z=this._text(Y);
}return Z;
},_offsetHeight:function(){var Y=0;
var Z=this.listView.content.prevAll(":visible");
Z.each(function(){var aa=b(this);
Y+=G(aa,true);
});
return Y;
},_height:function(aa){var ae=this;
var ab=ae.list;
var Z=ae.options.height;
var af=ae.popup.visible();
var ac;
var ad;
var Y;
if(aa||ae.options.noDataTemplate){ad=ab.add(ab.parent(".k-animation-container")).show();
if(!ab.is(":visible")){ad.hide();
return;
}Z=ae.listView.content[0].scrollHeight>Z?Z:"auto";
ad.height(Z);
if(Z!=="auto"){ac=ae._offsetHeight();
Y=G(b(ae.footer))||0;
Z=Z-ac-Y;
}ae.listView.content.height(Z);
if(!af){ad.hide();
}}return Z;
},_openHandler:function(Y){this._adjustListWidth();
if(this.trigger(F)){Y.preventDefault();
}else{this._focused.attr("aria-expanded",true);
this.ul.attr("aria-hidden",false);
}},_adjustListWidth:function(){var ab=this,aa=ab.list,ac=aa[0].style.width,ad=ab.wrapper,Y,Z;
if(!aa.data(X)&&ac){return;
}Y=window.getComputedStyle?window.getComputedStyle(ad[0],null):0;
Z=parseFloat(Y&&Y.width)||H(ad);
if(Y&&f.msie){Z+=parseFloat(Y.paddingLeft)+parseFloat(Y.paddingRight)+parseFloat(Y.borderLeftWidth)+parseFloat(Y.borderRightWidth);
}if(aa.css("box-sizing")!=="border-box"){ac=Z-(H(aa)-aa.width());
}else{ac=Z;
}aa.css({fontFamily:ad.css("font-family"),width:ab.options.autoWidth?"auto":ac,minWidth:ac,whiteSpace:ab.options.autoWidth?"nowrap":"normal"}).data(X,ac);
return true;
},_closeHandler:function(Y){if(this.trigger(i)){Y.preventDefault();
}else{this._focused.attr("aria-expanded",false);
this.ul.attr("aria-hidden",true);
}},_focusItem:function(){var Z=this.listView;
var aa=!Z.focus();
var Y=A(Z.select());
if(Y===U&&this.options.highlightFirst&&aa){Y=0;
}if(Y!==U){Z.focus(Y);
}else{if(aa){Z.scrollToIndex(0);
}}},_calculateGroupPadding:function(aa){var ab=this.ul.children(".k-first:first");
var Z=this.listView.content.prev(o);
var ac=0;
var Y="right";
if(Z[0]&&Z[0].style.display!=="none"){if(aa!=="auto"){ac=x.support.scrollbar();
}if(this.element.parents(".k-rtl").length){Y="left";
}ac+=parseFloat(ab.css("border-"+Y+"-width"),10)+parseFloat(ab.children(".k-group").css("padding-"+Y),10);
Z.css("padding-"+Y,ac);
}},_calculatePopupHeight:function(Y){var Z=this._height(this.dataSource.flatView().length||Y);
this._calculateGroupPadding(Z);
this._calculateColumnsHeaderPadding(Z);
},_calculateColumnsHeaderPadding:function(Y){if(this.options.columns&&this.options.columns.length){var aa=this;
var Z=S.isRtl(aa.wrapper);
var ab=x.support.scrollbar();
aa.columnsHeader.css(Z?"padding-left":"padding-right",Y!=="auto"?ab:0);
}},_refreshScroll:function(){var Z=this.listView;
var Y=Z.element.height()>Z.content.height();
if(this.options.autoWidth){Z.content.css({overflowX:"hidden",overflowY:Y?"scroll":"auto"});
}},_resizePopup:function(Y){if(this.options.virtual){return;
}if(!this.popup.element.is(":visible")){this.popup.one("open",function(Z){return J(function(){this._calculatePopupHeight(Z);
},this);
}.call(this,Y));
this.popup.one("activate",J(this._refreshScroll,this));
}else{this._calculatePopupHeight(Y);
}},_popup:function(){var Y=this;
Y.popup=new T.Popup(Y.list,j({},Y.options.popup,{anchor:Y.wrapper,open:J(Y._openHandler,Y),close:J(Y._closeHandler,Y),animation:Y.options.animation,isRtl:S.isRtl(Y.wrapper),autosize:Y.options.autoWidth}));
},_toggleHover:function(Y){b(Y.currentTarget).toggleClass(q,Y.type==="mouseenter");
},_toggle:function(Y,Z){var aa=this;
var ab=S.mobileOS&&(S.touch||S.MSPointers||S.pointers);
Y=Y!==U?Y:!aa.popup.visible();
if(!Z&&!ab&&aa._focused[0]!==c()){aa._prevent=true;
aa._focused.focus();
aa._prevent=false;
}aa[Y?F:i]();
},_triggerCascade:function(){var Y=this;
if(!Y._cascadeTriggered||Y.value()!==V(Y._cascadedValue,typeof Y.value())){Y._cascadedValue=Y.value();
Y._cascadeTriggered=true;
Y.trigger(g,{userTriggered:Y._userTriggered});
}},_triggerChange:function(){if(this._valueBeforeCascade!==this.value()){this.trigger(h);
}},_unbindDataSource:function(){var Y=this;
Y.dataSource.unbind(N,Y._requestStartHandler).unbind(M,Y._requestEndHandler).unbind("error",Y._errorHandler);
},requireValueMapper:function(Z,aa){var Y=(Z.value instanceof Array?Z.value.length:Z.value)||(aa instanceof Array?aa.length:aa);
if(Y&&Z.virtual&&typeof Z.virtual.valueMapper!=="function"){throw new Error("ValueMapper is not provided while the value is being set. See http://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#the-valuemapper-function");
}}});
function V(Z,Y){if(Z!==U&&Z!==""&&Z!==null){if(Y==="boolean"){if(typeof Z!=="boolean"){Z=Z.toString().toLowerCase()==="true";
}Z=Boolean(Z);
}else{if(Y==="number"){Z=Number(Z);
}else{if(Y==="string"){Z=Z.toString();
}}}}return Z;
}j(B,{inArray:function(aa,ab){var Y,Z,ac=ab.children;
if(!aa||aa.parentNode!==ab){return -1;
}for(Y=0,Z=ac.length;
Y<Z;
Y++){if(aa===ac[Y]){return Y;
}}return -1;
},unifyType:V});
x.ui.List=B;
T.Select=B.extend({init:function(Y,Z){B.fn.init.call(this,Y,Z);
this._initial=this.element.val();
},setDataSource:function(Y){var aa=this;
var Z;
aa.options.dataSource=Y;
aa._dataSource();
if(aa.listView.bound()){aa._initialIndex=null;
aa.listView._current=null;
}aa.listView.setDataSource(aa.dataSource);
if(aa.options.autoBind){aa.dataSource.fetch();
}Z=aa._parentWidget();
if(Z){aa._cascadeSelect(Z);
}},close:function(){this.popup.close();
},select:function(Y){var Z=this;
if(Y===U){return Z.selectedIndex;
}else{return Z._select(Y).done(function(){Z._cascadeValue=Z._old=Z._accessor();
Z._oldIndex=Z.selectedIndex;
});
}},_accessor:function(Z,Y){return this[this._isSelect?"_accessorSelect":"_accessorInput"](Z,Y);
},_accessorInput:function(Z){var Y=this.element[0];
if(Z===U){return Y.value;
}else{if(Z===null){Z="";
}Y.value=Z;
}},_accessorSelect:function(ab,aa){var Y=this.element[0];
var Z;
if(ab===U){return n(Y).value||"";
}n(Y).selected=false;
if(aa===U){aa=-1;
}Z=ab!==null&&ab!=="";
if(Z&&aa==-1){this._custom(ab);
}else{if(ab){Y.value=ab;
}else{Y.selectedIndex=aa;
}}},_syncValueAndText:function(){return true;
},_custom:function(ab){var aa=this;
var Z=aa.element;
var Y=aa._customOption;
if(!Y){Y=b("<option/>");
aa._customOption=Y;
Z.append(Y);
}Y.text(ab);
Y[0].selected=true;
},_hideBusy:function(){var Y=this;
clearTimeout(Y._busy);
Y._arrowIcon.removeClass(C);
Y._focused.attr("aria-busy",false);
Y._busy=null;
Y._showClear();
},_showBusy:function(Y){var Z=this;
if(Y.isDefaultPrevented()){return;
}Z._request=true;
if(Z._busy){return;
}Z._busy=setTimeout(function(){if(Z._arrowIcon){Z._focused.attr("aria-busy",true);
Z._arrowIcon.addClass(C);
Z._hideClear();
}},100);
},_requestEnd:function(){this._request=false;
this._hideBusy();
},_dataSource:function(){var ac=this,Z=ac.element,ab=ac.options,Y=ab.dataSource||{},aa;
Y=b.isArray(Y)?{data:Y}:Y;
if(ac._isSelect){aa=Z[0].selectedIndex;
if(aa>-1){ab.index=aa;
}Y.select=Z;
Y.fields=[{field:ab.dataTextField},{field:ab.dataValueField}];
}if(ac.dataSource){ac._unbindDataSource();
}else{ac._requestStartHandler=J(ac._showBusy,ac);
ac._requestEndHandler=J(ac._requestEnd,ac);
ac._errorHandler=J(ac._hideBusy,ac);
}ac.dataSource=x.data.DataSource.create(Y).bind(N,ac._requestStartHandler).bind(M,ac._requestEndHandler).bind("error",ac._errorHandler);
},_firstItem:function(){this.listView.focusFirst();
},_lastItem:function(){this.listView.focusLast();
},_nextItem:function(){return this.listView.focusNext();
},_prevItem:function(){return this.listView.focusPrev();
},_getNormalizedDataItem:function(Y){var ad=this,ac=ad.listView,ab=typeof Y==="number",Z=ad.optionLabel&&ad.optionLabel.length,aa;
if(ab){aa=Z?--Y:Y;
}else{aa=ac.getElementIndex(Y);
}return ac.dataItemByIndex(aa);
},_getNormalizedSelectCandidate:function(Y){var ac=this,Z=ac.optionLabel&&ac.optionLabel.length,aa=typeof Y==="number",ab=Y;
if(Z&&aa){ab++;
}return ab;
},_move:function(ad){var am=this;
var ag=am.listView;
var af=ad.keyCode;
var ac=af===y.DOWN;
var ae=am.options.virtual;
var aa;
var ai;
var Z;
var ah;
var aj;
if(af===y.UP||ac){if(ad.altKey){am.toggle(ac);
}else{if(!ag.bound()&&!am.ul[0].firstChild){if(!am._fetch){am.dataSource.one(h,function(){am._fetch=false;
am._move(ad);
});
am._fetch=true;
am._filterSource();
}ad.preventDefault();
return true;
}Z=am._focus();
if(!am._fetch&&(!Z||Z.hasClass("k-state-selected"))){if(ac){ah=am._nextItem();
if(ae&&ah<=0||!am._focus()&&!ah){am._lastItem();
}}else{ah=am._prevItem();
if(ae&&ah>=ag.dataSource.total()-1||!am._focus()&&!ah){am._firstItem();
}}}aj=am._getNormalizedSelectCandidate(am._get(am._focus())||ah||0);
am._select(aj,true).done(function(){var an=function(){if(!am.popup.visible()){am._blur();
}if(am._cascadedValue===null){am._cascadedValue=am.value();
}else{am._cascadedValue=am.dataItem()?am.dataItem()[am.options.dataValueField]||am.dataItem():null;
}};
if(am.trigger(O,{dataItem:am._getNormalizedDataItem(aj),item:am._focus()})){am._select(Z).done(an);
}else{an();
}});
}ad.preventDefault();
ai=true;
}else{if(af===y.ENTER||af===y.TAB){if(am.popup.visible()){ad.preventDefault();
}Z=am._focus();
aa=am.dataItem();
if(!am.popup.visible()&&(!aa||am.text()!==am._text(aa))){Z=null;
}var Y=am.filterInput&&am.filterInput[0]===c();
var ak;
if(Z){aa=ag.dataItemByIndex(ag.getElementIndex(Z));
var al=true;
if(aa){al=am._value(aa)!==B.unifyType(am.value(),typeof am._value(aa));
}if(al&&am.trigger(O,{dataItem:aa,item:Z})){return;
}ak=am._select(Z);
}else{if(am.input){if(am._syncValueAndText()||am._isSelect){am._accessor(am.input.val());
}am.listView.value(am.input.val());
}}if(am._focusElement){am._focusElement(am.wrapper);
}if(Y&&af===y.TAB){am.wrapper.focusout();
}else{if(ak&&typeof ak.done==="function"){ak.done(function(){am._blur();
});
}else{am._blur();
}}am.close();
ai=true;
}else{if(af===y.ESC){if(am.popup.visible()){ad.preventDefault();
}am.close();
ai=true;
}else{if(am.popup.visible()&&(af===y.PAGEDOWN||af===y.PAGEUP)){ad.preventDefault();
var ab=af===y.PAGEDOWN?1:-1;
ag.scrollWith(ab*ag.screenHeight());
ai=true;
}}}}return ai;
},_fetchData:function(){var Z=this;
var Y=!!Z.dataSource.view().length;
if(Z._request||Z.options.cascadeFrom){return;
}if(!Z.listView.bound()&&!Z._fetch&&!Y){Z._fetch=true;
Z.dataSource.fetch().done(function(){Z._fetch=false;
});
}},_options:function(Y,ah,ak){var aj=this,ac=aj.element,ad=ac[0],af=Y.length,ai="",ag,Z,aa,ab,ae=0;
if(ah){ai=ah;
}for(;
ae<af;
ae++){ag="<option";
Z=Y[ae];
aa=aj._text(Z);
ab=aj._value(Z);
if(ab!==U){ab+="";
if(ab.indexOf('"')!==-1){ab=ab.replace(K,"&quot;");
}ag+=' value="'+ab+'"';
}ag+=">";
if(aa!==U){ag+=r(aa);
}ag+="</option>";
ai+=ag;
}ac.html(ai);
if(ak!==U){ad.value=ak;
if(ad.value&&!ak){ad.selectedIndex=-1;
}}if(ad.selectedIndex!==-1){ag=n(ad);
if(ag){ag.setAttribute(P,P);
}}},_reset:function(){var ab=this,Y=ab.element,aa=Y.attr("form"),Z=aa?b("#"+aa):Y.closest("form");
if(Z[0]){ab._resetHandler=function(){setTimeout(function(){ab.value(ab._initial);
});
};
ab._form=Z.on("reset",ab._resetHandler);
}},_parentWidget:function(){var Z=this.options.name;
if(!this.options.cascadeFrom){return;
}var ab=b("#"+this.options.cascadeFrom);
var aa=ab.data("kendo"+Z);
if(!aa){for(var Y=0;
Y<d[Z].length;
Y+=1){aa=ab.data("kendo"+d[Z][Y]);
if(!!aa){break;
}}}return aa;
},_cascade:function(){var ab=this;
var Z=ab.options;
var Y=Z.cascadeFrom;
var aa;
if(Y){aa=ab._parentWidget();
if(!aa){return;
}ab._cascadeHandlerProxy=J(ab._cascadeHandler,ab);
ab._cascadeFilterRequests=[];
Z.autoBind=false;
aa.bind("set",function(){ab.one("set",function(ac){ab._selectedValue=ac.value||ab._accessor();
});
});
aa.first(g,ab._cascadeHandlerProxy);
if(aa.listView.bound()){ab._toggleCascadeOnFocus();
ab._cascadeSelect(aa);
}else{aa.one("dataBound",function(){ab._toggleCascadeOnFocus();
if(aa.popup.visible()){aa._focused.focus();
}});
if(!aa.value()){ab.enable(false);
}}}},_toggleCascadeOnFocus:function(){var aa=this;
var Z=aa._parentWidget();
var Y=u&&Z instanceof T.DropDownList?e:m;
Z._focused.add(Z.filterInput).bind(k,function(){Z.unbind(g,aa._cascadeHandlerProxy);
Z.first(h,aa._cascadeHandlerProxy);
});
Z._focused.add(Z.filterInput).bind(Y,function(){Z.unbind(h,aa._cascadeHandlerProxy);
Z.first(g,aa._cascadeHandlerProxy);
});
},_cascadeHandler:function(Y){var Z=this._parentWidget();
var aa=this.value();
this._userTriggered=Y.userTriggered||Z._userTriggered;
if(this.listView.bound()){this._clearSelection(Z,true);
}this._cascadeSelect(Z,aa);
},_cascadeChange:function(Y){var Z=this;
var aa=Z._accessor()||Z._selectedValue;
if(!Z._cascadeFilterRequests.length){Z._selectedValue=null;
}if(Z._userTriggered){Z._clearSelection(Y,true);
}else{if(aa){if(aa!==V(Z.listView.value()[0],typeof aa)){Z.value(aa);
}if(!Z.dataSource.view()[0]||Z.selectedIndex===-1){Z._clearSelection(Y,true);
}}else{if(Z.dataSource.flatView().length){Z.select(Z.options.index);
}}}Z.enable();
Z._triggerCascade();
Z._triggerChange();
Z._userTriggered=false;
},_cascadeSelect:function(ac,ae){var ad=this;
var Y=ac.dataItem();
var aa=Y?Y[ad.options.cascadeFromParentField]||ac._value(Y):null;
var af=ad.options.cascadeFromField||ac.options.dataValueField;
var Z;
ad._valueBeforeCascade=ae!==U?ae:ad.value();
if(aa||aa===0){Z=ad.dataSource.filter()||{};
L(Z,af);
var ab=function(){var ag=ad._cascadeFilterRequests.shift();
if(ag){ad.unbind("dataBound",ag);
}ag=ad._cascadeFilterRequests[0];
if(ag){ad.first("dataBound",ag);
}ad._cascadeChange(ac);
};
ad._cascadeFilterRequests.push(ab);
if(ad._cascadeFilterRequests.length===1){ad.first("dataBound",ab);
}ad._cascading=true;
ad._filterSource({field:af,operator:"eq",value:aa});
ad._cascading=false;
}else{ad.enable(false);
ad._clearSelection(ac);
ad._triggerCascade();
ad._triggerChange();
ad._userTriggered=false;
}}});
var Q=".StaticList";
var R=x.ui.DataBoundWidget.extend({init:function(Y,Z){W.fn.init.call(this,Y,Z);
this.element.attr("role","listbox").on("click"+Q,"li",J(this._click,this)).on("mouseenter"+Q,"li",function(){b(this).addClass(q);
}).on("mouseleave"+Q,"li",function(){b(this).removeClass(q);
});
if(S.touch){this._touchHandlers();
}if(this.options.selectable==="multiple"){this.element.attr("aria-multiselectable",true);
}this.content=this.element.wrap("<div class='k-list-scroller' unselectable='on'></div>").parent();
this.header=this.content.before('<div class="k-group-header" style="display:none"></div>').prev();
this.bound(false);
this._optionID=x.guid();
this._selectedIndices=[];
this._view=[];
this._dataItems=[];
this._values=[];
var aa=this.options.value;
if(aa){this._values=b.isArray(aa)?aa.slice(0):[aa];
}this._getter();
this._templates();
this.setDataSource(this.options.dataSource);
this._onScroll=J(function(){var ab=this;
clearTimeout(ab._scrollId);
ab._scrollId=setTimeout(function(){ab._renderHeader();
},50);
},this);
},options:{name:"StaticList",dataValueField:null,valuePrimitive:false,selectable:true,template:null,groupTemplate:null,fixedGroupTemplate:null},events:["click",h,"activate","deactivate","dataBinding","dataBound","selectedItemChange"],setDataSource:function(Z){var aa=this;
var Y=Z||{};
var ab;
Y=b.isArray(Y)?{data:Y}:Y;
Y=x.data.DataSource.create(Y);
if(aa.dataSource){aa.dataSource.unbind(h,aa._refreshHandler);
ab=aa.value();
aa.value([]);
aa.bound(false);
aa.value(ab);
}else{aa._refreshHandler=J(aa.refresh,aa);
}aa.setDSFilter(Y.filter());
aa.dataSource=Y.bind(h,aa._refreshHandler);
aa._fixedHeader();
},_touchHandlers:function(){var ab=this;
var Z;
var Y;
var aa=function(ac){return(ac.originalEvent||ac).changedTouches[0].pageY;
};
ab.element.on("touchstart"+Q,function(ac){Z=aa(ac);
});
ab.element.on("touchend"+Q,function(ac){if(ac.isDefaultPrevented()){return;
}Y=aa(ac);
if(Math.abs(Y-Z)<10){ab._touchTriggered=true;
ab._triggerClick(b(ac.target).closest(w).get(0));
}});
},skip:function(){return this.dataSource.skip();
},setOptions:function(Y){W.fn.setOptions.call(this,Y);
this._getter();
this._templates();
this._render();
},destroy:function(){this.element.off(Q);
if(this._refreshHandler){this.dataSource.unbind(h,this._refreshHandler);
}clearTimeout(this._scrollId);
W.fn.destroy.call(this);
},dataItemByIndex:function(Y){return this.dataSource.flatView()[Y];
},screenHeight:function(){return this.content[0].clientHeight;
},scrollToIndex:function(Y){var Z=this.element[0].children[Y];
if(Z){this.scroll(Z);
}},scrollWith:function(Y){this.content.scrollTop(this.content.scrollTop()+Y);
},scroll:function(ac){if(!ac){return;
}if(ac[0]){ac=ac[0];
}var Z=this.content[0],ae=ac.offsetTop,ad=ac.offsetHeight,ab=Z.scrollTop,aa=Z.clientHeight,Y=ae+ad;
if(ab>ae){ab=ae;
}else{if(Y>ab+aa){ab=Y-aa;
}}Z.scrollTop=ab;
},selectedDataItems:function(Y){if(Y===U){return this._dataItems.slice();
}this._dataItems=Y;
this._values=this._getValues(Y);
},_getValues:function(Y){var Z=this._valueGetter;
return b.map(Y,function(aa){return Z(aa);
});
},focusNext:function(){var Y=this.focus();
if(!Y){Y=0;
}else{Y=Y.next();
}this.focus(Y);
},focusPrev:function(){var Y=this.focus();
if(!Y){Y=this.element[0].children.length-1;
}else{Y=Y.prev();
}this.focus(Y);
},focusFirst:function(){this.focus(this.element[0].children[0]);
},focusLast:function(){this.focus(A(this.element[0].children));
},focus:function(Y){var ab=this;
var aa=ab._optionID;
var Z;
if(Y===U){return ab._current;
}Y=A(ab._get(Y));
Y=b(this.element[0].children[Y]);
if(ab._current){ab._current.removeClass(l).removeAttr(s);
ab.trigger("deactivate");
}Z=!!Y[0];
if(Z){Y.addClass(l);
ab.scroll(Y);
Y.attr("id",aa);
}ab._current=Z?Y:null;
ab.trigger("activate");
},focusIndex:function(){return this.focus()?this.focus().index():U;
},skipUpdate:function(Y){this._skipUpdate=Y;
},select:function(ab){var ah=this;
var ae=ah.options.selectable;
var ag=ae!=="multiple"&&ae!==false;
var af=ah._selectedIndices;
var ai=[this.element.find(".k-state-selected").index()];
var Y=[];
var ac=[];
var ad;
if(ab===U){return af.slice();
}ab=ah._get(ab);
if(ab.length===1&&ab[0]===-1){ab=[];
}var Z=b.Deferred().resolve();
var aa=ah.isFiltered();
if(aa&&!ag&&ah._deselectFiltered(ab)){return Z;
}if(ag&&!aa&&b.inArray(A(ab),af)!==-1&&b.inArray(A(ab),ai)!==-1){if(ah._dataItems.length&&ah._view.length){ah._dataItems=[ah._view[af[0]].item];
}return Z;
}ad=ah._deselect(ab);
ac=ad.removed;
ab=ad.indices;
if(ab.length){if(ag){ab=[A(ab)];
}Y=ah._select(ab);
}if(Y.length||ac.length){ah._valueComparer=null;
ah.trigger(h,{added:Y,removed:ac});
}return Z;
},removeAt:function(Y){this._selectedIndices.splice(Y,1);
this._values.splice(Y,1);
this._valueComparer=null;
return{position:Y,dataItem:this._dataItems.splice(Y,1)[0]};
},setValue:function(Y){Y=b.isArray(Y)||Y instanceof E?Y.slice(0):[Y];
this._values=Y;
this._valueComparer=null;
},value:function(ab){var aa=this;
var Y=aa._valueDeferred;
var Z;
if(ab===U){return aa._values.slice();
}aa.setValue(ab);
if(!Y||Y.state()==="resolved"){aa._valueDeferred=Y=b.Deferred();
}if(aa.bound()){Z=aa._valueIndices(aa._values);
if(aa.options.selectable==="multiple"){aa.select(-1);
}aa.select(Z);
Y.resolve();
}aa._skipUpdate=false;
return Y;
},items:function(){return this.element.children(w);
},_click:function(Y){if(this._touchTriggered){this._touchTriggered=false;
return;
}if(!Y.isDefaultPrevented()){this._triggerClick(Y.currentTarget);
}},_triggerClick:function(Y){if(!this.trigger("click",{item:b(Y)})){this.select(Y);
}},_valueExpr:function(ad,ae){var ac=this;
var aa=0;
var Y;
var Z;
var ab=[];
if(!ac._valueComparer||ac._valueType!==ad){ac._valueType=ad;
for(;
aa<ae.length;
aa++){ab.push(V(ae[aa],ad));
}Y="for (var idx = 0; idx < "+ab.length+"; idx++) { if (current === values[idx]) {   return idx; }} return -1;";
Z=new Function("current","values",Y);
ac._valueComparer=function(af){return Z(af,ab);
};
}return ac._valueComparer;
},_dataItemPosition:function(Y,ab){var Z=this._valueGetter(Y);
var aa=this._valueExpr(typeof Z,ab);
return aa(Z);
},_getter:function(){this._valueGetter=x.getter(this.options.dataValueField);
},_deselect:function(ad){var al=this;
var Y=al.element[0].children;
var ai=al.options.selectable;
var ak=al._selectedIndices;
var aa=al._dataItems;
var am=al._values;
var ag=[];
var ab=0;
var ae;
var ac,aj;
var ah=0;
ad=ad.slice();
if(ai===true||!ad.length){for(;
ab<ak.length;
ab++){b(Y[ak[ab]]).removeClass("k-state-selected").attr("aria-selected",false);
ag.push({position:ab,dataItem:aa[ab]});
}al._values=[];
al._dataItems=[];
al._selectedIndices=[];
}else{if(ai==="multiple"){for(;
ab<ad.length;
ab++){ac=ad[ab];
if(!b(Y[ac]).hasClass("k-state-selected")){continue;
}for(ae=0;
ae<ak.length;
ae++){aj=ak[ae];
if(aj===ac){b(Y[aj]).removeClass("k-state-selected").attr("aria-selected",false);
var Z=this._view[ac].item;
var af=this._dataItemPosition(Z,this._values);
ag.push({position:af,dataItem:Z});
aa.splice(ae,1);
ak.splice(ae,1);
ad.splice(ab,1);
am.splice(ae,1);
ah+=1;
ab-=1;
ae-=1;
break;
}}}}}return{indices:ad,removed:ag};
},_deselectFiltered:function(ac){var Y=this.element[0].children;
var Z,ab,ad;
var ae=[];
var aa=0;
for(;
aa<ac.length;
aa++){ab=ac[aa];
Z=this._view[ab].item;
ad=this._dataItemPosition(Z,this._values);
if(ad>-1){ae.push(this.removeAt(ad));
b(Y[ab]).removeClass("k-state-selected");
}}if(ae.length){this.trigger(h,{added:[],removed:ae});
return true;
}return false;
},_select:function(ae){var af=this;
var Z=af.element[0].children;
var aa=af._view;
var ab,ad;
var Y=[];
var ac=0;
if(A(ae)!==-1){af.focus(ae);
}for(;
ac<ae.length;
ac++){ad=ae[ac];
ab=aa[ad];
if(ad===-1||!ab){continue;
}ab=ab.item;
af._selectedIndices.push(ad);
af._dataItems.push(ab);
af._values.push(af._valueGetter(ab));
b(Z[ad]).addClass("k-state-selected").attr("aria-selected",true);
Y.push({dataItem:ab});
}return Y;
},getElementIndex:function(Y){return b(Y).data("offset-index");
},_get:function(Y){if(typeof Y==="number"){Y=[Y];
}else{if(!t(Y)){Y=this.getElementIndex(Y);
Y=[Y!==U?Y:-1];
}}return Y;
},_template:function(){var aa=this;
var Y=aa.options;
var Z=Y.template;
if(!Z){Z=x.template('<li tabindex="-1" role="option" unselectable="on" class="k-item">${'+x.expr(Y.dataTextField,"data")+"}</li>",{useWithBlock:false});
}else{Z=x.template(Z);
Z=function(ab){return'<li tabindex="-1" role="option" unselectable="on" class="k-item">'+Z(ab)+"</li>";
};
}return Z;
},_templates:function(){var ac;
var ab=this.options;
var ad={template:ab.template,groupTemplate:ab.groupTemplate,fixedGroupTemplate:ab.fixedGroupTemplate};
if(ab.columns){for(var Z=0;
Z<ab.columns.length;
Z++){var Y=ab.columns[Z];
var ae=Y.field?Y.field.toString():"text";
ad["column"+Z]=Y.template||"#: "+ae+"#";
}}for(var aa in ad){ac=ad[aa];
if(ac&&typeof ac!=="function"){ad[aa]=x.template(ac);
}}this.templates=ad;
},_normalizeIndices:function(Z){var aa=[];
var Y=0;
for(;
Y<Z.length;
Y++){if(Z[Y]!==U){aa.push(Z[Y]);
}}return aa;
},_valueIndices:function(ac,ab){var Y=this._view;
var Z=0;
var aa;
ab=ab?ab.slice():[];
if(!ac.length){return[];
}for(;
Z<Y.length;
Z++){aa=this._dataItemPosition(Y[Z].item,ac);
if(aa!==-1){ab[aa]=Z;
}}return this._normalizeIndices(ab);
},_firstVisibleItem:function(){var Z=this.element[0];
var Y=this.content[0];
var ae=Y.scrollTop;
var ac=b(Z.children[0]).height();
var ad=Math.floor(ae/ac)||0;
var ab=Z.children[ad]||Z.lastChild;
var aa=ab.offsetTop<ae;
while(ab){if(aa){if(ab.offsetTop+ac>ae||!ab.nextSibling){break;
}ab=ab.nextSibling;
}else{if(ab.offsetTop<=ae||!ab.previousSibling){break;
}ab=ab.previousSibling;
}}return this._view[b(ab).data("offset-index")];
},_fixedHeader:function(){if(this.isGrouped()&&this.templates.fixedGroupTemplate){this.header.show();
this.content.scroll(this._onScroll);
}else{this.header.hide();
this.content.off("scroll",this._onScroll);
}},_renderHeader:function(){var Y=this.templates.fixedGroupTemplate;
if(!Y){return;
}var Z=this._firstVisibleItem();
if(Z&&Z.group.toString().length){this.header.html(Y(Z.group));
}},_renderItem:function(Y){var ac='<li tabindex="-1" role="option" unselectable="on" class="k-item';
var Z=Y.item;
var ad=Y.index!==0;
var ae=Y.selected;
var ab=this.isGrouped();
var aa=this.options.columns&&this.options.columns.length;
if(ad&&Y.newGroup){ac+=" k-first";
}if(Y.isLastGroupedItem&&aa){ac+=" k-last";
}if(ae){ac+=" k-state-selected";
}ac+='" aria-selected="'+(ae?"true":"false")+'" data-offset-index="'+Y.index+'">';
if(aa){ac+=this._renderColumns(Z);
}else{ac+=this.templates.template(Z);
}if(ad&&Y.newGroup){if(aa){ac+='<div class="k-cell k-group-cell"><span>'+this.templates.groupTemplate(Y.group)+"</span></div>";
}else{ac+='<div class="k-group">'+this.templates.groupTemplate(Y.group)+"</div>";
}}else{if(ab&&aa){ac+="<div class='k-cell k-spacer-cell'></div>";
}}return ac+"</li>";
},_renderColumns:function(aa){var ac="";
for(var ab=0;
ab<this.options.columns.length;
ab++){var Y=this.options.columns[ab].width;
var Z=parseInt(Y,10);
var ad="";
if(Y&&!isNaN(Z)){ad+="style='width:";
ad+=Z;
ad+=I.test(Y)?"%":"px";
ad+=";'";
}ac+="<span class='k-cell' "+ad+">";
ac+=this.templates["column"+ab](aa);
ac+="</span>";
}return ac;
},_render:function(){var ab="";
var ac=0;
var ad=0;
var Y;
var Z=[];
var ai=this.dataSource.view();
var ah=this.value();
var aa,ag,af;
var ae=this.isGrouped();
if(ae){for(ac=0;
ac<ai.length;
ac++){aa=ai[ac];
ag=true;
for(af=0;
af<aa.items.length;
af++){Y={selected:this._selected(aa.items[af],ah),item:aa.items[af],group:aa.value,newGroup:ag,isLastGroupedItem:af===aa.items.length-1,index:ad};
Z[ad]=Y;
ad+=1;
ab+=this._renderItem(Y);
ag=false;
}}}else{for(ac=0;
ac<ai.length;
ac++){Y={selected:this._selected(ai[ac],ah),item:ai[ac],index:ac};
Z[ac]=Y;
ab+=this._renderItem(Y);
}}this._view=Z;
this.element[0].innerHTML=ab;
if(ae&&Z.length){this._renderHeader();
}},_selected:function(Y,aa){var Z=!this.isFiltered()||this.options.selectable==="multiple";
return Z&&this._dataItemPosition(Y,aa)!==-1;
},setDSFilter:function(Y){this._lastDSFilter=j({},Y);
},isFiltered:function(){if(!this._lastDSFilter){this.setDSFilter(this.dataSource.filter());
}return !x.data.Query.compareFilters(this.dataSource.filter(),this._lastDSFilter);
},refresh:function(Z){var ad=this;
var Y=Z&&Z.action;
var ac=ad.options.skipUpdateOnBind;
var aa=Y==="itemchange";
var ab;
ad.trigger("dataBinding");
ad._angularItems("cleanup");
ad._fixedHeader();
ad._render();
ad.bound(true);
if(aa||Y==="remove"){ab=D(ad._dataItems,Z.items);
if(ab.changed.length){if(aa){ad.trigger("selectedItemChange",{items:ab.changed});
}else{ad.value(ad._getValues(ab.unchanged));
}}}else{if(ad.isFiltered()||ad._skipUpdate||ad._emptySearch){ad.focus(0);
if(ad._skipUpdate){ad._skipUpdate=false;
ad._selectedIndices=ad._valueIndices(ad._values,ad._selectedIndices);
}}else{if(!ac&&(!Y||Y==="add")){ad.value(ad._values);
}}}if(ad._valueDeferred){ad._valueDeferred.resolve();
}ad._angularItems("compile");
ad.trigger("dataBound");
},bound:function(Y){if(Y===U){return this._bound;
}this._bound=Y;
},isGrouped:function(){return(this.dataSource.group()||[]).length;
}});
T.plugin(R);
function A(Y){return Y[Y.length-1];
}function n(Z){var Y=Z.selectedIndex;
return Y>-1?Z.options[Y]:{};
}function D(af,ad){var ac=ad.length;
var ag=af.length;
var Z;
var aa;
var ab,ae;
var Y=[];
var ah=[];
if(ag){for(ab=0;
ab<ag;
ab++){Z=af[ab];
aa=false;
for(ae=0;
ae<ac;
ae++){if(Z===ad[ae]){aa=true;
Y.push({index:ab,item:Z});
break;
}}if(!aa){ah.push(Z);
}}}return{changed:Y,unchanged:ah};
}function v(Y){if(!Y||b.isEmptyObject(Y)){return false;
}if(Y.filters&&!Y.filters.length){return false;
}return true;
}function L(Y,Z){var aa;
var ab=false;
if(Y.filters){aa=b.grep(Y.filters,function(ac){ab=L(ac,Z);
if(ac.filters){return ac.filters.length;
}else{return ac.field!=Z;
}});
if(!ab&&Y.filters.length!==aa.length){ab=true;
}Y.filters=aa;
}return ab;
}}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
