(function(b,a){a("kendo.multiselect",["kendo.list","kendo.mobile.scroller","kendo.virtuallist"],b);
}(function(){var a={id:"multiselect",name:"MultiSelect",category:"web",description:"The MultiSelect widget allows the selection from pre-defined values.",depends:["list"],features:[{id:"mobile-scroller",name:"Mobile scroller",description:"Support for kinetic scrolling in mobile device",depends:["mobile.scroller"]},{id:"virtualization",name:"VirtualList",description:"Support for virtualization",depends:["virtuallist"]}]};
(function(b,Q){var u=window.kendo,P=u.ui,y=P.List,w=b.extend({A:65},u.keys),d=u._activeElement,E=u.data.ObservableArray,H=b.proxy,s="id",x="li",c="accept",n="filter",K="rebind",F="open",j="close",h="change",G="progress",L="select",l="deselect",e="aria-disabled",f="aria-readonly",o="k-state-focused",M="k-state-selected",p="k-hidden",q="k-state-hover",N="k-state-disabled",C="k-no-click",m="disabled",J="readonly",g="off",D=".kendoMultiSelect",i="click"+D,v="keydown"+D,z="mouseenter"+D,A="mouseleave"+D,r=z+" "+A,I=/"/g,t=b.isArray,O=["font-family","font-size","font-stretch","font-style","font-weight","letter-spacing","text-transform","line-height"];
var B=y.extend({init:function(S,U){var V=this,T,R;
V.ns=D;
y.fn.init.call(V,S,U);
V._optionsMap={};
V._customOptions={};
V._wrapper();
V._tagList();
V._input();
V._textContainer();
V._loader();
V._clearButton();
V._tabindex(V.input);
S=V.element.attr("multiple","multiple").hide();
U=V.options;
if(!U.placeholder){U.placeholder=S.data("placeholder");
}T=S.attr(s);
if(T){V._tagID=T+"_tag_active";
T=T+"_taglist";
V.tagList.attr(s,T);
V.input.attr("aria-describedby",T);
}V._initialOpen=true;
V._ariaLabel();
V._ariaSetLive();
V._dataSource();
V._ignoreCase();
V._popup();
V._tagTemplate();
V.requireValueMapper(V.options);
V._initList();
V._reset();
V._enable();
V._placeholder();
if(U.autoBind){V.dataSource.fetch();
}else{if(U.value){V._preselect(U.value);
}}R=b(V.element).parents("fieldset").is(":disabled");
if(R){V.enable(false);
}V._ariaSetSize(V.value().length);
u.notify(V);
V._toggleCloseVisibility();
},options:{name:"MultiSelect",tagMode:"multiple",enabled:true,autoBind:true,autoClose:true,highlightFirst:true,dataTextField:"",dataValueField:"",filter:"startswith",ignoreCase:true,minLength:1,messages:{singleTag:"item(s) selected",clear:"clear",deleteTag:"delete",noData:"No data found."},enforceMinLength:false,delay:100,value:null,maxSelectedItems:null,placeholder:"",height:200,animation:{},virtual:false,itemTemplate:"",tagTemplate:"",groupTemplate:"#:data#",fixedGroupTemplate:"#:data#",clearButton:true,autoWidth:false,popup:null},events:[F,j,h,L,l,"filtering","dataBinding","dataBound"],setDataSource:function(R){this.options.dataSource=R;
this._state="";
this._dataSource();
this.persistTagList=false;
this.listView.setDataSource(this.dataSource);
if(this.options.autoBind){this.dataSource.fetch();
}},setOptions:function(S){var R=this._listOptions(S);
y.fn.setOptions.call(this,S);
this.listView.setOptions(R);
this._accessors();
this._aria(this.tagList.attr(s));
this._tagTemplate();
this._placeholder();
this._clearButton();
},currentTag:function(R){var S=this;
if(R!==Q){if(S._currentTag){S._currentTag.removeClass(o).removeAttr(s);
S._currentTag.find(".k-select").attr("aria-hidden",true);
S.input.removeAttr("aria-activedescendant");
}if(R){R.addClass(o).attr(s,S._tagID);
R.find(".k-select").removeAttr("aria-hidden");
S.input.attr("aria-activedescendant",S._tagID);
}S._currentTag=R;
}else{return S._currentTag;
}},dataItems:function(){return this.listView.selectedDataItems();
},destroy:function(){var S=this,R=S.ns;
clearTimeout(S._busy);
clearTimeout(S._typingTimeout);
S.wrapper.off(R);
S.tagList.off(R);
S.input.off(R);
S._clear.off(R);
y.fn.destroy.call(S);
},_activateItem:function(){if(this.popup.visible()){y.fn._activateItem.call(this);
}this.currentTag(null);
},_listOptions:function(T){var V=this;
var S=y.fn._listOptions.call(V,b.extend(T,{selectedItemChange:H(V._selectedItemChange,V),selectable:"multiple"}));
var R=this.options.itemTemplate||this.options.template;
var U=S.itemTemplate||R||S.template;
if(!U){U="#:"+u.expr(S.dataTextField,"data")+"#";
}S.template=U;
return S;
},_setListValue:function(){y.fn._setListValue.call(this,this._initialValues.slice(0));
},_listChange:function(S){var R=this.dataSource.flatView();
var U=this._optionsMap;
var V=this._value;
if(this._state===K){this._state="";
}for(var T=0;
T<S.added.length;
T++){if(U[V(S.added[T].dataItem)]===Q){this._render(R);
break;
}}this._selectValue(S.added,S.removed);
},_selectedItemChange:function(S){var U=S.items;
var R;
var T;
for(T=0;
T<U.length;
T++){R=U[T];
this.tagList.children().eq(R.index).children("span:first").html(this.tagTextTemplate(R.item));
}},_wrapperMousedown:function(S){var V=this;
var T=S.target.nodeName.toLowerCase()!=="input";
var U=b(S.target);
var R=U.hasClass("k-select")||U.hasClass("k-icon");
if(R){R=!U.closest(".k-select").children(".k-i-arrow-60-down").length;
}if(T&&!(R&&u.support.mobileOS)&&S.cancelable){S.preventDefault();
}if(!R){if(V.input[0]!==d()&&T){V.input.focus();
}if(V.options.minLength===1){V.open();
}}},_inputFocus:function(){this._placeholder(false,true);
this.wrapper.addClass(o);
},_inputFocusout:function(){var R=this;
clearTimeout(R._typingTimeout);
R.wrapper.removeClass(o);
R._placeholder(!R.listView.selectedDataItems()[0],true);
R.close();
if(R._state===n){R._state=c;
R.listView.skipUpdate(true);
}if(R.listView.bound()&&R.listView.isFiltered()){R.persistTagList=true;
R._clearFilter();
}R.element.blur();
},_removeTag:function(ab,Z){var ac=this;
var aa=ac._state;
var Y=ab.index();
var U=ac.listView;
var ad=U.value()[Y];
var S=ac.listView.selectedDataItems()[Y];
var R=ac._customOptions[ad];
var W=U.element[0].children;
var X;
var V;
if(ac.trigger(l,{dataItem:S,item:ab})){ac._close();
return;
}if(R===Q&&(aa===c||aa===n)){R=ac._optionsMap[ad];
}var T=function(){ac.currentTag(null);
if(Z){ac._change();
}ac._close();
};
if(R===Q&&U.select().length){ac.persistTagList=false;
U.select(U.select()[Y]).done(T);
}else{X=ac.element[0].children[R];
if(X){X.selected=false;
}U.removeAt(Y);
V=W[R];
if(V){W[R].classList.remove("k-state-selected");
}if(ac.options.tagMode!=="single"){ab.remove();
}else{ac._updateTagListHTML();
}T();
}},_tagListClick:function(R){R.preventDefault();
R.stopPropagation();
var S=b(R.currentTarget);
if(!S.children(".k-i-arrow-60-down").length){this._removeTag(S.closest(x),true);
}},_clearValue:function(){var R=this;
if(R.options.tagMode==="single"){R._clearSingleTagValue();
}else{R.tagList.children().each(function(S,T){R._removeTag(b(T),false);
});
}R.input.val("");
R._search();
R._change();
R.focus();
R._hideClear();
if(R._state===n){R._state=c;
}},_clearSingleTagValue:function(){var V=this;
var S=V.dataItems();
var U=V.tagList.children();
var T=V.persistTagList;
for(var R=0;
R<S.length;
R+=1){if(V.trigger(l,{dataItem:S[R],item:U.first()})){V._close();
return;
}}if(T){V.persistTagList=false;
}V.listView.value([]);
V.persistTagList=T;
},_focusHandler:function(){this.input.focus();
},_editable:function(T){var W=this,R=T.disable,U=T.readonly,X=W.wrapper.off(D),V=W.tagList.off(D),S=W.element.add(W.input.off(D));
if(!U&&!R){X.removeClass(N).removeClass(C).on(r,W._toggleHover).on("mousedown"+D+" touchend"+D,H(W._wrapperMousedown,W)).on(i,H(W._focusHandler,W));
W.input.on(v,H(W._keydown,W)).on("paste"+D,H(W._search,W)).on("input"+D,H(W._search,W)).on("focus"+D,H(W._inputFocus,W)).on("focusout"+D,H(W._inputFocusout,W));
W._clear.on(i+" touchend"+D,H(W._clearValue,W));
S.removeAttr(m).removeAttr(J).attr(e,false).attr(f,false);
V.on(z,x,function(){b(this).addClass(q);
}).on(A,x,function(){b(this).removeClass(q);
}).on(i+" touchend"+D,"li.k-button .k-select",H(W._tagListClick,W));
}else{X.toggleClass(N,R).toggleClass(C,U);
S.attr(m,R).attr(J,U).attr(e,R).attr(f,U);
}},_close:function(){var R=this;
if(R.options.autoClose){R.close();
}else{R.popup.position();
}},_filterSource:function(R,S){if(!S){S=this._retrieveData;
}this._retrieveData=false;
y.fn._filterSource.call(this,R,S);
},close:function(){this._activeItem=null;
this.input.removeAttr("aria-activedescendant");
this.popup.close();
},open:function(){var R=this;
if(R._request){R._retrieveData=false;
}if(R._retrieveData||!R.listView.bound()||R._state===c){R._open=true;
R._state=K;
R.listView.skipUpdate(true);
R.persistTagList=R._initialOpen&&!R.listView.bound()?false:true;
R._filterSource();
R._focusItem();
}else{if(R._allowOpening()){if(R._initialOpen&&!R.options.autoBind&&!R.options.virtual&&R.options.value&&!b.isPlainObject(R.options.value[0])){R.value(R.value()||R._initialValues);
}R.popup._hovered=true;
R._initialOpen=false;
R.popup.open();
R._focusItem();
}}},toggle:function(R){R=R!==Q?R:!this.popup.visible();
this[R?F:j]();
},refresh:function(){this.listView.refresh();
},_listBound:function(){var S=this;
var R=S.dataSource.flatView();
S._render(R);
S._renderFooter();
S._renderNoData();
S._toggleNoData(!R.length);
S._resizePopup();
S._updateItemFocus();
if(S._open){S._open=false;
S.toggle(S._allowOpening());
}S.popup.position();
if(S._touchScroller){S._touchScroller.reset();
}S._hideBusy();
S.trigger("dataBound");
},_updateItemFocus:function(){var U=this,R=U.dataSource.flatView(),T=U.listView.skip(),S=T===Q||T===0;
if(R.length&&S){if(!U.options.highlightFirst){U.listView.focus(-1);
}else{U.listView.focusFirst();
}}},_inputValue:function(){var S=this;
var R=S.input.val();
if(S.options.placeholder===R){R="";
}return R;
},value:function(W){var V=this;
var S=V.listView;
var U=S.value().slice();
var T=V.options.maxSelectedItems;
var R=S.bound()&&S.isFiltered();
if(W===Q){return U;
}V.persistTagList=false;
V.requireValueMapper(V.options,W);
W=V._normalizeValues(W);
if(T!==null&&W.length>T){W=W.slice(0,T);
}if(R){V._clearFilter();
}S.value(W);
V._old=V._valueBeforeCascade=W.slice();
if(!R){V._fetchData();
}V._ariaSetSize(V.value().length);
V._toggleCloseVisibility();
},_preselect:function(R,T){var S=this;
if(!t(R)&&!(R instanceof u.data.ObservableArray)){R=[R];
}if(b.isPlainObject(R[0])||R[0] instanceof u.data.ObservableObject||!S.options.dataValueField){S.dataSource.data(R);
S.value(T||S._initialValues);
S._retrieveData=true;
}},_setOption:function(T,S){var R=this.element[0].children[this._optionsMap[T]];
if(R){R.selected=S;
}},_fetchData:function(){var T=this;
var R=!!T.dataSource.view().length;
var S=T.listView.value().length===0;
if(S||T._request){return;
}if(T._retrieveData||!T._fetch&&!R){T._fetch=true;
T._retrieveData=false;
T.dataSource.read().done(function(){T._fetch=false;
});
}},_isBound:function(){return this.listView.bound()&&!this._retrieveData;
},_dataSource:function(){var U=this,S=U.element,T=U.options,R=T.dataSource||{};
R=t(R)?{data:R}:R;
R.select=S;
R.fields=[{field:T.dataTextField},{field:T.dataValueField}];
if(U.dataSource&&U._refreshHandler){U._unbindDataSource();
}else{U._progressHandler=H(U._showBusy,U);
U._errorHandler=H(U._hideBusy,U);
}U.dataSource=u.data.DataSource.create(R).bind(G,U._progressHandler).bind("error",U._errorHandler);
},_reset:function(){var U=this,R=U.element,T=R.attr("form"),S=T?b("#"+T):R.closest("form");
if(S[0]){U._resetHandler=function(){setTimeout(function(){U.value(U._initialValues);
U._placeholder();
});
};
U._form=S.on("reset",U._resetHandler);
}},_initValue:function(){var R=this.options.value||this.element.val();
this._old=this._initialValues=this._normalizeValues(R);
},_normalizeValues:function(S){var R=this;
if(S===null){S=[];
}else{if(S&&b.isPlainObject(S)){S=[R._value(S)];
}else{if(S&&b.isPlainObject(S[0])){S=b.map(S,function(T){return R._value(T);
});
}else{if(!t(S)&&!(S instanceof E)){S=[S];
}else{if(t(S)){S=S.slice();
}}}}}return S;
},_change:function(){var R=this,S=R.value();
if(!k(S,R._old)){R._old=S.slice();
R.trigger(h);
R.element.trigger(h);
}R.popup.position();
R._ariaSetSize(S.length);
R._toggleCloseVisibility();
},_click:function(R){var T=this;
var S=R.item;
R.preventDefault();
T._select(S).done(function(){T._activeItem=S;
T._change();
T._close();
});
},_getActiveItem:function(){return this._activeItem||b(this.listView.items()[this._getSelectedIndices().length-1])||this.listView.focus();
},_getSelectedIndices:function(){return this.listView._selectedIndices||this.listView._selectedIndexes;
},_keydown:function(W){var ac=this;
var Z=W.keyCode;
var ab=ac._currentTag;
var aa=ac.listView;
var X=ac.input.val();
var Y=u.support.isRtl(ac.wrapper);
var ad=ac.popup.visible();
var U=0;
var S;
if(Z!==w.ENTER){this._multipleSelection=false;
}if(Z===w.DOWN){W.preventDefault();
if(!ad){ac.open();
if(!aa.focus()){aa.focusFirst();
}return;
}if(aa.focus()){if(!ac._activeItem&&W.shiftKey){ac._activeItem=aa.focus();
U=-1;
}S=aa.getElementIndex(ac._getActiveItem().first());
aa.focusNext();
if(!aa.focus()){aa.focusLast();
}else{if(W.shiftKey){this._multipleSelection=true;
ac._selectRange(S,aa.getElementIndex(aa.focus().first())+U);
}}}else{aa.focusFirst();
}}else{if(Z===w.UP){if(ad){if(!ac._activeItem&&W.shiftKey){ac._activeItem=aa.focus();
U=1;
}S=aa.getElementIndex(ac._getActiveItem().first());
aa.focusPrev();
if(!aa.focus()){ac.close();
}else{if(W.shiftKey){this._multipleSelection=true;
ac._selectRange(S,aa.getElementIndex(aa.focus().first())+U);
}}}W.preventDefault();
}else{if(Z===w.LEFT&&!Y||Z===w.RIGHT&&Y){if(!X){ab=ab?ab.prev():b(ac.tagList[0].lastChild);
if(ab[0]){ac.currentTag(ab);
}}}else{if(Z===w.RIGHT&&!Y||Z===w.LEFT&&Y){if(!X&&ab){ab=ab.next();
ac.currentTag(ab[0]?ab:null);
}}else{if(W.ctrlKey&&!W.altKey&&Z===w.A&&ad&&!ac.options.virtual){this._multipleSelection=true;
if(this._getSelectedIndices().length===aa.items().length){ac._activeItem=null;
}if(aa.items().length){ac._selectRange(0,aa.items().length-1);
}}else{if(Z===w.ENTER&&ad){if(!aa.focus()){return;
}W.preventDefault();
if(this._multipleSelection){this._multipleSelection=false;
if(aa.focus().hasClass(M)){ac._close();
return;
}}ac._select(aa.focus()).done(function(){ac._change();
ac._close();
});
}else{if(Z===w.SPACEBAR&&W.ctrlKey&&ad){if(ac._activeItem&&aa.focus()&&aa.focus()[0]===ac._activeItem[0]){ac._activeItem=null;
}if(!b(aa.focus()).hasClass(M)){ac._activeItem=aa.focus();
}ac._select(aa.focus()).done(function(){ac._change();
});
W.preventDefault();
}else{if(Z===w.SPACEBAR&&W.shiftKey&&ad){var R=aa.getElementIndex(ac._getActiveItem());
var T=aa.getElementIndex(aa.focus());
if(R!==Q&&T!==Q){ac._selectRange(R,T);
}W.preventDefault();
}else{if(Z===w.ESC){if(ad){W.preventDefault();
}else{ac.tagList.children().each(function(ae,af){ac._removeTag(b(af),false);
});
ac._change();
}ac.close();
}else{if(Z===w.HOME){if(ad){if(!aa.focus()){ac.close();
}else{if(W.ctrlKey&&W.shiftKey&&!ac.options.virtual){ac._selectRange(aa.getElementIndex(aa.focus()[0]),0);
}aa.focusFirst();
}}else{if(!X){ab=ac.tagList[0].firstChild;
if(ab){ac.currentTag(b(ab));
}}}}else{if(Z===w.END){if(ad){if(!aa.focus()){ac.close();
}else{if(W.ctrlKey&&W.shiftKey&&!ac.options.virtual){ac._selectRange(aa.getElementIndex(aa.focus()[0]),aa.element.children().length-1);
}aa.focusLast();
}}else{if(!X){ab=ac.tagList[0].lastChild;
if(ab){ac.currentTag(b(ab));
}}}}else{if((Z===w.DELETE||Z===w.BACKSPACE)&&!X){ac._state=c;
if(ac.options.tagMode==="single"){ac._clearSingleTagValue();
ac._change();
ac._close();
return;
}if(Z===w.BACKSPACE&&!ab){ab=b(ac.tagList[0].lastChild);
}if(ab&&ab[0]){ac._removeTag(ab,true);
}}else{if(ac.popup.visible()&&(Z===w.PAGEDOWN||Z===w.PAGEUP)){W.preventDefault();
var V=Z===w.PAGEDOWN?1:-1;
aa.scrollWith(V*aa.screenHeight());
}else{clearTimeout(ac._typingTimeout);
setTimeout(function(){ac._scale();
});
ac._search();
}}}}}}}}}}}}}},_hideBusy:function(){var R=this;
clearTimeout(R._busy);
R.input.attr("aria-busy",false);
R._loading.addClass(p);
R._request=false;
R._busy=null;
R._toggleCloseVisibility();
},_showBusyHandler:function(){this.input.attr("aria-busy",true);
this._loading.removeClass(p);
this._hideClear();
},_showBusy:function(){var R=this;
R._request=true;
if(R._busy){return;
}R._busy=setTimeout(H(R._showBusyHandler,R),100);
},_placeholder:function(X,Y){var Z=this;
var T=Z.input;
var R=d();
var W=Z.options.placeholder;
var U=T.val();
var V=T[0]===R;
var S=U.length;
if(!V||Z.options.autoClose||U===W){S=0;
U="";
}if(X===Q){X=false;
if(T[0]!==R){X=!Z.listView.selectedDataItems()[0];
}}Z._prev=U;
T.toggleClass("k-readonly",X).val(X?W:U);
if(V&&!Y){u.caret(T[0],S,S);
}Z._scale();
},_scale:function(){var T=this,U=T.wrapper.find(".k-multiselect-wrap"),V=U.width(),R=T._span.text(T.input.val()),S;
if(!U.is(":visible")){R.appendTo(document.documentElement);
V=S=R.width()+25;
R.appendTo(U);
}else{S=R.width()+25;
}T.input.width(S>V?V:S);
},_option:function(S,R,U){var T="<option";
if(S!==Q){S+="";
if(S.indexOf('"')!==-1){S=S.replace(I,"&quot;");
}T+=' value="'+S+'"';
}if(U){T+=" selected";
}T+=">";
if(R!==Q){T+=u.htmlEncode(R);
}return T+="</option>";
},_render:function(S){var Z=this.listView.selectedDataItems();
var ab=this.listView.value();
var V=S.length;
var Y;
var W="";
var T;
var aa;
var U;
if(ab.length!==Z.length){Z=this._buildSelectedItems(ab);
}var R={};
var X={};
for(U=0;
U<V;
U++){T=S[U];
aa=this._value(T);
Y=this._selectedItemIndex(aa,Z);
if(Y!==-1){Z.splice(Y,1);
}X[aa]=U;
W+=this._option(aa,this._text(T),Y!==-1);
}if(Z.length){for(U=0;
U<Z.length;
U++){T=Z[U];
aa=this._value(T);
R[aa]=V;
X[aa]=V;
V+=1;
W+=this._option(aa,this._text(T),true);
}}this._customOptions=R;
this._optionsMap=X;
this.element.html(W);
},_buildSelectedItems:function(W){var V=this.options.dataValueField;
var U=this.options.dataTextField;
var T=[];
var S;
for(var R=0;
R<W.length;
R++){S={};
S[V]=W[R];
S[U]=W[R];
T.push(S);
}return T;
},_selectedItemIndex:function(T,S){var U=this._value;
var R=0;
for(;
R<S.length;
R++){if(T===U(S[R])){return R;
}}return -1;
},_search:function(){var R=this;
clearTimeout(R._typingTimeout);
R._typingTimeout=setTimeout(function(){var S=R._inputValue();
if(R._prev!==S){R._prev=S;
R.search(S);
R._toggleCloseVisibility();
}},R.options.delay);
},_toggleCloseVisibility:function(){if(this.value().length||this.input.val()&&this.input.val()!==this.options.placeholder){this._showClear();
}else{this._hideClear();
}},_allowOpening:function(){return this._allowSelection()&&y.fn._allowOpening.call(this);
},_allowSelection:function(){var R=this.options.maxSelectedItems;
return R===null||R>this.listView.value().length;
},_angularTagItems:function(R){var S=this;
S.angular(R,function(){return{elements:S.tagList[0].children,data:b.map(S.dataItems(),function(T){return{dataItem:T};
})};
});
},updatePersistTagList:function(R,S){if(this.persistTagList.added&&this.persistTagList.added.length===S.length&&this.persistTagList.removed&&this.persistTagList.removed.length===R.length){this.persistTagList=false;
}else{this.listView._removedAddedIndexes=this._old.slice();
this.persistTagList={added:R,removed:S};
}},_selectValue:function(R,V){var Y=this;
var Z=Y.dataSource.total();
var X=Y.tagList;
var T=Y._value;
var W;
var S;
var U;
if(this.persistTagList){this.updatePersistTagList(R,V);
return;
}Y._angularTagItems("cleanup");
if(Y.options.tagMode==="multiple"){for(U=V.length-1;
U>-1;
U--){W=V[U];
if(X.children().length){X[0].removeChild(X[0].children[W.position]);
Y._setOption(T(W.dataItem),false);
}}for(U=0;
U<R.length;
U++){S=R[U];
X.append(Y.tagTemplate(S.dataItem));
Y._setOption(T(S.dataItem),true);
}}else{if(!Y._maxTotal||Y._maxTotal<Z){Y._maxTotal=Z;
}this._updateTagListHTML();
for(U=V.length-1;
U>-1;
U--){Y._setOption(T(V[U].dataItem),false);
}for(U=0;
U<R.length;
U++){Y._setOption(T(R[U].dataItem),true);
}}Y._angularTagItems("compile");
Y._placeholder();
},_updateTagListHTML:function(){var S=this;
var U=S.value();
var T=S.dataSource.total();
var R=S.tagList;
R.html("");
if(U.length){R.append(S.tagTemplate({values:U,dataItems:S.dataItems(),maxTotal:S._maxTotal,currentTotal:T}));
}},_select:function(R){var V=b.Deferred().resolve();
if(!R){return V;
}var W=this;
var U=W.listView;
var S=U.dataItemByIndex(U.getElementIndex(R));
var T=R.hasClass("k-state-selected");
if(W._state===K){W._state="";
}if(!W._allowSelection()&&!T){return V;
}if(W.trigger(T?l:L,{dataItem:S,item:R})){W._close();
return V;
}W.persistTagList=false;
return U.select(R).done(function(){W._placeholder();
if(W._state===n){W._state=c;
U.skipUpdate(true);
}});
},_selectRange:function(Z,R){var aa=this;
var W=this.listView;
var X=this.options.maxSelectedItems;
var U=this._getSelectedIndices().slice();
var V=[];
var S;
var Y=function(ab){W.select(ab).done(function(){ab.forEach(function(ae){var ad=W.dataItemByIndex(ae);
var ac=W.element.children()[ae];
var af=b(ac).hasClass("k-state-selected");
aa.trigger(af?L:l,{dataItem:ad,item:b(ac)});
});
aa._change();
});
};
if(U.length-1===R-Z){return Y(U);
}if(Z<R){for(S=Z;
S<=R;
S++){V.push(S);
}}else{for(S=Z;
S>=R;
S--){V.push(S);
}}if(X!==null&&V.length>X){V=V.slice(0,X);
}for(S=0;
S<V.length;
S++){var T=V[S];
if(this._getSelectedIndices().indexOf(T)==-1){U.push(T);
}else{U.splice(U.indexOf(T),1);
}}if(!U.length){return;
}aa.persistTagList=false;
return Y(U);
},_input:function(){var U=this;
var S=U.element;
var R=S[0].accessKey;
var T=U._inputWrapper.children("input.k-input");
if(!T[0]){T=b('<input class="k-input" style="width: 25px" />').appendTo(U._inputWrapper);
}S.removeAttr("accesskey");
U._focused=U.input=T.attr({accesskey:R,autocomplete:g,role:"textbox",title:S[0].title,"aria-expanded":false,"aria-haspopup":"listbox","aria-autocomplete":"list"});
},_tagList:function(){var S=this,R=S._inputWrapper.children("ul");
if(!R[0]){R=b('<ul unselectable="on" class="k-reset"/>').appendTo(S._inputWrapper);
}S.tagList=R;
},_tagTemplate:function(){var X=this;
var U=X.options;
var W=U.tagTemplate;
var S=U.dataSource;
var T=U.tagMode==="multiple";
var V=U.messages.singleTag;
var R;
if(X.element[0].length&&!S){U.dataTextField=U.dataTextField||"text";
U.dataValueField=U.dataValueField||"value";
}R=T?u.template("#:"+u.expr(U.dataTextField,"data")+"#",{useWithBlock:false}):u.template("#:values.length# "+V);
X.tagTextTemplate=W=W?u.template(W):R;
X.tagTemplate=function(Y){return'<li aria-selected="true" class="k-button" unselectable="on"><span unselectable="on">'+W(Y)+'</span><span aria-hidden="true" unselectable="on" aria-label="'+(T?'delete" title="'+X.options.messages.deleteTag+'" aria-label="'+X.options.messages.deleteTag:"open")+'" class="k-select"><span class="k-icon '+(T?"k-i-close":"k-i-arrow-60-down")+'"></span></span></li>';
};
},_loader:function(){this._loading=b('<span class="k-icon k-i-loading '+p+'"></span>').insertAfter(this.input);
},_clearButton:function(){y.fn._clearButton.call(this);
if(this.options.clearButton){this._clear.insertAfter(this.input);
this.wrapper.addClass("k-multiselect-clearable");
}},_textContainer:function(){var R=u.getComputedStyles(this.input[0],O);
R.position="absolute";
R.visibility="hidden";
R.top=-3333;
R.left=-3333;
this._span=b("<span/>").css(R).appendTo(this.wrapper);
},_wrapper:function(){var S=this,R=S.element,T=R.parent("span.k-multiselect");
if(!T[0]){T=R.wrap('<div class="k-widget k-multiselect" unselectable="on" />').parent();
T[0].style.cssText=R[0].style.cssText;
T[0].title=R[0].title;
b('<div class="k-multiselect-wrap k-floatwrap" unselectable="on" role="listbox"/>').insertBefore(R);
}S.wrapper=T.addClass(R[0].className).removeClass("input-validation-error").css("display","");
S._inputWrapper=b(T[0].firstChild);
},_ariaSetSize:function(T){var S=this;
var R=S.tagList.children();
if(T&&R.length){R.attr("aria-setsize",T);
}},_ariaSetLive:function(){var R=this;
R.ul.attr("aria-live",!R._isFilterEnabled()?"off":"polite");
}});
function k(R,S){var T;
if(R===null&&S!==null||R!==null&&S===null){return false;
}T=R.length;
if(T!==S.length){return false;
}while(T--){if(R[T]!==S[T]){return false;
}}return true;
}P.plugin(B);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
