(function(b,a){a("ooxml/utils",["kendo.core"],b);
}(function(){(function(){kendo.ooxml=kendo.ooxml||{};
kendo.ooxml.createZip=function(){if(typeof JSZip==="undefined"){throw new Error("JSZip not found. Check http://docs.telerik.com/kendo-ui/framework/excel/introduction#requirements for more details.");
}return new JSZip();
};
}());
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("ooxml/kendo-ooxml",["kendo.core","ooxml/utils"],b);
}(function(){(function(a){window.kendo.ooxml=window.kendo.ooxml||{};
var Q=kendo.ooxml;
var L=a.map;
var p=Q.createZip;
var q={toString:function(ay){return ay;
}};
var J=kendo.Class.extend({});
J.register=function(ay){q=ay;
};
J.toString=function(az,ay){return q.toString(az,ay);
};
function t(aA,az,ay){return(1461*(aA+4800+((az-13)/12|0))/4|0)+(367*(az-1-12*((az-13)/12|0))/12|0)-(3*((aA+4900+((az-13)/12|0))/100|0)/4|0)+ay-32075;
}var f=t(1900,0,-1);
function R(aA,az,ay){return t(aA,az,ay)-f;
}function S(ay,az,aB,aA){return(ay+(az+(aB+aA/1000)/60)/60)/24;
}function u(ay){var aA=S(ay.getHours(),ay.getMinutes(),ay.getSeconds(),ay.getMilliseconds());
var az=R(ay.getFullYear(),ay.getMonth(),ay.getDate());
return az<0?az-1+aA:az+aA;
}var O="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
var s="data:"+O+";base64,";
var r={compression:"DEFLATE",type:"base64"};
var g={compression:"DEFLATE",type:"blob"};
var e={compression:"DEFLATE",type:"arraybuffer"};
function am(ay){return s+ay;
}function E(az,ay){return ay.indexOf(az);
}var T=JSON.parse.bind(JSON);
function z(ay){return String(ay).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/\'/g,"&#39;");
}function aa(ay,az){var aB="";
for(var aA=0;
aA<ay;
++aA){aB+=az(aA);
}return aB;
}function C(ay,az){var aB="";
if(ay!=null){if(Array.isArray(ay)){for(var aA=0;
aA<ay.length;
++aA){aB+=az(ay[aA],aA);
}}else{if(typeof ay=="object"){Object.keys(ay).forEach(function(aD,aC){aB+=az(ay[aD],aD,aC);
});
}}}return aB;
}var ax='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r';
var Z=ax+'\n            <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n               <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>\n               <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>\n               <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>\n            </Relationships>';
var n=function(aC){var az=aC.creator;
var aA=aC.lastModifiedBy;
var ay=aC.created;
var aB=aC.modified;
return ax+'\n <cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"\n   xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"\n   xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n   <dc:creator>'+z(az)+"</dc:creator>\n   <cp:lastModifiedBy>"+z(aA)+'</cp:lastModifiedBy>\n   <dcterms:created xsi:type="dcterms:W3CDTF">'+z(ay)+'</dcterms:created>\n   <dcterms:modified xsi:type="dcterms:W3CDTF">'+z(aB)+"</dcterms:modified>\n</cp:coreProperties>";
};
var c=function(ay){var az=ay.sheets;
return ax+'\n<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">\n  <Application>Microsoft Excel</Application>\n  <DocSecurity>0</DocSecurity>\n  <ScaleCrop>false</ScaleCrop>\n  <HeadingPairs>\n    <vt:vector size="2" baseType="variant">\n      <vt:variant>\n        <vt:lpstr>Worksheets</vt:lpstr>\n      </vt:variant>\n      <vt:variant>\n        <vt:i4>'+az.length+'</vt:i4>\n      </vt:variant>\n    </vt:vector>\n  </HeadingPairs>\n  <TitlesOfParts>\n    <vt:vector size="'+az.length+'" baseType="lpstr">'+C(az,function(aB,aA){return aB.options.title?"<vt:lpstr>"+z(aB.options.title)+"</vt:lpstr>":"<vt:lpstr>Sheet"+(aA+1)+"</vt:lpstr>";
})+"</vt:vector>\n  </TitlesOfParts>\n  <LinksUpToDate>false</LinksUpToDate>\n  <SharedDoc>false</SharedDoc>\n  <HyperlinksChanged>false</HyperlinksChanged>\n  <AppVersion>14.0300</AppVersion>\n</Properties>";
};
var l=function(aA){var aB=aA.sheetCount;
var ay=aA.commentFiles;
var az=aA.drawingFiles;
return ax+'\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n  <Default Extension="png" ContentType="image/png"/>\n  <Default Extension="gif" ContentType="image/gif"/>\n  <Default Extension="jpg" ContentType="image/jpeg"/>\n  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />\n  <Default Extension="xml" ContentType="application/xml" />\n  <Default Extension="vml" ContentType="application/vnd.openxmlformats-officedocument.vmlDrawing"/>\n  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml" />\n  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>\n  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>\n  '+aa(aB,function(aC){return'<Override PartName="/xl/worksheets/sheet'+(aC+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml" />';
})+"\n  "+C(ay,function(aC){return'<Override PartName="/xl/'+aC+'" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"/>';
})+"\n  "+C(az,function(aC){return'<Override PartName="/xl/drawings/'+aC+'" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>';
})+'\n  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />\n  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml" />\n</Types>';
};
var aq=function(az){var aA=az.sheets;
var ay=az.filterNames;
var aB=az.userNames;
return ax+'\n<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">\n  <fileVersion appName="xl" lastEdited="5" lowestEdited="5" rupBuild="9303" />\n  <workbookPr defaultThemeVersion="124226" />\n  <bookViews>\n    <workbookView xWindow="240" yWindow="45" windowWidth="18195" windowHeight="7995" />\n  </bookViews>\n  <sheets>\n  '+C(aA,function(aF,aC){var aE=aF.options;
var aD=aE.name||aE.title||"Sheet"+(aC+1);
return'<sheet name="'+z(aD)+'" sheetId="'+(aC+1)+'" r:id="rId'+(aC+1)+'" />';
})+"\n  </sheets>\n  "+(ay.length||aB.length?"\n    <definedNames>\n      "+C(ay,function(aC){return'\n         <definedName name="_xlnm._FilterDatabase" hidden="1" localSheetId="'+aC.localSheetId+'">'+z(X(aC.name))+"!"+z(aC.from)+":"+z(aC.to)+"</definedName>";
})+"\n      "+C(aB,function(aC){return'\n         <definedName name="'+aC.name+'" hidden="'+(aC.hidden?1:0)+'" '+(aC.localSheetId!=null?'localSheetId="'+aC.localSheetId+'"':"")+">"+z(aC.value)+"</definedName>";
})+"\n    </definedNames>":"")+'\n  <calcPr fullCalcOnLoad="1" calcId="145621" />\n</workbook>';
};
var au=function(aN){var aF=aN.frozenColumns;
var aG=aN.frozenRows;
var az=aN.columns;
var aC=aN.defaults;
var aA=aN.data;
var aI=aN.index;
var aM=aN.mergeCells;
var ay=aN.autoFilter;
var aE=aN.filter;
var aP=aN.showGridLines;
var aH=aN.hyperlinks;
var aQ=aN.validations;
var aB=aN.defaultCellStyleId;
var aO=aN.rtl;
var aL=aN.legacyDrawing;
var aD=aN.drawing;
var aK=aN.lastRow;
var aJ=aN.lastCol;
return ax+'\n<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" mc:Ignorable="x14ac">\n   '+(aK&&aJ?'<dimension ref="A1:'+Y(aK-1,aJ-1)+'" />':"")+"\n\n   <sheetViews>\n     <sheetView "+(aO?'rightToLeft="1"':"")+" "+(aI===0?'tabSelected="1"':"")+' workbookViewId="0" '+(aP===false?'showGridLines="0"':"")+">\n     "+(aG||aF?'\n       <pane state="frozen"\n         '+(aF?'xSplit="'+aF+'"':"")+"\n         "+(aG?'ySplit="'+aG+'"':"")+'\n         topLeftCell="'+(String.fromCharCode(65+(aF||0))+((aG||0)+1))+'"\n       />':"")+'\n     </sheetView>\n   </sheetViews>\n\n   <sheetFormatPr x14ac:dyDescent="0.25" '+(!aC.skipCustomHeight?'customHeight="1"':"")+' defaultRowHeight="'+(aC.rowHeight?aC.rowHeight*0.75:15)+'"\n     '+(aC.columnWidth?'defaultColWidth="'+ao(aC.columnWidth)+'"':"")+" />\n\n   "+(aB!=null||az&&az.length>0?"\n     <cols>\n       "+(!az||!az.length?'\n         <col min="1" max="16384" style="'+aB+'"\n              '+(aC.columnWidth?'width="'+ao(aC.columnWidth)+'"':"")+" /> ":"")+"\n       "+C(az,function(aS,aR){var aT=typeof aS.index==="number"?aS.index+1:aR+1;
if(aS.width===0){return"<col "+(aB!=null?'style="'+aB+'"':"")+'\n                        min="'+aT+'" max="'+aT+'" hidden="1" customWidth="1" />';
}return"<col "+(aB!=null?'style="'+aB+'"':"")+'\n                      min="'+aT+'" max="'+aT+'" customWidth="1"\n                      '+(aS.autoWidth?'width="'+(aS.width*7+5)/7*256/256+'" bestFit="1"':'width="'+ao(aS.width)+'"')+" />";
})+"\n     </cols>":"")+"\n\n   <sheetData>\n     "+C(aA,function(aS,aR){var aT=typeof aS.index==="number"?aS.index+1:aR+1;
return'\n         <row r="'+aT+'" x14ac:dyDescent="0.25"\n              '+(aS.level?'outlineLevel="'+aS.level+'"':"")+"\n              "+(aS.height===0?'hidden="1"':aS.height?'ht="'+an(aS.height)+'" customHeight="1"':"")+">\n           "+C(aS.data,function(aU){return'\n             <c r="'+aU.ref+'" '+(aU.style?'s="'+aU.style+'"':"")+" "+(aU.type?'t="'+aU.type+'"':"")+">\n               "+(aU.formula!=null?aw(aU.formula):"")+"\n               "+(aU.value!=null?"<v>"+z(aU.value)+"</v>":"")+"\n             </c>";
})+"\n         </row>\n       ";
})+"\n   </sheetData>\n\n   "+(ay?'<autoFilter ref="'+ay.from+":"+ay.to+'"/>':aE?aj(aE):"")+"\n\n   "+(aM.length?'\n     <mergeCells count="'+aM.length+'">\n       '+C(aM,function(aR){return'<mergeCell ref="'+aR+'"/>';
})+"\n     </mergeCells>":"")+"\n\n   "+(aQ.length?"\n     <dataValidations>\n       "+C(aQ,function(aR){return'\n         <dataValidation sqref="'+aR.sqref.join(" ")+'"\n                         showErrorMessage="'+aR.showErrorMessage+'"\n                         type="'+z(aR.type)+'"\n                         '+(aR.type!=="list"?'operator="'+z(aR.operator)+'"':"")+'\n                         allowBlank="'+aR.allowBlank+'"\n                         showDropDown="'+aR.showDropDown+'"\n                         '+(aR.error?'error="'+z(aR.error)+'"':"")+"\n                         "+(aR.errorTitle?'errorTitle="'+z(aR.errorTitle)+'"':"")+">\n           "+(aR.formula1?"<formula1>"+z(aR.formula1)+"</formula1>":"")+"\n           "+(aR.formula2?"<formula2>"+z(aR.formula2)+"</formula2>":"")+"\n         </dataValidation>";
})+"\n     </dataValidations>":"")+"\n\n   "+(aH.length?"\n     <hyperlinks>\n       "+C(aH,function(aR){return'\n         <hyperlink ref="'+aR.ref+'" r:id="'+aR.rId+'"/>';
})+"\n     </hyperlinks>":"")+'\n\n   <pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3" />\n   '+(aD?'<drawing r:id="'+aD+'"/>':"")+"\n   "+(aL?'<legacyDrawing r:id="'+aL+'"/>':"")+"\n</worksheet>";
};
var ar=function(az){var ay=az.count;
return ax+'\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n  '+aa(ay,function(aA){return'\n    <Relationship Id="rId'+(aA+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(aA+1)+'.xml" />';
})+'\n  <Relationship Id="rId'+(ay+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml" />\n  <Relationship Id="rId'+(ay+2)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml" />\n</Relationships>';
};
var av=function(aB){var aA=aB.hyperlinks;
var ay=aB.comments;
var aC=aB.sheetIndex;
var az=aB.drawings;
return ax+'\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n  '+C(aA,function(aD){return'\n    <Relationship Id="'+aD.rId+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="'+z(aD.target)+'" TargetMode="External" />';
})+"\n  "+(!ay.length?"":'\n    <Relationship Id="comment'+aC+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments'+aC+'.xml"/>\n    <Relationship Id="vml'+aC+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="../drawings/vmlDrawing'+aC+'.vml"/>')+"\n  "+(!az.length?"":'\n    <Relationship Id="drw'+aC+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing'+aC+'.xml"/>')+"\n</Relationships>";
};
var k=function(az){var ay=az.comments;
return ax+'\n<comments xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">\n  <authors>\n    <author></author>\n  </authors>\n  <commentList>\n    '+C(ay,function(aA){return'\n      <comment ref="'+aA.ref+'" authorId="0">\n        <text>\n          <r>\n            <rPr>\n              <sz val="8"/>\n              <color indexed="81"/>\n              <rFont val="Tahoma"/>\n              <charset val="1"/>\n            </rPr>\n            <t>'+z(aA.text)+"</t>\n          </r>\n        </text>\n      </comment>";
})+"\n  </commentList>\n</comments>";
};
var K=function(az){var ay=az.comments;
return'<xml xmlns:v="urn:schemas-microsoft-com:vml"\n     xmlns:o="urn:schemas-microsoft-com:office:office"\n     xmlns:x="urn:schemas-microsoft-com:office:excel">\n  <v:shapetype coordsize="21600,21600" id="_x0000_t202" path="m,l,21600r21600,l21600,xe">\n    <v:stroke joinstyle="miter"/>\n    <v:path gradientshapeok="t" o:connecttype="rect"/>\n  </v:shapetype>\n  '+C(ay,function(aA){return'\n    <v:shape type="#_x0000_t202" style="visibility: hidden" fillcolor="#ffffe1" o:insetmode="auto">\n      <v:shadow on="t" color="black" obscured="t"/>\n      <x:ClientData ObjectType="Note">\n        <x:MoveWithCells/>\n        <x:SizeWithCells/>\n        <x:Anchor>'+aA.anchor+"</x:Anchor>\n        <x:AutoFill>False</x:AutoFill>\n        <x:Row>"+aA.row+"</x:Row>\n        <x:Column>"+aA.col+"</x:Column>\n      </x:ClientData>\n    </v:shape>";
})+"\n</xml>";
};
var x=function(ay){return ax+'\n<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing"\n          xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"\n          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">\n  '+C(ay,function(az,aA){return'\n    <xdr:oneCellAnchor editAs="oneCell">\n      <xdr:from>\n        <xdr:col>'+az.col+"</xdr:col>\n        <xdr:colOff>"+az.colOffset+"</xdr:colOff>\n        <xdr:row>"+az.row+"</xdr:row>\n        <xdr:rowOff>"+az.rowOffset+'</xdr:rowOff>\n      </xdr:from>\n      <xdr:ext cx="'+az.width+'" cy="'+az.height+'" />\n      <xdr:pic>\n        <xdr:nvPicPr>\n          <xdr:cNvPr id="'+(aA+1)+'" name="Picture '+(aA+1)+'"/>\n          <xdr:cNvPicPr/>\n        </xdr:nvPicPr>\n        <xdr:blipFill>\n          <a:blip r:embed="'+az.imageId+'"/>\n          <a:stretch>\n            <a:fillRect/>\n          </a:stretch>\n        </xdr:blipFill>\n        <xdr:spPr>\n          <a:prstGeom prst="rect">\n            <a:avLst/>\n          </a:prstGeom>\n        </xdr:spPr>\n      </xdr:pic>\n      <xdr:clientData/>\n    </xdr:oneCellAnchor>';
})+"\n</xdr:wsDr>";
};
var w=function(ay){return ax+'\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n  '+C(ay,function(az){return'\n    <Relationship Id="'+az.rId+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="'+az.target+'"/>';
})+"\n</Relationships>";
};
var ab=function(aA){var ay=aA.count;
var aB=aA.uniqueCount;
var az=aA.indexes;
return ax+'\n<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="'+ay+'" uniqueCount="'+aB+'">\n  '+C(Object.keys(az),function(aC){return'\n    <si><t xml:space="preserve">'+z(aC.substring(1))+"</t></si>";
})+"\n</sst>";
};
var al=function(aC){var aB=aC.formats;
var aA=aC.fonts;
var az=aC.fills;
var ay=aC.borders;
var aD=aC.styles;
return ax+'\n<styleSheet\n    xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"\n    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"\n    mc:Ignorable="x14ac"\n    xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac">\n  <numFmts count="'+aB.length+'">\n  '+C(aB,function(aF,aE){return'\n    <numFmt formatCode="'+z(aF.format)+'" numFmtId="'+(165+aE)+'" />';
})+'\n  </numFmts>\n  <fonts count="'+(aA.length+1)+'" x14ac:knownFonts="1">\n    <font>\n       <sz val="11" />\n       <color theme="1" />\n       <name val="Calibri" />\n       <family val="2" />\n       <scheme val="minor" />\n    </font>\n    '+C(aA,function(aE){return"\n    <font>\n      "+(aE.bold?"<b/>":"")+"\n      "+(aE.italic?"<i/>":"")+"\n      "+(aE.underline?"<u/>":"")+'\n      <sz val="'+(aE.fontSize||11)+'" />\n      '+(aE.color?'<color rgb="'+z(aE.color)+'" />':'<color theme="1" />')+"\n      "+(aE.fontFamily?'\n        <name val="'+z(aE.fontFamily)+'" />\n        <family val="2" />\n      ':'\n        <name val="Calibri" />\n        <family val="2" />\n        <scheme val="minor" />\n      ')+"\n    </font>";
})+'\n  </fonts>\n  <fills count="'+(az.length+2)+'">\n      <fill><patternFill patternType="none"/></fill>\n      <fill><patternFill patternType="gray125"/></fill>\n    '+C(az,function(aE){return"\n      "+(aE.background?'\n        <fill>\n          <patternFill patternType="solid">\n              <fgColor rgb="'+z(aE.background)+'"/>\n          </patternFill>\n        </fill>\n      ':"");
})+'\n  </fills>\n  <borders count="'+(ay.length+1)+'">\n    <border><left/><right/><top/><bottom/><diagonal/></border>\n    '+C(ay,j)+'\n  </borders>\n  <cellStyleXfs count="1">\n    <xf borderId="0" fillId="0" fontId="0" />\n  </cellStyleXfs>\n  <cellXfs count="'+(aD.length+1)+'">\n    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" />\n    '+C(aD,function(aE){return'\n      <xf xfId="0"\n          '+(aE.fontId?'fontId="'+aE.fontId+'" applyFont="1"':"")+"\n          "+(aE.fillId?'fillId="'+aE.fillId+'" applyFill="1"':"")+"\n          "+(aE.numFmtId?'numFmtId="'+aE.numFmtId+'" applyNumberFormat="1"':"")+"\n          "+(aE.textAlign||aE.verticalAlign||aE.wrap?'applyAlignment="1"':"")+"\n          "+(aE.borderId?'borderId="'+aE.borderId+'" applyBorder="1"':"")+">\n        "+(aE.textAlign||aE.verticalAlign||aE.wrap?"\n        <alignment\n          "+(aE.textAlign?'horizontal="'+z(aE.textAlign)+'"':"")+"\n          "+(aE.verticalAlign?'vertical="'+z(aE.verticalAlign)+'"':"")+"\n          "+(aE.indent?'indent="'+z(aE.indent)+'"':"")+"\n          "+(aE.wrap?'wrapText="1"':"")+" />\n        ":"")+"\n      </xf>\n    ";
})+'\n  </cellXfs>\n  <cellStyles count="1">\n    <cellStyle name="Normal" xfId="0" builtinId="0"/>\n  </cellStyles>\n  <dxfs count="0" />\n  <tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleMedium9" />\n</styleSheet>';
};
function aw(ay){if(typeof ay=="string"){return"<f>"+z(ay)+"</f>";
}return'<f t="array" ref="'+ay.ref+'">'+z(ay.src)+"</f>";
}function P(ay){var az=Math.floor(ay/26)-1;
return(az>=0?P(az):"")+String.fromCharCode(65+ay%26);
}function Y(az,ay){return P(ay)+(az+1);
}function b(az,ay){return"$"+P(ay)+"$"+(az+1);
}function B(az){var ay=az.frozenRows||(az.freezePane||{}).rowSplit||1;
return ay-1;
}function ao(az){var ay=7;
return az/ay-Math.floor(128/ay)/256;
}function an(ay){return ay*0.75;
}function ak(ay){return String(ay).replace(/[\x00-\x09\x0B\x0C\x0E-\x1F]/g,"").replace(/\r?\n/g,"\r\n");
}var at=kendo.Class.extend({init:function(az,aA,aB,ay){this.options=az;
this._strings=aA;
this._styles=aB;
this._borders=ay;
this._validations={};
this._comments=[];
this._drawings=az.drawings||[];
this._hyperlinks=(this.options.hyperlinks||[]).map(function(aD,aC){return a.extend({},aD,{rId:"link"+aC});
});
},relsToXML:function(){var aA=this._hyperlinks;
var ay=this._comments;
var az=this._drawings;
if(aA.length||ay.length||az.length){return av({hyperlinks:aA,comments:ay,sheetIndex:this.options.sheetIndex,drawings:az});
}},toXML:function(aF){var aK=this;
var aI=this.options.mergedCells||[];
var aJ=this.options.rows||[];
var az=G(aJ,aI);
this._readCells(az);
var ay=this.options.filter;
var aC;
if(ay&&typeof ay.from==="number"&&typeof ay.to==="number"){ay={from:Y(B(this.options),ay.from),to:Y(B(this.options),ay.to)};
}else{if(ay&&ay.ref&&ay.columns){aC=ay;
ay=null;
}}var aL=[];
for(var aE in this._validations){if(Object.prototype.hasOwnProperty.call(aK._validations,aE)){aL.push(aK._validations[aE]);
}}var aA=null;
if(this.options.defaultCellStyle){aA=this._lookupStyle(this.options.defaultCellStyle);
}var aD=this.options.freezePane||{};
var aB=this.options.defaults||{};
var aH=this.options.rows?this._getLastRow():1;
var aG=this.options.rows?this._getLastCol():1;
return au({frozenColumns:this.options.frozenColumns||aD.colSplit,frozenRows:this.options.frozenRows||aD.rowSplit,columns:this.options.columns,defaults:aB,data:az,index:aF,mergeCells:aI,autoFilter:ay,filter:aC,showGridLines:this.options.showGridLines,hyperlinks:this._hyperlinks,validations:aL,defaultCellStyleId:aA,rtl:this.options.rtl!==undefined?this.options.rtl:aB.rtl,legacyDrawing:this._comments.length?"vml"+this.options.sheetIndex:null,drawing:this._drawings.length?"drw"+this.options.sheetIndex:null,lastRow:aH,lastCol:aG});
},commentsXML:function(){if(this._comments.length){return k({comments:this._comments});
}},drawingsXML:function(ay){if(this._drawings.length){var aA={};
var az=this._drawings.map(function(aB){var aD=U(aB.topLeftCell);
var aC=aA[aB.image];
if(!aC){aC=aA[aB.image]={rId:"img"+aB.image,target:ay[aB.image].target};
}return{col:aD.col,colOffset:V(aB.offsetX),row:aD.row,rowOffset:V(aB.offsetY),width:V(aB.width),height:V(aB.height),imageId:aC.rId};
});
return{main:x(az),rels:w(aA)};
}},legacyDrawing:function(){if(this._comments.length){return K({comments:this._comments});
}},_lookupString:function(aB){var az="$"+aB;
var ay=this._strings.indexes[az];
var aA;
if(ay!==undefined){aA=ay;
}else{aA=this._strings.indexes[az]=this._strings.uniqueCount;
this._strings.uniqueCount++;
}this._strings.count++;
return aA;
},_lookupStyle:function(aA){var az=JSON.stringify(aA);
if(az==="{}"){return 0;
}var ay=E(az,this._styles);
if(ay<0){ay=this._styles.push(az)-1;
}return ay+1;
},_lookupBorder:function(ay){var aA=JSON.stringify(ay);
if(aA==="{}"){return;
}var az=E(aA,this._borders);
if(az<0){az=this._borders.push(aA)-1;
}return az+1;
},_readCells:function(aD){var aE=this;
for(var aA=0;
aA<aD.length;
aA++){var aC=aD[aA];
var az=aC.cells;
aC.data=[];
for(var aB=0;
aB<az.length;
aB++){var ay=aE._cell(az[aB],aC.index,aB);
if(ay){aC.data.push(ay);
}}}},_cell:function(aE,aH,aA){if(!aE||aE===y){return null;
}var aK=aE.value;
var az={};
if(aE.borderLeft){az.left=aE.borderLeft;
}if(aE.borderRight){az.right=aE.borderRight;
}if(aE.borderTop){az.top=aE.borderTop;
}if(aE.borderBottom){az.bottom=aE.borderBottom;
}az=this._lookupBorder(az);
var aF=this.options.defaultCellStyle||{};
var aI={borderId:az};
(function(aL){aL("color");
aL("background");
aL("bold");
aL("italic");
aL("underline");
if(!aL("fontFamily")){aL("fontName","fontFamily");
}aL("fontSize");
aL("format");
if(!aL("textAlign")){aL("hAlign","textAlign");
}if(!aL("verticalAlign")){aL("vAlign","verticalAlign");
}aL("wrap");
aL("indent");
}(function(aL,aM){var aN=aE[aL];
if(aN===undefined){aN=aF[aL];
}if(aN!==undefined){aI[aM||aL]=aN;
return true;
}}));
var aD=this.options.columns||[];
var aC=aD[aA];
var aJ=typeof aK;
if(aC&&aC.autoWidth&&(!aE.colSpan||aE.colSpan===1)){var aG=aK;
if(aJ==="number"){aG=J.toString(aK,aE.format);
}aC.width=Math.max(aC.width||0,String(aG).length);
}if(aJ==="string"){aK=ak(aK);
aK=this._lookupString(aK);
aJ="s";
}else{if(aJ==="number"){aJ="n";
}else{if(aJ==="boolean"){aJ="b";
aK=Number(aK);
}else{if(aK&&aK.getTime){aJ=null;
aK=u(aK);
if(!aI.format){aI.format="mm-dd-yy";
}}else{aJ=null;
aK=null;
}}}}aI=this._lookupStyle(aI);
var aB=Y(aH,aA);
if(aE.validation){this._addValidation(aE.validation,aB);
}if(aE.comment){var ay=[aA+1,15,aH,10,aA+3,15,aH+3,4];
this._comments.push({ref:aB,text:aE.comment,row:aH,col:aA,anchor:ay.join(", ")});
}return{value:aK,formula:aE.formula,type:aJ,style:aI,ref:aB};
},_addValidation:function(aB,az){var aA={showErrorMessage:aB.type==="reject"?1:0,formula1:aB.from,formula2:aB.to,type:N[aB.dataType]||aB.dataType,operator:M[aB.comparerType]||aB.comparerType,allowBlank:aB.allowNulls?1:0,showDropDown:aB.showButton?0:1,error:aB.messageTemplate,errorTitle:aB.titleTemplate};
var ay=JSON.stringify(aA);
if(!this._validations[ay]){this._validations[ay]=aA;
aA.sqref=[];
}this._validations[ay].sqref.push(az);
},_getLastRow:function(){return o(this.options.rows);
},_getLastCol:function(){var ay=0;
this.options.rows.forEach(function(az){if(az.cells){ay=Math.max(ay,o(az.cells));
}});
return ay;
}});
function o(ay){var az=ay.length;
ay.forEach(function(aA){if(aA.index&&aA.index>=az){az=aA.index+1;
}});
return az;
}var M={greaterThanOrEqualTo:"greaterThanOrEqual",lessThanOrEqualTo:"lessThanOrEqual"};
var N={number:"decimal"};
var v={General:0,"0":1,"0.00":2,"#,##0":3,"#,##0.00":4,"0%":9,"0.00%":10,"0.00E+00":11,"# ?/?":12,"# ??/??":13,"mm-dd-yy":14,"d-mmm-yy":15,"d-mmm":16,"mmm-yy":17,"h:mm AM/PM":18,"h:mm:ss AM/PM":19,"h:mm":20,"h:mm:ss":21,"m/d/yy h:mm":22,"#,##0 ;(#,##0)":37,"#,##0 ;[Red](#,##0)":38,"#,##0.00;(#,##0.00)":39,"#,##0.00;[Red](#,##0.00)":40,"mm:ss":45,"[h]:mm:ss":46,"mmss.0":47,"##0.0E+0":48,"@":49,"[$-404]e/m/d":27,"m/d/yy":30,t0:59,"t0.00":60,"t#,##0":61,"t#,##0.00":62,"t0%":67,"t0.00%":68,"t# ?/?":69,"t# ??/??":70};
function m(az){var ay=az;
if(ay.length<6){ay=ay.replace(/(\w)/g,function(aA,aB){return aB+aB;
});
}ay=ay.substring(1).toUpperCase();
if(ay.length<8){ay="FF"+ay;
}return ay;
}var ap=kendo.Class.extend({init:function(ay){var az=this;
this.options=ay||{};
this._strings={indexes:{},count:0,uniqueCount:0};
this._styles=[];
this._borders=[];
this._images=this.options.images;
this._imgId=0;
this._sheets=L(this.options.sheets||[],function(aB,aA){aB.defaults=az.options;
aB.sheetIndex=aA+1;
return new at(aB,az._strings,az._styles,az._borders);
});
},imageFilename:function(az){var ay=++this._imgId;
switch(az){case"image/jpg":case"image/jpeg":return"image"+ay+".jpg";
case"image/png":return"image"+ay+".png";
case"image/gif":return"image"+ay+".gif";
default:return"image"+ay+".bin";
}},toZIP:function(){var aZ=this;
var a3=p();
var aC=a3.folder("docProps");
aC.file("core.xml",n({creator:this.options.creator||"Kendo UI",lastModifiedBy:this.options.creator||"Kendo UI",created:this.options.date||new Date().toJSON(),modified:this.options.date||new Date().toJSON()}));
var aT=this._sheets.length;
aC.file("app.xml",c({sheets:this._sheets}));
var aQ=a3.folder("_rels");
aQ.file(".rels",Z);
var a1=a3.folder("xl");
var a2=a1.folder("_rels");
a2.file("workbook.xml.rels",ar({count:aT}));
if(this._images){var aN=a1.folder("media");
Object.keys(this._images).forEach(function(a5){var a6=aZ._images[a5];
var a4=aZ.imageFilename(a6.type);
aN.file(a4,a6.data);
a6.target="../media/"+a4;
});
}var aU={};
a1.file("workbook.xml",aq({sheets:this._sheets,filterNames:L(this._sheets,function(a9,a7){var a8=a9.options;
var ba=a8.name||a8.title||"Sheet"+(a7+1);
aU[ba.toLowerCase()]=a7;
var a5=a8.filter;
if(a5){if(a5.ref){var a4=a5.ref.split(":");
var a6=U(a4[0]);
var bb=U(a4[1]);
return{localSheetId:a7,name:ba,from:b(a6.row,a6.col),to:b(bb.row,bb.col)};
}else{if(typeof a5.from!=="undefined"&&typeof a5.to!=="undefined"){return{localSheetId:a7,name:ba,from:b(B(a8),a5.from),to:b(B(a8),a5.to)};
}}}}),userNames:L(this.options.names||[],function(a4){return{name:a4.localName,localSheetId:a4.sheet?aU[a4.sheet.toLowerCase()]:null,value:a4.value,hidden:a4.hidden};
})}));
var a0=a1.folder("worksheets");
var aE=a1.folder("drawings");
var aF=aE.folder("_rels");
var aW=a0.folder("_rels");
var az=[];
var aD=[];
for(var aL=0;
aL<aT;
aL++){var aS=aZ._sheets[aL];
var aV="sheet"+(aL+1)+".xml";
var aX=aS.toXML(aL);
var aR=aS.relsToXML();
var aA=aS.commentsXML();
var aM=aS.legacyDrawing();
var aG=aS.drawingsXML(aZ._images);
if(aR){aW.file(aV+".rels",aR);
}if(aA){var aO="comments"+aS.options.sheetIndex+".xml";
a1.file(aO,aA);
az.push(aO);
}if(aM){aE.file("vmlDrawing"+aS.options.sheetIndex+".vml",aM);
}if(aG){var aP="drawing"+aS.options.sheetIndex+".xml";
aE.file(aP,aG.main);
aF.file(aP+".rels",aG.rels);
aD.push(aP);
}a0.file(aV,aX);
}var ay=L(this._borders,T);
var aY=L(this._styles,T);
var aK=function(a4){return a4.underline||a4.bold||a4.italic||a4.color||a4.fontFamily||a4.fontSize;
};
var aB=function(a6){var a5=Number(a6);
var a4;
if(a5){a4=a5*3/4;
}return a4;
};
var aI=L(aY,function(a4){if(a4.fontSize){a4.fontSize=aB(a4.fontSize);
}if(a4.color){a4.color=m(a4.color);
}if(aK(a4)){return a4;
}});
var aJ=L(aY,function(a4){if(a4.format&&v[a4.format]===undefined){return a4;
}});
var aH=L(aY,function(a4){if(a4.background){a4.background=m(a4.background);
return a4;
}});
a1.file("styles.xml",al({fonts:aI,fills:aH,formats:aJ,borders:ay,styles:L(aY,function(a5){var a4={};
if(aK(a5)){a4.fontId=E(a5,aI)+1;
}if(a5.background){a4.fillId=E(a5,aH)+2;
}a4.textAlign=a5.textAlign;
a4.indent=a5.indent;
a4.verticalAlign=a5.verticalAlign;
a4.wrap=a5.wrap;
a4.borderId=a5.borderId;
if(a5.format){if(v[a5.format]!==undefined){a4.numFmtId=v[a5.format];
}else{a4.numFmtId=165+E(a5,aJ);
}}return a4;
})}));
a1.file("sharedStrings.xml",ab(this._strings));
a3.file("[Content_Types].xml",l({sheetCount:aT,commentFiles:az,drawingFiles:aD}));
return a3;
},toDataURL:function(){var ay=this.toZIP();
return ay.generateAsync?ay.generateAsync(r).then(am):am(ay.generate(r));
},toBlob:function(){var ay=this.toZIP();
if(ay.generateAsync){return ay.generateAsync(g);
}return new Blob([ay.generate(e)],{type:O});
}});
function i(az){var ay="thin";
if(az===2){ay="medium";
}else{if(az===3){ay="thick";
}}return ay;
}function h(ay,aA){var az="";
if(aA){az+="<"+ay+' style="'+i(aA.size)+'">';
if(aA.color){az+='<color rgb="'+m(aA.color)+'"/>';
}az+="</"+ay+">";
}return az;
}function j(ay){return"<border>"+h("left",ay.left)+h("right",ay.right)+h("top",ay.top)+h("bottom",ay.bottom)+"</border>";
}var y={};
function G(aC,aA){var aB=[];
var aD=[];
F(aC,function(aH,aG){var aF={_source:aH,index:aG,height:aH.height,level:aH.level,cells:[]};
aB.push(aF);
aD[aG]=aF;
});
var aE=ac(aB).slice(0);
var ay={rowData:aB,rowsByIndex:aD,mergedCells:aA};
for(var az=0;
az<aE.length;
az++){A(aE[az],ay);
delete aE[az]._source;
}return ac(aB);
}function F(aC,ay){for(var az=0;
az<aC.length;
az++){var aB=aC[az];
if(!aB){continue;
}var aA=aB.index;
if(typeof aA!=="number"){aA=az;
}ay(aB,aA);
}}function ac(ay){return ay.sort(function(az,aA){return az.index-aA.index;
});
}function W(ay,az){if(ay.indexOf(az)<0){ay.push(az);
}}function D(aB,aD){for(var aA=0;
aA<aB.length;
++aA){var aC=aB[aA];
var ay=aC.split(":");
var aE=ay[0];
if(aE===aD){var az=ay[1];
aE=U(aE);
az=U(az);
return{rowSpan:az.row-aE.row+1,colSpan:az.col-aE.col+1};
}}}function U(aB){function ay(aE){var aF=aE.toUpperCase();
var aC=0;
for(var aD=0;
aD<aF.length;
++aD){aC=aC*26+aF.charCodeAt(aD)-64;
}return aC-1;
}function az(aC){return parseInt(aC,10)-1;
}var aA=/^([a-z]+)(\d+)$/i.exec(aB);
return{row:az(aA[2]),col:ay(aA[1])};
}function V(ay){return Math.round(ay*9525);
}function A(aE,aD){var aI=aE._source;
var aJ=aE.index;
var aB=aI.cells;
var az=aE.cells;
if(!aB){return;
}for(var aF=0;
aF<aB.length;
aF++){var ay=aB[aF]||y;
var aK=ay.rowSpan||1;
var aC=ay.colSpan||1;
var aA=H(az,ay);
var aM=Y(aJ,aA);
if(aK===1&&aC===1){var aL=D(aD.mergedCells,aM);
if(aL){aC=aL.colSpan;
aK=aL.rowSpan;
}}ad(ay,az,aA,aC);
if(aK>1||aC>1){W(aD.mergedCells,aM+":"+Y(aJ+aK-1,aA+aC-1));
}if(aK>1){for(var aH=aJ+1;
aH<aJ+aK;
aH++){var aG=aD.rowsByIndex[aH];
if(!aG){aG=aD.rowsByIndex[aH]={index:aH,cells:[]};
aD.rowData.push(aG);
}ad(ay,aG.cells,aA-1,aC+1);
}}}}function H(az,ay){var aA;
if(typeof ay.index==="number"){aA=ay.index;
I(az,ay,ay.index);
}else{aA=d(az,ay);
}return aA;
}function I(az,ay,aA){az[aA]=ay;
}function d(az,ay){var aB=az.length;
for(var aA=0;
aA<az.length+1;
aA++){if(!az[aA]){az[aA]=ay;
aB=aA;
break;
}}return aB;
}function ad(ay,aB,aC,az){for(var aA=1;
aA<az;
aA++){var aD={borderTop:ay.borderTop,borderRight:ay.borderRight,borderBottom:ay.borderBottom,borderLeft:ay.borderLeft};
I(aB,aD,aC+aA);
}}var ag=function(aB){var aA=aB.ref;
var ay=aB.columns;
var az=aB.generators;
return'\n<autoFilter ref="'+aA+'">\n  '+C(ay,function(aC){return'\n    <filterColumn colId="'+aC.index+'">\n      '+az[aC.filter](aC)+"\n    </filterColumn>\n  ";
})+"\n</autoFilter>";
};
var ae=function(aA){var az=aA.logic;
var ay=aA.criteria;
return"\n<customFilters "+(az==="and"?'and="1"':"")+">\n"+C(ay,function(aB){var aC=aj.customOperator(aB);
var aD=aj.customValue(aB);
return"<customFilter "+(aC?'operator="'+aC+'"':"")+' val="'+aD+'"/>';
})+"\n</customFilters>";
};
var af=function(ay){var az=ay.type;
return'<dynamicFilter type="'+aj.dynamicFilterType(az)+'" />';
};
var ah=function(ay){var az=ay.type;
var aA=ay.value;
return'<top10 percent="'+(/percent$/i.test(az)?1:0)+'"\n       top="'+(/^top/i.test(az)?1:0)+'"\n       val="'+aA+'" />';
};
var ai=function(az){var ay=az.blanks;
var aA=az.values;
return"<filters "+(ay?'blank="1"':"")+">\n    "+C(aA,function(aB){return'\n      <filter val="'+aB+'" />';
})+"\n  </filters>";
};
function aj(ay){return ag({ref:ay.ref,columns:ay.columns,generators:{custom:ae,dynamic:af,top:ah,value:ai}});
}aj.customOperator=function(ay){return{eq:"equal",gt:"greaterThan",gte:"greaterThanOrEqual",lt:"lessThan",lte:"lessThanOrEqual",ne:"notEqual",doesnotstartwith:"notEqual",doesnotendwith:"notEqual",doesnotcontain:"notEqual",doesnotmatch:"notEqual"}[ay.operator.toLowerCase()];
};
function X(ay){if(/^\'/.test(ay)){return ay;
}if(/^[a-z_][a-z0-9_]*$/i.test(ay)){return ay;
}return"'"+ay.replace(/\x27/g,"\\'")+"'";
}aj.customValue=function(az){function ay(aA){return aA.replace(/([*?])/g,"~$1");
}switch(az.operator.toLowerCase()){case"startswith":case"doesnotstartwith":return ay(az.value)+"*";
case"endswith":case"doesnotendwith":return"*"+ay(az.value);
case"contains":case"doesnotcontain":return"*"+ay(az.value)+"*";
default:return az.value;
}};
aj.dynamicFilterType=function(ay){return{quarter1:"Q1",quarter2:"Q2",quarter3:"Q3",quarter4:"Q4",january:"M1",february:"M2",march:"M3",april:"M4",may:"M5",june:"M6",july:"M7",august:"M8",september:"M9",october:"M10",november:"M11",december:"M12"}[ay.toLowerCase()]||ay;
};
kendo.deepExtend(kendo.ooxml,{IntlService:J,Workbook:ap,Worksheet:at});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("ooxml/main",["kendo.core","ooxml/kendo-ooxml"],b);
}(function(){(function(a){var b=kendo.ooxml.Workbook;
kendo.ooxml.IntlService.register({toString:kendo.toString});
kendo.ooxml.Workbook=b.extend({toDataURL:function(){var c=b.fn.toDataURL.call(this);
if(typeof c!=="string"){throw new Error("The toDataURL method can be used only with jsZip 2. Either include jsZip 2 or use the toDataURLAsync method.");
}return c;
},toDataURLAsync:function(){var c=a.Deferred();
var d=b.fn.toDataURL.call(this);
if(typeof d==="string"){d=c.resolve(d);
}else{if(d&&d.then){d.then(function(e){c.resolve(e);
},function(){c.reject();
});
}}return c.promise();
}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.ooxml",["ooxml/main"],b);
}(function(){var a={id:"ooxml",name:"XLSX generation",category:"framework",advanced:true,depends:["core"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
