(function(b,a){a("kendo.pager",["kendo.data"],b);
}(function(){var a={id:"pager",name:"Pager",category:"framework",depends:["data"],advanced:true};
(function(b,A){var k=window.kendo,z=k.ui,C=z.Widget,w=b.proxy,h=".k-i-arrow-end-left",n=".k-i-arrow-end-right",v=".k-i-arrow-60-left",r=".k-i-arrow-60-right",y="k-pager-md k-pager-sm",d="change",s=".kendoPager",e="click",l="keydown",f="disabled",p="down",o=Number.MAX_VALUE,j=k.template('<a href="\\#" aria-label="#=text#" title="#=text#" class="k-link k-pager-nav #= wrapClassName #"><span class="k-icon #= className #"></span></a>');
function c(F,D,G,E,H){return F({idx:D,text:G,ns:k.ns,numeric:E,title:H||""});
}function x(F,D,G,E){return F({idx:D,text:G||D,selected:E||false});
}function i(D,E,F){return j({className:D.substring(1),text:E,wrapClassName:F||""});
}function B(E,G,F,D){E.find(G).parent().attr(k.attr("page"),F).attr("tabindex",-1).toggleClass("k-state-disabled",D);
}function g(D,E){B(D,h,1,E<=1);
}function u(D,E){B(D,v,Math.max(1,E-1),E<=1);
}function q(D,E,F){B(D,r,Math.min(F,E+1),E>=F);
}function m(D,E,F){B(D,n,F,E>=F);
}var t=C.extend({init:function(D,E){var J=this,F,K;
var I=null;
C.fn.init.call(J,D,E);
E=J.options;
J._createDataSource(E);
J.linkTemplate=k.template(J.options.linkTemplate);
J.selectTemplate=k.template(J.options.selectTemplate);
J.currentPageTemplate=k.template(J.options.currentPageTemplate);
J.numericSelectItemTemplate=k.template(J.options.numericSelectItemTemplate);
F=J.page();
K=J.totalPages();
J._refreshHandler=w(J.refresh,J);
J.dataSource.bind(d,J._refreshHandler);
J.downEvent=k.applyEventMap(p,k.guid());
if(E.previousNext){if(!J.element.find(h).length){J.element.append(i(h,E.messages.first,"k-pager-first"));
g(J.element,F,K);
}if(!J.element.find(v).length){J.element.append(i(v,E.messages.previous));
u(J.element,F,K);
}}if(E.numeric){if(!J._numericWrap){J._numericWrap=J.element.find(".k-pager-numbers-wrap");
if(J._numericWrap.length===0){J._numericWrap=b("<div class='k-pager-numbers-wrap' />").appendTo(J.element);
}}if(!J._numericSelect){J._numericSelect=J._numericWrap.find(".k-dropdown");
if(J._numericSelect.length===0){J._numericSelect=b("<select class='k-dropdown' />").appendTo(J._numericWrap);
}}if(!J.list){J.list=J._numericWrap.find(".k-pager-numbers");
if(J.list.length===0){J.list=b('<ul class="k-pager-numbers" />').appendTo(J._numericWrap);
}}if(E.dataSource&&!E.dataSource.total()){J._numericSelect.empty().append("<option value='0' />");
J.list.empty().append(J.selectTemplate({text:0}));
}}if(E.input){if(!J.element.find(".k-pager-input").length){J.element.append('<span class="k-pager-input k-label">'+E.messages.page+'<input class="k-textbox">'+k.format(E.messages.of,K)+"</span>");
}J.element.on(l+s,".k-pager-input input",w(J._keydown,J));
}if(E.previousNext){if(!J.element.find(r).length){J.element.append(i(r,E.messages.next));
q(J.element,F,K);
}if(!J.element.find(n).length){J.element.append(i(n,E.messages.last,"k-pager-last"));
m(J.element,F,K);
}}if(E.pageSizes){if(!J.element.find(".k-pager-sizes").length){var H=E.pageSizes.length?E.pageSizes:["all",5,10,20];
var G=b.map(H,function(L){if(L.toLowerCase&&L.toLowerCase()==="all"){return"<option value='all'>"+E.messages.allPages+"</option>";
}return"<option>"+L+"</option>";
});
b('<span class="k-pager-sizes k-label"><select></select>'+E.messages.itemsPerPage+"</span>").appendTo(J.element).find("select").html(G.join("")).end().appendTo(J.element);
}J.element.find(".k-pager-sizes select").val(J.pageSize());
if(k.ui.DropDownList){J.element.find(".k-pager-sizes select").show().kendoDropDownList();
}J.element.on(d+s,".k-pager-sizes select",w(J._change,J));
}if(E.refresh){if(!J.element.find(".k-pager-refresh").length){J.element.append('<a href="#" class="k-pager-refresh k-link" title="'+E.messages.refresh+'" aria-label="'+E.messages.refresh+'"><span class="k-icon k-i-reload"></span></a>');
}J.element.on(e+s,".k-pager-refresh",w(J._refreshClick,J));
}if(E.info){if(!J.element.find(".k-pager-info").length){J.element.append('<span class="k-pager-info k-label" />');
}}J.element.on(e+s,"a",w(J._click,J)).on(d+s,"select.k-dropdown",w(J._numericSelectChange,J)).addClass("k-pager-wrap k-widget k-floatwrap");
if(E.autoBind){J.refresh();
}J._resizeHandler=w(J.resize,J,true);
b(window).on("resize"+s,J._resizeHandler);
I=J._getWidthSizeClass(J.element.outerWidth());
if(I){J.element.addClass(I);
}k.notify(J);
},destroy:function(){var D=this;
C.fn.destroy.call(D);
D.element.off(s);
D.dataSource.unbind(d,D._refreshHandler);
D._refreshHandler=null;
b(window).off("resize"+s,this._resizeHandler);
k.destroy(D.element);
D.element=D.list=null;
},events:[d],options:{name:"Pager",selectTemplate:'<li><span class="k-link k-state-selected">#=text#</span></li>',currentPageTemplate:'<li class="k-current-page"><span class="k-link k-pager-nav">#=text#</span></li>',linkTemplate:'<li><a tabindex="-1" href="\\#" class="k-link" data-#=ns#page="#=idx#" #if (title !== "") {# title="#=title#" #}#>#=text#</a></li>',numericItemTemplate:'<li><a tabindex="-1" href="\\#" class="k-link" data-#=ns#page="#=idx#" #if (title !== "") {# title="#=title#" #}#>#=text#</a></li>',numericSelectItemTemplate:'<option value="#= idx #" #if (selected) {# selected="selected" #}#>#= text #</option>',buttonCount:10,autoBind:true,numeric:true,info:true,input:false,previousNext:true,pageSizes:false,refresh:false,responsive:true,messages:{allPages:"All",display:"{0} - {1} of {2} items",empty:"No items to display",page:"Page",of:"of {0}",itemsPerPage:"items per page",first:"Go to the first page",previous:"Go to the previous page",next:"Go to the next page",last:"Go to the last page",refresh:"Refresh",morePages:"More pages"}},setDataSource:function(D){var E=this;
E.dataSource.unbind(d,E._refreshHandler);
E.dataSource=E.options.dataSource=D;
D.bind(d,E._refreshHandler);
if(E.options.autoBind){D.fetch();
}},_resize:function(E){if(E.width){var F=this._getWidthSizeClass(E.width);
var D=this.element;
if(!F){D.removeClass(y);
}else{if(!D.hasClass(F)){D.removeClass(y);
D.addClass(F);
}}}},_createDataSource:function(D){this.dataSource=k.data.DataSource.create(D.dataSource);
},refresh:function(F){var U=this,J,G,S=1,P,N=U.page(),I="",R="",M=U.options,O=U.pageSize(),E=U._collapsedTotal(),V=U.dataSource._isGroupPaged()?U.dataSource.groupsTotal(true):U.dataSource.total(),W=U.totalPages(),K=U.linkTemplate,L=U.numericSelectItemTemplate,D=M.buttonCount;
if(F&&F.action=="itemchange"){return;
}if(M.numeric){if(N>D){P=N%D;
S=P===0?N-D+1:N-P+1;
}G=Math.min(S+D-1,W);
if(S>1){I+=c(K,S-1,"...",false,M.messages.morePages);
R+=x(L,S-1,M.messages.morePages);
}for(J=S;
J<=G;
J++){I+=c(J==N?U.selectTemplate:K,J,J,true);
R+=x(L,J,J,J==N);
}if(G<W){I+=c(K,J,"...",false,M.messages.morePages);
R+=x(L,J,M.messages.morePages);
}if(I===""){I=U.selectTemplate({text:0});
R=b("<option value='0' />");
}U.list.html(I);
U._numericSelect.html(R);
}if(M.info){if(V>0){I=k.format(M.messages.display,U.dataSource.options.endless?1:Math.min((N-1)*(U.dataSource.pageSize()||0)+1,E),Math.min(N*O,E),V);
}else{I=M.messages.empty;
}U.element.find(".k-pager-info").html(I);
}if(M.input){U.element.find(".k-pager-input").html(U.options.messages.page+'<input class="k-textbox" aria-label="'+N+'">'+k.format(M.messages.of,W)).find("input").val(N).attr(f,V<1).toggleClass("k-state-disabled",V<1);
}if(M.previousNext){g(U.element,N,W);
u(U.element,N,W);
q(U.element,N,W);
m(U.element,N,W);
}if(M.pageSizes){var H=U.element.find(".k-pager-sizes option[value='all']").length>0;
var Q=H&&(O===this.dataSource.total()||O==o);
var T=O;
if(Q){O="all";
T=M.messages.allPages;
}U.element.find(".k-pager-sizes select").val(O).attr("aria-label",O).filter("["+k.attr("role")+"=dropdownlist]").kendoDropDownList("value",O).kendoDropDownList("text",T);
}},_collapsedTotal:function(){return this.dataSource.total();
},_keydown:function(D){if(D.keyCode===k.keys.ENTER){var E=this.element.find(".k-pager-input").find("input"),F=parseInt(E.val(),10);
if(isNaN(F)||F<1||F>this.totalPages()){F=this.page();
}E.val(F);
this.page(F);
}},_refreshClick:function(D){D.preventDefault();
this.dataSource.read();
},_change:function(E){var G=E.currentTarget.value;
var F=parseInt(G,10);
var D=this.dataSource;
if(!isNaN(F)){D.pageSize(F);
}else{if((G+"").toLowerCase()=="all"){D._pageSize=A;
D._take=A;
D._skip=0;
D.fetch();
}}},_numericSelectChange:function(D){var F=D.currentTarget;
var G=F.value;
var E=parseInt(G,10);
F.blur();
this.page(E);
},_click:function(D){var E=b(D.currentTarget);
D.preventDefault();
if(!E.is(".k-state-disabled")){this.page(parseInt(E.attr(k.attr("page")),10));
}},totalPages:function(){return Math.ceil((this.dataSource.total()||0)/(this.pageSize()||1));
},pageSize:function(){return this.dataSource.pageSize()||this.dataSource.total();
},page:function(D){if(D){if(this.trigger("pageChange",{index:D})){return;
}this.dataSource.page(D);
this.trigger(d,{index:D});
}else{if(this.dataSource.total()>0){return this.dataSource.page();
}else{return 0;
}}},_getWidthSizeClass:function(F){var E=this,D=y.split(" ");
if(!E.options.responsive){return null;
}else{if(F<=480){return D[1];
}else{if(F<=600){return D[0];
}}}return null;
}});
z.plugin(t);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
