(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/pako",["kendo.core"],b);
}(function(){(function(){kendo.pdf=kendo.pdf||{};
kendo.pdf.supportsDeflate=function(){return window.pako&&typeof window.pako.deflate=="function";
};
kendo.pdf.deflate=function(a){return window.pako.deflate(a);
};
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/core",["pdf/pako","kendo.core","kendo.color","kendo.drawing"],b);
}(function(){(function(ae){window.kendo.pdf=window.kendo.pdf||{};
var a=ae.jQuery;
var be=ae.support;
var bf=be.browser;
var ag=ae.pdf;
var D=ae.drawing;
var bp=D.util;
var af=ae.geometry;
var T=typeof Uint8Array!=="undefined"&&ae.support.browser&&(!ae.support.browser.msie||ae.support.browser.version>9);
var e=function(){var bs="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(bE){var bB=bE.replace(/[^A-Za-z0-9\+\/\=]/g,""),bA=0,bC=bB.length,bD=[];
while(bA<bC){var bw=bs.indexOf(bB.charAt(bA++));
var bx=bs.indexOf(bB.charAt(bA++));
var by=bs.indexOf(bB.charAt(bA++));
var bz=bs.indexOf(bB.charAt(bA++));
var bt=bw<<2|bx>>>4;
var bu=(bx&15)<<4|by>>>2;
var bv=(by&3)<<6|bz;
bD.push(bt);
if(by!=64){bD.push(bu);
}if(bz!=64){bD.push(bv);
}}return bD;
},encode:function(bt){var bB=0,bC=bt.length;
var bD="";
while(bB<bC){var bu=bt[bB++];
var bv=bt[bB++];
var bw=bt[bB++];
var bx=bu>>>2;
var by=(bu&3)<<4|bv>>>4;
var bz=(bv&15)<<2|bw>>>6;
var bA=bw&63;
if(bB-bC==2){bz=bA=64;
}else{if(bB-bC==1){bA=64;
}}bD+=bs.charAt(bx)+bs.charAt(by)+bs.charAt(bz)+bs.charAt(bA);
}return bD;
}};
}();
function g(bs){var bx=0,bw=0;
if(bs==null){bs=T?new Uint8Array(256):[];
}else{bw=bs.length;
}var bt=T?function(bT){if(bT>=bs.length){var bU=new Uint8Array(Math.max(bT+256,bs.length*2));
bU.set(bs,0);
bs=bU;
}}:function(){};
var bv=T?function(){return new Uint8Array(bs.buffer,0,bw);
}:function(){return bs;
};
var bK=T?function(bT){if(typeof bT=="string"){return bS(bT);
}var bU=bT.length;
bt(bx+bU);
bs.set(bT,bx);
bx+=bU;
if(bx>bw){bw=bx;
}}:function(bT){if(typeof bT=="string"){return bS(bT);
}for(var bU=0;
bU<bT.length;
++bU){bL(bT[bU]);
}};
var bH=T?function(bU,bT){if(bs.buffer.slice){return new Uint8Array(bs.buffer.slice(bU,bU+bT));
}else{var bV=new Uint8Array(bT);
bV.set(new Uint8Array(bs.buffer,bU,bT));
return bV;
}}:function(bU,bT){return bs.slice(bU,bU+bT);
};
function bu(){return bx>=bw;
}function bz(){return bx<bw?bs[bx++]:0;
}function bL(bT){bt(bx);
bs[bx++]=bT&255;
if(bx>bw){bw=bx;
}}function bE(){return bz()<<8|bz();
}function bQ(bT){bL(bT>>8);
bL(bT);
}function bF(){var bT=bE();
return bT>=32768?bT-65536:bT;
}function bR(bT){bQ(bT<0?bT+65536:bT);
}function bC(){return bE()*65536+bE();
}function bO(bT){bQ(bT>>>16&65535);
bQ(bT&65535);
}function bD(){var bT=bC();
return bT>=2147483648?bT-4294967296:bT;
}function bP(bT){bO(bT<0?bT+4294967296:bT);
}function bA(){return bC()/65536;
}function bM(bT){bO(Math.round(bT*65536));
}function bB(){return bD()/65536;
}function bN(bT){bP(Math.round(bT*65536));
}function by(bT){return bJ(bT,bz);
}function bG(bT){return String.fromCharCode.apply(String,by(bT));
}function bS(bU){for(var bT=0;
bT<bU.length;
++bT){bL(bU.charCodeAt(bT));
}}function bJ(bU,bV){for(var bW=new Array(bU),bT=0;
bT<bU;
++bT){bW[bT]=bV();
}return bW;
}var bI={eof:bu,readByte:bz,writeByte:bL,readShort:bE,writeShort:bQ,readLong:bC,writeLong:bO,readFixed:bA,writeFixed:bM,readShort_:bF,writeShort_:bR,readLong_:bD,writeLong_:bP,readFixed_:bB,writeFixed_:bN,read:by,write:bK,readString:bG,writeString:bS,times:bJ,get:bv,slice:bH,offset:function(bT){if(bT!=null){bx=bT;
return bI;
}return bx;
},skip:function(bT){bx+=bT;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return bw;
},saveExcursion:function(bT){var bU=bx;
try{return bT();
}finally{bx=bU;
}},writeBase64:function(bT){if(window.atob){bS(window.atob(bT));
}else{bK(e.decode(bT));
}},base64:function(){return e.encode(bv());
}};
return bI;
}function bl(bw){var bv=[],bs=0,bu=bw.length,bx,bt;
while(bs<bu){bx=bw.charCodeAt(bs++);
if(bx>=55296&&bx<=56319&&bs<bu){bt=bw.charCodeAt(bs++);
if((bt&64512)==56320){bv.push(((bx&1023)<<10)+(bt&1023)+65536);
}else{bv.push(bx);
bs--;
}}else{bv.push(bx);
}}return bv;
}function bm(bs){return bs.map(function(bu){var bt="";
if(bu>65535){bu-=65536;
bt+=String.fromCharCode(bu>>>10&1023|55296);
bu=56320|bu&1023;
}bt+=String.fromCharCode(bu);
return bt;
}).join("");
}function d(bs){var bt=window.atob(bs);
var bv=new Uint8Array(bt.length);
for(var bu=0;
bu<bt.length;
bu++){bv[bu]=bt.charCodeAt(bu);
}return bv;
}function r(bs){var bu=new Uint8Array(bs.length);
for(var bt=0;
bt<bs.length;
bt++){bu[bt]=bs[bt];
}return bu;
}function f(bs){if(window.atob){return d(bs);
}return r(e.decode(bs));
}function V(bt,bs){return Object.prototype.hasOwnProperty.call(bt,bs);
}function bb(bs){return Object.keys(bs).sort(function(bt,bu){return bt-bu;
}).map(parseFloat);
}function w(bs){this.raw=bs;
this.scalerType=bs.readLong();
this.tableCount=bs.readShort();
this.searchRange=bs.readShort();
this.entrySelector=bs.readShort();
this.rangeShift=bs.readShort();
var bv=this.tables={};
for(var bu=0;
bu<this.tableCount;
++bu){var bt={tag:bs.readString(4),checksum:bs.readLong(),offset:bs.readLong(),length:bs.readLong()};
bv[bt.tag]=bt;
}}w.prototype={readTable:function(bu,bs){var bt=this.tables[bu];
if(!bt){throw new Error("Table "+bu+" not found in directory");
}return this[bu]=bt.table=new bs(this,bt);
},render:function(bF){var bH=this;
var bD=Object.keys(bF).length;
var bw=Math.pow(2,Math.floor(Math.log(bD)/Math.LN2));
var bA=bw*16;
var bu=Math.floor(Math.log(bw)/Math.LN2);
var bz=bD*16-bA;
var by=g();
by.writeLong(this.scalerType);
by.writeShort(bD);
by.writeShort(bA);
by.writeShort(bu);
by.writeShort(bz);
var bt=bD*16;
var bx=by.offset()+bt;
var bv=null;
var bE=g();
for(var bG in bF){if(V(bF,bG)){var bC=bF[bG];
by.writeString(bG);
by.writeLong(bH.checksum(bC));
by.writeLong(bx);
by.writeLong(bC.length);
bE.write(bC);
if(bG=="head"){bv=bx;
}bx+=bC.length;
while(bx%4){bE.writeByte(0);
bx++;
}}}by.write(bE.get());
var bB=this.checksum(by.get());
var bs=2981146554-bB;
by.offset(bv+8);
by.writeLong(bs);
return by.get();
},checksum:function(bs){bs=g(bs);
var bt=0;
while(!bs.eof()){bt+=bs.readLong();
}return bt&4294967295;
}};
function v(bu){function bs(bw,bv){this.definition=bv;
this.length=bv.length;
this.offset=bv.offset;
this.file=bw;
this.rawData=bw.raw;
this.parse(bw.raw);
}bs.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var bt in bu){if(V(bu,bt)){bs[bt]=bs.prototype[bt]=bu[bt];
}}return bs;
}var W=v({parse:function(bs){bs.offset(this.offset);
this.version=bs.readLong();
this.revision=bs.readLong();
this.checkSumAdjustment=bs.readLong();
this.magicNumber=bs.readLong();
this.flags=bs.readShort();
this.unitsPerEm=bs.readShort();
this.created=bs.read(8);
this.modified=bs.read(8);
this.xMin=bs.readShort_();
this.yMin=bs.readShort_();
this.xMax=bs.readShort_();
this.yMax=bs.readShort_();
this.macStyle=bs.readShort();
this.lowestRecPPEM=bs.readShort();
this.fontDirectionHint=bs.readShort_();
this.indexToLocFormat=bs.readShort_();
this.glyphDataFormat=bs.readShort_();
},render:function(bs){var bt=g();
bt.writeLong(this.version);
bt.writeLong(this.revision);
bt.writeLong(0);
bt.writeLong(this.magicNumber);
bt.writeShort(this.flags);
bt.writeShort(this.unitsPerEm);
bt.write(this.created);
bt.write(this.modified);
bt.writeShort_(this.xMin);
bt.writeShort_(this.yMin);
bt.writeShort_(this.xMax);
bt.writeShort_(this.yMax);
bt.writeShort(this.macStyle);
bt.writeShort(this.lowestRecPPEM);
bt.writeShort_(this.fontDirectionHint);
bt.writeShort_(bs);
bt.writeShort_(this.glyphDataFormat);
return bt.get();
}});
var ao=v({parse:function(bs){bs.offset(this.offset);
var bt=this.file.head.indexToLocFormat;
if(bt===0){this.offsets=bs.times(this.length/2,function(){return 2*bs.readShort();
});
}else{this.offsets=bs.times(this.length/4,bs.readLong);
}},offsetOf:function(bs){return this.offsets[bs];
},lengthOf:function(bs){return this.offsets[bs+1]-this.offsets[bs];
},render:function(bu){var bv=g();
var bt=bu[bu.length-1]>65535;
for(var bs=0;
bs<bu.length;
++bs){if(bt){bv.writeLong(bu[bs]);
}else{bv.writeShort(bu[bs]/2);
}}return{format:bt?1:0,table:bv.get()};
}});
var X=v({parse:function(bs){bs.offset(this.offset);
this.version=bs.readLong();
this.ascent=bs.readShort_();
this.descent=bs.readShort_();
this.lineGap=bs.readShort_();
this.advanceWidthMax=bs.readShort();
this.minLeftSideBearing=bs.readShort_();
this.minRightSideBearing=bs.readShort_();
this.xMaxExtent=bs.readShort_();
this.caretSlopeRise=bs.readShort_();
this.caretSlopeRun=bs.readShort_();
this.caretOffset=bs.readShort_();
bs.skip(4*2);
this.metricDataFormat=bs.readShort_();
this.numOfLongHorMetrics=bs.readShort();
},render:function(bs){var bt=g();
bt.writeLong(this.version);
bt.writeShort_(this.ascent);
bt.writeShort_(this.descent);
bt.writeShort_(this.lineGap);
bt.writeShort(this.advanceWidthMax);
bt.writeShort_(this.minLeftSideBearing);
bt.writeShort_(this.minRightSideBearing);
bt.writeShort_(this.xMaxExtent);
bt.writeShort_(this.caretSlopeRise);
bt.writeShort_(this.caretSlopeRun);
bt.writeShort_(this.caretOffset);
bt.write([0,0,0,0,0,0,0,0]);
bt.writeShort_(this.metricDataFormat);
bt.writeShort(bs.length);
return bt.get();
}});
var au=v({parse:function(bs){bs.offset(this.offset);
this.version=bs.readLong();
this.numGlyphs=bs.readShort();
this.maxPoints=bs.readShort();
this.maxContours=bs.readShort();
this.maxComponentPoints=bs.readShort();
this.maxComponentContours=bs.readShort();
this.maxZones=bs.readShort();
this.maxTwilightPoints=bs.readShort();
this.maxStorage=bs.readShort();
this.maxFunctionDefs=bs.readShort();
this.maxInstructionDefs=bs.readShort();
this.maxStackElements=bs.readShort();
this.maxSizeOfInstructions=bs.readShort();
this.maxComponentElements=bs.readShort();
this.maxComponentDepth=bs.readShort();
},render:function(bs){var bt=g();
bt.writeLong(this.version);
bt.writeShort(bs.length);
bt.writeShort(this.maxPoints);
bt.writeShort(this.maxContours);
bt.writeShort(this.maxComponentPoints);
bt.writeShort(this.maxComponentContours);
bt.writeShort(this.maxZones);
bt.writeShort(this.maxTwilightPoints);
bt.writeShort(this.maxStorage);
bt.writeShort(this.maxFunctionDefs);
bt.writeShort(this.maxInstructionDefs);
bt.writeShort(this.maxStackElements);
bt.writeShort(this.maxSizeOfInstructions);
bt.writeShort(this.maxComponentElements);
bt.writeShort(this.maxComponentDepth);
return bt.get();
}});
var Y=v({parse:function(bs){bs.offset(this.offset);
var bt=this.file,bu=bt.hhea;
this.metrics=bs.times(bu.numOfLongHorMetrics,function(){return{advance:bs.readShort(),lsb:bs.readShort_()};
});
var bv=bt.maxp.numGlyphs-bt.hhea.numOfLongHorMetrics;
this.leftSideBearings=bs.times(bv,bs.readShort_);
},forGlyph:function(bs){var bt=this.metrics;
var bu=bt.length;
if(bs<bu){return bt[bs];
}return{advance:bt[bu-1].advance,lsb:this.leftSideBearings[bs-bu]};
},render:function(bs){var bw=this;
var bv=g();
for(var bt=0;
bt<bs.length;
++bt){var bu=bw.forGlyph(bs[bt]);
bv.writeShort(bu.advance);
bv.writeShort_(bu.lsb);
}return bv.get();
}});
var S=function(){function bv(bz){this.raw=bz;
}bv.prototype={compound:false,render:function(){return this.raw.get();
}};
var bs=1;
var bw=8;
var bu=32;
var by=64;
var bx=128;
function bt(bz){this.raw=bz;
var bB=this.glyphIds=[];
var bC=this.idOffsets=[];
while(true){var bA=bz.readShort();
bC.push(bz.offset());
bB.push(bz.readShort());
if(!(bA&bu)){break;
}bz.skip(bA&bs?4:2);
if(bA&bx){bz.skip(8);
}else{if(bA&by){bz.skip(4);
}else{if(bA&bw){bz.skip(2);
}}}}}bt.prototype={compound:true,render:function(bB){var bD=this;
var bC=g(this.raw.get());
for(var bz=0;
bz<this.glyphIds.length;
++bz){var bA=bD.glyphIds[bz];
bC.offset(bD.idOffsets[bz]);
bC.writeShort(bB[bA]);
}return bC.get();
}};
return v({parse:function(){this.cache={};
},glyphFor:function(bC){var bz=this.cache;
if(V(bz,bC)){return bz[bC];
}var bE=this.file.loca;
var bD=bE.lengthOf(bC);
if(bD===0){return bz[bC]=null;
}var bA=this.rawData;
var bG=this.offset+bE.offsetOf(bC);
var bH=g(bA.slice(bG,bD));
var bF=bH.readShort_();
var bJ=bH.readShort_();
var bL=bH.readShort_();
var bI=bH.readShort_();
var bK=bH.readShort_();
var bB=bz[bC]=bF==-1?new bt(bH):new bv(bH);
bB.numberOfContours=bF;
bB.xMin=bJ;
bB.yMin=bL;
bB.xMax=bI;
bB.yMax=bK;
return bB;
},render:function(bA,bF,bE){var bG=g(),bD=[];
for(var bB=0;
bB<bF.length;
++bB){var bC=bF[bB];
var bz=bA[bC];
bD.push(bG.offset());
if(bz){bG.write(bz.render(bE));
}}bD.push(bG.offset());
return{table:bG.get(),offsets:bD};
}});
}();
var aA=function(){function bs(bu,bt){this.text=bu;
this.length=bu.length;
this.platformID=bt.platformID;
this.platformSpecificID=bt.platformSpecificID;
this.languageID=bt.languageID;
this.nameID=bt.nameID;
}return v({parse:function(bu){bu.offset(this.offset);
bu.readShort();
var bt=bu.readShort();
var by=this.offset+bu.readShort();
var bw=bu.times(bt,function(){return{platformID:bu.readShort(),platformSpecificID:bu.readShort(),languageID:bu.readShort(),nameID:bu.readShort(),length:bu.readShort(),offset:bu.readShort()+by};
});
var bz=this.strings={};
for(var bv=0;
bv<bw.length;
++bv){var bx=bw[bv];
bu.offset(bx.offset);
var bA=bu.readString(bx.length);
if(!bz[bx.nameID]){bz[bx.nameID]=[];
}bz[bx.nameID].push(new bs(bA,bx));
}this.postscriptEntry=bz[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(bx){var bC=this;
var bA=this.strings;
var bz=0;
for(var bt in bA){if(V(bA,bt)){bz+=bA[bt].length;
}}var bw=g();
var bB=g();
bw.writeShort(0);
bw.writeShort(bz);
bw.writeShort(6+12*bz);
for(bt in bA){if(V(bA,bt)){var bv=bt==6?[new bs(bx,bC.postscriptEntry)]:bA[bt];
for(var bu=0;
bu<bv.length;
++bu){var by=bv[bu];
bw.writeShort(by.platformID);
bw.writeShort(by.platformSpecificID);
bw.writeShort(by.languageID);
bw.writeShort(by.nameID);
bw.writeShort(by.length);
bw.writeShort(bB.offset());
bB.writeString(by.text);
}}}bw.write(bB.get());
return bw.get();
}});
}();
var a0=function(){var bs=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return v({parse:function(bt){var bw=this;
bt.offset(this.offset);
this.format=bt.readLong();
this.italicAngle=bt.readFixed_();
this.underlinePosition=bt.readShort_();
this.underlineThickness=bt.readShort_();
this.isFixedPitch=bt.readLong();
this.minMemType42=bt.readLong();
this.maxMemType42=bt.readLong();
this.minMemType1=bt.readLong();
this.maxMemType1=bt.readLong();
var bv;
switch(this.format){case 65536:case 196608:break;
case 131072:bv=bt.readShort();
this.glyphNameIndex=bt.times(bv,bt.readShort);
this.names=[];
var bu=this.offset+this.length;
while(bt.offset()<bu){bw.names.push(bt.readString(bt.readByte()));
}break;
case 151552:bv=bt.readShort();
this.offsets=bt.read(bv);
break;
case 262144:this.map=bt.times(this.file.maxp.numGlyphs,bt.readShort);
break;
}},glyphFor:function(bt){switch(this.format){case 65536:return bs[bt]||".notdef";
case 131072:var bu=this.glyphNameIndex[bt];
if(bu<bs.length){return bs[bu];
}return this.names[bu-bs.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[bt]||65535;
}},render:function(bx){var bB=this;
if(this.format==196608){return this.raw();
}var by=g(this.rawData.slice(this.offset,32));
by.writeLong(131072);
by.offset(32);
var bw=[];
var bA=[];
for(var bt=0;
bt<bx.length;
++bt){var bu=bx[bt];
var bz=bB.glyphFor(bu);
var bv=bs.indexOf(bz);
if(bv>=0){bw.push(bv);
}else{bw.push(bs.length+bA.length);
bA.push(bz);
}}by.writeShort(bx.length);
for(bt=0;
bt<bw.length;
++bt){by.writeShort(bw[bt]);
}for(bt=0;
bt<bA.length;
++bt){by.writeByte(bA[bt].length);
by.writeString(bA[bt]);
}return by.get();
}});
}();
var q=function(){function bs(bv,bw,bu){var bx=this;
bx.platformID=bv.readShort();
bx.platformSpecificID=bv.readShort();
bx.offset=bw+bv.readLong();
bv.saveExcursion(function(){var by;
bv.offset(bx.offset);
bx.format=bv.readShort();
switch(bx.format){case 0:bx.length=bv.readShort();
bx.language=bv.readShort();
for(var bG=0;
bG<256;
++bG){bu[bG]=bv.readByte();
}break;
case 4:bx.length=bv.readShort();
bx.language=bv.readShort();
var bM=bv.readShort()/2;
bv.skip(6);
var bC=bv.times(bM,bv.readShort);
bv.skip(2);
var bO=bv.times(bM,bv.readShort);
var bH=bv.times(bM,bv.readShort_);
var bI=bv.times(bM,bv.readShort);
var bz=(bx.length+bx.offset-bv.offset())/2;
var bF=bv.times(bz,bv.readShort);
for(bG=0;
bG<bM;
++bG){var bN=bO[bG],bA=bC[bG];
for(by=bN;
by<=bA;
++by){var bE;
if(bI[bG]===0){bE=by+bH[bG];
}else{var bJ=bI[bG]/2-(bM-bG)+(by-bN);
bE=bF[bJ]||0;
if(bE!==0){bE+=bH[bG];
}}bu[by]=bE&65535;
}}break;
case 6:bx.length=bv.readShort();
bx.language=bv.readShort();
by=bv.readShort();
var bK=bv.readShort();
while(bK-->0){bu[by++]=bv.readShort();
}break;
case 12:bv.readShort();
bx.length=bv.readLong();
bx.language=bv.readLong();
var bL=bv.readLong();
while(bL-->0){by=bv.readLong();
var bB=bv.readLong();
var bD=bv.readLong();
while(by<=bB){bu[by++]=bD++;
}}break;
default:if(window.console){window.console.error("Unhandled CMAP format: "+bx.format);
}}});
}function bt(bH,bJ){var bv=bb(bH);
var bR=[];
var bA=[];
var bG=null;
var by=null;
function bI(bT){return bJ[bH[bT]];
}for(var bE=0;
bE<bv.length;
++bE){var bu=bv[bE];
var bC=bI(bu);
var bw=bC-bu;
if(bG==null||bw!==by){if(bG){bA.push(bG);
}bR.push(bu);
by=bw;
}bG=bu;
}if(bG){bA.push(bG);
}bA.push(65535);
bR.push(65535);
var bO=bR.length;
var bP=bO*2;
var bN=2*Math.pow(2,Math.floor(Math.log(bO)/Math.LN2));
var bB=Math.log(bN/2)/Math.LN2;
var bM=bP-bN;
var bx=[];
var bL=[];
var bD=[];
for(bE=0;
bE<bO;
++bE){var bQ=bR[bE];
var bz=bA[bE];
if(bQ==65535){bx.push(0);
bL.push(0);
break;
}var bS=bI(bQ);
if(bQ-bS>=32768){bx.push(0);
bL.push(2*(bD.length+bO-bE));
for(var bF=bQ;
bF<=bz;
++bF){bD.push(bI(bF));
}}else{bx.push(bS-bQ);
bL.push(0);
}}var bK=g();
bK.writeShort(3);
bK.writeShort(1);
bK.writeLong(12);
bK.writeShort(4);
bK.writeShort(16+bO*8+bD.length*2);
bK.writeShort(0);
bK.writeShort(bP);
bK.writeShort(bN);
bK.writeShort(bB);
bK.writeShort(bM);
bA.forEach(bK.writeShort);
bK.writeShort(0);
bR.forEach(bK.writeShort);
bx.forEach(bK.writeShort_);
bL.forEach(bK.writeShort);
bD.forEach(bK.writeShort);
return bK.get();
}return v({parse:function(bu){var bw=this;
var bv=bw.offset;
bu.offset(bv);
bw.codeMap={};
bw.version=bu.readShort();
var bx=bu.readShort();
bw.tables=bu.times(bx,function(){return new bs(bu,bv,bw.codeMap);
});
},render:function(bu,bv){var bw=g();
bw.writeShort(0);
bw.writeShort(1);
bw.write(bt(bu,bv));
return bw.get();
}});
}();
var aE=v({parse:function(bs){bs.offset(this.offset);
this.version=bs.readShort();
this.averageCharWidth=bs.readShort_();
this.weightClass=bs.readShort();
this.widthClass=bs.readShort();
this.type=bs.readShort();
this.ySubscriptXSize=bs.readShort_();
this.ySubscriptYSize=bs.readShort_();
this.ySubscriptXOffset=bs.readShort_();
this.ySubscriptYOffset=bs.readShort_();
this.ySuperscriptXSize=bs.readShort_();
this.ySuperscriptYSize=bs.readShort_();
this.ySuperscriptXOffset=bs.readShort_();
this.ySuperscriptYOffset=bs.readShort_();
this.yStrikeoutSize=bs.readShort_();
this.yStrikeoutPosition=bs.readShort_();
this.familyClass=bs.readShort_();
this.panose=bs.times(10,bs.readByte);
this.charRange=bs.times(4,bs.readLong);
this.vendorID=bs.readString(4);
this.selection=bs.readShort();
this.firstCharIndex=bs.readShort();
this.lastCharIndex=bs.readShort();
if(this.version>0){this.ascent=bs.readShort_();
this.descent=bs.readShort_();
this.lineGap=bs.readShort_();
this.winAscent=bs.readShort();
this.winDescent=bs.readShort();
this.codePageRange=bs.times(2,bs.readLong);
if(this.version>1){this.xHeight=bs.readShort();
this.capHeight=bs.readShort();
this.defaultChar=bs.readShort();
this.breakChar=bs.readShort();
this.maxContext=bs.readShort();
}}},render:function(){return this.raw();
}});
var bd=100000;
function aB(){var bu="",bt=String(bd);
for(var bs=0;
bs<bt.length;
++bs){bu+=String.fromCharCode(bt.charCodeAt(bs)-48+65);
}++bd;
return bu;
}function bc(bs){this.font=bs;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=aB()+"+"+this.font.psName;
}bc.prototype={use:function(bs){var bw=this;
if(typeof bs=="string"){return bl(bs).reduce(function(by,bx){return by+String.fromCharCode(bw.use(bx));
},"");
}var bt=bw.unicodes[bs];
if(!bt){bt=bw.next++;
bw.subset[bt]=bs;
bw.unicodes[bs]=bt;
var bv=bw.font.cmap.codeMap[bs];
if(bv){bw.ncid2ogid[bt]=bv;
if(bw.ogid2ngid[bv]==null){var bu=bw.nextGid++;
bw.ogid2ngid[bv]=bu;
bw.ngid2ogid[bu]=bv;
}}}return bt;
},encodeText:function(bs){return this.use(bs);
},glyphIds:function(){return bb(this.ogid2ngid);
},glyphsFor:function(bt,bw){var bx=this;
if(!bw){bw={};
}for(var bu=0;
bu<bt.length;
++bu){var bv=bt[bu];
if(!bw[bv]){var bs=bw[bv]=bx.font.glyf.glyphFor(bv);
if(bs&&bs.compound){bx.glyphsFor(bs.glyphIds,bw);
}}}return bw;
},render:function(){var bB=this;
var bu=this.glyphsFor(this.glyphIds());
for(var by in bu){if(V(bu,by)){by=parseInt(by,10);
if(bB.ogid2ngid[by]==null){var bw=bB.nextGid++;
bB.ogid2ngid[by]=bw;
bB.ngid2ogid[bw]=by;
}}}var bx=bb(this.ngid2ogid);
var bz=bx.map(function(bC){return this.ngid2ogid[bC];
},this);
var bs=this.font;
var bt=bs.glyf.render(bu,bz,this.ogid2ngid);
var bv=bs.loca.render(bt.offsets);
this.lastChar=this.next-1;
var bA={cmap:q.render(this.ncid2ogid,this.ogid2ngid),glyf:bt.table,loca:bv.table,hmtx:bs.hmtx.render(bz),hhea:bs.hhea.render(bz),maxp:bs.maxp.render(bz),post:bs.post.render(bz),name:bs.name.render(this.psName),head:bs.head.render(bv.format),"OS/2":bs.os2.render()};
return this.font.directory.render(bA);
},cidToGidMap:function(){var bx=this;
var bw=g(),bt=0;
for(var bs=this.firstChar;
bs<this.next;
++bs){while(bt<bs){bw.writeShort(0);
bt++;
}var bv=bx.ncid2ogid[bs];
if(bv){var bu=bx.ogid2ngid[bv];
bw.writeShort(bu);
}else{bw.writeShort(0);
}bt++;
}return bw.get();
}};
function bk(by,bu){var bz=this;
var bs=bz.contents=g(by);
if(bs.readString(4)=="ttcf"){var bw;
var bx=function(){bs.offset(bw);
bz.parse();
};
if(!bu){throw new Error("Must specify a name for TTC files");
}bs.readLong();
var bv=bs.readLong();
for(var bt=0;
bt<bv;
++bt){bw=bs.readLong();
bs.saveExcursion(bx);
if(bz.psName==bu){return;
}}throw new Error("Font "+bu+" not found in collection");
}else{bs.offset(0);
bz.parse();
}}bk.prototype={parse:function(){var bs=this.directory=new w(this.contents);
this.head=bs.readTable("head",W);
this.loca=bs.readTable("loca",ao);
this.hhea=bs.readTable("hhea",X);
this.maxp=bs.readTable("maxp",au);
this.hmtx=bs.readTable("hmtx",Y);
this.glyf=bs.readTable("glyf",S);
this.name=bs.readTable("name",aA);
this.post=bs.readTable("post",a0);
this.cmap=bs.readTable("cmap",q);
this.os2=bs.readTable("OS/2",aE);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(bs){return this.hmtx.forGlyph(bs).advance*this.scale;
},makeSubset:function(){return new bc(this);
}};
var P=String.fromCharCode;
var h="ЧЪ";
function I(bs){return P(bs>>8)+P(bs&255);
}function J(bu){var bw="";
for(var bt=0;
bt<bu.length;
bt++){var bs=bu.charCodeAt(bt);
if(bs<65535){bw+=I(bs);
}else{var bv=(bs-65536>>10)+55296;
var bx=(bs-65536&1023)+56320;
bw+=I(bv);
bw+=I(bx);
}}return bw;
}var i=ae.support.browser;
var aC="\n";
var a4=0;
var aG={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function ar(){var bs=0,bu=g();
function bt(){var bv=arguments;
for(var bw=0;
bw<arguments.length;
++bw){var by=bv[bw];
if(by===undefined){throw new Error("Cannot output undefined to PDF");
}else{if(by instanceof aZ){by.beforeRender(bt);
by.render(bt);
}else{if(ab(by)){a2(by,bt);
}else{if(ac(by)){a3(by,bt);
}else{if(typeof by=="number"){if(isNaN(by)){throw new Error("Cannot output NaN to PDF");
}var bx=by.toFixed(7);
if(bx.indexOf(".")>=0){bx=bx.replace(/\.?0+$/,"");
}if(bx=="-0"){bx="0";
}bu.writeString(bx);
}else{if(/string|boolean/.test(typeof by)){bu.writeString(String(by));
}else{if(typeof by.get=="function"){bu.write(by.get());
}else{if(typeof by=="object"){if(!by){bu.writeString("null");
}else{bt(new aK(by));
}}}}}}}}}}}bt.writeData=function(bv){bu.write(bv);
};
bt.withIndent=function(bv){++bs;
bv(bt);
--bs;
};
bt.indent=function(){bt(aC,aF("",bs*2,"  "));
bt.apply(null,arguments);
};
bt.offset=function(){return bu.offset();
};
bt.toString=function(){throw new Error("FIX CALLER");
};
bt.get=function(){return bu.get();
};
bt.stream=function(){return bu;
};
return bt;
}function bq(bv,bt){var bs=bv.beforeRender;
var bu=bv.render;
bv.beforeRender=function(){};
bv.render=function(bw){bw(bt," 0 R");
};
bv.renderFull=function(bw){bv._offset=bw.offset();
bw(bt," 0 obj ");
bs.call(bv,bw);
bu.call(bv,bw);
bw(" endobj");
};
}function R(bs){if(typeof bs!="function"){var bu=bs;
bs=function(bx,bw){return bx in bu?bu[bx]:bw;
};
}var bv=bs("paperSize",aG.a4);
if(!bv){return{};
}if(typeof bv=="string"){bv=aG[bv.toLowerCase()];
if(bv==null){throw new Error("Unknown paper size");
}}bv[0]=bn(bv[0]);
bv[1]=bn(bv[1]);
if(bs("landscape",false)){bv=[Math.max(bv[0],bv[1]),Math.min(bv[0],bv[1])];
}var bt=bs("margin");
if(bt){if(typeof bt=="string"||typeof bt=="number"){bt=bn(bt,0);
bt={left:bt,top:bt,right:bt,bottom:bt};
}else{bt={left:bn(bt.left,0),top:bn(bt.top,0),right:bn(bt.right,0),bottom:bn(bt.bottom,0)};
}if(bs("addMargin")){bv[0]+=bt.left+bt.right;
bv[1]+=bt.top+bt.bottom;
}}return{paperSize:bv,margin:bt};
}function aL(by){var bB=this;
var bz=ar();
var bw=0;
var bx=[];
function bt(bD,bC){return by&&by[bD]!=null?by[bD]:bC;
}bB.getOption=bt;
bB.attach=function(bC){if(bx.indexOf(bC)<0){bq(bC,++bw);
bx.push(bC);
}return bC;
};
bB.pages=[];
bB.FONTS={};
bB.IMAGES={};
bB.GRAD_COL_FUNCTIONS={};
bB.GRAD_OPC_FUNCTIONS={};
bB.GRAD_COL={};
bB.GRAD_OPC={};
var bs=bB.attach(new aJ());
var bA=bB.attach(new aS());
if(bt("autoPrint")){var bv={};
bv.JavaScript=new aK({Names:[new aW("JS"),bB.attach(new aK({S:b("JavaScript"),JS:new aW("print(true);")}))]});
bs.props.Names=new aK(bv);
}bs.setPages(bA);
var bu=bB.attach(new aK({Producer:new aW(bt("producer","Kendo UI PDF Generator"),true),Title:new aW(bt("title",""),true),Author:new aW(bt("author",""),true),Subject:new aW(bt("subject",""),true),Keywords:new aW(bt("keywords",""),true),Creator:new aW(bt("creator","Kendo UI PDF Generator"),true),CreationDate:bt("date",new Date())}));
bB.addPage=function(bG){var bI=R(function(bM,bL){return bG&&bG[bM]!=null?bG[bM]:bL;
});
var bJ=bI.paperSize;
var bF=bI.margin;
var bE=bJ[0];
var bD=bJ[1];
if(bF){bE-=bF.left+bF.right;
bD-=bF.top+bF.bottom;
}var bC=new aV(ar(),null,true);
var bK={Contents:bB.attach(bC),Parent:bA,MediaBox:[0,0,bJ[0],bJ[1]]};
var bH=new aR(bB,bK);
bH._content=bC;
bA.addPage(bB.attach(bH));
bH.transform(1,0,0,-1,0,bJ[1]);
if(bF){bH.translate(bF.left,bF.top);
bH.rect(0,0,bE,bD);
bH.clip();
}bB.pages.push(bH);
return bH;
};
bB.render=function(){var bC;
bz("%PDF-1.4",aC,"%базон",aC,aC);
for(bC=0;
bC<bx.length;
++bC){bx[bC].renderFull(bz);
bz(aC,aC);
}var bD=bz.offset();
bz("xref",aC,0," ",bx.length+1,aC);
bz("0000000000 65535 f ",aC);
for(bC=0;
bC<bx.length;
++bC){bz(br(bx[bC]._offset,10)," 00000 n ",aC);
}bz(aC);
bz("trailer",aC);
bz(new aK({Size:bx.length+1,Root:bs,Info:bu}),aC,aC);
bz("startxref",aC,bD,aC);
bz("%%EOF",aC);
return bz.stream().offset(0);
};
}var M={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function aj(bw,bs){var bu;
if(i.msie&&(bu=/^data:.*?;base64,/i.exec(bw))){bs(f(bw.substr(bu[0].length)));
return;
}function bt(){if(window.console){if(window.console.error){window.console.error("Cannot load URL: %s",bw);
}else{window.console.log("Cannot load URL: %s",bw);
}}bs(null);
}var bv=new XMLHttpRequest();
bv.open("GET",bw,true);
if(T){bv.responseType="arraybuffer";
}bv.onload=function(){if(bv.status==200||bv.status==304){if(T){bs(new Uint8Array(bv.response));
}else{bs(new window.VBArray(bv.responseBody).toArray());
}}else{bt();
}};
bv.onerror=bt;
bv.send(null);
}function ak(bu,bs){var bt=M[bu];
if(bt){bs(bt);
}else{aj(bu,function(bv){if(bv==null){throw new Error("Cannot load font from "+bu);
}else{var bw=new bk(bv);
M[bu]=bw;
bs(bw);
}});
}}var Z={};
function o(){Z={};
}function am(bC,bB,by,bA){var bz=Z[bC],bx,bw;
if(bz){by(bz);
}else{bz=new Image();
if(!/^data:/i.test(bC)){bz.crossOrigin="Anonymous";
}if(T&&!/^data:/i.test(bC)){var bD=new XMLHttpRequest();
bD.onload=function(){bw=bD.response;
bx=URL.createObjectURL(bw);
bs(bx);
};
bD.onerror=bt;
bD.open("GET",bC,true);
bD.responseType="blob";
bD.send();
}else{bs(bC);
}}function bs(bE){bz.src=bE;
if(bz.complete&&!i.msie){bu();
}else{bz.onload=bu;
bz.onerror=bt;
}}function bv(){if(!bB){bB={width:bz.width,height:bz.height};
}var bG=document.createElement("canvas");
bG.width=bB.width;
bG.height=bB.height;
var bH=bG.getContext("2d");
bH.drawImage(bz,0,0,bB.width,bB.height);
var bM;
try{bM=bH.getImageData(0,0,bB.width,bB.height);
}catch(bJ){bt();
return;
}finally{if(bx){URL.revokeObjectURL(bx);
}}var bK=false,bO=g(),bF=g();
var bN=bM.data;
var bL=0;
while(bL<bN.length){bO.writeByte(bN[bL++]);
bO.writeByte(bN[bL++]);
bO.writeByte(bN[bL++]);
var bE=bN[bL++];
if(bE<255){bK=true;
}bF.writeByte(bE);
}if(bK||bA.keepPNG){bz=new aT(bB.width,bB.height,bO,bF);
}else{var bI=bG.toDataURL("image/jpeg",bA.jpegQuality);
bI=bI.substr(bI.indexOf(";base64,")+8);
var bP=g();
bP.writeBase64(bI);
bz=new aO(bP);
}by(Z[bC]=bz);
}function bt(){by(Z[bC]="ERROR");
}function bu(){if(bB){if(bB.width>=bz.width||bB.height>=bz.height){bB=null;
}}if(!bB&&bw&&/^image\/jpe?g$/i.test(bw.type)){var bE=new FileReader();
bE.onload=function(){try{var bG=new aO(g(new Uint8Array(this.result)));
URL.revokeObjectURL(bx);
by(Z[bC]=bG);
}catch(bF){bv();
}};
bE.readAsArrayBuffer(bw);
}else{bv();
}}}function at(bs){return function(bx,bt){var bv=bx.length,bu=bv;
if(bv===0){return bt();
}function bw(){if(--bv===0){bt();
}}while(bu-->0){bs(bx[bu],bw);
}};
}var al=at(ak);
var an=function(bt,bs,bw){bw=a.extend({jpegQuality:0.92,keepPNG:false},bw);
var bx=Object.keys(bt),bu=bx.length;
if(bu===0){return bs();
}function bv(){if(--bu===0){bs();
}}bx.forEach(function(by){am(by,bt[by],bv,bw);
});
};
aL.prototype={loadFonts:al,loadImages:an,getFont:function(bt){var bs=this.FONTS[bt];
if(!bs){bs=M[bt];
if(!bs){throw new Error("Font "+bt+" has not been loaded");
}if(bs===true){bs=this.attach(new aU(bt));
}else{bs=this.attach(new aM(this,bs));
}this.FONTS[bt]=bs;
}return bs;
},getImage:function(bt){var bs=this.IMAGES[bt];
if(!bs){bs=Z[bt];
if(!bs){throw new Error("Image "+bt+" has not been loaded");
}if(bs==="ERROR"){return null;
}bs=this.IMAGES[bt]=this.attach(bs.asStream(this));
}return bs;
},getOpacityGS:function(bw,bt){var bv=parseFloat(bw).toFixed(3);
bw=parseFloat(bv);
bv+=bt?"S":"F";
var bs=this._opacityGSCache||(this._opacityGSCache={});
var bu=bs[bv];
if(!bu){var bx={Type:b("ExtGState")};
if(bt){bx.CA=bw;
}else{bx.ca=bw;
}bu=this.attach(new aK(bx));
bu._resourceName=b("GS"+ ++a4);
bs[bv]=bu;
}return bu;
},dict:function(bs){return new aK(bs);
},name:function(bs){return b(bs);
},stream:function(bt,bs){return new aV(bs,bt);
}};
function aF(bu,bt,bs){while(bu.length<bt){bu=bs+bu;
}return bu;
}function br(bt,bs){return aF(String(bt),bs,"0");
}function U(bt,bs){return Object.prototype.hasOwnProperty.call(bt,bs);
}var ab=Array.isArray||function(bs){return bs instanceof Array;
};
function ac(bs){return bs instanceof Date;
}function a2(bs,bt){bt("[");
if(bs.length>0){bt.withIndent(function(){for(var bu=0;
bu<bs.length;
++bu){if(bu>0&&bu%8===0){bt.indent(bs[bu]);
}else{bt(" ",bs[bu]);
}}});
}bt(" ]");
}function a3(bs,bt){bt("(D:",br(bs.getUTCFullYear(),4),br(bs.getUTCMonth()+1,2),br(bs.getUTCDate(),2),br(bs.getUTCHours(),2),br(bs.getUTCMinutes(),2),br(bs.getUTCSeconds(),2),"Z)");
}function ay(bs){return bs*(72/25.4);
}function p(bs){return ay(bs*10);
}function aa(bs){return bs*72;
}function bn(bv,bs){if(typeof bv=="number"){return bv;
}if(typeof bv=="string"){var bt;
bt=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(bv);
if(bt){var bu=parseFloat(bt[1]);
if(!isNaN(bu)){if(bt[2]=="pt"){return bu;
}return{mm:ay,cm:p,"in":aa}[bt[2]](bu);
}}}if(bs!=null){return bs;
}throw new Error("Can't parse unit: "+bv);
}function aZ(){}aZ.prototype.beforeRender=function(){};
function t(bt,bv,bs){if(!bs){bs=aZ;
}bt.prototype=new bs();
for(var bu in bv){if(U(bv,bu)){bt.prototype[bu]=bv[bu];
}}return bt;
}var aW=t(function aW(bt,bs){this.value=bt;
this.utf16be=Boolean(bs);
},{render:function(bv){var bw=this.value;
if(this.utf16be){bw=h+J(bw);
bw=bw.replace(/([\(\)\\])/g,"\\$1");
bv("(",bw,")");
}else{var bt=[40];
for(var bu=0;
bu<bw.length;
++bu){var bs=bw.charCodeAt(bu)&255;
if(bs==40||bs==41||bs==92){bt.push(92);
}bt.push(bs);
}bt.push(41);
bv.writeData(bt);
}},toString:function(){return this.value;
}});
var aN=t(function aN(bs){this.value=bs;
},{render:function(bt){var bu=this;
bt("<");
for(var bs=0;
bs<this.value.length;
++bs){bt(br(bu.value.charCodeAt(bs).toString(16),4));
}bt(">");
}},aW);
var aP=t(function aP(bs){this.name=bs;
},{render:function(bs){bs("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(bs){return"#"+br(bs.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var aQ={};
aP.get=b;
function b(bs){if(U(aQ,bs)){return aQ[bs];
}return aQ[bs]=new aP(bs);
}var aK=t(function aK(bs){this.props=bs;
},{render:function(bt){var bu=this.props,bs=true;
bt("<<");
bt.withIndent(function(){for(var bv in bu){if(U(bu,bv)&&!/^_/.test(bv)){bs=false;
bt.indent(b(bv)," ",bu[bv]);
}}});
if(!bs){bt.indent();
}bt(">>");
}});
var aV=t(function aV(bt,bu,bs){if(typeof bt=="string"){var bv=g();
bv.write(bt);
bt=bv;
}this.data=bt;
this.props=bu||{};
this.compress=bs;
},{render:function(bt){var bs=this.data.get(),bu=this.props;
if(this.compress&&ag.supportsDeflate()){if(!bu.Filter){bu.Filter=[];
}else{if(!(bu.Filter instanceof Array)){bu.Filter=[bu.Filter];
}}bu.Filter.unshift(b("FlateDecode"));
bs=ag.deflate(bs);
}bu.Length=bs.length;
bt(new aK(bu)," stream",aC);
bt.writeData(bs);
bt(aC,"endstream");
}});
var aJ=t(function aJ(){this.props={Type:b("Catalog")};
},{setPages:function(bs){this.props.Pages=bs;
}},aK);
var aS=t(function aS(){this.props={Type:b("Pages"),Kids:[],Count:0};
},{addPage:function(bs){this.props.Kids.push(bs);
this.props.Count++;
}},aK);
var ba=[192,193,194,195,197,198,199,201,202,203,205,206,207];
function aO(bu){bu.offset(0);
var bB,bw,bt,bs;
var bA=bu.readShort();
if(bA!=65496){throw new Error("Invalid JPEG image");
}while(!bu.eof()){var bv=bu.readByte();
if(bv!=255){throw new Error("Invalid JPEG image");
}var by=bu.readByte();
var bx=bu.readShort();
if(ba.indexOf(by)>=0){bs=bu.readByte();
bw=bu.readShort();
bB=bu.readShort();
bt=bu.readByte();
break;
}bu.skip(bx-2);
}if(bt==null){throw new Error("Invalid JPEG image");
}var bz={Type:b("XObject"),Subtype:b("Image"),Width:bB,Height:bw,BitsPerComponent:bs,Filter:b("DCTDecode")};
switch(bt){case 1:bz.ColorSpace=b("DeviceGray");
break;
case 3:bz.ColorSpace=b("DeviceRGB");
break;
case 4:bz.ColorSpace=b("DeviceCMYK");
bz.Decode=[1,0,1,0,1,0,1,0];
break;
}this.asStream=function(){bu.offset(0);
var bC=new aV(bu,bz);
bC._resourceName=b("I"+ ++a4);
return bC;
};
}function aT(bv,bt,bu,bs){this.asStream=function(bx){var bw=new aV(bs,{Type:b("XObject"),Subtype:b("Image"),Width:bv,Height:bt,BitsPerComponent:8,ColorSpace:b("DeviceGray")},true);
var by=new aV(bu,{Type:b("XObject"),Subtype:b("Image"),Width:bv,Height:bt,BitsPerComponent:8,ColorSpace:b("DeviceRGB"),SMask:bx.attach(bw)},true);
by._resourceName=b("I"+ ++a4);
return by;
};
}var aU=t(function aU(bs){this.props={Type:b("Font"),Subtype:b("Type1"),BaseFont:b(bs)};
this._resourceName=b("F"+ ++a4);
},{encodeText:function(bs){return new aW(String(bs));
}},aK);
var aM=t(function aM(bu,bs,bv){bv=this.props=bv||{};
bv.Type=b("Font");
bv.Subtype=b("Type0");
bv.Encoding=b("Identity-H");
this._pdf=bu;
this._font=bs;
this._sub=bs.makeSubset();
this._resourceName=b("F"+ ++a4);
var bt=bs.head;
this.name=bs.psName;
var bw=this.scale=bs.scale;
this.bbox=[bt.xMin*bw,bt.yMin*bw,bt.xMax*bw,bt.yMax*bw];
this.italicAngle=bs.post.italicAngle;
this.ascent=bs.ascent*bw;
this.descent=bs.descent*bw;
this.lineGap=bs.lineGap*bw;
this.capHeight=bs.os2.capHeight||this.ascent;
this.xHeight=bs.os2.xHeight||0;
this.stemV=0;
this.familyClass=(bs.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=(bs.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|1<<5;
},{encodeText:function(bs){return new aN(this._sub.encodeText(String(bs)));
},getTextWidth:function(bt,bw){var bx=this;
var by=0,bs=this._font.cmap.codeMap;
for(var bv=0;
bv<bw.length;
++bv){var bu=bs[bw.charCodeAt(bv)];
by+=bx._font.widthOfGlyph(bu||0);
}return by*bt/1000;
},beforeRender:function(){var bC=this;
var bD=bC._sub;
var bu=bD.render();
var bz=new aV(g(bu),{Length1:bu.length},true);
var bw=bC._pdf.attach(new aK({Type:b("FontDescriptor"),FontName:b(bC._sub.psName),FontBBox:bC.bbox,Flags:bC.flags,StemV:bC.stemV,ItalicAngle:bC.italicAngle,Ascent:bC.ascent,Descent:bC.descent,CapHeight:bC.capHeight,XHeight:bC.xHeight,FontFile2:bC._pdf.attach(bz)}));
var bt=bD.ncid2ogid;
var by=bD.firstChar;
var bA=bD.lastChar;
var bs=[];
(function bB(bI,bG){if(bI<=bA){var bH=bt[bI];
if(bH==null){bB(bI+1);
}else{if(!bG){bs.push(bI,bG=[]);
}bG.push(bC._font.widthOfGlyph(bH));
bB(bI+1,bG);
}}}(by));
var bv=new aK({Type:b("Font"),Subtype:b("CIDFontType2"),BaseFont:b(bC._sub.psName),CIDSystemInfo:new aK({Registry:new aW("Adobe"),Ordering:new aW("Identity"),Supplement:0}),FontDescriptor:bw,FirstChar:by,LastChar:bA,DW:Math.round(bC._font.widthOfGlyph(0)),W:bs,CIDToGIDMap:bC._pdf.attach(bC._makeCidToGidMap())});
var bx=bC.props;
bx.BaseFont=b(bC._sub.psName);
bx.DescendantFonts=[bC._pdf.attach(bv)];
var bE=new aX(by,bA,bD.subset);
var bF=new aV(ar(),null,true);
bF.data(bE);
bx.ToUnicode=bC._pdf.attach(bF);
},_makeCidToGidMap:function(){return new aV(g(this._sub.cidToGidMap()),null,true);
}},aK);
var aX=t(function aY(bs,bt,bu){this.firstChar=bs;
this.lastChar=bt;
this.map=bu;
},{render:function(bs){bs.indent("/CIDInit /ProcSet findresource begin");
bs.indent("12 dict begin");
bs.indent("begincmap");
bs.indent("/CIDSystemInfo <<");
bs.indent("  /Registry (Adobe)");
bs.indent("  /Ordering (UCS)");
bs.indent("  /Supplement 0");
bs.indent(">> def");
bs.indent("/CMapName /Adobe-Identity-UCS def");
bs.indent("/CMapType 2 def");
bs.indent("1 begincodespacerange");
bs.indent("  <0000><ffff>");
bs.indent("endcodespacerange");
var bt=this;
bs.indent(bt.lastChar-bt.firstChar+1," beginbfchar");
bs.withIndent(function(){for(var bu=bt.firstChar;
bu<=bt.lastChar;
++bu){var bx=bt.map[bu];
var bw=bm([bx]);
bs.indent("<",br(bu.toString(16),4),">","<");
for(var bv=0;
bv<bw.length;
++bv){bs(br(bw.charCodeAt(bv).toString(16),4));
}bs(">");
}});
bs.indent("endbfchar");
bs.indent("endcmap");
bs.indent("CMapName currentdict /CMap defineresource pop");
bs.indent("end");
bs.indent("end");
}});
function aq(bs){return bs.map(function(bt){return ab(bt)?aq(bt):typeof bt=="number"?(Math.round(bt*1000)/1000).toFixed(3):bt;
}).join(" ");
}function k(by,bz,bv,bs,bA,bw,bt){var bx=aq([bz,bv,bs,bA,bw,bt]);
var bu=by.GRAD_COL_FUNCTIONS[bx];
if(!bu){bu=by.GRAD_COL_FUNCTIONS[bx]=by.attach(new aK({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[bz,bv,bs],C1:[bA,bw,bt]}));
}return bu;
}function n(bw,bs,bt){var bv=aq([bs,bt]);
var bu=bw.GRAD_OPC_FUNCTIONS[bv];
if(!bu){bu=bw.GRAD_OPC_FUNCTIONS[bv]=bw.attach(new aK({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[bs],C1:[bt]}));
}return bu;
}function ap(bB,bE){var bx=false;
var bA=[];
var bt=[];
var bz=[];
var bw=[];
var by,bC,bu,bD,bv;
for(by=1;
by<bE.length;
++by){bC=bE[by-1];
bu=bE[by];
bD=bC.color;
bv=bu.color;
bt.push(k(bB,bD.r,bD.g,bD.b,bv.r,bv.g,bv.b));
if(bD.a<1||bv.a<1){bx=true;
}bz.push(bu.offset);
bw.push(0,1);
}if(bx){for(by=1;
by<bE.length;
++by){bC=bE[by-1];
bu=bE[by];
bD=bC.color;
bv=bu.color;
bA.push(n(bB,bD.a,bv.a));
}}bz.pop();
return{hasAlpha:bx,colors:bs(bt),opacities:bx?bs(bA):null};
function bs(bF){if(bF.length==1){return bF[0];
}return{FunctionType:3,Functions:bF,Domain:[0,1],Bounds:bz,Encode:bw};
}}function j(by,bx,bA,bu,bv,bt){var bz,bw;
if(!bt){var bs=[bx].concat(bu);
bA.forEach(function(bB){bs.push(bB.offset,bB.color.r,bB.color.g,bB.color.b);
});
bw=aq(bs);
bz=by.GRAD_COL[bw];
}if(!bz){bz=new aK({Type:b("Shading"),ShadingType:bx?3:2,ColorSpace:b("DeviceRGB"),Coords:bu,Domain:[0,1],Function:bv,Extend:[true,true]});
by.attach(bz);
bz._resourceName="S"+ ++a4;
if(bw){by.GRAD_COL[bw]=bz;
}}return bz;
}function m(bz,bx,bA,bu,bv,bt){var by,bw;
if(!bt){var bs=[bx].concat(bu);
bA.forEach(function(bB){bs.push(bB.offset,bB.color.a);
});
bw=aq(bs);
by=bz.GRAD_OPC[bw];
}if(!by){by=new aK({Type:b("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:b("Mask"),S:b("Luminosity"),G:bz.attach(new aV("/a0 gs /s0 sh",{Type:b("XObject"),Subtype:b("Form"),FormType:1,BBox:bt?[bt.left,bt.top+bt.height,bt.left+bt.width,bt.top]:[0,1,1,0],Group:{Type:b("Group"),S:b("Transparency"),CS:b("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:b("DeviceGray"),Coords:bu,Domain:[0,1],ShadingType:bx?3:2,Function:bv,Extend:[true,true]}}}}))}});
bz.attach(by);
by._resourceName="O"+ ++a4;
if(bw){bz.GRAD_OPC[bw]=by;
}}return by;
}function l(by,bv,bs){var bw=bv.type=="radial";
var bu=ap(by,bv.stops);
var bt=bw?[bv.start.x,bv.start.y,bv.start.r,bv.end.x,bv.end.y,bv.end.r]:[bv.start.x,bv.start.y,bv.end.x,bv.end.y];
var bz=j(by,bw,bv.stops,bt,bu.colors,bv.userSpace&&bs);
var bx=bu.hasAlpha?m(by,bw,bv.stops,bt,bu.opacities,bv.userSpace&&bs):null;
return{hasAlpha:bu.hasAlpha,shading:bz,opacity:bx};
}var aR=t(function aR(bs,bt){this._pdf=bs;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
bt=this.props=bt||{};
bt.Type=b("Page");
bt.ProcSet=[b("PDF"),b("Text"),b("ImageB"),b("ImageC"),b("ImageI")];
bt.Resources=new aK({Font:new aK(this._fontResources),ExtGState:new aK(this._gsResources),XObject:new aK(this._xResources),Pattern:new aK(this._patResources),Shading:new aK(this._shResources)});
bt.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(bs,bt,bu,bv,bw,bx){if(!ad(arguments)){this._matrix=az(arguments,this._matrix);
this._out(bs," ",bt," ",bu," ",bv," ",bw," ",bx," cm");
this._out(aC);
}},translate:function(bs,bt){this.transform(1,0,0,1,bs,bt);
},scale:function(bs,bt){this.transform(bs,0,0,bt,0,0);
},rotate:function(bs){var bt=Math.cos(bs),bu=Math.sin(bs);
this.transform(bt,bu,-bu,bt,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",aC);
},endText:function(){this._textMode=false;
this._out("ET",aC);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(bs,bt){this._requireTextMode();
if(bs==null){bs=this._font;
}else{if(!(bs instanceof aM)){bs=this._pdf.getFont(bs);
}}if(bt==null){bt=this._fontSize;
}this._fontResources[bs._resourceName]=bs;
this._font=bs;
this._fontSize=bt;
this._out(bs._resourceName," ",bt," Tf",aC);
},setTextLeading:function(bs){this._requireTextMode();
this._out(bs," TL",aC);
},setTextRenderingMode:function(bs){this._requireTextMode();
this._out(bs," Tr",aC);
},showText:function(bv,bt){this._requireFont();
if(bv.length>1&&bt&&this._font instanceof aM){var bs=this._font.getTextWidth(this._fontSize,bv);
var bu=bt/bs*100;
this._out(bu," Tz ");
}this._out(this._font.encodeText(bv)," Tj",aC);
},showTextNL:function(bs){this._requireFont();
this._out(this._font.encodeText(bs)," '",aC);
},addLink:function(bv,bs){var bt=this._toPage({x:bs.left,y:bs.bottom});
var bu=this._toPage({x:bs.right,y:bs.top});
this._annotations.push(new aK({Type:b("Annot"),Subtype:b("Link"),Rect:[bt.x,bt.y,bu.x,bu.y],Border:[0,0,0],A:new aK({Type:b("Action"),S:b("URI"),URI:new aW(bv)})}));
},setStrokeColor:function(bu,bt,bs){this._out(bu," ",bt," ",bs," RG",aC);
},setOpacity:function(bs){this.setFillOpacity(bs);
this.setStrokeOpacity(bs);
this._opacity*=bs;
},setStrokeOpacity:function(bt){if(bt<1){var bs=this._pdf.getOpacityGS(this._opacity*bt,true);
this._gsResources[bs._resourceName]=bs;
this._out(bs._resourceName," gs",aC);
}},setFillColor:function(bu,bt,bs){this._out(bu," ",bt," ",bs," rg",aC);
},setFillOpacity:function(bt){if(bt<1){var bs=this._pdf.getOpacityGS(this._opacity*bt,false);
this._gsResources[bs._resourceName]=bs;
this._out(bs._resourceName," gs",aC);
}},gradient:function(bu,bs){this.save();
this.rect(bs.left,bs.top,bs.width,bs.height);
this.clip();
if(!bu.userSpace){this.transform(bs.width,0,0,bs.height,bs.left,bs.top);
}var bt=l(this._pdf,bu,bs);
var bw=bt.shading._resourceName,bv;
this._shResources[bw]=bt.shading;
if(bt.hasAlpha){bv=bt.opacity._resourceName;
this._gsResources[bv]=bt.opacity;
this._out("/"+bv+" gs ");
}this._out("/"+bw+" sh",aC);
this.restore();
},setDashPattern:function(bs,bt){this._out(bs," ",bt," d",aC);
},setLineWidth:function(bs){this._out(bs," w",aC);
},setLineCap:function(bs){this._out(bs," J",aC);
},setLineJoin:function(bs){this._out(bs," j",aC);
},setMitterLimit:function(bs){this._out(bs," M",aC);
},save:function(){this._contextStack.push(this._context());
this._out("q",aC);
},restore:function(){this._out("Q",aC);
this._context(this._contextStack.pop());
},moveTo:function(bs,bt){this._out(bs," ",bt," m",aC);
},lineTo:function(bs,bt){this._out(bs," ",bt," l",aC);
},bezier:function(bs,bv,bt,bw,bu,bx){this._out(bs," ",bv," ",bt," ",bw," ",bu," ",bx," c",aC);
},bezier1:function(bs,bu,bt,bv){this._out(bs," ",bu," ",bt," ",bv," y",aC);
},bezier2:function(bs,bu,bt,bv){this._out(bs," ",bu," ",bt," ",bv," v",aC);
},close:function(){this._out("h",aC);
},rect:function(bu,bv,bt,bs){this._out(bu," ",bv," ",bt," ",bs," re",aC);
},ellipse:function(bx,by,bv,bw){function bs(bz){return bx+bz;
}function bt(bz){return by+bz;
}var bu=0.5522847498307936;
this.moveTo(bs(0),bt(bw));
this.bezier(bs(bv*bu),bt(bw),bs(bv),bt(bw*bu),bs(bv),bt(0));
this.bezier(bs(bv),bt(-bw*bu),bs(bv*bu),bt(-bw),bs(0),bt(-bw));
this.bezier(bs(-bv*bu),bt(-bw),bs(-bv),bt(-bw*bu),bs(-bv),bt(0));
this.bezier(bs(-bv),bt(bw*bu),bs(-bv*bu),bt(bw),bs(0),bt(bw));
},circle:function(bt,bu,bs){this.ellipse(bt,bu,bs,bs);
},stroke:function(){this._out("S",aC);
},nop:function(){this._out("n",aC);
},clip:function(){this._out("W n",aC);
},clipStroke:function(){this._out("W S",aC);
},closeStroke:function(){this._out("s",aC);
},fill:function(){this._out("f",aC);
},fillStroke:function(){this._out("B",aC);
},drawImage:function(bt){var bs=this._pdf.getImage(bt);
if(bs){this._xResources[bs._resourceName]=bs;
this._out(bs._resourceName," Do",aC);
}},comment:function(bt){var bs=this;
bt.split(/\r?\n/g).forEach(function(bu){bs._out("% ",bu,aC);
});
},_context:function(bs){if(bs!=null){this._opacity=bs.opacity;
this._matrix=bs.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(bz){var by=this._matrix;
var bs=by[0],bt=by[1],bu=by[2],bv=by[3],bw=by[4],bx=by[5];
return{x:bs*bz.x+bu*bz.y+bw,y:bt*bz.x+bv*bz.y+bx};
}},aK);
function bo(bs){return bs.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function aI(bs){var bv=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var bu=bv.exec(bs);
if(!bu){return{fontSize:12,fontFamily:"sans-serif"};
}var bt=bu[8]?parseInt(bu[8],10):12;
return{italic:bu[2]&&bu[2].toLowerCase()=="italic",variant:bu[4],bold:bu[6]&&/bold|700/i.test(bu[6]),fontSize:bt,lineHeight:bu[12]?bu[12]=="normal"?bt:parseInt(bu[12],10):null,fontFamily:bu[14].split(/\s*,\s*/g).map(bo)};
}function Q(bw){function bu(by){if(bw.bold){by+="|bold";
}if(bw.italic){by+="|italic";
}return by.toLowerCase();
}var bs=bw.fontFamily;
var bv,bx;
if(bs instanceof Array){for(var bt=0;
bt<bs.length;
++bt){bv=bu(bs[bt]);
bx=N[bv];
if(bx){break;
}}}else{bx=N[bs.toLowerCase()];
}while(typeof bx=="function"){bx=bx();
}if(!bx){bx="Times-Roman";
}return bx;
}var N={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function O(bs,bt){bs=bs.toLowerCase();
N[bs]=function(){return N[bt];
};
N[bs+"|bold"]=function(){return N[bt+"|bold"];
};
N[bs+"|italic"]=function(){return N[bt+"|italic"];
};
N[bs+"|bold|italic"]=function(){return N[bt+"|bold|italic"];
};
}O("Times New Roman","serif");
O("Courier New","monospace");
O("Arial","sans-serif");
O("Helvetica","sans-serif");
O("Verdana","sans-serif");
O("Tahoma","sans-serif");
O("Georgia","sans-serif");
O("Monaco","monospace");
O("Andale Mono","monospace");
function u(bt,bu){if(arguments.length==1){for(var bs in bt){if(U(bt,bs)){u(bs,bt[bs]);
}}}else{bt=bt.toLowerCase();
N[bt]=bu;
switch(bt){case"dejavu sans":N["sans-serif"]=bu;
break;
case"dejavu sans|bold":N["sans-serif|bold"]=bu;
break;
case"dejavu sans|italic":N["sans-serif|italic"]=bu;
break;
case"dejavu sans|bold|italic":N["sans-serif|bold|italic"]=bu;
break;
case"dejavu serif":N.serif=bu;
break;
case"dejavu serif|bold":N["serif|bold"]=bu;
break;
case"dejavu serif|italic":N["serif|italic"]=bu;
break;
case"dejavu serif|bold|italic":N["serif|bold|italic"]=bu;
break;
case"dejavu mono":N.monospace=bu;
break;
case"dejavu mono|bold":N["monospace|bold"]=bu;
break;
case"dejavu mono|italic":N["monospace|italic"]=bu;
break;
case"dejavu mono|bold|italic":N["monospace|bold|italic"]=bu;
break;
}}}function az(bs,bv){var bt=bs[0],bw=bs[1],by=bs[2],bA=bs[3],bC=bs[4],bE=bs[5];
var bu=bv[0],bx=bv[1],bz=bv[2],bB=bv[3],bD=bv[4],bF=bv[5];
return[bt*bu+bw*bz,bt*bx+bw*bB,by*bu+bA*bz,by*bx+bA*bB,bC*bu+bE*bz+bD,bC*bx+bE*bB+bF];
}function ad(bs){return bs[0]===1&&bs[1]===0&&bs[2]===0&&bs[3]===1&&bs[4]===0&&bs[5]===0;
}var bg={fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7};
var bh=bg;
var s={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var ah={butt:0,round:1,square:2};
var ai={miter:0,round:1,bevel:2};
function a1(bx,bs){var bv=[],by={},bB=bx.options;
function bw(bE,bC,bD){if(!bD){bD=bB;
}if(bD.pdf&&bD.pdf[bE]!=null){return bD.pdf[bE];
}return bC;
}var bA=bw("multiPage");
var bz=bw("imgDPI");
if(bz){o();
}bx.traverse(function(bC){x({Image:function(bE){var bG=bE.src();
if(bz){var bD=bE.bbox().size;
var bF=by[bG];
bD={width:Math.ceil(bD.width*bz/72),height:Math.ceil(bD.height*bz/72)};
if(bF){bD.width=Math.max(bF.width,bD.width);
bD.height=Math.max(bF.height,bD.height);
}by[bG]=bD;
}else{by[bG]=null;
}},Text:function(bD){var bE=aI(bD.options.font);
var bF=Q(bE);
if(bv.indexOf(bF)<0){bv.push(bF);
}}},bC);
});
function bu(){if(--bt>0){return;
}var bD=new aL({producer:bw("producer"),title:bw("title"),author:bw("author"),subject:bw("subject"),keywords:bw("keywords"),creator:bw("creator"),date:bw("date"),autoPrint:bw("autoPrint")});
function bC(bG){var bH=bG.options;
var bM=aD(bG);
var bF=bM.bbox;
bG=bM.root;
var bK=bw("paperSize",bw("paperSize","auto"),bH),bE=false;
if(bK=="auto"){if(bF){var bL=bF.getSize();
bK=[bL.width,bL.height];
bE=true;
var bI=bF.getOrigin();
bM=new D.Group();
bM.transform(new af.Matrix(1,0,0,1,-bI.x,-bI.y));
bM.append(bG);
bG=bM;
}else{bK="A4";
}}var bJ;
bJ=bD.addPage({paperSize:bK,margin:bw("margin",bw("margin"),bH),addMargin:bE,landscape:bw("landscape",bw("landscape",false),bH)});
A(bG,bJ,bD);
}if(bA){bx.children.forEach(bC);
}else{bC(bx);
}bs(bD.render(),bD);
}var bt=2;
al(bv,bu);
an(by,bu,{jpegQuality:bw("jpegQuality",0.92),keepPNG:bw("keepPNG",false)});
}function bj(bt,bs){a1(bt,function(bu){bs("data:application/pdf;base64,"+bu.base64());
});
}function bi(bt,bs){a1(bt,function(bu){bs(new window.Blob([bu.get()],{type:"application/pdf"}));
});
}function a5(bu,bt,bv,bs){if(window.Blob&&!bf.safari){bi(bu,function(bw){ae.saveAs({dataURI:bw,fileName:bt});
if(bs){bs(bw);
}});
}else{bj(bu,function(bw){ae.saveAs({dataURI:bw,fileName:bt,proxyURL:bv});
if(bs){bs(bw);
}});
}}function x(bu,bs){var bt=bu[bs.nodeType];
if(bt){return bt.call.apply(bt,arguments);
}return bs;
}function A(bs,bv,bw){if(bs.options._pdfDebug){bv.comment("BEGIN: "+bs.options._pdfDebug);
}var bx=bs.transform();
var bu=bs.opacity();
bv.save();
if(bu!=null&&bu<1){bv.setOpacity(bu);
}a8(bs,bv,bw);
a7(bs,bv,bw);
if(bx){var bt=bx.matrix();
bv.transform(bt.a,bt.b,bt.c,bt.d,bt.e,bt.f);
}a6(bs,bv,bw);
x({Path:F,MultiPath:E,Circle:z,Arc:y,Text:H,Image:C,Group:B,Rect:G},bs,bv,bw);
bv.restore();
if(bs.options._pdfDebug){bv.comment("END: "+bs.options._pdfDebug);
}}function a8(bu,by){var bz=bu.stroke&&bu.stroke();
if(!bz){return;
}var bs=bz.color;
if(bs){bs=aH(bs);
if(bs==null){return;
}by.setStrokeColor(bs.r,bs.g,bs.b);
if(bs.a!=1){by.setStrokeOpacity(bs.a);
}}var bA=bz.width;
if(bA!=null){if(bA===0){return;
}by.setLineWidth(bA);
}var bt=bz.dashType;
if(bt){by.setDashPattern(s[bt],0);
}var bv=bz.lineCap;
if(bv){by.setLineCap(ah[bv]);
}var bw=bz.lineJoin;
if(bw){by.setLineJoin(ai[bw]);
}var bx=bz.opacity;
if(bx!=null){by.setStrokeOpacity(bx);
}}function a7(bt,bw){var bu=bt.fill&&bt.fill();
if(!bu){return;
}if(bu instanceof D.Gradient){return;
}var bs=bu.color;
if(bs){bs=aH(bs);
if(bs==null){return;
}bw.setFillColor(bs.r,bs.g,bs.b);
if(bs.a!=1){bw.setFillOpacity(bs.a);
}}var bv=bu.opacity;
if(bv!=null){bw.setFillOpacity(bv);
}}function a6(bt,bu,bv){var bs=bt.clip();
if(bs){c(bs,bu,bv);
bu.clip();
}}function a9(bs){return bs&&(bs instanceof D.Gradient||bs.color&&!/^(none|transparent)$/i.test(bs.color)&&(bs.width==null||bs.width>0)&&(bs.opacity==null||bs.opacity>0));
}function ax(bt,by,bz,bD){var bv=bt.fill();
if(bv instanceof D.Gradient){if(bD){by.clipStroke();
}else{by.clip();
}var bx=bv instanceof D.RadialGradient;
var bB,bu;
if(bx){bB={x:bv.center().x,y:bv.center().y,r:0};
bu={x:bv.center().x,y:bv.center().y,r:bv.radius()};
}else{bB={x:bv.start().x,y:bv.start().y};
bu={x:bv.end().x,y:bv.end().y};
}var bC=bv.stops.elements().map(function(bH){var bG=bH.offset();
if(/%$/.test(bG)){bG=parseFloat(bG)/100;
}else{bG=parseFloat(bG);
}var bF=aH(bH.color());
bF.a*=bH.opacity();
return{offset:bG,color:bF};
});
bC.unshift(bC[0]);
bC.push(bC[bC.length-1]);
var bw={userSpace:bv.userSpace(),type:bx?"radial":"linear",start:bB,end:bu,stops:bC};
var bs=bt.rawBBox();
var bE=bs.topLeft(),bA=bs.getSize();
bs={left:bE.x,top:bE.y,width:bA.width,height:bA.height};
by.gradient(bw,bs);
return true;
}}function aw(bs,bt,bu){if(a9(bs.fill())&&a9(bs.stroke())){if(!ax(bs,bt,bu,true)){bt.fillStroke();
}}else{if(a9(bs.fill())){if(!ax(bs,bt,bu,false)){bt.fill();
}}else{if(a9(bs.stroke())){bt.stroke();
}else{bt.nop();
}}}}function av(bw,bv){var bx=bw.segments;
if(bx.length==4&&bw.options.closed){var bs=[];
for(var bt=0;
bt<bx.length;
++bt){if(bx[bt].controlIn()){return false;
}bs[bt]=bx[bt].anchor();
}var bu=bs[0].y==bs[1].y&&bs[1].x==bs[2].x&&bs[2].y==bs[3].y&&bs[3].x==bs[0].x||bs[0].x==bs[1].x&&bs[1].y==bs[2].y&&bs[2].x==bs[3].x&&bs[3].y==bs[0].y;
if(bu){bv.rect(bs[0].x,bs[0].y,bs[2].x-bs[0].x,bs[2].y-bs[0].y);
return true;
}}}function c(bu,bw,bx){var bB=bu.segments;
if(bB.length===0){return;
}if(!av(bu,bw,bx)){for(var by,bv=0;
bv<bB.length;
++bv){var bA=bB[bv];
var bs=bA.anchor();
if(!by){bw.moveTo(bs.x,bs.y);
}else{var bz=by.controlOut();
var bt=bA.controlIn();
if(bz&&bt){bw.bezier(bz.x,bz.y,bt.x,bt.y,bs.x,bs.y);
}else{bw.lineTo(bs.x,bs.y);
}}by=bA;
}if(bu.options.closed){bw.close();
}}}function F(bs,bt,bu){c(bs,bt,bu);
aw(bs,bt,bu);
}function E(bs,bu,bw){var bv=bs.paths;
for(var bt=0;
bt<bv.length;
++bt){c(bv[bt],bu,bw);
}aw(bs,bu,bw);
}function z(bs,bu,bv){var bt=bs.geometry();
bu.circle(bt.center.x,bt.center.y,bt.radius);
aw(bs,bu,bv);
}function y(bs,bu,bv){var bw=bs.geometry().curvePoints();
bu.moveTo(bw[0].x,bw[0].y);
for(var bt=1;
bt<bw.length;
){bu.bezier(bw[bt].x,bw[bt++].y,bw[bt].x,bw[bt++].y,bw[bt].x,bw[bt++].y);
}aw(bs,bu,bv);
}function H(bs,bu){var bw=aI(bs.options.font);
var bv=bs._position;
var bt;
if(bs.fill()&&bs.stroke()){bt=bh.fillAndStroke;
}else{if(bs.fill()){bt=bh.fill;
}else{if(bs.stroke()){bt=bh.stroke;
}}}bu.transform(1,0,0,-1,bv.x,bv.y+bw.fontSize);
bu.beginText();
bu.setFont(Q(bw),bw.fontSize);
bu.setTextRenderingMode(bt);
bu.showText(bs.content(),bs._pdfRect?bs._pdfRect.width():null);
bu.endText();
}function B(bt,bv,bw){if(bt._pdfLink){bv.addLink(bt._pdfLink.url,bt._pdfLink);
}var bs=bt.children;
for(var bu=0;
bu<bs.length;
++bu){A(bs[bu],bv,bw);
}}function C(bs,bt){var bx=bs.src();
if(!bx){return;
}var bu=bs.rect();
var bw=bu.getOrigin();
var bv=bu.getSize();
bt.transform(bv.width,0,0,-bv.height,bw.x,bw.y+bv.height);
bt.drawImage(bx);
}function G(bs,bu,bv){var bt=bs.geometry();
bu.rect(bt.origin.x,bt.origin.y,bt.size.width,bt.size.height);
aw(bs,bu,bv);
}function aH(bt){var bs=ae.parseColor(bt,true);
return bs?bs.toRGB():null;
}function aD(bA){var bu=false;
var bx=af.Matrix.unit();
var bv=null;
var bt;
do{bt=false;
bA=by(bA);
}while(bA&&bt);
return{root:bA,bbox:bv};
function bs(bD){bt=true;
return bD;
}function bB(bD){return bD.visible()&&bD.opacity()>0&&(a9(bD.fill())||a9(bD.stroke()));
}function bz(bD){var bE=[];
for(var bG=0;
bG<bD.length;
++bG){var bF=by(bD[bG]);
if(bF!=null){bE.push(bF);
}}return bE;
}function bC(bH,bE){var bF=bu;
var bG=bx;
if(bH.transform()){bx=bx.multiplyCopy(bH.transform().matrix());
}var bD=bH.clip();
if(bD){bD=bD.bbox();
if(bD){bD=bD.bbox(bx);
bu=bu?af.Rect.intersect(bu,bD):bD;
}}try{return bE();
}finally{bu=bF;
bx=bG;
}}function bw(bE){if(bu==null){return false;
}var bD=bE.rawBBox().bbox(bx);
if(bu&&bD){bD=af.Rect.intersect(bD,bu);
}return bD;
}function by(bD){return bC(bD,function(){if(!(bD instanceof D.Group||bD instanceof D.MultiPath)){var bE=bw(bD);
if(!bE){return bs(null);
}bv=bv?af.Rect.union(bv,bE):bE;
}return x({Path:function(bF){if(bF.segments.length===0||!bB(bF)){return bs(null);
}return bF;
},MultiPath:function(bG){if(!bB(bG)){return bs(null);
}var bF=new D.MultiPath(bG.options);
bF.paths=bz(bG.paths);
if(bF.paths.length===0){return bs(null);
}return bF;
},Circle:function(bF){if(!bB(bF)){return bs(null);
}return bF;
},Arc:function(bF){if(!bB(bF)){return bs(null);
}return bF;
},Text:function(bF){if(!/\S/.test(bF.content())||!bB(bF)){return bs(null);
}return bF;
},Image:function(bF){if(!(bF.visible()&&bF.opacity()>0)){return bs(null);
}return bF;
},Group:function(bG){if(!(bG.visible()&&bG.opacity()>0)){return bs(null);
}var bF=new D.Group(bG.options);
bF.children=bz(bG.children);
bF._pdfLink=bG._pdfLink;
if(bG!==bA&&bF.children.length===0&&!bG._pdfLink){return bs(null);
}return bF;
},Rect:function(bF){if(!bB(bF)){return bs(null);
}return bF;
}},bD);
});
}}function K(bs,bu){var bv=bp.createPromise();
for(var bt in bu){if(bt=="margin"&&bs.options.pdf&&bs.options.pdf._ignoreMargin){continue;
}bs.options.set("pdf."+bt,bu[bt]);
}bj(bs,bv.resolve);
return bv;
}function L(bs,bu){var bv=bp.createPromise();
for(var bt in bu){if(bt=="margin"&&bs.options.pdf&&bs.options.pdf._ignoreMargin){continue;
}bs.options.set("pdf."+bt,bu[bt]);
}if(window.Blob&&!bf.safari){bi(bs,bv.resolve);
}else{bj(bs,bv.resolve);
}return bv;
}ae.deepExtend(ae.pdf,{Document:aL,BinaryStream:g,defineFont:u,parseFontDef:aI,getFontURL:Q,loadFonts:al,loadImages:an,getPaperOptions:R,clearImageCache:o,TEXT_RENDERING_MODE:bg,exportPDF:K,exportPDFToBlob:L,saveAs:a5,toDataURL:bj,toBlob:bi,render:a1});
ae.drawing.exportPDF=ae.pdf.exportPDF;
ae.drawing.pdf=ae.pdf;
}(kendo));
return kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/mixins",["pdf/core"],b);
}(function(){(function(a,b){kendo.PDFMixin={extend:function(c){c.events.push("pdfExport");
c.options.pdf=this.options;
c.saveAsPDF=this.saveAsPDF;
c._drawPDF=this._drawPDF;
c._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator v."+kendo.version,date:null},saveAsPDF:function(){var e=new a.Deferred();
var f=e.promise();
var c={promise:f};
if(this.trigger("pdfExport",c)){return;
}var d=this.options.pdf;
d.multiPage=d.multiPage||d.allPages;
this._drawPDF(e).then(function(g){return kendo.drawing.exportPDF(g,d);
}).done(function(g){kendo.saveAs({dataURI:g,fileName:d.fileName,proxyURL:d.proxyURL,forceProxy:d.forceProxy,proxyTarget:d.proxyTarget});
e.resolve();
}).fail(function(g){e.reject(g);
});
return f;
},_drawPDF:function(c){var d=new a.Deferred();
kendo.drawing.drawDOM(this.wrapper).done(function(f){var e={page:f,pageNumber:1,progress:1,totalPages:1};
c.notify(e);
d.resolve(e.page);
}).fail(function(e){d.reject(e);
});
return d;
},_drawPDFShadow:function(e,d){e=e||{};
var g=this.wrapper;
var f=a("<div class='k-pdf-export-shadow'>");
if(e.width){f.css({width:e.width,overflow:"visible"});
}g.before(f);
f.append(e.content||g.clone(true,true));
var c=a.Deferred();
setTimeout(function(){var h=kendo.drawing.drawDOM(f,d);
h.always(function(){f.remove();
}).then(function(){c.resolve.apply(c,arguments);
}).fail(function(){c.reject.apply(c,arguments);
}).progress(function(){c.progress.apply(c,arguments);
});
},15);
return c.promise();
}};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.pdf",["kendo.core","kendo.drawing","pdf/core","pdf/mixins"],b);
}(function(){var a={id:"pdf",name:"PDF export",description:"PDF Generation framework",mixin:true,category:"framework",depends:["core","drawing"]};
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
