(function(b,a){a("kendo.selectable",["kendo.core","kendo.userevents"],b);
}(function(){var a={id:"selectable",name:"Selectable",category:"framework",depends:["core","userevents"],advanced:true};
(function(b,q){var i=window.kendo,t=i.ui.Widget,l=b.proxy,c=Math.abs,e="aria-selected",o="k-state-selected",d="k-state-selecting",n="k-selectable",f="change",k=".kendoSelectable",r="unselect",s="k-state-unselecting",h="input,a,textarea,.k-multiselect-wrap,select,button,.k-button>span,.k-button>img,span.k-icon.k-i-arrow-60-down,span.k-icon.k-i-arrow-60-up,label.k-checkbox-label.k-no-text,.k-icon.k-i-collapse,.k-icon.k-i-expand,span.k-numeric-wrap,.k-focusable",j=i.support.browser.msie,p=false;
(function(u){(function(){u('<div class="parent"><span></span></div>').on("click",">*",function(){p=true;
}).find("span").trigger("click").end().off();
}());
}(b));
var m=t.extend({init:function(u,w){var x=this,v;
t.fn.init.call(x,u,w);
x._marquee=b("<div class='k-marquee'><div class='k-marquee-color'></div></div>");
x._lastActive=null;
x.element.addClass(n);
x.relatedTarget=x.options.relatedTarget;
v=x.options.multiple;
if(this.options.aria&&v){x.element.attr("aria-multiselectable",true);
}x.userEvents=new i.UserEvents(x.element,{global:true,allowSelection:true,filter:(!p?"."+n+" ":"")+x.options.filter,tap:l(x._tap,x),touchAction:v?"none":"pan-x pan-y"});
if(v){x.userEvents.bind("start",l(x._start,x)).bind("move",l(x._move,x)).bind("end",l(x._end,x)).bind("select",l(x._select,x));
}},events:[f,r],options:{name:"Selectable",filter:">*",inputSelectors:h,multiple:false,relatedTarget:b.noop},_isElement:function(y){var u=this.element;
var v,w=u.length,x=false;
y=y[0];
for(v=0;
v<w;
v++){if(u[v]===y){x=true;
break;
}}return x;
},_tap:function(w){var A=b(w.target),B=this,v=w.event.ctrlKey||w.event.metaKey,x=B.options.multiple,z=x&&w.event.shiftKey,y,C=w.event.which,u=w.event.button;
if(!B._isElement(A.closest("."+n))||C&&C==3||u&&u==2){return;
}if(!this._allowSelection(w.event.target)){return;
}y=A.hasClass(o);
if(!x||!v){B.clear();
}A=A.add(B.relatedTarget(A));
if(z){B.selectRange(B._firstSelectee(),A,w);
}else{if(y&&v){B._unselect(A);
B._notify(f,w);
}else{B.value(A,w);
}B._lastActive=B._downTarget=A;
}},_start:function(w){var z=this,y=b(w.target),x=y.hasClass(o),v,u=w.event.ctrlKey||w.event.metaKey;
if(!this._allowSelection(w.event.target)){return;
}z._downTarget=y;
if(!z._isElement(y.closest("."+n))){z.userEvents.cancel();
return;
}if(z.options.useAllItems){z._items=z.element.find(z.options.filter);
}else{v=y.closest(z.element);
z._items=v.find(z.options.filter);
}w.sender.capture();
z._marquee.appendTo(document.body).css({left:w.x.client+1,top:w.y.client+1,width:0,height:0});
if(!u){z.clear();
}y=y.add(z.relatedTarget(y));
if(x){z._selectElement(y,true);
if(u){y.addClass(s);
}}},_move:function(u){var w=this,v={left:u.x.startLocation>u.x.location?u.x.location:u.x.startLocation,top:u.y.startLocation>u.y.location?u.y.location:u.y.startLocation,width:c(u.x.initialDelta),height:c(u.y.initialDelta)};
w._marquee.css(v);
w._invalidateSelectables(v,u.event.ctrlKey||u.event.metaKey);
u.preventDefault();
},_end:function(u){var w=this;
w._marquee.remove();
w._unselect(w.element.find(w.options.filter+"."+s)).removeClass(s);
var v=w.element.find(w.options.filter+"."+d);
v=v.add(w.relatedTarget(v));
w.value(v,u);
w._lastActive=w._downTarget;
w._items=null;
},_invalidateSelectables:function(y,u){var v,x,A=this._downTarget[0],w=this._items,z,B;
for(v=0,x=w.length;
v<x;
v++){B=w.eq(v);
z=B.add(this.relatedTarget(B));
if(g(B,y)){if(B.hasClass(o)){if(u&&A!==B[0]){z.removeClass(o).addClass(s);
}}else{if(!B.hasClass(d)&&!B.hasClass(s)){z.addClass(d);
}}}else{if(B.hasClass(d)){z.removeClass(d);
}else{if(u&&B.hasClass(s)){z.removeClass(s).addClass(o);
}}}}},value:function(x,u){var w=this,v=l(w._selectElement,w);
if(x){x.each(function(){v(this);
});
w._notify(f,u);
return;
}return w.element.find(w.options.filter+"."+o);
},_firstSelectee:function(){var v=this,u;
if(v._lastActive!==null){return v._lastActive;
}u=v.value();
return u.length>0?u[0]:v.element.find(v.options.filter)[0];
},_selectElement:function(u,w){var x=b(u),v=!w&&this._notify("select",{element:u});
x.removeClass(d);
if(!v){x.addClass(o);
if(this.options.aria){x.attr(e,true);
}}},_notify:function(v,u){u=u||{};
return this.trigger(v,u);
},_unselect:function(u){if(this.trigger(r,{element:u})){return;
}u.removeClass(o);
if(this.options.aria){u.attr(e,false);
}return u;
},_select:function(u){if(this._allowSelection(u.event.target)){if(!j||j&&!b(i._activeElement()).is(this.options.inputSelectors)){u.preventDefault();
}}},_allowSelection:function(u){if(b(u).is(this.options.inputSelectors)){this.userEvents.cancel();
this._downTarget=null;
return false;
}return true;
},resetTouchEvents:function(){this.userEvents.cancel();
},clear:function(){var u=this.element.find(this.options.filter+"."+o);
this._unselect(u);
},selectRange:function(y,v,u){var z=this,w,A,x;
z.clear();
if(z.element.length>1){x=z.options.continuousItems();
}if(!x||!x.length){x=z.element.find(z.options.filter);
}y=b.inArray(b(y)[0],x);
v=b.inArray(b(v)[0],x);
if(y>v){A=y;
y=v;
v=A;
}if(!z.options.useAllItems){v+=z.element.length-1;
}for(w=y;
w<=v;
w++){z._selectElement(x[w]);
}z._notify(f,u);
},destroy:function(){var u=this;
t.fn.destroy.call(u);
u.element.off(k);
u.userEvents.destroy();
u._marquee=u._lastActive=u.element=u.userEvents=null;
}});
m.parseOptions=function(v){var u=typeof v==="string"&&v.toLowerCase();
return{multiple:u&&u.indexOf("multiple")>-1,cell:u&&u.indexOf("cell")>-1};
};
function g(v,x){if(!v.is(":visible")){return false;
}var w=i.getOffset(v),y=x.left+x.width,u=x.top+x.height;
w.right=w.left+i._outerWidth(v);
w.bottom=w.top+i._outerHeight(v);
return !(w.left>y||w.right<x.left||w.top>u||w.bottom<x.top);
}i.ui.plugin(m);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
