(function(b,a){a("kendo.switch",["kendo.core"],b);
}(function(){var a={id:"switch",name:"Switch",category:"web",description:"The Switch widget is used to display two exclusive choices.",depends:["core"]};
(function(b,w){var j=window.kendo,v=j.ui,m=".kendoSwitch",x=v.Widget,p=j.support,f="change",t={widget:"k-switch k-widget",container:"k-switch-container",handle:"k-switch-handle",checked:"k-switch-on",checkedLabel:"k-switch-label-on",unchecked:"k-switch-off",uncheckedLabel:"k-switch-label-off",disabled:"k-state-disabled",readonly:"k-state-readonly",active:"k-state-active"},i="disabled",d="aria-disabled",o="readonly",e="aria-readonly",c="aria-checked",g="checked",h=p.click+m,u=p.pointers?"pointerup":"touchend",k="keydown"+m,l="_label",n=b.proxy;
var s=j.template('<span class="#=styles.widget#" role="switch"></span>');
var r=j.template("<span class='#=styles.container#'><span class='#=styles.checkedLabel#'>#=checked#</span><span class='#=styles.uncheckedLabel#'>#=unchecked#</span><span class='#=styles.handle#'></span></span>");
var q=x.extend({init:function(y,z){var A=this,B;
x.fn.init.call(A,y,z);
z=A.options;
y=A.element[0];
y.type="checkbox";
B=b(s({styles:t}));
A.wrapper=A.element.wrap(B).parent();
A.wrapper.append(b(r({styles:t,checked:z.messages.checked,unchecked:z.messages.unchecked}))).addClass(y.className).removeClass("input-validation-error");
A.wrapper.on(h,n(A._click,A)).on(u,n(A._touchEnd,A)).on(k,n(A._keydown,A));
if(A.options.enabled){A._tabindex();
}A._initSettings();
A._aria();
j.notify(A,j.ui);
},setOptions:function(A){var B=this,z=A.messages,y,C;
B.options=b.extend(B.options,A);
if(z&&z.checked!==w){y=B.wrapper.find("."+t.checkedLabel);
y.text(z.checked);
}if(z&&z.unchecked!==w){C=B.wrapper.find("."+t.uncheckedLabel);
C.text(z.unchecked);
}if(A.width){B.wrapper.css({width:A.width});
}if(A.enabled!==w){B.enable(A.enabled);
}if(A.readonly!==w){B.readonly(A.readonly);
}B.check(A.checked);
},_initSettings:function(){var A=this,y=A.element[0],z=A.options;
if(z.width){A.wrapper.css({width:z.width});
}if(z.checked===null){z.checked=y.checked;
}A.check(z.checked);
z.enabled=z.enabled&&!A.element.attr(i);
A.enable(z.enabled);
z.readonly=z.readonly||!!A.element.attr(o);
A.readonly(z.readonly);
},_aria:function(){var E=this,A=E.element,F=E.wrapper,B=A.attr("id"),C=b('label[for="'+B+'"]'),y=A.attr("aria-label"),z=A.attr("aria-labelledby");
if(y){F.attr("aria-label",y);
}else{if(z){F.attr("aria-labelledby",z);
}else{if(C.length){var D=C.attr("id");
if(!D){D=(B||j.guid())+l;
C.attr("id",D);
}F.attr("aria-labelledby",D);
}}}},events:[f],options:{name:"Switch",messages:{checked:"On",unchecked:"Off"},width:null,checked:null,enabled:true,readonly:false},check:function(y){var A=this,z=A.element[0];
if(y===w){return z.checked;
}if(z.checked!==y){A.options.checked=z.checked=y;
}A.wrapper.attr(c,y).toggleClass(t.checked,y).toggleClass(t.unchecked,!y);
if(y){A.element.attr(g,g);
}else{A.element.removeAttr(g);
}},value:function(y){if(typeof y==="string"){y=y==="true";
}return this.check.apply(this,[y]);
},destroy:function(){x.fn.destroy.call(this);
this.wrapper.off(m);
},toggle:function(){var y=this;
y.check(!y.element[0].checked);
},enable:function(z){var y=this.element,A=this.wrapper;
if(typeof z=="undefined"){z=true;
}this.options.enabled=z;
if(z){y.removeAttr(i);
A.removeAttr(d);
}else{y.attr(i,i);
A.attr(d,true);
}A.toggleClass(t.disabled,!z);
},readonly:function(z){var A=this,y=A.element,B=A.wrapper;
if(typeof z=="undefined"){z=true;
}A.options.readonly=z;
if(z){y.attr(o,true);
B.attr(e,true);
}else{y.removeAttr(o);
B.removeAttr(e);
}B.toggleClass(t.readonly,z);
},_check:function(){var z=this,y=z.element[0].checked=!z.element[0].checked;
z.wrapper.focus();
if(!z.options.enabled||z.options.readonly||z.trigger(f,{checked:y})){z.element[0].checked=!y;
return;
}z.check(y);
},_keydown:function(y){if(y.keyCode===j.keys.SPACEBAR){this._check();
y.preventDefault();
}},_isTouch:function(y){return/touch/.test(y.type)||y.originalEvent&&/touch/.test(y.originalEvent.pointerType);
},_click:function(y){if(!this._isTouch(y)&&y.which===1){this._check();
}},_touchEnd:function(y){if(this._isTouch(y)){this._check();
y.preventDefault();
}}});
v.plugin(q);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
