(function(b,a){a("kendo.timeline",["kendo.fx","kendo.data","kendo.draganddrop"],b);
}(function(){var a={id:"timeline",name:"Timeline",category:"web",description:"The Kendo Timeline widget display events over time",depends:["userevents"]};
(function(b,D){var q=window.kendo,C=q.ui,I=C.Widget,j=q.data.DataSource,A=q.effects.Transition,v=b.proxy,r=q.keys,p=b.isArray,s=-1,g=0,w=1,E="vertical",B="transitionEnd",H=3,G="timeline-event",m="k-timeline-flag-wrap",z="k-timeline-track-item",x="k-timeline-scrollable-wrap",t=".kendoTimeline",h="change",k='# var titleField = data.titleField, subtitleField = data.subtitleField, descriptionField = data.descriptionField, imagesField = data.imagesField, actionsField = data.actionsField, altField = data.altField, data = data.data; #<div class="k-card-inner"><div class="k-card-header"># if(data[titleField]) { #<h5 class="k-card-title">#= data[titleField] #</h5># }if(data[subtitleField]) { #<h6 class="k-card-subtitle">#= data[subtitleField] #</h6># } #</div><div class="k-card-body"><div class="k-card-description"># if(data[descriptionField]) { #<p>#= data[descriptionField] #</p># }if(data[imagesField] && data[imagesField].length > 0) { #<img src="#= data[imagesField][0].src #"  #if(data[altField]){# alt="#:data[altField]#" #}# class="k-card-image" /># } #</div></div># if(data[actionsField] && data[actionsField].length > 0) { #<div class="k-card-actions"># for (var i = 0; i < data[actionsField].length; i++) { #<a class="k-button k-flat k-primary" href="#= data[actionsField][i].url ? data[actionsField][i].url : "\\#" #">#= data[actionsField][i].text #</a># } #</div># } #</div>',l='# var titleField = data.titleField, subtitleField = data.subtitleField, descriptionField = data.descriptionField, imagesField = data.imagesField, navigatable = data.navigatable, collapsibleEvents = data.collapsibleEvents, actionsField = data.actionsField, altField = data.altField, data = data.data; #<div class="k-card-inner"><div class="k-card-header"><h5 class="k-card-title"># if(data[titleField]) { #<span class="k-event-title">#= data[titleField] #</span># } #<span class="k-event-collapse k-button k-button-icon k-flat"><span class="k-icon k-i-arrow-chevron-right"></span></span></h5># if(data[subtitleField]) { #<h6 class="k-card-subtitle">#= data[subtitleField] #</h6># } #</div><div class="k-card-body"><div class="k-card-description"># if(data[descriptionField]) { #<p>#= data[descriptionField] #</p># } ## if(data[imagesField] && data[imagesField].length > 0) { #<img src="#= data[imagesField][0].src #" #if(data[altField]){# alt="#:data[altField]#" #}# class="k-card-image" /># } #</div></div># if(data[actionsField] && data[actionsField].length > 0) { #<div class="k-card-actions"># for (var i = 0; i < data[actionsField].length; i++) { #<a class="k-button k-flat k-primary" href="#= data[actionsField][i].url ? data[actionsField][i].url : "\\#" #">#= data[actionsField][i].text #</a># } #</div># } #</div>',o='# var itemTemplate = data.itemTemplate, dateField = data.dateField, dateFormat = data.dateFormat, showDateLabels = data.showDateLabels, data = data.data, year = 0; ## for (var i = 0; i < data.length; i++) {if(!(data[i][dateField] instanceof Date)) {continue;}var currentYear = data[i][dateField].getFullYear();if(year != currentYear) {year = currentYear; #<li class="k-timeline-track-item k-timeline-flag-wrap"><span class="k-timeline-flag">#= year #</span></li># } #<li class="k-timeline-track-item"><div class="k-timeline-date-wrap"># if(showDateLabels) { #<span class="k-timeline-date">#= kendo.toString(data[i][dateField], dateFormat) #</span># } #</div><a class="k-timeline-circle"></a></li># } #',F='# var itemTemplate = data.itemTemplate, dateField = data.dateField, titleField = data.titleField, descriptionField = data.descriptionField, subtitleField = data.subtitleField, imagesField = data.imagesField, actionsField = data.actionsField, alterMode = data.alterMode, collapsibleEvents = data.collapsibleEvents, dateFormat = data.dateFormat, showDateLabels = data.showDateLabels, navigatable = data.navigatable, altField = data.altField, data = data.data, counter = 0, year = 0, reverse = false;for (var i = 0; i < data.length; i++) {if(!(data[i][dateField] instanceof Date)) {continue;}var currentYear = data[i][dateField].getFullYear();if(currentYear != year) {year = currentYear; #<li class="k-timeline-flag-wrap"><span class="k-timeline-flag">#= year #</span></li># } reverse = counter % 2 === 0 && alterMode; #<li class="#= reverse ? \'k-timeline-event k-reverse\' : \'k-timeline-event\' #" data-uid="#: data[i].uid #"># if(showDateLabels) { #<div class="k-timeline-date-wrap"><span class="k-timeline-date">#= kendo.toString(data[i][dateField], dateFormat) #</span></div># } #<a class="k-timeline-circle"></a><div class="#= collapsibleEvents ? \'k-timeline-card k-collapsed\' : \'k-timeline-card\' #"><div class="k-card" #= (navigatable) ? "tabindex=\'0\' aria-live=\'polite\' aria-atomic=\'true\' role=\'button\'" : "" #><span class="#= reverse ? \'k-timeline-card-callout k-card-callout k-callout-e\' : \'k-timeline-card-callout k-card-callout k-callout-w\' #"></span>#= itemTemplate({titleField: titleField, subtitleField: subtitleField, descriptionField: descriptionField, imagesField: imagesField, actionsField: actionsField, data: data[i], altField: altField, navigatable: navigatable, collapsibleEvents: collapsibleEvents}) #</div></div></li># counter ++;} #',d='<a class="k-button k-timeline-arrow k-timeline-arrow-left k-state-disabled" title="previous"><span class="k-icon k-i-arrow-60-left"></span></a><a class="k-button k-timeline-arrow k-timeline-arrow-right k-state-disabled" title="next"><span class="k-icon k-i-arrow-60-right"></span></a>';
function i(J){return"k-"+J;
}function f(J){var K=J.css("transform");
var M;
var L;
if(K!="none"){L=K.match(/-?[\d\.]+/g);
M=L[4];
return M/J.width()*100;
}else{return 0;
}}function e(J,K){return J.offset().left-K.offset().left+J.width()/2;
}function c(J,K,L){J.css(K,L);
}var u=q.Class.extend({init:function(K){this.cardContainer=b("<div class='k-card' />");
var J=b("<div class='k-timeline-card'></div>").append(this.cardContainer);
this.element=b("<li class='"+i(G)+"'></li>").append(J);
K.append(this.element);
},content:function(K,L){var J=b("<span class='k-timeline-card-callout k-card-callout k-callout-n'></span>");
this.cardContainer.html(K);
this.cardContainer.append(J);
this.element.attr("data-uid",L);
},position:function(J){this.element.css("transform","translate3d("+this.element.width()*J+"px, 0, 0)");
},setPageCallout:function(L,M){var K=this.element;
var J=K.find(".k-timeline-card-callout");
J.css(L,M);
},destroy:function(){var J=this;
J.cardContainer=null;
J.element.remove();
J.element=null;
}});
var n=q.Observable.extend({init:function(J,L){var N=this;
q.Observable.fn.init.call(this);
this.element=J;
var K,O,M;
K=new q.ui.Movable(N.element);
O=new A({axis:"x",movable:K,onEnd:function(){N.trigger(B);
}});
M=[];
b.extend(N,{duration:L&&L.duration||1,movable:K,transition:O,pages:M,eventTemplate:L.eventTemplate,eventHeight:L.eventHeight,dataFieldMappings:L.dataFieldMappings});
this.bind([B],L);
},initPages:function(){var M=this.pages,J=this.element,L;
for(var K=0;
K<H;
K++){L=new u(J);
M.push(L);
}},repositionPages:function(){var J=this.pages;
J[0].position(s);
J[1].position(g);
J[2].position(w);
},setPageContent:function(M,J){var N=typeof this.eventTemplate===Function?this.eventTemplate:q.template(this.eventTemplate);
var K=this.dataFieldMappings;
var L;
L=N({data:J,titleField:K.title,subtitleField:K.subtitle,descriptionField:K.description,imagesField:K.images,actionsField:K.actions,altField:K.altField});
M.content(L,J.uid);
},updatePage:function(L,K,J){var N=this.pages;
var M=L===null?N[1]:L?N[N.length-1]:N[0];
this.setPageContent(M,K);
M.setPageCallout("left",J/M.element.width()*100+"%");
},moveTo:function(J){this.movable.moveAxis("x",-J);
},transitionTo:function(K,J){this.transition.moveTo({location:K,duration:this.duration,ease:J});
},destroy:function(){var K=this;
for(var J=0;
J<K.pages.length;
J++){K.pages[J].destroy();
}K.unbind();
K.movable=K.transition=K.dataFieldMappings=K.eventTemplate=K.duration=K.pages=null;
}});
var y=q.ui.Widget.extend({init:function(J,K){var M=this;
var L=K.orientation||M.options.orientation;
I.fn.init.call(this,J,K);
this.element.addClass(L===E?"k-timeline k-widget k-timeline-vertical":"k-timeline k-widget k-timeline-horizontal");
if(L!=E){M._horizontal();
}else{M._vertical();
}this.element.on("click",".k-card-actions",function(){var N=b(event.target);
var P=b(event.target).closest(".k-timeline-event").data("uid");
var O=M.dataSource.getByUid(P);
M.trigger("actionClick",{sender:M,element:N,dataItem:O});
});
M.currentEventIndex=0;
M._forward=null;
M._eventPage=1;
M._currentIndex=0;
M._firstIndexInView=0;
M._initDataFieldMappings();
M.setDataSource(K.dataSource);
},_horizontal:function(){var O=this;
var J=this.element;
var M=this.options;
var Q=b("<div />");
var P=b("<div />");
var N=b("<ul />");
var L=b("<div />");
var K=b("<ul />");
O._trackWrap=Q;
O._trackEl=P;
O._scrollableWrap=N;
O._eventsWrap=L;
O._eventsList=K;
Q.addClass("k-timeline-track-wrap");
P.addClass("k-timeline-track");
N.addClass("k-timeline-scrollable-wrap");
L.addClass("k-timeline-events-list");
K.addClass("k-timeline-scrollable-wrap");
if(M.eventHeight){K.height(M.eventHeight);
}P.append(N);
Q.append(d);
Q.append(P);
L.append(K);
Q.appendTo(J);
L.appendTo(J);
},_vertical:function(){var O=this;
var N=this.options;
var K=this.element;
var L=O._eventsList=b("<ul />");
var M=N.navigatable;
var J=N.collapsibleEvents;
O.element.append(L);
if(N.alternatingMode){K.addClass("k-timeline-alternating");
}if(J){K.addClass("k-timeline-collapsible");
this.element.on("click",".k-card-header",function(){var P=b(this).closest(".k-timeline-card");
var Q=P.find(".k-card-body");
var R=O.dataSource.getByUid(P.closest("li").data("uid"));
if(P.hasClass("k-collapsed")){if(!O.trigger("expand",{sender:O,dataItem:R})){q.fx(Q).expand("vertical").stop().play();
P.toggleClass("k-collapsed");
if(M&&J){P.find(".k-card").attr("aria-expanded",true);
}}}else{if(!O.trigger("collapse",{sender:O,dataItem:R})){q.fx(Q).expand("vertical").stop().reverse();
P.toggleClass("k-collapsed");
if(M&&J){P.find(".k-card").attr("aria-expanded",false);
}}}});
}if(M){if(J){this.element.on("keydown"+t,O,function(P){if(P.keyCode==r.SPACEBAR||P.keyCode==r.ENTER){var R=b(P.target);
var Q=R.find(".k-card-header");
if(Q.length){P.preventDefault();
Q.trigger("click");
}}});
}}},_renderContentVertical:function(J){var O=this;
var M=O.options;
var K;
var L;
if(typeof M.eventTemplate===Function){L=M.eventTemplate;
}else{L=M.eventTemplate?q.template(M.eventTemplate):q.template(l,{useWithBlock:false});
}var N=q.template(F,{useWithBlock:false});
K=N({data:J,dateField:M.dataDateField,titleField:M.dataTitleField,subtitleField:M.dataSubtitleField,descriptionField:M.dataDescriptionField,imagesField:M.dataImagesField,actionsField:M.dataActionsField,itemTemplate:L,alterMode:M.alternatingMode,collapsibleEvents:M.collapsibleEvents,dateFormat:M.dateFormat,showDateLabels:M.showDateLabels,altField:M.dataImagesAltField,navigatable:M.navigatable});
this._eventsList.html(K);
if(M.eventWidth){O.element.find(".k-card").width(M.eventWidth);
}},_renderContentHorizontal:function(J){var O=this;
var N=O.options;
var L;
var M;
var K=O._dataFieldMappings;
if(typeof N.eventTemplate===Function){M=N.eventTemplate;
}else{M=N.eventTemplate?q.template(N.eventTemplate):q.template(k,{useWithBlock:false});
}var P=q.template(o,{useWithBlock:false});
L=P({data:J,itemTemplate:M,dateFormat:N.dateFormat,dateField:N.dataDateField,showDateLabels:N.showDateLabels});
if(N.initialEventIndex){O._trackWrap.append(b(L).find(".k-timeline-scrollable-wrap").css("transform","translateX(-100%)").parent());
}else{O._scrollableWrap.html(L);
}if(O.pane){O.pane.destroy();
}O.pane=new n(O._eventsList,{transitionEnd:v(this,"_transitionEnd"),eventTemplate:M,dataFieldMappings:K,eventHeight:N.eventHeight});
},_initDataFieldMappings:function(){var K=this;
var J=K.options;
K._dataFieldMappings={title:J.dataTitleField,subtitle:J.dataSubtitleField,date:J.dataDateField,description:J.dataDescriptionField,images:J.dataImagesField,actions:J.dataActionsField,altField:J.dataImagesAltField};
},_transitionEnd:function(){if(this._forward){this.pane.pages.push(this.pane.pages.shift());
}else{this.pane.pages.unshift(this.pane.pages.pop());
}this._forward=null;
this.pane.repositionPages();
this.pane.movable.moveAxis("x",0);
if(this.options.navigatable){this._transition=null;
this._eventsList.find(".k-card").removeAttr("id");
this.pane.pages[1].cardContainer.attr("id",this._cardId);
this._setCurrent(this._currentBullet);
}this._animationInProgress=false;
},_setCurrentEvent:function(K){var M=this;
var N=b(K.currentTarget);
var L;
var J=M.dataSource.view()[N.parent().children(":not(.k-timeline-flag-wrap)").index(N)];
L=M._forward?M.pane.pages[2].element:M.pane.pages[0].element;
if(!M.trigger("change",{eventContainer:L,dataItem:J})){M.open(N);
}},open:function(K){var N=this;
var O=b(K);
var P=O.find(".k-timeline-circle");
var Q=O.parent().children(":not(.k-timeline-flag-wrap)");
var M=Q.index(O);
var L;
if(this.options.navigatable){N._removeCurrent();
Q.attr("aria-selected",false);
O.attr("aria-selected",true);
N._currentBullet=O;
}var J=N.dataSource.view()[M];
if(N.currentEventIndex===M){return;
}N._currentIndex=O.index();
L=N._forward=N.currentEventIndex<M;
N.currentEventIndex=M;
N.pane.updatePage(L,J,e(P,N._trackWrap));
if(N._forward){clearTimeout(N.navigateTimeOut);
N.navigateTimeOut=setTimeout(function(){N.pane.transition.moveTo({location:-N.pane.pages[2].element.width(),duration:800,ease:A.easeOutExpo});
},200);
}else{clearTimeout(N.navigateTimeOut);
N.navigateTimeOut=setTimeout(function(){N.pane.transition.moveTo({location:N.pane.pages[0].element.width(),duration:800,ease:A.easeOutExpo});
},200);
}N._repositionEvents();
},_navigateToView:function(K){var L=this;
var J=b(K.currentTarget).hasClass("k-timeline-arrow-right")?1:-1;
if(!L.trigger("navigate",{sender:L,action:J>0?"next":"previous"})&&!L._animationInProgress){L._animationInProgress=true;
if(J>0){L.next();
}else{L.previous();
}L._updateArrows();
}},_updateArrows:function(){var M=this;
var J=M.element.find(".k-timeline-arrow");
var K=J.filter(".k-timeline-arrow-left");
var L=J.filter(".k-timeline-arrow-right");
if(M._validateNavigation(false)){K.addClass("k-state-disabled");
}else{K.removeClass("k-state-disabled");
}if(M._validateNavigation(true)){L.addClass("k-state-disabled");
}else{L.removeClass("k-state-disabled");
}},_validateNavigation:function(J){var K=this;
var L=K._end||0;
if(J){return K._firstIndexInView+K.numOfEvents>=K.maxEvents;
}else{return Math.abs(L)<=1;
}},next:function(){var K=this;
var J=K.options;
if(!K._validateNavigation(true)&&J.orientation!=E){K._forward=true;
K._navigate();
}K._updateArrows();
},_navigate:function(){var T=this;
var O;
var N;
var L;
var V;
var Q=T._forward;
var M=f(this._trackWrap.find("."+x));
var R=Q?-b("."+x).width():b("."+x).width();
var J=T._currentIndex;
var K;
var P=T._firstIndexInView;
M=Q?M-100:M+100;
if(M>=0){M=0;
}T._end=M;
V=T._tackItemWidth;
K=Math.floor(J/T.numOfEvents);
if(Q){if(T.numOfEvents===1){O=P===0?1:P;
N=this._trackWrap.find("."+z).eq(O).nextAll(":not(."+m+")").first();
T._firstIndexInView=N.index();
}else{O=P+T.numOfEvents-1;
N=this._trackWrap.find("."+z).eq(O).nextAll(":not(."+m+")").first();
T._firstIndexInView=P+T.numOfEvents;
}}else{if(T.numOfEvents===1){O=P;
N=this._trackWrap.find("."+z).eq(O).prevAll(":not(."+m+")").first();
T._firstIndexInView=N.index();
}else{O=P;
N=this._trackWrap.find("."+z).eq(O).prevAll(":not(."+m+")").first();
N=N.length>0?N:this._trackWrap.find("."+z+":not(."+m+")").first();
T._firstIndexInView=P-T.numOfEvents<0?0:P-T.numOfEvents;
}}L=T.dataSource.view()[N.index("li[class='k-timeline-track-item']")];
this._trackWrap.find("."+x).css("transform","translateX("+M+"%)");
if(T._currentIndex!=N.index()){T.currentEventIndex=N.index("li[class='k-timeline-track-item']");
T._currentIndex=N.index();
T.pane.updatePage(T._forward,L,K===0&&!Q?N.find(".k-timeline-circle").offset().left+15:e(N.find(".k-timeline-circle"),T._trackWrap)+R);
clearTimeout(T.navigateTimeOut);
T.navigateTimeOut=setTimeout(function(){if(Q&&T.pane&&T.pane.pages.length>0){T.pane.transition.moveTo({location:-T.pane.pages[2].element.width(),duration:800,ease:A.easeOutExpo});
}else{T.pane.transition.moveTo({location:T.pane.pages[0].element.width(),duration:800,ease:A.easeOutExpo});
}},200);
}else{var S=this._trackWrap.find("."+x);
var U=function(){if(T.numOfEvents!=1){var X=T.pane.pages[1];
var W=e(N.find(".k-timeline-circle"),T._trackWrap);
X.setPageCallout("left",W/X.element.width()*100+"%");
}this._transition=null;
S.off("transitionend"+t,U);
};
S.on("transitionend"+t,U);
}},previous:function(){var K=this;
var J=K.options;
if(!K._validateNavigation(false)&&J.orientation!=E){K._forward=false;
K._navigate();
}K._updateArrows();
},expand:function(L){var K=b(L).find(".k-timeline-card");
var J=b(L).find(".k-card-body");
if(K.hasClass("k-collapsed")){q.fx(J).expand("vertical").stop().play();
K.removeClass("k-collapsed");
}},collapse:function(L){var K=b(L).find(".k-timeline-card");
var J=b(L).find(".k-card-body");
if(!K.hasClass("k-collapsed")){q.fx(J).expand("vertical").stop().reverse();
K.addClass("k-collapsed");
}},items:function(){return this.element.find("li[data-uid]");
},_resizeHandler:function(){var J=this;
clearTimeout(J.resizeTimeOut);
J.resizeTimeOut=setTimeout(function(){J._redrawEvents();
J.pane.repositionPages();
});
},redraw:function(){var J=this.options;
if(J.orientation!=E){this._redrawEvents();
this.pane.repositionPages();
}},_redrawEvents:function(){var K=this;
var J=Math.floor(K.element.find(".k-timeline-scrollable-wrap").width()/150);
var L;
if(K.element.width()<=480){K.element.addClass("k-timeline-mobile");
L=100;
K.numOfEvents=1;
K._tackItemWidth=L;
K.element.find("li.k-timeline-track-item").css("flex","1 0 "+L+"%");
K._repositionEvents();
}else{K.element.removeClass("k-timeline-mobile");
if(J!=K.numOfEvents){K.numOfEvents=J;
L=100/J;
c(K.element.find("li.k-timeline-track-item"),"flex","1 0 "+L+"%");
K._tackItemWidth=L;
K._repositionEvents();
}}K._updateArrows();
},_repositionEvents:function(){var Q=this;
var T=Q._tackItemWidth;
var O=Q._forward===null?Q.pane.pages[1]:Q._forward?Q.pane.pages[2]:Q.pane.pages[0];
var R=this._trackWrap.find("."+x);
var L=f(R);
var J;
var N;
var M;
var K;
if(Q.numOfEvents===1){N=Q.currentEventIndex*T;
}else{N=Q._currentIndex*T;
}if(O){if(Q.numOfEvents===1){O.setPageCallout("left","50%");
M=N;
c(R,"transform","translateX(-"+M+"%)");
Q._firstIndexInView=Q._currentIndex;
Q._updateArrows();
return;
}if(N>=Math.abs(L)+100){M=Math.abs(L)+(N-(Math.abs(L)+100)+T);
Q._end=-M;
c(R,"transform","translateX(-"+M+"%)");
Q._firstIndexInView=Q._currentIndex-Q.numOfEvents+1;
}else{if(N<=Math.abs(L)){M=N;
Q._end=-M;
c(R,"transform","translateX(-"+M+"%)");
Q._firstIndexInView=Q._currentIndex;
}else{K=R.find("li.k-timeline-track-item").eq(Q._currentIndex).find(".k-timeline-circle");
J=e(K,Q._trackWrap);
O.setPageCallout("left",J/O.element.width()*100+"%");
Q._firstIndexInView=Math.round(Math.abs(L)/T);
}}var P=this._trackWrap.find("."+x);
var S=function(){if(Q.numOfEvents!=1){var W=Q.pane.pages[1];
var V=Q._trackWrap.find("."+z).eq(Q._currentIndex);
var U=e(V.find(".k-timeline-circle"),Q._trackWrap);
W.setPageCallout("left",U/W.element.width()*100+"%");
}P.off("transitionend"+t,S);
};
P.on("transitionend"+t,S);
}Q._updateArrows();
},_initHorizontal:function(){var M=this;
var K=M._trackWrap.find(".k-timeline-circle").first();
var J=M.dataSource.view()[0];
var L=M.options.navigatable;
M.maxEvents=M._trackWrap.find(".k-timeline-track-item").length;
M._currentIndex=1;
M.pane.initPages();
M.pane.repositionPages();
M.pane.updatePage(M._forward,J,e(K,M._trackWrap));
M._updateArrows();
b(window).on("resize"+t,v(this,"_resizeHandler"));
M._trackWrap.on("click",".k-timeline-track-item:not(.k-timeline-flag-wrap)",v(this,"_setCurrentEvent"));
M._trackWrap.on("click",".k-timeline-arrow:not(.k-state-disabled)",v(this,"_navigateToView"));
if(L){M._trackWrap.find(".k-timeline-track-item.k-timeline-flag-wrap").attr("aria-hidden",true);
M._trackWrap.find(".k-timeline-track-item:not(.k-timeline-flag-wrap)").attr("role","option").attr("aria-selected",false).first().attr("aria-selected",true);
M._cardId=q.guid();
M._scrollableWrap.attr("role","listbox").attr("tabindex",0).on("focus"+t,function(){M.pane.pages[1].cardContainer.attr("id",M._cardId);
M._setCurrent(M._scrollableWrap.find(".k-timeline-track-item").eq(M._currentIndex));
}).on("focusout"+t,function(){M._removeCurrent();
}).on("keydown"+t,function(O){var P;
var N=M._currentBullet;
var Q;
var R;
if(M._transition){return;
}if(O.keyCode==r.LEFT){P=true;
R=N.prevAll(".k-timeline-track-item:not(.k-timeline-flag-wrap)").first();
if(R.length){Q=e(R,M._trackWrap);
if(Q<0||Q>R.parent().width()){M._transition=true;
M._removeCurrent();
M.previous();
M.open(R);
}else{M._setCurrent(R);
}}}if(O.keyCode==r.RIGHT){P=true;
R=N.nextAll(".k-timeline-track-item:not(.k-timeline-flag-wrap)").first();
if(R.length){Q=e(R,M._trackWrap);
if(Q<0||Q>R.parent().width()){M._transition=true;
M._removeCurrent();
M.next();
M.open(R);
}else{M._setCurrent(R);
}}}if(O.keyCode==r.SPACEBAR||O.keyCode==r.ENTER){P=true;
M._currentBullet.trigger("click");
}if(P){O.preventDefault();
}});
}},_setCurrent:function(K){if(!K){return;
}var J=q.guid();
var L=this;
L._removeCurrent();
L._scrollableWrap.attr("aria-activedescendant",J);
K.attr("id",J).addClass("k-state-focus");
K.siblings().removeAttr("aria-describedby");
if(K.attr("aria-selected")==="true"){K.attr("aria-describedby",L._cardId);
}L._currentBullet=K;
},_removeCurrent:function(){if(this._currentBullet){this._currentBullet.removeClass("k-state-focus").removeAttr("id").removeAttr("aria-describedby");
}this._scrollableWrap.removeAttr("aria-activedescendant");
},setDataSource:function(J){var L=this;
var K=L.options;
J=p(J)?{data:J}:J;
if(L.dataSource&&L._refresh){L.dataSource.unbind(h,L._refresh);
}else{this._refresh=v(L,"refresh");
}this.dataSource=j.create(J);
if(this.dataSource._sort===D){this.dataSource._sort=[{field:K.dataDateField,dir:"asc"}];
}L.dataSource.bind(h,L._refresh);
if(K.autoBind){this.dataSource.fetch();
}},refresh:function(){var L=this;
var K=L.options;
var J=this.dataSource.view();
if(K.orientation!=E){L._trackWrap.empty().remove();
L.element.find(".k-timeline-events-list").remove();
L._horizontal();
}L.currentEventIndex=0;
L._forward=null;
L._eventPage=1;
L._currentIndex=0;
L._firstIndexInView=0;
L.numOfEvents=null;
L._end=0;
L._initDataFieldMappings();
if(J.length){if(K.orientation==="horizontal"){L._renderContentHorizontal(J);
L._redrawEvents();
L._initHorizontal();
}else{L._renderContentVertical(J);
}}L.trigger("dataBound",{sender:L});
},destroy:function(){var J=this.options;
I.fn.destroy.call(this);
if(this.resizeTimeOut){clearTimeout(this.resizeTimeOut);
}if(this.navigateTimeOut){clearTimeout(this.navigateTimeOut);
}b(window).off("resize"+t,this._resizeHandler);
this.element.off();
if(J.orientation!=E){this.pane.destroy();
this._trackWrap.find("."+x).off();
this.element.find(".k-timeline-arrow").off();
this._trackWrap.off();
this.currentEventIndex=this.maxEvents=this.numOfEvents=this._currentIndex=this._eventPage=this._eventsList=this._eventsWrap=this.element=this._trackWrap=this.pane=null;
}q.destroy(this.element);
this._dataFieldMappings=this.element=null;
},options:{autoBind:true,name:"Timeline",orientation:"vertical",dateFormat:"MMM d, yyyy",showDateLabels:true,collapsibleEvents:false,alternatingMode:false,dataTitleField:"title",dataDateField:"date",dataSubtitleField:"subtitle",dataDescriptionField:"description",dataImagesField:"images",dataActionsField:"actions",dataImagesAltField:"altField",navigatable:false},events:["collapse","dataBound","expand","actionClick","change","navigate"]});
q.ui.plugin(y);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
