(function(b,a){a("kendo.timepicker",["kendo.popup","kendo.dateinput"],b);
}(function(){var a={id:"timepicker",name:"TimePicker",category:"web",description:"The TimePicker widget allows the end user to select a value from a list of predefined values or to type a new value.",depends:["popup"]};
(function(b,ar){var L=window.kendo,M=L.keys,ac=L.parseDate,c=L._activeElement,x=L._extractFormat,am=L.support,k=am.browser,aq=L.ui,au=aq.Widget,aa="open",n="close",l="change",Z=".kendoTimePicker",m="click"+Z,t="k-state-default",u="disabled",ag="readonly",O="li",ai="<span></span>",z="k-state-focused",E="k-state-hover",F="mouseenter"+Z+" mouseleave"+Z,T="mousedown"+Z,V=60000,U=86400000,ah="k-state-selected",al="k-state-disabled",j="aria-selected",g="aria-expanded",h="aria-hidden",f="aria-disabled",i="aria-readonly",e="aria-activedescendant",G="id",I=b.isArray,w=b.extend,ae=b.proxy,o=Date,q=/d{1,2}|E{1,6}|e{1,6}|c{3,6}|c{1}|M{1,5}|L{1,5}|y{1,4}|H{1,2}|h{1,2}|k{1,2}|K{1,2}|m{1,2}|a{1,5}|s{1,2}|S{1,3}|z{1,4}|Z{1,5}|x{1,5}|X{1,5}|G{1,5}|q{1,5}|Q{1,5}|"[^"]*"|'[^']*'/g,P="literal",S="month",D="hour",av="zone",at="weekday",af="quarter",p={G:"era",y:"year",q:af,Q:af,M:S,L:S,d:"day",E:at,c:at,e:at,h:D,H:D,k:D,K:D,m:"minute",s:"second",a:"dayperiod",x:av,X:av,z:av,Z:av},W={month:{type:"months",minLength:3,standAlone:"L"},quarter:{type:"quarters",minLength:3,standAlone:"q"},weekday:{type:"days",minLength:{E:0,c:3,e:3},standAlone:"c"},dayperiod:{type:"dayPeriods",minLength:0},era:{type:"eras",minLength:0}},ap=new o(),R='<div tabindex="0" class="k-timeselector"><div class="k-time-header"><span class="k-title"></span><button class="k-button k-flat k-time-now" title="Select now" aria-label="Select now">#=messages.now#</button></div><div class="k-time-list-container"><span class="k-time-highlight"></span></div></div>',X='<div class="k-time-footer k-action-buttons"><button class="k-button k-time-cancel" title="Cancel changes" aria-label="Cancel changes">#=messages.cancel#</button><button class="k-time-accept k-button k-primary" title="Set time" aria-label="Set time">#=messages.set#</button></div>',C='<span class="k-time-highlight"></span>';
ap=new Date(ap.getFullYear(),ap.getMonth(),ap.getDate(),0,0,0);
var ao=function(ax){var ay=this,aw=ax.id;
ay.options=ax;
ay._dates=[];
ay._createList(ax.timeView&&ax.timeView.list==="scroll");
if(aw){ay._timeViewID=aw+"_timeview";
ay._optionID=aw+"_option_selected";
ay.ul.attr(G,ay._timeViewID);
}ay._heightHandler=ae(ay._height,ay);
ay._popup();
};
ao.prototype={_createList:function(aw){if(aw){this._createScrollList();
}else{this._createClassicRenderingList();
}},_createScrollList:function(){this.list=b(L.template(R)(this.options)).on(T,ad);
if(!this.options.omitPopup){this.list.append(L.template(X)(this.options));
}this.ul=this.list.find(".k-time-list-container");
this.list.on("click"+Z,".k-time-header button.k-time-now",ae(this._nowClickHandler,this));
this.list.on("click"+Z,".k-time-footer button.k-time-cancel",ae(this._cancelClickHandler,this));
this.list.on("click"+Z,".k-time-footer button.k-time-accept",ae(this._setClickHandler,this));
this.list.on("mouseover"+Z,".k-time-list-wrapper",ae(this._mouseOverHandler,this));
this.list.on("keydown"+Z,ae(this._scrollerKeyDownHandler,this));
},_scrollerKeyDownHandler:function(ax){var aF=this,aB=ax.keyCode,aD=b(ax.currentTarget).find(".k-time-list-wrapper.k-state-focused"),aE=aF.list.find(".k-time-list-wrapper"),aC=aE.length,ay=aE.index(aD),az=L.support.isRtl(aF.wrapper),aA=A(aD.find(".k-item:visible:eq(0)")),aw=aD.find(".k-time-container.k-content.k-scrollable");
if(!aD.length){return;
}if(aB==M.RIGHT&&!az||aB==M.LEFT&&az){if(ay+1<aC){aF._focusList(aE.eq(ay+1));
}}else{if(aB==M.LEFT&&!az||aB==M.RIGHT&&az){if(ay-1>=0){aF._focusList(aE.eq(ay-1));
}}else{if(aB==M.UP){aw.scrollTop(aw.scrollTop()-aA);
ax.preventDefault();
}else{if(aB==M.DOWN){aw.scrollTop(aw.scrollTop()+aA);
ax.preventDefault();
}else{if(aB===M.ENTER){aF._setClickHandler();
}else{if(aB===M.ESC){aF._cancelClickHandler();
}}}}}}},_mouseOverHandler:function(aw){this._focusList(b(aw.currentTarget));
},_focusList:function(aw){this.list.find(".k-time-list-wrapper").removeClass(z);
aw.addClass(z);
this.list.focus();
this._scrollTop=aw.find(".k-scrollable").scrollTop();
},_createClassicRenderingList:function(){var aw=this;
aw.ul=b('<ul tabindex="-1" role="listbox" aria-hidden="true" unselectable="on" class="k-list k-reset"/>').css({overflow:am.kineticScrollNeeded?"":"auto"}).on(m,O,ae(aw._click,aw)).on("mouseenter"+Z,O,function(){b(this).addClass(E);
}).on("mouseleave"+Z,O,function(){b(this).removeClass(E);
});
aw.list=b("<div class='k-list-container k-list-scroller' unselectable='on'/>").append(aw.ul).on(T,ad);
aw.template=L.template('<li tabindex="-1" role="option" class="k-item" unselectable="on">#=data#</li>',{useWithBlock:false});
},current:function(ax){var ay=this,aw=ay.options.active;
if(ax!==ar){if(ay._current){ay._current.removeClass(ah);
if(ay._current&&ay._current.length){ay._current[0].removeAttribute(G);
ay._current[0].removeAttribute(j);
}}if(ax){ax=b(ax).addClass(ah).attr(G,ay._optionID).attr(j,true);
ay.scroll(ax[0]);
}ay._current=ax;
if(aw){aw(ax);
}}else{return ay._current;
}},_updateTitle:function(){this.list.find(".k-time-header > .k-title").html(L.toString(this._value,this.options.format,this.options.culture));
},applyValue:function(aF){if(!aF){return;
}var aA=H(this.options.format.toLowerCase(),"t");
var ay=aF.getHours();
var aB=aF.getMinutes();
var aD=aF.getSeconds();
var aw;
var az=this.ul.find('[data-index="1"]');
var aC=this.ul.find('[data-index="2"]');
var aE=this.ul.find('[data-index="3"]');
var ax=this.ul.find('[data-index="4"]');
if(aA){if(ay>=12){aw="PM";
if(ay>12){ay-=12;
}}else{aw="AM";
if(ay===0){ay=12;
}}}if(az.length){this._scrollListToPosition(az,ay);
}if(aC.length){this._scrollListToPosition(aC,aB);
}if(aE.length){this._scrollListToPosition(aE,aD);
}if(ax.length){this._scrollListToPosition(ax,aw);
}},_scrollListToPosition:function(ay,az){var aw=ay.find('.k-item[data-value="'+ab(az)+'"]');
var ax=A(aw);
ay.scrollTop(ay.find(".k-item:visible").index(aw)*ax);
},close:function(){this.popup.close();
},destroy:function(){var aw=this;
aw.ul.off(Z);
aw.list.off(Z);
if(this.popup){aw.popup.destroy();
}},open:function(){var ax=this;
var aw;
if(!ax.ul[0].firstChild||ax.ul.find("li").length<1){ax.bind();
}aw=ax.popup._hovered;
ax.popup._hovered=true;
ax.popup.open();
setTimeout(function(){ax.popup._hovered=aw;
},1);
if(ax._current){ax.scroll(ax._current[0]);
}},dataBind:function(ax){var aE=this,aC=aE.options,ay=aC.format,aF=L.toString,aD=aE.template,aB=ax.length,aA=0,aw,az="";
for(;
aA<aB;
aA++){aw=ax[aA];
if(K(aw,aC.min,aC.max)){az+=aD(aF(aw,ay,aC.culture));
}}aE._html(az);
},refresh:function(){var aN=this,aI=aN.options,aw=aI.format,aH=v(),ay=aH<0,aP=L.parseDate(aN._value),aJ=aP?Q(aP,aI.min):Q(new Date(),aI.min),aB=aI.min,aA=aI.max,aF=B(aB),aE=B(aA),aD=B(N(aI.interval)),aC=aI.interval*V,aO=L.toString,aM=aN.template,aK=aI.useValueToRender?aJ:new Date(+aI.min),aL=new o(aK),aG,az,ax="";
if(ay){az=(U+aH*V)/aC;
}else{az=U/aC;
}if(aF!=aE||aD===aE){if(aF>aE){aE+=U;
}az=(aE-aF)/aC+1;
}if(aI.timeView&&aI.timeView.list==="scroll"){ax=aN._createListContent(aj(aw));
}else{aN.getDatesInRange(aG,aE,aL,aA,aC,aK).forEach(function(aQ){ax+=aM(aO(aQ,aw,aI.culture));
});
}aN._html(ax);
},_updateListBottomOffset:function(ay){var ax=A(ay.find(".k-item:visible:eq(0)"));
var az=ay.outerHeight();
var aw=az-ax;
ay.find(".k-scrollable-placeholder").css({height:ay.find("ul").height()+aw});
},_updateHoursRange:function(){var aB=this;
var aw=this.ul.find('[data-index="1"]');
var az=this._minHours;
var ay=this._maxHours;
var ax=H(this.options.format.toLowerCase(),"t");
var aC;
var aD;
var aA=this._findSelectedValue(this.ul.find('[data-index="4"]'));
if(!aw.length){return;
}if(ax&&aA){if(aA==="AM"){if(az<12){aD=true;
}if(ay<12){aC=true;
}}else{if(aA==="PM"){if(az>12){aD=true;
az-=12;
}if(ay>12){aC=true;
ay-=12;
}}}aw.find(".k-item").each(function(aE,aF){aF=b(aF);
var aG=+aF.attr("data-value");
if(aB._validateMin&&aD&&aG<az||aB._validateMax&&aC&&aG>ay){aF.hide();
}else{aF.show();
}});
}else{aw.find(".k-item").each(function(aE,aF){aF=b(aF);
var aG=+aF.attr("data-value");
if(aB._validateMin&&aG<az||aB._validateMax&&aG>ay){aF.hide();
}else{aF.show();
}});
}this._updateListBottomOffset(aw);
},_updateMinutesRange:function(){var aE=this;
var aB=this.ul.find('[data-index="2"]');
var az=this._minHours;
var ax=this._maxHours;
var aA=this._minMinutes;
var ay=this._maxMinutes;
var aD=+this._findSelectedValue(this.ul.find('[data-index="1"]'));
var aw=H(this.options.format.toLowerCase(),"t");
var aC=this._findSelectedValue(this.ul.find('[data-index="4"]'));
if(aw&&aC==="PM"){aD+=12;
}if(!aB.length){return;
}aB.find(".k-item").each(function(aF,aG){aG=b(aG);
var aH=+aG.attr("data-value");
if(aE._validateMin&&aH<aA&&az&&aD===az||aE._validateMax&&aH>ay&&ax&&aD===ax){aG.hide();
}else{aG.show();
}});
this._updateListBottomOffset(aB);
},_updateSecondsRange:function(){var aC=this;
var aA=this.ul.find('[data-index="3"]');
var az=this._minSeconds;
var ax=this._minSeconds;
var ay=this._minMinutes;
var aw=this._maxMinutes;
var aB=+this._findSelectedValue(this.ul.find('[data-index="2"]'));
if(!aA.length){return;
}aA.find(".k-item").each(function(aD,aE){aE=b(aE);
var aF=+aE.attr("data-value");
if(aC._validateMin&&aF<az&&ay&&aB===ay||aC._validateMax&&aF>ax&&aw&&aB===aw){aE.hide();
}else{aE.show();
}});
this._updateListBottomOffset(aA);
},_updateDesignatorRange:function(){var ay=this._minHours;
var ax=this._maxHours;
var aw=this.ul.find('[data-index="4"]');
if(!aw.length){return;
}if(this._validateMin&&ay>=12){aw.find('.k-item[data-value="AM"]').hide();
}else{aw.find('.k-item[data-value="AM"]').show();
}if(this._validateMax&&ax<12){aw.find('.k-item[data-value="PM"]').hide();
}else{aw.find('.k-item[data-value="PM"]').show();
}},_updateRanges:function(){if(!this.options.specifiedRange){return;
}if(!this._currentlySelected){this._currentlySelected=new Date();
}var aw=this.options.max;
var ax=this.options.min;
if(this.options.validateDate){if(aw.getFullYear()===this._currentlySelected.getFullYear()&&aw.getMonth()===this._currentlySelected.getMonth()&&aw.getDate()===this._currentlySelected.getDate()){this._validateMax=true;
}else{this._validateMax=false;
}if(ax.getFullYear()===this._currentlySelected.getFullYear()&&ax.getMonth()===this._currentlySelected.getMonth()&&ax.getDate()===this._currentlySelected.getDate()){this._validateMin=true;
}else{this._validateMin=false;
}if(!this._validateMax&&!this._validateMin){return;
}}else{this._validateMax=true;
this._validateMin=true;
}this._minMinutes=ax.getMinutes();
this._maxMinutes=aw.getMinutes();
this._minHours=ax.getHours();
this._maxHours=aw.getHours();
this._minSeconds=ax.getSeconds();
this._maxSeconds=aw.getSeconds();
this._updateDesignatorRange();
this._updateHoursRange();
this._updateMinutesRange();
this._updateSecondsRange();
},addTranslate:function(){var aC=this.ul.find(".k-time-container.k-content.k-scrollable");
var az=aC.length;
var aA;
var ay;
var aB;
var aD;
var aE;
var aw;
for(var ax=0;
ax<az;
ax++){aA=aC.eq(ax);
ay=A(aA.find(".k-item:visible:eq(0)"));
aB=aA.outerHeight();
aD=(aB-ay)/2;
aE="translateY("+aD+"px)";
aw=aB-ay;
aA.find("ul").css({transform:aE,"-ms-transform":aE});
aA.find(".k-scrollable-placeholder").css({height:aA.find("ul").height()+aw});
aA.off(Z).on("click"+Z,".k-item",ae(this._itemClickHandler,this)).on("scroll"+Z,ae(this._listScrollHandler,this));
}},_nowClickHandler:function(){var aw=new Date();
this.value(aw);
this.options.change(L.toString(aw,this.options.format,this.options.culture));
},_cancelClickHandler:function(){this.value(this._value);
this.popup.close();
},_setClickHandler:function(){this._value=new Date(this._currentlySelected);
this.options.change(L.toString(this._currentlySelected,this.options.format,this.options.culture),true);
this.popup.close();
},_listScrollHandler:function(aw){var ay=this;
var ax=A(b(aw.currentTarget).find(".k-item:visible:eq(0)"));
if(ay._scrollingTimeout){clearTimeout(ay._scrollingTimeout);
}ay._scrollingTimeout=setTimeout(function(){if(aw.currentTarget.scrollTop%ax>1){aw.currentTarget.scrollTop+=ax-aw.currentTarget.scrollTop%ax;
}ay._scrollTop=aw.currentTarget.scrollTop;
ay._updateCurrentlySelected();
ay._updateRanges();
},100);
},_updateCurrentlySelected:function(){var ay=H(this.options.format.toLowerCase(),"t");
var ax=this.ul.find('[data-index="1"]');
var az=this.ul.find('[data-index="2"]');
var aA=this.ul.find('[data-index="3"]');
var aw=this.ul.find('[data-index="4"]');
var aC;
var aD;
var aE;
var aB;
if(!this.ul.is(":visible")){return;
}if(!this._currentlySelected){this._currentlySelected=this._value?new Date(this._value):new Date();
}if(ax.length){aC=+this._findSelectedValue(ax);
}if(az.length){aD=+this._findSelectedValue(az);
}if(aA.length){aE=+this._findSelectedValue(aA);
}if(aw.length){aB=this._findSelectedValue(aw);
}if(ay){if(aB=="PM"){aC+=12;
if(aC==24){aC=12;
}}if(aB==="AM"&&aC===12){aC=0;
}}if(aC!==ar){this._currentlySelected.setHours(aC);
}if(aD!==ar){this._currentlySelected.setMinutes(aD);
}if(aE!==ar){this._currentlySelected.setSeconds(aE);
}},_findSelectedValue:function(ax){var aw=y(ax.scrollTop(),A(ax.find(".k-item:visible:eq(0)")));
return ax.find(".k-item:visible").eq(aw).attr("data-value");
},_itemClickHandler:function(aw){var az=b(aw.originalEvent.currentTarget);
var ax=az.find(".k-item:visible").index(b(aw.currentTarget));
var ay=A(az.find(".k-item:visible:eq(0)"));
az.scrollTop(ax*ay);
},getDatesInRange:function(az,ay,aC,aw,ax,aB){var aA=[];
while(true){if(ay&&(B(aB)>=ay||aC.getDate()!=aB.getDate())){az=B(aB);
if(aC<aB){az+=U;
}if(az>ay){aB=new o(+aw);
}if(B(aB)>0){aA.push(new Date(aB));
}break;
}if(aC.getDate()!=aB.getDate()){break;
}aA.push(new Date(aB));
aB.setTime(aB.getTime()+ax);
if(!ay&&this.options.maxSet){break;
}}return aA;
},_createListContent:function(az){var ax=az.length;
var aA="";
var ay;
var aB;
for(var aw=0;
aw<ax;
aw++){ay=az[aw];
if(ay.type==="literal"){aA+=this._literalTemplate(ay);
}else{aB=this._getValues(ay,true);
aA+=this._itemTemplate(aB.values,ay,this.options.messages[ay.type],aB.index);
}}return aA;
},_itemTemplate:function(aC,az,aB,ax){var aA="";
var ay=aC.length;
aA+='<div class="k-time-list-wrapper" role="presentation"><span class="k-title">'+(aB||az.type)+'</span><div class="k-time-list"><div class="k-time-container k-content k-scrollable" role="presentation" data-index="'+ax+'"><ul class="k-reset">';
for(var aw=0;
aw<ay;
aw++){aA+='<li class="k-item" data-value="'+aC[aw]+'"><span>'+aC[aw]+"</span></li>";
}aA+='</ul><div class="k-scrollable-placeholder"></div></div></div></div>';
return aA;
},_getValues:function(ay,aA){var az=[];
var ax;
var aB=0;
var aw;
if(ay.type==="hour"){aB=1;
ax=1;
aw=ay.hour12?12:24;
}else{if(ay.type==="minute"){ax=2;
aw=59;
}else{if(ay.type==="second"){ax=3;
aw=59;
}}}for(;
aB<=aw;
aB++){az.push(aA?ab(aB):aB);
}return{values:az,index:ax};
},_literalTemplate:function(aw){var ax='<div class="k-time-separator">'+(aw.pattern===" tt"?":":aw.pattern)+"</div>";
if(aw.pattern===" tt"){ax+=this._itemTemplate(["AM","PM"],aw,"AM/PM",4);
}return ax;
},bind:function(){var ax=this,aw=ax.options.dates;
if(aw&&aw[0]){ax.dataBind(aw);
}else{ax.refresh();
}},_html:function(aw){var ax=this;
if(ax.options.timeView&&ax.options.timeView.list==="scroll"){aw=C+aw;
ax.ul.html(aw);
}else{ax.ul[0].innerHTML=aw;
ax.popup.unbind(aa,ax._heightHandler);
ax.popup.one(aa,ax._heightHandler);
ax.current(null);
ax.select(ax._value);
}},scroll:function(aA){if(!aA){return;
}var ax=this.list[0],aC=aA.offsetTop,aB=aA.offsetHeight,az=ax.scrollTop,ay=ax.clientHeight,aw=aC+aB;
if(az>aC){az=aC;
}else{if(aw>az+ay){az=aw-ay;
}}ax.scrollTop=az;
},select:function(ax){var aA=this,ay=aA.options,aw=aA._current,az;
if(ax instanceof Date){ax=L.toString(ax,ay.format,ay.culture);
}if(typeof ax==="string"){if(!aw||aw.text()!==ax){ax=b.grep(aA.ul[0].childNodes,function(aB){return(aB.textContent||aB.innerText)==ax;
});
ax=ax[0]?ax:null;
}else{ax=aw;
}}az=aA._distinctSelection(ax);
aA.current(az);
},_distinctSelection:function(ax){var az=this,aw,ay;
if(ax&&ax.length>1){aw=B(az._value);
ay=b.inArray(aw,az._dates);
ax=az.ul.children()[ay];
}return ax;
},setOptions:function(ax){var aw=this.options;
ax.min=ac(ax.min);
ax.max=ac(ax.max);
this.options=w(aw,ax,{active:aw.active,change:aw.change,close:aw.close,open:aw.open});
this.bind();
},toggle:function(){var aw=this;
if(aw.popup.visible()){aw.close();
}else{aw.open();
}},value:function(ax){var aw=this;
aw._value=ax;
if(aw.ul[0].firstChild){if(aw.options.timeView&&aw.options.timeView.list==="scroll"){aw.applyValue(ax);
}else{aw.select(ax);
}}},_click:function(ay){var aA=this,az=b(ay.currentTarget),aw=az.text(),ax=aA.options.dates;
if(ax&&ax.length>0){aw=ax[az.index()];
}if(!ay.isDefaultPrevented()){aA.select(az);
aA.options.change(aw,true);
aA.close();
}},_height:function(){var az=this;
var ax=az.list;
var ay=ax.parent(".k-animation-container");
var aw=az.options.height;
if(az.ul[0].children.length){ax.add(ay).show().height(az.ul[0].scrollHeight>aw?aw:"auto").hide();
}},_parse:function(aB){var aA=this,az=aA.options,ay=B(az.min)!=B(ap)?az.min:null,ax=B(az.max)!=B(ap)?az.max:null,aw=aA._value||ay||ax||ap;
if(aB instanceof o){return aB;
}aB=ac(aB,az.parseFormats,az.culture);
if(aB){aB=new o(aw.getFullYear(),aw.getMonth(),aw.getDate(),aB.getHours(),aB.getMinutes(),aB.getSeconds(),aB.getMilliseconds());
}return aB;
},_adjustListWidth:function(){var ay=this.list,aA=ay[0].style.width,aB=this.options.anchor,aw,ax,az=L._outerWidth;
if(!ay.data("width")&&aA){return;
}aw=window.getComputedStyle?window.getComputedStyle(aB[0],null):0;
ax=aw?parseFloat(aw.width):az(aB);
if(aw&&(k.mozilla||k.msie)){ax+=parseFloat(aw.paddingLeft)+parseFloat(aw.paddingRight)+parseFloat(aw.borderLeftWidth)+parseFloat(aw.borderRightWidth);
}aA=ax-(az(ay)-ay.width());
ay.css({fontFamily:aB.css("font-family"),width:aA}).data("width",aA);
},_popup:function(){var az=this,ax=az.list,ay=az.options,aw=ay.anchor;
if(!this.options.omitPopup){az.popup=new aq.Popup(ax,w(ay.popup,{anchor:aw,open:ay.open,close:ay.close,animation:ay.animation,isRtl:am.isRtl(ay.anchor),activate:function(){if(az.options.timeView&&az.options.timeView.list==="scroll"){az.addTranslate();
if(az._value){az.applyValue(az._value);
}else{az._updateCurrentlySelected();
}az._updateRanges();
az._focusList(az.list.find(".k-time-list-wrapper:eq(0)"));
}}}));
}else{ax.appendTo(ay.timeDiv);
}},move:function(ay){var aA=this,az=ay.keyCode,aB=aA.ul[0],aw=aA._current,ax=az===M.DOWN;
if(az===M.UP||ax){if(ay.altKey){aA.toggle(ax);
return;
}else{if(ax){aw=aw?aw[0].nextSibling:aB.firstChild;
}else{aw=aw?aw[0].previousSibling:aB.lastChild;
}}if(aw){aA.select(aw);
}aA.options.change(aA._current.text());
ay.preventDefault();
}else{if(az===M.ENTER||az===M.TAB||az===M.ESC){ay.preventDefault();
if(aw){aA.options.change(aw.text(),true);
}aA.close();
}}}};
function v(){var ay=new o(),aw=new o(ay.getFullYear(),ay.getMonth(),ay.getDate(),0,0,0),ax=new o(ay.getFullYear(),ay.getMonth(),ay.getDate(),12,0,0);
return -1*(aw.getTimezoneOffset()-ax.getTimezoneOffset());
}function B(aw){return aw.getHours()*60*V+aw.getMinutes()*V+aw.getSeconds()*1000+aw.getMilliseconds();
}function N(ax){var aw=new Date(2100,0,1);
aw.setMinutes(-ax);
return aw;
}function K(aB,ax,aw){var az=B(ax),ay=B(aw),aA;
if(!aB||az==ay){return true;
}aA=B(aB);
if(az>aA){aA+=U;
}if(ay<az){ay+=U;
}return aA>=az&&aA<=ay;
}ao.getMilliseconds=B;
L.TimeView=ao;
var an=au.extend({init:function(ay,aB){var aC=this,aF,aD,aw;
aB=aB||{};
aB.componentType=aB.componentType||"classic";
au.fn.init.call(aC,ay,aB);
ay=aC.element;
aB=aC.options;
aB.min=ac(ay.attr("min"))||ac(aB.min);
aB.max=ac(ay.attr("max"))||ac(aB.max);
if(+aB.max!=+ap||+aB.min!=+ap){this._specifiedRange=true;
}Y(aB);
aC._initialOptions=w({},aB);
aC._wrapper();
if(aC.options.timeView&&aC.options.timeView.list==="scroll"){aC.options.height=null;
}aC.timeView=aD=new ao(w({},aB,{id:ay.attr(G),anchor:aC.wrapper,format:aB.format,change:function(aH,aG){if(aG){aC._change(aH);
}else{ay.val(aH);
}},open:function(aG){if(aC.options.timeView&&aC.options.timeView.list!=="scroll"){aC.timeView._adjustListWidth();
}else{aC.timeView._updateTitle();
}if(aC.trigger(aa)){aG.preventDefault();
}else{ay.attr(g,true);
aF.attr(h,false);
}},close:function(aG){if(aC.trigger(n)){aG.preventDefault();
}else{ay.attr(g,false);
aF.attr(h,true);
}},active:function(aG){if(ay&&ay.length){ay[0].removeAttribute(e);
}if(aG){ay.attr(e,aD._optionID);
}},specifiedRange:aC._specifiedRange,maxSet:+aB.max!=+ap}));
aF=aD.ul;
aC._icon();
aC._reset();
try{ay[0].setAttribute("type","text");
}catch(ax){ay[0].type="text";
}ay.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":aD._timeViewID,autocomplete:"off"});
aw=ay.is("[disabled]")||b(aC.element).parents("fieldset").is(":disabled");
if(aw){aC.enable(false);
}else{aC.readonly(ay.is("[readonly]"));
}if(aB.dateInput){var aA=aB.min;
var az=aB.max;
var aE=new o();
if(B(aA)==B(az)){aA=new o(aE.getFullYear(),aE.getMonth(),aE.getDate(),0,0,0);
az=new o(aE.getFullYear(),aE.getMonth(),aE.getDate(),24,0,0);
}aC._dateInput=new aq.DateInput(ay,{culture:aB.culture,format:aB.format,min:aA,max:az,value:aB.value,interval:aB.interval});
}aC._old=aC._update(aB.value||aC.element.val());
aC._oldText=ay.val();
L.notify(aC);
},options:{name:"TimePicker",min:ap,max:ap,format:"",dates:[],parseFormats:[],value:null,interval:30,height:200,animation:{},dateInput:false,messages:{set:"Set",cancel:"Cancel",hour:"hour",minute:"minute",second:"second",millisecond:"millisecond",now:"Now"},componentType:"classic"},events:[aa,n,l],componentTypes:{classic:{timeView:{list:"list"}},modern:{timeView:{list:"scroll"}}},setOptions:function(aw){var ax=this;
var ay=ax._value;
au.fn.setOptions.call(ax,aw);
aw=ax.options;
Y(aw);
ax.timeView.setOptions(aw);
if(ay){ax.element.val(L.toString(ay,aw.format,aw.culture));
}},dataBind:function(aw){if(I(aw)){this.timeView.dataBind(aw);
}},_editable:function(az){var aB=this,ax=az.disable,aA=az.readonly,aw=aB._arrow.off(Z),ay=aB.element.off(Z),aC=aB._inputWrapper.off(Z);
if(aB._dateInput){aB._dateInput._unbindInput();
}if(!aA&&!ax){aC.addClass(t).removeClass(al).on(F,aB._toggleHover);
if(ay&&ay.length){ay[0].removeAttribute(u);
ay[0].removeAttribute(ag);
}ay.attr(f,false).attr(i,false).on("keydown"+Z,ae(aB._keydown,aB)).on("focusout"+Z,ae(aB._blur,aB)).on("focus"+Z,function(){aB._inputWrapper.addClass(z);
});
if(aB._dateInput){aB._dateInput._bindInput();
}aw.on(m,ae(aB._click,aB)).on(T,ad);
}else{aC.addClass(ax?al:t).removeClass(ax?t:al);
ay.attr(u,ax).attr(ag,aA).attr(f,ax).attr(i,aA);
}},readonly:function(aw){this._editable({readonly:aw===ar?true:aw,disable:false});
},enable:function(aw){this._editable({readonly:false,disable:!(aw=aw===ar?true:aw)});
},destroy:function(){var aw=this;
au.fn.destroy.call(aw);
aw.timeView.destroy();
aw.element.off(Z);
aw._arrow.off(Z);
aw._inputWrapper.off(Z);
if(aw._form){aw._form.off("reset",aw._resetHandler);
}},close:function(){this.timeView.close();
},open:function(){this.timeView.open();
},min:function(aw){return this._option("min",aw);
},max:function(aw){if(aw&&this.timeView){this.timeView.options.maxSet=true;
}else{if(this.timeView){this.timeView.options.maxSet=false;
}}return this._option("max",aw);
},value:function(ax){var aw=this;
if(ax===ar){return aw._value;
}aw._old=aw._update(ax);
if(aw._old===null){aw.element.val("");
}aw._oldText=aw.element.val();
},_blur:function(){var aw=this,ax=aw.element.val();
if(!(aw.options.timeView&&aw.options.timeView.list==="scroll")){aw.close();
}if(ax!==aw._oldText){aw._change(ax);
}aw._inputWrapper.removeClass(z);
},_click:function(){var ax=this,aw=ax.element;
ax.timeView.toggle();
if(!am.touch&&aw[0]!==c()){aw.trigger("focus");
}},_change:function(aA){var az=this,ax=az.element.val(),aw;
aA=az._update(aA);
aw=!L.calendar.isEqualDate(az._old,aA);
var aB=aw&&!az._typing;
var ay=ax!==az.element.val();
if(aB||ay){az.element.trigger(l);
}if(aw){az._old=aA;
az._oldText=az.element.val();
az.trigger(l);
}az._typing=false;
},_icon:function(){var ay=this,ax=ay.element,aw;
aw=ax.next("span.k-select");
if(!aw[0]){aw=b('<span unselectable="on" class="k-select" aria-label="select"><span class="k-icon k-i-clock"></span></span>').insertAfter(ax);
}ay._arrow=aw.attr({role:"button","aria-controls":ay.timeView._timeViewID});
},_keydown:function(aw){var ay=this,ax=aw.keyCode,az=ay.timeView,aA=ay.element.val();
if(az.popup.visible()||aw.altKey){az.move(aw);
if(ay._dateInput&&aw.stopImmediatePropagation){aw.stopImmediatePropagation();
}}else{if(ax===M.ENTER&&aA!==ay._oldText){ay._change(aA);
}else{ay._typing=true;
}}},_option:function(aw,az){var ay=this,ax=ay.options;
if(az===ar){return ax[aw];
}az=ay.timeView._parse(az);
if(!az){return;
}az=new o(+az);
ax[aw]=az;
ay.timeView.options[aw]=az;
ay.timeView.bind();
},_toggleHover:function(aw){b(aw.currentTarget).toggleClass(E,aw.type==="mouseenter");
},_update:function(aA){var ay=this,ax=ay.options,az=ay.timeView,aw=az._parse(aA);
if(!K(aw,ax.min,ax.max)){aw=null;
}ay._value=aw;
ay._currentlySelected=aw;
if(ay._dateInput&&aw){ay._dateInput.value(aw||aA);
}else{ay.element.val(L.toString(aw||aA,ax.format,ax.culture));
}az.value(aw);
return aw;
},_wrapper:function(){var ax=this,aw=ax.element,ay;
ay=aw.parents(".k-timepicker");
if(!ay[0]){ay=aw.wrap(ai).parent().addClass("k-picker-wrap k-state-default");
ay=ay.wrap(ai).parent();
}ay[0].style.cssText=aw[0].style.cssText;
ax.wrapper=ay.addClass("k-widget k-timepicker").addClass(aw[0].className);
aw.css({width:"100%",height:aw[0].style.height});
ax._inputWrapper=b(ay[0].firstChild);
},_reset:function(){var az=this,aw=az.element,ay=aw.attr("form"),ax=ay?b("#"+ay):aw.closest("form");
if(ax[0]){az._resetHandler=function(){az.value(aw[0].defaultValue);
az.max(az._initialOptions.max);
az.min(az._initialOptions.min);
};
az._form=ax.on("reset",az._resetHandler);
}}});
function Y(aw){var ax=aw.parseFormats;
aw.format=x(aw.format||L.getCulture(aw.culture).calendars.standard.patterns.t);
ax=I(ax)?ax:[ax];
ax.splice(0,0,aw.format);
aw.parseFormats=ax;
}function ad(aw){aw.preventDefault();
}function Q(aw,ax){return new Date(aw.getFullYear(),aw.getMonth(),aw.getDate(),ax.getHours(),ax.getMinutes(),ax.getSeconds(),ax.getMilliseconds());
}function s(ax,ay){var aw=ay.calendar;
var az;
if(typeof ax==="string"){if(aw.patterns[ax]){az=aw.patterns[ax];
}else{az=ax;
}}if(!az){az=aw.patterns.d;
}return az;
}function d(ax,ay){var aw=ax[ax.length-1];
if(aw&&aw.type==="LITERAL"){aw.pattern+=ay;
}else{ax.push({type:P,pattern:ay});
}}function J(aw){return aw==="h"||aw==="K";
}function r(aw){var ax;
if(aw<=3){ax="abbreviated";
}else{if(aw===4){ax="wide";
}else{if(aw===5){ax="narrow";
}else{if(aw===6){ax="short";
}}}}return ax;
}function ak(ay,ax,aw){aw=aw||0;
return ay.indexOf(ax,aw)===aw;
}function H(ay,ax){var aw=false;
if(ay.indexOf(ax)!==-1){aw=true;
}return aw;
}function aj(aw){var ax=L.culture();
var aE=s(aw,ax);
var aD=[];
var ay=q.lastIndex=0;
var az=q.exec(aE);
var aG;
var aH;
var aC;
var aB;
var aA;
var aF;
while(az){var aI=az[0];
if(ay<az.index){d(aD,aE.substring(ay,az.index));
}if(ak(aI,'"')||ak(aI,"'")){d(aD,aI);
}else{aG=aI[0];
aH=p[aG];
aC={type:aH,pattern:aI};
if(aH==="hour"){aC.hour12=J(aI);
}aB=W[aH];
if(aB){aA=typeof aB.minLength==="number"?aB.minLength:aB.minLength[aG];
aF=aI.length;
if(aF>=aA){aC.names={type:aB.type,nameType:r(aF),standAlone:aB.standAlone===aG};
}}aD.push(aC);
}ay=q.lastIndex;
az=q.exec(aE);
}if(ay<aE.length){d(aD,aE.substring(ay));
}return aD;
}function ab(ay,ax){var aw=String(ay);
while(aw.length<(ax||2)){aw="0"+aw;
}return aw;
}function y(ax,aw){return Math.max(Math.round(ax/aw),0);
}function A(aw){return aw.length&&aw[0].getBoundingClientRect().height;
}aq.plugin(an);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
