(function(b,a){a("kendo.validator",["kendo.core"],b);
}(function(){var a={id:"validator",name:"Validator",category:"web",description:"The Validator offers an easy way to do a client-side form validation.",depends:["core"]};
(function(b,F){var r=window.kendo,M=r.ui.Widget,w=".kendoValidator",o="k-invalid-msg",p=new RegExp(o,"i"),m="k-invalid",L="k-valid",J="k-validation-summary",n="k-text-error",t="k-messagebox k-messagebox-error",d="aria-invalid",c="aria-describedby",i=/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/i,G=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i,l=":input:not(:button,[type=submit],[type=reset],[disabled],[readonly])",g=":checkbox:not([disabled],[readonly])",x="[type=number],[type=range]",e="blur",u="name",j="form",v="novalidate",H="validate",f="change",I="validateInput",B=b.proxy,A=function(O,N){if(typeof N==="string"){N=new RegExp("^(?:"+N+")$");
}return N.test(O);
},s=function(N,P,O){var Q=N.val();
if(N.filter(P).length&&Q!==""){return A(Q,O);
}return true;
},k=function(N,O){if(N.length){return N[0].attributes[O]!=null;
}return false;
};
if(!r.ui.validator){r.ui.validator={rules:{},messages:{},allowSubmit:b.noop,validateOnInit:b.noop};
}function C(N){var P=r.ui.validator.ruleResolvers||{},Q={},O;
for(O in P){b.extend(true,Q,P[O].resolve(N));
}return Q;
}function h(N){return N.replace(/&amp/g,"&amp;").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");
}function y(N){N=(N+"").split(".");
if(N.length>1){return N[1].length;
}return 0;
}function z(N){if(b.parseHTML){return b(b.parseHTML(N));
}return b(N);
}function D(Q,R){var O=b(),P,N;
for(var S=0,T=Q.length;
S<T;
S++){P=Q[S];
if(p.test(P.className)){N=P.getAttribute(r.attr("for"));
if(N===R){O=O.add(P);
}}}return O;
}function q(O,N){if(!O){return false;
}if(typeof O.nodeName!=="string"||O.nodeName!=="LABEL"){return false;
}if(typeof O.getAttribute("for")!=="string"||typeof N.getAttribute("id")!=="string"){return false;
}if(O.getAttribute("for")!==N.getAttribute("id")){return false;
}return true;
}var E='<ul>#for(var i = 0; i < errors.length; i += 1){#<li><a data-field="#=errors[i].field#" href="\\#">#= errors[i].message #</a></li># } #</ul>';
var K=M.extend({init:function(N,O){var Q=this,P=C(N),R="["+r.attr("validate")+"!=false]";
O=O||{};
O.rules=b.extend({},r.ui.validator.rules,P.rules,O.rules);
O.messages=b.extend({},r.ui.validator.messages,P.messages,O.messages);
M.fn.init.call(Q,N,O);
Q._errorTemplate=r.template(Q.options.errorTemplate);
Q._summaryTemplate=r.template(Q.options.validationSummary.template||E);
if(Q.element.is(j)){Q.element.attr(v,v);
}Q._inputSelector=l+R;
Q._checkboxSelector=g+R;
Q._errors={};
Q._attachEvents();
Q._isValidated=false;
if(Q._validateOnInit()){Q.validate();
}},events:[H,f,I],options:{name:"Validator",errorTemplate:'<span class="k-form-error">#= message #</span>',messages:{required:"{0} is required",pattern:"{0} is not valid",min:"{0} should be greater than or equal to {1}",max:"{0} should be smaller than or equal to {1}",step:"{0} is not valid",email:"{0} is not valid email",url:"{0} is not valid URL",date:"{0} is not valid date",dateCompare:"End date should be greater than or equal to the start date"},rules:{required:function(O){var Q=!O.attr("name")&&!O.is(":checked"),P=O.attr("name")&&!this.element.find("input[name='"+O.attr("name")+"']:checked").length,N=O.filter("[type=checkbox]").length&&(Q||P),R=O.filter("[type=radio]").length&&!this.element.find("input[name='"+O.attr("name")+"']:checked").length,S=O.val();
return !(k(O,"required")&&(!S||S===""||S.length===0||N||R));
},pattern:function(N){if(N.filter("[type=text],[type=email],[type=url],[type=tel],[type=search],[type=password]").filter("[pattern]").length&&N.val()!==""){return A(N.val(),N.attr("pattern"));
}return true;
},min:function(N){if(N.filter(x+",["+r.attr("type")+"=number]").filter("[min]").length&&N.val()!==""){var O=parseFloat(N.attr("min"))||0,P=r.parseFloat(N.val());
return O<=P;
}return true;
},max:function(N){if(N.filter(x+",["+r.attr("type")+"=number]").filter("[max]").length&&N.val()!==""){var O=parseFloat(N.attr("max"))||0,P=r.parseFloat(N.val());
return O>=P;
}return true;
},step:function(O){if(O.filter(x+",["+r.attr("type")+"=number]").filter("[step]").length&&O.val()!==""){var P=parseFloat(O.attr("min"))||0,R=parseFloat(O.attr("step"))||1,S=parseFloat(O.val()),N=y(R),Q;
if(N){Q=Math.pow(10,N);
return Math.floor((S-P)*Q)%(R*Q)/Math.pow(100,N)===0;
}return(S-P)%R===0;
}return true;
},email:function(N){return s(N,"[type=email],["+r.attr("type")+"=email]",i);
},url:function(N){return s(N,"[type=url],["+r.attr("type")+"=url]",G);
},date:function(N){if(N.filter("[type^=date],["+r.attr("type")+"=date]").length&&N.val()!==""){return r.parseDate(N.val(),N.attr(r.attr("format")))!==null;
}return true;
}},validateOnBlur:true,validationSummary:false},_allowSubmit:function(){return r.ui.validator.allowSubmit(this.element,this.errors());
},_validateOnInit:function(){return r.ui.validator.validateOnInit(this.element);
},destroy:function(){M.fn.destroy.call(this);
this.element.off(w);
if(this.validationSummary){this.validationSummary.off(w);
this.validationSummary=null;
}},value:function(){if(!this._isValidated){return false;
}return this.errors().length===0;
},_submit:function(N){if(!this.validate()&&!this._allowSubmit()){N.stopPropagation();
N.stopImmediatePropagation();
N.preventDefault();
return false;
}return true;
},_checkElement:function(N){var O=this.value();
this.validateInput(N);
if(this.value()!==O){this.trigger(f);
}},_attachEvents:function(){var N=this;
if(N.element.is(j)){N.element.on("submit"+w,B(N._submit,N));
}if(N.options.validateOnBlur){if(!N.element.is(l)){N.element.on(e+w,N._inputSelector,function(){N._checkElement(b(this));
});
N.element.on("click"+w,N._checkboxSelector,function(){N._checkElement(b(this));
});
}else{N.element.on(e+w,function(){N._checkElement(N.element);
});
if(N.element.is(g)){N.element.on("click"+w,function(){N._checkElement(N.element);
});
}}}},validate:function(){var O;
var N;
var S=false;
var R;
var Q=this.value();
this._errors={};
if(!this.element.is(l)){var P=false;
O=this.element.find(this._inputSelector);
for(N=0,R=O.length;
N<R;
N++){if(!this.validateInput(O.eq(N))){P=true;
}}S=!P;
}else{S=this.validateInput(this.element);
}if(this.options.validationSummary&&!Q){this.showValidationSummary();
}this.trigger(H,{valid:S,errors:this.errors()});
if(Q!==S){this.trigger(f);
}return S;
},validateInput:function(Q){Q=b(Q);
this._isValidated=true;
var ac=this,ab=ac._errorTemplate,aa=ac._checkValidity(Q),ad=aa.valid,N="."+o,P=Q.attr(u)||"",T=ac._findMessageContainer(P).add(Q.next(N).filter(function(){var ag=b(this);
if(ag.filter("["+r.attr("for")+"]").length){return ag.attr(r.attr("for"))===P;
}return true;
})).addClass("k-hidden"),W=!ad?ac._extractMessage(Q,aa.key):"",V=!ad?z(ab({message:h(W),field:P})):"",ae=!Q.attr(d);
Q.removeAttr(d);
if(!ad){ac._errors[P]=W;
var U=T.attr("id");
ac._decorateMessageContainer(V,P);
if(U){V.attr("id",U);
}if(T.length!==0){T.replaceWith(V);
}else{var af=r.widgetInstance(Q);
var Y=Q.parent().get(0);
var X=Q.next().get(0);
var Z=Q.prev().get(0);
if(!af&&Q.is("[type=radio]")){af=r.widgetInstance(Q.closest(".k-radio-list"));
}if(!af&&Q.is("[type=checkbox]")){af=r.widgetInstance(Q.closest(".k-checkbox-list"));
}if(af&&af.wrapper){V.insertAfter(af.wrapper);
}else{if(Y&&Y.nodeName==="LABEL"){V.insertAfter(Y);
}else{if(X&&q(X,Q[0])){V.insertAfter(X);
}else{if(Z&&q(Z,Q[0])){V.insertAfter(Q);
}else{V.insertAfter(Q);
}}}}}V.removeClass("k-hidden");
Q.attr(d,true);
}else{delete ac._errors[P];
}if(ae!==ad){this.trigger(I,{valid:ad,input:Q,error:W,field:P});
}Q.toggleClass(m,!ad);
Q.toggleClass(L,ad);
if(r.widgetInstance(Q)){var S=r.widgetInstance(Q)._inputWrapper;
var R=r.widgetInstance(Q)._inputLabel;
if(S){S.toggleClass(m,!ad);
S.toggleClass(L,ad);
}if(R){R.toggleClass(n,!ad);
}}if(ae!==ad){var O=V?V.attr("id"):T.attr("id");
ac._associateMessageContainer(Q,O);
if(this.options.validationSummary&&this.options.validateOnBlur){this.showValidationSummary();
}}return ad;
},hideMessages:function(){var P=this,N="."+o,O=P.element;
P._disassociateMessageContainers();
if(!O.is(l)){O.find(N).addClass("k-hidden");
}else{O.next(N).addClass("k-hidden");
}},reset:function(){var P=this,N=P.element.find("."+m),O=P.element.find("."+n);
P._errors=[];
P.hideMessages();
P.hideValidationSummary();
N.removeAttr(d);
N.removeClass(m);
O.removeClass(n);
},_findMessageContainer:function(O){var R=r.ui.validator.messageLocators,S,N=b();
for(var P=0,Q=this.element.length;
P<Q;
P++){N=N.add(D(this.element[P].getElementsByTagName("*"),O));
}for(S in R){N=N.add(R[S].locate(this.element,O));
}return N;
},_decorateMessageContainer:function(N,O){var P=r.ui.validator.messageLocators,Q;
N.addClass(o).attr(r.attr("for"),O||"");
if(!N.attr("id")){N.attr("id",O+"-error");
}for(Q in P){P[Q].decorate(N,O);
}},_extractMessage:function(P,R){var S=this,N=S.options.messages[R],O=P.attr(u),Q;
if(!r.ui.Validator.prototype.options.messages[R]){Q=r.isFunction(N)?N(P):N;
}N=r.isFunction(N)?N(P):N;
return r.format(P.attr(r.attr(R+"-msg"))||P.attr("validationMessage")||Q||N||P.attr("title")||"",O,P.attr(R)||P.attr(r.attr(R)));
},_checkValidity:function(N){var P=this.options.rules,O;
for(O in P){if(!P[O].call(this,N)){return{valid:false,key:O};
}}return{valid:true};
},errors:function(){var P=[],O=this._errors,N;
for(N in O){P.push(O[N]);
}return P;
},setOptions:function(N){if(N.validationSummary){this.hideValidationSummary();
}r.deepExtend(this.options,N);
this.destroy();
this.init(this.element,this.options);
this._setEvents(this.options);
},_getInputNames:function(){var S=this,P=S.element.find(S._inputSelector),R=[];
for(var N=0,Q=P.length;
N<Q;
N++){var O=b(P[N]);
if(k(O,u)){if(R.indexOf(O.attr(u))===-1||O.closest(".k-checkbox-list").length===0&&O.closest(".k-radio-list").length===0){R.push(O.attr(u));
}}}return R;
},_associateMessageContainer:function(O,N){var P=r.getWidgetFocusableElement(O);
if(!P||!N){return;
}r.toggleAttribute(P,c,N);
},_disassociateMessageContainers:function(){var R=this,Q=R.element.find("."+m).addBack(),P,N;
for(var O=0;
O<Q.length;
O+=1){P=b(Q[O]);
if(P.is("input")){N=R._findMessageContainer(P.attr(u)).add(P.next("."+o)).attr("id");
R._associateMessageContainer(P,N);
}}},_errorsByName:function(){var R=this,O=R._getInputNames(),Q=[];
for(var N=0;
N<O.length;
N+=1){var P=O[N];
if(R._errors[P]){Q.push({field:P,message:R._errors[P]});
}}return Q;
},_renderSummary:function(){var R=this,P=this.options.validationSummary,O=this.element,Q=O.prev(),N;
if(P.container){N=b(P.container);
}else{if(Q&&Q.hasClass(J)){N=Q;
}else{N=b("<div />").insertBefore(R.element);
}}N.addClass([J,t].join(" "));
N.attr("role","alert");
N.on("click"+w,B(R._summaryClick,R));
return N;
},_summaryClick:function(N){N.preventDefault();
var R=this,O=b(N.target),Q=R.element.find("[name='"+O.data("field")+"']"),P;
if(!Q.length){return;
}P=r.getWidgetFocusableElement(Q);
if(P){P.focus();
}},showValidationSummary:function(){var Q=this,P=Q.validationSummary,N=Q._errorsByName(),O;
if(!P){P=Q.validationSummary=Q._renderSummary();
}O=z(Q._summaryTemplate({errors:N}));
P.html(O);
P.toggleClass("k-hidden",!N.length);
},hideValidationSummary:function(){var O=this,N=O.validationSummary;
if(!N){return;
}N.addClass("k-hidden");
}});
r.ui.plugin(K);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
