(function(b,a){a("kendo.window",["kendo.draganddrop","kendo.popup"],b);
}(function(){var a={id:"window",name:"Window",category:"web",description:"The Window widget displays content in a modal or non-modal HTML window.",depends:["draganddrop","popup"],features:[{id:"window-fx",name:"Animation",description:"Support for animation",depends:["fx"]}]};
(function(b,ai){var y=window.kendo,ak=y.ui.Widget,ad=y.ui.Popup.TabKeyTrap,m=y.ui.Draggable,v=b.isPlainObject,d=y._activeElement,T=y._outerWidth,S=y._outerHeight,W=b.proxy,r=b.extend,o=b.each,ae=y.template,e="body",af,Q=".kendoWindow",P=".kendoWindowModal",F=".k-window",I=".k-window-title",J=I+"bar",G=".k-window-content",x=".k-dialog-content",H=".k-resize-handle",C=".k-overlay",w="k-content-frame",K="k-i-loading",B="k-state-hover",A="k-state-focused",M="k-window-maximized",aj=":visible",t="hidden",h="cursor",R="open",c="activate",j="deactivate",f="close",X="refresh",N="minimize",L="maximize",ab="resizeStart",Z="resize",aa="resizeEnd",n="dragstart",l="dragend",z="kendoKeydown",p="error",U="overflow",i="original-overflow-rule",aq="zIndex",O=".k-window-actions .k-i-window-minimize,.k-window-actions .k-i-window-maximize",D=".k-i-pin",E=".k-i-unpin",V=D+","+E,ag=".k-window-titlebar .k-window-action",Y=".k-window-titlebar .k-i-refresh",an="WindowEventsHandled",ap=/^0[a-z]*$/i,u=y.isLocalUrl,ac={small:"k-window-sm",medium:"k-window-md",large:"k-window-lg"};
function k(ar){return typeof ar!="undefined";
}function ah(ar,at){return parseInt(ar.css(at),10)||0;
}function g(av,at,ar){var au;
if(av&&isNaN(av)&&av.toString().indexOf("px")<0){au=av;
}else{au=Math.max(Math.min(parseInt(av,10),ar===Infinity?ar:parseInt(ar,10)),at===-Infinity?at:parseInt(at,10));
}return au;
}function q(){return !this.type||this.type.toLowerCase().indexOf("script")>=0;
}function s(ar){var aw={top:ar.offsetTop,left:ar.offsetLeft},at=ar.offsetParent;
while(at){aw.top+=at.offsetTop;
aw.left+=at.offsetLeft;
var au=b(at).css("overflowX");
var av=b(at).css("overflowY");
if(av==="auto"||av==="scroll"){aw.top-=at.scrollTop;
}if(au==="auto"||au==="scroll"){aw.left-=at.scrollLeft;
}at=at.offsetParent;
}return aw;
}var al=ak.extend({init:function(au,az){var aC=this,aG,ay={},aD,at,aA,ax=false,ar,aE,aF,av,aB=az&&az.actions&&!az.actions.length,aw;
ak.fn.init.call(aC,au,az);
az=aC.options;
aA=az.position;
au=aC.element;
ar=az.content;
av=b(window);
if(aB){az.actions=[];
}aC.appendTo=b(az.appendTo);
aC.containment=az.draggable.containment?b(az.draggable.containment).first():null;
if(ar&&!v(ar)){ar=az.content={url:ar};
}au.find("script").filter(q).remove();
if(!au.parent().is(aC.appendTo)&&!aC.containment&&(aA.top===ai||aA.left===ai)){if(au.is(aj)){ay=au.offset();
ax=true;
}else{aD=au.css("visibility");
at=au.css("display");
au.css({visibility:t,display:""});
ay=au.offset();
au.css({visibility:aD,display:at});
}if(aA.top===ai){aA.top=ay.top;
}if(aA.left===ai){aA.left=ay.left;
}}if(!k(az.visible)||az.visible===null){az.visible=au.is(aj);
}aG=aC.wrapper=au.closest(F);
if(!au.is(".k-window-content")||!aG[0]){au.addClass("k-window-content");
aC._createWindow(au,az);
aG=aC.wrapper=au.closest(F);
aC.title(aC.options.title);
aC._dimensions();
}aC.minTop=aC.minLeft=-Infinity;
aC.maxTop=aC.maxLeft=Infinity;
aC._position();
if(ar){aC.refresh(ar);
}if(az.visible){aC.toFront();
}aE=aG.children(G);
if(az.visible&&az.modal){aC._overlay(aG.is(aj)).css({opacity:0.5});
}aG.on("mouseenter"+Q,ag,W(aC._buttonEnter,aC)).on("mouseleave"+Q,ag,W(aC._buttonLeave,aC)).on("click"+Q,"> "+ag,W(aC._windowActionHandler,aC)).on("keydown"+Q,aC,W(aC._keydown,aC)).on("focus"+Q,W(aC._focus,aC)).on("blur"+Q,W(aC._blur,aC));
aE.on("keydown"+Q,aC,W(aC._keydownContent,aC));
aF=aE.find("."+w)[0];
if(aF&&!av.data(an)){av.on("blur"+Q,function(){var aH=b(document.activeElement).parent(G);
if(aH.length){var aI=y.widgetInstance(aH);
aI._focus();
}});
av.on("focus"+Q,function(){b(G).not(x).each(function(aI,aH){y.widgetInstance(b(aH))._blur();
});
});
av.data(an,true);
}this._resizable();
this._draggable();
if(az.pinned&&this.wrapper.is(":visible")){aC.pin();
}aw=au.attr("id");
if(aw){aw=aw+"_wnd_title";
aG.children(J).children(I).attr("id",aw);
aE.attr({role:"dialog","aria-labelledby":aw});
}aG.add(aG.children(".k-resize-handle,"+J)).on("mousedown"+Q,W(aC.toFront,aC));
aC.touchScroller=y.touchScroller(au);
aC._resizeHandler=W(aC._onDocumentResize,aC);
aC._marker=y.guid().substring(0,8);
b(window).on("resize"+Q+aC._marker,aC._resizeHandler);
if(az.visible){aC.trigger(R);
aC.trigger(c);
}y.notify(aC);
if(this.options.modal){this._tabKeyTrap=new ad(aG);
this._tabKeyTrap.trap();
this._tabKeyTrap.shouldTrap=function(){return aG.data("isFront");
};
}},_buttonEnter:function(ar){b(ar.currentTarget).addClass(B);
},_buttonLeave:function(ar){b(ar.currentTarget).removeClass(B);
},_focus:function(){this.wrapper.addClass(A);
},_blur:function(){this.wrapper.removeClass(A);
},_dimensions:function(){var aE=this.wrapper;
var ay=this.options;
var aD=ay.width;
var au=ay.height;
var ax=ay.maxHeight;
var aA=ay.size;
var at=["minWidth","minHeight","maxWidth","maxHeight"];
var ar=aE.css("box-sizing")=="content-box";
var aw=ar?ah(aE,"border-left-width")+ah(aE,"border-right-width"):0;
var aB=ar?ah(aE,"border-top-width")+ah(aE,"border-bottom-width"):0;
var az=ar?ah(aE,"padding-top"):0;
if(this.containment&&!this._isPinned){this._updateBoundaries();
ay.maxHeight=Math.min(this.containment.height-(aB+az),ax);
ay.maxWidth=Math.min(this.containment.width-aw,ay.maxWidth);
}for(var av=0;
av<at.length;
av++){var aC=ay[at[av]]||"";
if(aC!=Infinity){aE.css(at[av],aC);
}}if(ax!=Infinity){this.element.css("maxHeight",ax);
}if(aD){aE.width(g(aD,ay.minWidth,ay.maxWidth));
}else{aE.width("");
}if(au){aE.height(g(au,ay.minHeight,ay.maxHeight));
}else{aE.height("");
}if(!ay.visible){aE.hide();
}if(aA&&ac[aA]){aE.addClass(ac[aA]);
}},_position:function(){var av=this.wrapper,au=this.options.position,at,ar;
this._updateBoundaries();
if(this.containment){au.top=au.top||0;
au.left=au.left||0;
at=au.top.toString().indexOf("%")>0?parseInt(this.containment.height*(parseFloat(au.top)/100),10):au.top;
ar=au.left.toString().indexOf("%")>0?parseInt(this.containment.width*(parseFloat(au.left)/100),10):au.left;
au.top=g(at,this.minTop,this.maxTop);
au.left=g(ar,this.minLeft,this.maxLeft);
}if(au.top===0){au.top=au.top.toString();
}if(au.left===0){au.left=au.left.toString();
}av.css({top:au.top||"",left:au.left||""});
},_updateBoundaries:function(){var ar=this.containment;
if(!ar){return null;
}ar.width=ar.innerWidth();
ar.height=ar.innerHeight();
if(parseInt(ar.width,10)>ar[0].clientWidth){ar.width-=y.support.scrollbar();
}if(parseInt(ar.height,10)>ar[0].clientHeight){ar.height-=y.support.scrollbar();
}ar.position=s(ar[0]);
if(this._isPinned){this.minTop=this.minLeft=-Infinity;
this.maxTop=this.maxLeft=Infinity;
}else{this.minTop=ar.scrollTop();
this.minLeft=ar.scrollLeft();
this.maxLeft=this.minLeft+ar.width-T(this.wrapper,true);
this.maxTop=this.minTop+ar.height-S(this.wrapper,true);
}},_animationOptions:function(au){var ar=this.options.animation;
var at={open:{effects:{}},close:{hide:true,effects:{}}};
return ar&&ar[au]||at[au];
},_resize:function(){y.resize(this.element.children());
},_resizable:function(){var ar=this.options.resizable;
var at=this.wrapper;
if(this.resizing){at.off("dblclick"+Q).children(H).remove();
this.resizing.destroy();
this.resizing=null;
}if(ar){at.on("dblclick"+Q,J,W(function(au){if(!b(au.target).closest(".k-window-action").length){this.toggleMaximization();
}},this));
o("n e s w se sw ne nw".split(" "),function(av,au){at.append(af.resizeHandle(au));
});
this.resizing=new ao(this);
}at=null;
},_draggable:function(){var ar=this.options.draggable;
if(this.dragging){this.dragging.destroy();
this.dragging=null;
}if(ar){this.dragging=new am(this,ar.dragHandle||J);
}},_actions:function(){var au=this.options;
var ar=au.actions;
var av=au.pinned;
var aw=this.wrapper.children(J);
var at=aw.find(".k-window-actions");
var ax=["maximize","minimize"];
ar=b.map(ar,function(ay){ay=av&&ay.toLowerCase()==="pin"?"unpin":ay;
return{name:ax.indexOf(ay.toLowerCase())>-1?"window-"+ay:ay};
});
at.html(y.render(af.action,ar));
},setOptions:function(at){var aw=this;
var av=aw.options.size;
var ar=JSON.parse(JSON.stringify(at));
r(at.position,aw.options.position);
r(at.position,ar.position);
ak.fn.setOptions.call(aw,at);
var au=aw.options.scrollable!==false;
aw.restore();
if(typeof at.title!=="undefined"){aw.title(at.title);
}aw.wrapper.removeClass(ac[av]);
aw._dimensions();
aw._position();
aw._resizable();
aw._draggable();
aw._actions();
if(typeof at.modal!=="undefined"){var ax=aw.options.visible!==false;
aw._enableDocumentScrolling();
aw._overlay(at.modal&&ax);
}aw.element.css(U,au?"":"hidden");
},events:[R,c,j,f,N,L,X,ab,Z,aa,n,l,z,p],options:{name:"Window",animation:{open:{effects:{zoom:{direction:"in"},fade:{direction:"in"}},duration:350},close:{effects:{zoom:{direction:"out",properties:{scale:0.7}},fade:{direction:"out"}},duration:350,hide:true}},title:"",actions:["Close"],autoFocus:true,modal:false,size:"auto",resizable:true,draggable:true,minWidth:90,minHeight:50,maxWidth:Infinity,maxHeight:Infinity,pinned:false,scrollable:true,position:{},content:null,visible:null,height:null,width:null,appendTo:"body",isMaximized:false,isMinimized:false},_closable:function(){return b.inArray("close",b.map(this.options.actions,function(ar){return ar.toLowerCase();
}))>-1;
},_keydownContent:function(ar){var av=this,au=y.keys,at=ar.keyCode;
if(at==au.ESC&&av._closable()){ar.stopPropagation();
av._close(false);
}},_keydown:function(at){var aE=this,aD=aE.options,az=y.keys,ay=at.keyCode,aG=aE.wrapper,aC,av,ar=10,aw=aD.isMaximized,ax=aD.isMinimized,aB,aA,aF,au;
if(ay==az.ESC&&aE._closable()){at.stopPropagation();
aE._close(false);
}if(at.target!=at.currentTarget||aE._closing){return;
}if(at.altKey&&ay==82){aE.refresh();
}if(at.altKey&&ay==80){if(aE.options.pinned){aE.unpin();
}else{aE.pin();
}}if(at.altKey&&ay==az.UP){if(ax){aE.restore();
aE.wrapper.focus();
}else{if(!aw){aE.maximize();
aE.wrapper.focus();
}}}else{if(at.altKey&&ay==az.DOWN){if(!ax&&!aw){aE.minimize();
aE.wrapper.focus();
}else{if(aw){aE.restore();
}}}}aC=y.getOffset(aG);
if(aE.containment&&!aE._isPinned){aC=aE.options.position;
}if(aD.draggable&&!at.ctrlKey&&!at.altKey&&!aw){aE._updateBoundaries();
if(ay==az.UP){aC.top=g(aC.top-ar,aE.minTop,aE.maxTop);
av=aG.css("top",aC.top);
}else{if(ay==az.DOWN){aC.top=g(aC.top+ar,aE.minTop,aE.maxTop);
av=aG.css("top",aC.top);
}else{if(ay==az.LEFT){aC.left=g(aC.left-ar,aE.minLeft,aE.maxLeft);
av=aG.css("left",aC.left);
}else{if(ay==az.RIGHT){aC.left=g(aC.left+ar,aE.minLeft,aE.maxLeft);
av=aG.css("left",aC.left);
}}}}}if(aD.resizable&&at.ctrlKey&&!aw&&!ax){if(ay==az.UP){av=true;
aA=aG.height()-ar;
}else{if(ay==az.DOWN){av=true;
if(aE.containment&&!aE._isPinned){aA=Math.min(aG.height()+ar,aE.containment.height-aC.top-ah(aG,"padding-top")-ah(aG,"borderBottomWidth")-ah(aG,"borderTopWidth"));
}else{aA=aG.height()+ar;
}}}if(ay==az.LEFT){av=true;
aB=aG.width()-ar;
}else{if(ay==az.RIGHT){av=true;
if(aE.containment&&!aE._isPinned){aB=Math.min(aG.width()+ar,aE.containment.width-aC.left-ah(aG,"borderLeftWidth")-ah(aG,"borderRightWidth"));
}else{aB=aG.width()+ar;
}}}if(av){aF=g(aB,aD.minWidth,aD.maxWidth);
au=g(aA,aD.minHeight,aD.maxHeight);
if(!isNaN(aF)){aG.width(aF);
aE.options.width=aF+"px";
}if(!isNaN(au)){aG.height(au);
aE.options.height=au+"px";
}aE.resize();
}}if(av){at.preventDefault();
}},_overlay:function(at){var ar=this.containment?this.containment.children(C):this.appendTo.children(C),au=this.wrapper;
if(!ar.length){ar=b("<div class='k-overlay' />");
}ar.insertBefore(au[0]).toggle(at).css(aq,parseInt(au.css(aq),10)-1);
if(this.options.modal.preventScroll&&!this.containment){this._stopDocumentScrolling();
}return ar;
},_actionForIcon:function(ar){var at=/\bk-i(-\w+)+\b/.exec(ar[0].className)[0];
return{"k-i-close":"_close","k-i-window-maximize":"maximize","k-i-window-minimize":"minimize","k-i-window-restore":"restore","k-i-refresh":"refresh","k-i-pin":"pin","k-i-unpin":"unpin"}[at];
},_windowActionHandler:function(at){if(this._closing){return;
}var au=b(at.target).closest(".k-window-action").find(".k-icon");
var ar=this._actionForIcon(au);
if(ar){at.preventDefault();
this[ar]();
return false;
}},_modals:function(){var ar=this;
var at=b(F).filter(function(){var au=b(this);
var av=ar._object(au);
var aw=av&&av.options;
return aw&&aw.modal&&aw.visible&&aw.appendTo===ar.options.appendTo&&au.is(aj);
}).sort(function(au,av){return +b(au).css("zIndex")-+b(av).css("zIndex");
});
ar=null;
return at;
},_object:function(at){var ar=at.children(G);
var au=y.widgetInstance(ar);
if(au){return au;
}return ai;
},center:function(){var ay=this,av=ay.options.position,az=ay.wrapper,ar=b(window),ax=0,aw=0,au,at;
if(ay.options.isMaximized){return ay;
}if(ay.options.pinned&&!ay._isPinned){ay.pin();
}if(!ay.options.pinned){ax=ar.scrollTop();
aw=ar.scrollLeft();
}if(this.containment&&!ay.options.pinned){au=this.minTop+(this.maxTop-this.minTop)/2;
at=this.minLeft+(this.maxLeft-this.minLeft)/2;
}else{ay._scrollIsAppended=true;
at=aw+Math.max(0,(ar.width()-az.width())/2);
au=ax+Math.max(0,(ar.height()-az.height()-ah(az,"paddingTop"))/2);
}az.css({left:at,top:au});
av.top=au;
av.left=at;
return ay;
},title:function(au){var at=this,ax,ar=true,ay=at.wrapper,av=ay.children(J),aw=av.children(I);
if(!arguments.length){return aw.html();
}if(b.isPlainObject(au)){ax=typeof au.text!=="undefined"?au.text:"";
ar=au.encoded!==false;
}else{ax=au;
}if(ax===false){ay.addClass("k-window-titleless");
ay.css("padding-top",0);
av.remove();
}else{if(!av.length){ay.prepend(af.titlebar({title:ar?y.htmlEncode(ax):ax}));
at._actions();
av=ay.children(J);
}else{aw.html(ar?y.htmlEncode(ax):ax);
}}at.options.title=ax;
return at;
},content:function(au,at){var ar=this.wrapper.children(G),av=ar.children(".km-scroll-container");
ar=av[0]?av:ar;
if(!k(au)){return ar.html();
}this.angular("cleanup",function(){return{elements:ar.children()};
});
y.destroy(this.element.children());
ar.empty().html(au);
this.angular("compile",function(){var aw=[];
for(var ax=ar.length;
--ax>=0;
){aw.push({dataItem:at});
}return{elements:ar.children(),data:aw};
});
return this;
},open:function(){var aA=this,aB=aA.wrapper,av=aA.options,az=this._animationOptions("open"),at=aB.children(G),ax,aw,ar=this.containment&&!aA._isPinned,au=ar?this.containment:b(document);
if(!aA.trigger(R)){if(aA._closing){aB.kendoStop(true,true);
}aA._closing=false;
aA.toFront();
if(av.autoFocus){aA.wrapper.focus();
}av.visible=true;
if(av.modal){aw=!!aA._modals().length;
ax=aA._overlay(aw);
ax.kendoStop(true,true);
if(az.duration&&y.effects.Fade&&!aw){var ay=y.fx(ax).fadeIn();
ay.duration(az.duration||0);
ay.endValue(0.5);
ay.play();
}else{ax.css("opacity",0.5);
}ax.show();
b(window).on("focus"+P,function(){if(aB.data("isFront")&&!b(document.activeElement).closest(aB).length){aA.wrapper.focus();
}});
}if(!aB.is(aj)){at.css(U,t);
aA.wrapper.find(ag).addClass("k-flat");
aB.show().kendoStop().kendoAnimate({effects:az.effects,duration:az.duration,complete:W(this._activate,this)});
}}if(av.isMaximized){aA._containerScrollTop=au.scrollTop();
aA._containerScrollLeft=au.scrollLeft();
aA._stopDocumentScrolling();
}if(this.options.pinned&&!this._isPinned){this.pin();
}return aA;
},_activate:function(){var ar=this.options.scrollable!==false;
if(this.options.autoFocus){this.wrapper.focus();
}this.element.css(U,ar?"":"hidden");
y.resize(this.element.children());
this.trigger(c);
},_removeOverlay:function(ay){var au=this._modals();
var av=this.options;
var at=av.modal&&!au.length;
var aw=av.modal?this._overlay(true):b(ai);
var ar=this._animationOptions("close");
if(at){if(!ay&&ar.duration&&y.effects.Fade){var ax=y.fx(aw).fadeOut();
ax.duration(ar.duration||0);
ax.startValue(0.5);
ax.play();
}else{this._overlay(false).remove();
}if(av.modal.preventScroll){this._enableDocumentScrolling();
}}else{if(au.length){this._object(au.last())._overlay(true);
if(av.modal.preventScroll){this._stopDocumentScrolling();
}}}},_close:function(ay){var az=this,aA=az.wrapper,aw=az.options,ax=this._animationOptions("open"),av=this._animationOptions("close"),ar=this.containment&&!az._isPinned,au=ar?this.containment:b(document),at;
if(az._closing){return;
}at=az.trigger(f,{userTriggered:!ay});
az._closing=!at;
if(aA.is(aj)&&!at){aw.visible=false;
b(F).each(function(aD,aC){var aB=b(aC).children(G);
if(aC!=aA&&aB.find("> ."+w).length>0){aB.children(C).remove();
}});
this._removeOverlay();
az.wrapper.find(ag).removeClass("k-flat");
aA.kendoStop().kendoAnimate({effects:av.effects||ax.effects,reverse:av.reverse===true,duration:av.duration,complete:W(this._deactivate,this)});
b(window).off(P);
}if(az.options.isMaximized){az._enableDocumentScrolling();
if(az._containerScrollTop&&az._containerScrollTop>0){au.scrollTop(az._containerScrollTop);
}if(az._containerScrollLeft&&az._containerScrollLeft>0){au.scrollLeft(az._containerScrollLeft);
}}if(az.options.iframe){az.wrapper.blur();
}},_deactivate:function(){var at=this;
at.wrapper.hide().css("opacity","");
at.trigger(j);
if(at.options.modal){var ar=at._object(at._modals().last());
if(ar){ar.toFront();
}}},close:function(){this._close(true);
return this;
},_actionable:function(ar){return b(ar).is(ag+","+ag+" .k-icon,:input,a");
},_shouldFocus:function(au){var ar=d(),at=this.wrapper;
return this.options.autoFocus&&!b(ar).is(at)&&!this._actionable(au)&&(!at.find(ar).length||!at.find(au).length);
},toFront:function(au){var az=this,aB=az.wrapper,at=aB[0],ar=az.containment&&!az._isPinned,av=this._animationOptions("open"),aC=+aB.css(aq),aw=aC,ay=au&&au.target||null;
b(F).each(function(aF,aE){var aG=b(aE),aH=aG.css(aq),aD=aG.children(G);
if(!isNaN(aH)){aC=Math.max(+aH,aC);
}aB.data("isFront",aE==at);
if(aE!=at&&aD.find("> ."+w).length>0){aD.append(af.overlay);
}});
if(!aB[0].style.zIndex||aw<aC){aB.css(aq,aC+2);
}az.element.find("> .k-overlay").remove();
if(az._shouldFocus(ay)){setTimeout(function(){az.wrapper.focus();
},av?av.duration:0);
var ax=ar?az.containment.scrollTop():b(window).scrollTop(),aA=parseInt(aB.position().top,10);
if(!az.options.pinned&&aA>0&&aA<ax){if(ax>0){b(window).scrollTop(aA);
}else{aB.css("top",ax);
}}}aB=null;
return az;
},toggleMaximization:function(){if(this._closing){return this;
}return this[this.options.isMaximized?"restore":"maximize"]();
},restore:function(){var ax=this;
var au=ax.options;
var at=au.minHeight;
var av=ax.restoreOptions;
var aw;
var ar=ax.containment&&!ax._isPinned?ax.containment:b(document);
if(!au.isMaximized&&!au.isMinimized){return ax;
}if(at&&at!=Infinity){ax.wrapper.css("min-height",at);
}if(av&&!au.isMaximized){av.height=g(av.height,ax.options.minHeight,ax.options.maxHeight);
aw=au.position.top+parseInt(av.height,10)>ax.maxTop;
if(aw){au.position.top=g(au.position.top,ax.minTop,ax.maxTop-parseInt(av.height,10));
r(av,{left:au.position.left,top:au.position.top});
}}ax.wrapper.css({position:au.pinned?"fixed":"absolute",left:av.left,top:av.top,width:av.width,height:av.height}).removeClass(M).find(".k-window-content,.k-resize-handle").show().end().find(".k-window-titlebar .k-i-window-restore").parent().remove().end().end().find(O).parent().show().end().end().find(V).parent().show();
if(au.isMaximized){ax.wrapper.find(".k-i-window-maximize").parent().focus();
}else{if(au.isMinimized){ax.wrapper.find(".k-i-window-minimize").parent().focus();
}}ax.options.width=av.width;
ax.options.height=av.height;
if(!ax.options.modal.preventScroll){ax._enableDocumentScrolling();
}if(ax._containerScrollTop&&ax._containerScrollTop>0){ar.scrollTop(ax._containerScrollTop);
}if(ax._containerScrollLeft&&ax._containerScrollLeft>0){ar.scrollLeft(ax._containerScrollLeft);
}au.isMaximized=au.isMinimized=false;
ax.wrapper.removeAttr("aria-labelled-by");
ax.resize();
return ax;
},_sizingAction:function(ar,at){var aw=this,ax=aw.wrapper,av=ax[0].style,au=aw.options;
if(au.isMaximized||au.isMinimized){return aw;
}aw.restoreOptions={width:av.width,height:av.height};
ax.children(H).hide().end().children(J).find(O).parent().hide().eq(0).before(af.action({name:"window-restore"}));
at.call(aw);
aw.wrapper.children(J).find(V).parent().toggle(ar!=="maximize");
aw.trigger(ar);
ax.find(".k-i-window-restore").parent().focus();
return aw;
},maximize:function(){this._sizingAction("maximize",function(){var av=this,aw=av.wrapper,ar=this.containment&&!av._isPinned,au=aw.position(),at=b(document);
r(av.restoreOptions,{left:au.left+(ar?this.containment.scrollLeft():0),top:au.top+(ar?this.containment.scrollTop():0)});
this._containerScrollTop=ar?this.containment.scrollTop():at.scrollTop();
this._containerScrollLeft=ar?this.containment.scrollLeft():at.scrollLeft();
av._stopDocumentScrolling();
aw.css({top:ar?this.containment.scrollTop():0,left:ar?this.containment.scrollLeft():0,position:ar?"absolute":"fixed"}).addClass(M);
av.options.isMaximized=true;
av._onDocumentResize();
});
return this;
},_stopDocumentScrolling:function(){var av=this;
var au=av.containment;
if(au&&!av._isPinned){av._storeOverflowRule(au);
au.css(U,t);
av.wrapper.css({maxWidth:au.innerWidth(),maxHeight:au.innerHeight()});
return;
}var ar=b("body");
av._storeOverflowRule(ar);
ar.css(U,t);
var at=b("html");
av._storeOverflowRule(at);
at.css(U,t);
},_enableDocumentScrolling:function(){var at=this;
var ar=at.containment;
if(ar&&!at._isPinned){at._restoreOverflowRule(ar);
at.wrapper.css({maxWidth:ar.width,maxHeight:ar.height});
return;
}at._restoreOverflowRule(b(document.body));
at._restoreOverflowRule(b("html"));
},_storeOverflowRule:function(ar){if(this._isOverflowStored(ar)){return;
}var at=ar.get(0).style.overflow;
if(typeof at==="string"){ar.data(i,at);
}},_isOverflowStored:function(ar){return typeof ar.data(i)==="string";
},_restoreOverflowRule:function(ar){var at=ar.data(i);
if(at!==null&&at!==ai){ar.css(U,at);
ar.removeData(i);
}else{ar.css(U,"");
}},isMaximized:function(){return this.options.isMaximized;
},minimize:function(){this._sizingAction("minimize",function(){var ar=this;
ar.wrapper.css({height:"",minHeight:""});
ar.element.hide();
ar.options.isMinimized=true;
});
this.wrapper.attr("aria-labelled-by",this.element.attr("aria-labelled-by"));
this._updateBoundaries();
return this;
},isMinimized:function(){return this.options.isMinimized;
},pin:function(){var av=this,ax=b(window),ay=av.wrapper,at=av.options,au=at.position,aw=this.containment?s(ay[0]).top+ah(this.containment,"borderTopWidth"):ah(ay,"top"),ar=this.containment?s(ay[0]).left+ah(this.containment,"borderLeftWidth"):ah(ay,"left");
if(!av.options.isMaximized){au.top=aw;
au.left=ar;
if(av._scrollIsAppended&&(!this.containment||this.containment.css("position")!=="fixed")){au.top-=ax.scrollTop();
au.left-=ax.scrollLeft();
av._scrollIsAppended=false;
}ay.css(r(au,{position:"fixed"}));
ay.children(J).find(D).addClass("k-i-unpin").removeClass("k-i-pin");
av._isPinned=true;
av.options.pinned=true;
if(this.containment){at.maxWidth=at.maxHeight=Infinity;
ay.css({maxWidth:"",maxHeight:""});
}}},unpin:function(){var aw=this,ay=b(window),az=aw.wrapper,au=aw.options,av=aw.options.position,ar=aw.containment,ax=parseInt(az.css("top"),10)+ay.scrollTop(),at=parseInt(az.css("left"),10)+ay.scrollLeft();
if(!aw.options.isMaximized){aw._isPinned=false;
aw._scrollIsAppended=true;
aw.options.pinned=false;
if(ar){aw._updateBoundaries();
au.maxWidth=Math.min(ar.width,au.maxWidth);
au.maxHeight=Math.min(ar.height-ah(az,"padding-top"),au.maxHeight);
az.css({maxWidth:au.maxWidth,maxHeight:au.maxHeight});
if(ax<ar.position.top){ax=aw.minTop;
}else{if(ax>ar.position.top+ar.height){ax=aw.maxTop;
}else{ax=ax+ar.scrollTop()-(ar.position.top+ah(ar,"border-top-width"));
}}if(at<ar.position.left){at=aw.minLeft;
}else{if(at>ar.position.left+ar.width){at=aw.maxLeft;
}else{at=at+ar.scrollLeft()-(ar.position.left+ah(ar,"border-left-width"));
}}}av.top=g(ax,aw.minTop,aw.maxTop);
av.left=g(at,aw.minLeft,aw.maxLeft);
az.css(r(av,{position:""}));
az.children(J).find(E).addClass("k-i-pin").removeClass("k-i-unpin");
}},_onDocumentResize:function(){var ax=this,aA=ax.wrapper,az=b(window),aB=y.support.zoomLevel(),ar=aA.css("box-sizing")=="content-box",ay,at;
if(!ax.options.isMaximized){return;
}var au=ar?ah(aA,"border-left-width")+ah(aA,"border-right-width"):0;
var aw=ar?ah(aA,"border-top-width")+ah(aA,"border-bottom-width"):0;
var av=ar?ah(aA,"padding-top"):0;
if(ax.containment&&!ax._isPinned){ay=ax.containment.innerWidth()-au;
at=ax.containment.innerHeight()-(aw+av);
}else{ay=az.width()/aB-au;
at=az.height()/aB-(aw+av);
}aA.css({width:ay,height:at});
ax.options.width=ay;
ax.options.height=at;
ax.resize();
},refresh:function(av){var ax=this,au=ax.options,ar=b(ax.element),at,aw,ay;
if(!v(av)){av={url:av};
}av=r({},au.content,av);
aw=k(au.iframe)?au.iframe:av.iframe;
ay=av.url;
if(ay){if(!k(aw)){aw=!u(ay);
}if(!aw){ax._ajaxRequest(av);
}else{at=ar.find("."+w)[0];
if(at){at.src=ay||at.src;
}else{ar.html(af.contentFrame(r({},au,{content:av})));
}ar.find("."+w).unbind("load"+Q).on("load"+Q,W(this._triggerRefresh,this));
}}else{if(av.template){ax.content(ae(av.template)({}));
}ax.trigger(X);
}ar.toggleClass("k-window-iframecontent",!!aw);
return ax;
},_triggerRefresh:function(){this.trigger(X);
},_ajaxComplete:function(){clearTimeout(this._loadingIconTimeout);
this.wrapper.find(Y).removeClass(K);
},_ajaxError:function(at,ar){this.trigger(p,{status:ar,xhr:at});
},_ajaxSuccess:function(ar){return function(at){var au=at;
if(ar){au=ae(ar)(at||{});
}this.content(au,at);
this.element.prop("scrollTop",0);
this.trigger(X);
};
},_showLoading:function(){this.wrapper.find(Y).addClass(K);
},_ajaxRequest:function(ar){this._loadingIconTimeout=setTimeout(W(this._showLoading,this),100);
b.ajax(r({type:"GET",dataType:"html",cache:false,error:W(this._ajaxError,this),complete:W(this._ajaxComplete,this),success:W(this._ajaxSuccess(ar.template),this)},ar));
},_destroy:function(){if(this.resizing){this.resizing.destroy();
}if(this.dragging){this.dragging.destroy();
}this.wrapper.off(Q).children(G).off(Q).end().find(".k-resize-handle,.k-window-titlebar").off(Q);
b(window).off("resize"+Q+this._marker);
b(window).off(P);
b(window).off(Q);
clearTimeout(this._loadingIconTimeout);
ak.fn.destroy.call(this);
this.unbind(ai);
y.destroy(this.wrapper);
this._removeOverlay(true);
},destroy:function(){this._destroy();
this.wrapper.empty().remove();
this.wrapper=this.appendTo=this.element=b();
},_createWindow:function(){var ar=this.element,av=this.options,at,aw,au=y.support.isRtl(ar);
if(av.scrollable===false){ar.css("overflow","hidden");
}aw=b(af.wrapper(av));
at=ar.find("iframe:not(.k-content-frame)").map(function(){var ax=this.getAttribute("src");
this.src="";
return ax;
});
aw.toggleClass("k-rtl",au).attr("tabindex",0).append(ar).find("iframe:not(.k-content-frame)").each(function(ax){this.src=at[ax];
});
if(this.containment){this.containment.prepend(aw);
}else{if(this.appendTo){aw.appendTo(this.appendTo);
}}aw.find(".k-window-title").css(au?"left":"right",T(aw.find(".k-window-actions"))+10);
ar.css("visibility","").show();
ar.find("[data-role=editor]").each(function(){var ax=b(this).data("kendoEditor");
if(ax){ax.refresh();
}});
aw=ar=null;
}});
af={wrapper:ae("<div class='k-widget k-window'></div>"),action:ae("<a role='button' href='\\#' class='k-button k-flat k-button-icon k-window-action' aria-label='#= name #'><span class='k-icon k-i-#= name.toLowerCase() #'></span></a>"),titlebar:ae("<div class='k-window-titlebar'><span class='k-window-title'>#= title #</span><div class='k-window-actions'></div></div>"),overlay:"<div class='k-overlay'></div>",contentFrame:ae("<iframe frameborder='0' title='#= title #' class='"+w+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),resizeHandle:ae("<div class='k-resize-handle k-resize-#= data #'></div>")};
function ao(at){var ar=this;
ar.owner=at;
ar._preventDragging=false;
ar._draggable=new m(at.wrapper,{filter:">"+H,group:at.wrapper.id+"-resizing",dragstart:W(ar.dragstart,ar),drag:W(ar.drag,ar),dragend:W(ar.dragend,ar)});
ar._draggable.userEvents.bind("press",W(ar.addOverlay,ar));
ar._draggable.userEvents.bind("release",W(ar.removeOverlay,ar));
}ao.prototype={addOverlay:function(){this.owner.wrapper.append(af.overlay);
},removeOverlay:function(){this.owner.wrapper.find(C).remove();
},dragstart:function(ar){var az=this;
var aA=az.owner;
var aB=aA.wrapper;
az._preventDragging=aA.trigger(ab);
if(az._preventDragging){return;
}az.elementPadding=parseInt(aB.css("padding-top"),10);
az.initialPosition=y.getOffset(aB,"position");
az.resizeDirection=ar.currentTarget.prop("className").replace("k-resize-handle k-resize-","");
az.initialSize={width:aB.outerWidth(),height:aB.outerHeight()};
aA._updateBoundaries();
az.containerOffset=aA.containment?aA.containment.position:y.getOffset(aA.appendTo,"position");
var aw=aB.offsetParent();
if(aw.is("html")){az.containerOffset.top=az.containerOffset.left=0;
}else{var av=aw.css("margin-top");
var au=aw.css("margin-left");
var at=!ap.test(av)||!ap.test(au);
if(at){var aC=s(aB[0]);
var ax=aC.left-az.containerOffset.left-az.initialPosition.left;
var ay=aC.top-az.containerOffset.top-az.initialPosition.top;
az._relativeElMarginLeft=ax>1?ax:0;
az._relativeElMarginTop=ay>1?ay:0;
az.initialPosition.left+=az._relativeElMarginLeft;
az.initialPosition.top+=az._relativeElMarginTop;
}}aB.children(H).not(ar.currentTarget).hide();
b(e).css(h,ar.currentTarget.css(h));
},drag:function(av){if(this._preventDragging){return;
}var aG=this,aJ=aG.owner,aK=aJ.wrapper,aC=aJ.options,aD=aC.position,au=aG.resizeDirection,ar=aG.containerOffset,aw=aG.initialPosition,ax=aG.initialSize,at=aJ.containment&&!aJ._isPinned,aE=y.support.isRtl(aJ.containment),ay=at&&aE&&aJ.containment.innerWidth()>aJ.containment.width?y.support.scrollbar():0,aF=at?{top:aJ.containment.scrollTop(),left:aJ.containment.scrollLeft()}:{top:0,left:0},aA,az,aH,aI,aL=Math.max(av.x.location,0),aM=Math.max(av.y.location,0);
if(au.indexOf("e")>=0){if(aJ.containment&&aL-ax.width>=aJ.maxLeft-aF.left+ar.left+ay){aA=aJ.maxLeft+ay-aw.left+ax.width-aF.left;
}else{aA=aL-aw.left-ar.left;
}aK.width(g(aA,aC.minWidth,aC.maxWidth));
}else{if(au.indexOf("w")>=0){aI=aw.left+ax.width+ar.left;
aA=g(aI-aL,aC.minWidth,aC.maxWidth);
aD.left=aI-aA-ar.left-ay-(aG._relativeElMarginLeft||0)+aF.left;
if(aJ.containment&&aD.left<=aJ.minLeft){aD.left=aJ.minLeft;
aA=g(aI-ay-aD.left-ar.left+aF.left,aC.minWidth,aC.maxWidth);
}aK.css({left:aD.left,width:aA});
}}var aB=aM;
if(aJ.options.pinned){aB-=b(window).scrollTop();
}if(au.indexOf("s")>=0){az=aB-aw.top-aG.elementPadding-ar.top;
if(aB-ax.height-aG.elementPadding>=aJ.maxTop+ar.top-aF.top){az=aJ.maxTop-aw.top+ax.height-aF.top;
}aK.height(g(az,aC.minHeight,aC.maxHeight));
}else{if(au.indexOf("n")>=0){aH=aw.top+ax.height+ar.top;
az=g(aH-aB,aC.minHeight,aC.maxHeight);
aD.top=aH-az-ar.top-(aG._relativeElMarginTop||0)+aF.top;
if(aD.top<=aJ.minTop&&aJ.containment){aD.top=aJ.minTop;
az=g(aH-aD.top-ar.top+aF.top,aC.minHeight,aC.maxHeight);
}aK.css({top:aD.top,height:az});
}}if(aA){aJ.options.width=aA+"px";
}if(az){aJ.options.height=az+"px";
}aJ.resize();
},dragend:function(ar){if(this._preventDragging){return;
}var at=this,au=at.owner,av=au.wrapper;
av.children(H).not(ar.currentTarget).show();
b(e).css(h,"");
if(au.touchScroller){au.touchScroller.reset();
}if(ar.keyCode==27){av.css(at.initialPosition).css(at.initialSize);
}au.trigger(aa);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
function am(au,ar){var at=this;
at.owner=au;
at._preventDragging=false;
at._draggable=new m(au.wrapper,{filter:ar,group:au.wrapper.id+"-moving",dragstart:W(at.dragstart,at),drag:W(at.drag,at),dragend:W(at.dragend,at),dragcancel:W(at.dragcancel,at)});
at._draggable.userEvents.stopPropagation=false;
}am.prototype={dragstart:function(av){var ax=this.owner,au=ax.options.draggable,aw=ax.element,ar=aw.find(".k-window-actions"),at=y.getOffset(ax.appendTo);
this._preventDragging=ax.trigger(n)||!au;
if(this._preventDragging||ax.isMaximized()){return;
}ax.initialWindowPosition=y.getOffset(ax.wrapper,"position");
ax.initialPointerPosition={left:ax.options.position.left,top:ax.options.position.top};
ax.startPosition={left:av.x.client-ax.initialWindowPosition.left,top:av.y.client-ax.initialWindowPosition.top};
ax._updateBoundaries();
if(!ax.containment){if(ar.length>0){ax.minLeft=T(ar)+parseInt(ar.css("right"),10)-T(aw);
}else{ax.minLeft=20-T(aw);
}ax.minLeft-=at.left;
ax.minTop=-at.top;
}ax.wrapper.append(af.overlay).children(H).hide();
b(e).css(h,av.currentTarget.css(h));
},drag:function(at){var ax=this.owner;
var av=ax.options.position;
var ar=ax.options.draggable.axis;
var au;
var aw;
if(this._preventDragging||ax.isMaximized()){return;
}if(!ar||ar.toLowerCase()==="x"){au=at.x.client-ax.startPosition.left;
if(ax.containment&&!ax._isPinned){au+=ax.containment.scrollLeft();
}av.left=g(au,ax.minLeft,ax.maxLeft);
}if(!ar||ar.toLowerCase()==="y"){aw=at.y.client-ax.startPosition.top;
if(ax.containment&&!ax._isPinned){aw+=ax.containment.scrollTop();
}av.top=g(aw,ax.minTop,ax.maxTop);
}if(y.support.transforms){b(ax.wrapper).css("transform","translate("+(av.left-ax.initialPointerPosition.left)+"px, "+(av.top-ax.initialPointerPosition.top)+"px)");
}else{b(ax.wrapper).css(av);
}},_finishDrag:function(){var ar=this.owner;
ar.wrapper.children(H).toggle(!ar.options.isMinimized).end().find(C).remove();
b(e).css(h,"");
},dragcancel:function(ar){if(this._preventDragging){return;
}this._finishDrag();
ar.currentTarget.closest(F).css(this.owner.initialWindowPosition);
},dragend:function(){var ar=this.owner;
if(this._preventDragging||ar.isMaximized()){return;
}b(ar.wrapper).css(ar.options.position).css("transform","");
this._finishDrag();
ar.trigger(l);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
y.ui.plugin(al);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
