using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Web.UI;

[assembly: AssemblyVersion("16.1.1.0")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditorExtender.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditorExtender.min.css", "text/css")]
[assembly: AssemblyFileVersion("16.1.1.0")]
[assembly: AssemblyConfiguration("Release")]
[assembly: TagPrefix("AjaxControlToolkit", "ajaxToolkit")]
[assembly: AssemblyTitle("ASP.NET AJAX Control Toolkit")]
[assembly: AllowPartiallyTrustedCallers]
[assembly: ComVisible(false)]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: WebResource("Accordion.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Accordion.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Accordion.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Accordion.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxFileUpload.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AjaxFileUpload.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxFileUpload.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AjaxFileUpload.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.AjaxFileUpload.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.AjaxFileUpload.min.css", "text/css")]
[assembly: WebResource("AlwaysVisibleControl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AlwaysVisibleControl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AlwaysVisibleControl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AlwaysVisibleControl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Animation.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Animation.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Animation.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Animation.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AnimationScripts.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AnimationScripts.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AnimationScripts.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AnimationScripts.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AsyncFileUpload.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AsyncFileUpload.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AsyncFileUpload.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AsyncFileUpload.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Images.AsyncFileUpload.Button.png", "image/png")]
[assembly: WebResource("AreaChart.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AreaChart.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AreaChart.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AreaChart.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.AreaChart.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.AreaChart.min.css", "text/css")]
[assembly: WebResource("AutoComplete.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/AutoComplete.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AutoComplete.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/AutoComplete.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Backgrounds.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Backgrounds.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("BaseScripts.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/BaseScripts.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("BaseScripts.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/BaseScripts.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("BalloonPopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/BalloonPopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("BalloonPopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/BalloonPopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BalloonPopup.Cloud.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BalloonPopup.Cloud.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BalloonPopup.Rectangle.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BalloonPopup.Rectangle.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.BalloonPopup.CloudSprite.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.BalloonPopup.CloudSprite.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.BalloonPopup.RectangleSprite.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.BalloonPopup.RectangleSprite.gif", "image/gif")]
[assembly: WebResource("BarChart.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/BarChart.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("BarChart.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/BarChart.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BarChart.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.BarChart.min.css", "text/css")]
[assembly: WebResource("BubbleChart.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/BubbleChart.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("BubbleChart.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/BubbleChart.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.BubbleChart.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.BubbleChart.min.css", "text/css")]
[assembly: WebResource("Common.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Common.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Common.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Common.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Compat.DragDrop.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Compat.DragDrop.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Compat.DragDrop.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Compat.DragDrop.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Compat.Timer.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Compat.Timer.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Compat.Timer.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Compat.Timer.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ComponentSet.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ComponentSet.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ComponentSet.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ComponentSet.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Calendar.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Calendar.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Calendar.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Calendar.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Calendar.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Calendar.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Calendar.Arrow-Left.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Calendar.Arrow-Right.gif", "image/gif")]
[assembly: WebResource("CascadingDropDown.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/CascadingDropDown.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("CascadingDropDown.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/CascadingDropDown.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("CollapsiblePanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/CollapsiblePanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("CollapsiblePanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/CollapsiblePanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ColorPicker.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ColorPicker.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ColorPicker.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ColorPicker.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ColorPicker.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ColorPicker.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("ComboBox.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ComboBox.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ComboBox.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ComboBox.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ComboBox.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ComboBox.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.ComboBox.Arrow-Down.gif", "image/gif")]
[assembly: WebResource("ConfirmButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ConfirmButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ConfirmButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ConfirmButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Common.DateTime.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Common.DateTime.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Common.DateTime.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Common.DateTime.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DynamicPopulate.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/DynamicPopulate.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DynamicPopulate.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/DynamicPopulate.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DraggableListItem.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/DraggableListItem.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DraggableListItem.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/DraggableListItem.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DropDown.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/DropDown.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DropDown.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/DropDown.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.DropDown.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.DropDown.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.DropDown.DropArrow.gif", "image/gif")]
[assembly: WebResource("DropShadow.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/DropShadow.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DropShadow.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/DropShadow.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DropWatcher.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/DropWatcher.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("DropWatcher.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/DropWatcher.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("FilteredTextBox.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/FilteredTextBox.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("FilteredTextBox.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/FilteredTextBox.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("FloatingBehavior.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/FloatingBehavior.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("FloatingBehavior.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/FloatingBehavior.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Gravatar.Anonymous.jpg", "image/jpeg")]
[assembly: WebResource("AjaxControlToolkit.Images.Gravatar.G.jpg", "image/jpeg")]
[assembly: WebResource("AjaxControlToolkit.Images.Gravatar.PG.jpg", "image/jpeg")]
[assembly: WebResource("AjaxControlToolkit.Images.Gravatar.R.jpg", "image/jpeg")]
[assembly: WebResource("AjaxControlToolkit.Images.Gravatar.X.jpg", "image/jpeg")]
[assembly: WebResource("HoverMenu.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HoverMenu.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HoverMenu.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HoverMenu.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Hover.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Hover.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Hover.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Hover.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditorExtender.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditorExtender.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditorExtender.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditorExtender.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditorExtender", "image/png")]
[assembly: WebResource("HtmlEditor.Editor.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Editor.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Editor.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Editor.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.HtmlEditor.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.HtmlEditor.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.HtmlEditor.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.HtmlEditor.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Enums.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Enums.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Enums.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Enums.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Events.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Events.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Events.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Events.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.PreviewPanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.PreviewPanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.PreviewPanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.PreviewPanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ModePanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ModePanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ModePanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ModePanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.EditPanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.EditPanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.EditPanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.EditPanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.HtmlPanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.HtmlPanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.HtmlPanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.HtmlPanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ExecCommandEmulation.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ExecCommandEmulation.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ExecCommandEmulation.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ExecCommandEmulation.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.DesignPanel.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.DesignPanel.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.DesignPanel.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.DesignPanel.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.DesignPanelEventHandler.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.DesignPanelEventHandler.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.DesignPanelEventHandler.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.DesignPanelEventHandler.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.Popup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.Popup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.Popup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.Popup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.AttachedTemplatePopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.AttachedTemplatePopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.AttachedTemplatePopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.AttachedTemplatePopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.AttachedPopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.AttachedPopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.AttachedPopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.AttachedPopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupCommonButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.PopupCommonButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupCommonButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.PopupCommonButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupBoxButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.PopupBoxButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupBoxButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.PopupBoxButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupBGIButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.PopupBGIButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.PopupBGIButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.PopupBGIButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.OkCancelAttachedTemplatePopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.OkCancelAttachedTemplatePopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.OkCancelAttachedTemplatePopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.OkCancelAttachedTemplatePopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.LinkProperties.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.LinkProperties.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.LinkProperties.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.LinkProperties.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.BaseColorsPopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Popups.BaseColorsPopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Popups.BaseColorsPopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Popups.BaseColorsPopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BackColorClear.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.BackColorClear.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BackColorClear.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.BackColorClear.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BackColorSelector.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.BackColorSelector.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BackColorSelector.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.BackColorSelector.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Bold.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Bold.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Bold.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Bold.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BoxButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.BoxButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BoxButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.BoxButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BulletedList.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.BulletedList.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.BulletedList.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.BulletedList.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ColorButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ColorButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ColorButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ColorButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ColorSelector.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ColorSelector.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ColorSelector.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ColorSelector.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.CommonButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.CommonButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.CommonButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.CommonButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Copy.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Copy.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Copy.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Copy.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Cut.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Cut.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Cut.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Cut.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DecreaseIndent.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DecreaseIndent.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DecreaseIndent.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DecreaseIndent.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignMode.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DesignMode.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignMode.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DesignMode.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeBoxButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DesignModeBoxButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeBoxButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DesignModeBoxButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeImageButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DesignModeImageButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeImageButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DesignModeImageButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModePopupImageButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DesignModePopupImageButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModePopupImageButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DesignModePopupImageButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeSelectButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.DesignModeSelectButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.DesignModeSelectButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.DesignModeSelectButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.EditorToggleButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.EditorToggleButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.EditorToggleButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.EditorToggleButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedBackColor.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.FixedBackColor.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedBackColor.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.FixedBackColor.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedColorButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.FixedColorButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedColorButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.FixedColorButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedForeColor.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.FixedForeColor.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FixedForeColor.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.FixedForeColor.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FontName.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.FontName.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FontName.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.FontName.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FontSize.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.FontSize.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.FontSize.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.FontSize.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColor.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ForeColor.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColor.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ForeColor.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColorClear.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ForeColorClear.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColorClear.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ForeColorClear.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColorSelector.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ForeColorSelector.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ForeColorSelector.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ForeColorSelector.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.HorizontalSeparator.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.HorizontalSeparator.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.HorizontalSeparator.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.HorizontalSeparator.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Italic.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Italic.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Italic.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Italic.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ModeButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ModeButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ModeButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ModeButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.HtmlMode.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.HtmlMode.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.HtmlMode.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.HtmlMode.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Toolbar.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.Toolbar.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.Toolbar.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.Toolbar.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ImageButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.ImageButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.ImageButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.ImageButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.IncreaseIndent.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.IncreaseIndent.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.IncreaseIndent.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.IncreaseIndent.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.InsertHR.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.InsertHR.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.InsertHR.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.InsertHR.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.InsertLink.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.InsertLink.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.InsertLink.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.InsertLink.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyCenter.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.JustifyCenter.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyCenter.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.JustifyCenter.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyFull.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.JustifyFull.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyFull.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.JustifyFull.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyLeft.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.JustifyLeft.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyLeft.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.JustifyLeft.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyRight.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.JustifyRight.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.JustifyRight.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.JustifyRight.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Ltr.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Ltr.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Ltr.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Ltr.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.MethodButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.MethodButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.MethodButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.MethodButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.OkCancelPopupButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.OkCancelPopupButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.OkCancelPopupButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.OkCancelPopupButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.OrderedList.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.OrderedList.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.OrderedList.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.OrderedList.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Paragraph.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Paragraph.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Paragraph.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Paragraph.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Paste.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Paste.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Paste.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Paste.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PasteText.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.PasteText.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PasteText.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.PasteText.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PasteWord.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.PasteWord.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PasteWord.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.PasteWord.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PreviewMode.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.PreviewMode.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.PreviewMode.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.PreviewMode.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Redo.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Redo.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Redo.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Redo.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveAlignment.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.RemoveAlignment.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveAlignment.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.RemoveAlignment.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveLink.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.RemoveLink.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveLink.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.RemoveLink.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveStyles.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.RemoveStyles.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.RemoveStyles.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.RemoveStyles.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Rtl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Rtl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Rtl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Rtl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SelectButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.SelectButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SelectButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.SelectButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Selector.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Selector.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Selector.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Selector.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.StrikeThrough.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.StrikeThrough.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.StrikeThrough.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.StrikeThrough.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SubScript.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.SubScript.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SubScript.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.SubScript.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SuperScript.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.SuperScript.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.SuperScript.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.SuperScript.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Underline.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Underline.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Underline.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Underline.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Undo.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/HtmlEditor.ToolbarButtons.Undo.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("HtmlEditor.ToolbarButtons.Undo.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/HtmlEditor.ToolbarButtons.Undo.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Editor.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Editor.min.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Popups.AttachedTemplatePopup.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Popups.AttachedTemplatePopup.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.HtmlPanel.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.HtmlPanel.min.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Document.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.Document.min.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.DesignPanel.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.HtmlEditor.DesignPanel.min.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.BgiButton.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorBgClear-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorBgClear-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatBold-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatBold-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ListBullet-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ListBullet-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Copy-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Copy-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Cut-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Cut-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-IndentLess-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-IndentLess-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Design-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Design-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-BackColor-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-BackColor-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ForeColor-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ForeColor-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorFg-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorFg-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorFgClear-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ColorFgClear-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Separator.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Html-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Html-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-IndentMore-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-IndentMore-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Rule-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Rule-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Link-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Link-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.ToolbarButtons.Italic", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatItalic-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatItalic-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignCenter-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignCenter-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignJustify-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignJustify-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignLeft-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignLeft-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignRight-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignRight-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatLtr-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatLtr-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ListNum-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-ListNum-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatParagraph-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatParagraph-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Paste-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Paste-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-PasteText-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-PasteText-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-PasteWord-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-PasteWord-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Preview-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Preview-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Redo-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Redo-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignRemove-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-AlignRemove-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Unlink-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Unlink-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Unformat-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Unformat-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatRtl-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatRtl-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Selector-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Selector-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatStrike-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatStrike-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatSub-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatSub-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatSup-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatSup-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatUnderline-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-FormatUnderline-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Undo-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Undo-Inactive.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-1x1.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Anchor.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Flash.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Media.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditor.Ed-Placeholder.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.HtmlEditorExtender.Buttons.png", "image/png")]
[assembly: WebResource("LineChart.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/LineChart.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("LineChart.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/LineChart.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.LineChart.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.LineChart.min.css", "text/css")]
[assembly: WebResource("ListSearch.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ListSearch.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ListSearch.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ListSearch.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MaskedEdit.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/MaskedEdit.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MaskedEdit.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/MaskedEdit.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MaskedEditValidator.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/MaskedEditValidator.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MaskedEditValidator.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/MaskedEditValidator.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ModalPopup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ModalPopup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ModalPopup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ModalPopup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MultiHandleSlider.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/MultiHandleSlider.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MultiHandleSlider.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/MultiHandleSlider.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.MultiHandleSlider.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.MultiHandleSlider.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.Handle-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.HandleDown-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.HandleHover-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.Rail-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.RailOuter-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.Handle-Vertical.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.HandleDown-Vertical.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.HandleHover-Vertical.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.Rail-Vertical.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.MultiHandleSlider.RailOuter-Vertical.gif", "image/gif")]
[assembly: WebResource("MutuallyExclusiveCheckBox.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/MutuallyExclusiveCheckBox.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("MutuallyExclusiveCheckBox.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/MutuallyExclusiveCheckBox.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("NoBot.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/NoBot.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("NoBot.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/NoBot.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("NumericUpDown.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/NumericUpDown.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("NumericUpDown.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/NumericUpDown.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.NumericUpDown.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.NumericUpDown.min.css", "text/css")]
[assembly: WebResource("PagingBulletedList.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/PagingBulletedList.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PagingBulletedList.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/PagingBulletedList.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PasswordStrength.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/PasswordStrength.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PasswordStrength.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/PasswordStrength.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PieChart.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/PieChart.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PieChart.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/PieChart.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.PieChart.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.PieChart.min.css", "text/css")]
[assembly: WebResource("PopupControl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/PopupControl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("PopupControl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/PopupControl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Popup.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Popup.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Popup.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Popup.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Rating.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Rating.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Rating.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Rating.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ResizableControl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ResizableControl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ResizableControl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ResizableControl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("RoundedCorners.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/RoundedCorners.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("RoundedCorners.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/RoundedCorners.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Seadragon.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Seadragon.debug.js", CdnSupportsSecureConnection = true, PerformSubstitution = true)]
[assembly: WebResource("Seadragon.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Seadragon.js", CdnSupportsSecureConnection = true, PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Fullscreen-Grouphover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Fullscreen-Hover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Fullscreen-Pressed.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Fullscreen-Rest.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Home-Grouphover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Home-Hover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Home-Pressed.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.Home-Rest.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomIn-Grouphover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomIn-Hover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomIn-Pressed.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomIn-Rest.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomOut-Grouphover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomOut-Hover.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomOut-Pressed.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Seadragon.ZoomOut-Rest.png", "image/png")]
[assembly: WebResource("Slider.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Slider.debug.js", CdnSupportsSecureConnection = true, PerformSubstitution = true)]
[assembly: WebResource("Slider.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Slider.js", CdnSupportsSecureConnection = true, PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Slider.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Slider.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Slider.Handle-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Slider.Handle-Vertical.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Slider.Rail-Horizontal.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Slider.Rail-Vertical.gif", "image/gif")]
[assembly: WebResource("SlideShow.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/SlideShow.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("SlideShow.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/SlideShow.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.SlideShow.css", "text/css")]
[assembly: WebResource("AjaxControlToolkit.Styles.SlideShow.min.css", "text/css")]
[assembly: WebResource("Tabs.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Tabs.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Tabs.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Tabs.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Tabs.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Tabs.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Background.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveLeft-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveLeft-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveRight-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.ActiveRight-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Active-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Active-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-Active.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-ActiveLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-ActiveRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-Hover.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-HoverLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-HoverRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-Left.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Bottom-Right.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Hover.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverLeft-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverLeft-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverRight-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.HoverRight-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Hover-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Hover-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Left.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Left-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Left-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Line.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Right.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Right-VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.Right-VerticalRight.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.VerticalLeft.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.Tabs.VerticalRight.gif", "image/gif")]
[assembly: WebResource("TextBoxWatermark.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/TextBoxWatermark.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("TextBoxWatermark.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/TextBoxWatermark.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Common.Threading.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Common.Threading.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Common.Threading.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Common.Threading.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ToggleButton.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ToggleButton.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ToggleButton.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ToggleButton.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Twitter.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.Twitter.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.Twitter.24.png", "image/png")]
[assembly: WebResource("AjaxControlToolkit.Images.Twitter.32.png", "image/png")]
[assembly: WebResource("UpdatePanelAnimation.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/UpdatePanelAnimation.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("UpdatePanelAnimation.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/UpdatePanelAnimation.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ValidatorCallout.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/ValidatorCallout.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("ValidatorCallout.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/ValidatorCallout.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ValidatorCallout.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Styles.ValidatorCallout.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("AjaxControlToolkit.Images.ValidatorCallout.Alert-Large.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.ValidatorCallout.Alert-Small.gif", "image/gif")]
[assembly: WebResource("AjaxControlToolkit.Images.ValidatorCallout.Close.gif", "image/gif")]
[assembly: WebResource("Localization.Resources.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ar.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.ar.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ar.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.ar.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.cs.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.cs.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.cs.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.cs.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.de.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.de.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.de.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.de.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.es.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.es.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.es.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.es.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.fr.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.fr.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.fr.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.fr.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.he.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.he.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.he.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.he.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.hi.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.hi.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.hi.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.hi.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.it.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.it.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.it.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.it.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ja.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.ja.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ja.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.ja.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ko.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.ko.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ko.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.ko.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.nl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.nl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.nl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.nl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.pl.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.pl.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.pl.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.pl.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.pt.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.pt.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.pt.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.pt.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ru.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.ru.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.ru.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.ru.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.tr.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.tr.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.tr.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.tr.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.zh-CHS.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.zh-CHS.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.zh-CHS.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.zh-CHS.debug.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.zh-CHT.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Release/Localization.Resources.zh-CHT.js", CdnSupportsSecureConnection = true)]
[assembly: WebResource("Localization.Resources.zh-CHT.debug.js", "text/javascript", CdnPath = "//ajax.aspnetcdn.com/ajax/act/16_1_1/Scripts/AjaxControlToolkit/Debug/Localization.Resources.zh-CHT.debug.js", CdnSupportsSecureConnection = true)]
[assembly: AssemblyProduct("ASP.NET AJAX Control Toolkit")]
[assembly: AssemblyCopyright("Copyright © CodePlex Foundation 2012-2016")]
[assembly: AssemblyCompany("CodePlex Foundation")]
