using System;
using System.ComponentModel;

namespace System.Data.Design
{
	// Token: 0x0200023B RID: 571
	[DataSourceXmlClass("Parameter")]
	internal class DesignParameter : DataSourceComponent, IDbDataParameter, IDataParameter, IDataSourceNamedObject, INamedObject, ICloneable
	{
		// Token: 0x170004D5 RID: 1237
		// (get) Token: 0x0600159E RID: 5534 RVA: 0x00079666 File Offset: 0x00077866
		// (set) Token: 0x0600159F RID: 5535 RVA: 0x0007966E File Offset: 0x0007786E
		[DataSourceXmlAttribute]
		[DefaultValue(false)]
		public bool AllowDbNull
		{
			get
			{
				return this.allowDbNull;
			}
			set
			{
				this.allowDbNull = value;
			}
		}

		// Token: 0x170004D6 RID: 1238
		// (get) Token: 0x060015A0 RID: 5536 RVA: 0x00079677 File Offset: 0x00077877
		// (set) Token: 0x060015A1 RID: 5537 RVA: 0x0007967F File Offset: 0x0007787F
		[DataSourceXmlAttribute]
		[MergableProperty(false)]
		[DefaultValue("")]
		public string ParameterName
		{
			get
			{
				return this.parameterName;
			}
			set
			{
				if (!StringUtil.EqualValue(this.ParameterName, value))
				{
					if (this.CollectionParent != null)
					{
						this.CollectionParent.ValidateUniqueName(this, value);
					}
					this.parameterName = value;
				}
			}
		}

		// Token: 0x170004D7 RID: 1239
		// (get) Token: 0x060015A2 RID: 5538 RVA: 0x000796AB File Offset: 0x000778AB
		// (set) Token: 0x060015A3 RID: 5539 RVA: 0x000796B3 File Offset: 0x000778B3
		[DataSourceXmlAttribute]
		public string ColumnName
		{
			get
			{
				return this.columnName;
			}
			set
			{
				this.columnName = value;
			}
		}

		// Token: 0x170004D8 RID: 1240
		// (get) Token: 0x060015A4 RID: 5540 RVA: 0x000796BC File Offset: 0x000778BC
		// (set) Token: 0x060015A5 RID: 5541 RVA: 0x000796C4 File Offset: 0x000778C4
		[DataSourceXmlAttribute]
		[Browsable(false)]
		public string AutogeneratedName
		{
			get
			{
				return this.autogeneratedName;
			}
			set
			{
				this.autogeneratedName = value;
			}
		}

		// Token: 0x170004D9 RID: 1241
		// (get) Token: 0x060015A6 RID: 5542 RVA: 0x000796CD File Offset: 0x000778CD
		// (set) Token: 0x060015A7 RID: 5543 RVA: 0x000796D5 File Offset: 0x000778D5
		[DataSourceXmlAttribute]
		public DbType DbType
		{
			get
			{
				return this.dbType;
			}
			set
			{
				this.dbType = value;
			}
		}

		// Token: 0x170004DA RID: 1242
		// (get) Token: 0x060015A8 RID: 5544 RVA: 0x000796DE File Offset: 0x000778DE
		// (set) Token: 0x060015A9 RID: 5545 RVA: 0x000796E6 File Offset: 0x000778E6
		[DataSourceXmlAttribute]
		public string ProviderType
		{
			get
			{
				return this.providerType;
			}
			set
			{
				this.providerType = value;
			}
		}

		// Token: 0x170004DB RID: 1243
		// (get) Token: 0x060015AA RID: 5546 RVA: 0x000796EF File Offset: 0x000778EF
		// (set) Token: 0x060015AB RID: 5547 RVA: 0x000796F7 File Offset: 0x000778F7
		[DataSourceXmlAttribute]
		[DefaultValue(0)]
		public byte Precision
		{
			get
			{
				return this.precision;
			}
			set
			{
				this.precision = value;
			}
		}

		// Token: 0x170004DC RID: 1244
		// (get) Token: 0x060015AC RID: 5548 RVA: 0x00079700 File Offset: 0x00077900
		// (set) Token: 0x060015AD RID: 5549 RVA: 0x00079708 File Offset: 0x00077908
		[DataSourceXmlAttribute]
		[DefaultValue(0)]
		public byte Scale
		{
			get
			{
				return this.scale;
			}
			set
			{
				this.scale = value;
			}
		}

		// Token: 0x170004DD RID: 1245
		// (get) Token: 0x060015AE RID: 5550 RVA: 0x00079711 File Offset: 0x00077911
		// (set) Token: 0x060015AF RID: 5551 RVA: 0x00079719 File Offset: 0x00077919
		[DataSourceXmlAttribute]
		[DefaultValue(0)]
		public int Size
		{
			get
			{
				return this.size;
			}
			set
			{
				this.size = value;
				if (this.size < 0)
				{
					this.size = int.MaxValue;
				}
			}
		}

		// Token: 0x170004DE RID: 1246
		// (get) Token: 0x060015B0 RID: 5552 RVA: 0x00079736 File Offset: 0x00077936
		// (set) Token: 0x060015B1 RID: 5553 RVA: 0x0007973E File Offset: 0x0007793E
		[DataSourceXmlAttribute]
		[Browsable(false)]
		public string DataTypeServer
		{
			get
			{
				return this.dataTypeServer;
			}
			set
			{
				this.dataTypeServer = value;
			}
		}

		// Token: 0x170004DF RID: 1247
		// (get) Token: 0x060015B2 RID: 5554 RVA: 0x00079747 File Offset: 0x00077947
		// (set) Token: 0x060015B3 RID: 5555 RVA: 0x0007974F File Offset: 0x0007794F
		[DataSourceXmlAttribute]
		[DefaultValue(ParameterDirection.Input)]
		public ParameterDirection Direction
		{
			get
			{
				return this.direction;
			}
			set
			{
				this.direction = value;
			}
		}

		// Token: 0x170004E0 RID: 1248
		// (get) Token: 0x060015B4 RID: 5556 RVA: 0x00079758 File Offset: 0x00077958
		// (set) Token: 0x060015B5 RID: 5557 RVA: 0x00079760 File Offset: 0x00077960
		[DefaultValue("")]
		[DataSourceXmlAttribute]
		public string SourceColumn
		{
			get
			{
				return this.sourceColumn;
			}
			set
			{
				this.sourceColumn = value;
			}
		}

		// Token: 0x170004E1 RID: 1249
		// (get) Token: 0x060015B6 RID: 5558 RVA: 0x00079769 File Offset: 0x00077969
		// (set) Token: 0x060015B7 RID: 5559 RVA: 0x00079771 File Offset: 0x00077971
		[DefaultValue(DataRowVersion.Current)]
		[DataSourceXmlAttribute]
		public DataRowVersion SourceVersion
		{
			get
			{
				return this.sourceVersion;
			}
			set
			{
				this.sourceVersion = value;
			}
		}

		// Token: 0x170004E2 RID: 1250
		// (get) Token: 0x060015B8 RID: 5560 RVA: 0x0007977A File Offset: 0x0007797A
		// (set) Token: 0x060015B9 RID: 5561 RVA: 0x00079782 File Offset: 0x00077982
		[DataSourceXmlAttribute]
		[Browsable(false)]
		public string DataSourceName
		{
			get
			{
				return this.dataSourceName;
			}
			set
			{
				this.dataSourceName = value;
			}
		}

		// Token: 0x170004E3 RID: 1251
		// (get) Token: 0x060015BA RID: 5562 RVA: 0x0007978B File Offset: 0x0007798B
		// (set) Token: 0x060015BB RID: 5563 RVA: 0x00079793 File Offset: 0x00077993
		string INamedObject.Name
		{
			get
			{
				return this.ParameterName;
			}
			set
			{
				this.ParameterName = value;
			}
		}

		// Token: 0x170004E4 RID: 1252
		// (get) Token: 0x060015BC RID: 5564 RVA: 0x0007979C File Offset: 0x0007799C
		string IDataSourceNamedObject.PublicTypeName
		{
			get
			{
				return "Parameter";
			}
		}

		// Token: 0x170004E5 RID: 1253
		// (get) Token: 0x060015BD RID: 5565 RVA: 0x00003B0F File Offset: 0x00001D0F
		[Browsable(false)]
		[DefaultValue(false)]
		[DesignOnly(true)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public bool IsNullable
		{
			get
			{
				return true;
			}
		}

		// Token: 0x170004E6 RID: 1254
		// (get) Token: 0x060015BE RID: 5566 RVA: 0x00003598 File Offset: 0x00001798
		// (set) Token: 0x060015BF RID: 5567 RVA: 0x00003937 File Offset: 0x00001B37
		[Browsable(false)]
		[DefaultValue(null)]
		public object Value
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		// Token: 0x170004E7 RID: 1255
		// (get) Token: 0x060015C0 RID: 5568 RVA: 0x0007978B File Offset: 0x0007798B
		[Browsable(false)]
		public string Name
		{
			get
			{
				return this.ParameterName;
			}
		}

		// Token: 0x170004E8 RID: 1256
		// (get) Token: 0x060015C1 RID: 5569 RVA: 0x000797A3 File Offset: 0x000779A3
		// (set) Token: 0x060015C2 RID: 5570 RVA: 0x000797AB File Offset: 0x000779AB
		[DefaultValue(false)]
		[DataSourceXmlAttribute]
		public bool SourceColumnNullMapping
		{
			get
			{
				return this.sourceColumnNullMapping;
			}
			set
			{
				this.sourceColumnNullMapping = value;
			}
		}

		// Token: 0x060015C3 RID: 5571 RVA: 0x0007978B File Offset: 0x0007798B
		public override string ToString()
		{
			return this.ParameterName;
		}

		// Token: 0x060015C4 RID: 5572 RVA: 0x000797B4 File Offset: 0x000779B4
		public DesignParameter() : this(string.Empty)
		{
		}

		// Token: 0x060015C5 RID: 5573 RVA: 0x000797C1 File Offset: 0x000779C1
		public DesignParameter(string name)
		{
			this.parameterName = name;
			this.autogeneratedName = string.Empty;
			this.direction = ParameterDirection.Input;
			this.sourceVersion = DataRowVersion.Current;
			this.dataSourceName = string.Empty;
		}

		// Token: 0x060015C6 RID: 5574 RVA: 0x000797F8 File Offset: 0x000779F8
		public override bool Equals(object o)
		{
			DesignParameter designParameter = o as DesignParameter;
			return designParameter != null && designParameter.ParameterName.Equals(this.ParameterName);
		}

		// Token: 0x060015C7 RID: 5575 RVA: 0x00079822 File Offset: 0x00077A22
		public override int GetHashCode()
		{
			return this.ParameterName.GetHashCode();
		}

		// Token: 0x060015C8 RID: 5576 RVA: 0x00079830 File Offset: 0x00077A30
		public object Clone()
		{
			return new DesignParameter(this.ParameterName)
			{
				ColumnName = this.ColumnName,
				AutogeneratedName = this.AutogeneratedName,
				DbType = this.DbType,
				Precision = this.Precision,
				Scale = this.Scale,
				Size = this.Size,
				DataTypeServer = this.DataTypeServer,
				Direction = this.Direction,
				SourceColumn = this.SourceColumn,
				SourceVersion = this.SourceVersion,
				SourceColumnNullMapping = this.SourceColumnNullMapping
			};
		}

		// Token: 0x060015C9 RID: 5577 RVA: 0x000798D0 File Offset: 0x00077AD0
		public static DesignParameter GetDefaultRetvalParam()
		{
			DesignParameter designParameter = new DesignParameter("RETURN_VALUE");
			designParameter.DbType = DbType.Int32;
			designParameter.Precision = (designParameter.Scale = 0);
			designParameter.Size = 4;
			designParameter.Direction = ParameterDirection.ReturnValue;
			return designParameter;
		}

		// Token: 0x04000B41 RID: 2881
		private string parameterName;

		// Token: 0x04000B42 RID: 2882
		private string columnName;

		// Token: 0x04000B43 RID: 2883
		private string autogeneratedName;

		// Token: 0x04000B44 RID: 2884
		private DbType dbType;

		// Token: 0x04000B45 RID: 2885
		private byte precision;

		// Token: 0x04000B46 RID: 2886
		private byte scale;

		// Token: 0x04000B47 RID: 2887
		private int size;

		// Token: 0x04000B48 RID: 2888
		private string dataTypeServer;

		// Token: 0x04000B49 RID: 2889
		private ParameterDirection direction;

		// Token: 0x04000B4A RID: 2890
		private string sourceColumn;

		// Token: 0x04000B4B RID: 2891
		private DataRowVersion sourceVersion;

		// Token: 0x04000B4C RID: 2892
		private string dataSourceName;

		// Token: 0x04000B4D RID: 2893
		private bool sourceColumnNullMapping;

		// Token: 0x04000B4E RID: 2894
		private bool allowDbNull;

		// Token: 0x04000B4F RID: 2895
		private string providerType;

		// Token: 0x04000B50 RID: 2896
		private static int[] adoDataType2DbType = new int[]
		{
			8,
			0,
			20,
			12,
			128,
			1,
			11,
			3,
			129,
			0,
			6,
			4,
			7,
			5,
			133,
			5,
			134,
			6,
			135,
			6,
			14,
			7,
			5,
			8,
			0,
			13,
			10,
			13,
			64,
			6,
			72,
			9,
			9,
			13,
			13,
			13,
			3,
			11,
			205,
			1,
			201,
			0,
			203,
			16,
			131,
			7,
			138,
			13,
			4,
			15,
			2,
			10,
			16,
			14,
			21,
			20,
			19,
			19,
			18,
			18,
			17,
			2,
			204,
			1,
			200,
			0,
			139,
			21,
			202,
			16,
			12,
			13,
			130,
			16
		};

		// Token: 0x04000B51 RID: 2897
		public const string DEFAULT_RETVAL_NAME = "RETURN_VALUE";
	}
}
