using System;

namespace TechnoPro.Common.DAO.Impl.Inventory
{
	// Token: 0x020000BB RID: 187
	internal static class QueryStorageInventoryReservation
	{
		// Token: 0x04000252 RID: 594
		internal const string UQ_MARK_RESERVATION_AS_COMPLETED_BY_ID = "update InventoryV2_Reservation set IsCompleted=1 where ReservationID=@reservationid";

		// Token: 0x04000253 RID: 595
		internal const string DQ_CANCEL_RESERVATION_BY_ID = "DELETE FROM InventoryV2_Reservation where ReservationID=@reservationid";

		// Token: 0x04000254 RID: 596
		internal const string DQ_CANCEL_RESERVATION_GROUP_BY_ID = "DELETE FROM InventoryV2_ReservationGroup where ReservationGroupId=@reservationgroupid";

		// Token: 0x04000255 RID: 597
		internal const string UQ_UPDATE_RESERVATION = "if ((select count(*) from InventoryV2_Reservation where ReservationGroupId=@reservationgroupid) > 1)\r\n\t            begin\r\n\t\t            BEGIN TRANSACTION\r\n\t\t            INSERT INTO [InventoryV2_ReservationGroup]\r\n                                    ([ReservationStartDate]\r\n                                    ,[ReservationEndDate]\r\n                                    ,[WhoMadeReservationId]\r\n                                    ,[WhoReservedStaffPersonId]\r\n                                    ,[NotificationEmails]\r\n                                    ,[BeNotified]\r\n                                    ,[ReservationNotes])\r\n                                VALUES\r\n                                    (@reservationstartdate\r\n                                    ,@reservationenddate\r\n                                    ,@whomadereservationid\r\n                                    ,@whoreservedstaffpersonid\r\n                                    ,@notificationemails\r\n                                    ,@benotified\r\n                                    ,@reservationnotes)\r\n\t                SET @rgroupid = scope_identity()\r\n\t                UPDATE [InventoryV2_Reservation]\r\n\t\t\t\t            SET\tReservationGroupId = @rgroupid\r\n\t\t\t\t            where ReservationID = @reservationid\r\n\t\t            COMMIT TRANSACTION\r\n\t            end\r\n            else\r\n\t            begin\r\n\t\t            UPDATE InventoryV2_ReservationGroup\r\n                            SET ReservationStartDate = @reservationstartdate,\r\n\t                            ReservationEndDate = @reservationenddate,\r\n\t                            NotificationEmails = @notificationemails,\r\n\t                            BeNotified = @benotified,\r\n\t                            ReservationNotes = @reservationnotes\r\n                            where ReservationGroupId = @reservationgroupid\r\n\t\t            set @rgroupid = @reservationgroupid\r\n\t            end";

		// Token: 0x04000256 RID: 598
		internal const string UQ_UPDATE_RESERVATION_GROUP = "UPDATE InventoryV2_ReservationGroup\r\n                SET ReservationStartDate = @reservationstartdate,\r\n\t                ReservationEndDate = @reservationenddate,\r\n\t                NotificationEmails = @notificationemails,\r\n\t                BeNotified = @benotified,\r\n\t                ReservationNotes = @reservationnotes\r\n                where ReservationGroupId = @reservationgroupid";

		// Token: 0x04000257 RID: 599
		internal const string IQ_CREATE_RESERVATION_GROUP = "INSERT INTO [InventoryV2_ReservationGroup]\r\n                       ([ReservationStartDate]\r\n                       ,[ReservationEndDate]\r\n                       ,[WhoMadeReservationId]\r\n                       ,[WhoReservedStaffPersonId]\r\n                       ,[NotificationEmails]\r\n                       ,[BeNotified]\r\n                       ,[ReservationNotes])\r\n                 VALUES\r\n                       (@reservationstartdate\r\n                       ,@reservationenddate\r\n                       ,@whomadereservationid\r\n                       ,@whoreservedstaffpersonid\r\n                       ,@notificationemails\r\n                       ,@benotified\r\n                       ,@reservationnotes)\r\n\r\n\t            SET @reservationgroupid = scope_identity()";

		// Token: 0x04000258 RID: 600
		internal const string IQ_CREATE_RESERVATION = "INSERT INTO [InventoryV2_Reservation]\r\n                       ([ProductUniqueId]\r\n                       ,[ReservationGroupId])\r\n                 VALUES\r\n                       (@productuniqueid\r\n                       ,@reservationgroupid)\r\n\r\n\t            SET @reservationid = scope_identity()";

		// Token: 0x04000259 RID: 601
		internal const string SQ_GET_RESERVATION_BY_ID = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.ReservationID=@reservationid";

		// Token: 0x0400025A RID: 602
		internal const string SQ_GET_RESERVATIONS_BY_PRODUCT_ID = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and r.ProductUniqueId=@productuniqueid\r\n                ORDER BY rg.ReservationStartDate";

		// Token: 0x0400025B RID: 603
		internal const string SQ_GET_RESERVATIONS_BY_PRODUCT_UNIQUE_ID_AND_DATE_RANGE = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and r.ProductUniqueId=@productuniqueid AND rg.ReservationStartDate < @enddate AND rg.ReservationEndDate > @startdate\r\n                ORDER BY rg.ReservationStartDate";

		// Token: 0x0400025C RID: 604
		internal const string SQ_GET_RESERVATIONS_BY_PRODUCT_AND_DATE_RANGE = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                INNER JOIN InventoryV2_Product p ON p.ProductUniqueId=r.ProductUniqueId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and p.ProductDynamicDataID=@productid AND rg.ReservationStartDate < @enddate AND rg.ReservationEndDate > @startdate\r\n                ORDER BY rg.ReservationStartDate";

		// Token: 0x0400025D RID: 605
		internal const string SQ_GET_RESERVATIONS_BY_WHO_MADE_IT_ID = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and rg.WhoMadeReservationId=@whomadereservationid\r\n                ORDER BY rg.ReservationStartDate";

		// Token: 0x0400025E RID: 606
		internal const string SQ_GET_RESERVATIONS_BY_WHO_MADE_IT_AND_DATE_RANGE = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and rg.WhoMadeReservationId=@whomadereservationid AND rg.ReservationStartDate < @enddate AND rg.ReservationEndDate > @startdate\r\n                ORDER BY rg.ReservationStartDate";

		// Token: 0x0400025F RID: 607
		internal const string SQ_GET_RESERVATIONS_BY_DATE_RANGE = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t    rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t    rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n        rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t    rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\nFROM InventoryV2_Reservation r\r\nINNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\nLEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\nLEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\nLEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\nLEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\nLEFT JOIN InventoryV2_Product p ON r.ProductUniqueID=p.ProductUniqueID\r\nLEFT JOIN InventoryV2_Category cg ON cg.CategoryName=p.CategoryName\r\nLEFT JOIN InventoryV2_Catalog ct ON ct.CatalogID=cg.CatalogId\r\nWHERE ct.IsActive = 1 AND r.IsCompleted=0 AND rg.ReservationStartDate < @enddate AND rg.ReservationEndDate > @startdate\r\nORDER BY rg.ReservationStartDate";

		// Token: 0x04000260 RID: 608
		internal const string SQ_GET_NEXT_RESERVATION_BY_PRODUCT_ID_AFTER_DATE = "SELECT TOP(1) \r\n\t\t               r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n            WHERE r.IsCompleted=0 and r.ProductUniqueId=@productuniqueid AND rg.ReservationStartDate >= @date\r\n            ORDER BY rg.ReservationStartDate";

		// Token: 0x04000261 RID: 609
		internal const string SQ_GET_RESERVATIONS_BY_GROUP_ID = "SELECT r.ReservationID, r.ProductUniqueId,\r\n\t                   rg.ReservationGroupId, rg.ReservationStartDate, rg.ReservationEndDate, rg.CreationDatetime,\r\n\t                   rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n\t                   rg.NotificationEmails, rg.BeNotified, rg.ReservationNotes\r\n                FROM InventoryV2_Reservation r\r\n                INNER JOIN InventoryV2_ReservationGroup rg ON rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                WHERE r.IsCompleted=0 and r.ReservationGroupId=@reservationgroupid";
	}
}
