using System;

namespace TechnoPro.Common.DAO.Impl.DynamicForms.QueryStorage
{
	// Token: 0x020000E6 RID: 230
	public static class QueryStorageAppointmentNotes
	{
		// Token: 0x040003EC RID: 1004
		internal const string QS_APP_IDS_BY_STUDENT_AND_SCREENNUMS_AND_DATE = "SELECT    DISTINCT pad.appointmentid\r\nFROM        perappdata2 pad LEFT JOIN appointments a ON a.appointmentid=pad.appointmentid\r\nWHERE       pad.personid=@pid\r\n            AND (@startdate IS NULL OR a.startdate BETWEEN @startdate AND @enddate )\r\n            AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\n            AND pad.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum IN (SELECT orderid AS screennum FROM splitorderids(@screennums,',')))\r\nORDER BY pad.appointmentid";

		// Token: 0x040003ED RID: 1005
		internal const string QS_APPOINTMENT_NOTES_BY_APPOINTMENT_ID = "SELECT  app.appointmentid,app.startDate,app.endDate,app.dateAdded,app.cancelled,app.apptypeid,\r\n        app.ishidden,app.islocked,app.personid AS whobookedpersonid,app.[subject],\r\n        att.attendeeid,att.personid,att.noshow,att.misccode,p.firstname,p.middlename,p.lastname,p.student_no,MIN(pg.groupid) AS groupid,\r\n        acr.cancelreasontext,am.memotext,am.isencrypted,[at].[description] AS apptypedescription,[at].appointmentTypeGroupID,atg.[description] AS apptypegrouptitle,\r\n        ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM    appointments app LEFT JOIN attendees att ON att.AppointmentID=app.appointmentid \r\n        LEFT JOIN people p ON p.personid=att.personid \r\n        LEFT JOIN appointmenttypes [at] ON [at].apptypeid=app.apptypeid \r\n        LEFT JOIN appointmenttypegroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID\r\n        LEFT JOIN appointmentshowtimeas ast ON ast.extraiconid=app.appcode \r\n        LEFT JOIN appointmentmemos am ON am.AppointmentID=app.AppointmentID\r\n        LEFT JOIN appointmentcancelledreason acr ON acr.appointmentid=att.appointmentid\r\n\t\tLEFT JOIN peoplegroups pg ON pg.personid=att.personid AND pg.groupid<10\r\nWHERE   app.appointmentid=@appid\r\nGROUP BY app.appointmentid,app.startDate,app.endDate,app.dateAdded,app.cancelled,app.apptypeid,\r\n        app.ishidden,app.islocked,app.personid,app.[subject],\r\n        att.attendeeid,att.personid,att.noshow,att.misccode,p.firstname,p.middlename,p.lastname,p.student_no,\r\n        acr.cancelreasontext,am.memotext,am.isencrypted,[at].[description],[at].appointmentTypeGroupID,atg.[description],\r\n        ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour";

		// Token: 0x040003EE RID: 1006
		internal const string QS_APPOINTMENT_NOTES_NO_ATTENDEES_NO_HAS_NOTES = "DECLARE @sd datetime\r\nDECLARE @ed datetime\r\nIF NOT @startdate IS NULL\r\nBEGIN\r\n    SET @sd = DATEADD(D, 0, DATEDIFF(D, 0, @startdate))\r\n    SET @ed = DATEADD(D, 1, DATEDIFF(D, 0, @enddate))\r\nEND\r\n\r\nSELECT orderid AS apptypeid INTO #tapptypeids FROM splitorderids(COALESCE(@apptypeids,''),',')\r\n\r\nSELECT  app.appointmentid,app.startDate,app.endDate,app.dateAdded,app.cancelled,app.apptypeid,\r\n        app.ishidden,app.islocked,app.personid AS whobookedpersonid,app.[subject],\r\n        att.personid,att.noshow,att.misccode,p.firstname,p.middlename,p.lastname,p.student_no,\r\n        acr.cancelreasontext,am.memotext,am.isencrypted,at.[description] AS apptypedescription,at.appointmentTypeGroupID,atg.[description] AS apptypegrouptitle,\r\n        ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM    attendees att LEFT JOIN appointments app ON app.AppointmentID=att.appointmentid \r\n        LEFT JOIN people p ON p.personid=att.personid \r\n        LEFT JOIN appointmenttypes at ON at.apptypeid=app.apptypeid \r\n        LEFT JOIN appointmenttypegroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID\r\n        LEFT JOIN appointmentshowtimeas ast ON ast.extraiconid=app.appcode \r\n        LEFT JOIN appointmentmemos am ON am.AppointmentID=app.AppointmentID\r\n        LEFT JOIN appointmentcancelledreason acr ON acr.appointmentid=att.appointmentid\r\nWHERE   att.personid=@pid \r\n        AND (@sd IS NULL OR (app.startDate>=@sd AND app.startDate<@ed))\r\n        AND (@apptypeids IS NULL OR app.apptypeid IN (SELECT apptypeid FROM #tapptypeids))\r\nORDER BY app.startDate DESC,att.appointmentid\r\n\r\nDROP TABLE #tapptypeids";
	}
}
