using System;

namespace TechnoPro.Common.DAO.Impl.DynamicForms.QueryStorage
{
	// Token: 0x020000E7 RID: 231
	public static class QueryStorageDataForReports
	{
		// Token: 0x040003EF RID: 1007
		internal const string QS_InstructorPM_DATA_BY_FIELDS_AND_EXAMIDS = "SELECT orderid AS personid INTO #texamids FROM splitorderids(COALESCE(@examids,''),',');\r\nSELECT orderid AS controlid INTO #tcids FROM splitorderids(COALESCE(@cids,''),',');\r\n\r\nSELECT    ps.appointmentid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\nFROM        perinstructordata2 ps LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.appointmentid IN (SELECT personid FROM #texamids)\r\n            AND ps.controlid IN (SELECT controlid FROM #tcids)\r\nORDER BY ps.appointmentid,ps.controlid\r\n\r\nDROP TABLE #texamids\r\nDROP TABLE #tcids";

		// Token: 0x040003F0 RID: 1008
		internal const string QS_PS_DATA_BY_FIELDS_AND_STUDENTS = "SELECT orderid AS personid INTO #t1 FROM splitorderids(@pids,',');\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',');\r\n\r\nSELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename,ps.uniqueid\r\nFROM        perstudentdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid IN (SELECT personid FROM #t1)\r\n            AND ps.controlid IN (SELECT controlid FROM #t2)\r\nORDER BY ps.personid,ps.controlid\r\n\r\nDROP TABLE #t1;\r\nDROP TABLE #t2";

		// Token: 0x040003F1 RID: 1009
		internal const string QS_PC_CASE_DATA_BY_FIELDS_AND_STUDENTS = "SELECT orderid AS personid INTO #t1 FROM splitorderids(@pids,',');\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',');\r\n\r\nSELECT    DISTINCT ps.infopcid AS personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,CAST(NULL AS varbinary(8000)) AS firstname,CAST(NULL AS varbinary(8000)) AS lastname,p.student_no,CAST(NULL AS varbinary(8000)) AS middlename,ps.uniqueid\r\nFROM        pcdata2 ps LEFT JOIN infopc p ON p.personid=ps.infopcid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.infopcid IN (SELECT personid AS infopcid FROM #t1)\r\n            AND ps.controlid IN (SELECT controlid FROM #t2)\r\nORDER BY ps.infopcid,ps.controlid\r\n\r\nDROP TABLE #t1;\r\nDROP TABLE #t2";

		// Token: 0x040003F2 RID: 1010
		internal const string QS_PA_DATA_BY_FIELDS_AND_STUDENTS_AND_APPOINTMENTS = "SELECT orderid1 AS personid,orderid2 AS appointmentid INTO #t1 FROM SplitOrderIDsMultiplex2(@contexts,',',':')\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',')\r\n        \r\n        SELECT    ps.personid,app.appointmentid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n                    ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n                    ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n                    ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n                    ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n                    ,p.firstname,p.lastname,p.student_no,p.middlename,ps.uniqueid\r\n        FROM        perappdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n                    LEFT JOIN appointments app ON app.appointmentid=ps.appointmentid\r\n                    LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\n        WHERE       EXISTS(SELECT personid FROM #t1 WHERE personid=ps.personid AND appointmentid=ps.appointmentid)\r\n                    AND ps.controlid IN (SELECT controlid FROM #t2)\r\n        ORDER BY ps.personid,app.appointmentid,ps.controlid\r\n        \r\n        DROP TABLE #t1;\r\n        DROP TABLE #t2";

		// Token: 0x040003F3 RID: 1011
		internal const string QS_PM_DATA_BY_FIELDS_AND_STUDENTS_AND_APPOINTMENTS = "SELECT orderid1 AS personid,orderid2 AS appointmentid INTO #t1 FROM SplitOrderIDsMultiplex2(@contexts,',',':')\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',')\r\n        \r\n        SELECT    ps.personid,ps.appointmentid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n                    ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n                    ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n                    ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n                    ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n                    ,p.firstname,p.lastname,p.student_no,p.middlename,ps.uniqueid\r\n        FROM        pmdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n                    --LEFT JOIN appointments app ON app.appointmentid=ps.appointmentid\r\n                    LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\n        WHERE       EXISTS(SELECT personid FROM #t1 WHERE personid=ps.personid AND appointmentid=ps.appointmentid)\r\n                    AND ps.controlid IN (SELECT controlid FROM #t2)\r\n        ORDER BY ps.personid,ps.appointmentid,ps.controlid\r\n        \r\n        DROP TABLE #t1;\r\n        DROP TABLE #t2";

		// Token: 0x040003F4 RID: 1012
		internal const string QS_ACCOMMODATION_TEMPLATE_DATA_BY_FIELDS_AND_STUDENTS = "SELECT orderid AS personid INTO #t1 FROM splitorderids(@pids,',');\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',');\r\n\r\nSELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename,ps.uniqueid\r\nFROM        accommodationdataactive ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid IN (SELECT personid FROM #t1)\r\n            AND ps.controlid IN (SELECT controlid FROM #t2)\r\n            AND ps.courseid=0 --template only\r\nORDER BY ps.personid,ps.controlid\r\n\r\nDROP TABLE #t1;\r\nDROP TABLE #t2";

		// Token: 0x040003F5 RID: 1013
		internal const string QS_ACCOMMODATION_TEMPLATE_AND_COURSES_DATA_BY_FIELDS_AND_STUDENTS = "SELECT orderid1 AS personid,orderid2 AS courseid INTO #t1 FROM SplitOrderIDsMultiplex2(@contexts,',',':')\r\nSELECT orderid AS controlid INTO #t2 FROM splitorderids(@cids,',')\r\n\r\nSELECT    ps.personid,ps.courseid AS appointmentid,ps.courseid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename,ps.uniqueid\r\nFROM        accommodationdataactive ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       EXISTS(SELECT personid FROM #t1 WHERE personid=ps.personid AND courseid=ps.courseid)\r\n            AND ps.controlid IN (SELECT controlid FROM #t2)\r\nORDER BY ps.personid,ps.courseid,ps.controlid\r\n\r\nDROP TABLE #t1\r\nDROP TABLE #t2";

		// Token: 0x040003F6 RID: 1014
		internal const string QS_BAREBONES_APPOINTMENTS_BY_PERSONID_AND_CONTROLIDS = "SELECT orderid AS personid INTO\t#tpids FROM splitorderids(@pids,',')\r\nSELECT orderid AS controlid INTO #tcids FROM splitorderids(@cids,',')\r\nSELECT DISTINCT screennum INTO #tscreennums FROM dynamicscreencontrols WHERE controlid IN (SELECT controlid FROM #tcids)\r\n\r\nSELECT DISTINCT at.apptypeid  INTO #tapptypeids\r\nFROM appointmenttypes at\r\nWHERE NOT at.perappscreennumsfortabs IS NULL AND NOT at.perappscreennumsfortabs='' \r\nAND EXISTS( SELECT orderid FROM splitorderids(at.perappscreennumsfortabs,',') WHERE orderid IN (SELECT screennum AS orderid FROM #tscreennums))\r\n\r\nSELECT\tDISTINCT att.personid,att.appointmentid,app.startdate,COALESCE(atg.title + ': ', '') + at.[description] AS [description],app.apptypeid\r\nFROM\tattendees att LEFT JOIN appointments app ON app.appointmentid=att.appointmentid\r\n\t\tLEFT JOIN appointmenttypes at ON at.apptypeid=app.apptypeid\r\n\t\tLEFT JOIN appointmenttypegroups atg on atg.AppointmentTypeGroupID=at.appointmentTypeGroupID\r\nWHERE\tatt.noshow=0\r\n\t\tAND att.personid IN (SELECT personid FROM #tpids)\r\n\t\tAND app.cancelled=0\r\n\t\tAND app.apptypeid IN (SELECT apptypeid FROM #tapptypeids)\r\nORDER BY att.personid,app.startdate\r\n\r\nDROP TABLE #tpids\r\nDROP TABLE #tcids\r\nDROP TABLE #tscreennums\r\nDROP TABLE #tapptypeids";

		// Token: 0x040003F7 RID: 1015
		internal const string QS_BAREBONES_PERDATEENTRIES_BY_PERSONID_AND_CONTROLIDS = "SELECT orderid AS personid INTO\t#tpids FROM splitorderids(@pids,',')\r\nSELECT orderid AS controlid INTO #tcids FROM splitorderids(@cids,',')\r\nSELECT DISTINCT screennum INTO #tscreennums FROM dynamicscreencontrols WHERE controlid IN (SELECT controlid FROM #tcids)\r\n\r\nSELECT\tpm.personid,pm.appointmentid,pm.[description],pm.dateentered,pm.dateentered AS startdate,pm.[description] AS title\r\nFROM\tinfopm pm \r\nWHERE\tpm.screennum IN (SELECT screennum FROM #tscreennums)\r\n\t\tAND pm.personid IN (SELECT personid FROM #tpids)\r\nORDER BY pm.personid,pm.dateentered\r\n\r\nDROP TABLE #tpids\r\nDROP TABLE #tcids\r\nDROP TABLE #tscreennums";
	}
}
