(function(b,a){a("kendo.treeview.draganddrop",["kendo.data","kendo.draganddrop"],b);
}(function(){var a={id:"treeview.draganddrop",name:"Hierarchical Drag & Drop",category:"framework",depends:["core","draganddrop"],advanced:true};
(function(b,j){var f=window.kendo;
var i=f.ui;
var h=b.proxy;
var d=b.extend;
var k="visibility";
var g="k-state-hover";
var e="input,a:not(.k-in),textarea,.k-multiselect-wrap,select,button,a.k-button>.k-icon,button.k-button>.k-icon,span.k-icon.k-i-arrow-60-right,span.k-icon.k-i-arrow-45-down-right";
var c="<div class='k-drop-hint k-drop-hint-h'><div class='k-drop-hint-start'></div><div class='k-drop-hint-line'></div></div>";
i.HierarchicalDragAndDrop=f.Class.extend({init:function(l,m){this.element=l;
this.hovered=l;
this.options=d({dragstart:b.noop,drag:b.noop,drop:b.noop,dragend:b.noop},m);
this._draggable=new i.Draggable(l,{ignore:e,filter:m.filter,autoScroll:m.autoScroll,cursorOffset:{left:10,top:f.support.mobileOS?-40/f.support.zoomLevel():10},hint:h(this._hint,this),dragstart:h(this.dragstart,this),dragcancel:h(this.dragcancel,this),drag:h(this.drag,this),dragend:h(this.dragend,this),$angular:m.$angular,holdToDrag:m.holdToDrag});
},_hint:function(m){var l="k-header k-drag-clue radHeader radDragClue";
var n=m.closest(".RadGantt")[0];
if(n&&n.control&&n.control._skin){l+=" radSkin_"+n.control._skin;
}return'<div class="'+l+'"><span class="k-icon k-drag-status radIcon radDragStatus"></span><span class="radDragClueText">'+this.options.hintText(m)+"</span></div>";
},_removeTouchHover:function(){if(f.support.touch&&this.hovered){this.hovered.find("."+g).removeClass(g);
this.hovered=false;
}},_hintStatus:function(l){var m=this._draggable.hint.find(".k-drag-status")[0];
if(l){m.className="k-icon k-drag-status "+l;
}else{return f.trim(m.className.replace(/(p|k)-(icon|drag-status)/g,""));
}},dragstart:function(l){this.source=l.currentTarget.closest(this.options.itemSelector);
if(this.options.dragstart(this.source)){l.preventDefault();
}if(this.options.reorderable){this.dropHint=b(c).css(k,"hidden").appendTo(this.element);
}else{this.dropHint=b();
}},drag:function(o){var w=this.options;
var y=this.source;
var A=this.dropTarget=b(f.eventTarget(o));
var m=A.closest(w.allowedContainers);
var p,u,v,s,n;
var r,q,l;
var t,x,z;
if(!m.length){z="k-i-cancel";
this._removeTouchHover();
}else{if(y[0]==A[0]||w.contains(y[0],A[0])){z="k-i-cancel";
}else{z="k-i-insert-middle";
t=w.itemFromTarget(A);
p=t.item;
if(p.length){this._removeTouchHover();
u=f._outerHeight(p);
s=t.content;
if(w.reorderable){n=u/(s.length>0?4:2);
v=f.getOffset(p).top;
r=o.y.location<v+n;
q=v+u-n<o.y.location;
l=s.length&&!r&&!q;
}else{l=true;
r=false;
q=false;
}this.hovered=l?m:false;
this.dropHint.css(k,l?"hidden":"visible");
if(this._lastHover&&this._lastHover[0]!=s[0]){this._lastHover.removeClass(g);
}this._lastHover=s.toggleClass(g,l);
if(l){z="k-i-plus";
}else{x=p.position();
x.top+=r?0:u;
this.dropHint.css(x)[r?"prependTo":"appendTo"](w.dropHintContainer(p));
if(r&&t.first){z="k-i-insert-up";
}if(q&&t.last){z="k-i-insert-down";
}}}else{if(A[0]!=this.dropHint[0]){if(this._lastHover){this._lastHover.removeClass(g);
}if(!b.contains(this.element[0],m[0])){z="k-i-plus";
}else{z="k-i-cancel";
}}}}}this.options.drag({originalEvent:o.originalEvent,source:y,target:A,pageY:o.y.location,pageX:o.x.location,status:z.substring(2),setStatus:function(B){z=B;
}});
if(z.indexOf("k-i-insert")!==0){this.dropHint.css(k,"hidden");
}this._hintStatus(z);
},dragcancel:function(){this.dropHint.remove();
},dragend:function(p){var r="over",s=this.source,l,m=this.dropHint,o=this.dropTarget,q,n;
if(m.css(k)=="visible"){r=this.options.dropPositionFrom(m);
l=m.closest(this.options.itemSelector);
}else{if(o){l=o.closest(this.options.itemSelector);
if(!l.length){l=o.closest(this.options.allowedContainers);
}}}q={originalEvent:p.originalEvent,source:s[0],destination:l[0],valid:this._hintStatus()!="k-i-cancel",setValid:function(t){this.valid=t;
},dropTarget:o[0],position:r};
n=this.options.drop(q);
m.remove();
this._removeTouchHover();
if(this._lastHover){this._lastHover.removeClass(g);
}if(!q.valid||n){this._draggable.dropped=q.valid;
return;
}this._draggable.dropped=true;
this.options.dragend({originalEvent:p.originalEvent,source:s,destination:l,position:r});
},destroy:function(){this._lastHover=this.hovered=null;
this._draggable.destroy();
}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
