using System;
using System.Diagnostics;
using System.Drawing;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;
using System.Web.Script;
using System.Web.UI;

[assembly: AssemblyVersion("4.0.0.0")]
[assembly: Dependency("System.Web,", LoadHint.Always)]
[assembly: InternalsVisibleTo("System.Web.Extensions.Test, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
[assembly: InternalsVisibleTo("System.Web.Extensions.Design, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: InternalsVisibleTo("System.ServiceModel.Web, PublicKey=0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9")]
[assembly: AjaxFrameworkAssembly]
[assembly: WebResource("MicrosoftAjax.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjax.js", LoadSuccessExpression = "window.Sys && Sys._Application && Sys.Observer")]
[assembly: WebResource("MicrosoftAjaxApplicationServices.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxApplicationServices.js", LoadSuccessExpression = "window.Sys && Sys.Services")]
[assembly: WebResource("MicrosoftAjaxComponentModel.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxComponentModel.js", LoadSuccessExpression = "window.Sys && Sys.CommandEventArgs")]
[assembly: WebResource("MicrosoftAjaxCore.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxCore.js", LoadSuccessExpression = "window.Type && Sys.Observer")]
[assembly: WebResource("MicrosoftAjaxGlobalization.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxGlobalization.js", LoadSuccessExpression = "window.Sys && Sys.CultureInfo")]
[assembly: WebResource("MicrosoftAjaxHistory.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxHistory.js", LoadSuccessExpression = "window.Sys && Sys.HistoryEventArgs")]
[assembly: WebResource("MicrosoftAjaxNetwork.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxNetwork.js", LoadSuccessExpression = "window.Sys && Sys.Net && Sys.Net.WebRequestExecutor")]
[assembly: WebResource("MicrosoftAjaxSerialization.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxSerialization.js", LoadSuccessExpression = "window.Sys && Sys.Serialization")]
[assembly: WebResource("MicrosoftAjaxTimer.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxTimer.js", LoadSuccessExpression = "window.Sys && Sys.UI && Sys.UI._Timer")]
[assembly: WebResource("MicrosoftAjaxWebForms.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxWebForms.js", LoadSuccessExpression = "window.Sys && Sys.WebForms")]
[assembly: WebResource("MicrosoftAjaxWebServices.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxWebServices.js", LoadSuccessExpression = "window.Sys && Sys.Net && Sys.Net.WebServiceProxy")]
[assembly: WebResource("Date.HijriCalendar.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/Date.HijriCalendar.js", LoadSuccessExpression = "window.Type && Type._registerScript && Type._registerScript._scripts && Type._registerScript._scripts['Date.HijriCalendar.js']")]
[assembly: WebResource("Date.UmAlQuraCalendar.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/Date.UmAlQuraCalendar.js", LoadSuccessExpression = "window.Type && Type._registerScript && Type._registerScript._scripts && Type._registerScript._scripts['Date.UmAlQuraCalendar.js']")]
[assembly: WebResource("MicrosoftAjax.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjax.debug.js", LoadSuccessExpression = "window.Sys && Sys._Application && Sys.Observer")]
[assembly: WebResource("MicrosoftAjaxApplicationServices.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxApplicationServices.debug.js", LoadSuccessExpression = "window.Sys && Sys.Services")]
[assembly: WebResource("MicrosoftAjaxComponentModel.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxComponentModel.debug.js", LoadSuccessExpression = "window.Sys && Sys.CommandEventArgs")]
[assembly: WebResource("MicrosoftAjaxCore.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxCore.debug.js", LoadSuccessExpression = "window.Type && Sys.Observer")]
[assembly: WebResource("MicrosoftAjaxGlobalization.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxGlobalization.debug.js", LoadSuccessExpression = "window.Sys && Sys.CultureInfo")]
[assembly: WebResource("MicrosoftAjaxHistory.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxHistory.debug.js", LoadSuccessExpression = "window.Sys && Sys.HistoryEventArgs")]
[assembly: WebResource("MicrosoftAjaxNetwork.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxNetwork.debug.js", LoadSuccessExpression = "window.Sys && Sys.Net && Sys.Net.WebRequestExecutor")]
[assembly: WebResource("MicrosoftAjaxSerialization.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxSerialization.debug.js", LoadSuccessExpression = "window.Sys && Sys.Serialization")]
[assembly: WebResource("MicrosoftAjaxTimer.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxTimer.debug.js", LoadSuccessExpression = "window.Sys && Sys.UI && Sys.UI._Timer")]
[assembly: WebResource("MicrosoftAjaxWebForms.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxWebForms.debug.js", LoadSuccessExpression = "window.Sys && Sys.WebForms")]
[assembly: WebResource("MicrosoftAjaxWebServices.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjaxWebServices.debug.js", LoadSuccessExpression = "window.Sys && Sys.Net && Sys.Net.WebServiceProxy")]
[assembly: WebResource("Date.HijriCalendar.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/Date.HijriCalendar.debug.js", LoadSuccessExpression = "window.Type && Type._registerScript && Type._registerScript._scripts && Type._registerScript._scripts['Date.HijriCalendar.js']")]
[assembly: WebResource("Date.UmAlQuraCalendar.debug.js", "application/x-javascript", CdnSupportsSecureConnection = true, CdnPath = "http://ajax.aspnetcdn.com/ajax/4.6/1/Date.UmAlQuraCalendar.debug.js", LoadSuccessExpression = "window.Type && Type._registerScript && Type._registerScript._scripts && Type._registerScript._scripts['Date.UmAlQuraCalendar.js']")]
[assembly: ScriptResource("MicrosoftAjax.js", "System.Web.Resources.ScriptLibrary.Res", "Sys.Res")]
[assembly: ScriptResource("MicrosoftAjax.debug.js", "System.Web.Resources.ScriptLibrary.Res.debug", "Sys.Res")]
[assembly: ScriptResource("MicrosoftAjaxCore.js", "System.Web.Resources.ScriptLibrary.Res", "Sys.Res")]
[assembly: ScriptResource("MicrosoftAjaxCore.debug.js", "System.Web.Resources.ScriptLibrary.Res.debug", "Sys.Res")]
[assembly: ScriptResource("MicrosoftAjaxWebForms.js", "System.Web.Resources.ScriptLibrary.WebForms.Res", "Sys.WebForms.Res")]
[assembly: ScriptResource("MicrosoftAjaxWebForms.debug.js", "System.Web.Resources.ScriptLibrary.WebForms.Res.debug", "Sys.WebForms.Res")]
[assembly: TagPrefix("System.Web.UI", "asp")]
[assembly: TagPrefix("System.Web.UI.WebControls", "asp")]
[assembly: BitmapSuffixInSatelliteAssembly]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AllowPartiallyTrustedCallers(PartialTrustVisibilityLevel = PartialTrustVisibilityLevel.NotVisibleByDefault)]
[assembly: SecurityRules(SecurityRuleSet.Level2, SkipVerificationInFullTrust = true)]
[assembly: AssemblyTitle("System.Web.Extensions.dll")]
[assembly: AssemblyDescription("System.Web.Extensions.dll")]
[assembly: AssemblyDefaultAlias("System.Web.Extensions.dll")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("4.8.9319.0")]
[assembly: AssemblyInformationalVersion("4.8.9319.0")]
[assembly: SatelliteContractVersion("4.0.0.0")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyDelaySign(true)]
[assembly: AssemblyKeyFile("f:\\dd\\tools\\devdiv\\35MSSharedLib1024.snk")]
[assembly: DefaultDllImportSearchPaths(DllImportSearchPath.System32 | DllImportSearchPath.AssemblyDirectory)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, Execution = true)]
