(function(b,a){a("kendo.gantt.data",["kendo.data","kendo.treelist"],b);
}(function(){var a={id:"gantt.data",name:"GanttData",category:"web",description:"The Gantt Data.",depends:["data","treelist"],hidden:true};
(function(b,r){var k=b.isArray,f=b.extend,m=b.map,l=kendo.data,o=l.Query,d=l.DataSource,p=l.TreeListDataSource,q=l.TreeListModel,n="parentId";
var c=function(t,s){return function(w){w=k(w)?{data:w}:w;
var v=w||{};
var u=v.data;
v.data=u;
if(!(v instanceof t)&&v instanceof d){throw new Error("Incorrect DataSource type. Only "+s+" instances are supported");
}return v instanceof t?v:new t(v);
};
};
var e=function(w){if(w.filter("[name=end], [name=start], [name=plannedEnd], [name=plannedStart]").length){var v=w.attr("name"),y=kendo.widgetInstance(w,kendo.ui),t={},s=w,u,x;
while(s!==window&&!u){s=s.parent();
u=s.data("kendoEditable");
}x=u?u.options.model:null;
if(!x){return true;
}if(v.indexOf("planned")>=0){t.plannedStart=x.plannedStart;
t.plannedEnd=x.plannedEnd;
}else{t.start=x.start;
t.end=x.end;
}t[v]=y?y.value():kendo.parseDate(w.val());
if(v.indexOf("planned")>=0){return t.plannedStart<=t.plannedEnd;
}else{return t.start<=t.end;
}}return true;
};
var h=kendo.data.Model.define({id:"id",fields:{id:{type:"number",editable:false},predecessorId:{type:"number"},successorId:{type:"number"},type:{type:"number"}}});
var i=d.extend({init:function(s){d.fn.init.call(this,f(true,{},{schema:{modelBase:h,model:h}},s));
},dependencies:function(s){var t=this.predecessors(s),u=this.successors(s);
t.push.apply(t,u);
return t;
},predecessors:function(s){return this._dependencies("successorId",s);
},successors:function(s){return this._dependencies("predecessorId",s);
},_dependencies:function(t,v){var s=this.view();
var u={field:t,operator:"eq",value:v};
s=new o(s).filter(u).toArray();
return s;
}});
i.create=c(i,"GanttDependencyDataSource");
var j=q.define({fields:{id:{type:"number",editable:false},parentId:{type:"number",defaultValue:null,validation:{required:true},nullable:true},orderId:{type:"number",validation:{required:true}},title:{type:"string",defaultValue:"New task"},start:{type:"date",validation:{required:true}},end:{type:"date",validation:{required:true,dateCompare:e,message:"End date should be after or equal to the start date"}},percentComplete:{type:"number",validation:{required:true,min:0,max:1,step:0.01}},summary:{type:"boolean"},expanded:{type:"boolean",defaultValue:true},plannedStart:{type:"date",defaultValue:null,nullable:true},plannedEnd:{type:"date",defaultValue:null,nullable:true,validation:{dateCompare:e,message:"Planned end date should be after or equal to the planned start date"}}},duration:function(){var s=this.end,t=this.start;
return s-t;
},isMilestone:function(){return this.duration()===0;
},_offset:function(v){var s=["start","end"],u;
for(var t=0;
t<s.length;
t++){u=new Date(this.get(s[t]).getTime()+v);
this.set(s[t],u);
}},_offsetPlanned:function(v){var s=["plannedStart","plannedEnd"],u;
for(var t=0;
t<s.length;
t++){u=new Date(this.get(s[t]).getTime()+v);
this.set(s[t],u);
}}});
j.define=function(s,u){if(u===r){u=s;
s=j;
}var v=u.parentId||n;
u.parentIdField=v;
var t=q.define(s,u);
if(v){t.parentIdField=v;
}return t;
};
var g=p.extend({init:function(s){p.fn.init.call(this,f(true,{},{schema:{modelBase:j,model:j},sort:{field:"orderId",dir:"asc"}},s));
},add:function(s){if(!s){return;
}s=this._toGanttTask(s);
return this.insert(this.taskSiblings(s).length,s);
},insert:function(s,t){if(!t){return;
}t=this._toGanttTask(t);
t.set("orderId",s);
t=d.fn.insert.call(this,s,t);
this._reorderSiblings(t,this.taskSiblings(t).length-1);
this._resolveSummaryFields(this.taskParent(t));
return t;
},remove:function(u){var t=u.get("parentId"),s=this.taskAllChildren(u);
this._removeItems(s);
u=p.fn.remove.call(this,u);
this._childRemoved(t,u.get("orderId"));
return u;
},taskAllChildren:function(u){var t=[],v=this;
var s=function(w){var x=v.taskChildren(w);
t.push.apply(t,x);
m(x,s);
};
if(!!u){s(u);
}else{t=this.view();
}return t;
},taskChildren:function(v){var s=this.view();
var t={field:"parentId",operator:"eq",value:null};
var u=this._sort&&this._sort.length?this._sort:{field:"orderId",dir:"asc"};
var w;
if(!!v){w=v.get("id");
if(w===r||w===null||w===""){return[];
}t.value=w;
}s=new o(s).filter(t).sort(u).toArray();
return s;
},taskLevel:function(u){var s=0,t=this.taskParent(u);
while(t!==null){s+=1;
t=this.taskParent(t);
}return s;
},taskParent:function(s){if(!s||s.get("parentId")===null){return null;
}return this.get(s.parentId);
},taskSiblings:function(t){if(!t){return null;
}var s=this.taskParent(t);
return this.taskChildren(s);
},taskTree:function(x){var u=[],t,y=this.taskChildren(x);
for(var v=0,w=y.length;
v<w;
v++){t=y[v];
u.push(t);
if(t.get("expanded")){var s=this.taskTree(t);
u.push.apply(u,s);
}}return u;
},update:function(x,y){var z=this,w;
var u=function(E,D){var A=z.taskAllChildren(E);
for(var B=0,C=A.length;
B<C;
B++){A[B]._offset(D);
}};
var v=function(E,D){var A=z.taskAllChildren(E);
for(var B=0,C=A.length;
B<C;
B++){A[B]._offsetPlanned(D);
}};
var t=function(A){var B=A.field,C=A.sender;
switch(B){case"start":z._resolveSummaryStart(z.taskParent(C));
u(C,C.get(B).getTime()-w.getTime());
break;
case"end":z._resolveSummaryEnd(z.taskParent(C));
break;
case"plannedStart":z._resolveSummaryPlannedStart(z.taskParent(C));
if(C.get(B)&&w){v(C,C.get(B).getTime()-w.getTime());
}break;
case"plannedEnd":z._resolveSummaryPlannedEnd(z.taskParent(C));
break;
case"percentComplete":z._resolveSummaryPercentComplete(z.taskParent(C));
break;
case"orderId":z._reorderSiblings(C,w);
break;
}};
if(y.parentId!==r){w=x.get("parentId");
if(w!==y.parentId){x.set("parentId",y.parentId);
z._childRemoved(w,x.get("orderId"));
x.set("orderId",z.taskSiblings(x).length-1);
z._resolveSummaryFields(z.taskParent(x));
}delete y.parentId;
}x.bind("change",t);
for(var s in y){w=x.get(s);
if(s==="plannedStart"||s==="plannedEnd"){if(w!==r||y[s]!==null){x.set(s,y[s]);
}}else{x.set(s,y[s]);
}}x.unbind("change",t);
},_childRemoved:function(x,u){var w=x===null?null:this.get(x),s=this.taskChildren(w);
for(var t=u,v=s.length;
t<v;
t++){s[t].set("orderId",t);
}this._resolveSummaryFields(w);
},_resolveSummaryFields:function(s){if(!s){return;
}this._updateSummary(s);
if(!this.taskChildren(s).length){return;
}this._resolveSummaryStart(s);
this._resolveSummaryEnd(s);
this._resolveSummaryPlannedStart(s);
this._resolveSummaryPlannedEnd(s);
this._resolveSummaryPercentComplete(s);
},_resolveSummaryStart:function(t){var u=this;
var s=function(A){var v=u.taskChildren(A);
var z=v[0].start.getTime();
var w;
for(var x=1,y=v.length;
x<y;
x++){w=v[x].start.getTime();
if(w<z){z=w;
}}return new Date(z);
};
this._updateSummaryRecursive(t,"start",s);
},_resolveSummaryEnd:function(t){var u=this;
var s=function(A){var v=u.taskChildren(A);
var z=v[0].end.getTime();
var w;
for(var x=1,y=v.length;
x<y;
x++){w=v[x].end.getTime();
if(w>z){z=w;
}}return new Date(z);
};
this._updateSummaryRecursive(t,"end",s);
},_resolveSummaryPlannedStart:function(t){var u=this;
var s=function(A){var v=u.taskChildren(A),z=null,w;
for(var x=0,y=v.length;
x<y;
x++){if(v[x].plannedStart){w=v[x].plannedStart.getTime();
if(!z||w<z){z=w;
}}}if(!z){return null;
}return new Date(z);
};
this._updateSummaryRecursive(t,"plannedStart",s);
},_resolveSummaryPlannedEnd:function(t){var u=this;
var s=function(A){var v=u.taskChildren(A),z=null,w;
for(var x=0,y=v.length;
x<y;
x++){if(v[x].plannedEnd){w=v[x].plannedEnd.getTime();
if(!z||w>z){z=w;
}}}if(!z){return null;
}return new Date(z);
};
this._updateSummaryRecursive(t,"plannedEnd",s);
},_resolveSummaryPercentComplete:function(t){var u=this;
var s=function(w){var v=u.taskChildren(w);
var x=new o(v).aggregate([{field:"percentComplete",aggregate:"average"}]);
return x.percentComplete.average;
};
this._updateSummaryRecursive(t,"percentComplete",s);
},_reorderSiblings:function(A,w){var x=A.get("orderId"),s=x>w,z=s?w:x,t=s?x:w,v=s?z:z+1,y=this.taskSiblings(A);
if(!y.length){return;
}t=Math.min(t,y.length-1);
for(var u=z;
u<=t;
u++){if(y[u]===A){continue;
}y[u].set("orderId",v);
v+=1;
}},_toGanttTask:function(s){if(!(s instanceof j)){var t=s;
s=d.fn._createNewModel.call(this);
s.accept(t);
}return s;
},_updateSummary:function(t){if(t!==null){var s=this.taskChildren(t).length;
t.set("summary",s>0);
}},_updateSummaryRecursive:function(v,t,s){if(!v){return;
}var w=s(v);
v.set(t,w);
var u=this.taskParent(v);
if(u){this._updateSummaryRecursive(u,t,s);
}}});
g.create=c(g,"GanttDataSource");
f(true,kendo.data,{GanttDataSource:g,GanttTask:j,GanttDependencyDataSource:i,GanttDependency:h});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
