(function(b,a){a("util/text-metrics",["kendo.core"],b);
}(function(){(function(a){window.kendo.util=window.kendo.util||{};
var e=kendo.Class.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,p){var o=this._map;
var m={key:n,value:p};
o[n]=m;
if(!this._head){this._head=this._tail=m;
}else{this._tail.newer=m;
m.older=this._tail;
this._tail=m;
}if(this._length>=this._size){o[this._head.key]=null;
this._head=this._head.newer;
this._head.older=null;
}else{this._length++;
}},get:function(n){var m=this._map[n];
if(m){if(m===this._head&&m!==this._tail){this._head=m.newer;
this._head.older=null;
}if(m!==this._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=this._tail;
m.newer=null;
this._tail.newer=m;
this._tail=m;
}return m.value;
}}});
var i=/\r?\n|\r|\t/g;
var j=" ";
function g(m){return String(m).replace(i,j);
}function h(n){var o=[];
for(var m in n){o.push(m+n[m]);
}return o.sort().join("");
}function d(o){var m=2166136261;
for(var n=0;
n<o.length;
++n){m+=(m<<1)+(m<<4)+(m<<7)+(m<<8)+(m<<24);
m^=o.charCodeAt(n);
}return m>>>0;
}function l(){return{width:0,height:0,baseline:0};
}var b={baselineMarkerSize:1};
var c;
if(typeof document!=="undefined"){c=document.createElement("div");
c.style.cssText="position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: pre!important;";
}var k=kendo.Class.extend({init:function(m){this._cache=new e(1000);
this.options=a.extend({},b,m);
},measure:function(v,t,r){if(r===void 0){r={};
}if(!v){return l();
}var u=h(t);
var o=d(v+u);
var n=this._cache.get(o);
if(n){return n;
}var s=l();
var q=r.box||c;
var m=this._baselineMarker().cloneNode(false);
for(var p in t){var x=t[p];
if(typeof x!=="undefined"){q.style[p]=x;
}}var w=r.normalizeText!==false?g(v):String(v);
q.textContent=w;
q.appendChild(m);
document.body.appendChild(q);
if(w.length){s.width=q.offsetWidth-this.options.baselineMarkerSize;
s.height=q.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(o,s);
}q.parentNode.removeChild(q);
return s;
},_baselineMarker:function(){var m=document.createElement("div");
m.style.cssText="display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;";
return m;
}});
k.current=new k();
function f(o,n,m){return k.current.measure(o,n,m);
}kendo.deepExtend(kendo.util,{LRUCache:e,TextMetrics:k,measureText:f,objectKey:h,hashKey:d,normalizeText:g});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.gantt.editors",["kendo.data","kendo.popup","kendo.window","kendo.gantt.data","kendo.grid","kendo.datetimepicker","kendo.numerictextbox"],b);
}(function(){var a={id:"gantt.editors",name:"GanttEditors",category:"web",description:"The Gantt component editors.",depends:["data","popup","window","gantt.data","grid","datetimepicker","numerictextbox"],hidden:true};
(function(b,D){var o=window.kendo,C=o.ui,e=o.support.browser,r=o.Observable,E=C.Widget,s=o._outerWidth,p=b.extend({F10:121},o.keys),v=b.proxy,l=b.extend,n=b.isPlainObject,q=".kendoGantt",t="p0",z="tabIndex",f="click",F="width",y="string",d="aria-activedescendant",c="action-option-focused",i=".",h={down:{origin:"bottom left",position:"top left"},up:{origin:"top left",position:"bottom left"}},A=o.template('<div class="#=styles.popupWrapper#"><ul class="#=styles.popupList#" role="listbox">#for(var i = 0, l = actions.length; i < l; i++){#<li class="#=styles.item#" data-action="#=actions[i].data#" role="option">#=actions[i].text#</span>#}#</ul></div>');
var m={buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",focused:"k-state-focused",gridContent:"k-grid-content",hovered:"k-state-hover",item:"k-item",popupWrapper:"k-list-container",popupList:"k-list k-reset",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},primary:"k-primary",toolbar:{appendButton:"k-gantt-create"}};
var g=function(H,I){var G={name:I.field,title:I.title};
var J=I.model.fields[I.field].validation;
if(J&&n(J)&&J.message){G[o.attr("dateCompare-msg")]=J.message;
}b('<input type="text" required '+o.attr("type")+'="date" '+o.attr("role")+'="datetimepicker" '+o.attr("bind")+'="value:'+I.field+'" '+o.attr("validate")+"='true' />").attr(G).appendTo(H);
b("<span "+o.attr("for")+'="'+I.field+'" class="k-invalid-msg"/>').hide().appendTo(H);
};
var x=function(G,H){b('<a href="#" class="'+H.styles.button+'">'+H.messages.assignButton+"</a>").click(H.click).appendTo(G);
};
var B=r.extend({init:function(G,H){r.fn.init.call(this);
this.element=G;
this.options=l(true,{},this.options,H);
this._popup();
},options:{direction:"down",navigatable:false},destroy:function(){clearTimeout(this._focusTimeout);
this.popup.destroy();
this.element.off(q);
this.list.off(q);
this.unbind();
},_adjustListWidth:function(){var I=this.list;
var K=I[0].style.width;
var L=this.element;
var J=s(I);
var G;
var H;
if(!I.data(F)&&K){return;
}G=window.getComputedStyle?window.getComputedStyle(L[0],null):0;
H=G?parseFloat(G.width):s(L);
if(G&&(e.mozilla||e.msie)){H+=parseFloat(G.paddingLeft)+parseFloat(G.paddingRight)+parseFloat(G.borderLeftWidth)+parseFloat(G.borderRightWidth);
}if(I.css("box-sizing")!=="border-box"){K=H-(s(I)-I.width());
}else{K=H;
}if(J>K){K=J;
}I.css({fontFamily:L.css("font-family"),width:K}).data(F,K);
},_current:function(H){var G=this.list.find(i+C.Gantt.styles.focused);
var I=G[H]();
if(I.length){G.removeClass(C.Gantt.styles.focused).removeAttr("id");
I.addClass(C.Gantt.styles.focused).attr("id",c);
this.list.find("ul").removeAttr(d).attr(d,c);
}},_popup:function(){var J=this;
var H="li"+i+C.Gantt.styles.item;
var G=this.options.messages.actions;
var I=this.options.navigatable;
this.list=b(A({styles:C.Gantt.styles,actions:[{data:"add",text:G.addChild},{data:"insert-before",text:G.insertBefore},{data:"insert-after",text:G.insertAfter}]}));
this.element.append(this.list);
this.popup=new o.ui.Popup(this.list,l({anchor:this.element,open:function(){J._adjustListWidth();
},animation:this.options.animation},h[this.options.direction]));
this.element.on(f+q,function(L){var M=b(this);
var K=M.attr(o.attr("action"));
L.preventDefault();
if(K){J.trigger("command",{type:K});
}else{J.popup.open();
if(I){J.list.find("li:first").addClass(C.Gantt.styles.focused).attr("id",c).end().find("ul").attr({TABINDEX:0,"aria-activedescendant":c}).focus();
}}});
this.list.find(H).hover(function(){b(this).addClass(C.Gantt.styles.hovered);
},function(){b(this).removeClass(C.Gantt.styles.hovered);
}).end().on(f+q,H,function(){J.trigger("command",{type:b(this).attr(o.attr("action"))});
J.popup.close();
});
if(I){this.popup.bind("close",function(){J.list.find(H).removeClass(C.Gantt.styles.focused).end().find("ul").attr(z,0);
J.element.parents("["+o.attr("role")+'="gantt"]').find(i+C.Gantt.styles.gridContent+" > table:first").focus();
});
this.list.find("ul").on("keydown"+q,function(K){var L=K.keyCode;
switch(L){case p.UP:K.preventDefault();
J._current("prev");
break;
case p.DOWN:K.preventDefault();
J._current("next");
break;
case p.ENTER:J.list.find(i+C.Gantt.styles.focused).click();
break;
case p.ESC:K.preventDefault();
J.popup.close();
break;
}});
}}});
var k={desktop:{dateRange:g,resources:x}};
var j=o.Observable.extend({init:function(G,H){o.Observable.fn.init.call(this);
this.element=G;
this.options=l(true,{},this.options,H);
this.createButton=this.options.createButton;
},fields:function(H,K,M){var O=this;
var L=this.options;
var J=L.messages.editor;
var N=L.resources;
var I;
var G=function(P){P.preventDefault();
N.editor(O.container.find(i+C.Gantt.styles.popup.resourcesField),K);
};
if(L.editable.template){I=b.map(K.fields,function(Q,P){return{field:P};
});
}else{I=[{field:"title",title:J.title},{field:"start",title:J.start,editor:H.dateRange},{field:"end",title:J.end,editor:H.dateRange},{field:"percentComplete",title:J.percentComplete,format:t}];
if(M){I.splice.apply(I,[1,0].concat([{field:"plannedStart",title:J.plannedStart,editor:H.dateRange},{field:"plannedEnd",title:J.plannedEnd,editor:H.dateRange}]));
}if(K.get(N.field)){I.push({field:N.field,title:J.resources,messages:J,editor:H.resources,click:G,styles:C.Gantt.styles.popup});
}}return I;
},_buildEditTemplate:function(M,I,G){var P=this.options.resources;
var R=this.options.editable.template;
var Q=l({},o.Template,this.options.templateSettings);
var N=Q.paramName;
var O=C.Gantt.styles.popup;
var J="";
if(R){if(typeof R===y){R=o.unescape(R);
}J+=o.template(R,Q)(M);
}else{for(var K=0,L=I.length;
K<L;
K++){var H=I[K];
J+='<div class="'+O.editLabel+'"><label for="'+H.field+'">'+(H.title||H.field||"")+"</label></div>";
if(H.field===P.field){J+='<div class="'+O.resourcesField+'" style="display:none"></div>';
}if(!M.editable||M.editable(H.field)){G.push(H);
J+="<div "+o.attr("container-for")+'="'+H.field+'" class="'+O.editField+'"></div>';
}else{var S="#:";
if(H.field){H=o.expr(H.field,N);
S+=H+"==null?'':"+H;
}else{S+="''";
}S+="#";
S=o.template(S,Q);
J+='<div class="'+O.editField+'">'+S(M)+"</div>";
}}}return J;
}});
var u=j.extend({destroy:function(){this.close();
this.unbind();
},close:function(){var H=this;
var G=function(){if(H.editable){H.editable.destroy();
H.editable=null;
H.container=null;
}if(H.popup){H.popup.destroy();
H.popup=null;
}};
if(this.editable&&this.container.is(":visible")){H.trigger("close",{window:H.container});
this.container.data("kendoWindow").bind("deactivate",G).close();
}else{G();
}},editTask:function(H,G){this.editable=this._createPopupEditor(H,G);
},showDialog:function(K){var G=K.buttons;
var M=C.Gantt.styles.popup;
var H=o.format('<div class="{0}"><div class="{1}"><p class="{2}">{3}</p><div class="{4}">',M.form,M.formContainer,M.message,K.text,M.buttonsContainer);
for(var I=0,J=G.length;
I<J;
I++){H+=this.createButton(G[I]);
}H+="</div></div></div>";
var N=this.element;
if(this.popup){this.popup.destroy();
}var L=this.popup=b(H).appendTo(N).eq(0).on("click",i+M.button,function(P){P.preventDefault();
L.close();
var O=b(P.currentTarget).index();
G[O].click();
}).kendoWindow({modal:true,autoFocus:false,resizable:false,draggable:false,title:K.title,visible:false,deactivate:function(){this.destroy();
N.focus();
}}).getKendoWindow();
L.center().open();
L.element.find("."+C.Gantt.styles.primary).focus();
},_createPopupEditor:function(P,N){var Q=this;
var M={};
var L=this.options.messages;
var O=C.Gantt.styles.popup;
var K=o.format('<div {0}="{1}" class="{2} {3}"><div class="{4}">',o.attr("uid"),P.uid,O.form,O.editForm,O.formContainer);
var J=this.fields(k.desktop,P,N);
var H=[];
K+=this._buildEditTemplate(P,J,H);
K+='<div class="'+O.buttonsContainer+'">';
K+=this.createButton({name:"update",text:L.save,className:C.Gantt.styles.primary});
K+=this.createButton({name:"cancel",text:L.cancel});
if(Q.options.editable.destroy!==false){K+=this.createButton({name:"delete",text:L.destroy});
}K+="</div></div></div>";
var G=this.container=b(K).appendTo(this.element).eq(0).kendoWindow(l({modal:true,resizable:false,draggable:true,title:L.editor.editorTitle,visible:false,close:function(R){if(R.userTriggered){if(Q.trigger("cancel",{container:G,model:P})){R.preventDefault();
}}}},M));
var I=G.kendoEditable({fields:H,model:P,clearContainer:false,validateOnBlur:true,target:Q.options.target}).data("kendoEditable");
o.cycleForm(G);
if(!this.trigger("edit",{container:G,model:P})){G.data("kendoWindow").center().open();
G.on(f+q,i+C.Gantt.styles.buttonCancel,function(R){R.preventDefault();
R.stopPropagation();
Q.trigger("cancel",{container:G,model:P});
});
G.on(f+q,i+C.Gantt.styles.buttonSave,function(R){R.preventDefault();
R.stopPropagation();
var T=Q.fields(k.desktop,P,N);
var W={};
var S;
for(var U=0,V=T.length;
U<V;
U++){S=T[U].field;
W[S]=P.get(S);
}Q.trigger("save",{container:G,model:P,updateInfo:W});
});
G.on(f+q,i+C.Gantt.styles.buttonDelete,function(R){R.preventDefault();
R.stopPropagation();
Q.trigger("remove",{container:G,model:P});
});
}else{Q.trigger("cancel",{container:G,model:P});
}return I;
}});
var w=E.extend({init:function(G,H){E.fn.init.call(this,G,H);
this.wrapper=this.element;
this.model=this.options.model;
this.resourcesField=this.options.resourcesField;
this.createButton=this.options.createButton;
this._initContainer();
this._attachHandlers();
},events:["save"],close:function(){this.window.bind("deactivate",v(this.destroy,this)).close();
},destroy:function(){this._dettachHandlers();
this.grid.destroy();
this.grid=null;
this.window.destroy();
this.window=null;
E.fn.destroy.call(this);
o.destroy(this.wrapper);
this.element=this.wrapper=null;
},open:function(){this.window.center().open();
},_attachHandlers:function(){var H=this.grid;
var G=this._cancelProxy=v(this._cancel,this);
this.container.on(f+q,i+C.Gantt.styles.buttonCancel,this._cancelProxy);
this._saveProxy=v(this._save,this);
this.container.on(f+q,i+C.Gantt.styles.buttonSave,this._saveProxy);
this.window.bind("close",function(I){if(I.userTriggered){G(I);
}});
H.wrapper.on(f+q,"input[type='checkbox']",function(){var I=b(this);
var K=b(I).closest("tr");
var J=H.dataSource.getByUid(K.attr(o.attr("uid")));
var L=b(I).is(":checked")?1:"";
J.set("value",L);
});
},_cancel:function(G){G.preventDefault();
this.close();
},_createButtons:function(){var G=this.options.buttons;
var H='<div class="'+C.Gantt.styles.popup.buttonsContainer+'">';
for(var I=0,J=G.length;
I<J;
I++){H+=this.createButton(G[I]);
}H+="</div>";
this.container.append(H);
},_dettachHandlers:function(){this._cancelProxy=null;
this._saveProxy=null;
this.container.off(q);
this.grid.wrapper.off();
},_initContainer:function(){var I=this;
var H=C.Gantt.styles.popup;
var G=o.format('<div class="{0} {1}"><div class="{2} {3}"></div></div>"',H.form,H.editForm,H.formContainer,H.resourcesFormContainer);
G=b(G);
this.container=G.find(i+H.resourcesFormContainer);
this.window=G.kendoWindow({modal:true,resizable:false,draggable:true,visible:false,title:this.options.messages.resourcesEditorTitle,open:function(){I.grid.resize(true);
}}).data("kendoWindow");
this._resourceGrid();
this._createButtons();
},_resourceGrid:function(){var I=this;
var H=this.options.messages;
var G=b('<div id="resources-grid"/>').appendTo(this.container);
this.grid=new o.ui.Grid(G,{columns:[{field:"name",title:H.resourcesHeader,template:"<label><input type='checkbox' value='#=name#'# if (value > 0 && value !== null) {#checked='checked'# } #/>#=name#</labe>"},{field:"value",title:H.unitsHeader,template:function(J){var L=J.format;
var K=J.value!==null?J.value:"";
return L?o.toString(K,L):K;
}}],height:280,sortable:true,editable:true,filterable:true,dataSource:{data:I.options.data,schema:{model:{id:"id",fields:{id:{from:"id"},name:{from:"name",type:"string",editable:false},value:{from:"value",type:"number",validation:this.options.unitsValidation},format:{from:"format",type:"string"}}}}},save:function(J){var K=!!J.values.value;
J.container.parent().find("input[type='checkbox']").prop("checked",K);
}});
},_save:function(G){G.preventDefault();
this._updateModel();
if(!this.wrapper.is(i+C.Gantt.styles.popup.resourcesField)){this.trigger("save",{container:this.wrapper,model:this.model});
}this.close();
},_updateModel:function(){var J=[];
var K;
var G=this.grid.dataSource.data();
for(var H=0,I=G.length;
H<I;
H++){K=G[H].get("value");
if(K!==null&&K>0){J.push(G[H]);
}}this.model[this.resourcesField]=J;
}});
o.gantt={TaskDropDown:B,Editor:j,PopupEditor:u,ResourceEditor:w};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
