(function(b,a){a("kendo.gantt.list",["kendo.treelist","kendo.treeview.draganddrop"],b);
}(function(){var a={id:"gantt.list",name:"Gantt List",category:"web",description:"The Gantt List",depends:["treelist","treeview.draganddrop"],hidden:true};
(function(b){var l=b.extend,v=b.map,A=b.proxy,q=b.isFunction,H=kendo.ui,G=H.TreeList,z=kendo._outerHeight,c=kendo._activeElement,s=kendo.keys,w=kendo.support.mobileOS,g=kendo.attr("type"),e=kendo.attr("bind"),o=kendo.attr("format"),E="string",y=".kendoGanttList",j="dblclick",m="focusin",n="focusout",r="keydown",t="keyup",x="mousedown",d="beforeEdit",k="edit",C="save",f="cancel",B="render",i=".",h="{0:"+kendo.getCulture().calendar.patterns.d+"}",F={title:"Title",start:"Start Time",end:"End Time",percentComplete:"% Done",parentId:"Predecessor ID",id:"ID",orderId:"Order ID"},D="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>",u={gridHeader:"k-grid-header",gridContentWrap:"k-grid-content",editCell:"k-edit-cell",iconCollapse:"k-i-collapse",iconExpand:"k-i-expand"};
var p=H.GanttList=G.extend({init:function(I,J){if(this.options.columns.length===0){this.options.columns.push("title");
}G.fn.init.call(this,I,J);
this._unbindDataSource();
this._adjustHeight();
this._setWidth();
},options:{name:"GanttList",autoBind:false,sortable:true,selectable:true,navigatable:false,editable:{move:true,mode:"incell"},resizable:false,renderAllRows:false},destroy:function(){G.fn.destroy.call(this);
kendo.destroy(this.element);
},closeCell:function(J){var L=this;
var I=(L.editor||{}).element;
var M;
var K;
if(!I||!I[0]||!L._isIncellEditable()){return;
}K=L.dataItem(I);
L._cancelEditor();
I.removeClass(H.GanttList.listStyles.editCell);
M=I.parent().removeClass(H.GanttList.listStyles.editRow);
if(L.lockedContent){L._relatedRow(M).removeClass(H.GanttList.listStyles.editRow);
}if(J){L._render();
}L.trigger("itemChange",{item:M,data:K,ns:H});
if(L.lockedContent){L._adjustRowHeight(M.css("height","")[0],L._relatedRow(M).css("height","")[0]);
}},insertAfter:function(I,K){if(!I||!K){return;
}var J=K.orderId;
var L={parentId:K.parentId};
if(K.parentId===I.parentId&&K.orderId>I.orderId){L.orderId=J;
}else{L.orderId=J+1;
}this.trigger("reorder",{task:I,updateInfo:L});
},insertBefore:function(I,K){if(!I||!K){return;
}var J=K.orderId;
var L={parentId:K.parentId};
if(K.parentId===I.parentId&&K.orderId>I.orderId){L.orderId=J-1;
}else{L.orderId=J;
}this.trigger("reorder",{task:I,updateInfo:L});
},_adjustHeight:function(){var J=this.element;
var I=J.find(i+H.GanttList.listStyles.gridContentWrap);
var K=J.find(i+H.GanttList.listStyles.gridHeader);
var L;
var M=kendo.support.scrollbar();
if(this._isHeightSet(J)){L=J.height()-z(K);
I.height(L);
if(this._hasLockedColumns){M=this.table[0].offsetWidth>this.table.parent()[0].clientWidth?M:0;
this.lockedContent.height(L-M);
}}},_adjustRowHeight:function(L,M){var I;
var J=L.offsetHeight;
var K=M.offsetHeight;
if(J>K){I=J+"px";
}else{if(J<K){I=K+"px";
}}if(I){L.style.height=M.style.height=I;
}},_isHeightSet:function(I){var J,K;
if(I[0].style.height){return true;
}else{J=I.height();
}I.height("auto");
K=I.height();
I.height("");
return J!=K;
},_attachCellEditingEventHandlers:function(){var J=this,I=J.options.editable;
if(J._isIncellEditable()&&I.update!==false){J._startEditHandler=function(L){var M=L.currentTarget?b(L.currentTarget):L;
var K=J._columnFromElement(M);
if(J.editable){return;
}if(K&&K.editable()){J._editCell(M,K,J._modelFromElement(M));
}};
J.content.on(m+y,A(J._focusInEditableHandler,J)).on(n+y,A(J._focusoutCellHandler,J)).on(r+y,"tr:not(.k-grouping-row) > td",A(J._keydownHandler,J)).on(t+y,"tr:not(.k-grouping-row) > td",A(J._keyupHandler,J));
if(!w){J.content.on(x+y,"tr:not(.k-grouping-row) > td",A(J._mouseDownHandler,J)).on(j+y,"tr:not(.k-grouping-row) > td",A(J._openEditorHandler,J));
}else{J.touch=J.content.kendoTouch({filter:"td",touchstart:function(K){J._mouseDownHandler(K.touch);
},doubletap:function(K){if(K.event.target.classList.contains("k-icon")){return;
}J._openEditorHandler(K.touch);
}}).data("kendoTouch");
}}},_blurActiveElement:function(){var I=kendo._activeElement();
if(I&&I.nodeName.toLowerCase()!=="body"){b(I).blur();
}},_closeCellTimeouted:function(){var L=this,K=c(),J=L.editor||{},I=J.element;
if(I&&I[0]&&K&&!b.contains(I[0],K)&&I[0]!==K&&!b(K).closest(".k-animation-container").length){if(J.end()){L.closeCell();
}}},_columns:function(){var J=this,I=this.options.columns;
J._hasExpandable=false;
I.forEach(function(K){if(K.expandable){J._hasExpandable=true;
}});
J.columns=J.options.columns=v(I,A(J._eachColumn,J));
G.fn._columns.call(J);
},_columnEditor:function(J){var I={name:J.field,required:true};
I[e]="value:"+J.field;
I[g]="date";
I[o]=kendo._extractFormat(J.format);
return function(K,N){var M=N.model,L=M.fields[J.field]||M[J.field],O=L.validation;
if(O&&O.dateCompare&&q(O.dateCompare)&&O.message){b("<span "+kendo.attr("for")+'="'+J.field+'" class="k-invalid-msg"/>').hide().appendTo(K);
I[kendo.attr("dateCompare-msg")]=O.message;
}b('<input type="text"/>').attr(I).prependTo(K).kendoDateTimePicker({format:N.format});
};
},_columnFromElement:function(I){var K=I.closest("td"),L=K.parent(),J=L.children().index(K);
return this.columns[J];
},_eachColumn:function(I){var N=this,M=N.options.resourcesField,K=this.options.sortable;
var L=function(){this.field="";
this.title="";
this.editable=function(){return false;
};
this.sortable=false;
};
var J=function(Q){var R=Q.get(M)||[],O=[];
for(var P=0;
P<R.length;
P++){O.push(kendo.format("{0} [{1}]",R[P].get("name"),R[P].get("formatedValue")));
}return O.join(", ");
};
if(I.columns){N.hasNestedColumns=true;
I.columns=v(I.columns,A(this._eachColumn,this));
}if(typeof I===E){I={field:I,title:F[I]};
}if(I.editable===true){I.editable=function(){return true;
};
}else{I.editable=function(){return false;
};
}if(I.field==="start"||I.field==="end"){I.format=kendo.getCulture().calendar.patterns[I.format]||I.format||h;
if(!I.editor){if(I.format===h||I.format.toLowerCase().indexOf("h")>-1){I.editor=N._columnEditor(I);
}}}if(I.field===M){I.sortable=false;
I.template=I.template||J;
}if(!N._hasExpandable&&I.field==="title"){I.expandable=true;
}if(K&&!I.sortable){I.sortable=false;
}return l(new L(),I);
},_editCell:function(I,J,L){var O=this,N=O.options.resourcesField,M=O.dataSource._createNewModel(L.toJSON()),K;
if(J.field===N){J.editor(I,M);
return;
}else{if(O.trigger(d,{model:L,container:I})){O.dataSource._restorePageSizeAfterAddChild();
return;
}O.closeCell();
L._edit=true;
O._cancelEditor();
O._render({editedColumn:J,editedColumnIndex:I.index()});
K=O.table.add(O.lockedTable).find(i+H.GanttList.listStyles.editCell).first();
O.editor=O._createIncellEditor(K,{columns:[J],model:L,change:function(P){if(O.trigger(C,{values:P.values,container:I,model:L})){P.preventDefault();
}}});
O._current=K;
O.trigger(k,{container:I,model:L});
}},_focusInEditableHandler:function(I){var K=this,J=I.target;
if(!b.contains(J,c())){clearTimeout(K._closeCellTimeout);
K._closeCellTimeout=null;
}},_focusoutCellHandler:function(I){var J=this;
J._closeCellTimeout=setTimeout(function(){J._closeCellTimeouted(I);
},1);
},_keydownHandler:function(I){if(I.keyCode===s.ENTER){I.preventDefault();
}},_keyupHandler:function(J){var M=this,K=J.keyCode,I,L;
switch(K){case s.ENTER:M._blurActiveElement();
M._closeCellTimeouted(J);
break;
case s.ESC:if(M.editor){I=b(J.target);
L=M._modelFromElement(I);
M.trigger(f,{model:L,cell:I});
}break;
}},_modelFromElement:function(I){var K=I.closest("tr"),J=this.dataSource.getByUid(K.attr(kendo.attr("uid")));
return J;
},_mouseDownHandler:function(J){var I=b(J.currentTarget);
if(!I.hasClass(H.GanttList.listStyles.editCell)){this._blurActiveElement();
}},_openEditorHandler:function(I){var M=this,L=b(I.currentTarget),J=M.lockedTable&&L.closest("table")[0]===M.lockedTable[0],K=M.selectable&&M.selectable.options.multiple;
if(L.hasClass(H.GanttList.listStyles.editCell)||L.has("a.k-grid-delete").length||L.has("button.k-grid-delete").length||L.closest("tbody")[0]!==M.tbody[0]&&!J||b(I.target).is(":input")||b(I.target).hasClass(H.GanttList.listStyles.iconExpand)||b(I.target).hasClass(H.GanttList.listStyles.iconCollapse)){return;
}if(M.editor){if(M.editor.end()){if(K){b(c()).blur();
}M.closeCell();
M.editCell(L);
}}else{M.editCell(L);
}},_renderTree:function(I){G.fn._render.call(this);
if(this.hasNestedColumns){this.element.addClass("k-gantt-treelist-nested-columns");
}if(I&&I.length&&!I.editedColumn){if(this.options.rowHeight){this._rowHeight(I);
}this.trigger(B);
}},_rowHeight:function(N){var I=this.content,K=this.options,L=typeof K.rowHeight===E?K.rowHeight:K.rowHeight+"px",M=b(kendo.format(D,L)),J;
I.append(M);
J=z(M.find("tr"));
M.remove();
this.element.find('[role="treegrid"]').css("height",N.length*J+"px");
},_setData:function(I){this.dataSource.data(I);
},_setWidth:function(){this.element.find(".k-grid-header table").css("minWidth",this.options.listWidth);
this.content.find("table").css("minWidth",this.options.listWidth);
}});
H.plugin(p);
b.extend(true,p,{listStyles:u});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
