(function(b,a){a("kendo.gantt.timeline",["kendo.dom","kendo.touch","kendo.draganddrop"],b);
}(function(){var a={id:"gantt.timeline",name:"Gantt Timeline",category:"web",description:"The Gantt Timeline",depends:["dom","touch","draganddrop"],hidden:true};
(function(b){var P=kendo.ui.Widget;
var o=kendo.dom.element;
var q=kendo.dom.text;
var p=kendo.dom.html;
var m=b.isPlainObject;
var A=kendo._outerWidth;
var z=kendo._outerHeight;
var i=b.extend;
var D=b.proxy;
var n=false;
var s=kendo.keys;
var E=kendo.data.Query;
var I="string";
var x=".kendoGanttTimeline";
var d="click";
var f="dblclick";
var w="mousemove";
var u="mouseenter";
var v="mouseleave";
var r="keydown";
var h=".";
var K=kendo.template("#=kendo.toString(start, 't')#");
var e=kendo.template("#=kendo.toString(start, 'ddd M/dd')#");
var O=kendo.template("#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#");
var t=kendo.template("#=kendo.toString(start, 'MMM')#");
var Q=kendo.template("#=kendo.toString(start, 'yyyy')#");
var F=kendo.template('<div class="#=styles.marquee#"><div class="#=styles.marqueeColor#"></div></div>');
var G=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper# k-gantt-resize-hint"><div class="#=styles.tooltipContent#"><div>#=messages.start#: #=kendo.toString(start, format)#</div><div>#=messages.end#: #=kendo.toString(end, format)#</div></div></div>');
var B=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#" ><div class="#=styles.tooltipContent#">#=text#%</div><div class="#=styles.tooltipCallout#" style="left:13px;"></div></div>');
var J=kendo.template('<div class="#=kendo.htmlEncode(styles.taskDetails)#"><strong>#=kendo.htmlEncode(task.title)#</strong><div class="#=styles.taskDetailsPercent#">#=kendo.toString(task.percentComplete, "p0")#</div><ul class="#=styles.reset#"><li>#=messages.start#: #=kendo.toString(task.start, "h:mm tt ddd, MMM d")#</li><li>#=messages.end#: #=kendo.toString(task.end, "h:mm tt ddd, MMM d")#</li></ul></div>');
var y=kendo.template("<span>#=offsetPrefix#: #=offsetText#</span>");
var C=kendo.template('<div class="k-task-content"><div>#=plannedStart#: #=startDate#</div><div>#=plannedEnd#: #=endDate#</div></div>');
var H="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>";
var g={day:{type:"kendo.ui.GanttDayView"},week:{type:"kendo.ui.GanttWeekView"},month:{type:"kendo.ui.GanttMonthView"},year:{type:"kendo.ui.GanttYearView"}};
function M(R){delete R.name;
delete R.prefix;
delete R.views;
return R;
}function l(S){var T=[];
var R=S.workWeekStart;
T.push(R);
while(S.workWeekEnd!=R){if(R>6){R-=7;
}else{R++;
}T.push(R);
}return T;
}function c(){var R=kendo._activeElement();
if(R&&R.nodeName.toLowerCase()!=="body"){b(R).blur();
}}var N={alt:"k-alt",reset:"k-reset",nonWorking:"k-nonwork-hour",header:"k-header",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasksWrapper:"k-gantt-tables",rowsTable:"k-gantt-rows",columnsTable:"k-gantt-columns",tasksTable:"k-gantt-tasks",dependenciesWrapper:"k-gantt-dependencies",resource:"k-resource",resourceAlt:"k-resource k-alt",task:"k-task",taskSingle:"k-task-single",taskMilestone:"k-task-milestone",taskSummary:"k-task-summary",taskWrap:"k-task-wrap",taskMilestoneWrap:"k-milestone-wrap",taskSummaryWrap:"k-summary-wrap",taskPlanned:"k-task-planned",taskPlannedMoment:"k-task-moment",taskPlannedDuration:"k-task-duration",taskPlannedMomentLeft:"k-moment-left",taskAdvanced:"k-task-advanced",taskDelayed:"k-task-delayed",taskOffset:"k-task-offset",taskOffsetWrap:"k-task-offset-wrap",taskInnerWrap:"k-task-inner-wrap",resourcesWrap:"k-resources-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",taskDragHandle:"k-task-draghandle",taskContent:"k-task-content",taskTemplate:"k-task-template",taskActions:"k-task-actions",taskDelete:"k-task-delete",taskComplete:"k-task-complete",taskDetails:"k-task-details",taskDetailsPercent:"k-task-pct",link:"k-link",icon:"k-icon",iconDelete:"k-i-close",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskResizeHandleEast:"k-resize-e",taskSummaryProgress:"k-task-summary-progress",taskSummaryComplete:"k-task-summary-complete",line:"k-gantt-line",lineHorizontal:"k-gantt-line-h",lineVertical:"k-gantt-line-v",arrowWest:"k-arrow-w",arrowEast:"k-arrow-e",dragHint:"k-drag-hint",dependencyHint:"k-gantt-dependency-hint",tooltipWrapper:"k-tooltip",tooltipContent:"k-tooltip-content",tooltipCallout:"k-callout k-callout-s",callout:"k-callout",marquee:"k-marquee k-gantt-marquee",marqueeColor:"k-marquee-color",offsetTooltipAdvanced:"k-offset-tooltip-advanced",offsetTooltipDelay:"k-offset-tooltip-delayed",plannedTooltip:"k-planned-tooltip"};
var k=kendo.ui.GanttView=P.extend({init:function(R,S){P.fn.init.call(this,R,S);
this.title=this.options.title||this.options.name;
this.header=this.element.find(h+k.styles.gridHeader);
this.content=this.element.find(h+k.styles.gridContent);
this.contentWidth=this.content.width();
this._workDays=l(this.options);
this._headerTree=S.headerTree;
this._taskTree=S.taskTree;
this._taskTemplate=S.taskTemplate?kendo.template(S.taskTemplate,i({},kendo.Template,S.templateSettings)):null;
this._dependencyTree=S.dependencyTree;
this._taskCoordinates={};
this._currentTime();
},destroy:function(){P.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
this.headerRow=null;
this.header=null;
this.content=null;
this._dragHint=null;
this._resizeHint=null;
this._resizeTooltip=null;
this._taskTooltip=null;
this._percentCompleteResizeTooltip=null;
this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
},options:{showWorkHours:false,showWorkDays:false,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,slotSize:100,currentTimeMarker:{updateInterval:10000}},renderLayout:function(){this._slots=this._createSlots();
this._tableWidth=this._calculateTableWidth();
this.createLayout(this._layout());
this._slotDimensions();
this._adjustHeight();
this.content.find(h+k.styles.dependenciesWrapper).width(this._tableWidth);
},_adjustHeight:function(){if(this.content){this.content.height(this.element.height()-z(this.header));
}},createLayout:function(U){var T=this._headers(U);
var R=this._colgroup();
var W=this._headerTree;
var S=o("tbody",null,T);
var V=o("table",{style:{width:this._tableWidth+"px"},role:"presentation"},[R,S]);
W.render([V]);
this.headerRow=this.header.find("table:first tr").last();
},_slotDimensions:function(){var S=this.headerRow[0].children;
var W=this._timeSlots();
var V;
var R;
for(var T=0,U=S.length;
T<U;
T++){R=S[T];
V=W[T];
V.offsetLeft=R.offsetLeft;
V.offsetWidth=R.offsetWidth;
}},render:function(Y){var X=Y.length;
var W=k.styles;
var T;
var V=this._rowsTable(X);
var S=this._columnsTable(X);
var Z=this._tasksTable(Y);
var U=this.options.currentTimeMarker;
var R=this.options.calculatedSize;
var aa;
this._taskTree.render([V,S,Z]);
T=this.content.find(h+W.rowsTable);
if(R){aa=R.row*Y.length;
this.content.find(h+W.tasksTable).height(aa);
T.height(aa);
}this._contentHeight=T.height();
this._rowHeight=R?R.row:this._contentHeight/T.find("tr").length;
this.content.find(h+W.columnsTable).height(this._contentHeight);
if(U!==false&&U.updateInterval!==undefined){this._renderCurrentTime();
}},_rowsTable:function(U){var V=[];
var T;
var W=k.styles;
var R=[null,{className:W.alt}];
for(var S=0;
S<U;
S++){T=o("tr",R[S%2],[o("td",null,[q("\xA0")])]);
V.push(T);
}return this._createTable(1,V,{className:W.rowsTable});
},_columnsTable:function(){var S=[];
var U;
var Z=k.styles;
var W=this._timeSlots();
var X=W.length;
var V;
var Y;
var aa=0;
var R;
for(var T=0;
T<X;
T++){V=W[T];
R={};
Y=V.span;
aa+=Y;
if(Y!==1){R.colspan=Y;
}if(V.isNonWorking){R.className=Z.nonWorking;
}S.push(o("td",R,[q("\xA0")]));
}U=o("tr",null,S);
return this._createTable(aa,[U],{className:Z.columnsTable});
},_tasksTable:function(am){var ag=[];
var af;
var T;
var aa;
var Z;
var ak;
var aj=k.styles;
var V=this._taskCoordinates={};
var ai=this._calculateMilestoneWidth();
var Y=Math.round(ai.width);
var ab=this.options.resourcesField;
var U=[aj.resource,aj.resourceAlt];
var S=this.options.calculatedSize;
var ad;
var ac=this._calculateResourcesMargin();
var al=this._calculateTaskBorderWidth();
var ae;
var ah=this.options.showPlannedTasks;
var R=function(an){var ao;
var ap;
ao=aa.left;
ap=ao+aa.width;
if(ak.isMilestone()){ao-=Y/2;
ap=ao+Y;
}V[ak.id]={start:ao,end:ap,rowIndex:an};
};
for(var W=0,X=am.length;
W<X;
W++){ak=am[W];
aa=this._taskPosition(ak);
if(ah){Z=this._taskPositionPlanned(ak);
Z.borderWidth=al;
}aa.borderWidth=al;
af=o("tr",null);
T=o("td");
if(ak.start<=this.end&&ak.end>=this.start){T.children.push(this._renderTask(am[W],aa,Z));
if(ak[ab]&&ak[ab].length){if(n){ad=this._tableWidth-aa.left;
}else{ad=Math.max(aa.width||ai.clientWidth,0)+aa.left;
}ae={width:this._tableWidth-(ad+ac)+"px"};
ae[n?"right":"left"]=ad+"px";
if(S){ae.height=S.cell+"px";
}T.children.push(o("div",{className:aj.resourcesWrap,style:ae},this._renderResources(ak[ab],U[W%2])));
}R(W);
}af.children.push(T);
ag.push(af);
}return this._createTable(1,ag,{className:k.styles.tasksTable});
},_createTable:function(T,V,W){var S=[];
var R;
var X;
for(var U=0;
U<T;
U++){S.push(o("col"));
}R=o("colgroup",null,S);
X=o("tbody",null,V);
if(!W.style){W.style={};
}W.style.width=this._tableWidth+"px";
W.role="presentation";
return o("table",W,[R,X]);
},_calculateTableWidth:function(){var V=this._timeSlots();
var U=0;
var X=0;
var R;
var W;
for(var S=0,T=V.length;
S<T;
S++){R=V[S].span;
X+=R;
if(R>U){U=R;
}}W=Math.round(X*this.options.slotSize/U);
return W;
},_calculateMilestoneWidth:function(){var U;
var S=k.styles.task+" "+k.styles.taskMilestone;
var T=b("<div class='"+S+"' style='visibility: hidden; position: absolute'>");
var R;
this.content.append(T);
R=T[0].getBoundingClientRect();
U={width:R.right-R.left,clientWidth:T[0].clientWidth};
T.remove();
return U;
},_calculateResourcesMargin:function(){var R;
var S=b("<div class='"+k.styles.resourcesWrap+"' style='visibility: hidden; position: absolute'>");
this.content.append(S);
R=parseInt(S.css(n?"margin-right":"margin-left"),10);
S.remove();
return R;
},_calculateTaskBorderWidth:function(){var U;
var R=k.styles.task+" "+k.styles.taskSingle;
var T=b("<div class='"+R+"' style='visibility: hidden; position: absolute'>");
var S;
this.content.append(T);
S=kendo.getComputedStyles(T[0],["border-left-width"]);
U=parseFloat(S["border-left-width"],10);
T.remove();
return U;
},_renderTask:function(ae,ab,aa){var U=this.options.editable;
var ah=ab.left;
var ad=k.styles;
var al=ad.taskWrap;
var R=this.options.calculatedSize;
var T={};
var aj={className:al,style:{left:ah+"px"}};
var S=[];
var W=0;
var ag=ab.width;
var ak,af,ac,Z;
var V,ai,X,Y;
if(R){aj.style.height=R.cell+"px";
}if(aa){if(ae.isMilestone()){Z=this._renderPlannedMilestone(ab,aa);
}else{Z=this._renderPlannedSingleTask(ab,aa,ae);
}S.push(Z);
if(n&&aa.left<=ab.left){aj.style.left=aa.left+"px";
}}if(ae.summary){af=this._renderSummary(ae,ab,aa);
aj.className+=" "+ad.taskSummaryWrap;
}else{if(ae.isMilestone()){af=this._renderMilestone(ae,ab);
aj.className+=" "+ad.taskMilestoneWrap;
}else{af=this._renderSingleTask(ae,ab,aa);
}}if(aa&&!ae.isMilestone()&&ae.plannedStart<ae.end&&ae.plannedEnd>ae.start&&ae.plannedEnd<ae.end){if(n){ag=ab.left+ab.width-aa.left;
}else{ag=aa.left+aa.width-ab.left;
}if(n){Y=aa.left-ab.left;
}else{Y=ab.left+ab.width-(aa.left+aa.width);
}X=o("div",{className:ad.taskOffset,style:{width:Y-2*aa.borderWidth+"px"}});
if(U&&U.resize!==false&&U.update!==false&&!ae.summary){if(U.destroy!==false){X.children.push(o("span",{className:ad.taskActions},[o("a",{className:ad.link+" "+ad.taskDelete,href:"#","aria-label":"Delete"},[o("span",{className:ad.icon+" "+ad.iconDelete})])]));
}if(n){X.children.push(o("span",{className:ad.taskResizeHandle+" "+ad.taskResizeHandleWest,style:{right:ab.width-5+"px"}}));
}else{X.children.push(o("span",{className:ad.taskResizeHandle+" "+ad.taskResizeHandleEast}));
}}ai=o("div",{className:ad.taskOffsetWrap+" "+ad.taskInnerWrap},[af,X]);
S.push(ai);
}else{if(aa){S.push(o("div",{className:ad.taskInnerWrap},[af]));
}else{S.push(af);
}}ak=o("div",aj,S);
if(U&&U.dependencyCreate!==false){if(aa&&ae.plannedEnd>ae.end){W=aa.left+aa.width-ab.left-ab.width-3+"px";
}ak.children.push(o("div",{className:ad.taskDot+" "+ad.taskDotStart}));
if(n){W="auto";
if(aa&&ae.plannedEnd>ae.end){V=ab.left-aa.left+"px";
}}ak.children.push(o("div",{className:ad.taskDot+" "+ad.taskDotEnd,style:{right:W,left:V}}));
}if(!ae.summary&&!ae.isMilestone()&&U&&U.dragPercentComplete!==false&&U.update!==false&&this._taskTemplate===null){ac=Math.round(ag*ae.percentComplete);
T[n?"right":"left"]=ac+"px";
ak.children.push(o("div",{className:ad.taskDragHandle,style:T}));
}return ak;
},_renderSingleTask:function(Z,W,V){var Y=k.styles;
var X;
var aa=[];
var ab;
var T=this.options.editable;
var R=Y.task+" "+Y.taskSingle;
var ac=W.width;
if(V){if(Z.plannedEnd&&Z.plannedEnd<=Z.start){R+=" "+Y.taskDelayed;
}else{if(Z.plannedEnd&&Z.plannedEnd>Z.end){R+=" "+Y.taskAdvanced;
}else{if(Z.plannedEnd&&Z.plannedEnd<Z.end){if(!n){ac=ac-(W.left+W.width-V.left-V.width);
}else{ac=ac+W.left-V.left;
}}}}}X=Math.round(ac*Z.percentComplete);
if(this._taskTemplate!==null){ab=p(this._taskTemplate(Z));
}else{ab=q(Z.title);
aa.push(o("div",{className:Y.taskComplete,style:{width:X+"px"}}));
}var S=o("div",{className:Y.taskContent},[o("div",{className:Y.taskTemplate},[ab])]);
aa.push(S);
if(T){if(T.destroy!==false&&(!V||!Z.plannedEnd||(Z.end<=Z.plannedEnd||Z.start>=Z.plannedEnd))){S.children.push(o("span",{className:Y.taskActions},[o("a",{className:Y.link+" "+Y.taskDelete,href:"#","aria-label":"Delete"},[o("span",{className:Y.icon+" "+Y.iconDelete})])]));
}if(T.resize!==false&&T.update!==false){S.children.push(o("span",{className:Y.taskResizeHandle+" "+Y.taskResizeHandleWest}));
S.children.push(o("span",{className:Y.taskResizeHandle+" "+Y.taskResizeHandleEast}));
}}var U=o("div",{className:R,"data-uid":Z.uid,style:{width:Math.max(ac-W.borderWidth*2,0)+"px"}},aa);
return U;
},_renderMilestone:function(U){var T=k.styles;
var R=T.task+" "+T.taskMilestone;
var S=this.options.showPlannedTasks;
if(S&&U.plannedEnd&&U.plannedEnd<U.start){R+=" "+T.taskDelayed;
}else{if(U.plannedStart&&U.plannedStart>U.end){R+=" "+T.taskAdvanced;
}}return o("div",{className:R,"data-uid":U.uid});
},_renderSummary:function(X,U,T){var W=k.styles;
var Y=U.width;
var V;
var R=W.task+" "+W.taskSummary;
if(T){if(X.plannedEnd&&X.plannedEnd<=X.start){R+=" "+W.taskDelayed;
}else{if(X.plannedEnd&&X.plannedEnd>X.end){R+=" "+W.taskAdvanced;
}else{if(X.plannedEnd&&X.plannedEnd<X.end){if(!n){Y=Y-(U.left+U.width-T.left-T.width);
}else{Y=Y+U.left-T.left;
}}}}}V=Math.round(Y*X.percentComplete);
var S=o("div",{className:R,"data-uid":X.uid,style:{width:Y+"px"}},[o("div",{className:W.taskSummaryProgress,style:{width:V+"px"}},[o("div",{className:W.taskSummaryComplete,style:{width:U.width+"px"}})])]);
return S;
},_renderPlannedSingleTask:function(U,T,X){var W=k.styles;
var R=[];
var V={};
if(X.plannedStart&&X.plannedEnd){R.push(o("div",{className:W.taskPlannedMoment+" "+W.taskPlannedMomentLeft}));
R.push(o("div",{className:W.taskPlannedDuration,style:{width:Math.max(T.width-T.borderWidth*2-16,0)+"px"}}));
R.push(o("div",{className:W.taskPlannedMoment}));
}else{if(X.plannedStart){R.push(o("div",{className:W.taskPlannedMoment+" "+W.taskPlannedMomentLeft}));
}else{if(X.plannedEnd){R.push(o("div",{className:W.taskPlannedMoment,style:{"margin-left":Math.max(T.width-5,0)+"px"}}));
}}}if(n){V={"margin-right":U.left-T.left+U.width-T.width+"px"};
}else{V={"margin-left":T.left-U.left+"px"};
}var S=o("div",{className:W.taskPlanned,style:V},R);
return S;
},_renderPlannedMilestone:function(T,S){var V=k.styles;
var U={};
var R;
if(n){U={"margin-right":T.left-S.left+"px"};
}else{U={"margin-left":S.left-T.left+"px"};
}R=o("div",{className:V.taskPlanned,style:U},[o("div",{className:V.taskPlannedMoment})]);
return R;
},_renderResources:function(W,S){var R=[];
var V;
for(var T=0,U=W.length;
T<U;
T++){V=W[T];
R.push(o("span",{className:S,style:{color:V.get("color")}},[q(V.get("name"))]));
}if(n){R.reverse();
}return R;
},_taskPosition:function(U){var S=Math.round;
var T=S(this._offset(n?U.end:U.start));
var R=S(this._offset(n?U.start:U.end));
return{left:T,width:R-T};
},_taskPositionPlanned:function(U){var S=Math.round;
var T=S(this._offset(n?U.plannedEnd:U.plannedStart));
var R=S(this._offset(n?U.plannedStart:U.plannedEnd));
return{left:T,width:R-T};
},_offset:function(R){var V=this._timeSlots();
var S;
var X;
var T;
var U=0;
var W;
if(!V.length){return 0;
}W=this._slotIndex("start",R);
S=V[W];
if(S.end<R){U=S.offsetWidth;
}else{if(S.start<=R){X=R-S.start;
T=S.end-S.start;
U=X/T*S.offsetWidth;
}}if(n){U=S.offsetWidth+1-U;
}return S.offsetLeft+U;
},_slotIndex:function(S,X,U){var V=this._timeSlots();
var W=0;
var R=V.length-1;
var T;
if(U){V=[].slice.call(V).reverse();
}do{T=Math.ceil((R+W)/2);
if(V[T][S]<X){W=T;
}else{if(T===R){T--;
}R=T;
}}while(W!==R);
if(U){W=V.length-1-W;
}return W;
},_timeByPosition:function(X,V,W){var T=this._slotByPosition(X);
if(V){return W?T.end:T.start;
}var S=X-this.element.find(h+k.styles.tasksTable).offset().left;
var R=T.end-T.start;
var U=S-T.offsetLeft;
if(n){U=T.offsetWidth-U;
}return new Date(T.start.getTime()+R*(U/T.offsetWidth));
},_slotByPosition:function(T){var R=T-this.element.find(h+k.styles.tasksTable).offset().left;
var S=this._slotIndex("offsetLeft",R,n);
return this._timeSlots()[S];
},_renderDependencies:function(R){var S=[];
var V=this._dependencyTree;
for(var T=0,U=R.length;
T<U;
T++){S.push.apply(S,this._renderDependency(R[T]));
}V.render(S);
},_renderDependency:function(R){var W=this._taskCoordinates[R.predecessorId];
var X=this._taskCoordinates[R.successorId];
var S;
var V;
if(!W||!X){return[];
}V="_render"+["FF","FS","SF","SS"][n?3-R.type:R.type];
S=this[V](W,X);
for(var T=0,U=S.length;
T<U;
T++){S[T].attr["data-uid"]=R.uid;
}return S;
},_renderFF:function(R,T){var S=this._dependencyFF(R,T,false);
S[S.length-1].children[0]=this._arrow(true);
return S;
},_renderSS:function(R,T){var S=this._dependencyFF(T,R,true);
S[0].children[0]=this._arrow(false);
return S.reverse();
},_renderFS:function(R,T){var S=this._dependencyFS(R,T,false);
S[S.length-1].children[0]=this._arrow(false);
return S;
},_renderSF:function(R,T){var S=this._dependencyFS(T,R,true);
S[0].children[0]=this._arrow(true);
return S.reverse();
},_dependencyFF:function(W,ah,ad){var ag=this;
var aa=[];
var Z=0;
var ai=0;
var ak=0;
var Y=0;
var V=ad?"start":"end";
var U;
var ac=2;
var T=1;
var ae=this._rowHeight;
var ab=10;
var X=W.rowIndex*ae+Math.floor(ae/2)-1;
var aj=ah.rowIndex*ae+Math.floor(ae/2)-1;
var af=k.styles;
var R=function(){aa.push(ag._line(af.line+" "+af.lineHorizontal,{left:Z+"px",top:ai+"px",width:ak+"px"}));
};
var S=function(){aa.push(ag._line(af.line+" "+af.lineVertical,{left:Z+"px",top:ai+"px",height:Y+"px"}));
};
Z=W[V];
ai=X;
ak=ab;
U=ah[V]-W[V];
if(U>0!==ad){ak=Math.abs(U)+ab;
}if(ad){Z-=ak;
ak-=T;
R();
}else{R();
Z+=ak-ac;
}if(aj<ai){Y=ai-aj;
Y+=ac;
ai=aj;
S();
}else{Y=aj-ai;
Y+=ac;
S();
ai+=Y-ac;
}ak=Math.abs(Z-ah[V]);
if(!ad){ak-=T;
Z-=ak;
}R();
return aa;
},_dependencyFS:function(V,ai,ae){var ah=this;
var Z=[];
var Y=0;
var aj=0;
var al=0;
var X=0;
var af=this._rowHeight;
var ab=Math.floor(af/2);
var ac=10;
var aa=2*ac;
var U=ai.start-V.end;
var ad=2;
var T=1;
var W=V.rowIndex*af+Math.floor(af/2)-1;
var ak=ai.rowIndex*af+Math.floor(af/2)-1;
var ag=k.styles;
var R=function(){Z.push(ah._line(ag.line+" "+ag.lineHorizontal,{left:Y+"px",top:aj+"px",width:al+"px"}));
};
var S=function(){Z.push(ah._line(ag.line+" "+ag.lineVertical,{left:Y+"px",top:aj+"px",height:X+"px"}));
};
Y=V.end;
aj=W;
al=ac;
if(ae){Y+=T;
if(U>aa){al=U-(ac-ad);
}al-=T;
}R();
Y+=al-ad;
if(U<=aa){X=ae?Math.abs(ak-W)-ab:ab;
if(ak<W){aj-=X;
X+=ad;
S();
}else{S();
aj+=X;
}al=V.end-ai.start+aa;
if(al<ac){al=ac;
}Y-=al-ad;
R();
}if(ak<W){X=aj-ak;
aj=ak;
X+=ad;
S();
}else{X=ak-aj;
S();
aj+=X;
}al=ai.start-Y;
if(!ae){al-=T;
}R();
return Z;
},_line:function(R,S){return o("div",{className:R,style:S});
},_arrow:function(R){return o("span",{className:R?k.styles.arrowWest:k.styles.arrowEast});
},_colgroup:function(){var W=this._timeSlots();
var S=W.length;
var R=[];
for(var T=0;
T<S;
T++){for(var U=0,V=W[T].span;
U<V;
U++){R.push(o("col"));
}}return o("colgroup",null,R);
},_createDragHint:function(R){var T=k.styles;
var S;
this._dragHint=R.clone().addClass(T.dragHint).css({cursor:"move"});
S=this._dragHint.find(h+T.taskPlanned);
S.css({visibility:"hidden"});
if(n&&R.find(h+T.taskAdvanced).length>0){S.css({"margin-right":"auto",width:0});
this._dragHint.find(h+T.taskDotEnd).css({left:0});
}R.closest("td").append(this._dragHint);
},_updateDragHint:function(S){var R=this._offset(S);
this._dragHint.css({left:R});
},_removeDragHint:function(){this._dragHint.remove();
this._dragHint=null;
},_createResizeHint:function(U){var T=k.styles;
var V=this._taskCoordinates[U.id].rowIndex*this._rowHeight;
var W;
var X;
var S=this.options;
var R=S.messages;
this._resizeHint=b(F({styles:T})).css({top:0,height:this._contentHeight});
this.content.append(this._resizeHint);
this._resizeTooltip=b(G({styles:T,start:U.start,end:U.end,messages:R.views,format:S.resizeTooltipFormat})).css({top:0,left:0});
this.content.append(this._resizeTooltip);
this._resizeTooltipWidth=A(this._resizeTooltip);
W=z(this._resizeTooltip);
X=V-W;
if(X<0){X=V+this._rowHeight;
}this._resizeTooltipTop=X;
},_updateResizeHint:function(X,R,V){var S=this._offset(n?R:X);
var W=this._offset(n?X:R);
var ac=W-S;
var aa=V!==n?S:W;
var Z=this._tableWidth-kendo.support.scrollbar();
var ab=this._resizeTooltipWidth;
var U=this.options;
var T=U.messages;
var Y=this.element.find(h+k.styles.tasksTable).offset().left-this.element.find(h+k.styles.tasksWrapper).offset().left;
if(n){S+=Y;
}this._resizeHint.css({left:S,width:ac});
if(this._resizeTooltip){this._resizeTooltip.remove();
}aa-=Math.round(ab/2);
if(aa<0){aa=0;
}else{if(aa+ab>Z){aa=Z-ab;
}}if(n){aa+=Y;
}this._resizeTooltip=b(G({styles:k.styles,start:X,end:R,messages:T.views,format:U.resizeTooltipFormat})).css({top:this._resizeTooltipTop,left:aa,"min-width":ab}).appendTo(this.content);
},_removeResizeHint:function(){this._resizeHint.remove();
this._resizeHint=null;
this._resizeTooltip.remove();
this._resizeTooltip=null;
},_updatePercentCompleteTooltip:function(X,T,U){this._removePercentCompleteTooltip();
var V=this._percentCompleteResizeTooltip=b(B({styles:k.styles,text:U})).appendTo(this.element);
var W=Math.round(A(V)/2);
var R=V.find(h+k.styles.callout);
var S=Math.round(A(R)/2);
V.css({top:X-(z(V)+S),left:T-W});
R.css("left",W-S);
},_removePercentCompleteTooltip:function(){if(this._percentCompleteResizeTooltip){this._percentCompleteResizeTooltip.remove();
}this._percentCompleteResizeTooltip=null;
},_updateDependencyDragHint:function(R,S){this._removeDependencyDragHint();
this._creteDependencyDragHint(R,S);
},_creteDependencyDragHint:function(U,W){var V=k.styles;
var S=W.x-U.x;
var T=W.y-U.y;
var X=Math.sqrt(S*S+T*T);
var R=Math.atan(T/S);
if(S<0){R+=Math.PI;
}b("<div class='"+V.line+" "+V.lineHorizontal+" "+V.dependencyHint+"'></div>").css({top:U.y,left:U.x,width:X,"transform-origin":"0% 0","-ms-transform-origin":"0% 0","-webkit-transform-origin":"0% 0",transform:"rotate("+R+"rad)","-ms-transform":"rotate("+R+"rad)","-webkit-transform":"rotate("+R+"rad)"}).appendTo(this.content);
},_removeDependencyDragHint:function(){this.content.find(h+k.styles.dependencyHint).remove();
},_createTaskTooltip:function(ab,U,W){var aa=k.styles;
var X=this.options;
var R=this.content;
var S=R.offset();
var T=kendo.scrollLeft(R);
var Y=b(U).parents("tr").first();
var Z=Y.offset();
var ac=X.tooltip&&X.tooltip.template?kendo.template(X.tooltip.template):J;
var V=n?W-(S.left+T+kendo.support.scrollbar()):W-(S.left-T);
var ae=Z.top+z(Y)-S.top+R.scrollTop();
var ad=this._taskTooltip=b('<div style="z-index: 100002;" class="'+aa.tooltipWrapper+'" ><div class="'+aa.taskContent+'"></div></div>');
ad.css({left:V,top:ae}).appendTo(R).find(h+aa.taskContent).append(ac({styles:aa,task:ab,messages:X.messages.views}));
this._adjustTooltipDimensions(ad,Z,S,V,T);
},_removeTaskTooltip:function(){if(this._taskTooltip){this._taskTooltip.remove();
}this._taskTooltip=null;
},_createOffsetTooltip:function(ag,V,Z){var af=k.styles;
var R=this.content;
var S=R.offset();
var T=kendo.scrollLeft(R);
var ad=V.parents("tr").first();
var ae=ad.offset();
var X=n?Z-(S.left+T+kendo.support.scrollbar()):Z-(S.left-T);
var ai=ae.top+z(ad)-S.top+R.scrollTop();
var ah=this._offsetTooltip=b('<div style="z-index: 100002;" class="'+af.tooltipWrapper+'" ></div>');
var ab=Math.round((ag.end.getTime()-ag.plannedEnd.getTime())/60000);
var ac=this.options.messages.plannedTasks;
var Y=ab%60;
var aa=Y+" "+ac.minutes;
var W,U;
if(ab>=60){W=ab=Math.floor(ab/60);
aa=W+" "+ac.hours;
if(Y!==0){aa+=" "+Y+" "+ac.minutes;
}if(ab>=24){W=ab%24;
U=ab=Math.floor(ab/24);
aa=U+" "+ac.days;
if(W!==0){aa+=" "+W+" "+ac.hours;
}}}ah.css({left:X,top:ai}).addClass(af.offsetTooltipDelay).appendTo(R).append(y({offsetPrefix:ac.offsetTooltipDelay,offsetText:aa}));
this._adjustTooltipDimensions(ah,ae,S,X,T);
},_removeOffsetTooltip:function(){if(this._offsetTooltip){this._offsetTooltip.remove();
}this._offsetTooltip=null;
},_createPlannedTooltip:function(ab,V,X){var aa=k.styles;
var R=this.content;
var S=R.offset();
var T=kendo.scrollLeft(R);
var Y=V.parents("tr").first();
var Z=Y.offset();
var W=n?X-(S.left+T+kendo.support.scrollbar()):X-(S.left-T);
var ad=Z.top+z(Y)-S.top+R.scrollTop();
var ac=this._plannedTooltip=b('<div style="z-index: 100002;" class="'+aa.tooltipWrapper+" "+aa.plannedTooltip+'" ></div>');
var U=this.options.messages.editor;
ac.css({left:W,top:ad}).appendTo(R).append(C({plannedStart:U.plannedStart,startDate:kendo.toString(ab.plannedStart,"H:mm tt ddd, MMM dd"),plannedEnd:U.plannedEnd,endDate:kendo.toString(ab.plannedEnd,"H:mm tt ddd, MMM dd")}));
this._adjustTooltipDimensions(ac,Z,S,W,T);
},_removePlannedTooltip:function(){if(this._plannedTooltip){this._plannedTooltip.remove();
}this._plannedTooltip=null;
},_adjustTooltipDimensions:function(X,W,S,V,T){var R=this.content;
var U=R.width();
var Y;
if(z(X)<W.top-S.top){X.css("top",W.top-S.top-z(X)+R.scrollTop());
}Y=A(X);
if(Y+V-T>U){V-=Y;
if(V<T){V=T+U-(Y+17);
}X.css("left",V);
}},_scrollTo:function(Z){var aa=Z.offset().left;
var ac=Z.width();
var ab=aa+ac;
var ad=Z.closest("tr");
var ag=ad.offset().top;
var af=ad.height();
var ae=ag+af;
var R=this.content;
var V=R.offset();
var X=V.top;
var T=R.height();
var S=X+T;
var U=V.left;
var Y=R.width();
var W=U+Y;
var ah=kendo.support.scrollbar();
if(ag<X){R.scrollTop(R.scrollTop()+(ag-X));
}else{if(ae>S){R.scrollTop(R.scrollTop()+(ae+ah-S));
}}if(aa<U&&ac>Y&&ab<W||ab>W&&ac<Y){kendo.scrollLeft(R,kendo.scrollLeft(R)+(ab+ah-W));
}else{if(ab>W&&ac>Y&&aa>U||aa<U&&ac<Y){kendo.scrollLeft(R,kendo.scrollLeft(R)+(aa-U));
}}},_scrollToDate:function(R){var U=this.start;
var T=this.end;
var S;
if(R>=U&&R<T){S=this._offset(R);
if(kendo.support.isRtl(this.element)){S=this._tableWidth-S;
}kendo.scrollLeft(this.content,S);
}},_timeSlots:function(){if(!this._slots||!this._slots.length){return[];
}return this._slots[this._slots.length-1];
},_headers:function(U){var aa=[];
var X;
var V;
var R;
var W;
var ab=k.styles;
for(var Z=0,Y=U.length;
Z<Y;
Z++){X=U[Z];
V=[];
for(var T=0,S=X.length;
T<S;
T++){R=X[T];
W=p(R.text);
V.push(o("td",{colspan:R.span,className:ab.header+(R.isNonWorking?" "+ab.nonWorking:"")},[W]));
}aa.push(o("tr",null,V));
}return aa;
},_hours:function(Y,R){var W;
var X=[];
var V=this.options;
var aa=V.workDayStart.getHours();
var Z=V.workDayEnd.getHours();
var U;
var S;
var T=V.hourSpan;
Y=new Date(Y);
R=new Date(R);
if(V.showWorkHours){Y.setHours(aa);
}while(Y<R){W=new Date(Y);
S=W.getHours();
U=S>=aa&&S<Z;
W.setHours(W.getHours()+T);
if(S==W.getHours()){W.setHours(W.getHours()+2*T);
}if(!V.showWorkHours||U){X.push({start:Y,end:W,isNonWorking:!U,span:1});
}Y=W;
}return X;
},_days:function(V,R){var T;
var U=[];
var S;
V=new Date(V);
R=new Date(R);
while(V<R){T=R<kendo.date.nextDay(V)?R:kendo.date.nextDay(V);
S=this._isWorkDay(V);
if(!this.options.showWorkDays||S){U.push({start:V,end:T,isNonWorking:!S,span:1});
}V=T;
}return U;
},_weeks:function(X,S){var U;
var V=[];
var T=this.calendarInfo().firstDay;
var R;
var W;
X=new Date(X);
S=new Date(S);
while(X<S){U=kendo.date.dayOfWeek(kendo.date.addDays(X,1),T,1);
if(U>S){U=S;
}R=this._days(X,U);
W=R.length;
if(W>0){V.push({start:R[0].start,end:R[W-1].end,span:W});
}X=U;
}return V;
},_months:function(X,S){var U;
var T;
var V=[];
var R;
var W;
X=new Date(X);
S=new Date(S);
while(X<S){U=new Date(X);
T=kendo.date.firstDayOfMonth(new Date(U.setMonth(U.getMonth()+1)));
U=S<T?S:T;
R=this._days(X,U);
W=R.length;
if(W>0){V.push({start:R[0].start,end:R[W-1].end,span:W});
}X=U;
}return V;
},_years:function(W,R){var U;
var T;
var S;
var V=[];
W=new Date(W);
R=new Date(R);
while(W<R){U=new Date(W);
U=kendo.date.firstDayOfMonth(new Date(U.setMonth(12)));
if(U>=R){U=R;
}S=U.getMonth()||12;
T=S-W.getMonth();
V.push({start:W,end:U,span:T});
W=U;
}return V;
},_slotHeaders:function(V,W){var R=[];
var U;
for(var S=0,T=V.length;
S<T;
S++){U=V[S];
R.push({text:W(U),isNonWorking:!!U.isNonWorking,span:U.span});
}return R;
},_isWorkDay:function(R){var S=R.getDay();
var V=this._workDays;
for(var T=0,U=V.length;
T<U;
T++){if(V[T]===S){return true;
}}return false;
},calendarInfo:function(){return kendo.getCulture().calendars.standard;
},_renderCurrentTime:function(){var R=this._getCurrentTime();
var W=this._offset(R);
var S=b("<div class='k-current-time'></div>");
var X=k.styles;
var U=this.element.find(h+X.tasksWrapper);
var V=this.element.find(h+X.tasksTable);
var T;
if(!this.content||!this._timeSlots().length){return;
}this.content.find(".k-current-time").remove();
T=this._timeSlots()[this._slotIndex("start",R)];
if(R<T.start||R>T.end){return;
}if(U.length&&V.length){W+=V.offset().left-U.offset().left;
}S.css({left:W+"px",top:"0px",width:"1px",height:this._contentHeight+"px"}).appendTo(this.content);
},_getCurrentTime:function(){return new Date();
},_currentTime:function(){var R=this.options.currentTimeMarker;
if(R!==false&&R.updateInterval!==undefined){this._renderCurrentTime();
this._currentTimeUpdateTimer=setInterval(D(this._renderCurrentTime,this),R.updateInterval);
}}});
i(true,k,{styles:N});
kendo.ui.GanttDayView=k.extend({name:"day",options:{timeHeaderTemplate:K,dayHeaderTemplate:e,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(S){var R=this.options.range;
this.start=kendo.date.getDate(S.start);
this.end=kendo.date.getDate(S.end);
if(kendo.date.getMilliseconds(S.end)>0||this.end.getTime()===this.start.getTime()){this.end=kendo.date.addDays(this.end,1);
}if(R&&R.start){this.start=kendo.date.getDate(R.start);
this.start.setHours(R.start.getHours());
}if(R&&R.end){this.end=kendo.date.getDate(R.end);
this.end.setHours(R.end.getHours());
}},_createSlots:function(){var S;
var R;
var U;
var T;
var X=[];
S=this._days(this.start,this.end);
U=[];
for(var V=0,W=S.length;
V<W;
V++){R=S[V];
T=this._hours(R.start,R.end);
R.span=T.length;
U.push.apply(U,T);
}X.push(S);
X.push(U);
return X;
},_layout:function(){var S=[];
var R=this.options;
S.push(this._slotHeaders(this._slots[0],kendo.template(R.dayHeaderTemplate)));
S.push(this._slotHeaders(this._slots[1],kendo.template(R.timeHeaderTemplate)));
return S;
}});
kendo.ui.GanttWeekView=k.extend({name:"week",options:{dayHeaderTemplate:e,weekHeaderTemplate:O,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(V){var U=this.options.range;
var R=this.calendarInfo();
var T=R.firstDay;
var W=V.end;
var S;
if(T===W.getDay()){W.setDate(W.getDate()+7);
}this.start=kendo.date.getDate(kendo.date.dayOfWeek(V.start,T,-1));
this.end=kendo.date.getDate(kendo.date.dayOfWeek(W,T,1));
if(U&&U.start){this.start=kendo.date.getDate(U.start);
}if(U&&U.end){S=new Date(U.end);
if(kendo.date.getDate(S)<U.end){this.end=kendo.date.getDate(new Date(S.setDate(S.getDate()+1)));
}else{this.end=kendo.date.getDate(S);
}}},_createSlots:function(){var R=[];
R.push(this._weeks(this.start,this.end));
R.push(this._days(this.start,this.end));
return R;
},_layout:function(){var S=[];
var R=this.options;
S.push(this._slotHeaders(this._slots[0],kendo.template(R.weekHeaderTemplate)));
S.push(this._slotHeaders(this._slots[1],kendo.template(R.dayHeaderTemplate)));
return S;
}});
kendo.ui.GanttMonthView=k.extend({name:"month",options:{weekHeaderTemplate:O,monthHeaderTemplate:t,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(T){var S=this.options.range;
var R;
this.start=kendo.date.firstDayOfMonth(T.start);
this.end=kendo.date.addDays(kendo.date.getDate(kendo.date.lastDayOfMonth(T.end)),1);
if(S&&S.start){this.start=kendo.date.getDate(S.start);
}if(S&&S.end){R=new Date(S.end);
if(kendo.date.getDate(R)<S.end){this.end=kendo.date.getDate(new Date(R.setDate(R.getDate()+1)));
}else{this.end=kendo.date.getDate(R);
}}},_createSlots:function(){var R=[];
R.push(this._months(this.start,this.end));
R.push(this._weeks(this.start,this.end));
return R;
},_layout:function(){var S=[];
var R=this.options;
S.push(this._slotHeaders(this._slots[0],kendo.template(R.monthHeaderTemplate)));
S.push(this._slotHeaders(this._slots[1],kendo.template(R.weekHeaderTemplate)));
return S;
}});
kendo.ui.GanttYearView=k.extend({name:"year",options:{yearHeaderTemplate:Q,monthHeaderTemplate:t,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(T){var S=this.options.range;
var R;
this.start=kendo.date.firstDayOfMonth(new Date(T.start.setMonth(0)));
this.end=kendo.date.firstDayOfMonth(new Date(T.end.setMonth(12)));
if(S&&S.start){this.start=kendo.date.firstDayOfMonth(S.start);
}if(S&&S.end){R=kendo.date.firstDayOfMonth(S.end);
this.end=kendo.date.getDate(new Date(R.setMonth(R.getMonth()+1)));
}},_createSlots:function(){var S=[];
var R=this._months(this.start,this.end);
b(R).each(function(T,U){U.span=1;
});
S.push(this._years(this.start,this.end));
S.push(R);
return S;
},_layout:function(){var S=[];
var R=this.options;
S.push(this._slotHeaders(this._slots[0],kendo.template(R.yearHeaderTemplate)));
S.push(this._slotHeaders(this._slots[1],kendo.template(R.monthHeaderTemplate)));
return S;
}});
var L={wrapper:"k-timeline k-grid k-widget",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",tasksWrapper:"k-gantt-tables",dependenciesWrapper:"k-gantt-dependencies",task:"k-task",taskOffset:"k-task-offset",taskOffsetWrap:"k-task-offset-wrap",taskPlanned:"k-task-planned",line:"k-gantt-line",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskDragHandle:"k-task-draghandle",taskComplete:"k-task-complete",taskDelete:"k-task-delete",taskWrapActive:"k-task-wrap-active",taskWrap:"k-task-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",hovered:"k-state-hover",selected:"k-state-selected",origin:"k-origin"};
var j=kendo.ui.GanttTimeline=P.extend({init:function(R,S){P.fn.init.call(this,R,S);
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}n=kendo.support.isRtl(R);
this._wrapper();
this._domTrees();
this._views();
this._selectable();
this._draggable();
this._resizable();
this._percentResizeDraggable();
this._createDependencyDraggable();
this._attachEvents();
this._tooltip();
},options:{name:"GanttTimeline",messages:{views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"}},snap:true,selectable:true,editable:true},destroy:function(){P.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
if(this._currentTimeUpdateTimer){clearInterval(this._currentTimeUpdateTimer);
}this._unbindView(this._selectedView);
if(this._moveDraggable){this._moveDraggable.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}if(this._percentDraggable){this._percentDraggable.destroy();
}if(this._dependencyDraggable){this._dependencyDraggable.destroy();
}if(this.touch){this.touch.destroy();
}this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
this.wrapper.off(x);
kendo.destroy(this.wrapper);
},_wrapper:function(){var T=j.styles;
var U=this;
var S=this.options;
var R=function(){var Y=typeof S.rowHeight===I?S.rowHeight:S.rowHeight+"px";
var Z=b(kendo.format(H,Y));
var W;
var V;
var X=U.wrapper.find(h+T.tasksWrapper);
X.append(Z);
W=z(Z.find("tr"));
V=Z.find("td").height();
Z.remove();
return{row:W,cell:V};
};
this.wrapper=this.element.addClass(T.wrapper).append("<div class='"+T.gridHeader+"'><div class='"+T.gridHeaderWrap+"'></div></div>").append("<div class='"+T.gridContentWrap+"'><div class='"+T.tasksWrapper+"'></div><div class='"+T.dependenciesWrapper+"'></div></div>");
if(S.rowHeight){this._calculatedSize=R();
}},_domTrees:function(){var R=j.styles;
var S=kendo.dom.Tree;
var T=this.wrapper;
this._headerTree=new S(T.find(h+R.gridHeaderWrap)[0]);
this._taskTree=new S(T.find(h+R.tasksWrapper)[0]);
this._dependencyTree=new S(T.find(h+R.dependenciesWrapper)[0]);
},_views:function(){var Y=this.options.views;
var X;
var T;
var V;
var R;
var W;
this.views={};
for(var S=0,U=Y.length;
S<U;
S++){X=Y[S];
T=m(X);
if(T&&X.selectable===false){continue;
}V=T?typeof X.type!=="string"?X.title:X.type:X;
R=g[V];
if(R){if(T){X.type=R.type;
}R.title=this.options.messages.views[V];
}X=i({title:V},R,T?X:{});
if(V){this.views[V]=X;
if(!W||X.selected){W=V;
}}}if(W){this._selectedViewName=W;
}},view:function(R){if(R){this._selectView(R);
this.trigger("navigate",{view:R,action:"changeView"});
}return this._selectedView;
},_selectView:function(R){if(R&&this.views[R]){if(this._selectedView){this._unbindView(this._selectedView);
}this._selectedView=this._initializeView(R);
this._selectedViewName=R;
}},_viewByIndex:function(R){var S;
var T=this.views;
for(S in T){if(!R){return S;
}R--;
}},_initializeView:function(R){var V=this.views[R];
if(V){var U=V.type;
if(typeof U==="string"){U=kendo.getter(V.type)(window);
}if(U){var T={};
i(T,this.options.range,V.range);
var S=V.date||this.options.date;
V=new U(this.wrapper,M(i(true,{headerTree:this._headerTree,taskTree:this._taskTree,dependencyTree:this._dependencyTree,calculatedSize:this._calculatedSize},V,this.options,{date:S,range:T})));
}else{throw new Error("There is no such view");
}}return V;
},_unbindView:function(R){if(R){R.destroy();
}},_range:function(V){var U={field:"start",dir:"asc"};
var S={field:"end",dir:"desc"};
if(!V||!V.length){return{start:new Date(),end:new Date()};
}var T=new E(V).sort(U).toArray()[0].start||new Date();
var R=new E(V).sort(S).toArray()[0].end||new Date();
return{start:new Date(T),end:new Date(R)};
},_render:function(T){var U=this.view();
var S=this._range(T);
var R=U.options.date;
this._tasks=T;
U.range(S);
U.renderLayout();
U.render(T);
if(R){U._scrollToDate(R);
}},_renderDependencies:function(R){this.view()._renderDependencies(R);
},_taskByUid:function(V){var U=this._tasks;
var S=U.length;
var T;
for(var R=0;
R<S;
R++){T=U[R];
if(T.uid===V){return T;
}}},_draggable:function(){var Z=this;
var U;
var Y;
var S;
var W;
var V=this.options.snap;
var X=j.styles;
var T=this.options.editable;
var R=function(){Z.view()._removeDragHint();
if(U){U.css("opacity",1);
}U=null;
Y=null;
Z.dragInProgress=false;
};
if(!T||T.move===false||T.update===false){return;
}this._moveDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+X.task+","+h+X.taskOffset,holdToDrag:kendo.support.mobileOS,ignore:h+X.taskResizeHandle});
this._moveDraggable.bind("dragstart",function(aa){var ab=Z.view();
U=aa.currentTarget.closest(h+X.taskWrap);
Y=Z._taskByUid(aa.currentTarget.parent().find(h+X.task).attr("data-uid"));
if(Z.trigger("moveStart",{task:Y})){aa.preventDefault();
return;
}S=Y.start;
W=ab._timeByPosition(aa.x.location,V)-S;
ab._createDragHint(U);
U.css("opacity",0.5);
clearTimeout(Z._tooltipTimeout);
Z.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ab){if(!Z.dragInProgress){return;
}var ad=Z.view();
var aa=new Date(ad._timeByPosition(ab.x.location,V)-W);
var ac=aa;
if(!Z.trigger("move",{task:Y,start:aa})){S=aa;
if(n){ac=new Date(S.getTime()+Y.duration());
}ad._updateDragHint(ac);
}},15)).bind("dragend",function(){Z.trigger("moveEnd",{task:Y,start:S});
R();
}).bind("dragcancel",function(){R();
}).userEvents.bind("select",function(){c();
});
},_resizable:function(){var aa=this;
var V;
var Z;
var T;
var S;
var W;
var X=this.options.snap;
var Y=j.styles;
var U=this.options.editable;
var R=function(){aa.view()._removeResizeHint();
V=null;
Z=null;
aa.dragInProgress=false;
};
if(!U||U.resize===false||U.update===false){return;
}this._resizeDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+Y.taskResizeHandle,holdToDrag:false});
this._resizeDraggable.bind("dragstart",function(ab){W=ab.currentTarget.hasClass(Y.taskResizeHandleWest);
if(n){W=!W;
}V=ab.currentTarget.closest(h+Y.taskWrap).find(h+Y.task);
Z=aa._taskByUid(V.attr("data-uid"));
if(aa.trigger("resizeStart",{task:Z})){ab.preventDefault();
return;
}T=Z.start;
S=Z.end;
aa.view()._createResizeHint(Z);
clearTimeout(aa._tooltipTimeout);
aa.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ac){if(!aa.dragInProgress){return;
}var ad=aa.view();
var ab=ad._timeByPosition(ac.x.location,X,!W);
if(W){if(ab<S){T=ab;
}else{T=S;
}}else{if(ab>T){S=ab;
}else{S=T;
}}if(!aa.trigger("resize",{task:Z,start:T,end:S})){ad._updateResizeHint(T,S,W);
}},15)).bind("dragend",function(){aa.trigger("resizeEnd",{task:Z,resizeStart:W,start:T,end:S});
R();
}).bind("dragcancel",function(){R();
}).userEvents.bind("select",function(){c();
});
},_percentResizeDraggable:function(){var ab=this;
var Y;
var Z;
var aa;
var ac;
var W;
var V;
var S;
var ae;
var ad;
var X=j.styles;
var T;
var U=this.options.editable;
var R=function(){ab.view()._removePercentCompleteTooltip();
Z=null;
Y=null;
ab.dragInProgress=false;
};
var af=function(ah){var ag=Z.siblings(h+X.taskDragHandle);
if(!ag.length){ag=Z.closest(h+X.taskWrap).find(h+X.taskDragHandle);
}ag.css(n?"right":"left",ah);
Z.find(h+X.taskComplete).width(ah);
};
if(!U||U.dragPercentComplete===false||U.update===false){return;
}this._percentDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+X.taskDragHandle,holdToDrag:false});
this._percentDraggable.bind("dragstart",function(ag){if(ab.trigger("percentResizeStart")){ag.preventDefault();
return;
}Z=ag.currentTarget.siblings(h+X.task);
if(!Z.length){Z=ag.currentTarget.closest(h+X.taskWrap).find(h+X.task);
}Y=ab._taskByUid(Z.attr("data-uid"));
S=Y.percentComplete;
aa=Z.offset();
ac=this.element.offset();
W=Z.find(h+X.taskComplete).width();
V=A(Z);
clearTimeout(ab._tooltipTimeout);
ab.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ah){if(!ab.dragInProgress){return;
}T=n?-ah.x.initialDelta:ah.x.initialDelta;
var ag=Math.max(0,Math.min(V,W+T));
S=Math.round(ag/V*100);
af(ag);
ae=aa.top-ac.top;
ad=aa.left+ag-ac.left;
if(n){ad+=V-2*ag;
}ab.view()._updatePercentCompleteTooltip(ae,ad,S);
},15)).bind("dragend",function(){ab.trigger("percentResizeEnd",{task:Y,percentComplete:S/100});
R();
}).bind("dragcancel",function(){af(W);
R();
}).userEvents.bind("select",function(){c();
});
},_createDependencyDraggable:function(){var Z=this;
var V;
var T=b();
var U=b();
var W;
var X;
var Y=j.styles;
var S=this.options.editable;
var R=function(){V.css("display","").removeClass(Y.hovered);
V.parent().removeClass(Y.origin);
V=null;
aa(false);
U=b();
T=b();
Z.view()._removeDependencyDragHint();
Z.dragInProgress=false;
};
var aa=function(ab){if(!U.hasClass(Y.origin)){U.find(h+Y.taskDot).css("display",ab?"block":"");
T.toggleClass(Y.hovered,ab);
}};
if(!S||S.dependencyCreate===false){return;
}this._dependencyDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:h+Y.taskDot,holdToDrag:false});
this._dependencyDraggable.bind("dragstart",function(ab){if(Z.trigger("dependencyDragStart")){ab.preventDefault();
return;
}V=ab.currentTarget.css("display","block").addClass(Y.hovered);
V.parent().addClass(Y.origin);
var ac=V.offset();
var ad=Z.wrapper.find(h+Y.tasksWrapper).offset();
W=Math.round(ac.left-ad.left+z(V)/2);
X=Math.round(ac.top-ad.top+A(V)/2);
clearTimeout(Z._tooltipTimeout);
Z.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ad){if(!Z.dragInProgress){return;
}Z.view()._removeDependencyDragHint();
var af=b(kendo.elementUnderCursor(ad));
var ae=Z.wrapper.find(h+Y.tasksWrapper).offset();
var ab=ad.x.location-ae.left;
var ac=ad.y.location-ae.top;
Z.view()._updateDependencyDragHint({x:W,y:X},{x:ab,y:ac});
aa(false);
T=af.hasClass(Y.taskDot)?af:b();
U=af.closest(h+Y.taskWrap);
aa(true);
},15)).bind("dragend",function(){if(T.length){var ab=V.hasClass(Y.taskDotStart);
var ag=T.hasClass(Y.taskDotStart);
var ah=ab?ag?3:2:ag?1:0;
var ad=V.siblings(h+Y.task);
if(!ad.length){ad=V.closest(h+Y.taskWrap).find(h+Y.task);
}var ac=Z._taskByUid(ad.attr("data-uid"));
var af=T.siblings(h+Y.task);
if(!af.length){af=T.closest(h+Y.taskWrap).find(h+Y.task);
}var ae=Z._taskByUid(af.attr("data-uid"));
if(ac!==ae){Z.trigger("dependencyDragEnd",{type:ah,predecessor:ac,successor:ae});
}}R();
}).bind("dragcancel",function(){R();
}).userEvents.bind("select",function(){c();
});
},_selectable:function(){var S=this;
var R=j.styles;
if(this.options.selectable){this.wrapper.on(d+x,h+R.task+","+h+R.taskOffset,function(T){T.stopPropagation();
var U=b(this).attr("data-uid");
if(!U){U=b(this).closest(h+R.taskWrap).find(h+R.task).data("uid");
}if(!T.ctrlKey){S.trigger("select",{uid:U});
}else{S.trigger("clear");
}}).on(d+x,h+R.taskWrap,function(T){T.stopPropagation();
b(this).css("z-index","0");
var U=b(document.elementFromPoint(T.clientX,T.clientY));
if(U.hasClass(R.line)){U.click();
}b(this).css("z-index","");
}).on(d+x,h+R.tasksWrapper,function(){if(S.selectDependency().length>0){S.clearSelection();
}else{S.trigger("clear");
}}).on(d+x,h+R.line,function(T){T.stopPropagation();
S.selectDependency(this);
});
}},select:function(T){var R=this.wrapper.find(T);
var S=j.styles;
if(R.length){this.clearSelection();
R.addClass(S.selected);
if(kendo.support.mobileOS){R.parent().addClass(S.taskWrapActive);
}return;
}return this.wrapper.find(h+S.task+h+S.selected);
},selectDependency:function(U){var R=this.wrapper.find(U);
var T;
var S=j.styles;
if(R.length){this.clearSelection();
this.trigger("clear");
T=b(R).attr("data-uid");
this.wrapper.find(h+S.line+"[data-uid='"+T+"']").addClass(S.selected);
return;
}return this.wrapper.find(h+S.line+h+S.selected);
},clearSelection:function(){var R=j.styles;
this.wrapper.find(h+R.selected).removeClass(R.selected);
if(kendo.support.mobileOS){this.wrapper.find(h+R.taskWrapActive).removeClass(R.taskWrapActive);
}},_attachEvents:function(){var T=this;
var S=j.styles;
var R=this.options.editable;
if(R){this._tabindex();
this.wrapper.on(d+x,h+S.taskDelete,function(U){T.trigger("removeTask",{uid:b(this).closest(h+S.taskWrap).find(h+S.task).attr("data-uid")});
U.stopPropagation();
U.preventDefault();
}).on(r+x,function(U){var W;
var V=T.options.editable;
if(U.keyCode===s.DELETE&&V&&V.dependencyDestroy!==false){W=T.selectDependency();
if(W.length){T.trigger("removeDependency",{uid:W.attr("data-uid")});
T.clearSelection();
}}});
if(!kendo.support.mobileOS){this.wrapper.on(f+x,h+S.task+","+h+S.taskOffset,function(U){if(T.options.editable.update!==false){T.trigger("editTask",{uid:b(this).closest(h+S.taskWrap).find(h+S.task).attr("data-uid")});
U.stopPropagation();
U.preventDefault();
}});
}else{this.touch=this.wrapper.kendoTouch({filter:h+S.task+","+h+S.taskOffset,doubletap:function(U){if(T.options.editable.update!==false){T.trigger("editTask",{uid:b(U.touch.currentTarget).closest(h+S.taskWrap).find(h+S.task).attr("data-uid")});
}}}).data("kendoTouch");
}}},_tooltip:function(){var U=this;
var V=this.options.tooltip;
var T=j.styles;
var R;
var S=function(W){R=W.clientX;
};
if(V&&V.visible===false){return;
}if(!kendo.support.mobileOS){this.wrapper.on(u+x,h+T.task,function(){var W=this;
var X=U._taskByUid(b(this).attr("data-uid"));
if(U.dragInProgress){return;
}U._tooltipTimeout=setTimeout(function(){U.view()._createTaskTooltip(X,W,R);
},800);
b(this).on(w,S);
}).on(v+x,h+T.task,function(){clearTimeout(U._tooltipTimeout);
U.view()._removeTaskTooltip();
b(this).off(w,S);
}).on(u+x,h+T.taskOffset,function(){var X=b(this).closest(h+T.taskWrap).find(h+T.task);
var W=U._taskByUid(X.attr("data-uid"));
if(U.dragInProgress){return;
}U._offsetTooltipTimeout=setTimeout(function(){U.view()._createOffsetTooltip(W,X,R);
},800);
b(this).on(w,S);
}).on(v+x,h+T.taskOffset,function(){clearTimeout(U._offsetTooltipTimeout);
U.view()._removeOffsetTooltip();
b(this).off(w,S);
}).on(u+x,h+T.taskPlanned,function(){var X=b(this).closest(h+T.taskWrap).find(h+T.task);
var W=U._taskByUid(X.attr("data-uid"));
U._plannedTooltipTimeout=setTimeout(function(){U.view()._createPlannedTooltip(W,X,R);
},800);
b(this).on(w,S);
}).on(v+x,h+T.taskPlanned,function(){clearTimeout(U._plannedTooltipTimeout);
U.view()._removePlannedTooltip();
b(this).off(w,S);
});
}else{this.wrapper.on(d+x,h+T.taskDelete,function(W){W.stopPropagation();
U.view()._removeTaskTooltip();
}).on(v+x,h+T.task,function(W){var X=b(W.relatedTarget).parents(h+T.taskWrap,h+T.task);
if(X.length===0){U.view()._removeTaskTooltip();
}}).on(v+x,h+T.taskOffset,function(W){var X=b(W.relatedTarget).parents(h+T.taskWrap,h+T.task);
if(X.length===0){U.view()._removeOffsetTooltip();
}}).on(v+x,h+T.taskPlanned,function(W){var X=b(W.relatedTarget).parents(h+T.taskWrap,h+T.task);
if(X.length===0){U.view()._removePlannedTooltip();
}});
if(this.touch){this.touch.bind("tap",function(X){var Y=b(X.touch.target);
var W=X.touch.x.client;
var Z;
if(!Y.hasClass(T.task)){Z=U._taskByUid(Y.closest(h+T.taskWrap).find(h+T.task).attr("data-uid"));
if(U.view()._offsetTooltip){U.view()._removeOffsetTooltip();
}U.view()._createOffsetTooltip(Z,Y,W);
}else{Z=U._taskByUid(Y.attr("data-uid"));
if(U.view()._taskTooltip){U.view()._removeTaskTooltip();
}U.view()._createTaskTooltip(Z,Y,W);
}}).bind("doubletap",function(){U.view()._removeTaskTooltip();
U.view()._removeOffsetTooltip();
});
}}},_setPlanned:function(R){this.options.showPlannedTasks=R;
this.view().options.showPlannedTasks=R;
}});
i(true,j,{styles:L});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
