using System;
using System.Collections;
using System.Collections.Generic;

namespace System.Web.UI.WebControls
{
	// Token: 0x02000363 RID: 867
	public abstract class AutoFieldsGenerator : IAutoFieldGenerator, IStateManager
	{
		// Token: 0x17000B25 RID: 2853
		// (get) Token: 0x06002833 RID: 10291 RVA: 0x0008212F File Offset: 0x0008032F
		// (set) Token: 0x06002834 RID: 10292 RVA: 0x00082137 File Offset: 0x00080337
		internal bool InDataBinding { get; set; }

		// Token: 0x17000B26 RID: 2854
		// (get) Token: 0x06002835 RID: 10293 RVA: 0x00082140 File Offset: 0x00080340
		// (set) Token: 0x06002836 RID: 10294 RVA: 0x00082148 File Offset: 0x00080348
		internal object DataItem { get; set; }

		// Token: 0x06002837 RID: 10295 RVA: 0x00082154 File Offset: 0x00080354
		private ICollection CreateAutoGeneratedFieldsFromFieldProperties()
		{
			List<AutoGeneratedField> list = new List<AutoGeneratedField>();
			foreach (AutoGeneratedFieldProperties fieldProperties in this.AutoGeneratedFieldProperties)
			{
				list.Add(this.CreateAutoGeneratedFieldFromFieldProperties(fieldProperties));
			}
			return list;
		}

		// Token: 0x17000B27 RID: 2855
		// (get) Token: 0x06002838 RID: 10296 RVA: 0x000821B4 File Offset: 0x000803B4
		protected internal List<AutoGeneratedFieldProperties> AutoGeneratedFieldProperties
		{
			get
			{
				if (this._autoGeneratedFieldProperties == null)
				{
					this._autoGeneratedFieldProperties = new List<AutoGeneratedFieldProperties>();
				}
				return this._autoGeneratedFieldProperties;
			}
		}

		// Token: 0x06002839 RID: 10297 RVA: 0x000821D0 File Offset: 0x000803D0
		protected virtual AutoGeneratedField CreateAutoGeneratedFieldFromFieldProperties(AutoGeneratedFieldProperties fieldProperties)
		{
			AutoGeneratedField autoGeneratedField = new AutoGeneratedField(fieldProperties.DataField);
			string name = fieldProperties.Name;
			((IStateManager)autoGeneratedField).TrackViewState();
			autoGeneratedField.HeaderText = name;
			autoGeneratedField.SortExpression = name;
			autoGeneratedField.ReadOnly = fieldProperties.IsReadOnly;
			autoGeneratedField.DataType = fieldProperties.Type;
			return autoGeneratedField;
		}

		// Token: 0x17000B28 RID: 2856
		// (get) Token: 0x0600283A RID: 10298 RVA: 0x0008221D File Offset: 0x0008041D
		protected bool IsTrackingViewState
		{
			get
			{
				return this._tracking;
			}
		}

		// Token: 0x0600283B RID: 10299 RVA: 0x00082228 File Offset: 0x00080428
		protected virtual void TrackViewState()
		{
			this._tracking = true;
			foreach (object obj in this.AutoGeneratedFieldProperties)
			{
				((IStateManager)obj).TrackViewState();
			}
		}

		// Token: 0x0600283C RID: 10300 RVA: 0x00082288 File Offset: 0x00080488
		protected virtual void LoadViewState(object savedState)
		{
			if (savedState != null)
			{
				object[] array = (object[])savedState;
				int num = array.Length;
				this.AutoGeneratedFieldProperties.Clear();
				for (int i = 0; i < num; i++)
				{
					AutoGeneratedFieldProperties autoGeneratedFieldProperties = new AutoGeneratedFieldProperties();
					((IStateManager)autoGeneratedFieldProperties).TrackViewState();
					((IStateManager)autoGeneratedFieldProperties).LoadViewState(array[i]);
					this.AutoGeneratedFieldProperties.Add(autoGeneratedFieldProperties);
				}
			}
		}

		// Token: 0x0600283D RID: 10301 RVA: 0x000822DC File Offset: 0x000804DC
		protected virtual object SaveViewState()
		{
			int count = this.AutoGeneratedFieldProperties.Count;
			object[] array = new object[count];
			for (int i = 0; i < count; i++)
			{
				array[i] = ((IStateManager)this.AutoGeneratedFieldProperties[i]).SaveViewState();
			}
			return array;
		}

		// Token: 0x0600283E RID: 10302
		public abstract List<AutoGeneratedField> CreateAutoGeneratedFields(object dataItem, Control control);

		// Token: 0x17000B29 RID: 2857
		// (get) Token: 0x0600283F RID: 10303 RVA: 0x0008231D File Offset: 0x0008051D
		// (set) Token: 0x06002840 RID: 10304 RVA: 0x00082325 File Offset: 0x00080525
		public bool? AutoGenerateEnumFields { get; set; }

		// Token: 0x06002841 RID: 10305 RVA: 0x0008232E File Offset: 0x0008052E
		public virtual ICollection GenerateFields(Control control)
		{
			if (this.InDataBinding)
			{
				this._autoGeneratedFieldProperties = null;
				return this.CreateAutoGeneratedFields(this.DataItem, control);
			}
			return this.CreateAutoGeneratedFieldsFromFieldProperties();
		}

		// Token: 0x17000B2A RID: 2858
		// (get) Token: 0x06002842 RID: 10306 RVA: 0x00082353 File Offset: 0x00080553
		bool IStateManager.IsTrackingViewState
		{
			get
			{
				return this.IsTrackingViewState;
			}
		}

		// Token: 0x06002843 RID: 10307 RVA: 0x0008235B File Offset: 0x0008055B
		void IStateManager.LoadViewState(object savedState)
		{
			this.LoadViewState(savedState);
		}

		// Token: 0x06002844 RID: 10308 RVA: 0x00082364 File Offset: 0x00080564
		object IStateManager.SaveViewState()
		{
			return this.SaveViewState();
		}

		// Token: 0x06002845 RID: 10309 RVA: 0x0008236C File Offset: 0x0008056C
		void IStateManager.TrackViewState()
		{
			this.TrackViewState();
		}

		// Token: 0x04001DE7 RID: 7655
		private List<AutoGeneratedFieldProperties> _autoGeneratedFieldProperties;

		// Token: 0x04001DE8 RID: 7656
		private bool _tracking;
	}
}
