using System;
using System.Collections.Specialized;
using System.ComponentModel;

namespace System.Web.UI.WebControls
{
	// Token: 0x02000379 RID: 889
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class AutoGeneratedField : BoundField
	{
		// Token: 0x060028E6 RID: 10470 RVA: 0x000843D2 File Offset: 0x000825D2
		public AutoGeneratedField(string dataField)
		{
			this.DataField = dataField;
		}

		// Token: 0x17000B57 RID: 2903
		// (get) Token: 0x060028E7 RID: 10471 RVA: 0x000843E1 File Offset: 0x000825E1
		// (set) Token: 0x060028E8 RID: 10472 RVA: 0x000843E9 File Offset: 0x000825E9
		public override string DataFormatString
		{
			get
			{
				return base.DataFormatString;
			}
			set
			{
				if (!this._suppressPropertyThrows)
				{
					throw new NotSupportedException();
				}
			}
		}

		// Token: 0x17000B58 RID: 2904
		// (get) Token: 0x060028E9 RID: 10473 RVA: 0x000843FC File Offset: 0x000825FC
		// (set) Token: 0x060028EA RID: 10474 RVA: 0x0008442E File Offset: 0x0008262E
		public Type DataType
		{
			get
			{
				object obj = base.ViewState["DataType"];
				if (obj != null)
				{
					return (Type)obj;
				}
				return typeof(string);
			}
			set
			{
				base.ViewState["DataType"] = value;
			}
		}

		// Token: 0x17000B59 RID: 2905
		// (get) Token: 0x060028EB RID: 10475 RVA: 0x00084441 File Offset: 0x00082641
		// (set) Token: 0x060028EC RID: 10476 RVA: 0x000843E9 File Offset: 0x000825E9
		public override bool InsertVisible
		{
			get
			{
				return base.InsertVisible;
			}
			set
			{
				if (!this._suppressPropertyThrows)
				{
					throw new NotSupportedException();
				}
			}
		}

		// Token: 0x17000B5A RID: 2906
		// (get) Token: 0x060028ED RID: 10477 RVA: 0x00084449 File Offset: 0x00082649
		// (set) Token: 0x060028EE RID: 10478 RVA: 0x000843E9 File Offset: 0x000825E9
		public override bool ConvertEmptyStringToNull
		{
			get
			{
				return base.ConvertEmptyStringToNull;
			}
			set
			{
				if (!this._suppressPropertyThrows)
				{
					throw new NotSupportedException();
				}
			}
		}

		// Token: 0x17000B5B RID: 2907
		// (get) Token: 0x060028EF RID: 10479 RVA: 0x00084454 File Offset: 0x00082654
		private bool UseCheckBox
		{
			get
			{
				if (!this._useCheckBoxValid)
				{
					this._useCheckBox = (this.DataType == typeof(bool) || this.DataType == typeof(bool?));
					this._useCheckBoxValid = true;
				}
				return this._useCheckBox;
			}
		}

		// Token: 0x060028F0 RID: 10480 RVA: 0x000844AB File Offset: 0x000826AB
		protected override void CopyProperties(DataControlField newField)
		{
			((AutoGeneratedField)newField).DataType = this.DataType;
			this._suppressPropertyThrows = true;
			((AutoGeneratedField)newField)._suppressPropertyThrows = true;
			base.CopyProperties(newField);
			this._suppressPropertyThrows = false;
			((AutoGeneratedField)newField)._suppressPropertyThrows = false;
		}

		// Token: 0x060028F1 RID: 10481 RVA: 0x000844EB File Offset: 0x000826EB
		protected override DataControlField CreateField()
		{
			return new AutoGeneratedField(this.DataField);
		}

		// Token: 0x060028F2 RID: 10482 RVA: 0x000844F8 File Offset: 0x000826F8
		protected override object GetDesignTimeValue()
		{
			if (this.UseCheckBox)
			{
				return true;
			}
			return base.GetDesignTimeValue();
		}

		// Token: 0x060028F3 RID: 10483 RVA: 0x00084510 File Offset: 0x00082710
		public override void ExtractValuesFromCell(IOrderedDictionary dictionary, DataControlFieldCell cell, DataControlRowState rowState, bool includeReadOnly)
		{
			if (this.UseCheckBox)
			{
				string dataField = this.DataField;
				object obj = null;
				if (cell.Controls.Count > 0)
				{
					Control control = cell.Controls[0];
					CheckBox checkBox = control as CheckBox;
					if (checkBox != null && (includeReadOnly || checkBox.Enabled))
					{
						obj = checkBox.Checked;
					}
				}
				if (obj != null)
				{
					if (dictionary.Contains(dataField))
					{
						dictionary[dataField] = obj;
						return;
					}
					dictionary.Add(dataField, obj);
					return;
				}
			}
			else
			{
				base.ExtractValuesFromCell(dictionary, cell, rowState, includeReadOnly);
			}
		}

		// Token: 0x060028F4 RID: 10484 RVA: 0x00084598 File Offset: 0x00082798
		protected override void InitializeDataCell(DataControlFieldCell cell, DataControlRowState rowState)
		{
			if (this.UseCheckBox)
			{
				CheckBox checkBox = null;
				CheckBox checkBox2 = null;
				if (((rowState & DataControlRowState.Edit) != DataControlRowState.Normal && !this.ReadOnly) || (rowState & DataControlRowState.Insert) != DataControlRowState.Normal)
				{
					CheckBox checkBox3 = new CheckBox();
					checkBox = checkBox3;
					if (this.DataField.Length != 0 && (rowState & DataControlRowState.Edit) != DataControlRowState.Normal)
					{
						checkBox2 = checkBox3;
					}
				}
				else if (this.DataField.Length != 0)
				{
					CheckBox checkBox4 = new CheckBox();
					checkBox4.Enabled = false;
					checkBox = checkBox4;
					checkBox2 = checkBox4;
				}
				if (checkBox != null)
				{
					checkBox.ToolTip = this.HeaderText;
					cell.Controls.Add(checkBox);
				}
				if (checkBox2 != null)
				{
					checkBox2.DataBinding += this.OnDataBindField;
					return;
				}
			}
			else
			{
				base.InitializeDataCell(cell, rowState);
			}
		}

		// Token: 0x060028F5 RID: 10485 RVA: 0x0008463C File Offset: 0x0008283C
		protected override void OnDataBindField(object sender, EventArgs e)
		{
			if (this.UseCheckBox)
			{
				Control control = (Control)sender;
				Control namingContainer = control.NamingContainer;
				object value = this.GetValue(namingContainer);
				if (!(control is CheckBox))
				{
					throw new HttpException(SR.GetString("CheckBoxField_WrongControlType", new object[]
					{
						this.DataField
					}));
				}
				if (DataBinder.IsNull(value))
				{
					((CheckBox)control).Checked = false;
					return;
				}
				if (value is bool)
				{
					((CheckBox)control).Checked = (bool)value;
					return;
				}
				try
				{
					((CheckBox)control).Checked = bool.Parse(value.ToString());
					return;
				}
				catch (FormatException innerException)
				{
					throw new HttpException(SR.GetString("CheckBoxField_CouldntParseAsBoolean", new object[]
					{
						this.DataField
					}), innerException);
				}
			}
			base.OnDataBindField(sender, e);
		}

		// Token: 0x060028F6 RID: 10486 RVA: 0x00006164 File Offset: 0x00004364
		public override void ValidateSupportsCallback()
		{
		}

		// Token: 0x04001E42 RID: 7746
		private bool _suppressPropertyThrows;

		// Token: 0x04001E43 RID: 7747
		private bool _useCheckBox;

		// Token: 0x04001E44 RID: 7748
		private bool _useCheckBoxValid;
	}
}
