using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using System.Web.Util;

namespace System.Web.UI.WebControls
{
	// Token: 0x02000368 RID: 872
	public class GridViewColumnsGenerator : AutoFieldsGenerator
	{
		// Token: 0x06002858 RID: 10328 RVA: 0x00082674 File Offset: 0x00080874
		public override List<AutoGeneratedField> CreateAutoGeneratedFields(object dataObject, Control control)
		{
			if (!(control is GridView))
			{
				throw new ArgumentException(SR.GetString("InvalidDefaultAutoFieldGenerator", new object[]
				{
					base.GetType().FullName,
					typeof(GridView).FullName
				}));
			}
			PagedDataSource pagedDataSource = dataObject as PagedDataSource;
			GridView gridView = control as GridView;
			if (pagedDataSource == null)
			{
				return null;
			}
			List<AutoGeneratedField> list = new List<AutoGeneratedField>();
			bool flag = true;
			PropertyDescriptorCollection propertyDescriptorCollection = ((ITypedList)pagedDataSource).GetItemProperties(new PropertyDescriptor[0]);
			if (propertyDescriptorCollection == null)
			{
				Type type = null;
				object obj = null;
				IEnumerable dataSource = pagedDataSource.DataSource;
				Type type2 = dataSource.GetType();
				PropertyInfo property = type2.GetProperty("Item", BindingFlags.Instance | BindingFlags.Public, null, null, new Type[]
				{
					typeof(int)
				}, null);
				if (property != null)
				{
					type = property.PropertyType;
				}
				if (type == null || type == typeof(object))
				{
					IEnumerator enumerator = pagedDataSource.GetEnumerator();
					if (enumerator.MoveNext())
					{
						obj = enumerator.Current;
					}
					else
					{
						flag = false;
					}
					if (obj != null)
					{
						type = obj.GetType();
					}
					gridView.StoreEnumerator(enumerator, obj);
				}
				if (obj != null && obj is ICustomTypeDescriptor)
				{
					propertyDescriptorCollection = TypeDescriptor.GetProperties(obj);
				}
				else if (type != null)
				{
					if (this.ShouldGenerateField(type, gridView))
					{
						AutoGeneratedFieldProperties autoGeneratedFieldProperties = new AutoGeneratedFieldProperties();
						((IStateManager)autoGeneratedFieldProperties).TrackViewState();
						autoGeneratedFieldProperties.Type = type;
						autoGeneratedFieldProperties.Name = "Item";
						autoGeneratedFieldProperties.DataField = BoundField.ThisExpression;
						AutoGeneratedField autoGeneratedField = this.CreateAutoGeneratedFieldFromFieldProperties(autoGeneratedFieldProperties);
						if (autoGeneratedField != null)
						{
							list.Add(autoGeneratedField);
							base.AutoGeneratedFieldProperties.Add(autoGeneratedFieldProperties);
						}
					}
					else
					{
						propertyDescriptorCollection = TypeDescriptor.GetProperties(type);
					}
				}
			}
			else if (propertyDescriptorCollection.Count == 0)
			{
				flag = false;
			}
			if (propertyDescriptorCollection != null && propertyDescriptorCollection.Count != 0)
			{
				string[] dataKeyNames = gridView.DataKeyNames;
				int num = dataKeyNames.Length;
				string[] array = new string[num];
				for (int i = 0; i < num; i++)
				{
					array[i] = dataKeyNames[i].ToLowerInvariant();
				}
				foreach (object obj2 in propertyDescriptorCollection)
				{
					PropertyDescriptor propertyDescriptor = (PropertyDescriptor)obj2;
					Type propertyType = propertyDescriptor.PropertyType;
					if (this.ShouldGenerateField(propertyType, gridView))
					{
						string name = propertyDescriptor.Name;
						bool isReadOnly = ((IList)array).Contains(name.ToLowerInvariant());
						AutoGeneratedFieldProperties autoGeneratedFieldProperties2 = new AutoGeneratedFieldProperties();
						((IStateManager)autoGeneratedFieldProperties2).TrackViewState();
						autoGeneratedFieldProperties2.Name = name;
						autoGeneratedFieldProperties2.IsReadOnly = isReadOnly;
						autoGeneratedFieldProperties2.Type = propertyType;
						autoGeneratedFieldProperties2.DataField = name;
						AutoGeneratedField autoGeneratedField2 = this.CreateAutoGeneratedFieldFromFieldProperties(autoGeneratedFieldProperties2);
						if (autoGeneratedField2 != null)
						{
							list.Add(autoGeneratedField2);
							base.AutoGeneratedFieldProperties.Add(autoGeneratedFieldProperties2);
						}
					}
				}
			}
			if (list.Count == 0 && flag)
			{
				throw new InvalidOperationException(SR.GetString("GridView_NoAutoGenFields", new object[]
				{
					gridView.ID
				}));
			}
			return list;
		}

		// Token: 0x06002859 RID: 10329 RVA: 0x00082970 File Offset: 0x00080B70
		private bool ShouldGenerateField(Type propertyType, GridView gridView)
		{
			if (gridView.RenderingCompatibility < VersionUtil.Framework45 && base.AutoGenerateEnumFields == null)
			{
				return gridView.IsBindableType(propertyType);
			}
			return DataBoundControlHelper.IsBindableType(propertyType, base.AutoGenerateEnumFields ?? true);
		}
	}
}
