(function(a,b,p){var k="initialize",l="load",f="dataBound",h="expand",e="collapse",c="actionClick",d="change",n="navigate";
var i=a.extend;
var g=a.each;
var m="MissingRadClientDataSource";
var o={0:"vertical",1:"horizontal",vertical:0,horizontal:1,};
a.registerEnum(b,"RadTimelineOrientation",{Vertical:0,Horizontal:1});
b.RadTimeline=function(q){var r=this;
b.RadTimeline.initializeBase(r,[q]);
r._initialized=false;
r._options={};
r.kendoWidget=null;
r.attributes={};
r._skin=null;
r._webServiceClientDataSource="";
r._clientDataSourceID="";
r.clientDataSourceID="";
r._uniqueId=null;
};
b.RadTimeline.prototype={initialize:function(){var s=this;
var r=s._options;
if(s._initialized){return;
}try{s._initialize();
}catch(q){if(q&&q.message==m){if(!s._appLoadAdded){s._appLoadAdded=true;
Sys.Application.add_load(function(){s._initialize();
});
}}else{throw q;
}}},_initialize:function(){var s=this;
if(!s._options){return;
}b.RadTimeline.callBaseMethod(s,"initialize");
var r=s.clientDataSourceID||s._webServiceClientDataSource;
if(r){var q=$find(r);
if(q&&(q instanceof b.RadClientDataSource)){s._clientDataSource=q;
s._clientDataSource.set_parent(s);
if(s._itemsData){q.set_data(s._itemsData);
}s._options.dataSource=q._kendoDataSource;
}else{if(q===null){throw new Error(m);
}}}s.raiseEvent(k);
s._initializeKendoWidget();
s._initialized=true;
s.raiseEvent(l);
},dispose:function(){var q=this;
if(q.kendoWidget){q.kendoWidget.destroy();
}delete q.kendoWidget;
delete q._options;
b.RadTimeline.callBaseMethod(q,"dispose");
},_initializeKendoWidget:function(){var r=this;
if(r._options.orientation!==p){r._options.orientation=o[r._options.orientation];
}var q=j(r._options,r);
r.kendoWidget=a(r._element).kendoTimeline(q).getKendoTimeline();
},get_kendoWidget:function(){return this.kendoWidget;
},get_clientDataSource:function(){return this._clientDataSource;
},get_items:function(){return this.kendoWidget.items();
},get_dataItems:function(){return this.kendoWidget.dataSource.data();
},expand:function(q){this.kendoWidget.expand(q);
},collapse:function(q){this.kendoWidget.collapse(q);
},open:function(q){this.kendoWidget.open(q);
},next:function(){this.kendoWidget.next();
},previous:function(){this.kendoWidget.previous();
},repaint:function(){this.kendoWidget.redraw();
},get_orientation:function(){return o[this.kendoWidget.options.orientation];
}};
b.RadTimeline.registerClass("Telerik.Web.UI.RadTimeline",b.RadWebControl);
function j(r,s){var q=$telerik.$.extend({},r,{change:function(u){var t={sender:u.sender,dataItem:u.dataItem,eventContainer:u.eventContainer,};
if(a.raiseCancellableControlEvent(s,d,t)){u.preventDefault();
}else{s.updateClientState();
}},expand:function(u){var t={sender:u.sender,dataItem:u.dataItem};
if(a.raiseCancellableControlEvent(s,h,t)){u.preventDefault();
}},collapse:function(u){var t={sender:u.sender,dataItem:u.dataItem};
if(a.raiseCancellableControlEvent(s,e,t)){u.preventDefault();
}},actionClick:function(u){var t={sender:u.sender,dataItem:u.dataItem,element:u.element};
if(a.raiseCancellableControlEvent(s,c,t)){u.preventDefault();
}},navigate:function(u){var t={sender:u.sender,action:u.action};
if(a.raiseCancellableControlEvent(s,n,t)){u.preventDefault();
}},dataBound:function(u){var t={sender:u.sender};
if(!s.kendoWidget){s.kendoWidget=u.sender;
}a.raiseControlEvent(s,"dataBound",t);
}});
return q;
}b.RadTimeline._getWidgetOptions=function(){var r=a.extend(true,{},kendo.ui.Timeline.fn.options);
var q=["dplProcessing","name","prefix","toolbar","view","page","scale","pdfjsProcessing"];
g(q,function(s,t){delete r[t];
});
return r;
};
b.RadTimeline._registerControlProperties=function(q){a.each(q,function(s,r){if(!b.RadTimeline.prototype["get_"+s]){b.RadTimeline.prototype["get_"+s]=function(){return this.kendoWidget?this.kendoWidget.options[s]:p;
};
}});
};
b.RadTimeline._registerControlProperties(b.RadTimeline._getWidgetOptions());
a.registerControlEvents(b.RadTimeline,[k,l,f,d,h,e,c,n]);
a.registerControlProperties(b.RadTimeline,{itemsData:[],attributes:{},_pendingPostbackCommandArgs:null,});
})($telerik.$,Telerik.Web.UI);
