using System;

namespace TechnoPro.Common.DAO.Impl.AppointmentsWorkshops
{
	// Token: 0x02000140 RID: 320
	internal static class QueryStorageWorkshopDefinition
	{
		// Token: 0x04000594 RID: 1428
		internal const string QS_WORKSHOP_DEFINITIONS_BY_APP_TYPE_IDS = "SELECT\tw.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees,w.WorkshopFee,\r\n\t\tw.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n\t\tat.[description] AS apptypedescription,at.defaultcolour,at.iscourse,at.isworkshop,at.appointmentTypeGroupID,\r\n        atg.title AS apptypegrouptitle,\r\n\t\tw.personID AS p1personid,p.firstName AS p1firstname,p.lastName AS p1lastname,p.student_no AS p1student_no,\r\n        pgp.groupid AS p1groupid,\r\n\t\tw.personID2 AS p2personid,p2.firstName AS p2firstname,p2.lastName AS p2lastname,p2.student_no AS p2student_no,\r\n        pgp2.groupid AS p2groupid,\r\n\t\tw.personID3 AS p3personid,p3.firstName AS p3firstname,p3.lastName AS p3lastname,p3.student_no AS p3student_no,\r\n        pgp3.groupid AS p3groupid\r\nFROM\tWorkshops w LEFT JOIN AppointmentTypes at ON at.AppTypeID=w.AppTypeID \r\n        LEFT JOIN appointmenttypegroups atg ON atg.appointmenttypegroupid=at.appointmenttypegroupid\r\n\t\tLEFT JOIN people p ON p.PersonID=w.personID\r\n        LEFT JOIN peoplegroups pgp ON pgp.personid=p.personid AND pgp.groupid<10\r\n\t\tLEFT JOIN people p2 ON p2.PersonID=w.personID2\r\n        LEFT JOIN peoplegroups pgp2 ON pgp2.personid=p2.personid AND pgp2.groupid<10\r\n\t\tLEFT JOIN people p3 ON p3.PersonID=w.personID3\r\n        LEFT JOIN peoplegroups pgp3 ON pgp3.personid=p3.personid AND pgp3.groupid<10\r\nWHERE   w.isactive=1 AND w.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\nORDER BY at.[description],w.AppTypeID,w.workshopTitle,pgp.groupid,pgp2.groupid,pgp3.groupid";

		// Token: 0x04000595 RID: 1429
		internal const string QS_WORKSHOP_DEFINITION_BY_WORKSHOP_ID = "SELECT\tw.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees,w.WorkshopFee,\r\n\t\tw.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n\t\tat.[description] AS apptypedescription,at.defaultcolour,at.iscourse,at.isworkshop,at.appointmentTypeGroupID,\r\n        atg.title AS apptypegrouptitle,\r\n\t\tw.personID AS p1personid,p.firstName AS p1firstname,p.lastName AS p1lastname,p.student_no AS p1student_no,\r\n        pgp.groupid AS p1groupid,\r\n\t\tw.personID2 AS p2personid,p2.firstName AS p2firstname,p2.lastName AS p2lastname,p2.student_no AS p2student_no,\r\n        pgp2.groupid AS p2groupid,\r\n\t\tw.personID3 AS p3personid,p3.firstName AS p3firstname,p3.lastName AS p3lastname,p3.student_no AS p3student_no,\r\n        pgp3.groupid AS p3groupid\r\nFROM\tWorkshops w LEFT JOIN AppointmentTypes at ON at.AppTypeID=w.AppTypeID \r\n        LEFT JOIN appointmenttypegroups atg ON atg.appointmenttypegroupid=at.appointmenttypegroupid\r\n\t\tLEFT JOIN people p ON p.PersonID=w.personID\r\n        LEFT JOIN peoplegroups pgp ON pgp.personid=p.personid AND pgp.groupid<10\r\n\t\tLEFT JOIN people p2 ON p2.PersonID=w.personID2\r\n        LEFT JOIN peoplegroups pgp2 ON pgp2.personid=p2.personid AND pgp2.groupid<10\r\n\t\tLEFT JOIN people p3 ON p3.PersonID=w.personID3\r\n        LEFT JOIN peoplegroups pgp3 ON pgp3.personid=p3.personid AND pgp3.groupid<10\r\nWHERE  w.isactive=1 AND w.workshopid=@workshopid\r\nORDER BY at.[description],w.AppTypeID,w.workshopTitle,pgp.groupid,pgp2.groupid,pgp3.groupid";

		// Token: 0x04000596 RID: 1430
		internal const string QI_WORKSHOPS_UPDATE_WORKSHOP_DEFINITION = "update Workshops\r\nSET AppTypeID = @apptypeid,\r\n\tworkshopTitle = @workshoptitle,\r\n\tworkshopDescription = @workshopdescription,\r\n\tMaxAttendees = @maxattendees,\r\n\tWorkshopFee = @workshopfee,\r\n\tpersonID = @personid,\r\n\tpersonID2 = @personid2,\r\n\tpersonID3 = @personid3,\r\n\tnote = @note,\r\n\tlocation = @location\r\nWHERE WorkshopID = @workshopid";

		// Token: 0x04000597 RID: 1431
		internal const string QI_WORKSHOPS_NEW_WORKSHOP_DEFINITION = "INSERT INTO Workshops(AppTypeID, workshopTitle, workshopDescription, MaxAttendees, WorkshopFee, personID, personID2, personID3, note, location)\r\nVALUES (@apptypeid, @workshoptitle, @workshopdescription, @maxattendees, @workshopfee, @personid, @personid2, @personid3, @note, @location)\r\nSET @workshopid = SCOPE_IDENTITY()";

		// Token: 0x04000598 RID: 1432
		internal const string QD_WORKSHOPS_DELETE_WORKSHOP_BY_ID = "if exists(select 1 from AppointmentWorkshops where WorkshopID=@workshopid)\r\nbegin\r\n\tupdate Workshops SET isactive=0 WHERE WorkshopID=@workshopid\r\nend\r\nelse\r\nbegin\r\n\tDELETE FROM Workshops WHERE WorkshopID=@workshopid\r\nend";
	}
}
