using System;

namespace TechnoPro.Common.DAO.Impl.AppointmentsWorkshops
{
	// Token: 0x02000142 RID: 322
	public class QueryStorageWorkshopAppointments
	{
		// Token: 0x0400059B RID: 1435
		internal const string QS_WORKSHOP_APPOINTMENT = "SELECT\tw.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees,w.WorkshopFee,\r\n\t\tw.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n\t\tat.[description] as apptypedescription,at.appointmentTypeGroupID,at.defaultColour,at.isWorkshop,at.isCourse,\r\n\t\tatg.AppointmentTypeGroupID,atg.title as apptypegrouptitle,\r\n\t\tw.personID AS p1personid,p.firstName AS p1firstname,p.lastName AS p1lastname,p.student_no AS p1student_no,\r\n\t\tw.personID2 AS p2personid,p2.firstName AS p2firstname,p2.lastName AS p2lastname,p2.student_no AS p2student_no,\r\n\t\tw.personID3 AS p3personid,p3.firstName AS p3firstname,p3.lastName AS p3lastname,p3.student_no AS p3student_no,\r\n        aw.maxattendees AS maxattendeescount\r\nFROM\tappointmentworkshops aw LEFT JOIN Workshops w ON w.workshopid=aw.workshopid\r\n        LEFT JOIN AppointmentTypes at ON at.AppTypeID=w.AppTypeID \r\n        LEFT JOIN AppointmentTypeGroups atg ON at.appointmentTypeGroupID=atg.AppointmentTypeGroupID\r\n\t\tLEFT JOIN people p ON p.PersonID=w.personID\r\n\t\tLEFT JOIN people p2 ON p2.PersonID=w.personID2\r\n\t\tLEFT JOIN people p3 ON p3.PersonID=w.personID3\r\nWHERE   aw.appointmentid=@appid\r\nORDER BY at.[description],w.AppTypeID,w.workshopTitle";

		// Token: 0x0400059C RID: 1436
		internal const string QS_WORKSHOP_APPOINTMENTS_BY_APP_TYPE_AND_DATE = "SELECT    a.appointmentid,a.startdate,a.enddate,a.subject AS subtitle,a.location,a.ishidden,a.islocked,a.cancelled,\r\n            am.memotext,am.isencrypted,a.description,a.appcode,sta.showtimeastitle,sta.extraiconid,\r\n            a.personid,p2.firstname,p2.middlename,p2.lastname,p2.student_no,\r\n            a.whoadded AS whobookedpersonid,p.firstname AS whobookedfirstname,p.lastname AS whobookedlastname,p.student_no AS whobookedstudent_no,\r\n            a.dateAdded,a.groupcode,a.extraattendeescount,\r\n            w.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees AS DefaultMaxAttendees,w.WorkshopFee,\r\n\t\t    w.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n            CAST(NULL AS int) AS p1personid, -- not loading facilitators for this view\r\n\t\t    CAST(NULL AS int) AS p2personid,\r\n\t\t    CAST(NULL AS int) AS p3personid,\r\n            COALESCE(aw.maxattendees,w.maxattendees) AS maxattendees\r\nFROM        apps a LEFT JOIN people p ON p.personid=a.whoadded\r\n            LEFT JOIN appointmentmemos am ON am.appointmentid=a.appointmentid\r\n            LEFT JOIN people p2 ON p2.personid=a.personid\r\n            LEFT JOIN appointmentworkshops aw ON aw.appointmentid=a.appointmentid\r\n            LEFT JOIN workshops w ON w.workshopid=aw.workshopid\r\n            LEFT JOIN appointmentshowtimeas sta ON sta.appointmentshowtimeasid=a.appcode\r\nWHERE       w.isactive=1 AND a.apptypeid=@apptypeid\r\n            AND NOT ( a.enddate <= @startdate OR a.startdate > @enddate)\r\nORDER BY    a.startdate,a.apptypeid,aw.workshopid";

		// Token: 0x0400059D RID: 1437
		internal const string QS_WORKSHOP_APPOINTMENTS_BY_DATE_RANGE_AND_APP_TYPE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\ta.AttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   at.isWorkshop=1\r\n\t\tAND a.startdate >= @startdate AND a.startdate < @enddate\r\n        AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x0400059E RID: 1438
		internal const string QS_WORKSHOP_APPOINTMENTS_BY_DATE_RANGE_AND_APP_TYPE_AND_WORKSHOP_ID = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\ta.AttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   at.isWorkshop=1\r\n\t\tAND a.startdate >= @startdate AND a.startdate < @enddate\r\n        AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\n        AND (@workshopid IS NULL OR @workshopid < 1 OR a.appointmentid IN (SELECT appointmentid FROM appointmentworkshops WHERE workshopid=@workshopid))\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x0400059F RID: 1439
		internal const string QS_WORKSHOP_APPOINTMENTS_BY_WORKSHOP_AND_DATE = "SELECT    a.appointmentid,a.startdate,a.enddate,a.subject AS subtitle,a.location,a.ishidden,a.islocked,a.cancelled,\r\n            am.memotext,am.isencrypted,a.description,a.appcode,sta.showtimeastitle,sta.extraiconid,\r\n            a.personid,p2.firstname,p2.middlename,p2.lastname,p2.student_no,\r\n            a.noshow,a.misccode,a.attendeeid,\r\n            a.whoadded AS whobookedpersonid,p.firstname AS whobookedfirstname,p.lastname AS whobookedlastname,p.student_no AS whobookedstudent_no,\r\n            a.dateadded,a.groupcode,a.extraattendeescount,\r\n            w.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees AS DefaultMaxAttendees,w.WorkshopFee,\r\n\t\t    w.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n            CAST(NULL AS int) AS p1personid, -- not loading facilitators for this view\r\n\t\t    CAST(NULL AS int) AS p2personid,\r\n\t\t    CAST(NULL AS int) AS p3personid,\r\n            COALESCE(aw.maxattendees,w.maxattendees) AS maxattendees\r\nFROM        apps a \r\n\t\t\tLEFT JOIN people p ON p.personid=a.whoadded\r\n            LEFT JOIN appointmentmemos am ON am.appointmentid=a.appointmentid\r\n            LEFT JOIN people p2 ON p2.personid=a.personid\r\n            LEFT JOIN appointmentworkshops aw ON aw.appointmentid=a.appointmentid\r\n            LEFT JOIN workshops w ON w.workshopid=aw.workshopid\r\n            LEFT JOIN appointmentshowtimeas sta ON sta.appointmentshowtimeasid=a.appcode\r\nWHERE       w.isactive=1 AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\n            AND NOT aw.workshopid IS NULL\r\n            AND aw.workshopid=@workshopid\r\n            AND NOT ( a.enddate <= @startdate OR a.startdate > @enddate)\r\nORDER BY    a.startdate,a.apptypeid,aw.workshopid";

		// Token: 0x040005A0 RID: 1440
		internal const string QS_WORKSHOP_APPOINTMENT_BY_ID = "SELECT    a.appointmentid,a.startdate,a.enddate,a.subject AS subtitle,a.location,a.ishidden,a.islocked,a.cancelled,\r\n            am.memotext,am.isencrypted,a.description,a.appcode,sta.showtimeastitle,sta.extraiconid,\r\n            a.personid,p2.firstname,p2.middlename,p2.lastname,p2.student_no,\r\n            a.noshow,a.misccode,a.attendeeid,\r\n            a.whoadded AS whobookedpersonid,p.firstname AS whobookedfirstname,p.lastname AS whobookedlastname,p.student_no AS whobookedstudent_no,\r\n            a.dateadded,a.groupcode,a.extraattendeescount,\r\n            w.workshopid,w.apptypeid,w.workshopTitle,w.workshopDescription,w.MaxAttendees AS DefaultMaxAttendees,w.WorkshopFee,\r\n\t\t    w.partners,w.note,w.location,w.availableForOnlineBooking,w.waitingListMaxUsers,\r\n            CAST(NULL AS int) AS p1personid, -- not loading facilitators for this view\r\n\t\t    CAST(NULL AS int) AS p2personid,\r\n\t\t    CAST(NULL AS int) AS p3personid,\r\n            COALESCE(aw.maxattendees,w.maxattendees) AS maxattendees\r\nFROM        apps a \r\n\t\t\tLEFT JOIN people p ON p.personid=a.whoadded\r\n            LEFT JOIN appointmentmemos am ON am.appointmentid=a.appointmentid\r\n            LEFT JOIN people p2 ON p2.personid=a.personid\r\n            LEFT JOIN appointmentworkshops aw ON aw.appointmentid=a.appointmentid\r\n            LEFT JOIN workshops w ON w.workshopid=aw.workshopid\r\n            LEFT JOIN appointmentshowtimeas sta ON sta.appointmentshowtimeasid=a.appcode\r\nWHERE       w.isactive=1 AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,',')) and\r\n            aw.appointmentid=@appointmentid\r\nORDER BY    a.startdate,a.apptypeid,aw.workshopid";

		// Token: 0x040005A1 RID: 1441
		internal const string QU_WORKSHOP_APPOINTMENT = "IF exists (SELECT 1 from appointmentworkshops where appointmentid=@appid)\r\n\tbegin\r\n\t\tUPDATE appointmentworkshops SET workshopid=@workshopid,maxattendees=@maxattendees WHERE appointmentid=@appid\r\n\tend\r\nelse\r\n\tbegin\r\n\t\tinsert INTO appointmentworkshops (appointmentid, workshopid, maxattendees) VALUES(@appid, @workshopid, @maxattendees)\r\n\tend";

		// Token: 0x040005A2 RID: 1442
		internal const string QU_APPOINTMENT_WORKSHOPID = "IF exists (SELECT 1 from appointmentworkshops where appointmentid=@appid)\r\n\tbegin\r\n\t\tUPDATE appointmentworkshops SET workshopid=@workshopid WHERE appointmentid=@appid\r\n\tend\r\nelse\r\n\tbegin\r\n\t\tinsert INTO appointmentworkshops (appointmentid, workshopid) VALUES(@appid, @workshopid)\r\n\tend";

		// Token: 0x040005A3 RID: 1443
		internal const string QU_APPOINTMENT_WORKSHOP_MAX_ATTENDEES = "IF exists (SELECT 1 from appointmentworkshops where appointmentid=@appid)\r\n\tbegin\r\n\t\tUPDATE appointmentworkshops SET maxattendees=@maxattendees WHERE appointmentid=@appid\r\n\tend\r\nelse\r\n\tbegin\r\n        DECLARE @primaryAppId int = (SELECT groupcode FROM appointments WHERE appointmentid=@appid)\r\n        DECLARE @workshopId int = (SELECT workshopid FROM appointmentworkshops WHERE appointmentid=@primaryAppId)\r\n        IF NOT @workshopId IS NULL\r\n\t\t    insert INTO appointmentworkshops (appointmentid, workshopid, maxattendees) VALUES(@appid, @workshopId, @maxattendees)\r\n\tend";

		// Token: 0x040005A4 RID: 1444
		internal const string QD_APPOINTMENT_WORKSHOP = "DELETE FROM appointmentworkshops WHERE appointmentid=@appid";
	}
}
