using System;

namespace TechnoPro.Common.DAO.Impl.Notetaking
{
	// Token: 0x02000087 RID: 135
	public class QueryStorageNotetaking
	{
		// Token: 0x04000180 RID: 384
		internal const string QS_STUDENTS_RECEIVING_NOTES = "SELECT\tr.serviceproviderrequestid,r.ServiceProviderId,r.serviceproviderlucourseid,\r\n\t\tr.personid,p.lastName,p.firstName,p.middleName,p.student_no,\r\n\t\t\r\n\t\tr.lucourseid,luc.startdate,luc.enddate,luc.duration,luc.[term],luc.[subjectid],luc.course,luc.[section],\r\n\t\tluc.timeofday,luc.campus,lucd.altLookupString AS [subject],luc.department,luc.[location],luc.coursenote,\r\n\r\n\t\tr.serviceproviderlucourseid,luc2.LUCourseID AS sp_lucourseid,luc2.startdate AS sp_startdate,luc2.enddate AS sp_enddate,luc2.duration AS sp_duration,luc2.[term] AS sp_term,\t\r\n\t\tluc2.[subjectid] AS sp_subjectid,luc2.course AS sp_course,luc2.[section] AS sp_section,\r\n\t\tluc2.timeofday AS sp_timeofday,luc2.campus AS sp_campus,lucd2.altLookupString AS sp_subject,luc2.department AS sp_department,\r\n\t\tluc2.[location] AS sp_location,luc2.coursenote AS sp_coursenote\r\nFROM\tServiceProviderRequests r LEFT JOIN people p ON p.PersonID=r.personid\r\n\t\tLEFT JOIN lucourses luc ON luc.LUCourseID=r.lucourseid\r\n\t\tLEFT JOIN lucoursedata lucd ON lucd.luCourseDataID=luc.SubjectID\r\n\t\tLEFT JOIN lucourses luc2 ON luc2.LUCourseID=r.serviceproviderlucourseid\r\n\t\tLEFT JOIN lucoursedata lucd2 ON lucd2.luCourseDataID=luc2.SubjectID \r\nWHERE\tr.IsActive=1 AND r.serviceprovidertype=@sptype\r\n\t\tAND NOT r.ServiceProviderId IS NULL AND r.ServiceProviderId=@spid \r\n\t\tAND r.serviceproviderlucourseid=@lucid";

		// Token: 0x04000181 RID: 385
		internal const string QS_NOTETAKER_COURSES_BY_DATE = "SELECT\tDISTINCT spac.lucourseid INTO #t1\r\nFROM\tserviceproviderapplications spa LEFT JOIN serviceproviderapplicationcourses spac ON spac.ServiceProviderApplicationId=spa.ServiceProviderApplicationId\r\n\t\tLEFT JOIN lucourses luc ON luc.LUCourseID=spac.lucourseid\r\nWHERE\tspa.serviceproviderid=@spid AND spa.serviceprovidertype=128 AND (spac.registrationstatus IS NULL OR NOT spac.registrationstatus=2)\r\n        AND NOT ( ( luc.enddate<@sd ) OR (luc.startdate > @ed ) )\r\n\r\nSELECT\t#t1.lucourseid,luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS [subject],luc.course,\r\n\t\tluc.section,luc.timeofday,luc.campus,luc.subjectid\r\nFROM\t#t1 LEFT JOIN lucourses luc ON luc.lucourseid=#t1.lucourseid\r\n\t\tLEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n\r\nDROP TABLE #t1";

		// Token: 0x04000182 RID: 386
		internal const string QS_NOTETAKER_AVAILABLE_COURSE_UNIQUE_DATES = "SELECT\tDISTINCT spac.lucourseid INTO #t1\r\nFROM\tserviceproviderapplications spa LEFT JOIN serviceproviderapplicationcourses spac ON spac.ServiceProviderApplicationId=spa.ServiceProviderApplicationId\r\nWHERE\tspa.serviceproviderid=@spid AND spa.serviceprovidertype=128 AND (spac.registrationstatus IS NULL OR NOT spac.registrationstatus=2)\r\n\r\nSELECT DISTINCT x.startdate FROM\r\n(\r\nSELECT luc.startdate FROM #t1 LEFT JOIN lucourses luc ON luc.LUCourseID=#t1.lucourseid\r\nUNION\r\nSELECT luc.enddate AS startdate FROM #t1 LEFT JOIN lucourses luc ON luc.LUCourseID=#t1.lucourseid\r\n) x\r\n\r\nDROP TABLE #t1";

		// Token: 0x04000183 RID: 387
		internal const string QS_STUDENT_DOWNLOAD_HISTORY_BY_STUDENT_AND_COURSE_LAST_DATE_DOWNLOADED_FOR_EACH_LECTURE_NOTE = "SELECT nds.personid,nds.lucourseid,nds.notetakerdocumentid,nds.datedownloaded,\r\n         p.firstname,p.middlename,p.lastname,p.student_no,\r\n         luc.startdate,luc.enddate,luc.duration,luc.term,luc.subjectid,lucd.altlookupstring AS subject,luc.course,luc.[section],luc.timeofday,\r\n         nds.docname,nds.sizeinbytes,nds.datecreated,nds.notetakerid,nds.notetakerid AS serviceproviderid,nds.notes,nds.lecturedate,nds.issamplenotes,nds.deletiondate,\r\n         sp.firstname,sp.lastname,sp.student_no,sp.altid,sp.email,sp.phone1,sp.phone2\r\nFROM     NotetakingStudentDownloadHistoryMaxDatePerLectureNote nds LEFT JOIN people p ON p.personid=nds.personid\r\n         LEFT JOIN lucourses luc ON luc.lucourseid=nds.lucourseid\r\n         LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n         LEFT JOIN serviceproviders sp ON sp.serviceproviderid=nds.notetakerid\r\nWHERE    nds.personid=@pid AND nds.lucourseid=@lucid\r\nORDER BY nds.lecturedate DESC";

		// Token: 0x04000184 RID: 388
		internal const string QS_STUDENT_DOWNLOAD_HISTORY_BY_STUDENT_AND_COURSE = "SELECT nds.personid,nds.lucourseid,nds.notetakerdocumentid,nds.datedownloaded,\r\n         p.firstname,p.middlename,p.lastname,p.student_no,\r\n         luc.startdate,luc.enddate,luc.duration,luc.term,luc.subjectid,lucd.altlookupstring AS subject,luc.course,luc.[section],luc.timeofday,\r\n         nd.docname,nd.sizeinbytes,nd.datecreated,nd.notetakerid,nd.notetakerid AS serviceproviderid,nd.notes,nd.lecturedate,nd.issamplenotes,nd.deletiondate,\r\n         sp.firstname,sp.lastname,sp.student_no,sp.altid,sp.email,sp.phone1,sp.phone2\r\nFROM     NotetakerDocumentStudentDownloads nds LEFT JOIN people p ON p.personid=nds.personid\r\n         LEFT JOIN lucourses luc ON luc.lucourseid=nds.lucourseid\r\n         LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n         LEFT JOIN notetakerdocument nd ON nd.notetakerdocumentid=nds.notetakerdocumentid\r\n         LEFT JOIN serviceproviders sp ON sp.serviceproviderid=nd.notetakerid\r\nWHERE    nds.personid=@pid AND nds.lucourseid=@lucid\r\nORDER BY nds.datedownloaded DESC";

		// Token: 0x04000185 RID: 389
		internal const string QS_LOAD_NOTETAKERBASE_WITH_NOTES_AND_COURSEBASE_FOR_EQUIVALENT_COURSES = "SELECT DISTINCT ec.lucourseid,nd.notetakerid AS serviceproviderid,\r\n\tsp.firstname,sp.lastname,sp.middlename,sp.student_no,sp.email,sp.altid,\r\n    luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.course,\r\n    luc.section,luc.timeofday,lucd2.altlookupstring AS pinstructorname,luc.instructorid AS pinstructorid,\r\n    lucd2.email AS pinstructoremail,lucd2.phone AS pinstructorphone,lucd2.externalid AS pinstructorexternalid,\r\n    lucd2.id AS pinstructoremployeeid,\r\n    luc.subjectid\r\nFROM EquivalentCoursesChooser(@lucid,@equivalentsettingnum) ec LEFT JOIN NotetakerDocument nd \r\n\t\tON nd.LUCourseId=ec.lucourseid\r\nLEFT JOIN ServiceProviders sp ON sp.ServiceProviderId=nd.NotetakerID\r\nLEFT JOIN lucourses luc ON luc.lucourseid=ec.lucourseid\r\nLEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\nLEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=luc.notetakerid";

		// Token: 0x04000186 RID: 390
		internal const string QS_NOTETAKERBASE_BY_USERNAME = "SELECT    sp.serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.email,sp.altid\r\nFROM        serviceproviders sp \r\nWHERE       sp.isactive=1 AND\r\n            (\r\n                sp.altid=@usernameu OR sp.altid=@usernamel\r\n            )";

		// Token: 0x04000187 RID: 391
		internal const string QS_NOTETAKERBASE_BY_EMAIL = "SELECT    sp.serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.email,sp.altid\r\nFROM        serviceproviders sp \r\nWHERE       sp.isactive=1 AND\r\n            (\r\n                sp.email=@emailu OR sp.email=@emaill\r\n            )";

		// Token: 0x04000188 RID: 392
		internal const string QS_NOTETAKERBASE_BY_STUDENT_NUMBER = "SELECT    sp.serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.email,sp.altid\r\nFROM        serviceproviders sp \r\nWHERE       sp.isactive=1 AND\r\n            (\r\n                sp.student_no=@StudentNumber0 OR sp.student_no=@StudentNumber1\r\n            )";

		// Token: 0x04000189 RID: 393
		internal const string QS_NOTETAKERBASE_BY_ID = "SELECT    sp.serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.email,sp.altid\r\nFROM        serviceproviders sp \r\nWHERE       sp.serviceproviderid=@id";

		// Token: 0x0400018A RID: 394
		internal const string QS_LOOKUP_COURSE_BASE_EQUIVALENTS = "SELECT    ec.lucourseid,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.course,\r\n            luc.section,luc.timeofday,lucd2.altlookupstring AS pinstructorname,luc.instructorid AS pinstructorid,\r\n            lucd2.email AS pinstructoremail,lucd2.phone AS pinstructorphone,lucd2.externalid AS pinstructorexternalid,\r\n            lucd2.id AS pinstructoremployeeid,\r\n            luc.subjectid\r\nFROM        EquivalentCoursesChooser(@lucid,@equivalentsettingnum) ec LEFT JOIN lucourses luc ON luc.lucourseid=ec.lucourseid\r\n            LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n            LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=luc.notetakerid";

		// Token: 0x0400018B RID: 395
		internal const string QS_NOTETAKERBASE_BY_NOTEAKEE_AND_COURSE = "SELECT    spr.serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.email,sp.altid\r\nFROM        serviceproviderrequests spr LEFT JOIN serviceproviders sp ON sp.serviceproviderid=spr.serviceproviderid\r\nWHERE       spr.isactive=1 AND spr.personid=@pid AND spr.lucourseid=@lucid";

		// Token: 0x0400018C RID: 396
		internal const string QS_LECTURE_NOTE_DESCRIPTIONS_BY_NOTETAKER_AND_COURSE = "SELECT    nd.notetakerdocumentid,nd.docname,nd.numpages,nd.sizeinbytes,nd.datecreated,nd.DeletionDate,\r\n            nd.notetakerid AS serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.altid,sp.email,\r\n            nd.notes,nd.lecturedate,nd.lucourseid,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.course,\r\n            luc.section,luc.timeofday,lucd2.altlookupstring AS pinstructorname,luc.instructorid AS pinstructorid,\r\n            lucd2.email AS pinstructoremail,lucd2.phone AS pinstructorphone,lucd2.externalid AS pinstructorexternalid,\r\n            lucd2.id AS pinstructoremployeeid,\r\n            luc.subjectid\r\nFROM        notetakerdocument nd LEFT JOIN serviceproviders sp ON sp.serviceproviderid=nd.notetakerid\r\n            LEFT JOIN lucourses luc ON luc.lucourseid=nd.lucourseid\r\n            LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n            LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=luc.instructorid\r\nWHERE       nd.notetakerid=@spid AND nd.lucourseid=@lucid\r\nORDER BY    nd.lecturedate";

		// Token: 0x0400018D RID: 397
		internal const string QS_LECTURE_NOTE_DESCRIPTIONS_BY_STUDENT_AND_COURSE = "SELECT DISTINCT serviceproviderid,serviceproviderlucourseid INTO #t1 FROM ServiceProviderRequests WHERE personid=@studentpid AND NOT lucourseid IS NULL AND lucourseid=@studentlucid AND NOT serviceproviderid IS NULL AND NOT serviceproviderlucourseid IS NULL\r\n\r\nSELECT lucourseid INTO #tlucids FROM EquivalentCourses(@studentlucid)\r\n\r\n--add in possible other serviceproviders with notes\r\nINSERT INTO #t1 (serviceproviderid,serviceproviderlucourseid)\r\n\tSELECT DISTINCT notetakerid AS serviceproviderid,LUCourseId AS serviceproviderlucourseid FROM NotetakerDocument WHERE lucourseid IN (SELECT lucourseid FROM #tlucids)\r\n\r\nSELECT    nd.notetakerdocumentid,nd.docname,nd.numpages,nd.sizeinbytes,nd.datecreated,nd.DeletionDate,\r\n            nd.notetakerid AS serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.altid,sp.email,\r\n            nd.notes,nd.lecturedate,nd.lucourseid,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.course,\r\n            luc.section,luc.timeofday,lucd2.altlookupstring AS pinstructorname,luc.instructorid AS pinstructorid,\r\n            lucd2.email AS pinstructoremail,lucd2.phone AS pinstructorphone,lucd2.externalid AS pinstructorexternalid,\r\n            lucd2.id AS pinstructoremployeeid,\r\n            luc.subjectid\r\nFROM        notetakerdocument nd LEFT JOIN serviceproviders sp ON sp.serviceproviderid=nd.notetakerid\r\n            LEFT JOIN lucourses luc ON luc.lucourseid=nd.lucourseid\r\n            LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n            LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=luc.instructorid\r\nWHERE       EXISTS(SELECT serviceproviderid FROM #t1 WHERE serviceproviderid=nd.NotetakerID AND serviceproviderlucourseid=nd.lucourseid)\r\nORDER BY    nd.lecturedate\r\n\r\nDROP TABLE #t1\r\nDROP TABLE #tlucids";

		// Token: 0x0400018E RID: 398
		internal const string QS_LECTURE_NOTE_BY_ID = "SELECT    nd.notetakerdocumentid,nd.docname,nd.numpages,nd.sizeinbytes,nd.datecreated,nd.DeletionDate,\r\n            nd.notetakerid AS serviceproviderid,sp.firstname,sp.middlename,sp.lastname,sp.student_no,\r\n            sp.altid,sp.email,nd.binarydata,\r\n            nd.notes,nd.lecturedate,nd.lucourseid,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.course,\r\n            luc.section,luc.timeofday,lucd2.altlookupstring AS pinstructorname,luc.instructorid AS pinstructorid,\r\n            lucd2.email AS pinstructoremail,lucd2.phone AS pinstructorphone,lucd2.externalid AS pinstructorexternalid,\r\n            lucd2.id AS pinstructoremployeeid,\r\n            luc.subjectid\r\nFROM        notetakerdocument nd LEFT JOIN serviceproviders sp ON sp.serviceproviderid=nd.notetakerid\r\n            LEFT JOIN lucourses luc ON luc.lucourseid=nd.lucourseid\r\n            LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n            LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=luc.instructorid\r\nWHERE       nd.notetakerdocumentid=@id";

		// Token: 0x0400018F RID: 399
		internal const string QU_CANCEL_NOTETAKER_ASSIGNMENT = "SELECT    ServiceProviderRequestID,personid,lucourseid,datetimerequesttitle,startdatetimerequest,enddatetimerequest,serviceprovidertype,\r\n            dateentered,startdate,enddate,whoentered,ServiceProviderId,ServiceProviderRequestDetailId,notes,studentrequested,\r\n            studentrequestedcancelnote,DateAssigned,SpecialInstructions,partsgroupid,partsdescription,serviceproviderlucourseid,\r\n            CAST(0 AS bit) AS stillactive \r\nINTO #t1\r\nFROM        serviceproviderrequests \r\nWHERE       isactive=1 AND personid=@pid AND lucourseid=@lucid AND serviceprovidertype=128\r\n\r\nINSERT INTO serviceproviderrequestshistory \r\n    (ServiceProviderRequestID,personid,lucourseid,datetimerequesttitle,startdatetimerequest,enddatetimerequest,serviceprovidertype,\r\n    dateentered,startdate,enddate,whoentered,ServiceProviderId,ServiceProviderRequestDetailId,notes,studentrequested,studentrequestedcancelnote,\r\n    DateAssigned,SpecialInstructions,partsgroupid,partsdescription,serviceproviderlucourseid,stillactive) \r\n    SELECT  * FROM #t1\r\n\r\nUPDATE      serviceproviderrequests SET dateassigned=NULL,serviceproviderid=NULL,studentrequested=0,studentrequestedcancelnote=@note,\r\n            serviceproviderlucourseid=NULL WHERE isactive=1 AND personid=@pid AND lucourseid=@lucid AND serviceprovidertype=128\r\n\r\nSELECT  DISTINCT #t1.ServiceProviderId,sp.email,sp.firstname,sp.middlename,sp.lastname,sp.student_no,sp.altid,\r\n        #t1.serviceproviderlucourseid AS lucourseid,luc.startdate,luc.enddate,luc.duration,luc.term,luc.subjectid,lucd.altlookupstring AS subject,\r\n        luc.course,luc.[section],luc.timeofday,luc.campus,luc.department,luc.location,luc.coursenote\r\nFROM    #t1 LEFT JOIN ServiceProviders sp ON sp.ServiceProviderId=#t1.ServiceProviderId\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=#t1.serviceproviderlucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n\r\nDROP TABLE #t1";

		// Token: 0x04000190 RID: 400
		internal const string QU_ASSIGN_NOTETAKER = "UPDATE serviceproviderrequests SET serviceproviderid=@spid,dateassigned=getdate(),serviceproviderlucourseid=@splucid WHERE isactive=1 AND personid=@pid AND lucourseid=@lucid AND serviceprovidertype=128\r\n\r\n--load all students getting notes from this notetaker and course now\r\nSELECT\tDISTINCT r.personid\r\nFROM\tServiceProviderRequests r \r\nWHERE\tr.IsActive=1 AND r.serviceprovidertype=128\r\n\t\tAND NOT r.ServiceProviderId IS NULL AND r.ServiceProviderId=@spid \r\n\t\tAND r.serviceproviderlucourseid=@splucid";

		// Token: 0x04000191 RID: 401
		internal const string QU_LECTURE_NOTE = "UPDATE notetakerdocument \r\nSET docname=@docname,sizeinbytes=@sizeinbytes,binarydata=@binarydata,notes=@comment,lecturedate=@lecturedate\r\nWHERE notetakerdocumentid=@notetakerdocumentid";

		// Token: 0x04000192 RID: 402
		internal const string QU_COURSE_REGISTRATION_STATUS = "UPDATE ServiceProviderApplicationCourses SET registrationstatus=@registrationstatus WHERE ServiceProviderApplicationCourseId=@ServiceProviderApplicationCourseId";

		// Token: 0x04000193 RID: 403
		internal const string QI_LECTURE_NOTE = "INSERT INTO notetakerdocument (docname,numpages,sizeinbytes,datecreated,binarydata,notetakerid,lucourseid,notes,lecturedate,issamplenotes) \r\nVALUES (@docname,0,@sizeinbytes,getdate(),@binarydata,@spid,@lucid,@comment,@lecturedate,0);\r\n\r\nSET @notetakerdocumentid=(SELECT CAST(SCOPE_IDENTITY() AS int) AS notetakerdocumentid)";

		// Token: 0x04000194 RID: 404
		internal const string QI_RECORD_STUDENT_DOWNLOADED_LECTURE_NOTE = "DECLARE @lucid int\r\nSET @lucid=(SELECT TOP 1 lucourseid FROM notetakerdocument WHERE notetakerdocumentid=@docid)\r\nINSERT INTO NotetakerDocumentStudentDownloads (personid,lucourseid,notetakerdocumentid) VALUES (@pid,@lucid,@docid)";

		// Token: 0x04000195 RID: 405
		internal const string QI_COURSE_REGISTRATION = "IF EXISTS(SELECT ServiceProviderApplicationCourseId FROM ServiceProviderApplicationCourses WHERE lucourseid=@lucid AND ServiceProviderApplicationId IN (SELECT ServiceProviderApplicationId FROM ServiceProviderApplications WHERE ServiceProviderId=@serviceproviderid))\r\nBEGIN\r\n    UPDATE ServiceProviderApplicationCourses SET registrationstatus=NULL,exemptfromdatasync=COALESCE(@isexempt,exemptfromdatasync) WHERE lucourseid=@lucid AND ServiceProviderApplicationId IN (SELECT ServiceProviderApplicationId FROM ServiceProviderApplications WHERE ServiceProviderId=@serviceproviderid)\r\n    SELECT ServiceProviderApplicationCourseId FROM ServiceProviderApplicationCourse WHERE lucourseid=@lucid AND ServiceProviderApplicationId IN (SELECT ServiceProviderApplicationId FROM ServiceProviderApplications WHERE ServiceProviderId=@serviceproviderid))\r\nEND\r\nELSE\r\nBEGIN\r\nTODO!!!\r\n    INSERT INTO ServiceProviderApplicationCourses (personid,lucourseid,whoadded,dateadded,exemptfromdatasync) VALUES (@pid,@lucid,@whoami,getdate(),COALESCE(@isexempt,0));\r\n    SELECT CAST(SCOPE_IDENTITY() AS int) AS coursesid\r\nEND";

		// Token: 0x04000196 RID: 406
		internal const string QI_CreateOrRetrieveServiceProviderApplicationIdForCourses = "IF EXISTS(SELECT serviceproviderid FROM serviceproviderapplications WHERE serviceproviderid=@spid AND serviceprovidertype=@sptype)\r\n\tSELECT serviceproviderapplicationid FROM serviceproviderapplications WHERE serviceproviderid=@spid AND serviceprovidertype=@sptype\r\n\tELSE \r\n\tBEGIN\r\nINSERT INTO serviceproviderapplications (serviceproviderid,serviceprovidertype,note1,note2,dateentered,whoentered,ispermanent,isactive,isactivecomment) \r\nSELECT @spid,@sptype,'','',getdate(),1,NULL,1,NULL  \r\nSELECT serviceproviderapplicationid FROM serviceproviderapplications WHERE serviceproviderapplicationid=@@identity\r\nEND";

		// Token: 0x04000197 RID: 407
		internal const string QI_AddServiceProviderApplicationCourse = "IF EXISTS(SELECT serviceproviderapplicationcourseid FROM serviceproviderapplicationcourses WHERE serviceproviderapplicationid=@spa AND serviceprovidertype=@sptype AND lucourseid=@lucid)\r\nBEGIN\r\n    SELECT serviceproviderapplicationcourseid FROM serviceproviderapplicationcourses WHERE serviceproviderapplicationid=@spa AND serviceprovidertype=@sptype AND lucourseid=@lucid\r\nEND\r\nELSE\r\nBEGIN\r\n    INSERT INTO serviceproviderapplicationcourses \r\n            (serviceproviderapplicationid,serviceprovidertype,lucourseid,datecancelled) \r\n    VALUES  (@spa,@sptype,@lucid,NULL);\r\n    SELECT CAST(SCOPE_IDENTITY() AS int) AS serviceproviderapplicationcourseid\r\nEND";

		// Token: 0x04000198 RID: 408
		internal const string QI_NOTETAKER = "IF NOT EXISTS(SELECT serviceproviderid FROM ServiceProviders WHERE (NOT @altid IS NULL AND altid=@altid) OR (NOT @student_no IS NULL AND student_no=@student_no))\r\nBEGIN\r\n    INSERT INTO ServiceProviders (firstname,middlename,lastname,student_no,altid,specialization,notes1,notes2,email,phone1,phone2,phonenote,address,address2,email2,addressactive,address2active)\r\n    VALUES (@firstname,@middlename,@lastname,@student_no,@altid,@specialization,@notes1,@notes2,@email,@phone1,@phone2,@phonenote,@address,@address2,@email2,@addressactive,@address2active);\r\n    SET @serviceproviderid=(SELECT TOP 1 CAST(SCOPE_IDENTITY() AS int))\r\nEND\r\nELSE \r\n    SET @serviceproviderid=0";

		// Token: 0x04000199 RID: 409
		internal const string QD_LECTURE_NOTE = "DELETE FROM notetakerdocument WHERE notetakerdocumentid=@notetakerdocumentid";
	}
}
