using System;

namespace TechnoPro.Common.DAO.Impl.Surveys
{
	// Token: 0x0200003D RID: 61
	public class QueryStorageSurveys
	{
		// Token: 0x040000AF RID: 175
		internal const string QS_ALL_SURVEYS = "SELECT s.surveyid,s.title AS surveytitle,s.[description] AS surveydescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.[description],sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    survey s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.isdeleted=0\r\nORDER BY s.title";

		// Token: 0x040000B0 RID: 176
		internal const string QS_ACTIVE_SURVEYS = "SELECT s.surveyid,s.title AS surveytitle,s.[description] AS surveydescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.description,sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    survey s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.isdeleted=0 AND s.isdisabled=0 \r\n        AND \r\n        (\r\n            (s.startdate is NULL AND s.enddate IS NULL )\r\n\t\t\tOR\r\n            (NOT s.startdate IS NULL AND NOT s.enddate IS NULL AND getdate() BETWEEN s.startdate AND s.enddate)\r\n            OR\r\n            (NOT s.startdate IS NULL AND s.enddate IS NULL AND getdate() >= s.startdate)\r\n            OR\r\n            (s.startdate IS NULL AND NOT s.enddate IS NULL AND getdate() <= s.enddate)\r\n        )\r\nORDER BY s.title";

		// Token: 0x040000B1 RID: 177
		internal const string QS_SURVEY_BY_ID = "SELECT s.surveyid,s.title AS surveytitle,s.[description] AS surveydescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.description,sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    survey s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.surveyid=@surveyid";

		// Token: 0x040000B2 RID: 178
		internal const string QU_SURVEY_DISABLED_STATUS = "UPDATE survey SET isdisabled=@newdisabled WHERE surveyid=@id";

		// Token: 0x040000B3 RID: 179
		internal const string QU_UPDATE_SURVEY = "UPDATE survey SET title=@title,description=@description,formnum=@formnum,usewizard=@usewizard\r\n        ,submitmessage=@submitmessage,submitbuttontext=@submitbuttontext,shortcode=@shortcode\r\n        ,startdate=@startdate,enddate=@enddate,requireslogin=@requireslogin,canonlybefilledinonce=@canonlybefilledinonce\r\n        ,captcha=@captcha,studentemailconfirmationtemplateid=@studentemailconfirmationtemplateid,staffemailconfirmationtemplateid=@staffemailconfirmationtemplateid\r\n        ,restricttogroupid=@restricttogroupid,isdeleted=@isdeleted,isdisabled=@isdisabled\r\n        ,wholastmodified=@wholastmodified,datelastmodified=getdate()\r\nWHERE   surveyid=@surveyid";

		// Token: 0x040000B4 RID: 180
		internal const string QI_CREATE_SURVEY = "INSERT INTO survey (title,description,formnum,usewizard,submitmessage,submitbuttontext\r\n        ,shortcode,startdate,enddate,requireslogin,canonlybefilledinonce,captcha,studentemailconfirmationtemplateid,staffemailconfirmationtemplateid\r\n        ,restricttogroupid,isdeleted,isdisabled,whocreated)\r\nVALUES (@title,@description,@formnum,@usewizard,@submitmessage,@submitbuttontext\r\n        ,@shortcode,@startdate,@enddate,@requireslogin,@canonlybefilledinonce,@captcha,@studentemailconfirmationtemplateid,@staffemailconfirmationtemplateid\r\n        ,@restricttogroupid,@isdeleted,@isdisabled,@whocreated);\r\nSELECT CAST(SCOPE_IDENTITY() AS int) AS surveyid";

		// Token: 0x040000B5 RID: 181
		internal const string QD_SURVEY = "UPDATE Survey SET isdeleted=1 WHERE surveyid=@id";
	}
}
