using System;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Design;
using System.Drawing;
using System.Web.UI.Design.Util;
using System.Web.UI.WebControls;
using System.Windows.Forms;
using System.Windows.Forms.Design;

namespace System.Web.UI.Design.WebControls
{
	// Token: 0x0200012C RID: 300
	internal partial class TreeViewBindingsEditorForm : DesignerForm
	{
		// Token: 0x06000AC1 RID: 2753 RVA: 0x000444F0 File Offset: 0x000426F0
		public TreeViewBindingsEditorForm(IServiceProvider serviceProvider, System.Web.UI.WebControls.TreeView treeView, TreeViewDesigner treeViewDesigner) : base(serviceProvider)
		{
			this._treeView = treeView;
			this._autoBindInitialized = false;
			this.InitializeComponent();
			this.InitializeUI();
			foreach (object obj in this._treeView.DataBindings)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)((ICloneable)treeNodeBinding).Clone();
				treeViewDesigner.RegisterClone(treeNodeBinding, treeNodeBinding2);
				this._bindingsListView.Items.Add(treeNodeBinding2);
			}
		}

		// Token: 0x17000269 RID: 617
		// (get) Token: 0x06000AC2 RID: 2754 RVA: 0x00044590 File Offset: 0x00042790
		private IDataSourceSchema Schema
		{
			get
			{
				if (this._schema == null)
				{
					IDesignerHost designerHost = (IDesignerHost)base.ServiceProvider.GetService(typeof(IDesignerHost));
					if (designerHost != null)
					{
						HierarchicalDataBoundControlDesigner hierarchicalDataBoundControlDesigner = designerHost.GetDesigner(this._treeView) as HierarchicalDataBoundControlDesigner;
						if (hierarchicalDataBoundControlDesigner != null)
						{
							DesignerHierarchicalDataSourceView designerView = hierarchicalDataBoundControlDesigner.DesignerView;
							if (designerView != null)
							{
								try
								{
									this._schema = designerView.Schema;
								}
								catch (Exception ex)
								{
									IComponentDesignerDebugService componentDesignerDebugService = (IComponentDesignerDebugService)base.ServiceProvider.GetService(typeof(IComponentDesignerDebugService));
									if (componentDesignerDebugService != null)
									{
										componentDesignerDebugService.Fail(SR.GetString("DataSource_DebugService_FailedCall", new object[]
										{
											"DesignerHierarchicalDataSourceView.Schema",
											ex.Message
										}));
									}
								}
							}
						}
					}
				}
				return this._schema;
			}
		}

		// Token: 0x06000AC3 RID: 2755 RVA: 0x00044654 File Offset: 0x00042854
		private void AddBinding()
		{
			System.Windows.Forms.TreeNode selectedNode = this._schemaTreeView.SelectedNode;
			if (selectedNode != null)
			{
				TreeNodeBinding treeNodeBinding = new TreeNodeBinding();
				if (selectedNode.Text != this._schemaTreeView.Nodes[0].Text)
				{
					treeNodeBinding.DataMember = selectedNode.Text;
					if (((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Duplicate)
					{
						treeNodeBinding.Depth = selectedNode.FullPath.Split(new char[]
						{
							this._schemaTreeView.PathSeparator[0]
						}).Length - 1;
					}
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = ((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Schema;
					int num = this._bindingsListView.Items.IndexOf(treeNodeBinding);
					if (num == -1)
					{
						this._bindingsListView.Items.Add(treeNodeBinding);
						this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
					}
					else
					{
						treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[num];
						this._bindingsListView.SetSelected(num, true);
					}
				}
				else
				{
					this._bindingsListView.Items.Add(treeNodeBinding);
					this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				this.UpdateEnabledStates();
			}
			this._bindingsListView.Focus();
		}

		// Token: 0x06000AC4 RID: 2756 RVA: 0x000447BF File Offset: 0x000429BF
		private void ApplyBindings()
		{
			ControlDesigner.InvokeTransactedChange(this._treeView, new TransactedChangeCallback(this.ApplyBindingsChangeCallback), null, SR.GetString("TreeViewDesigner_EditBindingsTransactionDescription"));
		}

		// Token: 0x06000AC5 RID: 2757 RVA: 0x000447E4 File Offset: 0x000429E4
		private bool ApplyBindingsChangeCallback(object context)
		{
			this._treeView.DataBindings.Clear();
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding binding = (TreeNodeBinding)obj;
				this._treeView.DataBindings.Add(binding);
			}
			PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(this._treeView)["AutoGenerateDataBindings"];
			propertyDescriptor.SetValue(this._treeView, this._autogenerateBindingsCheckBox.Checked);
			return true;
		}

		// Token: 0x06000AC7 RID: 2759 RVA: 0x000448AF File Offset: 0x00042AAF
		private IDataSourceViewSchema FindViewSchema(string viewName, int level)
		{
			return TreeViewBindingsEditorForm.FindViewSchemaRecursive(this.Schema, 0, viewName, level, null);
		}

		// Token: 0x06000AC8 RID: 2760 RVA: 0x000448C0 File Offset: 0x00042AC0
		internal static IDataSourceViewSchema FindViewSchemaRecursive(object schema, int depth, string viewName, int level, IDataSourceViewSchema bestBet)
		{
			if (schema is IDataSourceSchema || schema is IDataSourceViewSchema)
			{
				IDataSourceViewSchema dataSourceViewSchema = schema as IDataSourceViewSchema;
				IDataSourceViewSchema[] array = (dataSourceViewSchema != null) ? dataSourceViewSchema.GetChildren() : ((IDataSourceSchema)schema).GetViews();
				if (array != null)
				{
					if (depth == level)
					{
						foreach (IDataSourceViewSchema dataSourceViewSchema2 in array)
						{
							if (string.Equals(dataSourceViewSchema2.Name, viewName, StringComparison.OrdinalIgnoreCase))
							{
								return dataSourceViewSchema2;
							}
							if (string.IsNullOrEmpty(dataSourceViewSchema2.Name) && bestBet == null)
							{
								bestBet = dataSourceViewSchema2;
							}
							bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema2, depth + 1, viewName, level, bestBet);
						}
					}
					else
					{
						foreach (IDataSourceViewSchema dataSourceViewSchema3 in array)
						{
							if (level == -1 && string.Equals(dataSourceViewSchema3.Name, viewName, StringComparison.OrdinalIgnoreCase) && bestBet == null)
							{
								return dataSourceViewSchema3;
							}
							bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema3, depth + 1, viewName, level, bestBet);
						}
					}
				}
				return bestBet;
			}
			return null;
		}

		// Token: 0x1700026A RID: 618
		// (get) Token: 0x06000AC9 RID: 2761 RVA: 0x000449A4 File Offset: 0x00042BA4
		protected override string HelpTopic
		{
			get
			{
				return "net.Asp.TreeView.BindingsEditorForm";
			}
		}

		// Token: 0x06000ACB RID: 2763 RVA: 0x00045224 File Offset: 0x00043424
		private void InitializeUI()
		{
			this._bindingsLabel.Text = SR.GetString("TreeViewBindingsEditor_Bindings");
			this._schemaLabel.Text = SR.GetString("TreeViewBindingsEditor_Schema");
			this._okButton.Text = SR.GetString("TreeViewBindingsEditor_OK");
			this._applyButton.Text = SR.GetString("TreeViewBindingsEditor_Apply");
			this._cancelButton.Text = SR.GetString("TreeViewBindingsEditor_Cancel");
			this._propertiesLabel.Text = SR.GetString("TreeViewBindingsEditor_BindingProperties");
			this._autogenerateBindingsCheckBox.Text = SR.GetString("TreeViewBindingsEditor_AutoGenerateBindings");
			this._addBindingButton.Text = SR.GetString("TreeViewBindingsEditor_AddBinding");
			this.Text = SR.GetString("TreeViewBindingsEditor_Title");
			Bitmap bitmap = BitmapSelector.CreateIcon(typeof(TreeViewBindingsEditor), "SortUp.ico").ToBitmap();
			bitmap.MakeTransparent();
			this._moveBindingUpButton.Image = bitmap;
			this._moveBindingUpButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingUpName");
			this._moveBindingUpButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingUpDescription");
			Bitmap bitmap2 = BitmapSelector.CreateIcon(typeof(TreeViewBindingsEditor), "SortDown.ico").ToBitmap();
			bitmap2.MakeTransparent();
			this._moveBindingDownButton.Image = bitmap2;
			this._moveBindingDownButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingDownName");
			this._moveBindingDownButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingDownDescription");
			Bitmap bitmap3 = BitmapSelector.CreateIcon(typeof(TreeViewBindingsEditor), "Delete.ico").ToBitmap();
			bitmap3.MakeTransparent();
			this._deleteBindingButton.Image = bitmap3;
			this._deleteBindingButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_DeleteBindingName");
			this._deleteBindingButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_DeleteBindingDescription");
			base.Icon = null;
		}

		// Token: 0x06000ACC RID: 2764 RVA: 0x000453F2 File Offset: 0x000435F2
		private void OnApplyButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			this._applyButton.Enabled = false;
		}

		// Token: 0x06000ACD RID: 2765 RVA: 0x00045406 File Offset: 0x00043606
		private void OnAddBindingButtonClick(object sender, EventArgs e)
		{
			this._applyButton.Enabled = true;
			this.AddBinding();
		}

		// Token: 0x06000ACE RID: 2766 RVA: 0x0004541A File Offset: 0x0004361A
		private void OnAutoGenerateChanged(object sender, EventArgs e)
		{
			if (this._autoBindInitialized)
			{
				this._applyButton.Enabled = true;
			}
		}

		// Token: 0x06000ACF RID: 2767 RVA: 0x00045430 File Offset: 0x00043630
		private void OnBindingsListViewGotFocus(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		// Token: 0x06000AD0 RID: 2768 RVA: 0x00045430 File Offset: 0x00043630
		private void OnBindingsListViewSelectedIndexChanged(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		// Token: 0x06000AD1 RID: 2769 RVA: 0x0002AF61 File Offset: 0x00029161
		private void OnCancelButtonClick(object sender, EventArgs e)
		{
			base.DialogResult = DialogResult.Cancel;
			base.Close();
		}

		// Token: 0x06000AD2 RID: 2770 RVA: 0x00045438 File Offset: 0x00043638
		private void OnDeleteBindingButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				this._bindingsListView.Items.RemoveAt(num);
				if (num >= this._bindingsListView.Items.Count)
				{
					num--;
				}
				if (num >= 0 && this._bindingsListView.Items.Count > 0)
				{
					this._bindingsListView.SetSelected(num, true);
				}
			}
		}

		// Token: 0x06000AD3 RID: 2771 RVA: 0x000454C4 File Offset: 0x000436C4
		protected override void OnInitialActivated(EventArgs e)
		{
			base.OnInitialActivated(e);
			System.Windows.Forms.TreeNode selectedNode = this._schemaTreeView.Nodes.Add(SR.GetString("TreeViewBindingsEditor_EmptyBindingText"));
			if (this.Schema != null)
			{
				this.PopulateSchema(this.Schema);
				this._schemaTreeView.ExpandAll();
			}
			this._schemaTreeView.SelectedNode = selectedNode;
			this._autoBindInitialized = false;
			this._autogenerateBindingsCheckBox.Checked = this._treeView.AutoGenerateDataBindings;
			this._autoBindInitialized = true;
			this.UpdateEnabledStates();
		}

		// Token: 0x06000AD4 RID: 2772 RVA: 0x00045548 File Offset: 0x00043748
		private void OnMoveBindingUpButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num > 0)
				{
					TreeNodeBinding item = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num - 1, item);
					this._bindingsListView.SetSelected(num - 1, true);
				}
			}
		}

		// Token: 0x06000AD5 RID: 2773 RVA: 0x000455D8 File Offset: 0x000437D8
		private void OnMoveBindingDownButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num + 1 < this._bindingsListView.Items.Count)
				{
					TreeNodeBinding item = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num + 1, item);
					this._bindingsListView.SetSelected(num + 1, true);
				}
			}
		}

		// Token: 0x06000AD6 RID: 2774 RVA: 0x00045676 File Offset: 0x00043876
		private void OnOKButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			base.DialogResult = DialogResult.OK;
			base.Close();
		}

		// Token: 0x06000AD7 RID: 2775 RVA: 0x0004568C File Offset: 0x0004388C
		private void OnPropertyGridPropertyValueChanged(object s, PropertyValueChangedEventArgs e)
		{
			this._applyButton.Enabled = true;
			if (e.ChangedItem.PropertyDescriptor.Name == "DataMember")
			{
				string viewName = (string)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				this._bindingsListView.Items[this._bindingsListView.SelectedIndex] = treeNodeBinding;
				this._bindingsListView.Refresh();
				IDataSourceViewSchema dataSourceViewSchema = this.FindViewSchema(viewName, treeNodeBinding.Depth);
				if (dataSourceViewSchema != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = dataSourceViewSchema;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				return;
			}
			if (e.ChangedItem.PropertyDescriptor.Name == "Depth")
			{
				int level = (int)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				IDataSourceViewSchema dataSourceViewSchema2 = this.FindViewSchema(treeNodeBinding2.DataMember, level);
				if (dataSourceViewSchema2 != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding2).DataSourceViewSchema = dataSourceViewSchema2;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding2;
				this._propertyGrid.Refresh();
			}
		}

		// Token: 0x06000AD8 RID: 2776 RVA: 0x000457D1 File Offset: 0x000439D1
		private void OnSchemaTreeViewAfterSelect(object sender, TreeViewEventArgs e)
		{
			this.UpdateEnabledStates();
		}

		// Token: 0x06000AD9 RID: 2777 RVA: 0x000457D9 File Offset: 0x000439D9
		private void OnSchemaTreeViewGotFocus(object sender, EventArgs e)
		{
			this._propertyGrid.SelectedObject = null;
		}

		// Token: 0x06000ADA RID: 2778 RVA: 0x000457E8 File Offset: 0x000439E8
		private void PopulateSchema(IDataSourceSchema schema)
		{
			if (schema == null)
			{
				return;
			}
			IDictionary duplicates = new Hashtable();
			IDataSourceViewSchema[] views = schema.GetViews();
			if (views != null)
			{
				for (int i = 0; i < views.Length; i++)
				{
					this.PopulateSchemaRecursive(this._schemaTreeView.Nodes, views[i], 0, duplicates);
				}
			}
		}

		// Token: 0x06000ADB RID: 2779 RVA: 0x00045830 File Offset: 0x00043A30
		private void PopulateSchemaRecursive(System.Windows.Forms.TreeNodeCollection nodes, IDataSourceViewSchema viewSchema, int depth, IDictionary duplicates)
		{
			if (viewSchema == null)
			{
				return;
			}
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode = new TreeViewBindingsEditorForm.SchemaTreeNode(viewSchema);
			nodes.Add(schemaTreeNode);
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode2 = (TreeViewBindingsEditorForm.SchemaTreeNode)duplicates[viewSchema.Name];
			if (schemaTreeNode2 != null)
			{
				schemaTreeNode2.Duplicate = true;
				schemaTreeNode.Duplicate = true;
			}
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				if (string.Compare(treeNodeBinding.DataMember, viewSchema.Name, StringComparison.OrdinalIgnoreCase) == 0)
				{
					IDataSourceViewSchemaAccessor dataSourceViewSchemaAccessor = treeNodeBinding;
					if (depth == treeNodeBinding.Depth || dataSourceViewSchemaAccessor.DataSourceViewSchema == null)
					{
						dataSourceViewSchemaAccessor.DataSourceViewSchema = viewSchema;
					}
				}
			}
			IDataSourceViewSchema[] children = viewSchema.GetChildren();
			if (children != null)
			{
				for (int i = 0; i < children.Length; i++)
				{
					this.PopulateSchemaRecursive(schemaTreeNode.Nodes, children[i], depth + 1, duplicates);
				}
			}
		}

		// Token: 0x06000ADC RID: 2780 RVA: 0x00045928 File Offset: 0x00043B28
		private void UpdateEnabledStates()
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				int num = this._bindingsListView.SelectedIndices[0];
				this._moveBindingDownButton.Enabled = (num + 1 < this._bindingsListView.Items.Count);
				this._moveBindingUpButton.Enabled = (num > 0);
				this._deleteBindingButton.Enabled = true;
			}
			else
			{
				this._moveBindingDownButton.Enabled = false;
				this._moveBindingUpButton.Enabled = false;
				this._deleteBindingButton.Enabled = false;
			}
			this._addBindingButton.Enabled = (this._schemaTreeView.SelectedNode != null);
		}

		// Token: 0x06000ADD RID: 2781 RVA: 0x000459D4 File Offset: 0x00043BD4
		private void UpdateSelectedBinding()
		{
			TreeNodeBinding selectedObject = null;
			if (this._bindingsListView.SelectedItems.Count > 0)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.SelectedItems[0];
				selectedObject = treeNodeBinding;
			}
			this._propertyGrid.SelectedObject = selectedObject;
			this._propertyGrid.Refresh();
			this.UpdateEnabledStates();
		}

		// Token: 0x0400067E RID: 1662
		private IDataSourceSchema _schema;

		// Token: 0x0200044E RID: 1102
		private class SchemaTreeNode : System.Windows.Forms.TreeNode
		{
			// Token: 0x0600292E RID: 10542 RVA: 0x000F9CA9 File Offset: 0x000F7EA9
			public SchemaTreeNode(IDataSourceViewSchema schema) : base(schema.Name)
			{
				this._schema = schema;
			}

			// Token: 0x170008B3 RID: 2227
			// (get) Token: 0x0600292F RID: 10543 RVA: 0x000F9CBE File Offset: 0x000F7EBE
			// (set) Token: 0x06002930 RID: 10544 RVA: 0x000F9CC6 File Offset: 0x000F7EC6
			public bool Duplicate
			{
				get
				{
					return this._duplicate;
				}
				set
				{
					this._duplicate = value;
				}
			}

			// Token: 0x170008B4 RID: 2228
			// (get) Token: 0x06002931 RID: 10545 RVA: 0x000F9CCF File Offset: 0x000F7ECF
			public object Schema
			{
				get
				{
					return this._schema;
				}
			}

			// Token: 0x04001D25 RID: 7461
			private IDataSourceViewSchema _schema;

			// Token: 0x04001D26 RID: 7462
			private bool _duplicate;
		}
	}
}
