using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000047 RID: 71
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000147 RID: 327
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
