using System;

namespace Telerik.Web.UI
{
	// Token: 0x020010CC RID: 4300
	public enum GridEditFormType
	{
		// Token: 0x04002E43 RID: 11843
		AutoGenerated,
		// Token: 0x04002E44 RID: 11844
		WebUserControl,
		// Token: 0x04002E45 RID: 11845
		Template
	}
}
