using System;
using System.Collections;
using System.Data;

namespace Telerik.Web.UI
{
	// Token: 0x020010F2 RID: 4338
	internal abstract class GridEnumerableBase
	{
		// Token: 0x17003983 RID: 14723
		// (get) Token: 0x0600B1AE RID: 45486 RVA: 0x00269A32 File Offset: 0x00267C32
		public virtual bool SupportsPaging
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17003984 RID: 14724
		// (get) Token: 0x0600B1AF RID: 45487 RVA: 0x00269A35 File Offset: 0x00267C35
		public virtual bool SupportsSorting
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17003985 RID: 14725
		// (get) Token: 0x0600B1B0 RID: 45488 RVA: 0x00269A38 File Offset: 0x00267C38
		public virtual bool SupportsGrouping
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17003986 RID: 14726
		// (get) Token: 0x0600B1B1 RID: 45489 RVA: 0x00269A3B File Offset: 0x00267C3B
		public virtual bool SupportsFiltering
		{
			get
			{
				return false;
			}
		}

		// Token: 0x17003987 RID: 14727
		// (get) Token: 0x0600B1B2 RID: 45490 RVA: 0x00269A3E File Offset: 0x00267C3E
		// (set) Token: 0x0600B1B3 RID: 45491 RVA: 0x00269A46 File Offset: 0x00267C46
		internal bool GroupingEnabled
		{
			get
			{
				return this._groupingEnabled;
			}
			set
			{
				this._groupingEnabled = value;
			}
		}

		// Token: 0x17003988 RID: 14728
		// (get) Token: 0x0600B1B4 RID: 45492 RVA: 0x00269A4F File Offset: 0x00267C4F
		// (set) Token: 0x0600B1B5 RID: 45493 RVA: 0x00269A57 File Offset: 0x00267C57
		public virtual GridResetPageIndexAction CurrentResetPageIndexAction
		{
			get
			{
				return this._resetPageIndexAction;
			}
			set
			{
				this._resetPageIndexAction = value;
			}
		}

		// Token: 0x0600B1B6 RID: 45494 RVA: 0x00269A60 File Offset: 0x00267C60
		public virtual void SetSortExpressions(GridSortExpressionCollection expressions)
		{
			throw new InvalidOperationException();
		}

		// Token: 0x0600B1B7 RID: 45495 RVA: 0x00269A67 File Offset: 0x00267C67
		public virtual void SetGroupByExpressions(GridGroupByExpressionCollection expressions)
		{
			throw new InvalidOperationException();
		}

		// Token: 0x17003989 RID: 14729
		// (get) Token: 0x0600B1B8 RID: 45496 RVA: 0x00269A6E File Offset: 0x00267C6E
		public virtual DataSet GroupingDataSet
		{
			get
			{
				throw new InvalidOperationException();
			}
		}

		// Token: 0x1700398A RID: 14730
		// (get) Token: 0x0600B1B9 RID: 45497 RVA: 0x00269A75 File Offset: 0x00267C75
		public virtual int Count
		{
			get
			{
				throw new InvalidOperationException();
			}
		}

		// Token: 0x0600B1BA RID: 45498
		public abstract void TransformEnumerable();

		// Token: 0x1700398B RID: 14731
		// (get) Token: 0x0600B1BB RID: 45499 RVA: 0x00269A7C File Offset: 0x00267C7C
		public virtual GridPagingManager Paging
		{
			get
			{
				if (this._paging == null)
				{
					this._paging = new GridPagingManager(this);
				}
				return this._paging;
			}
		}

		// Token: 0x0600B1BC RID: 45500 RVA: 0x00269A98 File Offset: 0x00267C98
		public virtual IEnumerable GetRowEnumerable()
		{
			throw new NotImplementedException();
		}

		// Token: 0x1700398C RID: 14732
		// (get) Token: 0x0600B1BD RID: 45501 RVA: 0x00269A9F File Offset: 0x00267C9F
		public virtual int DataSourceCount
		{
			get
			{
				throw new NotImplementedException();
			}
		}

		// Token: 0x1700398D RID: 14733
		// (get) Token: 0x0600B1BE RID: 45502 RVA: 0x00269AA6 File Offset: 0x00267CA6
		// (set) Token: 0x0600B1BF RID: 45503 RVA: 0x00269AAE File Offset: 0x00267CAE
		public bool IsDesignMode
		{
			get
			{
				return this._isDesignMode;
			}
			set
			{
				this._isDesignMode = value;
			}
		}

		// Token: 0x0600B1C0 RID: 45504 RVA: 0x00269AB7 File Offset: 0x00267CB7
		public virtual ArrayList GetColumns()
		{
			throw new GridNotSupportedException("Autogenerated columns not available");
		}

		// Token: 0x0600B1C1 RID: 45505 RVA: 0x00269AC3 File Offset: 0x00267CC3
		public virtual void AddHierarchyFilterExpression(string expression)
		{
			throw new InvalidOperationException();
		}

		// Token: 0x0600B1C2 RID: 45506 RVA: 0x00269ACA File Offset: 0x00267CCA
		public virtual void AddFilterExpression(string expression)
		{
			throw new InvalidOperationException();
		}

		// Token: 0x0600B1C3 RID: 45507 RVA: 0x00269AD1 File Offset: 0x00267CD1
		public virtual GridInsertionObject GetObjectForInsertion(IDictionary newValues)
		{
			throw new GridNotSupportedException("Object for insertion is not available");
		}

		// Token: 0x1700398E RID: 14734
		// (get) Token: 0x0600B1C4 RID: 45508 RVA: 0x00269ADD File Offset: 0x00267CDD
		public static GridEnumerableBase Null
		{
			get
			{
				return GridEnumerableBase._null;
			}
		}

		// Token: 0x1700398F RID: 14735
		// (get) Token: 0x0600B1C5 RID: 45509 RVA: 0x00269AE4 File Offset: 0x00267CE4
		public virtual bool IsReady
		{
			get
			{
				return false;
			}
		}

		// Token: 0x04002EA1 RID: 11937
		private GridPagingManager _paging;

		// Token: 0x04002EA2 RID: 11938
		private bool _groupingEnabled;

		// Token: 0x04002EA3 RID: 11939
		private bool _isDesignMode;

		// Token: 0x04002EA4 RID: 11940
		private GridResetPageIndexAction _resetPageIndexAction;

		// Token: 0x04002EA5 RID: 11941
		private static GridEnumerableBase.NullEnumerable _null = new GridEnumerableBase.NullEnumerable();

		// Token: 0x020010F3 RID: 4339
		private class NullEnumerable : GridEnumerableBase
		{
			// Token: 0x0600B1C8 RID: 45512 RVA: 0x00269AFB File Offset: 0x00267CFB
			public override void AddFilterExpression(string expression)
			{
				throw new NullEnumerableException();
			}

			// Token: 0x0600B1C9 RID: 45513 RVA: 0x00269B02 File Offset: 0x00267D02
			public override void AddHierarchyFilterExpression(string expression)
			{
				throw new NullEnumerableException();
			}

			// Token: 0x17003990 RID: 14736
			// (get) Token: 0x0600B1CA RID: 45514 RVA: 0x00269B09 File Offset: 0x00267D09
			public override int Count
			{
				get
				{
					throw new NullEnumerableException();
				}
			}

			// Token: 0x17003991 RID: 14737
			// (get) Token: 0x0600B1CB RID: 45515 RVA: 0x00269B10 File Offset: 0x00267D10
			public override int DataSourceCount
			{
				get
				{
					return 0;
				}
			}

			// Token: 0x17003992 RID: 14738
			// (get) Token: 0x0600B1CC RID: 45516 RVA: 0x00269B13 File Offset: 0x00267D13
			public override DataSet GroupingDataSet
			{
				get
				{
					throw new NullEnumerableException();
				}
			}

			// Token: 0x0600B1CD RID: 45517 RVA: 0x00269B1A File Offset: 0x00267D1A
			public override ArrayList GetColumns()
			{
				throw new NullEnumerableException();
			}

			// Token: 0x0600B1CE RID: 45518 RVA: 0x00269B21 File Offset: 0x00267D21
			public override IEnumerable GetRowEnumerable()
			{
				throw new NullEnumerableException();
			}

			// Token: 0x0600B1CF RID: 45519 RVA: 0x00269B28 File Offset: 0x00267D28
			public override void SetGroupByExpressions(GridGroupByExpressionCollection expressions)
			{
				throw new NullEnumerableException();
			}

			// Token: 0x0600B1D0 RID: 45520 RVA: 0x00269B2F File Offset: 0x00267D2F
			public override void SetSortExpressions(GridSortExpressionCollection expressions)
			{
				throw new NullEnumerableException();
			}

			// Token: 0x0600B1D1 RID: 45521 RVA: 0x00269B36 File Offset: 0x00267D36
			public override void TransformEnumerable()
			{
				throw new NullEnumerableException();
			}
		}
	}
}
