using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x020010B8 RID: 4280
	public class GridEditCommandColumn : GridColumn
	{
		// Token: 0x17003863 RID: 14435
		// (get) Token: 0x0600AE91 RID: 44689 RVA: 0x0025AFA4 File Offset: 0x002591A4
		public override bool Selectable
		{
			get
			{
				return false;
			}
		}

		// Token: 0x0600AE92 RID: 44690 RVA: 0x0025AFB8 File Offset: 0x002591B8
		[SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		public override void InitializeCell(TableCell cell, int columnIndex, GridItem inItem)
		{
			base.InitializeCell(cell, columnIndex, inItem);
			if (inItem.IsDataBound)
			{
				if (inItem.IsInEditMode)
				{
					ControlCollection controlCollection = (base.Owner.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight && cell.Controls.Count > 0) ? ((base.Owner.EditMode == GridEditMode.PopUp) ? cell.Controls[0].FindControl("EditFormContainer").Controls : cell.Controls[0].Controls) : cell.Controls;
					WebControl webControl;
					if (this.ButtonType == GridButtonColumnType.LinkButton)
					{
						LinkButton linkButton = new GridLinkButton();
						webControl = linkButton;
						linkButton.CommandName = ((inItem is IGridInsertItem) ? "PerformInsert" : "Update");
						linkButton.Text = ((inItem is IGridInsertItem) ? this.InsertText : this.UpdateText);
						if (base.Owner.OwnerGrid.EnableAriaSupport)
						{
							linkButton.Attributes.Add("title", linkButton.Text);
							linkButton.Attributes.Add("aria-role", "button");
						}
						this.SetValidationGroup(linkButton);
					}
					else if (this.ButtonType == GridButtonColumnType.PushButton)
					{
						Button button = new Button();
						webControl = button;
						button.CommandName = ((inItem is IGridInsertItem) ? "PerformInsert" : "Update");
						button.Text = ((inItem is IGridInsertItem) ? this.InsertText : this.UpdateText);
						this.SetValidationGroup(button);
					}
					else if (this.ButtonType == GridButtonColumnType.FontIconButton)
					{
						ElasticButton elasticButton = new ElasticButton
						{
							FirstSpanClass = "t-font-icon rgIcon rgUpdateIcon"
						};
						webControl = elasticButton;
						elasticButton.CssClass = "t-button rgActionButton rgUpdate";
						elasticButton.CommandName = ((inItem is IGridInsertItem) ? "PerformInsert" : "Update");
						elasticButton.UseSubmitBehavior = false;
						elasticButton.ToolTip = ((inItem is IGridInsertItem) ? this.InsertText : this.UpdateText);
						if (base.Owner.OwnerGrid.EnableAriaSupport)
						{
							elasticButton.Attributes.Add("aria-label", elasticButton.ToolTip);
						}
						elasticButton.Text = elasticButton.ToolTip;
						this.SetValidationGroup(elasticButton);
					}
					else
					{
						ImageButton imageButton = new ImageButton();
						webControl = imageButton;
						imageButton.CommandName = ((inItem is IGridInsertItem) ? "PerformInsert" : "Update");
						imageButton.AlternateText = ((inItem is IGridInsertItem) ? this.InsertText : this.UpdateText);
						imageButton.ToolTip = imageButton.AlternateText;
						imageButton.ImageUrl = ((inItem is IGridInsertItem) ? this.InsertImageUrl : this.UpdateImageUrl);
						imageButton.BorderWidth = Unit.Pixel(0);
						if (base.Owner.OwnerGrid.EnableAriaSupport)
						{
							imageButton.Attributes.Add("title", imageButton.AlternateText);
							imageButton.Attributes.Add("aria-role", "button");
						}
						this.SetValidationGroup(imageButton);
					}
					if (inItem is IGridInsertItem)
					{
						this.TrySetOnClientClickScript(webControl, inItem, "insertItem", new string[0]);
					}
					else
					{
						this.TrySetOnClientClickScript(webControl, inItem, "updateItem", new string[]
						{
							(inItem is GridEditFormItem) ? (inItem as GridEditFormItem).ParentItem.ItemIndexHierarchical : inItem.ItemIndexHierarchical
						});
					}
					if (this.UniqueName != "AutoGeneratedEditColumn")
					{
						webControl.ID = ((inItem is IGridInsertItem) ? "PerformInsertButton" : "UpdateButton");
					}
					else
					{
						webControl.ID = ((inItem is IGridInsertItem) ? "AutoGeneratedPerformInsertButton" : "AutoGeneratedUpdateButton");
					}
					controlCollection.Add(webControl);
					LiteralControl child = new LiteralControl("&nbsp;");
					controlCollection.Add(child);
					if (this.ButtonType == GridButtonColumnType.LinkButton)
					{
						LinkButton linkButton2 = new GridLinkButton();
						webControl = linkButton2;
						linkButton2.CommandName = "Cancel";
						linkButton2.Text = this.CancelText;
						linkButton2.CausesValidation = false;
					}
					else if (this.ButtonType == GridButtonColumnType.PushButton)
					{
						Button button2 = new Button();
						webControl = button2;
						button2.CommandName = "Cancel";
						button2.Text = this.CancelText;
						button2.CausesValidation = false;
					}
					else if (this.ButtonType == GridButtonColumnType.FontIconButton)
					{
						ElasticButton elasticButton2 = new ElasticButton
						{
							FirstSpanClass = "t-font-icon rgIcon rgCancelIcon"
						};
						webControl = elasticButton2;
						elasticButton2.CssClass = "t-button rgActionButton rgCancel";
						elasticButton2.CommandName = "Cancel";
						elasticButton2.UseSubmitBehavior = false;
						elasticButton2.ToolTip = this.CancelText;
						elasticButton2.Text = elasticButton2.ToolTip;
						if (base.Owner.OwnerGrid.EnableAriaSupport)
						{
							elasticButton2.Attributes.Add("aria-label", elasticButton2.ToolTip);
						}
						elasticButton2.CausesValidation = false;
					}
					else
					{
						ImageButton imageButton2 = new ImageButton();
						webControl = imageButton2;
						imageButton2.CommandName = "Cancel";
						imageButton2.AlternateText = this.CancelText;
						imageButton2.ToolTip = this.CancelText;
						imageButton2.CausesValidation = false;
						imageButton2.ImageUrl = this.CancelImageUrl;
						imageButton2.BorderWidth = Unit.Pixel(0);
					}
					if (inItem is IGridInsertItem)
					{
						this.TrySetOnClientClickScript(webControl, inItem, "cancelInsert", new string[0]);
					}
					else
					{
						this.TrySetOnClientClickScript(webControl, inItem, "cancelUpdate", new string[]
						{
							(inItem is GridEditFormItem) ? (inItem as GridEditFormItem).ParentItem.ItemIndexHierarchical : inItem.ItemIndexHierarchical
						});
					}
					if (this.UniqueName != "AutoGeneratedEditColumn")
					{
						webControl.ID = "CancelButton";
					}
					else
					{
						webControl.ID = "AutoGeneratedCancelButton";
					}
					controlCollection.Add(webControl);
					return;
				}
				ControlCollection controls = cell.Controls;
				WebControl webControl2;
				if (this.ButtonType == GridButtonColumnType.LinkButton)
				{
					LinkButton linkButton3 = new GridLinkButton();
					webControl2 = linkButton3;
					linkButton3.CommandName = "Edit";
					linkButton3.Text = this.EditText;
					linkButton3.CausesValidation = false;
				}
				else if (this.ButtonType == GridButtonColumnType.PushButton)
				{
					Button button3 = new Button();
					webControl2 = button3;
					button3.CommandName = "Edit";
					button3.Text = this.EditText;
					button3.CausesValidation = false;
				}
				else if (this.ButtonType == GridButtonColumnType.FontIconButton && base.Owner != null && (base.Owner.OwnerGrid.ResolvedRenderMode == RenderMode.Mobile || base.Owner.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight))
				{
					ElasticButton elasticButton3 = new ElasticButton
					{
						FirstSpanClass = "t-font-icon rgIcon rgEditIcon"
					};
					webControl2 = elasticButton3;
					elasticButton3.CssClass = "t-button rgActionButton rgEdit";
					elasticButton3.CommandName = "Edit";
					elasticButton3.UseSubmitBehavior = false;
					elasticButton3.Text = this.EditText;
					elasticButton3.ToolTip = this.EditText;
					if (base.Owner.OwnerGrid.EnableAriaSupport)
					{
						elasticButton3.Attributes.Add("aria-label", this.EditText);
					}
					elasticButton3.CausesValidation = false;
				}
				else
				{
					ImageButton imageButton3 = new ImageButton();
					webControl2 = imageButton3;
					imageButton3.CommandName = "Edit";
					imageButton3.AlternateText = this.EditText;
					imageButton3.ToolTip = this.EditText;
					imageButton3.CausesValidation = false;
					imageButton3.ImageUrl = this.EditImageUrl;
					imageButton3.PreRender += delegate(object sender, EventArgs e)
					{
						this.ConfigureButtonImage((ImageButton)sender);
					};
					imageButton3.BorderWidth = Unit.Pixel(0);
				}
				this.TrySetOnClientClickScript(webControl2, inItem, "editItem", new string[]
				{
					inItem.ItemIndexHierarchical
				});
				if (this.UniqueName != "AutoGeneratedEditColumn")
				{
					webControl2.ID = "EditButton";
				}
				else
				{
					webControl2.ID = "AutoGeneratedEditButton";
				}
				controls.Add(webControl2);
			}
		}

		// Token: 0x0600AE93 RID: 44691 RVA: 0x0025B755 File Offset: 0x00259955
		private void ConfigureButtonImage(ImageButton target)
		{
			if (!string.IsNullOrEmpty(this.EditImageUrl))
			{
				return;
			}
			if (string.IsNullOrEmpty(target.ImageUrl))
			{
				target.ImageUrl = base.Owner.OwnerGrid.ResolveGridImageUrl("Edit.gif", false);
			}
		}

		// Token: 0x0600AE94 RID: 44692 RVA: 0x0025B78E File Offset: 0x0025998E
		protected virtual void SetValidationGroup(IButtonControl button)
		{
			if (!string.IsNullOrEmpty(base.Owner.OwnerGrid.ValidationSettings.ValidationGroup))
			{
				button.ValidationGroup = base.Owner.OwnerGrid.ValidationSettings.ValidationGroup;
			}
		}

		// Token: 0x17003864 RID: 14436
		// (get) Token: 0x0600AE95 RID: 44693 RVA: 0x0025B7C8 File Offset: 0x002599C8
		// (set) Token: 0x0600AE96 RID: 44694 RVA: 0x0025B821 File Offset: 0x00259A21
		[NotifyParentProperty(true)]
		[DefaultValue(typeof(GridButtonColumnType), "LinkButton")]
		public virtual GridButtonColumnType ButtonType
		{
			get
			{
				object obj = base.ViewState["ButtonType"];
				if (obj != null)
				{
					return (GridButtonColumnType)obj;
				}
				if (base.Owner == null || (base.Owner.OwnerGrid.ResolvedRenderMode != RenderMode.Lightweight && base.Owner.OwnerGrid.ResolvedRenderMode != RenderMode.Mobile))
				{
					return GridButtonColumnType.LinkButton;
				}
				return GridButtonColumnType.FontIconButton;
			}
			set
			{
				if (value < GridButtonColumnType.LinkButton || value > GridButtonColumnType.FontIconButton)
				{
					throw new ArgumentOutOfRangeException("value");
				}
				base.ViewState["ButtonType"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x17003865 RID: 14437
		// (get) Token: 0x0600AE97 RID: 44695 RVA: 0x0025B854 File Offset: 0x00259A54
		// (set) Token: 0x0600AE98 RID: 44696 RVA: 0x0025B89F File Offset: 0x00259A9F
		[Localizable(true)]
		[DefaultValue("Cancel")]
		[NotifyParentProperty(true)]
		public virtual string CancelText
		{
			get
			{
				object obj = base.ViewState["CancelText"];
				if (obj != null)
				{
					return (string)obj;
				}
				if (base.Owner == null)
				{
					return "Cancel";
				}
				return base.Owner.OwnerGrid.Localization.CancelText;
			}
			set
			{
				base.ViewState["CancelText"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x17003866 RID: 14438
		// (get) Token: 0x0600AE99 RID: 44697 RVA: 0x0025B8B8 File Offset: 0x00259AB8
		// (set) Token: 0x0600AE9A RID: 44698 RVA: 0x0025B903 File Offset: 0x00259B03
		[DefaultValue("Edit")]
		[NotifyParentProperty(true)]
		[Localizable(true)]
		public virtual string EditText
		{
			get
			{
				object obj = base.ViewState["EditText"];
				if (obj != null)
				{
					return (string)obj;
				}
				if (base.Owner == null)
				{
					return "Edit";
				}
				return base.Owner.OwnerGrid.Localization.EditText;
			}
			set
			{
				base.ViewState["EditText"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x17003867 RID: 14439
		// (get) Token: 0x0600AE9B RID: 44699 RVA: 0x0025B91C File Offset: 0x00259B1C
		// (set) Token: 0x0600AE9C RID: 44700 RVA: 0x0025B967 File Offset: 0x00259B67
		[Localizable(true)]
		[NotifyParentProperty(true)]
		[DefaultValue("Update")]
		public virtual string UpdateText
		{
			get
			{
				object obj = base.ViewState["UpdateText"];
				if (obj != null)
				{
					return (string)obj;
				}
				if (base.Owner == null)
				{
					return "Update";
				}
				return base.Owner.OwnerGrid.Localization.UpdateText;
			}
			set
			{
				base.ViewState["UpdateText"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x17003868 RID: 14440
		// (get) Token: 0x0600AE9D RID: 44701 RVA: 0x0025B980 File Offset: 0x00259B80
		// (set) Token: 0x0600AE9E RID: 44702 RVA: 0x0025B9CB File Offset: 0x00259BCB
		[DefaultValue("Insert")]
		[Localizable(true)]
		[NotifyParentProperty(true)]
		public virtual string InsertText
		{
			get
			{
				object obj = base.ViewState["_it"];
				if (obj != null)
				{
					return (string)obj;
				}
				if (base.Owner == null)
				{
					return "Insert";
				}
				return base.Owner.OwnerGrid.Localization.InsertText;
			}
			set
			{
				base.ViewState["_it"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x17003869 RID: 14441
		// (get) Token: 0x0600AE9F RID: 44703 RVA: 0x0025B9E4 File Offset: 0x00259BE4
		// (set) Token: 0x0600AEA0 RID: 44704 RVA: 0x0025BA40 File Offset: 0x00259C40
		[UrlProperty]
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public virtual string InsertImageUrl
		{
			get
			{
				object obj = base.ViewState["_iurl"];
				if (obj != null)
				{
					return base.Owner.OwnerGrid.ResolveUrl((string)obj);
				}
				if (base.Owner != null)
				{
					return base.Owner.OwnerGrid.ResolveGridImageUrl("Update.gif", false);
				}
				return "";
			}
			set
			{
				base.ViewState["_iurl"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x0600AEA1 RID: 44705 RVA: 0x0025BA59 File Offset: 0x00259C59
		protected virtual bool ShouldSerializeInsertImageUrl()
		{
			return base.Owner != null && base.Owner.OwnerGrid.ShouldSerializeImageUrl(this.InsertImageUrl);
		}

		// Token: 0x1700386A RID: 14442
		// (get) Token: 0x0600AEA2 RID: 44706 RVA: 0x0025BA7C File Offset: 0x00259C7C
		// (set) Token: 0x0600AEA3 RID: 44707 RVA: 0x0025BAD8 File Offset: 0x00259CD8
		[NotifyParentProperty(true)]
		[UrlProperty]
		[DefaultValue("")]
		public virtual string UpdateImageUrl
		{
			get
			{
				object obj = base.ViewState["_uurl"];
				if (obj != null)
				{
					return base.Owner.OwnerGrid.ResolveUrl((string)obj);
				}
				if (base.Owner != null)
				{
					return base.Owner.OwnerGrid.ResolveGridImageUrl("Update.gif", false);
				}
				return "";
			}
			set
			{
				base.ViewState["_uurl"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x0600AEA4 RID: 44708 RVA: 0x0025BAF1 File Offset: 0x00259CF1
		protected virtual bool ShouldSerializeUpdateImageUrl()
		{
			return base.Owner != null && base.Owner.OwnerGrid.ShouldSerializeImageUrl(this.UpdateImageUrl);
		}

		// Token: 0x1700386B RID: 14443
		// (get) Token: 0x0600AEA5 RID: 44709 RVA: 0x0025BB14 File Offset: 0x00259D14
		// (set) Token: 0x0600AEA6 RID: 44710 RVA: 0x0025BB41 File Offset: 0x00259D41
		[DefaultValue("")]
		[UrlProperty]
		[NotifyParentProperty(true)]
		public virtual string EditImageUrl
		{
			get
			{
				object obj = base.ViewState["_eurl"];
				if (obj != null)
				{
					return (string)obj;
				}
				return "";
			}
			set
			{
				base.ViewState["_eurl"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x0600AEA7 RID: 44711 RVA: 0x0025BB5A File Offset: 0x00259D5A
		protected virtual bool ShouldSerializeEditImageUrl()
		{
			return base.Owner != null && base.Owner.OwnerGrid.ShouldSerializeImageUrl(this.EditImageUrl);
		}

		// Token: 0x1700386C RID: 14444
		// (get) Token: 0x0600AEA8 RID: 44712 RVA: 0x0025BB7C File Offset: 0x00259D7C
		// (set) Token: 0x0600AEA9 RID: 44713 RVA: 0x0025BBD8 File Offset: 0x00259DD8
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		[UrlProperty]
		public virtual string CancelImageUrl
		{
			get
			{
				object obj = base.ViewState["_curl"];
				if (obj != null)
				{
					return base.Owner.OwnerGrid.ResolveUrl((string)obj);
				}
				if (base.Owner != null)
				{
					return base.Owner.OwnerGrid.ResolveGridImageUrl("Cancel.gif", false);
				}
				return "";
			}
			set
			{
				base.ViewState["_curl"] = value;
				this.OnColumnChanged();
			}
		}

		// Token: 0x0600AEAA RID: 44714 RVA: 0x0025BBF1 File Offset: 0x00259DF1
		protected virtual bool ShouldSerializeCancelImageUrl()
		{
			return base.Owner != null && base.Owner.OwnerGrid.ShouldSerializeImageUrl(this.CancelImageUrl);
		}

		// Token: 0x0600AEAB RID: 44715 RVA: 0x0025BC13 File Offset: 0x00259E13
		protected override string GenerateUniqueName()
		{
			return base.GenerateUniqueNameBase("EditCommandColumn");
		}

		// Token: 0x1700386D RID: 14445
		// (get) Token: 0x0600AEAC RID: 44716 RVA: 0x0025BC20 File Offset: 0x00259E20
		// (set) Token: 0x0600AEAD RID: 44717 RVA: 0x0025BC23 File Offset: 0x00259E23
		[NotifyParentProperty(true)]
		[DefaultValue(false)]
		public override bool Groupable
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		// Token: 0x1700386E RID: 14446
		// (get) Token: 0x0600AEAE RID: 44718 RVA: 0x0025BC25 File Offset: 0x00259E25
		// (set) Token: 0x0600AEAF RID: 44719 RVA: 0x0025BC2D File Offset: 0x00259E2D
		[NotifyParentProperty(true)]
		[Browsable(true)]
		[DefaultValue("EditCommandColumn")]
		public override string UniqueName
		{
			get
			{
				return base.UniqueName;
			}
			set
			{
				base.UniqueName = value;
			}
		}

		// Token: 0x0600AEB0 RID: 44720 RVA: 0x0025BC38 File Offset: 0x00259E38
		public override GridColumn Clone()
		{
			GridEditCommandColumn gridEditCommandColumn = new GridEditCommandColumn();
			gridEditCommandColumn.CopyBaseProperties(this);
			return gridEditCommandColumn;
		}

		// Token: 0x0600AEB1 RID: 44721 RVA: 0x0025BC54 File Offset: 0x00259E54
		protected override void CopyBaseProperties(GridColumn fromColumn)
		{
			base.CopyBaseProperties(fromColumn);
			GridEditCommandColumn gridEditCommandColumn = (GridEditCommandColumn)fromColumn;
			this.ButtonType = gridEditCommandColumn.ButtonType;
			this.CancelText = gridEditCommandColumn.CancelText;
			this.EditText = gridEditCommandColumn.EditText;
			this.FooterText = gridEditCommandColumn.FooterText;
			this.UpdateText = gridEditCommandColumn.UpdateText;
			this.InsertText = gridEditCommandColumn.InsertText;
			this.EditImageUrl = gridEditCommandColumn.EditImageUrl;
			this.UpdateImageUrl = gridEditCommandColumn.UpdateImageUrl;
			this.CancelImageUrl = gridEditCommandColumn.CancelImageUrl;
			this.InsertImageUrl = gridEditCommandColumn.InsertImageUrl;
		}
	}
}
