using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Web;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x0200113E RID: 4414
	public class GridEditFormItem : GridEditableItem
	{
		// Token: 0x0600B3D9 RID: 46041 RVA: 0x00273E9F File Offset: 0x0027209F
		public GridEditFormItem(GridTableView ownerTableView, int itemIndex, int dataSetIndex, GridDataItem parentItem, bool isInEditMode) : base(ownerTableView, itemIndex, dataSetIndex, GridItemType.EditFormItem)
		{
			this._parentItem = parentItem;
			this._isInEditMode = isInEditMode;
			if (this.ParentItem != null)
			{
				this.ParentItem.SetEditFormItem(this);
			}
		}

		// Token: 0x17003A1F RID: 14879
		// (get) Token: 0x0600B3DA RID: 46042 RVA: 0x00273ED0 File Offset: 0x002720D0
		public TableCell EditFormCell
		{
			get
			{
				return this._editFormCell;
			}
		}

		// Token: 0x17003A20 RID: 14880
		// (get) Token: 0x0600B3DB RID: 46043 RVA: 0x00273ED8 File Offset: 0x002720D8
		[SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays")]
		public Control[] FormColumns
		{
			get
			{
				if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
				{
					throw new GridException("FormColumns are only available when EditFormType is GridEditFormType.AutoGenerated");
				}
				return this._formColumns;
			}
		}

		// Token: 0x17003A21 RID: 14881
		// (get) Token: 0x0600B3DC RID: 46044 RVA: 0x00273EFD File Offset: 0x002720FD
		public GridDataItem ParentItem
		{
			get
			{
				return this._parentItem;
			}
		}

		// Token: 0x0600B3DD RID: 46045 RVA: 0x00273F05 File Offset: 0x00272105
		public override void PrepareItemStyle()
		{
			this.EditFormCell.ColumnSpan = base.CalcColSpan(base.OwnerTableView.RenderColumns, this.calculatedColumnIndex, -1);
			base.PrepareItemStyle();
		}

		// Token: 0x0600B3DE RID: 46046 RVA: 0x00273F30 File Offset: 0x00272130
		public override void Initialize(GridColumn[] columns)
		{
			int num = 0;
			while (num < columns.Length && (columns[num] is GridExpandColumn || columns[num] is GridGroupSplitterColumn))
			{
				this.Cells.Add(this.CreateCellObject());
				num++;
			}
			this.calculatedColumnIndex = num;
			TableCell tableCell = this.CreateCellObject();
			tableCell.ColumnSpan = base.CalcColSpan(columns, this.calculatedColumnIndex, -1);
			tableCell.Style.Add("vertical-align", "top");
			this._editFormCell = tableCell;
			this.Cells.Add(tableCell);
			if (this._isInEditMode)
			{
				this.InitializeEditForm(columns);
			}
		}

		// Token: 0x0600B3DF RID: 46047 RVA: 0x00273FCB File Offset: 0x002721CB
		protected override TableCell CreateCellObject()
		{
			return new GridEditFormItem.EditFormTableCell();
		}

		// Token: 0x0600B3E0 RID: 46048 RVA: 0x00273FD4 File Offset: 0x002721D4
		private void InitializeMobileAutogeneratedForm(GridColumn[] columns, ControlCollection controls, GridEditFormSettings formSettings)
		{
			GridMobileEditView gridMobileEditView = new GridMobileEditView(base.OwnerTableView, this);
			gridMobileEditView.ID = "EditView";
			this.EditFormCell.Controls.Add(gridMobileEditView);
			gridMobileEditView.EnsureChildControlsCreated();
		}

		// Token: 0x0600B3E1 RID: 46049 RVA: 0x00274010 File Offset: 0x00272210
		private void InitializeLightweightEditForm(GridColumn[] columns, ControlCollection controls, GridEditFormSettings formSettings)
		{
			for (int i = 0; i < formSettings.ColumnNumber; i++)
			{
				Table table = new Table();
				AccessibilityHelper.AddSummary(table, formSettings.AutoGeneratedColumnEditorsTableWrapperSummary);
				AccessibilityHelper.AddCaption(table, formSettings.AutoGeneratedColumnEditorsTableWrapperCaption);
				controls.Add(table);
				AccessibilityHelper.AddAccessibilityRow(table, base.OwnerTableView.Caption);
				table.MergeStyle(formSettings.FormTableStyle);
				int num = 0;
				int num2 = 0;
				foreach (GridColumn gridColumn in columns)
				{
					GridTemplateColumn gridTemplateColumn = gridColumn as GridTemplateColumn;
					if (((!(gridColumn is GridEditableColumn) && !gridColumn.IsEditable) || (gridTemplateColumn != null && gridTemplateColumn.InsertVisiblityMode == GridColumnVisibilityMode.Inherited && !gridTemplateColumn.IsEditable) || (gridTemplateColumn != null && gridTemplateColumn.InsertVisiblityMode != GridColumnVisibilityMode.Inherited && gridTemplateColumn.IsReadOnly(this))) && (gridTemplateColumn == null || (gridTemplateColumn != null && gridTemplateColumn.ForceExtractValue == GridForceExtractValues.None)))
					{
						num++;
					}
					else if (gridColumn.EditFormColumnIndex != i)
					{
						num++;
					}
					else
					{
						Style s;
						if (num2 % 2 == 0)
						{
							s = formSettings.FormTableItemStyle;
						}
						else
						{
							s = formSettings.FormTableAlternatingItemStyle;
						}
						TableRow tableRow = new GridTableRow();
						table.Rows.Add(tableRow);
						tableRow.MergeStyle(s);
						TableCell tableCell = this.CreateCellObject();
						tableRow.Cells.Add(tableCell);
						TableCell tableCell2 = tableCell;
						tableCell = this.CreateCellObject();
						(tableCell as GridEditFormItem.EditFormTableCell).ColumnName = gridColumn.UniqueName;
						tableCell.ID = "EditCell__" + gridColumn.UniqueName;
						tableRow.Cells.Add(tableCell);
						gridColumn.InitializeCell(tableCell, num, this);
						if (base.OwnerTableView.OwnerGrid.IsClientCommandAssigned && this.IsInEditMode)
						{
							string arg = (this.ParentItem != null) ? this.ParentItem.ItemIndexHierarchical : "";
							string arg2 = string.Format("{0}__{1}", base.OwnerTableView.ClientID, arg);
							tableCell.Attributes["id"] = string.Format("{0}__{1}", arg2, gridColumn.UniqueName);
						}
						Control control = null;
						foreach (object obj in tableCell.Controls)
						{
							Control control2 = (Control)obj;
							if (this.ShouldLabelControl(control2) && control2.Visible)
							{
								control = control2;
								break;
							}
						}
						string text = string.Format(gridColumn.EditFormHeaderTextFormat, gridColumn.HeaderText);
						if (control != null)
						{
							string inputControlClientId = this.GetInputControlClientId(control);
							tableCell2.Text = string.Format("<label for=\"{0}\">{1}</label>", inputControlClientId, text);
						}
						else
						{
							tableCell2.Text = text;
						}
						num++;
						num2++;
						tableRow.Visible = gridColumn.IsEditable;
						GridEditableColumn gridEditableColumn = gridColumn as GridEditableColumn;
						if (gridEditableColumn != null)
						{
							tableRow.Visible = !gridEditableColumn.IsReadOnly(this);
						}
					}
				}
			}
			LiteralControl child = new LiteralControl("<br/>");
			controls.Add(child);
			if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
			{
				(controls[0].Parent as Panel).CssClass = "rgEditFormContainer";
				(controls[0].Parent as Panel).ID = "EditFormContainer";
			}
			if (formSettings.EditColumn.Visible)
			{
				formSettings.EditColumn.InitializeCell(this.EditFormCell, 0, this);
			}
		}

		// Token: 0x0600B3E2 RID: 46050 RVA: 0x0027437C File Offset: 0x0027257C
		private void InitializeAutogeneratedForm(GridColumn[] columns, ControlCollection controls, GridEditFormSettings formSettings)
		{
			Table table = new Table();
			table.ID = "mainTable";
			AccessibilityHelper.AddSummary(table, formSettings.FormMainTableSummary);
			AccessibilityHelper.AddCaption(table, formSettings.FormMainTableCaption);
			controls.Add(table);
			this.MainTableID = table.UniqueID;
			table.MergeStyle(formSettings.FormMainTableStyle);
			AccessibilityHelper.AddAccessibilityRow(table, base.OwnerTableView.Caption);
			TableRow tableRow = new GridTableRow();
			table.Rows.Add(tableRow);
			TableCell tableCell = this.CreateCellObject();
			tableCell.ColumnSpan = formSettings.ColumnNumber;
			tableRow.Cells.Add(tableCell);
			if (base.OwnerTableView.EditMode != GridEditMode.PopUp || formSettings.PopUpSettings.ShowCaptionInEditForm)
			{
				string text = string.Empty;
				if (this is IGridInsertItem && !string.IsNullOrEmpty(formSettings.InsertCaption))
				{
					tableCell.Text = formSettings.InsertCaption;
				}
				else
				{
					if (!string.IsNullOrEmpty(formSettings.CaptionFormatString))
					{
						text = formSettings.CaptionFormatString;
					}
					else if (!string.IsNullOrEmpty(formSettings.CaptionDataField))
					{
						text = "Edit {0}";
					}
					if (!string.IsNullOrEmpty(formSettings.CaptionDataField) && this.DataItem != null)
					{
						string text2 = DataBinder.Eval(this.DataItem, formSettings.CaptionDataField, text);
						tableCell.Text = text2;
					}
					else
					{
						tableCell.Text = text;
					}
				}
				if (base.OwnerTableView.OwnerGrid.EnableAriaSupport)
				{
					tableCell.Attributes.Add("aria-label", tableCell.Text);
				}
			}
			tableRow.Visible = !string.IsNullOrEmpty(tableCell.Text);
			if (tableRow.Visible)
			{
				tableRow.MergeStyle(formSettings.FormCaptionStyle);
			}
			TableRow tableRow2 = new GridTableRow();
			table.Rows.Add(tableRow2);
			tableRow2.ID = "DataRow";
			for (int i = 0; i < formSettings.ColumnNumber; i++)
			{
				TableCell tableCell2 = this.CreateCellObject();
				tableCell2.Style.Add("vertical-align", "top");
				tableRow2.Cells.Add(tableCell2);
			}
			TableRow tableRow3 = new GridTableRow();
			table.Rows.Add(tableRow3);
			tableRow3.MergeStyle(formSettings.FormTableButtonRowStyle);
			TableCell tableCell3 = this.CreateCellObject();
			tableCell3.ColumnSpan = formSettings.ColumnNumber;
			tableRow3.Cells.Add(tableCell3);
			if (formSettings.EditColumn.Visible)
			{
				formSettings.EditColumn.InitializeCell(tableCell3, 0, this);
			}
			else
			{
				tableRow3.Visible = false;
			}
			this._formColumns = new Control[formSettings.ColumnNumber];
			for (int j = 0; j < formSettings.ColumnNumber; j++)
			{
				TableCell tableCell4 = (table.FindControl("DataRow") as TableRow).Cells[j];
				Table table2 = new Table();
				AccessibilityHelper.AddSummary(table2, formSettings.AutoGeneratedColumnEditorsTableWrapperSummary);
				AccessibilityHelper.AddCaption(table2, formSettings.AutoGeneratedColumnEditorsTableWrapperCaption);
				tableCell4.Controls.Add(table2);
				AccessibilityHelper.AddAccessibilityRow(table2, base.OwnerTableView.Caption);
				this._formColumns[j] = table2;
				table2.MergeStyle(formSettings.FormTableStyle);
				int num = 0;
				int num2 = 0;
				foreach (GridColumn gridColumn in columns)
				{
					GridTemplateColumn gridTemplateColumn = gridColumn as GridTemplateColumn;
					if (((!(gridColumn is GridEditableColumn) && !gridColumn.IsEditable) || (gridTemplateColumn != null && gridTemplateColumn.InsertVisiblityMode == GridColumnVisibilityMode.Inherited && !gridTemplateColumn.IsEditable) || (gridTemplateColumn != null && gridTemplateColumn.InsertVisiblityMode != GridColumnVisibilityMode.Inherited && gridTemplateColumn.IsReadOnly(this))) && (gridTemplateColumn == null || (gridTemplateColumn != null && gridTemplateColumn.ForceExtractValue == GridForceExtractValues.None)))
					{
						num++;
					}
					else if (gridColumn.EditFormColumnIndex != j)
					{
						num++;
					}
					else
					{
						Style s;
						if (num2 % 2 == 0)
						{
							s = formSettings.FormTableItemStyle;
						}
						else
						{
							s = formSettings.FormTableAlternatingItemStyle;
						}
						TableRow tableRow4 = new GridTableRow();
						table2.Rows.Add(tableRow4);
						tableRow4.MergeStyle(s);
						TableCell tableCell5 = this.CreateCellObject();
						tableRow4.Cells.Add(tableCell5);
						TableCell tableCell6 = tableCell5;
						tableCell5 = this.CreateCellObject();
						(tableCell5 as GridEditFormItem.EditFormTableCell).ColumnName = gridColumn.UniqueName;
						tableCell5.ID = "EditCell__" + gridColumn.UniqueName;
						tableRow4.Cells.Add(tableCell5);
						gridColumn.InitializeCell(tableCell5, num, this);
						if (base.OwnerTableView.OwnerGrid.IsClientCommandAssigned && this.IsInEditMode)
						{
							string arg = (this.ParentItem != null) ? this.ParentItem.ItemIndexHierarchical : "";
							string arg2 = string.Format("{0}__{1}", base.OwnerTableView.ClientID, arg);
							tableCell5.Attributes["id"] = string.Format("{0}__{1}", arg2, gridColumn.UniqueName);
						}
						Control control = null;
						foreach (object obj in tableCell5.Controls)
						{
							Control control2 = (Control)obj;
							if (this.ShouldLabelControl(control2) && control2.Visible)
							{
								control = control2;
								break;
							}
						}
						string text3 = string.Format(gridColumn.EditFormHeaderTextFormat, gridColumn.HeaderText);
						if (control != null)
						{
							string inputControlClientId = this.GetInputControlClientId(control);
							tableCell6.Text = string.Format("<label for=\"{0}\">{1}</label>", inputControlClientId, text3);
						}
						else
						{
							tableCell6.Text = text3;
						}
						num++;
						num2++;
						tableRow4.Visible = gridColumn.IsEditable;
						GridEditableColumn gridEditableColumn = gridColumn as GridEditableColumn;
						if (gridEditableColumn != null)
						{
							tableRow4.Visible = !gridEditableColumn.IsReadOnly(this);
						}
					}
				}
			}
		}

		// Token: 0x0600B3E3 RID: 46051 RVA: 0x00274920 File Offset: 0x00272B20
		[SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		private string GetInputControlClientId(Control input)
		{
			string result;
			if (input is RadInputControl)
			{
				result = ((RadInputControl)input).TextElementID;
			}
			else if (input is RadDatePicker)
			{
				result = ((RadDatePicker)input).DateInput.TextElementID;
			}
			else if (input is RadComboBox)
			{
				result = input.ClientID + "_Input";
			}
			else
			{
				result = input.ClientID;
			}
			return result;
		}

		// Token: 0x0600B3E4 RID: 46052 RVA: 0x00274984 File Offset: 0x00272B84
		private bool ShouldLabelControl(Control ctrl)
		{
			if (ctrl is TextBox || ctrl is HtmlTextArea || ctrl is RadInputControl || ctrl is RadDatePicker || ctrl is RadComboBox || ctrl is DropDownList)
			{
				return !string.IsNullOrEmpty(ctrl.ClientID);
			}
			return ctrl is CheckBox || ctrl is RadioButton || ctrl is RadioButtonList;
		}

		// Token: 0x0600B3E5 RID: 46053 RVA: 0x002749EC File Offset: 0x00272BEC
		private void InitializeUserControlForm(GridColumn[] columns, ControlCollection controls, GridEditFormSettings formSettings)
		{
			if (this.Page != null)
			{
				Control control = this.Page.LoadControl(formSettings.UserControlName);
				control.ID = "EditFormControl";
				PropertyInfo property = control.GetType().GetProperty("DataItem", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
				if (property != null)
				{
					try
					{
						property.SetValue(control, this.DataItem, new object[0]);
					}
					catch (TargetInvocationException inner)
					{
						throw new GridException("Unable to set value of DataItem property of the user control ", inner);
					}
				}
				controls.Add(control);
			}
		}

		// Token: 0x0600B3E6 RID: 46054 RVA: 0x00274A74 File Offset: 0x00272C74
		private void InitializeTemplateForm(GridColumn[] columns, Control containerControl, GridEditFormSettings formSettings)
		{
			if (formSettings.FormTemplate != null)
			{
				formSettings.FormTemplate.InstantiateIn(containerControl);
			}
		}

		// Token: 0x0600B3E7 RID: 46055 RVA: 0x00274AA8 File Offset: 0x00272CA8
		[SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected virtual void InitializeEditForm(GridColumn[] columns)
		{
			this.EditFormCell.Controls.Clear();
			if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Mobile && base.OwnerTableView.EditMode == GridEditMode.PopUp)
			{
				this.InitializeMobileEditForm(columns);
				return;
			}
			GridEditFormSettings editFormSettings = base.OwnerTableView.EditFormSettings;
			Panel panel = new Panel();
			Control control;
			ControlCollection controls;
			if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
			{
				control = new WebControl(HtmlTextWriterTag.Div);
				string text;
				if (this.ParentItem != null)
				{
					text = string.Format("{0}__{1}_PEF", base.OwnerTableView.ClientID, this.ParentItem.ItemIndexHierarchical);
				}
				else
				{
					text = string.Format("{0}__{1}_PEF", base.OwnerTableView.ClientID, this.ClientID);
				}
				if (base.OwnerTableView.OwnerGrid._popUpLocations.ContainsKey(text))
				{
					Pair pair = base.OwnerTableView.OwnerGrid._popUpLocations[text];
					((WebControl)control).Style["left"] = pair.First.ToString();
					((WebControl)control).Style["top"] = pair.Second.ToString();
				}
				Panel panel2 = new Panel();
				panel2.CssClass = "rgHeader";
				panel2.Style["height"] = "20px";
				panel2.Style["cursor"] = "move";
				if (!string.IsNullOrEmpty(text))
				{
					panel2.Attributes["id"] = text;
				}
				Panel panel3 = new Panel();
				panel3.Style["float"] = "left";
				if (base.OwnerTableView.OwnerGrid.EnableAriaSupport)
				{
					panel3.CssClass = "rgPopupHeaderAria";
				}
				string text2 = string.Empty;
				string title = "";
				if (this is IGridInsertItem && !string.IsNullOrEmpty(editFormSettings.InsertCaption))
				{
					title = editFormSettings.InsertCaption;
				}
				else
				{
					if (!string.IsNullOrEmpty(editFormSettings.CaptionFormatString))
					{
						text2 = editFormSettings.CaptionFormatString;
					}
					else if (!string.IsNullOrEmpty(editFormSettings.CaptionDataField))
					{
						text2 = "Edit {0}";
					}
					if (!string.IsNullOrEmpty(editFormSettings.CaptionDataField))
					{
						if (this.DataItem != null)
						{
							string title2 = DataBinder.Eval(this.DataItem, editFormSettings.CaptionDataField, text2);
							title = title2;
						}
					}
					else
					{
						title = text2;
					}
				}
				Literal literal = new Literal
				{
					ID = "titleLiteral"
				};
				panel3.Controls.Add(literal);
				if (string.IsNullOrEmpty(editFormSettings.CaptionDataField) || this.DataItem != null)
				{
					literal.Load += delegate(object s, EventArgs a)
					{
						((ITextControl)s).Text = title;
					};
				}
				panel2.Controls.Add(panel3);
				Panel panel4 = new Panel();
				panel4.Style["float"] = "right";
				LinkButton linkButton = new LinkButton();
				linkButton.CommandName = "Cancel";
				linkButton.CausesValidation = false;
				linkButton.Style["text-decoration"] = "none";
				Image image = new Image();
				image.Style["border"] = "0";
				image.AlternateText = HttpUtility.HtmlEncode(base.OwnerTableView.EditFormSettings.PopUpSettings.CloseButtonToolTip);
				image.ToolTip = HttpUtility.HtmlEncode(base.OwnerTableView.EditFormSettings.PopUpSettings.CloseButtonToolTip);
				image.Style["cursor"] = "pointer";
				image.Style["float"] = "left";
				image.ImageUrl = RadAjaxLoadingPanel.GetWebResourceUrl(this.Page, "Telerik.Web.UI.Skins.Default.Grid.Cancel.gif");
				linkButton.Controls.Add(image);
				panel4.Controls.Add(linkButton);
				panel2.Controls.Add(panel4);
				Panel panel5 = new Panel();
				panel5.Style["clear"] = "both";
				panel5.Style["display"] = "none";
				panel2.Controls.Add(panel5);
				control.Controls.Add(panel2);
				control.Controls.Add(panel);
				panel.ScrollBars = base.OwnerTableView.EditFormSettings.PopUpSettings.ScrollBars;
				if (base.OwnerTableView.EditFormSettings.PopUpSettings.Width != Unit.Empty)
				{
					((WebControl)control).Style["width"] = base.OwnerTableView.EditFormSettings.PopUpSettings.Width.ToString();
				}
				if (base.OwnerTableView.EditFormSettings.PopUpSettings.Height != Unit.Empty)
				{
					((WebControl)control).Style["height"] = base.OwnerTableView.EditFormSettings.PopUpSettings.Height.ToString();
				}
				panel.Width = Unit.Percentage(100.0);
				panel.Height = Unit.Percentage(100.0);
				((WebControl)control).Style["position"] = "absolute";
				((WebControl)control).Style["display"] = "none";
				controls = panel.Controls;
			}
			else
			{
				control = new WebControl(HtmlTextWriterTag.Div);
				controls = control.Controls;
			}
			if (!base.OwnerTableView.OwnerGrid.EmptySkin())
			{
				((WebControl)control).CssClass = "rgEditForm";
				if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
				{
					WebControl webControl = (WebControl)control;
					string cssClass = webControl.CssClass;
					webControl.CssClass = string.Concat(new string[]
					{
						cssClass,
						" ",
						base.OwnerTableView.OwnerGrid.CssClass,
						" ",
						string.Format("RadGrid_{0}", base.OwnerTableView.OwnerGrid.RuntimeSkin)
					});
					WebControl webControl2 = (WebControl)control;
					webControl2.CssClass += " rgEditPopup";
				}
			}
			GridInitializeEditFormContainer gridInitializeEditFormContainer = new GridInitializeEditFormContainer(control);
			GridItemEventArgs gridItemEventArgs = new GridItemEventArgs(this, gridInitializeEditFormContainer);
			base.OwnerTableView.OwnerGrid.CallOnItemEvent(gridItemEventArgs);
			if (base.OwnerTableView.EditMode != GridEditMode.PopUp)
			{
				control = gridInitializeEditFormContainer.FormContainer;
			}
			if (control.Parent == null)
			{
				this.EditFormCell.Controls.Add(control);
			}
			if (base.OwnerTableView.EditMode == GridEditMode.PopUp && !base.OwnerTableView.OwnerGrid._popUpIds.Contains(control.ClientID))
			{
				base.OwnerTableView.OwnerGrid._popUpIds.Add(control.ClientID);
			}
			if (control is WebControl)
			{
				(control as WebControl).MergeStyle(editFormSettings.FormStyle);
			}
			if (gridItemEventArgs.Canceled)
			{
				return;
			}
			if (editFormSettings.EditFormType == GridEditFormType.AutoGenerated)
			{
				if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight)
				{
					this.InitializeLightweightEditForm(columns, controls, editFormSettings);
					return;
				}
				this.InitializeAutogeneratedForm(columns, controls, editFormSettings);
				return;
			}
			else
			{
				if (editFormSettings.EditFormType == GridEditFormType.WebUserControl)
				{
					this.InitializeUserControlForm(columns, controls, editFormSettings);
					return;
				}
				if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
				{
					this.InitializeTemplateForm(columns, panel, editFormSettings);
					return;
				}
				this.InitializeTemplateForm(columns, control, editFormSettings);
				return;
			}
		}

		// Token: 0x0600B3E8 RID: 46056 RVA: 0x00275218 File Offset: 0x00273418
		private void InitializeMobileEditForm(GridColumn[] columns)
		{
			ControlCollection controls = this.EditFormCell.Controls;
			GridEditFormSettings editFormSettings = base.OwnerTableView.EditFormSettings;
			if (editFormSettings.EditFormType == GridEditFormType.AutoGenerated)
			{
				this.InitializeMobileAutogeneratedForm(columns, controls, editFormSettings);
				return;
			}
			if (editFormSettings.EditFormType == GridEditFormType.WebUserControl)
			{
				this.InitializeUserControlForm(columns, controls, editFormSettings);
				return;
			}
			if (editFormSettings.EditFormType == GridEditFormType.Template)
			{
				this.InitializeTemplateForm(columns, this.EditFormCell, editFormSettings);
			}
		}

		// Token: 0x0600B3E9 RID: 46057 RVA: 0x00275279 File Offset: 0x00273479
		private void GridEditFormItem_Command(object sender, DockCommandEventArgs e)
		{
			base.FireCommandEvent("Cancel", "");
		}

		// Token: 0x0600B3EA RID: 46058 RVA: 0x0027528C File Offset: 0x0027348C
		protected override void CellsDataBound(GridColumn[] columns)
		{
			if (!this._isInEditMode)
			{
				return;
			}
			if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
			{
				return;
			}
			if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Mobile && base.OwnerTableView.EditMode == GridEditMode.PopUp)
			{
				foreach (GridColumn gridColumn in columns)
				{
					GridTemplateColumn gridTemplateColumn = gridColumn as GridTemplateColumn;
					if ((gridColumn is GridEditableColumn || gridColumn.IsEditable) && (gridTemplateColumn == null || gridTemplateColumn.InsertVisiblityMode != GridColumnVisibilityMode.Inherited || gridTemplateColumn.IsEditable) && (gridTemplateColumn == null || gridTemplateColumn.InsertVisiblityMode == GridColumnVisibilityMode.Inherited || !gridTemplateColumn.IsReadOnly(this)))
					{
						this.OnCellDataBound(gridColumn, this.FindControl("EditView").FindControl(gridColumn.UniqueName) as TableCell);
					}
				}
				return;
			}
			for (int j = 0; j < base.OwnerTableView.EditFormSettings.ColumnNumber; j++)
			{
				Table table;
				if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight)
				{
					if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
					{
						table = (Table)this.EditFormCell.Controls[0].Controls[1].Controls[j];
					}
					else
					{
						table = (Table)this.EditFormCell.Controls[0].Controls[j];
					}
				}
				else
				{
					table = (Table)(this.Page.FindControl(this.MainTableID).FindControl("DataRow") as TableRow).Cells[j].Controls[0];
				}
				int num = 0;
				List<TableRow> list = new List<TableRow>();
				foreach (object obj in table.Rows)
				{
					TableRow tableRow = (TableRow)obj;
					if (tableRow is GridTableRow)
					{
						list.Add(tableRow);
					}
				}
				foreach (GridColumn gridColumn2 in columns)
				{
					GridTemplateColumn gridTemplateColumn2 = gridColumn2 as GridTemplateColumn;
					if ((gridColumn2 is GridEditableColumn || gridColumn2.IsEditable) && (gridTemplateColumn2 == null || gridTemplateColumn2.InsertVisiblityMode != GridColumnVisibilityMode.Inherited || gridTemplateColumn2.IsEditable) && (gridTemplateColumn2 == null || gridTemplateColumn2.InsertVisiblityMode == GridColumnVisibilityMode.Inherited || !gridTemplateColumn2.IsReadOnly(this)) && gridColumn2.EditFormColumnIndex == j)
					{
						this.OnCellDataBound(gridColumn2, list[num].Cells[1]);
						num++;
					}
				}
			}
		}

		// Token: 0x0600B3EB RID: 46059 RVA: 0x00275528 File Offset: 0x00273728
		public override void SetupItem(bool dataBind, object dataItem, GridColumn[] columns, ControlCollection rows)
		{
			GridItemEventArgs e = new GridItemEventArgs(this, new GridItemCreated());
			this.DataItem = dataItem;
			if (dataBind)
			{
				this._isInEditMode = true;
				if (this.ParentItem != null)
				{
					this._isInEditMode = this.ParentItem.Edit;
				}
			}
			this.Visible = (this.ParentItem == null || (this.ParentItem.Visible && this._isInEditMode));
			rows.Add(this);
			this.Initialize(columns);
			base.OwnerTableView.OwnerGrid.CallOnItemCreated(e);
			if (!dataBind)
			{
				return;
			}
			this.DataBind();
			this.CellsDataBound(columns);
			e = new GridItemEventArgs(this, new GridItemDataBound());
			base.OwnerTableView.OwnerGrid.CallOnItemDataBound(e);
		}

		// Token: 0x0600B3EC RID: 46060 RVA: 0x002755E0 File Offset: 0x002737E0
		protected override void SetEdited(bool value)
		{
			if (!value)
			{
				this.ParentItem.Edit = false;
			}
		}

		// Token: 0x0600B3ED RID: 46061 RVA: 0x002755F1 File Offset: 0x002737F1
		internal override void SetItemDecorator(GridItemDecorator newDecorator)
		{
			base.SetItemDecorator(new GridNestedViewItemDecorator(this));
		}

		// Token: 0x0600B3EE RID: 46062 RVA: 0x00275600 File Offset: 0x00273800
		protected override bool OnBubbleEvent(object source, EventArgs e)
		{
			Hashtable hashtable = new Hashtable();
			hashtable["Update"] = true;
			hashtable["Cancel"] = true;
			CommandEventArgs commandEventArgs = e as CommandEventArgs;
			GridItem gridItem;
			if (this.ParentItem != null && commandEventArgs != null && hashtable[commandEventArgs.CommandName] == null)
			{
				gridItem = this.ParentItem;
			}
			else
			{
				gridItem = this;
			}
			if (e is GridCommandEventArgs)
			{
				base.RaiseBubbleEvent(gridItem, e);
				return true;
			}
			if (commandEventArgs != null)
			{
				GridCommandEventArgs args = GridCommandEventArgsFactory.CreateGridCommandEventArgs(gridItem, source, commandEventArgs);
				base.RaiseBubbleEvent(gridItem, args);
				return true;
			}
			return false;
		}

		// Token: 0x0600B3EF RID: 46063 RVA: 0x0027568C File Offset: 0x0027388C
		public override void InitializeEditorInCell(IGridEditableColumn column)
		{
			if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
			{
				throw new GridBindingException("The current EditFormType does not support the requested editing capabilities.");
			}
			if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Mobile && base.OwnerTableView.EditMode == GridEditMode.PopUp)
			{
				Control control = this.FindControl(column.Column.UniqueName);
				if (control != null)
				{
					column.Column.CurrentColumnEditor.InitializeFromControl(control);
					return;
				}
			}
			else
			{
				GridEditFormItem.EditFormTableCell editFormTableCell = this.FindEditFormTableCell(column.Column.UniqueName);
				if (editFormTableCell != null)
				{
					column.Column.CurrentColumnEditor.InitializeFromControl(editFormTableCell);
				}
			}
		}

		// Token: 0x0600B3F0 RID: 46064 RVA: 0x00275724 File Offset: 0x00273924
		protected GridEditFormItem.EditFormTableCell FindEditFormTableCell(string columnUniqueName)
		{
			GridEditFormItem.EditFormTableCell editFormTableCell = null;
			if (!string.IsNullOrEmpty(this.MainTableID) || base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight)
			{
				for (int i = 0; i < base.OwnerTableView.EditFormSettings.ColumnNumber; i++)
				{
					Table table;
					if (base.OwnerTableView.OwnerGrid.ResolvedRenderMode == RenderMode.Lightweight)
					{
						if (base.OwnerTableView.EditMode == GridEditMode.PopUp)
						{
							table = (Table)this.EditFormCell.Controls[0].Controls[1].Controls[i];
						}
						else
						{
							table = (Table)this.EditFormCell.Controls[0].Controls[i];
						}
					}
					else
					{
						table = (Table)(this.Page.FindControl(this.MainTableID).FindControl("DataRow") as TableRow).Cells[i].Controls[0];
					}
					foreach (object obj in table.Rows)
					{
						TableRow tableRow = (TableRow)obj;
						foreach (object obj2 in tableRow.Cells)
						{
							TableCell tableCell = (TableCell)obj2;
							GridEditFormItem.EditFormTableCell editFormTableCell2 = tableCell as GridEditFormItem.EditFormTableCell;
							if (editFormTableCell2 != null && editFormTableCell2.ColumnName == columnUniqueName)
							{
								editFormTableCell = editFormTableCell2;
								break;
							}
						}
						if (editFormTableCell != null)
						{
							break;
						}
					}
				}
			}
			return editFormTableCell;
		}

		// Token: 0x17003A22 RID: 14882
		// (get) Token: 0x0600B3F1 RID: 46065 RVA: 0x002758E4 File Offset: 0x00273AE4
		public override GridEditManager EditManager
		{
			get
			{
				if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
				{
					throw new GridBindingException("The current EditFormType does not support the requested editing capabilities.");
				}
				return base.EditManager;
			}
		}

		// Token: 0x17003A23 RID: 14883
		// (get) Token: 0x0600B3F2 RID: 46066 RVA: 0x00275909 File Offset: 0x00273B09
		public override bool IsDataBound
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17003A24 RID: 14884
		// (get) Token: 0x0600B3F3 RID: 46067 RVA: 0x0027590C File Offset: 0x00273B0C
		public override bool IsInEditMode
		{
			get
			{
				return this._isInEditMode;
			}
		}

		// Token: 0x17003A25 RID: 14885
		public override TableCell this[string columnUniqueName]
		{
			get
			{
				if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
				{
					if (this.ParentItem == null)
					{
						throw new GridNotSupportedException("Item in insert mode does implement indexer only when the edit form is autogenerated");
					}
					return this.ParentItem[columnUniqueName];
				}
				else
				{
					GridEditFormItem.EditFormTableCell editFormTableCell = this.FindEditFormTableCell(columnUniqueName);
					if (editFormTableCell != null)
					{
						return editFormTableCell;
					}
					if (this.ParentItem != null)
					{
						return this.ParentItem[columnUniqueName];
					}
					throw new GridException(string.Format("Cannot find cell bound to column with unique name '{0}'", columnUniqueName));
				}
			}
		}

		// Token: 0x17003A26 RID: 14886
		public override TableCell this[GridColumn column]
		{
			get
			{
				return this[column.UniqueName];
			}
		}

		// Token: 0x17003A27 RID: 14887
		// (get) Token: 0x0600B3F6 RID: 46070 RVA: 0x00275994 File Offset: 0x00273B94
		public override IDictionary SavedOldValues
		{
			get
			{
				object obj = this.ViewState["_sov"];
				if (obj == null)
				{
					obj = new Hashtable();
					this.ViewState["_sov"] = obj;
				}
				return (IDictionary)obj;
			}
		}

		// Token: 0x17003A28 RID: 14888
		// (get) Token: 0x0600B3F7 RID: 46071 RVA: 0x002759D2 File Offset: 0x00273BD2
		public override bool CanExtractValues
		{
			get
			{
				return base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.WebUserControl;
			}
		}

		// Token: 0x0600B3F8 RID: 46072 RVA: 0x002759EC File Offset: 0x00273BEC
		public override void ExtractValues(IDictionary newValues)
		{
			if (base.OwnerTableView.EditFormSettings.EditFormType == GridEditFormType.WebUserControl)
			{
				throw new GridNotSupportedException("Cannot extract values from item when EditFormType is WebUserControl. If you whish to use AutomaticUpdate, AutomaticInsert or AutomaticDelete, please specify GridEditFormType.Template for EditFormSettings.EditFormType and declare the WebUserControl into EditFormSettings.FormTemplate.");
			}
			if (base.OwnerTableView.EditFormSettings.EditFormType == GridEditFormType.AutoGenerated)
			{
				base.ExtractValues(newValues);
				return;
			}
			this.ExtractValuesFromTemplate(newValues, base.OwnerTableView.EditFormSettings.FormTemplate);
		}

		// Token: 0x0600B3F9 RID: 46073 RVA: 0x00275A48 File Offset: 0x00273C48
		protected virtual void ExtractValuesFromTemplate(IDictionary newValues, ITemplate templateControl)
		{
			IBindableTemplate bindableTemplate = templateControl as IBindableTemplate;
			if (bindableTemplate != null)
			{
				using (IDictionaryEnumerator enumerator = bindableTemplate.ExtractValues(this).GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						object obj = enumerator.Current;
						DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
						newValues[dictionaryEntry.Key] = dictionaryEntry.Value;
					}
					return;
				}
			}
			if (base.OwnerTableView.AllowAutomaticUpdates || base.OwnerTableView.AllowAutomaticDeletes)
			{
				throw new GridNotSupportedException("Automatic updates, inserts are supported only when the template is IBindableTemplate");
			}
		}

		// Token: 0x04002F59 RID: 12121
		public const string EditFormUserControlID = "EditFormControl";

		// Token: 0x04002F5A RID: 12122
		private TableCell _editFormCell;

		// Token: 0x04002F5B RID: 12123
		private int calculatedColumnIndex;

		// Token: 0x04002F5C RID: 12124
		private GridDataItem _parentItem;

		// Token: 0x04002F5D RID: 12125
		private bool _isInEditMode;

		// Token: 0x04002F5E RID: 12126
		private Control[] _formColumns;

		// Token: 0x04002F5F RID: 12127
		internal string MainTableID;

		// Token: 0x0200113F RID: 4415
		[SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
		public class EditFormTableCell : TableCell
		{
			// Token: 0x17003A29 RID: 14889
			// (get) Token: 0x0600B3FA RID: 46074 RVA: 0x00275AE0 File Offset: 0x00273CE0
			// (set) Token: 0x0600B3FB RID: 46075 RVA: 0x00275B0D File Offset: 0x00273D0D
			public string ColumnName
			{
				get
				{
					string text = (string)this.ViewState["_cn"];
					if (text == null)
					{
						return string.Empty;
					}
					return text;
				}
				set
				{
					this.ViewState["_cn"] = value;
				}
			}
		}
	}
}
