using System;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x02001140 RID: 4416
	public class GridEditFormInsertItem : GridEditFormItem, IGridInsertItem
	{
		// Token: 0x0600B3FD RID: 46077 RVA: 0x00275B28 File Offset: 0x00273D28
		public GridEditFormInsertItem(GridTableView ownerTableView) : base(ownerTableView, -1, -1, null, true)
		{
		}

		// Token: 0x17003A2A RID: 14890
		public override TableCell this[string columnUniqueName]
		{
			get
			{
				if (base.OwnerTableView.EditFormSettings.EditFormType != GridEditFormType.AutoGenerated)
				{
					if (base.ParentItem == null)
					{
						throw new GridNotSupportedException("Item in insert mode does implement indexer only when the edit form is autogenerated");
					}
					return base.ParentItem[columnUniqueName];
				}
				else
				{
					GridEditFormItem.EditFormTableCell editFormTableCell = base.FindEditFormTableCell(columnUniqueName);
					if (editFormTableCell != null)
					{
						return editFormTableCell;
					}
					if (base.ParentItem != null)
					{
						return base.ParentItem[columnUniqueName];
					}
					throw new GridException(string.Format("Cannot find cell bound to column with unique name '{0}'", columnUniqueName));
				}
			}
		}

		// Token: 0x17003A2B RID: 14891
		public override TableCell this[GridColumn column]
		{
			get
			{
				return this[column.UniqueName];
			}
		}

		// Token: 0x17003A2C RID: 14892
		// (get) Token: 0x0600B400 RID: 46080 RVA: 0x00275BB7 File Offset: 0x00273DB7
		// (set) Token: 0x0600B401 RID: 46081 RVA: 0x00275BBA File Offset: 0x00273DBA
		public override bool Edit
		{
			get
			{
				return true;
			}
			set
			{
				if (!value)
				{
					base.OwnerTableView.IsItemInserted = false;
				}
			}
		}

		// Token: 0x17003A2D RID: 14893
		// (get) Token: 0x0600B402 RID: 46082 RVA: 0x00275BCB File Offset: 0x00273DCB
		public override bool IsInEditMode
		{
			get
			{
				return true;
			}
		}

		// Token: 0x0600B403 RID: 46083 RVA: 0x00275BD0 File Offset: 0x00273DD0
		protected override void InitializeEditForm(GridColumn[] columns)
		{
			base.InitializeEditForm(columns);
			if (base.OwnerTableView.OwnerGrid.ClientSettings.AllowKeyboardNavigation && base.OwnerTableView.OwnerGrid.ResolvedRenderMode != RenderMode.Mobile)
			{
				base.Attributes["onkeypress"] = string.Format("$find('{0}')._handlerKeyDownInInserItem(event);", base.OwnerTableView.ClientID);
			}
		}
	}
}
