using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x020010CD RID: 4301
	[TypeConverter(typeof(ExpandableObjectConverter))]
	[SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable")]
	public class GridEditFormSettings : IStateManager
	{
		// Token: 0x0600AF7C RID: 44924 RVA: 0x00260BD0 File Offset: 0x0025EDD0
		public GridEditFormSettings(GridTableView owner)
		{
			this.owner = owner;
		}

		// Token: 0x170038A7 RID: 14503
		// (get) Token: 0x0600AF7D RID: 44925 RVA: 0x00260BEA File Offset: 0x0025EDEA
		private StateBag ViewState
		{
			get
			{
				return this.stateManager.ViewState;
			}
		}

		// Token: 0x170038A8 RID: 14504
		// (get) Token: 0x0600AF7E RID: 44926 RVA: 0x00260BF8 File Offset: 0x0025EDF8
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Set properties of the update-cancel buttons column that appears in an edit form")]
		public GridEditCommandColumn EditColumn
		{
			get
			{
				if (this._editColumn == null)
				{
					this._editColumn = new GridEditCommandColumn();
					this._editColumn.SetOwner(this.owner);
					this.stateManager.AddManager(this._editColumn, "_ecc");
				}
				return this._editColumn;
			}
		}

		// Token: 0x170038A9 RID: 14505
		// (get) Token: 0x0600AF7F RID: 44927 RVA: 0x00260C48 File Offset: 0x0025EE48
		// (set) Token: 0x0600AF80 RID: 44928 RVA: 0x00260C76 File Offset: 0x0025EE76
		[DefaultValue(1)]
		[NotifyParentProperty(true)]
		[Description("Number of vertical columns to split all edit fields on the form when it is autogenerated")]
		public int ColumnNumber
		{
			get
			{
				object obj = this.ViewState["_cn"];
				if (obj == null)
				{
					obj = 1;
				}
				return (int)obj;
			}
			set
			{
				if (value <= 0)
				{
					throw new GridException("The columns number must be greater than 1");
				}
				this.ViewState["_cn"] = value;
			}
		}

		// Token: 0x170038AA RID: 14506
		// (get) Token: 0x0600AF81 RID: 44929 RVA: 0x00260CA0 File Offset: 0x0025EEA0
		// (set) Token: 0x0600AF82 RID: 44930 RVA: 0x00260CCD File Offset: 0x0025EECD
		[Description("Data field to incude in form's caption")]
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public virtual string CaptionDataField
		{
			get
			{
				object obj = this.ViewState["_cdf"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["_cdf"] = value;
			}
		}

		// Token: 0x170038AB RID: 14507
		// (get) Token: 0x0600AF83 RID: 44931 RVA: 0x00260CE0 File Offset: 0x0025EEE0
		// (set) Token: 0x0600AF84 RID: 44932 RVA: 0x00260D0D File Offset: 0x0025EF0D
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		[Localizable(true)]
		[Description("Caption format string - {0} parameter must be included and would be repaced with DataField value")]
		public virtual string CaptionFormatString
		{
			get
			{
				object obj = this.ViewState["_cfs"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["_cfs"] = value;
			}
		}

		// Token: 0x170038AC RID: 14508
		// (get) Token: 0x0600AF85 RID: 44933 RVA: 0x00260D20 File Offset: 0x0025EF20
		// (set) Token: 0x0600AF86 RID: 44934 RVA: 0x00260D4D File Offset: 0x0025EF4D
		[NotifyParentProperty(true)]
		[DefaultValue("")]
		[Localizable(true)]
		[Description("Caption for the pop-up insert form")]
		public virtual string InsertCaption
		{
			get
			{
				object obj = this.ViewState["_icfs"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["_icfs"] = value;
			}
		}

		// Token: 0x170038AD RID: 14509
		// (get) Token: 0x0600AF87 RID: 44935 RVA: 0x00260D60 File Offset: 0x0025EF60
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		[Description("Style of the forms's area (rendered as a DIV elemet)")]
		public Style FormStyle
		{
			get
			{
				if (this._formStyle == null)
				{
					this._formStyle = new Style();
				}
				return this._formStyle;
			}
		}

		// Token: 0x170038AE RID: 14510
		// (get) Token: 0x0600AF88 RID: 44936 RVA: 0x00260D7B File Offset: 0x0025EF7B
		[NotifyParentProperty(true)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the forms' table elements that represent each form-column")]
		public TableStyle FormTableStyle
		{
			get
			{
				if (this._formTableStyle == null)
				{
					this._formTableStyle = new TableStyle();
					this.stateManager.AddManager(this._formTableStyle, "_fts");
				}
				return this._formTableStyle;
			}
		}

		// Token: 0x170038AF RID: 14511
		// (get) Token: 0x0600AF89 RID: 44937 RVA: 0x00260DAC File Offset: 0x0025EFAC
		[NotifyParentProperty(true)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the forms' main table element")]
		public TableStyle FormMainTableStyle
		{
			get
			{
				if (this._formMainTableStyle == null)
				{
					this._formMainTableStyle = new TableStyle();
					this.stateManager.AddManager(this._formMainTableStyle, "_fmts");
				}
				return this._formMainTableStyle;
			}
		}

		// Token: 0x170038B0 RID: 14512
		// (get) Token: 0x0600AF8A RID: 44938 RVA: 0x00260DDD File Offset: 0x0025EFDD
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		[Description("Style of the table row that shows the caption of the form")]
		public TableItemStyle FormCaptionStyle
		{
			get
			{
				if (this._formCaptionStyle == null)
				{
					this._formCaptionStyle = new TableItemStyle();
					this.stateManager.AddManager(this._formCaptionStyle, "_fcs");
				}
				return this._formCaptionStyle;
			}
		}

		// Token: 0x170038B1 RID: 14513
		// (get) Token: 0x0600AF8B RID: 44939 RVA: 0x00260E0E File Offset: 0x0025F00E
		[Description("Style of the normal row in the edit-form's table")]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		public TableItemStyle FormTableItemStyle
		{
			get
			{
				if (this._formTableItemStyle == null)
				{
					this._formTableItemStyle = new TableItemStyle();
					this.stateManager.AddManager(this._formTableItemStyle, "_ftis");
				}
				return this._formTableItemStyle;
			}
		}

		// Token: 0x170038B2 RID: 14514
		// (get) Token: 0x0600AF8C RID: 44940 RVA: 0x00260E3F File Offset: 0x0025F03F
		[NotifyParentProperty(true)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the alternating rows in the edit-form's table")]
		public TableItemStyle FormTableAlternatingItemStyle
		{
			get
			{
				if (this._formTableAlternatingItemStyle == null)
				{
					this._formTableAlternatingItemStyle = new TableItemStyle();
					this.stateManager.AddManager(this._formTableAlternatingItemStyle, "_ftais");
				}
				return this._formTableAlternatingItemStyle;
			}
		}

		// Token: 0x170038B3 RID: 14515
		// (get) Token: 0x0600AF8D RID: 44941 RVA: 0x00260E70 File Offset: 0x0025F070
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		[Description("Style of the footer row of the table, where the update-cancel buttons appear")]
		public TableItemStyle FormTableButtonRowStyle
		{
			get
			{
				if (this._formTableFooterStyle == null)
				{
					this._formTableFooterStyle = new TableItemStyle();
					this.stateManager.AddManager(this._formTableFooterStyle, "_ftfs");
				}
				return this._formTableFooterStyle;
			}
		}

		// Token: 0x0600AF8E RID: 44942 RVA: 0x00260EA1 File Offset: 0x0025F0A1
		void IStateManager.LoadViewState(object state)
		{
			this.stateManager.LoadViewState(state);
		}

		// Token: 0x0600AF8F RID: 44943 RVA: 0x00260EAF File Offset: 0x0025F0AF
		object IStateManager.SaveViewState()
		{
			return this.stateManager.SaveViewState();
		}

		// Token: 0x0600AF90 RID: 44944 RVA: 0x00260EBC File Offset: 0x0025F0BC
		void IStateManager.TrackViewState()
		{
			this.stateManager.TrackViewState();
		}

		// Token: 0x170038B4 RID: 14516
		// (get) Token: 0x0600AF91 RID: 44945 RVA: 0x00260EC9 File Offset: 0x0025F0C9
		bool IStateManager.IsTrackingViewState
		{
			get
			{
				return this.stateManager.IsTrackingViewState;
			}
		}

		// Token: 0x170038B5 RID: 14517
		// (get) Token: 0x0600AF92 RID: 44946 RVA: 0x00260ED8 File Offset: 0x0025F0D8
		// (set) Token: 0x0600AF93 RID: 44947 RVA: 0x00260F01 File Offset: 0x0025F101
		[NotifyParentProperty(true)]
		[DefaultValue(typeof(GridEditFormType), "AutoGenerated")]
		public GridEditFormType EditFormType
		{
			get
			{
				object obj = this.ViewState["_eft"];
				if (obj != null)
				{
					return (GridEditFormType)obj;
				}
				return GridEditFormType.AutoGenerated;
			}
			set
			{
				this.ViewState["_eft"] = value;
			}
		}

		// Token: 0x170038B6 RID: 14518
		// (get) Token: 0x0600AF94 RID: 44948 RVA: 0x00260F1C File Offset: 0x0025F11C
		// (set) Token: 0x0600AF95 RID: 44949 RVA: 0x00260F49 File Offset: 0x0025F149
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public string UserControlName
		{
			get
			{
				object obj = this.ViewState["_ucn"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["_ucn"] = value;
			}
		}

		// Token: 0x170038B7 RID: 14519
		// (get) Token: 0x0600AF96 RID: 44950 RVA: 0x00260F5C File Offset: 0x0025F15C
		// (set) Token: 0x0600AF97 RID: 44951 RVA: 0x00260F64 File Offset: 0x0025F164
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DefaultValue(null)]
		[Description("EditForm template - if EditFormType is Template")]
		[Browsable(false)]
		[TemplateContainer(typeof(GridItem), BindingDirection.TwoWay)]
		public virtual ITemplate FormTemplate
		{
			get
			{
				return this._formTemplate;
			}
			set
			{
				this._formTemplate = value;
			}
		}

		// Token: 0x170038B8 RID: 14520
		// (get) Token: 0x0600AF98 RID: 44952 RVA: 0x00260F70 File Offset: 0x0025F170
		[NotifyParentProperty(true)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		public GridPopUpSettings PopUpSettings
		{
			get
			{
				if (this._popUpSettings == null)
				{
					this._popUpSettings = new GridPopUpSettings(this.ViewState);
					if (this.owner.OwnerGrid != null)
					{
						this._popUpSettings.SetLocalizedStrings(this.owner.OwnerGrid.Localization);
					}
				}
				return this._popUpSettings;
			}
		}

		// Token: 0x170038B9 RID: 14521
		// (get) Token: 0x0600AF99 RID: 44953 RVA: 0x00260FC4 File Offset: 0x0025F1C4
		// (set) Token: 0x0600AF9A RID: 44954 RVA: 0x00260FF1 File Offset: 0x0025F1F1
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		[Description("The summary attribute for the table that wraps the whole GridEditFormItem")]
		public string FormMainTableSummary
		{
			get
			{
				object obj = this.ViewState["FormMainTableSummary"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["FormMainTableSummary"] = value;
			}
		}

		// Token: 0x170038BA RID: 14522
		// (get) Token: 0x0600AF9B RID: 44955 RVA: 0x00261004 File Offset: 0x0025F204
		// (set) Token: 0x0600AF9C RID: 44956 RVA: 0x00261031 File Offset: 0x0025F231
		[NotifyParentProperty(true)]
		[Description("The caption for the table that wraps the whole GridEditFormItem")]
		[DefaultValue("")]
		public string FormMainTableCaption
		{
			get
			{
				object obj = this.ViewState["FormMainTableCaption"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["FormMainTableCaption"] = value;
			}
		}

		// Token: 0x170038BB RID: 14523
		// (get) Token: 0x0600AF9D RID: 44957 RVA: 0x00261044 File Offset: 0x0025F244
		// (set) Token: 0x0600AF9E RID: 44958 RVA: 0x00261071 File Offset: 0x0025F271
		[Description("The summary attribute for the table which holds all cells created from the grid column editors")]
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public string AutoGeneratedColumnEditorsTableWrapperSummary
		{
			get
			{
				object obj = this.ViewState["AutoGeneratedColumnEditorsTableWrapperSummary"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["AutoGeneratedColumnEditorsTableWrapperSummary"] = value;
			}
		}

		// Token: 0x170038BC RID: 14524
		// (get) Token: 0x0600AF9F RID: 44959 RVA: 0x00261084 File Offset: 0x0025F284
		// (set) Token: 0x0600AFA0 RID: 44960 RVA: 0x002610B1 File Offset: 0x0025F2B1
		[DefaultValue("")]
		[Description("The caption for the table which holds all cells created from the grid column editors")]
		[NotifyParentProperty(true)]
		public string AutoGeneratedColumnEditorsTableWrapperCaption
		{
			get
			{
				object obj = this.ViewState["AutoGeneratedColumnEditorsTableWrapperCaption"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				this.ViewState["AutoGeneratedColumnEditorsTableWrapperCaption"] = value;
			}
		}

		// Token: 0x04002E46 RID: 11846
		private GridTableView owner;

		// Token: 0x04002E47 RID: 11847
		private Style _formStyle;

		// Token: 0x04002E48 RID: 11848
		private TableStyle _formMainTableStyle;

		// Token: 0x04002E49 RID: 11849
		private TableStyle _formTableStyle;

		// Token: 0x04002E4A RID: 11850
		private TableItemStyle _formCaptionStyle;

		// Token: 0x04002E4B RID: 11851
		private TableItemStyle _formTableItemStyle;

		// Token: 0x04002E4C RID: 11852
		private TableItemStyle _formTableAlternatingItemStyle;

		// Token: 0x04002E4D RID: 11853
		private TableItemStyle _formTableFooterStyle;

		// Token: 0x04002E4E RID: 11854
		private GridEditCommandColumn _editColumn;

		// Token: 0x04002E4F RID: 11855
		private ITemplate _formTemplate;

		// Token: 0x04002E50 RID: 11856
		private GridStateManager stateManager = new GridStateManager();

		// Token: 0x04002E51 RID: 11857
		private GridPopUpSettings _popUpSettings;
	}
}
