using System;
using System.Drawing;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x02001117 RID: 4375
	internal class GridItemDecorator
	{
		// Token: 0x170039F1 RID: 14833
		// (get) Token: 0x0600B31E RID: 45854 RVA: 0x0026FC27 File Offset: 0x0026DE27
		public GridItem Item
		{
			get
			{
				return this._item;
			}
		}

		// Token: 0x0600B31F RID: 45855 RVA: 0x0026FC2F File Offset: 0x0026DE2F
		public GridItemDecorator(GridItem item)
		{
			this._item = item;
		}

		// Token: 0x0600B320 RID: 45856 RVA: 0x0026FC40 File Offset: 0x0026DE40
		public virtual void SetItemVisibility(GridTableView owner, GridColumn[] columnArray)
		{
			int num = 0;
			int num2 = 0;
			foreach (object obj in this.Item.Cells)
			{
				TableCell tableCell = (TableCell)obj;
				GridColumn gridColumn = null;
				if (num >= 0 && columnArray.Length > num)
				{
					gridColumn = columnArray[num];
				}
				else if (columnArray.Length <= num)
				{
					int num3 = num - columnArray.Length;
					if (num3 > 0 && num3 < owner.AutoGeneratedColumns.Length)
					{
						gridColumn = owner.AutoGeneratedColumns[num3];
					}
				}
				if (gridColumn != null && !gridColumn.Visible)
				{
					num2++;
					GridGroupFooterItem gridGroupFooterItem = tableCell.Parent as GridGroupFooterItem;
					if (gridGroupFooterItem != null && gridGroupFooterItem.OwnerTableView.GroupFooterTemplate != null)
					{
						continue;
					}
					tableCell.Visible = this.GetIsDetailTemplateItemDataCell(tableCell);
				}
				num++;
			}
		}

		// Token: 0x0600B321 RID: 45857 RVA: 0x0026FD24 File Offset: 0x0026DF24
		private bool GetIsDetailTemplateItemDataCell(TableCell cell)
		{
			GridDetailTemplateItem gridDetailTemplateItem = cell.Parent as GridDetailTemplateItem;
			return gridDetailTemplateItem != null && cell.Equals(gridDetailTemplateItem.DataCell);
		}

		// Token: 0x0600B322 RID: 45858 RVA: 0x0026FD50 File Offset: 0x0026DF50
		public virtual void DecorateItem(GridTableView owner, GridColumn[] columnArray)
		{
			this.SetItemStyle(owner);
			int num = 0;
			foreach (object obj in this.Item.Cells)
			{
				TableCell tableCell = (TableCell)obj;
				GridColumn gridColumn = null;
				if (num >= 0 && columnArray.Length > num)
				{
					gridColumn = columnArray[num];
				}
				else if (columnArray.Length <= num)
				{
					int num2 = num - columnArray.Length;
					if (num2 > 0 && num2 < owner.AutoGeneratedColumns.Length)
					{
						gridColumn = owner.AutoGeneratedColumns[num2];
					}
				}
				if (gridColumn != null && !gridColumn.Visible)
				{
					GridGroupFooterItem gridGroupFooterItem = tableCell.Parent as GridGroupFooterItem;
					if (gridGroupFooterItem != null && gridGroupFooterItem.OwnerTableView.GroupFooterTemplate != null)
					{
						continue;
					}
					tableCell.Visible = this.GetIsDetailTemplateItemDataCell(tableCell);
				}
				else
				{
					if (gridColumn != null)
					{
						this.PrepareCellInColumn(owner, gridColumn, tableCell);
						gridColumn.PrepareCell(tableCell, this.Item);
					}
					this.PrepareCell(owner, tableCell);
				}
				if (gridColumn != null && !gridColumn.Display)
				{
					tableCell.Style["display"] = "none";
				}
				num++;
			}
			if (this.Item != null && !this.Item.Display)
			{
				this.Item.Style["display"] = "none";
			}
		}

		// Token: 0x0600B323 RID: 45859 RVA: 0x0026FEA0 File Offset: 0x0026E0A0
		protected void AddColorToStyle(CssStyleCollection style, string attribute, Color color)
		{
			string value = ColorTranslator.ToHtml(color);
			if (!string.IsNullOrEmpty(value))
			{
				style[attribute] = value;
			}
		}

		// Token: 0x0600B324 RID: 45860 RVA: 0x0026FEC4 File Offset: 0x0026E0C4
		public virtual void SetItemStyle(GridTableView owner)
		{
			if (this.Item is GridGroupFooterItem)
			{
				if (!owner.RenderFooterStyle.CssClass.Contains("rgFooter"))
				{
					GridItem item = this.Item;
					item.CssClass += " rgFooter";
				}
			}
			else
			{
				this.Item.MergeStyle(owner.RenderItemStyle);
			}
			if (this.Item is GridDataItem)
			{
				this.Item.Attributes["id"] = HttpUtility.HtmlEncode(string.Format("{0}__{1}", this.Item.OwnerTableView.ClientID, this.Item.ItemIndexHierarchical));
			}
		}

		// Token: 0x0600B325 RID: 45861 RVA: 0x0026FF70 File Offset: 0x0026E170
		public virtual void PrepareCell(GridTableView owner, TableCell cell)
		{
			GridTableCell gridTableCell = cell as GridTableCell;
			if (gridTableCell != null && owner.OwnerGrid.SelectedCellIndexes.Contains(gridTableCell.CellIndexHierarchical))
			{
				gridTableCell.CssClass = "rgSelectedCell";
			}
		}

		// Token: 0x0600B326 RID: 45862 RVA: 0x0026FFAC File Offset: 0x0026E1AC
		public virtual void PrepareCellInColumn(GridTableView owner, GridColumn column, TableCell cell)
		{
			GridGroupSplitterColumn gridGroupSplitterColumn = column as GridGroupSplitterColumn;
			if (gridGroupSplitterColumn != null && string.IsNullOrEmpty(owner.OwnerGrid.RuntimeSkin))
			{
				this.AddColorToStyle(cell.Style, "border-bottom-color", this.Item.OwnerTableView.RenderGroupHeaderItemStyle.BackColor);
				this.AddColorToStyle(cell.Style, "border-top-color", this.Item.OwnerTableView.RenderGroupHeaderItemStyle.BackColor);
				this.AddColorToStyle(cell.Style, "border-left-color", this.Item.OwnerTableView.RenderGroupHeaderItemStyle.BorderColor);
				this.AddColorToStyle(cell.Style, "border-right-color", this.Item.OwnerTableView.RenderGroupHeaderItemStyle.BorderColor);
			}
			cell.MergeStyle(column.ItemStyleInternal);
			if (gridGroupSplitterColumn != null)
			{
				cell.CssClass = string.Empty;
			}
		}

		// Token: 0x04002F33 RID: 12083
		private GridItem _item;
	}
}
