using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x0200124F RID: 4687
	public class TreeListEditFormItem : TreeListEditableItem
	{
		// Token: 0x0600C149 RID: 49481 RVA: 0x002B104C File Offset: 0x002AF24C
		public TreeListEditFormItem(RadTreeList ownerTreeList, TreeListDataItem parentItem, bool isDataBinding) : base(ownerTreeList, TreeListItemType.EditFormItem, isDataBinding)
		{
			if (parentItem != null)
			{
				this.ParentItem = parentItem;
				if (this.ParentItem.IsInEditMode && base.GetType() == typeof(TreeListEditFormItem))
				{
					parentItem.EditFormItem = this;
				}
			}
			this._editorCells = new List<TreeListEditFormItem.EditFormTableCell>();
		}

		// Token: 0x17003E55 RID: 15957
		// (get) Token: 0x0600C14A RID: 49482 RVA: 0x002B10B1 File Offset: 0x002AF2B1
		public override bool IsInEditMode
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17003E56 RID: 15958
		// (get) Token: 0x0600C14B RID: 49483 RVA: 0x002B10B4 File Offset: 0x002AF2B4
		// (set) Token: 0x0600C14C RID: 49484 RVA: 0x002B10C1 File Offset: 0x002AF2C1
		public override bool Edit
		{
			get
			{
				return this.ParentItem.Edit;
			}
			set
			{
				if (!value)
				{
					this.ParentItem.Edit = false;
				}
			}
		}

		// Token: 0x17003E57 RID: 15959
		// (get) Token: 0x0600C14D RID: 49485 RVA: 0x002B10D2 File Offset: 0x002AF2D2
		// (set) Token: 0x0600C14E RID: 49486 RVA: 0x002B10DA File Offset: 0x002AF2DA
		public TableCell EditFormCell { get; private set; }

		// Token: 0x17003E58 RID: 15960
		// (get) Token: 0x0600C14F RID: 49487 RVA: 0x002B10E3 File Offset: 0x002AF2E3
		// (set) Token: 0x0600C150 RID: 49488 RVA: 0x002B10EB File Offset: 0x002AF2EB
		public TreeListDataItem ParentItem { get; private set; }

		// Token: 0x17003E59 RID: 15961
		public TableCell this[string columnUniqueName]
		{
			get
			{
				foreach (TreeListEditFormItem.EditFormTableCell editFormTableCell in this._editorCells)
				{
					if (editFormTableCell.ColumnName == columnUniqueName)
					{
						return editFormTableCell;
					}
				}
				throw new ArgumentException(string.Format("Cannot find cell bound to column with unique name '{0}'", columnUniqueName));
			}
		}

		// Token: 0x0600C152 RID: 49490 RVA: 0x002B1160 File Offset: 0x002AF360
		public override void Initialize(IList<TreeListColumn> columns)
		{
			int num = (this.ParentItem != null) ? (this.ParentItem.HierarchyIndex.NestedLevel + 1) : 1;
			for (int i = 0; i < num; i++)
			{
				this.Cells.Add(this.CreateCellObject());
			}
			this.EditFormCell = new TableCell();
			this.EditFormCell.Style.Add("vertical-align", "top");
			this.EditFormCell.CssClass = "rtlCEdit";
			this.Cells.Add(this.EditFormCell);
			this.InitializeEditForm(columns);
			this.CallOnItemCreated();
			if (this.IsDataBinding)
			{
				this.DataBind();
				this.CellsDataBound(columns);
				this.CallOnItemDataBound();
			}
		}

		// Token: 0x0600C153 RID: 49491 RVA: 0x002B1218 File Offset: 0x002AF418
		protected virtual void InitializeEditForm(IList<TreeListColumn> columns)
		{
			this.EditFormCell.Controls.Clear();
			if (base.OwnerTreeList.ResolvedRenderMode == RenderMode.Mobile && base.OwnerTreeList.EditMode == TreeListEditMode.PopUp)
			{
				this.InitializeMobileEditForm(columns);
				return;
			}
			WebControl container = this.CreateEditFormContainer();
			if (base.OwnerTreeList.EditFormSettings.EditFormType == TreeListEditFormType.AutoGenerated)
			{
				this.InitializeAutoGeneratedEditForm(columns, container);
				return;
			}
			if (base.OwnerTreeList.EditFormSettings.EditFormType == TreeListEditFormType.WebUserControl)
			{
				this.InitializeUserControlEditForm(container);
				return;
			}
			if (base.OwnerTreeList.EditFormSettings.EditFormType == TreeListEditFormType.Template)
			{
				this.InitializeTemplateEditForm(container);
			}
		}

		// Token: 0x0600C154 RID: 49492 RVA: 0x002B1354 File Offset: 0x002AF554
		private WebControl CreateEditFormContainer()
		{
			if (base.OwnerTreeList.EditMode == TreeListEditMode.PopUp)
			{
				WebControl popUpPanel = new WebControl(HtmlTextWriterTag.Div);
				popUpPanel.CssClass = "rtlEditForm";
				string runtimeSkin = base.OwnerTreeList.RuntimeSkin;
				if (!string.IsNullOrEmpty(runtimeSkin))
				{
					WebControl popUpPanel2 = popUpPanel;
					popUpPanel2.CssClass = popUpPanel2.CssClass + " RadTreeList_" + runtimeSkin;
				}
				popUpPanel.Style["position"] = "absolute";
				popUpPanel.Style["display"] = "none";
				WebControl webControl = new WebControl(HtmlTextWriterTag.Div);
				webControl.CssClass = "rtlHeader";
				if (base.OwnerTreeList.RenderMode != RenderMode.Lightweight || base.OwnerTreeList.RenderMode != RenderMode.Mobile)
				{
					webControl.Style["height"] = "20px";
				}
				webControl.Style["cursor"] = "move";
				string popUpId = string.Empty;
				string text = (this is ITreeListInsertItem) ? "PIF" : "PEF";
				if (this.ParentItem != null)
				{
					popUpId = string.Format("{0}_{1}__{2}_{3}", new object[]
					{
						base.OwnerTreeList.ClientID,
						text,
						this.ParentItem.HierarchyIndex.NestedLevel,
						this.ParentItem.HierarchyIndex.LevelIndex
					});
				}
				else
				{
					popUpId = string.Format("{0}_{1}", base.OwnerTreeList.ClientID, text);
				}
				popUpPanel.Attributes["id"] = popUpId;
				popUpPanel.Load += delegate(object s, EventArgs e)
				{
					if (this.OwnerTreeList._popUpLocations.ContainsKey(popUpId))
					{
						Pair pair = this.OwnerTreeList._popUpLocations[popUpId];
						popUpPanel.Style["left"] = pair.First.ToString();
						popUpPanel.Style["top"] = pair.Second.ToString();
					}
				};
				if (!base.OwnerTreeList._popUpIds.Contains(popUpId))
				{
					base.OwnerTreeList._popUpIds.Add(popUpId);
				}
				WebControl webControl2 = new WebControl(HtmlTextWriterTag.Div);
				webControl2.Style["float"] = "left";
				string empty = string.Empty;
				string title = this.GetFormCaption();
				Literal literal = new Literal
				{
					ID = "titleLiteral"
				};
				webControl2.Controls.Add(literal);
				if (string.IsNullOrEmpty(base.OwnerTreeList.EditFormSettings.CaptionDataField) || this.DataItem != null)
				{
					literal.Load += delegate(object s, EventArgs a)
					{
						((ITextControl)s).Text = title;
					};
				}
				webControl.Controls.Add(webControl2);
				WebControl webControl3 = new WebControl(HtmlTextWriterTag.Div);
				webControl3.Style["float"] = "right";
				if (base.OwnerTreeList.ResolvedRenderMode == RenderMode.Lightweight || base.OwnerTreeList.ResolvedRenderMode == RenderMode.Mobile)
				{
					ElasticButton elasticButton = new ElasticButton();
					elasticButton.CommandName = "Cancel";
					elasticButton.CausesValidation = false;
					elasticButton.ToolTip = base.OwnerTreeList.EditFormSettings.PopUpSettings.CloseButtonToolTip;
					elasticButton.CssClass = "t-button rtlActionButton rtlClosePopUp";
					elasticButton.FirstSpanClass = "t-font-icon rtlIcon rtlClosePopUpIcon";
					webControl3.Controls.Add(elasticButton);
				}
				else
				{
					LinkButton linkButton = new LinkButton();
					linkButton.CommandName = "Cancel";
					linkButton.CausesValidation = false;
					linkButton.Style["text-decoration"] = "none";
					Image image = new Image();
					image.Style["border"] = "0";
					image.AlternateText = base.OwnerTreeList.EditFormSettings.PopUpSettings.CloseButtonToolTip;
					image.ToolTip = base.OwnerTreeList.EditFormSettings.PopUpSettings.CloseButtonToolTip;
					image.Style["cursor"] = "pointer";
					image.Style["float"] = "left";
					image.ImageUrl = RadAjaxLoadingPanel.GetWebResourceUrl(this.Page, "Telerik.Web.UI.Skins.Default.Grid.Cancel.gif");
					linkButton.Controls.Add(image);
					webControl3.Controls.Add(linkButton);
				}
				webControl.Controls.Add(webControl3);
				WebControl webControl4 = new WebControl(HtmlTextWriterTag.Div);
				webControl4.Style["clear"] = "both";
				webControl4.Style["display"] = "none";
				webControl.Controls.Add(webControl4);
				popUpPanel.Controls.Add(webControl);
				Panel panel = new Panel();
				panel.ScrollBars = base.OwnerTreeList.EditFormSettings.PopUpSettings.ScrollBars;
				if (base.OwnerTreeList.EditFormSettings.PopUpSettings.Width != Unit.Empty)
				{
					popUpPanel.Style["width"] = base.OwnerTreeList.EditFormSettings.PopUpSettings.Width.ToString();
				}
				if (base.OwnerTreeList.EditFormSettings.PopUpSettings.Height != Unit.Empty)
				{
					popUpPanel.Style["height"] = base.OwnerTreeList.EditFormSettings.PopUpSettings.Height.ToString();
				}
				panel.Width = Unit.Percentage(100.0);
				panel.Height = Unit.Percentage(100.0);
				popUpPanel.Controls.Add(panel);
				this.EditFormCell.Controls.Add(popUpPanel);
				return panel;
			}
			WebControl webControl5 = new WebControl(HtmlTextWriterTag.Div);
			webControl5.CssClass = "rtlEditForm";
			this.EditFormCell.Controls.Add(webControl5);
			return webControl5;
		}

		// Token: 0x0600C155 RID: 49493 RVA: 0x002B194C File Offset: 0x002AFB4C
		private void InitializeAutoGeneratedEditForm(IList<TreeListColumn> columns, WebControl container)
		{
			Table table = new Table();
			table.ID = "FormTable";
			AccessibilityHelper.AddSummary(table, base.OwnerTreeList.EditFormSettings.FormMainTableSummary);
			AccessibilityHelper.AddCaption(table, base.OwnerTreeList.EditFormSettings.FormMainTableCaption);
			container.Controls.Add(table);
			AccessibilityHelper.AddAccessibilityRow(table, base.OwnerTreeList.Caption);
			this.mainTableId = table.UniqueID;
			table.MergeStyle(base.OwnerTreeList.EditFormSettings.FormMainTableStyle);
			TableRow tableRow = new TreeListTableRow();
			table.Rows.Add(tableRow);
			TableCell tableCell = this.CreateCellObject();
			tableCell.ColumnSpan = base.OwnerTreeList.EditFormSettings.ColumnsCount;
			tableRow.Cells.Add(tableCell);
			if (base.OwnerTreeList.EditMode != TreeListEditMode.PopUp || base.OwnerTreeList.EditFormSettings.PopUpSettings.ShowCaptionInEditForm)
			{
				tableCell.Text = this.GetFormCaption();
			}
			tableRow.Visible = !string.IsNullOrEmpty(tableCell.Text);
			if (tableRow.Visible)
			{
				tableRow.MergeStyle(base.OwnerTreeList.EditFormSettings.FormCaptionStyle);
			}
			TableRow tableRow2 = new TreeListTableRow();
			table.Rows.Add(tableRow2);
			for (int i = 0; i < base.OwnerTreeList.EditFormSettings.ColumnsCount; i++)
			{
				TableCell tableCell2 = this.CreateCellObject();
				tableCell2.Style.Add("vertical-align", "top");
				tableRow2.Cells.Add(tableCell2);
			}
			TableRow tableRow3 = new GridTableRow();
			table.Rows.Add(tableRow3);
			tableRow3.MergeStyle(base.OwnerTreeList.EditFormSettings.FormTableButtonRowStyle);
			TableCell tableCell3 = this.CreateCellObject();
			tableCell3.ColumnSpan = base.OwnerTreeList.EditFormSettings.ColumnsCount;
			tableRow3.Cells.Add(tableCell3);
			if (base.OwnerTreeList.EditFormSettings.EditColumn.Visible)
			{
				base.OwnerTreeList.EditFormSettings.EditColumn.InitializeEditItemCell(tableCell3, this);
			}
			else
			{
				tableRow3.Visible = false;
			}
			for (int j = 0; j < base.OwnerTreeList.EditFormSettings.ColumnsCount; j++)
			{
				TableCell tableCell4 = table.Rows[2].Cells[j];
				Table table2 = new Table();
				AccessibilityHelper.AddSummary(table2, base.OwnerTreeList.EditFormSettings.AutoGeneratedColumnEditorsTableWrapperSummary);
				AccessibilityHelper.AddCaption(table2, base.OwnerTreeList.EditFormSettings.AutoGeneratedColumnEditorsTableWrapperCaption);
				tableCell4.Controls.Add(table2);
				table2.MergeStyle(base.OwnerTreeList.EditFormSettings.FormTableStyle);
				AccessibilityHelper.AddAccessibilityRow(table2, base.OwnerTreeList.Caption);
				int num = 0;
				int num2 = 0;
				foreach (TreeListColumn treeListColumn in columns)
				{
					TreeListEditableColumn treeListEditableColumn = treeListColumn as TreeListEditableColumn;
					if (treeListEditableColumn == null || !treeListEditableColumn.IsEditable || treeListEditableColumn.EditFormColumnIndex != j)
					{
						num++;
					}
					else
					{
						Style s = (num2 % 2 == 0) ? base.OwnerTreeList.EditFormSettings.FormTableItemStyle : base.OwnerTreeList.EditFormSettings.FormTableAlternatingItemStyle;
						TableRow tableRow4 = new TreeListTableRow();
						table2.Rows.Add(tableRow4);
						tableRow4.MergeStyle(s);
						TableCell tableCell5 = this.CreateCellObject();
						tableRow4.Cells.Add(tableCell5);
						TreeListEditFormItem.EditFormTableCell editFormTableCell = this.CreateCellObject() as TreeListEditFormItem.EditFormTableCell;
						editFormTableCell.ColumnName = treeListColumn.UniqueName;
						tableRow4.Cells.Add(editFormTableCell);
						this._editorCells.Add(editFormTableCell);
						this.InitializeColumnEditor(editFormTableCell, num, treeListEditableColumn);
						string text = string.Format(treeListEditableColumn.EditFormHeaderTextFormat, treeListColumn.HeaderText);
						string editorLabelTargetID = this.GetEditorLabelTargetID(editFormTableCell);
						if (!string.IsNullOrEmpty(editorLabelTargetID))
						{
							tableCell5.Text = string.Format("<label for=\"{0}\">{1}</label>", editorLabelTargetID, text);
						}
						else
						{
							tableCell5.Text = text;
						}
						num++;
						num2++;
					}
				}
			}
		}

		// Token: 0x0600C156 RID: 49494 RVA: 0x002B1D88 File Offset: 0x002AFF88
		private string GetFormCaption()
		{
			if (this is ITreeListInsertItem && !string.IsNullOrEmpty(base.OwnerTreeList.EditFormSettings.InsertCaption))
			{
				return base.OwnerTreeList.EditFormSettings.InsertCaption;
			}
			string text = string.Empty;
			if (!string.IsNullOrEmpty(base.OwnerTreeList.EditFormSettings.CaptionFormatString))
			{
				text = base.OwnerTreeList.EditFormSettings.CaptionFormatString;
			}
			else if (!string.IsNullOrEmpty(base.OwnerTreeList.EditFormSettings.CaptionDataField))
			{
				text = "Edit {0}";
			}
			if (!string.IsNullOrEmpty(base.OwnerTreeList.EditFormSettings.CaptionDataField) && this.DataItem != null)
			{
				return DataBinder.Eval(this.DataItem, base.OwnerTreeList.EditFormSettings.CaptionDataField, text);
			}
			return text;
		}

		// Token: 0x0600C157 RID: 49495 RVA: 0x002B1E50 File Offset: 0x002B0050
		[SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		private string GetEditorLabelTargetID(TableCell container)
		{
			foreach (object obj in container.Controls)
			{
				Control control = (Control)obj;
				if (control.Visible)
				{
					if (control is RadInputControl)
					{
						return ((RadInputControl)control).TextElementID;
					}
					if (control is RadDatePicker)
					{
						return ((RadDatePicker)control).DateInput.TextElementID;
					}
					if (control is RadMonthYearPicker)
					{
						return ((RadMonthYearPicker)control).DateInput.TextElementID;
					}
					if (control is RadComboBox)
					{
						return control.ClientID + "_Input";
					}
					if (control is TextBox || control is HtmlTextArea || control is DropDownList || control is CheckBox || control is RadioButton || control is RadioButtonList)
					{
						return control.ClientID;
					}
				}
			}
			return string.Empty;
		}

		// Token: 0x0600C158 RID: 49496 RVA: 0x002B1F60 File Offset: 0x002B0160
		protected override TableCell CreateCellObject()
		{
			return new TreeListEditFormItem.EditFormTableCell();
		}

		// Token: 0x0600C159 RID: 49497 RVA: 0x002B1F68 File Offset: 0x002B0168
		private void InitializeUserControlEditForm(WebControl container)
		{
			if (this.Page != null)
			{
				Control control = this.Page.LoadControl(base.OwnerTreeList.EditFormSettings.UserControlPath);
				control.ID = "EditFormControl";
				this.TrySetPropetyValueWithReflection(control, "DataItem", this.DataItem);
				container.Controls.Add(control);
			}
		}

		// Token: 0x0600C15A RID: 49498 RVA: 0x002B1FC4 File Offset: 0x002B01C4
		private bool TrySetPropetyValueWithReflection(object target, string propertyName, object value)
		{
			PropertyInfo property = target.GetType().GetProperty(propertyName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
			if (property != null)
			{
				try
				{
					property.SetValue(target, value, new object[0]);
					return true;
				}
				catch
				{
				}
				return false;
			}
			return false;
		}

		// Token: 0x0600C15B RID: 49499 RVA: 0x002B2014 File Offset: 0x002B0214
		private void InitializeTemplateEditForm(WebControl container)
		{
			if (base.OwnerTreeList.EditFormSettings.FormTemplate != null)
			{
				base.OwnerTreeList.EditFormSettings.FormTemplate.InstantiateIn(container);
			}
		}

		// Token: 0x0600C15C RID: 49500 RVA: 0x002B2040 File Offset: 0x002B0240
		private void InitializeMobileEditForm(IList<TreeListColumn> columns)
		{
			ControlCollection controls = this.EditFormCell.Controls;
			TreeListEditFormSettings editFormSettings = base.OwnerTreeList.EditFormSettings;
			if (editFormSettings.EditFormType == TreeListEditFormType.AutoGenerated)
			{
				this.InitializeMobileAutogeneratedForm();
				return;
			}
			if (editFormSettings.EditFormType == TreeListEditFormType.WebUserControl)
			{
				WebControl container = this.CreateEditFormContainer();
				this.InitializeUserControlEditForm(container);
				return;
			}
			if (editFormSettings.EditFormType == TreeListEditFormType.Template)
			{
				WebControl container2 = this.CreateEditFormContainer();
				this.InitializeTemplateEditForm(container2);
			}
		}

		// Token: 0x0600C15D RID: 49501 RVA: 0x002B20A4 File Offset: 0x002B02A4
		private void InitializeMobileAutogeneratedForm()
		{
			TreeListMobileEditView treeListMobileEditView = new TreeListMobileEditView(base.OwnerTreeList, this);
			treeListMobileEditView.ID = "EditView";
			this.EditFormCell.Controls.Add(treeListMobileEditView);
			treeListMobileEditView.EnsureChildControlsCreated();
		}

		// Token: 0x0600C15E RID: 49502 RVA: 0x002B20E0 File Offset: 0x002B02E0
		protected override void CellsDataBound(IList<TreeListColumn> columns)
		{
			if (base.OwnerTreeList.EditFormSettings.EditFormType != TreeListEditFormType.AutoGenerated)
			{
				return;
			}
			if (base.OwnerTreeList.ResolvedRenderMode == RenderMode.Mobile && base.OwnerTreeList.EditMode == TreeListEditMode.PopUp)
			{
				using (IEnumerator<TreeListColumn> enumerator = columns.GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						TreeListColumn treeListColumn = enumerator.Current;
						TreeListTemplateColumn treeListTemplateColumn = treeListColumn as TreeListTemplateColumn;
						if (treeListColumn is TreeListEditableColumn && (treeListTemplateColumn == null || treeListTemplateColumn.IsEditable) && (treeListTemplateColumn == null || !treeListTemplateColumn.ReadOnly))
						{
							this.OnCellDataBound(treeListColumn, this.FindControl("EditView").FindControl(treeListColumn.UniqueName) as TableCell);
						}
					}
					return;
				}
			}
			foreach (TreeListColumn treeListColumn2 in columns)
			{
				TreeListEditableColumn treeListEditableColumn = treeListColumn2 as TreeListEditableColumn;
				if (treeListEditableColumn != null && treeListEditableColumn.IsEditable)
				{
					TreeListEditFormItem.EditFormTableCell editFormTableCell = this[treeListEditableColumn.UniqueName] as TreeListEditFormItem.EditFormTableCell;
					if (editFormTableCell != null)
					{
						this.OnCellDataBound(treeListEditableColumn, editFormTableCell);
					}
				}
			}
		}

		// Token: 0x17003E5A RID: 15962
		// (get) Token: 0x0600C15F RID: 49503 RVA: 0x002B2204 File Offset: 0x002B0404
		public override bool CanExtractValues
		{
			get
			{
				return base.OwnerTreeList.EditFormSettings.EditFormType != TreeListEditFormType.WebUserControl || this.ImplementsIBindableControl(this.FindControl("EditFormControl"));
			}
		}

		// Token: 0x0600C160 RID: 49504 RVA: 0x002B222C File Offset: 0x002B042C
		protected virtual bool ImplementsIBindableControl(Control control)
		{
			return control != null && control.GetType().GetInterface("IBindableControl") != null;
		}

		// Token: 0x0600C161 RID: 49505 RVA: 0x002B224C File Offset: 0x002B044C
		public override void ExtractValues(IDictionary newValues)
		{
			if (base.OwnerTreeList.EditFormSettings.EditFormType == TreeListEditFormType.AutoGenerated)
			{
				base.ExtractValues(newValues);
				return;
			}
			if (base.OwnerTreeList.EditFormSettings.EditFormType == TreeListEditFormType.Template)
			{
				this.ExtractValuesFromTemplate(newValues, base.OwnerTreeList.EditFormSettings.FormTemplate);
				return;
			}
			if (!this.TryExtractValuesFromBindableControl(newValues, this.FindControl("EditFormControl")))
			{
				throw new NotSupportedException("Cannot extract values from item when EditFormType is WebUserControl.");
			}
		}

		// Token: 0x0600C162 RID: 49506 RVA: 0x002B22C0 File Offset: 0x002B04C0
		protected virtual void ExtractValuesFromTemplate(IDictionary newValues, ITemplate templateControl)
		{
			IBindableTemplate bindableTemplate = templateControl as IBindableTemplate;
			if (bindableTemplate != null)
			{
				using (IDictionaryEnumerator enumerator = bindableTemplate.ExtractValues(this).GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						object obj = enumerator.Current;
						DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
						newValues[dictionaryEntry.Key] = dictionaryEntry.Value;
					}
					return;
				}
			}
			throw new NotSupportedException("Cannot extract values from template edit form. IBindableTemplate required.");
		}

		// Token: 0x0600C163 RID: 49507 RVA: 0x002B233C File Offset: 0x002B053C
		protected virtual bool TryExtractValuesFromBindableControl(IDictionary newValues, Control control)
		{
			if (this.ImplementsIBindableControl(control))
			{
				OrderedDictionary orderedDictionary = new OrderedDictionary();
				MethodInfo method = control.GetType().GetMethod("ExtractValues");
				if (method != null)
				{
					method.Invoke(control, new object[]
					{
						orderedDictionary
					});
				}
				foreach (object obj in orderedDictionary)
				{
					DictionaryEntry dictionaryEntry = (DictionaryEntry)obj;
					newValues[dictionaryEntry.Key] = dictionaryEntry.Value;
				}
				return true;
			}
			return false;
		}

		// Token: 0x0600C164 RID: 49508 RVA: 0x002B23E8 File Offset: 0x002B05E8
		public override void PrepareItemStyle()
		{
			this.EditFormCell.ColumnSpan = this.CalculateCellSpan(base.OwnerTreeList.RenderColumns);
			base.PrepareItemStyle();
		}

		// Token: 0x040032DD RID: 13021
		public const string EditFormUserControlID = "EditFormControl";

		// Token: 0x040032DE RID: 13022
		private IList<TreeListEditFormItem.EditFormTableCell> _editorCells;

		// Token: 0x040032DF RID: 13023
		private string mainTableId = string.Empty;

		// Token: 0x02001250 RID: 4688
		internal class EditFormTableCell : TableCell
		{
			// Token: 0x17003E5B RID: 15963
			// (get) Token: 0x0600C165 RID: 49509 RVA: 0x002B240C File Offset: 0x002B060C
			// (set) Token: 0x0600C166 RID: 49510 RVA: 0x002B242C File Offset: 0x002B062C
			public string ColumnName
			{
				get
				{
					return (this.ViewState["ColumnName"] as string) ?? string.Empty;
				}
				set
				{
					this.ViewState["ColumnName"] = value;
				}
			}
		}
	}
}
