using System;
using System.Collections;
using System.ComponentModel;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Telerik.Web.UI
{
	// Token: 0x0200126B RID: 4715
	public class TreeListEditFormSettings : StateManager
	{
		// Token: 0x0600C41D RID: 50205 RVA: 0x002BEBB0 File Offset: 0x002BCDB0
		public TreeListEditFormSettings(RadTreeList owner)
		{
			this._ownerTreeList = owner;
			this.FormStyle = new Style(base.ViewState);
			this.FormMainTableStyle = new TableStyle(base.ViewState);
			this.FormTableStyle = new TableStyle(base.ViewState);
			this.FormCaptionStyle = new TableItemStyle(base.ViewState);
			this.FormTableItemStyle = new TableItemStyle(base.ViewState);
			this.FormTableAlternatingItemStyle = new TableItemStyle(base.ViewState);
			this.FormTableButtonRowStyle = new TableItemStyle(base.ViewState);
		}

		// Token: 0x17003F2B RID: 16171
		// (get) Token: 0x0600C41E RID: 50206 RVA: 0x002BEC41 File Offset: 0x002BCE41
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Set properties of the update-cancel buttons column that appears in an edit form")]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		public TreeListEditCommandColumn EditColumn
		{
			get
			{
				if (this._editColumn == null)
				{
					this._editColumn = new TreeListEditCommandColumn();
					this._editColumn.SetOwner(this._ownerTreeList);
				}
				return this._editColumn;
			}
		}

		// Token: 0x17003F2C RID: 16172
		// (get) Token: 0x0600C41F RID: 50207 RVA: 0x002BEC70 File Offset: 0x002BCE70
		// (set) Token: 0x0600C420 RID: 50208 RVA: 0x002BEC9E File Offset: 0x002BCE9E
		[Description("Number of vertical columns to split all edit fields on the form when it is autogenerated.")]
		[DefaultValue(1)]
		[NotifyParentProperty(true)]
		public int ColumnsCount
		{
			get
			{
				object obj = base.ViewState["ColumnsCount"];
				if (obj == null)
				{
					obj = 1;
				}
				return (int)obj;
			}
			set
			{
				if (value <= 0)
				{
					throw new Exception("The columns count must be greater than 1");
				}
				base.ViewState["ColumnsCount"] = value;
			}
		}

		// Token: 0x17003F2D RID: 16173
		// (get) Token: 0x0600C421 RID: 50209 RVA: 0x002BECC5 File Offset: 0x002BCEC5
		// (set) Token: 0x0600C422 RID: 50210 RVA: 0x002BECE5 File Offset: 0x002BCEE5
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public virtual string CaptionDataField
		{
			get
			{
				return (base.ViewState["CaptionDataField"] as string) ?? string.Empty;
			}
			set
			{
				base.ViewState["CaptionDataField"] = value;
			}
		}

		// Token: 0x17003F2E RID: 16174
		// (get) Token: 0x0600C423 RID: 50211 RVA: 0x002BECF8 File Offset: 0x002BCEF8
		// (set) Token: 0x0600C424 RID: 50212 RVA: 0x002BED18 File Offset: 0x002BCF18
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public virtual string CaptionFormatString
		{
			get
			{
				return (base.ViewState["CaptionFormatString"] as string) ?? string.Empty;
			}
			set
			{
				base.ViewState["CaptionFormatString"] = value;
			}
		}

		// Token: 0x17003F2F RID: 16175
		// (get) Token: 0x0600C425 RID: 50213 RVA: 0x002BED2B File Offset: 0x002BCF2B
		// (set) Token: 0x0600C426 RID: 50214 RVA: 0x002BED4B File Offset: 0x002BCF4B
		[NotifyParentProperty(true)]
		[DefaultValue("")]
		public virtual string InsertCaption
		{
			get
			{
				return (base.ViewState["InsertCaption"] as string) ?? string.Empty;
			}
			set
			{
				base.ViewState["InsertCaption"] = value;
			}
		}

		// Token: 0x17003F30 RID: 16176
		// (get) Token: 0x0600C427 RID: 50215 RVA: 0x002BED60 File Offset: 0x002BCF60
		// (set) Token: 0x0600C428 RID: 50216 RVA: 0x002BED98 File Offset: 0x002BCF98
		[DefaultValue(typeof(GridEditFormType), "AutoGenerated")]
		[NotifyParentProperty(true)]
		public TreeListEditFormType EditFormType
		{
			get
			{
				object obj = base.ViewState["EditFormType"];
				if (obj != null)
				{
					return (TreeListEditFormType)base.ViewState["EditFormType"];
				}
				return TreeListEditFormType.AutoGenerated;
			}
			set
			{
				base.ViewState["EditFormType"] = value;
			}
		}

		// Token: 0x17003F31 RID: 16177
		// (get) Token: 0x0600C429 RID: 50217 RVA: 0x002BEDB0 File Offset: 0x002BCFB0
		// (set) Token: 0x0600C42A RID: 50218 RVA: 0x002BEDD0 File Offset: 0x002BCFD0
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public string UserControlPath
		{
			get
			{
				return (base.ViewState["UserControlPath"] as string) ?? string.Empty;
			}
			set
			{
				base.ViewState["UserControlPath"] = value;
			}
		}

		// Token: 0x17003F32 RID: 16178
		// (get) Token: 0x0600C42B RID: 50219 RVA: 0x002BEDE4 File Offset: 0x002BCFE4
		// (set) Token: 0x0600C42C RID: 50220 RVA: 0x002BEE11 File Offset: 0x002BD011
		[Description("The summary attribute for the table that wraps the whole TreeListEditFormItem")]
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public string FormMainTableSummary
		{
			get
			{
				object obj = base.ViewState["FormMainTableSummary"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				base.ViewState["FormMainTableSummary"] = value;
			}
		}

		// Token: 0x17003F33 RID: 16179
		// (get) Token: 0x0600C42D RID: 50221 RVA: 0x002BEE24 File Offset: 0x002BD024
		// (set) Token: 0x0600C42E RID: 50222 RVA: 0x002BEE51 File Offset: 0x002BD051
		[DefaultValue("")]
		[Description("The caption for the table that wraps the whole TreeListEditFormItem")]
		[NotifyParentProperty(true)]
		public string FormMainTableCaption
		{
			get
			{
				object obj = base.ViewState["FormMainTableCaption"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				base.ViewState["FormMainTableCaption"] = value;
			}
		}

		// Token: 0x17003F34 RID: 16180
		// (get) Token: 0x0600C42F RID: 50223 RVA: 0x002BEE64 File Offset: 0x002BD064
		// (set) Token: 0x0600C430 RID: 50224 RVA: 0x002BEE91 File Offset: 0x002BD091
		[DefaultValue("")]
		[Description("The summary attribute for the table which holds all cells created from the grid column editors TreeListColumnEditor")]
		[NotifyParentProperty(true)]
		public string AutoGeneratedColumnEditorsTableWrapperSummary
		{
			get
			{
				object obj = base.ViewState["AutoGeneratedColumnEditorsTableWrapperSummary"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				base.ViewState["AutoGeneratedColumnEditorsTableWrapperSummary"] = value;
			}
		}

		// Token: 0x17003F35 RID: 16181
		// (get) Token: 0x0600C431 RID: 50225 RVA: 0x002BEEA4 File Offset: 0x002BD0A4
		// (set) Token: 0x0600C432 RID: 50226 RVA: 0x002BEED1 File Offset: 0x002BD0D1
		[Description("The caption for the table which holds all cells created from the grid column editors TreeListColumnEditor")]
		[DefaultValue("")]
		[NotifyParentProperty(true)]
		public string AutoGeneratedColumnEditorsTableWrapperCaption
		{
			get
			{
				object obj = base.ViewState["AutoGeneratedColumnEditorsTableWrapperCaption"];
				if (obj != null)
				{
					return (string)obj;
				}
				return string.Empty;
			}
			set
			{
				base.ViewState["AutoGeneratedColumnEditorsTableWrapperCaption"] = value;
			}
		}

		// Token: 0x17003F36 RID: 16182
		// (get) Token: 0x0600C433 RID: 50227 RVA: 0x002BEEE4 File Offset: 0x002BD0E4
		// (set) Token: 0x0600C434 RID: 50228 RVA: 0x002BEEEC File Offset: 0x002BD0EC
		[TemplateContainer(typeof(TreeListEditFormItem), BindingDirection.TwoWay)]
		[Browsable(false)]
		[DefaultValue(null)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		public virtual ITemplate FormTemplate { get; set; }

		// Token: 0x17003F37 RID: 16183
		// (get) Token: 0x0600C435 RID: 50229 RVA: 0x002BEEF5 File Offset: 0x002BD0F5
		// (set) Token: 0x0600C436 RID: 50230 RVA: 0x002BEEFD File Offset: 0x002BD0FD
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		[Description("Style of the edit form container in TreeListEditFormItem.")]
		public Style FormStyle { get; private set; }

		// Token: 0x17003F38 RID: 16184
		// (get) Token: 0x0600C437 RID: 50231 RVA: 0x002BEF06 File Offset: 0x002BD106
		// (set) Token: 0x0600C438 RID: 50232 RVA: 0x002BEF0E File Offset: 0x002BD10E
		[Description("Style of the forms' main table element")]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		public TableStyle FormMainTableStyle { get; private set; }

		// Token: 0x17003F39 RID: 16185
		// (get) Token: 0x0600C439 RID: 50233 RVA: 0x002BEF17 File Offset: 0x002BD117
		// (set) Token: 0x0600C43A RID: 50234 RVA: 0x002BEF1F File Offset: 0x002BD11F
		[Description("Style of the edit form's table element in TreeListEditFormItem.")]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		public TableStyle FormTableStyle { get; private set; }

		// Token: 0x17003F3A RID: 16186
		// (get) Token: 0x0600C43B RID: 50235 RVA: 0x002BEF28 File Offset: 0x002BD128
		// (set) Token: 0x0600C43C RID: 50236 RVA: 0x002BEF30 File Offset: 0x002BD130
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the edit form table row that shows the caption.")]
		[NotifyParentProperty(true)]
		public TableItemStyle FormCaptionStyle { get; private set; }

		// Token: 0x17003F3B RID: 16187
		// (get) Token: 0x0600C43D RID: 50237 RVA: 0x002BEF39 File Offset: 0x002BD139
		// (set) Token: 0x0600C43E RID: 50238 RVA: 0x002BEF41 File Offset: 0x002BD141
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the edit form table rows.")]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		public TableItemStyle FormTableItemStyle { get; private set; }

		// Token: 0x17003F3C RID: 16188
		// (get) Token: 0x0600C43F RID: 50239 RVA: 0x002BEF4A File Offset: 0x002BD14A
		// (set) Token: 0x0600C440 RID: 50240 RVA: 0x002BEF52 File Offset: 0x002BD152
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[Description("Style of the alternating rows in the edit form table.")]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		public TableItemStyle FormTableAlternatingItemStyle { get; private set; }

		// Token: 0x17003F3D RID: 16189
		// (get) Token: 0x0600C441 RID: 50241 RVA: 0x002BEF5B File Offset: 0x002BD15B
		// (set) Token: 0x0600C442 RID: 50242 RVA: 0x002BEF63 File Offset: 0x002BD163
		[Description("Style of the edit form table's footer row, where the Update/Insert/Cancel buttons appear.")]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		[NotifyParentProperty(true)]
		public TableItemStyle FormTableButtonRowStyle { get; private set; }

		// Token: 0x17003F3E RID: 16190
		// (get) Token: 0x0600C443 RID: 50243 RVA: 0x002BEF6C File Offset: 0x002BD16C
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[NotifyParentProperty(true)]
		[PersistenceMode(PersistenceMode.InnerProperty)]
		public TreeListPopUpSettings PopUpSettings
		{
			get
			{
				if (this._popUpSettings == null)
				{
					this._popUpSettings = new TreeListPopUpSettings(this._ownerTreeList);
					if (this.IsTrackingViewState)
					{
						((IStateManager)this._popUpSettings).TrackViewState();
					}
				}
				return this._popUpSettings;
			}
		}

		// Token: 0x0600C444 RID: 50244 RVA: 0x002BEFA0 File Offset: 0x002BD1A0
		protected override object SaveViewState()
		{
			return new ArrayList
			{
				base.SaveViewState(),
				((IStateManager)this.PopUpSettings).SaveViewState()
			}.ToArray(typeof(object));
		}

		// Token: 0x0600C445 RID: 50245 RVA: 0x002BEFE4 File Offset: 0x002BD1E4
		protected override void LoadViewState(object savedState)
		{
			if (savedState != null)
			{
				object[] array = (object[])savedState;
				int num = 0;
				base.LoadViewState(array[num++]);
				((IStateManager)this.PopUpSettings).LoadViewState(array[num++]);
			}
		}

		// Token: 0x0600C446 RID: 50246 RVA: 0x002BF01C File Offset: 0x002BD21C
		protected override void TrackViewState()
		{
			if (this.IsTrackingViewState)
			{
				base.TrackViewState();
				return;
			}
			base.TrackViewState();
			((IStateManager)this.PopUpSettings).TrackViewState();
		}

		// Token: 0x040033F8 RID: 13304
		private RadTreeList _ownerTreeList;

		// Token: 0x040033F9 RID: 13305
		private TreeListEditCommandColumn _editColumn;

		// Token: 0x040033FA RID: 13306
		private TreeListPopUpSettings _popUpSettings;
	}
}
