using System;

namespace Telerik.Web.UI
{
	// Token: 0x02001267 RID: 4711
	public class TreeListAutoGeneratedColumnCreatedEventArgs : EventArgs
	{
		// Token: 0x0600C3C7 RID: 50119 RVA: 0x002BE384 File Offset: 0x002BC584
		public TreeListAutoGeneratedColumnCreatedEventArgs(TreeListColumn column)
		{
			this.Column = column;
		}

		// Token: 0x17003F03 RID: 16131
		// (get) Token: 0x0600C3C8 RID: 50120 RVA: 0x002BE393 File Offset: 0x002BC593
		// (set) Token: 0x0600C3C9 RID: 50121 RVA: 0x002BE39B File Offset: 0x002BC59B
		public TreeListColumn Column { get; internal set; }
	}
}
