using System;

namespace Telerik.Web.UI
{
	// Token: 0x0200126C RID: 4716
	public enum TreeListEditFormType
	{
		// Token: 0x04003404 RID: 13316
		AutoGenerated,
		// Token: 0x04003405 RID: 13317
		WebUserControl,
		// Token: 0x04003406 RID: 13318
		Template
	}
}
