(function(a,A){var b=Telerik.Web.UI;
var u=window.kendo;
var z=u.ui;
var p=z.Gantt;
var q=z.GanttList;
var o=a.extend;
var k="radCalendar";
var l="radDatePicker";
var m="radDateTimePicker";
var w="radNumericTextbox";
var x="radTextbox";
var r={wrapper:"RadGantt k-gantt",plannedTasks:"rgtPlanned k-gantt-planned",content:"rgtContent",rowHeight:"rgtRowheight",listWrapper:"rgtTreelistWrapper",list:"rgtTreelistWrapper",timelineWrapper:"rgtTimelineWrapper",timeline:"rgtTimelineWrapper",splitBarWrapper:"rgtSplitbar",splitBar:"rgtSplitbar",splitBarHover:"rgtSplitbarHover",popupWrapper:"radPopup",popupList:"radList",resizeHandle:"radResizeHandle",icon:"radIcon",item:"radItem",line:"radLine",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"radPrimary",hovered:"radStateHovered",selected:"radStateSelected",focused:"radStateFocused",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"radGridContent",tasks:"rgtTasks k-gantt-tasks",popup:{form:"radPopupEditForm",editForm:"rgtEditForm",formContainer:"radEditFormContainer",resourcesFormContainer:"radResourceFormContainer",message:"radPopupMessage",buttonsContainer:"rgtButtonsContainer",button:"radButton",editField:"radFormField",editLabel:"radFormLabel",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"rgtToolbar rgtHeader",footerWrapper:"rgtToolbar rgtFooter",toolbar:"rgtToolbar",expanded:"rgtExpanded",views:"rgtViews",viewsWrapper:"radToolbar rgtViews",actions:"rgtActions",button:"radButton",buttonToggle:"radButton radButtonIcon k-gantt-toggle",iconPlus:"radIcon radIconPlus",iconPdf:"radIcon radIconPdf",iconToggle:"radIcon k-i-gantt-toggle",viewButtonDefault:"radStateDefault",viewButton:"rgtViewButton",currentView:"rgtCurrentView",link:"radButton",pdfButton:"rgtPdfButton",appendButton:"rgtCreateButton"}};
o(true,z.Gantt,{styles:r});
var v={wrapper:"radGrid rgtTreelist",header:"radHeader",alt:"radAlt",editCell:"k-edit-cell",group:"rgtTreelistGroup",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTreelistContent",gridContentWrap:"rgtTreelistContent",selected:"radStateSelected",icon:"radIcon",iconCollapse:"radIconCollapse",iconExpand:"radIconExpand",iconHidden:"radIconNone",iconPlaceHolder:"radIcon radIconNone",input:"k-input",link:"k-link",resizeHandle:"k-resize-handle",resizeHandleInner:"k-resize-handle-inner",dropPositions:"radIconInsertTop radIconInsertBottom radIconAdd radIconInsertMiddle",dropTop:"radIconInsertTop",dropBottom:"radIconInsertBottom",dropAdd:"radIconAdd",dropMiddle:"radIconInsertMiddle",dropDenied:"radIconDenied",dragStatus:"radDragStatus",dragClue:"radDragClue",dragClueText:"radDragClueText"};
o(true,z.GanttList,{listStyles:v,styles:v});
o(true,z.TreeList,{classNames:v});
var B={alt:"radAlt",reset:"k-reset",nonWorking:"radNonwork",header:"radHeader",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTimelineContent",tasksWrapper:"rgtTables",rowsTable:"radFauxRows",columnsTable:"radFauxColumns",tasksTable:"rgtTasks",dependenciesWrapper:"rgtDependencies",resource:"rgtResource",resourceAlt:"rgtResource radAlt",task:"rgtTask",taskSingle:"rgtTaskSingle",taskMilestone:"rgtTaskMilestone",taskSummary:"rgtTaskSummary",taskWrap:"rgtTaskWrap",taskMilestoneWrap:"rgtMilestoneWrap",resourcesWrap:"rgtResourceWrap",taskDot:"rgtTaskDot",taskDotStart:"rgtTaskStart",taskDotEnd:"rgtTaskEnd",taskDragHandle:"rgtDragHandle",taskContent:"rgtTaskContent",taskTemplate:"rgtTaskTemplate",taskActions:"rgtTaskActions",taskDelete:"rgtTaskDelete",taskComplete:"rgtTaskComplete",taskDetails:"rgtTaskDetails",taskDetailsPercent:"rgtTaskPct",link:"radButton",icon:"radIcon",iconDelete:"radIconDelete",taskResizeHandle:"radResizeHandle",taskResizeHandleWest:"radResizeW",taskResizeHandleEast:"radResizeE",taskSummaryProgress:"rgtProgress",taskSummaryComplete:"rgtComplete",line:"radLine",lineHorizontal:"radLineH",lineVertical:"radLineV",arrowWest:"radArrowW",arrowEast:"radArrowE",dragHint:"radDragHint",dependencyHint:"rgtDependencyHint",tooltipWrapper:"radTooltip",tooltipContent:"radTooltipContent",tooltipCallout:"radCallout radCalloutS",callout:"radCallout",marquee:"radMarquee",marqueeColor:"radMarqueeColor"};
o(true,z.GanttView,{styles:B});
var y={wrapper:"radGrid rgtTimeline",gridHeader:"radGridHeader",gridHeaderWrap:"radGridHeaderWrap",gridContent:"rgtTimelineContent",gridContentWrap:"rgtTimelineContent radGridContent",tasksWrapper:"rgtTables",dependenciesWrapper:"rgtDependencies",task:"rgtTask",line:"radLine",taskResizeHandle:"radResizeHandle",taskResizeHandleWest:"radResizeW",taskDragHandle:"rgtDragHandle",taskDelete:"rgtTaskDelete",taskComplete:"rgtTaskComplete",taskWrapActive:"rgtTaskWrapActive",taskWrap:"rgtTaskWrap",taskDot:"rgtTaskDot",taskDotStart:"rgtTaskStart",taskDotEnd:"rgtTaskEnd",hovered:"radStateHovered",selected:"radStateSelected",origin:"radOrigin"};
o(true,z.GanttTimeline,{styles:y});
function j(G){var F=p.styles;
var C=function(){var H=G.dateView;
H.div.addClass(F.popupWrapper);
H.calendar.wrapper.addClass(k);
};
var E=function(){G.timeView.list.addClass(F.popupWrapper);
};
var D=function(H){G.wrapper.addClass(H);
};
if(G){if(G instanceof z.DatePicker){D(l);
G.bind("open",function(){C();
},true);
}else{if(G instanceof z.DateTimePicker){D(m);
G.bind("open",function(H){if(H.view==="time"){E();
}else{C();
}});
}else{if(G instanceof z.NumericTextBox){D(w);
}}}}}function s(){return b.MaterialRippleManager.getInstance();
}function t(E,C){var D=s();
if(D){var F=D._rippleDelegatedZones;
if(F.indexOf(E.element.get(0))!==-1&&F.indexOf(C)===-1){D.initializeRippleZone({element:C,rippleConfigurations:[{containerSelector:".radButton, .radItem, .k-button, .k-dropdown-wrap, .k-filterable, .k-item"},{containerSelector:".k-grid-filter",rippleType:b.MaterialRippleType.Icon,maxRippleSize:60,cancelBubble:true}]});
}}}function n(C){var D=s();
if(D){D.disposeRippleZone(C);
}}var g=p.fn.editTask;
p.fn.editTask=function(D){g.call(this,D);
var C=this._editor.container;
t(this,C.parent().get(0));
C.parent().addClass("radSkin_"+this.options.skin);
var E=C.find("input[data-role]");
E.each(function(G,F){var H=u.widgetInstance($telerik.$(F));
if(H){j(H);
}});
C.find("input[name='title']").addClass(x);
};
var c=p.fn._createPlannedTasksSwitch;
p.fn._createPlannedTasksSwitch=function(){c.call(this);
var C=this.options.skin;
this.toggleSwitch.wrapper.addClass("RadSwitch_"+C);
};
var h=p.fn._onDialogClose;
p.fn._onDialogClose=function(C){n(C.window.parent().get(0));
h.call(this,C);
};
var i=p.fn.showDialog;
p.fn.showDialog=function(D){i.call(this,D);
var C=this._editor.popup.element;
t(this,C.parent().get(0));
this._editor.popup.bind("close",function(E){n(E.sender.element.parent().get(0));
});
C.parent().addClass("radSkin_"+this.options.skin);
};
var e=p.fn._dropDowns;
p.fn._dropDowns=function(){var D=this;
var C=function(E){t(D,this.element.get(0));
};
e.call(this);
if(this.footerDropDown){this.footerDropDown.popup.bind("open",C);
}if(this.headerDropDown){this.headerDropDown.popup.bind("open",C);
}};
var f=q.fn._editCell;
q.fn._editCell=function(C,D,E){f.call(this,C,D,E);
if(this.editable==false){return;
}var F=u.widgetInstance(C.find("input[data-role]"));
if(F){j(F);
}else{C.children("input").addClass(x);
}};
var d=p.fn._createResourceEditor;
p.fn._createResourceEditor=function(C,D){var E=this;
d.call(this,C,D);
var F=this._resourceEditor.window.wrapper;
this._resourceEditor.window.bind("close",function(G){n(G.sender.element.parent().get(0));
});
t(E,F[0]);
F.addClass("radSkin_"+this.options.skin);
this._resourceEditor.grid.bind("filterMenuInit",function(J){var G=J.container;
var K=G.data("kendoPopup");
var I=G.find("[data-role=dropdownlist]");
G.addClass("radSkin_"+E.options.skin);
K.bind("open",function(M){t(E,M.sender.element.get(0));
});
K.bind("close",function(M){n(M.sender.element.get(0));
});
for(var L=0;
L<I.length;
L++){var H=a(I[L]).data("kendoDropDownList");
H.bind("open",function(M){t(E,M.sender.list.get(0));
});
H.bind("close",function(M){n(M.sender.list.get(0));
});
}});
};
})(window.kendo.jQuery);
(function(a,l){$telerik.findGantt=$find;
$telerik.toGantt=function(o){return o;
};
Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.Gantt");
var c=Telerik.Web.UI;
var b=Sys.Serialization.JavaScriptSerializer;
var e="__EVENTVALIDATION";
var m="__VIEWSTATE";
var i="load";
var j=function(o){return o.d||o;
};
var h=window.kendo;
var f=h.ui.Gantt;
var g=h.ui.GanttList;
a.registerEnum(c,"GanttViewType",{Day:0,Week:1,Month:2,Year:3});
var d=c.Gantt={commands:{create:{task:"InsertTask",dependency:"InsertDependency",assignment:"InsertAssignment"},destroy:{task:"DeleteTask",dependency:"DeleteDependency",assignment:"DeleteAssignment"},update:{task:"UpdateTask",dependency:"UpdateDependency",assignment:"UpdateAssignment"},itemChange:{task:"UpdateTask",dependency:"UpdateDependency",assignment:"UpdateAssignment"}},transportProxy:function(q){this._data=q.data;
this._id=q.id;
this._type=q.type;
this._commandsCache=q.commandsCache;
var r=this;
var o=c.Gantt.commands;
var p=function(z){var u=z.cmd;
var y=u.indexOf("Task")>-1;
if(z.args.length){var s=z.args[0];
var v=s.data.models||s.data;
if(y){var w=function(B){var A=new Date(B);
A.setMinutes(A.getMinutes()-A.getTimezoneOffset());
return A;
};
for(var x=0;
x<v.length;
x++){v[x].Start=w(v[x].Start);
if(v[x].PlannedStart){v[x].PlannedStart=w(v[x].PlannedStart);
}v[x].End=w(v[x].End);
if(v[x].PlannedEnd){v[x].PlannedEnd=w(v[x].PlannedEnd);
}}}if(!(v instanceof Array)){v=[a.extend({},v)];
}if(r._postBack){r._commandsCache[u]=v;
}else{var t=c.Gantt.callbackCommand({cmd:u,data:v,type:r._type});
c.Gantt.request({id:r._id,cmd:t},function(){if(y){var A=arguments[0];
for(var B=0;
B<A.length;
B++){A[B].Start=new Date(A[B].Start);
if(A[B].PlannedStart){A[B].PlannedStart=new Date(A[B].PlannedStart);
}A[B].End=new Date(A[B].End);
if(A[B].PlannedEnd){A[B].PlannedEnd=new Date(A[B].PlannedEnd);
}}}s.success.apply(this,arguments);
},s.fail);
}}};
this.set_postback=function(s){r._postBack=s;
};
this.read=function(){var s=r._data;
if(s&&r._type==="task"){for(var t=0;
t<s.length;
t++){s[t].Start=new Date(s[t].Start);
if(s[t].PlannedStart){s[t].PlannedStart=new Date(s[t].PlannedStart);
}s[t].End=new Date(s[t].End);
if(s[t].PlannedEnd){s[t].PlannedEnd=new Date(s[t].PlannedEnd);
}}}arguments[0].success(r._data);
};
this.create=function(){p({args:arguments,cmd:o.create[r._type]});
};
this.update=function(){p({args:arguments,cmd:o.update[r._type]});
};
this.destroy=function(){p({args:arguments,cmd:o.destroy[r._type]});
};
},transport:function(q){var r=q.path.lastIndexOf("/")===q.path.length-1?q.path:q.path+"/";
var t=q.type;
var p=q.methods;
var s={parameterMap:function(v,u){if(u!=="read"){return b.serialize({models:(v.models||[v])});
}}};
for(var o in p){s[o]={url:r+p[o],type:t,dataType:"json",contentType:"application/json"};
}return s;
},request:function(p,q,o){a.ajax(c.Gantt.transportCallbackParams(p)).done(q).fail(o);
},callbackCommand:function(p){var q={commandName:p.cmd};
var o={task:"tasks",dependency:"dependencies",assignment:"assignments"};
q[o[p.type]]=p.data;
return q;
},transportCallbackParams:function(q){var o=$get(e);
var p=o?o.value:"";
var r=$get(m);
var s=r?r.value:"";
return{url:window.location,data:{__EVENTTARGET:"",__EVENTARGUMENT:"",__VIEWSTATE:s,__CALLBACKID:q.id,__CALLBACKPARAM:b.serialize(q.cmd),__EVENTVALIDATION:p},type:"POST",dataType:"JSON",converters:{"text json":c.Gantt.callbackConverter}};
},callbackConverter:function(p){var o=p.split("|")[1];
return a.parseJSON(o);
},createDependency:function(p,q,r){var o=new c.GanttDependency();
o._loadFromDictionary({predecessorId:p,successorId:q,type:r});
return o;
},createAssignment:function(q,p,r){var o=new c.GanttAssignment();
o._loadFromDictionary({TaskID:q,ResourceID:p,Units:r});
return o;
}};
var n=function(o){for(var p in o){this["set_"+p](o[p]);
}};
a.registerControlProperties(n,{path:"",useHttpGet:false,method:"GetTasks",deleteTasksMethod:"DeleteTasks",insertTasksMethod:"InsertTasks",updateTasksMethod:"UpdateTasks",getDependenciesMethod:"GetDependencies",deleteDependenciesMethod:"DeleteDependencies",insertDependenciesMethod:"InsertDependencies",getResourcesMethod:"GetResources",getAssignmentsMethod:"GetAssignments",insertAssignmentsMethod:"InsertAssignments",updateAssignmentsMethod:"UpdateAssignments",deleteAssignmentsMethod:"DeleteAssignments"});
c.RadGantt=function(o){c.RadGantt.initializeBase(this,[o]);
this._widget=null;
this._webServiceSettings=null;
this._postBackReference=null;
this._skin="Default";
this._uniqueId=null;
this._postBackOnNavigate=false;
this._postBackOnTaskInsert=false;
this._postBackOnTaskUpdate=false;
this._postBackOnTaskDelete=false;
this._postBackOnDependencyInsert=false;
this._postBackOnDependencyDelete=false;
this._postBackOnAssignmentInsert=false;
this._postBackOnAssignmentUpdate=false;
this._postBackOnAssignmentDelete=false;
this._commandsCache={};
this._navigationSettings={};
this._scrollTop=0;
this._scrollLeft=0;
};
c.RadGantt.prototype={initialize:function(){c.RadGantt.callBaseMethod(this,"initialize");
this._extendStyles();
this.initializePdfSettings();
this.initializeWidget();
this.initializeCustomFields();
this._initializePostback();
this._initializeKeyboardNavigation();
this._initializeScroll();
this.add_parentShown(this.get_element());
this.raiseEvent(i);
},initializePdfSettings:function(){var p=this.get_pdfSettings();
if(p){if(p.date){var o=parseInt(p.date.match(/\d+/)[0],10);
p.date=new Date(o);
}if(p.margin){p.margin=a.parseJSON(p.margin);
}if(p.fonts){p.fonts=a.parseJSON(p.fonts);
h.pdf.defineFont(p.fonts);
}}},initializeWidget:function(){var p=this;
var o=this.widget();
p.raiseEvent("kendoWidgetInitializing",o);
this._widget=a(this.get_element()).kendoGantt(o).data("kendoGantt");
this._widget.timeline.bind("navigate",function(q){p.updateClientState();
});
},initializeCustomFields:function(){var o=function(s){var t=c.GanttTask;
t.prototype["get_"+s]=function(){return this._data[s];
};
t.prototype["set_"+s]=function(v){var u={};
u[s]=v;
this._data[s]=v;
this._update(u);
};
};
var p=this.get_customTaskFields();
for(var q=0,r=p.length;
q<r;
q++){o(p[q].clientPropertyName);
}},_initializeScroll:function(){var p=this;
var o=a(this.get_element()).find(".rgtTimelineContent");
o.on("scroll",function(q){p._scrollTop=a(this).scrollTop();
p._scrollLeft=h.scrollLeft(this);
p.updateClientState();
}).scrollTop(this.get_scrollTop());
if(!p.get_selectedDate()&&!this._widget.view().options.date){h.scrollLeft(o,this.get_scrollLeft());
}},dispose:function(){this.disposeWidget();
this._disposeScroll();
this._disposeKeyboardNavigation();
c.RadGantt.callBaseMethod(this,"dispose");
},disposeWidget:function(){this._widget.destroy();
},_disposeScroll:function(){a(".rgtTimelineContent").off("scroll");
},proxy:function(p,o){var r=this.get_webServiceSettings();
var q;
if(r){q={task:{read:r.get_method(),update:r.get_updateTasksMethod(),destroy:r.get_deleteTasksMethod(),create:r.get_insertTasksMethod()},dependency:{read:r.get_getDependenciesMethod(),destroy:r.get_deleteDependenciesMethod(),create:r.get_insertDependenciesMethod()},assignment:{read:r.get_getAssignmentsMethod(),update:r.get_updateAssignmentsMethod(),destroy:r.get_deleteAssignmentsMethod(),create:r.get_insertAssignmentsMethod()}};
return d.transport({path:r.get_path(),type:r.get_useHttpGet()?"GET":"POST",methods:q[p]});
}else{return new c.Gantt.transportProxy({data:this[o](),id:this._uniqueId,type:p,commandsCache:this._commandsCache});
}},widget:function(){var q=this;
var o=!this.get_readOnly();
if(o){o=this._getEditableOpitons();
}var p={dataSource:this.tasksDataSource(),date:this.get_selectedDate(),dependencies:this.dependenciesDataSource(),autoBind:true,selectable:!this.get_readOnly(),editable:o,showPlannedTasks:this.get_showPlannedTasks(),toolbar:this.get_toolbarSettings(),currentTimeMarker:this.currentTimeMarker(),messages:this.get_localization(),showWorkHours:!this.get_showFullTime(),showWorkDays:!this.get_showFullWeek(),workWeekStart:this.get_workWeekStart(),workWeekEnd:this.get_workWeekEnd(),tooltip:this.get_tooltip(),hourSpan:this.get_hourSpan(),snap:this.get_snapToGrid(),height:this.get_height(),width:this.get_width(),listWidth:this.get_listWidth(),rowHeight:this.get_rowHeight(),views:this.views(),columns:this.columns(),resizable:this.get_allowColumnResize(),navigatable:this._getNavigatable(),skin:this._skin,range:{start:this.get_rangeStart(),end:this.get_rangeEnd()},pdf:this.get_pdfSettings(),taskTemplate:this.get_clientTemplate(),moveStart:function(r){if(a.raiseCancellableControlEvent(q,"taskMoveStart",{task:r.task})){r.preventDefault();
}},move:function(s){var r={task:s.task,start:s.start};
if(a.raiseCancellableControlEvent(q,"taskMoving",r)){s.preventDefault();
}},moveEnd:function(s){var r={task:s.task,start:s.start};
if(a.raiseCancellableControlEvent(q,"taskMoveEnd",r)){s.preventDefault();
}},resizeStart:function(r){if(a.raiseCancellableControlEvent(q,"taskResizeStart",{task:r.task})){r.preventDefault();
}},resize:function(s){var r={task:s.task,start:s.start,end:s.end};
if(a.raiseCancellableControlEvent(q,"taskResizing",r)){s.preventDefault();
}},resizeEnd:function(s){var r={task:s.task,start:s.start,end:s.end};
if(a.raiseCancellableControlEvent(q,"taskResizeEnd",r)){s.preventDefault();
}},columnResize:function(s){var r={column:s.column,newWidth:s.newWidth,oldWidth:s.oldWidth};
a.raiseControlEvent(q,"columnResized",r);
},navigate:function(r){q._raiseNavigationCommand(r);
},pdfExport:function(r){if(a.raiseCancellableControlEvent(q,"pdfExporting",{})){r.preventDefault();
}},dataBound:function(r){if(!q._widget){q._widget=r.sender;
}a.raiseControlEvent(q,"dataBound",{});
},togglePlannedTasks:function(s){var r={sender:s.sender,showPlannedTasks:s.showPlannedTasks};
if(a.raiseCancellableControlEvent(q,"togglePlannedTasks",r)){s.preventDefault();
}},change:function(s){var r={sender:s.sender,selectedElement:s.sender.select()};
a.raiseControlEvent(q,"taskSelectionChanged",r);
},edit:function(s){var r={sender:s.sender,task:s.task,container:s.container};
if(a.raiseCancellableControlEvent(q,"taskEditing",r)){s.preventDefault();
}},add:function(s){var r={sender:s.sender,task:s.task,dependency:s.dependency};
if(a.raiseCancellableControlEvent(q,"inserting",r)){s.preventDefault();
}},remove:function(s){var r={sender:s.sender,task:s.task,dependencies:s.dependencies};
if(a.raiseCancellableControlEvent(q,"removing",r)){s.preventDefault();
}},save:function(s){var r={sender:s.sender,task:s.task,values:s.values};
if(a.raiseCancellableControlEvent(q,"taskSaving",r)){s.preventDefault();
}},cancel:function(s){var r={sender:s.sender,task:s.task,container:s.container};
if(a.raiseCancellableControlEvent(q,"taskUpdateCancel",r)){s.preventDefault();
}},};
if(this.get_enableResources()){a.extend(true,p,{resources:this.resources(),assignments:this.assignments()});
}return p;
},repaint:function(){var o=this._widget;
if(o){o.resize();
o.refresh();
}},currentTimeMarker:function(){var o=this.get_showCurrentTimeMarker();
if(o){o={updateInterval:this.get_currentTimeMarkerInterval()};
}return o;
},get_toolbarSettings:function(){var o=this._toolbar;
if(!o){o=[];
if(!this.get_readOnly()&&this.get_allowTaskInsert()!==false){o.push("append");
}if(this.get_enablePdfExport()){o.push("pdf");
}if(this.get_allowPlannedTasks()){o.push("plannedTasks");
}}return o;
},views:function(){var o={day:{selected:true,slotSize:100,timeHeaderTemplate:"#=kendo.toString(start, 't')#",dayHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')#"},week:{selected:false,slotSize:100,dayHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')#",weekHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#"},month:{selected:false,slotSize:150,weekHeaderTemplate:"#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#",monthHeaderTemplate:"#=kendo.toString(start, 'MMMM, yyyy')#"},year:{selected:false,slotSize:100,monthHeaderTemplate:"#=kendo.toString(start, 'MMM')#",yearHeaderTemplate:"#=kendo.toString(start, 'yyyy')#"}};
var p=a.map(this.get_viewsData(),function(q){if(q.range&&q.range.start){q.range.start=new Date(q.range.start);
}if(q.range&&q.range.end){q.range.end=new Date(q.range.end);
}if(q.date){q.date=new Date(q.date);
}return a.extend(true,{},o[q.type],q);
});
return p;
},columns:function(){var o=[{field:"id",title:"ID",sortable:false,editable:false},{field:"title",title:"Title",sortable:true,editable:true},{field:"start",title:"Start Time",sortable:true,editable:true,format:"{0:MM/dd/yyyy HH:mm}"},{field:"end",title:"End Time",sortable:true,editable:true,format:"{0:MM/dd/yyyy HH:mm}"},{field:"percentComplete",title:"Percent Complete",sortable:true,editable:true,format:"{0:p}"}];
var q={title:"",sortable:true,editable:true,format:""};
var p=this.get_columnsData();
var r=function(u){for(var v=0;
v<o.length;
v++){var t=o[v];
if(t.field===u.field){return a.extend({},t,u);
}}return a.extend({},q,u);
};
for(var s=0;
s<p.length;
s++){p[s]=r(p[s]);
}return p.length?p:o;
},tasksDataSource:function(){var r=this;
var o=this.get_customTaskFields();
var v=["default","string","number","date","boolean"];
var p;
var q;
var u={transport:this.proxy("task","get_tasksData"),schema:{model:{id:"id",fields:{id:{from:"ID"},orderId:{from:"OrderID",type:"number"},parentId:{from:"ParentID",defaultValue:null},title:{from:"Title",defaultValue:"",type:"string"},start:{from:"Start",type:"date"},plannedStart:{from:"PlannedStart",type:"date",defaultValue:null,nullable:true},end:{from:"End",type:"date"},plannedEnd:{from:"PlannedEnd",type:"date",defaultValue:null,nullable:true},percentComplete:{from:"PercentComplete",type:"number"},summary:{from:"Summary",type:"bool"},expanded:{from:"Expanded",type:"bool"}}},parse:j},batch:true};
for(var s=0,t=o.length;
s<t;
s++){p=o[s];
q={from:p.propertyName,type:v[p.type]};
if(p.defaultValue!==l){q.defaultValue=p.defaultValue;
}u.schema.model.fields[p.clientPropertyName]=q;
}if(this.get_webServiceSettings()){u.requestStart=this._getRequestEventHandler("Tasks");
u.requestEnd=function(x){var w={sender:x.sender,dataSourceType:"Tasks",response:x.response,type:x.type};
a.raiseControlEvent(r,"requestEnd",w);
};
u.error=function(x){var w={sender:x.sender,dataSourceType:"Tasks",errorThrown:x.errorThrown,status:x.status,xhr:x.xhr};
a.raiseControlEvent(r,"requestFailed",w);
};
}return u;
},dependenciesDataSource:function(){var o=this;
var p={transport:this.proxy("dependency","get_dependenciesData"),schema:{model:{id:"id",fields:{id:{from:"ID"},predecessorId:{from:"PredecessorID"},successorId:{from:"SuccessorID"},type:{from:"Type",type:"number"}}},parse:j},batch:true};
if(this.get_webServiceSettings()){p.requestStart=this._getRequestEventHandler("Dependencies");
p.requestEnd=function(r){var q={sender:r.sender,dataSourceType:"Dependencies",response:r.response,type:r.type};
a.raiseControlEvent(o,"requestEnd",q);
};
p.error=function(r){var q={sender:r.sender,dataSourceType:"Dependencies",errorThrown:r.errorThrown,status:r.status,xhr:r.xhr};
a.raiseControlEvent(o,"requestFailed",q);
};
}return p;
},resources:function(){var o={dataColorField:"Color",dataTextField:"Text",dataFormatField:"Format",dataSource:this.resourcesDataSource()};
return o;
},resourcesDataSource:function(){var o=this;
var q=this.get_resourcesData();
var r=this.get_webServiceSettings();
var p={schema:{model:{id:"id",fields:{id:{from:"ID"}}},parse:j}};
if(q.length>0){p.data=q;
}else{if(r){p.transport=d.transport({path:r.get_path(),type:r.get_useHttpGet()?"GET":"POST",methods:{read:r.get_getResourcesMethod()}});
p.requestStart=this._getRequestEventHandler("Resources");
p.requestEnd=function(t){var s={sender:t.sender,dataSourceType:"Resources",response:t.response,type:t.type};
a.raiseControlEvent(o,"requestEnd",s);
};
p.error=function(t){var s={sender:t.sender,dataSourceType:"Resources",errorThrown:t.errorThrown,status:t.status,xhr:t.xhr};
a.raiseControlEvent(o,"requestFailed",s);
};
}}return p;
},assignments:function(){var o={dataTaskIdField:"TaskID",dataResourceIdField:"ResourceID",dataValueField:"Units",dataSource:this.assignmentsDataSource()};
return o;
},assignmentsDataSource:function(){var o=this;
var p={transport:this.proxy("assignment","get_assignmentsData"),schema:{model:{id:"id",fields:{id:{from:"ID"},TaskID:{from:"TaskID"},ResourceID:{from:"ResourceID"},Units:{from:"Units"}}},parse:j},batch:true};
if(this.get_webServiceSettings()){p.requestStart=this._getRequestEventHandler("Assignments");
p.requestEnd=function(r){var q={sender:r.sender,dataSourceType:"Assignments",response:r.response,type:r.type};
a.raiseControlEvent(o,"requestEnd",q);
};
p.error=function(r){var q={sender:r.sender,dataSourceType:"Assignments",errorThrown:r.errorThrown,status:r.status,xhr:r.xhr};
a.raiseControlEvent(o,"requestFailed",q);
};
}return p;
},get_tasks:function(){var o=this._widget.dataSource.taskChildren();
var s=new c.GanttTaskCollection(this);
var r;
for(var p=0,q=o.length;
p<q;
p++){r=new c.GanttTask();
r._loadFromDictionary(o[p]);
s._add(r);
}return s;
},get_allTasks:function(){var o=this._widget.dataSource.taskAllChildren();
var s=[];
var r;
for(var p=0,q=o.length;
p<q;
p++){r=new c.GanttTask();
r._loadFromDictionary(o[p]);
r._owner=this;
s.push(r);
}return s;
},get_webServiceSettings:function(){return this._webServiceSettings;
},set_webServiceSettings:function(p){var o=b.deserialize(p);
this._webServiceSettings=new n(o);
},get_dependencies:function(){var o=this._widget.dependencies.view();
var p=new c.GanttDependencyCollection(this);
var q;
for(var r=0,s=o.length;
r<s;
r++){q=new c.GanttDependency();
q._loadFromDictionary(o[r]);
p._add(q);
}return p;
},get_resources:function(){var o=this._widget.resources.dataSource.view();
var s=new c.GanttResourceCollection(this);
var r;
for(var p=0,q=o.length;
p<q;
p++){r=new c.GanttResource();
r._loadFromDictionary(o[p]);
s._add(r);
}return s;
},get_assignments:function(){var q=this._widget.assignments.dataSource.view();
var p=new c.GanttAssignmentCollection(this);
var o;
for(var r=0,s=q.length;
r<s;
r++){o=new c.GanttAssignment();
o._loadFromDictionary(q[r]);
p._add(o);
}return p;
},get_postBackReference:function(){return this._postBackReference;
},get_selectedView:function(){var o=this._widget.timeline._selectedViewName;
switch(o){case"day":return c.GanttViewType.Day;
case"week":return c.GanttViewType.Week;
case"month":return c.GanttViewType.Month;
case"year":return c.GanttViewType.Year;
}},set_selectedView:function(o){var p=["day","week","month","year"];
this._widget.view(p[o]);
},get_scrollTop:function(){return this._scrollTop;
},set_scrollTop:function(o){this._scrollTop=o;
a(this.get_element()).find(".rgtTimelineContent").scrollTop(o);
},get_scrollLeft:function(){return this._scrollLeft;
},set_scrollLeft:function(p){var o=a(this.get_element()).find(".rgtTimelineContent");
this._scrollLeft=p;
if(o.length){h.scrollLeft(o,p);
}},get_kendoWidget:function(){return this._widget;
},exportToPdf:function(){if(this.get_enablePdfExport()){this._widget.saveAsPDF();
}},saveClientState:function(){return'{"scrollTop":'+Math.round(this.get_scrollTop())+', "scrollLeft":'+Math.round(this.get_scrollLeft())+', "selectedView":'+this.get_selectedView()+"}";
},postback:function(o){var p=this.get_postBackReference().replace("arguments",Sys.Serialization.JavaScriptSerializer.serialize(o).replace(/\\/g,"\\\\").replace(/'/g,"\\'"));
eval(p);
},get_rippleZonesConfiguration:function(){return[{element:this.get_element(),rippleConfigurations:[{containerSelector:".radButton",disabledClass:"rgtTaskDelete"}]}];
},_extractTaskFromDomElement:function(q){var s;
var p;
var o;
var r=null;
s=a(q).closest(".rgtTask");
if(s.length>0){p=this._widget.dataSource;
o=p.getByUid(s.attr("data-uid"));
if(o){r=new c.GanttTask();
r._loadFromDictionary(o);
}}return r;
},_getRequestEventHandler:function(p){var o=this;
return function(r){var q={type:r.type+p,context:{}};
if(a.raiseCancellableControlEvent(o,"requestStart",q)){r.preventDefault();
return;
}r.sender.transport.parameterMap=function(t,s){var u={context:q.context};
if(s!=="read"){u.models=(t.models||[t]);
}return b.serialize(u);
};
};
},_raiseNavigationCommand:function(q){if(!q.view){return;
}var o={view:q.view};
var p={day:"SwitchToDayView",week:"SwitchToWeekView",month:"SwitchToMonthView",year:"SwitchToYearView"};
if(a.raiseCancellableControlEvent(this,"navigationCommand",o)){q.preventDefault();
}else{if(this._postBackOnNavigate){q.preventDefault();
this.postback({commandName:p[o.view]});
}}},_insertTask:function(o,q){var s=this._widget;
var r=q._data;
var p=s.dataSource._createNewModel(r);
s._createTask(p,o);
},_updateTask:function(p,q){var o=this._getKendoTask(p);
this._widget._updateTask(o,q);
},_removeTask:function(p){var o=this._getKendoTask(p);
this._widget.removeTask(o);
},_addDependency:function(o){var r=this._widget;
var p=o._getInfo();
var q=r.dependencies._createNewModel(p);
r._createDependency(q);
},_removeDependency:function(o){var p=this._getKendoDependency(o);
this._widget.removeDependency(p);
},_updateAssignment:function(o){var p=this._getKendoAssignment(o);
this._widget._updateAssignment(p,o.get_units());
},_addAssignment:function(o){var s=this._widget;
var q=o._getInfo();
var p=s.assignments.dataSource;
var r=p._createNewModel(q);
p.add(r);
},_removeAssignment:function(o){var p=this._getKendoAssignment(o);
this._widget._removeAssignment(p);
},_getKendoTask:function(o){return this._widget.dataSource.getByUid(o._uid);
},_getKendoDependency:function(o){return this._widget.dependencies.getByUid(o._uid);
},_getKendoAssignment:function(o){return this._widget.assignments.dataSource.getByUid(o._uid);
},_extendStyles:function(){var o=" radSkin_"+this._skin;
if($telerik.isRightToLeft(this.get_element())){f.styles.wrapper+=" RadGantt_rtl RadGantt_"+this._skin+"_rtl k-rtl";
}f.styles.popupWrapper+=o;
g.styles.dragClue+=o;
},_initializePostback:function(){var r=this;
var q=[this._postBackOnTaskInsert,this._postBackOnTaskUpdate,this._postBackOnTaskDelete,this._postBackOnDependencyInsert,this._postBackOnDependencyDelete,this._postBackOnAssignmentInsert,this._postBackOnAssignmentUpdate,this._postBackOnAssignmentDelete];
var p=["_createTask","_updateTask","_removeTask","_createDependency","_removeDependency","_updateAssignments","_updateAssignments","_updateAssignments"];
var o=a(p).filter(function(t){return q[t];
});
var s=a.grep(o,function(u,t){return a.inArray(u,o)===t;
});
a(s).each(function(u,t){var w=r._widget;
var v=w[t];
r._widget[t]=function(){w.dataSource.transport.set_postback(true);
if(w.dependencies.transport.set_postback){w.dependencies.transport.set_postback(true);
}if(w.assignments.dataSource.transport.set_postback){w.assignments.dataSource.transport.set_postback(true);
}v.apply(this,arguments);
r._commandsCache.commandName="Postback";
r.postback(r._commandsCache);
};
});
},_getNavigatable:function(){return this._navigationSettings.focusKey!==l;
},_initializeKeyboardNavigation:function(){var r=this._widget;
var q=this._navigationSettings;
var o=q.commandKey;
if(this._getNavigatable()){var p=this._keyboardNavigationHandler=function(u){var s=u.altKey===((1&o)>0);
var t=u.ctrlKey===((2&o)>0);
var v=u.shiftKey===((4&o)>0);
if(s&&t&&v&&u.keyCode===q.focusKey){r.list.content.find("table").focus();
}};
a(document.body).on("keydown",p);
}},_disposeKeyboardNavigation:function(){if(this._getNavigatable()){a(document.body).off("keydown",this._keyboardNavigationHandler);
}},_getEditableOpitons:function(){var t=this.get_allowTaskInsert();
var y=this.get_allowTaskUpdate();
var s=this.get_allowTaskDelete();
var u=this.get_allowTaskMove();
var x=this.get_allowTaskResize();
var w=this.get_allowTaskReorder();
var o=this.get_allowPercentCompleteDrag();
var q=this.get_allowDependencyInsert();
var r=this.get_allowDependencyDelete();
var p=this.get_displayDeleteConfirmation();
var v=this.get_allowPlannedTasks();
if(t&&y&&s&&u&&x&&w&&o&&q&&r&&p&&v==false){return true;
}return{plannedTasks:v,create:t,update:y,destroy:s,move:u,resize:x,reorder:w,dragPercentComplete:o,dependencyCreate:q,dependencyDestroy:r,confirmation:p};
},_getWidgetOptions:function(p,s){var r={snapToGrid:"snap",clientTemplate:"taskTemplate",allowColumnResize:"resizable",showFullTime:"showWorkHours",showFullWeek:"showWorkDays"};
var q={};
switch(p){case"showCurrentTimeMarker":case"currentTimeMarkerInterval":q.currentTimeMarker=this.currentTimeMarker();
break;
case"displayDeleteConfirmation":case"readOnly":var o=!this.get_readOnly();
q.selectable=!this.get_readOnly();
if(o){o=this._getEditableOpitons();
}q.editable=o;
break;
case"allowTaskInsert":case"allowTaskUpdate":case"allowTaskDelete":case"allowTaskMove":case"allowTaskReorder":case"allowTaskResize":case"allowPlannedTasks":case"allowPercentCompleteDrag":case"allowDependencyInsert":case"allowDependencyDelete":if(!this.get_readOnly()){q.editable=this._getEditableOpitons();
}break;
case"tooltip":q.tooltip=this.tooltip;
break;
case"toolbar":q.toolbar=this.get_toolbarSettings();
break;
case"showFullTime":case"showFullWeek":case"showPlannedTasks":q[r[p]||p]=!s;
break;
default:q[r[p]||p]=s;
}return q;
}};
function k(o,p){a.each(p,function(r,q){o.prototype["get_"+r]=function(){var s=this["_"+r];
return typeof s=="undefined"?q:s;
};
o.prototype["set_"+r]=function(u){this["_"+r]=u;
if(this._widget){switch(r){case"selectedDate":this._widget.date(u);
break;
case"rangeStart":case"rangeEnd":var t={start:this.get_rangeStart(),end:this.get_rangeEnd()};
this._widget.range(t);
break;
default:var s=this._getWidgetOptions(r,u);
this._widget.setOptions(s);
this.set_scrollTop(this.get_scrollTop());
this.set_scrollLeft(this.get_scrollLeft());
}}};
});
}k(c.RadGantt,{allowColumnResize:false,clientTemplate:null,currentTimeMarkerInterval:10000,displayDeleteConfirmation:true,height:700,hourSpan:1,listWidth:"30%",readOnly:false,rowHeight:null,snapToGrid:true,showCurrentTimeMarker:true,showFullTime:false,showFullWeek:true,showTooltip:true,width:"100%",rangeStart:null,rangeEnd:null,selectedDate:null,toolbar:null,allowTaskInsert:true,allowTaskUpdate:true,allowTaskDelete:true,allowPlannedTasks:false,showPlannedTasks:false,allowTaskMove:true,allowTaskReorder:true,allowTaskResize:true,allowPercentCompleteDrag:true,allowDependencyInsert:true,allowDependencyDelete:true,workWeekStart:c.DayOfWeek.Monday,workWeekEnd:c.DayOfWeek.Friday});
a.registerControlProperties(c.RadGantt,{tasksData:[],dependenciesData:[],resourcesData:[],assignmentsData:[],viewsData:[],columnsData:[],customTaskFields:[],localization:{},pdfSettings:{},tooltip:{},enableResources:false,enablePdfExport:false});
a.registerControlEvents(c.RadGantt,["navigationCommand","taskMoveStart","taskMoving","taskMoveEnd","taskResizeStart","taskResizing","taskResizeEnd","columnResized","pdfExporting","requestStart","requestEnd","requestFailed","dataBound","kendoWidgetInitializing",i,"togglePlannedTasks","taskSelectionChanged","taskEditing","taskSaving","taskUpdateCancel","inserting","removing",]);
c.RadGantt.registerClass("Telerik.Web.UI.RadGantt",c.RadWebControl);
})($telerik.$);
(function(a,b,c){b.GanttTask=function(){this._data={parentId:null,title:"",percentComplete:0,summary:false,expanded:true};
this._owner=null;
};
b.GanttTask.prototype={_loadFromDictionary:function(d){this._data=a.extend({},d);
if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._data.id;
},get_parentId:function(){return this._data.parentId;
},get_orderId:function(){return this._data.orderId;
},get_start:function(){return this._data.start;
},get_plannedStart:function(){return this._data.plannedStart;
},get_end:function(){return this._data.end;
},get_plannedEnd:function(){return this._data.plannedEnd;
},get_title:function(){return this._data.title;
},get_percentComplete:function(){return this._data.percentComplete;
},get_summary:function(){return this._data.summary;
},get_expanded:function(){return this._data.expanded;
},get_tasks:function(){var k=new b.GanttTaskCollection(this);
var f;
var e;
var d;
var j;
if(this._owner){f=this._owner._widget.dataSource;
e=f.getByUid(this._uid);
if(e){d=f.taskChildren(e);
for(var g=0,h=d.length;
g<h;
g++){j=new b.GanttTask();
j._loadFromDictionary(d[g]);
k._add(j);
}}}return k;
},get_dependencies:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.dependencies(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_predecessors:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.predecessors(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_successors:function(){var e=new b.GanttDependencyCollection(this);
var d;
if(this._owner){d=this._owner._widget.dependencies.successors(this.get_id());
e=this._createDependencyCollection(d);
}return e;
},get_element:function(){var e=this._owner;
var d=null;
if(e){d=a(e.get_element()).find(".rgtTimelineContent").find(".rgtTask[data-uid='"+this._uid+"']")[0];
}return d;
},set_start:function(d){this._data.start=d;
this._update({start:d});
},set_plannedStart:function(d){this._data.plannedStart=d;
this._update({plannedStart:d});
},set_end:function(d){this._data.end=d;
this._update({end:d});
},set_plannedEnd:function(d){this._data.plannedEnd=d;
this._update({plannedEnd:d});
},set_title:function(d){this._data.title=d;
this._update({title:d});
},set_percentComplete:function(d){this._data.percentComplete=d;
this._update({percentComplete:d});
},set_expanded:function(d){this._data.expanded=d;
this._update({expanded:d});
},_update:function(d){if(this._owner){this._owner._updateTask(this,d);
}},_createDependencyCollection:function(d){var f;
var e=new b.GanttDependencyCollection(this);
for(var g=0,h=d.length;
g<h;
g++){f=new b.GanttDependency();
f._loadFromDictionary(d[g]);
e._add(f);
}return e;
}};
b.GanttTask.registerClass("Telerik.Web.UI.GanttTask");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttTaskCollection=function(c){if(c instanceof b.GanttTask){this._owner=c._owner;
}else{this._owner=c;
}this._parent=c;
this._array=[];
};
b.GanttTaskCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._owner;
},_insert:function(c,d){Array.insert(this._array,c,d);
d._owner=this._owner;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(d){var c=this._array.length;
this.insert(c,d);
},insert:function(c,d){this._insert(c,d);
if(this._owner===this._parent){d._parentId=null;
}else{d._parentId=this._parent.get_id();
}this._owner._insertTask(c,d);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._owner._removeTask(c);
}},get_count:function(){return this._array.length;
},getTask:function(c){return this._array[c];
},indexOf:function(f){var c=this._array;
for(var d=0,e=c.length;
d<e;
d++){if(c[d]._uid===f._uid){return d;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttTaskCollection.registerClass("Telerik.Web.UI.GanttTaskCollection");
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){a.registerEnum(b,"GanttDependencyType",{FinishFinish:0,FinishStart:1,StartFinish:2,StartStart:3});
b.GanttDependency=function(){this._type=b.GanttDependencyType.FinishFinish;
this._owner=null;
};
b.GanttDependency.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.predecessorId!==c){this._predecessorId=d.predecessorId;
}if(d.successorId!==c){this._successorId=d.successorId;
}if(d.type!==c){this._type=d.type;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_predecessorId:function(){return this._predecessorId;
},get_successorId:function(){return this._successorId;
},get_type:function(){return this._type;
},_getInfo:function(){var d={predecessorId:this._predecessorId,successorId:this._successorId,type:this._type};
return d;
}};
b.GanttDependency.registerClass("Telerik.Web.UI.GanttDependency");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttDependencyCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttDependencyCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(c){this._add(c);
this._parent._addDependency(c);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._parent._removeDependency(c);
}},get_count:function(){return this._array.length;
},getDependency:function(c){return this._array[c];
},indexOf:function(d){var c=this._array;
for(var e=0,f=c.length;
e<f;
e++){if(c[e]._uid===d._uid){return e;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttDependencyCollection.registerClass("Telerik.Web.UI.GanttDependencyCollection");
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){b.GanttResource=function(){this._owner=null;
};
b.GanttResource.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.Text!==c){this._text=d.Text;
}if(d.Color!==c){this._color=d.Color;
}if(d.Format!==c){this._format=d.Format;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_text:function(){return this._text;
},get_color:function(){return this._color;
},get_format:function(){return this._format;
}};
b.GanttResource.registerClass("Telerik.Web.UI.GanttResource");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttResourceCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttResourceCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},get_count:function(){return this._array.length;
},getResource:function(c){return this._array[c];
},indexOf:function(f){var c=this._array;
for(var d=0,e=c.length;
d<e;
d++){if(c[d]._uid===f._uid){return d;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
})($telerik.$,Telerik.Web.UI);
(function(a,b,c){b.GanttAssignment=function(){this._owner=null;
};
b.GanttAssignment.prototype={_loadFromDictionary:function(d){if(d.id!==c){this._id=d.id;
}if(d.TaskID!==c){this._taskId=d.TaskID;
}if(d.ResourceID!==c){this._resourceId=d.ResourceID;
}if(d.Units!==c){this._units=d.Units;
}if(d.uid!==c){this._uid=d.uid;
}},get_id:function(){return this._id;
},get_taskId:function(){return this._taskId;
},get_resourceId:function(){return this._resourceId;
},get_units:function(){return this._units;
},set_units:function(d){this._units=d;
this._update();
},_getInfo:function(){var d={TaskID:this._taskId,ResourceID:this._resourceId,Units:this._units};
return d;
},_update:function(){if(this._owner){this._owner._updateAssignment(this);
}}};
b.GanttAssignment.registerClass("Telerik.Web.UI.GanttAssignment");
})($telerik.$,Telerik.Web.UI);
(function(a,b){b.GanttAssignmentCollection=function(c){this._parent=c;
this._array=[];
};
b.GanttAssignmentCollection.prototype={_add:function(c){this._array.push(c);
c._owner=this._parent;
},_remove:function(c){this._array.pop(c);
c._owner=null;
},add:function(c){this._add(c);
this._parent._addAssignment(c);
},remove:function(c){if(this.indexOf(c)>-1){this._remove(c);
this._parent._removeAssignment(c);
}},get_count:function(){return this._array.length;
},getAssignment:function(c){return this._array[c];
},indexOf:function(d){var c=this._array;
for(var e=0,f=c.length;
e<f;
e++){if(c[e]._uid===d._uid){return e;
}}return -1;
},toArray:function(){return this._array.slice(0);
}};
b.GanttAssignmentCollection.registerClass("Telerik.Web.UI.GanttAssignmentCollection");
})($telerik.$,Telerik.Web.UI);
