using System;

namespace TechnoPro.Common.DAO.Impl.Inventory.QueryStorage
{
	// Token: 0x020000BF RID: 191
	internal static class QueryStorageInventoryLoan
	{
		// Token: 0x0400027F RID: 639
		internal const string SQ_GET_ACTIVE_LOANS = "select   al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n        lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n        lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n        lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n        al.ProductUniqueID, al.LoanGroupId\r\nfrom InventoryV2_ActiveLoan al \r\nINNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\nLEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\nLEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\nLEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\nLEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\nLEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\nLEFT JOIN InventoryV2_Product p ON al.ProductUniqueID=p.ProductUniqueID\r\nLEFT JOIN InventoryV2_Category cg ON cg.CategoryName=p.CategoryName\r\nLEFT JOIN InventoryV2_Catalog ct ON ct.CatalogID=cg.CatalogId\r\nWHERE ct.IsActive = 1";

		// Token: 0x04000280 RID: 640
		internal const string SQ_GET_ACTIVE_LOAN_BY_ID = "select   al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where al.LoanID = @loanid";

		// Token: 0x04000281 RID: 641
		internal const string SQ_GET_ACTIVE_LOAN_BY_PRODUCT_UNIQUE_ID = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where al.ProductUniqueID = @productuniqueid";

		// Token: 0x04000282 RID: 642
		internal const string SQ_GET_ACTIVE_LOAN_BY_PRODUCT_ID = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId,\r\n                       p.ProductDynamicDataID\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                INNER JOIN InventoryV2_Product p ON p.ProductUniqueID=al.ProductUniqueID\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where p.ProductDynamicDataID = @productid";

		// Token: 0x04000283 RID: 643
		internal const string SQ_GET_ACTIVE_LOANS_BY_PERSON_LOANED_TO = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes,\r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where lg.LoanedToID = @loanedtoid";

		// Token: 0x04000284 RID: 644
		internal const string SQ_GET_ACTIVE_LOANS_BY_PERSON_LOANED_TO_AND_DATE_RANGE = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes,\r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where lg.LoanedToID = @loanedtoid AND lg.LoanedDate < @enddate AND lg.DueDate > @startdate";

		// Token: 0x04000285 RID: 645
		internal const string SQ_GET_ACTIVE_LOANS_BY_DUE_DATE_BEFORE = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes,\r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where lg.DueDate BETWEEN getdate() AND @enddate";

		// Token: 0x04000286 RID: 646
		internal const string SQ_GET_OVER_DUE_DATE_ACTIVE_LOANS = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes,\r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where lg.DueDate < getdate()";

		// Token: 0x04000287 RID: 647
		internal const string SQ_GET_RETURNED_LOANS = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId";

		// Token: 0x04000288 RID: 648
		internal const string SQ_GET_RETURNED_LOAN_BY_ID = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId \r\n            where rl.LoanID = @loanid";

		// Token: 0x04000289 RID: 649
		internal const string SQ_GET_RETURNED_LOANS_BY_PRODUCT_ID = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where rl.ProductUniqueID = @productuniqueid";

		// Token: 0x0400028A RID: 650
		internal const string SQ_GET_RETURNED_LOANS_BY_PRODUCT_UNIQUE_ID_AND_DATE_RANGE = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where rl.ProductUniqueID = @productuniqueid AND lg.LoanedDate < @enddate AND rl.ReturnedDate > @startdate";

		// Token: 0x0400028B RID: 651
		internal const string SQ_GET_RETURNED_LOANS_BY_PRODUCT_ID_AND_DATE_RANGE = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription,\r\n                   p.ProductDynamicDataID\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            INNER JOIN InventoryV2_Product p ON p.ProductUniqueID=rl.ProductUniqueID\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where p.ProductDynamicDataID = @productid AND lg.LoanedDate < @enddate AND rl.ReturnedDate > @startdate";

		// Token: 0x0400028C RID: 652
		internal const string SQ_GET_RETURNED_LOANS_BY_LOANED_TO_ID = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where lg.LoanedToId = @loanedtoid";

		// Token: 0x0400028D RID: 653
		internal const string SQ_GET_RETURNED_LOANS_BY_LOANED_TO_ID_AND_DATE_RANGE = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where lg.LoanedToID = @loanedtoid AND lg.LoanedDate < @enddate AND rl.ReturnedDate > @startdate";

		// Token: 0x0400028E RID: 654
		internal const string SQ_GET_ACTIVE_LOANS_BY_GROUP_ID = "select al.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes,\r\n                       lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n                       lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                       lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                       al.ProductUniqueID, al.LoanGroupId\r\n                from InventoryV2_ActiveLoan al \r\n                INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=al.LoanGroupId\r\n                LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where al.LoanGroupId = @loangroupid";

		// Token: 0x0400028F RID: 655
		internal const string SQ_GET_RETURNED_LOANS_BY_GROUP_ID = "select rl.LoanID, lg.LoanedDate, lg.DueDate, lg.LoanNotes, \r\n                   lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid, \r\n                   lg.LocationID, l.Campus, l.Building, l.RoomNumber, l.Seat, l.LocationNotes,\r\n                   lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid,\r\n                   rl.ProductUniqueID, rl.LoanGroupId,\r\n                   rl.WhoReturnedId as retpersonid, pret.firstname as retfirstname,pret.lastname as retlastname,pret.middlename as retmiddlename,pret.student_no as retstudent_no,pgret.mingroupid AS retgroupid,\r\n                   rl.ReturnedNotes, rl.ReturnedDate, \r\n                   ls.LoanStatusID, ls.LoanStatusName, ls.LoanStatusDescription\r\n            from InventoryV2_ReturnedLoan rl \r\n            INNER JOIN InventoryV2_LoanGroup lg ON lg.LoanGroupId=rl.LoanGroupId\r\n            LEFT JOIN InventoryV2_Location l ON l.LocationID=lg.LocationID\r\n            LEFT JOIN InventoryV2_LoanStatus ls on ls.LoanStatusID=rl.ReturnedStatusID\r\n            LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n            LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n            LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n            LEFT JOIN people pret ON pret.personid=rl.WhoReturnedId\r\n            LEFT JOIN peoplemingroup pgret ON pgret.personid=rl.WhoReturnedId\r\n            where rl.LoanGroupId = @loangroupid";

		// Token: 0x04000290 RID: 656
		internal const string UQ_MARK_PRODUCT_AS_LOANED = "update InventoryV2_Product set LoanID=@loanid where ProductUniqueID=@productuniqueid";

		// Token: 0x04000291 RID: 657
		internal const string IQ_CREATE_LOAN = "INSERT INTO [InventoryV2_ActiveLoan]\r\n                       ([ProductUniqueID]\r\n                       ,[LoanGroupId])\r\n                 VALUES\r\n                       (@productuniqueid\r\n                       ,@loangroupid)\r\n\r\n            SET @loanid = SCOPE_IDENTITY()";

		// Token: 0x04000292 RID: 658
		internal const string IQ_CREATE_LOAN_GROUP = "INSERT INTO [InventoryV2_LoanGroup]\r\n                       ([DueDate]\r\n                       ,[LoanNotes]\r\n                       ,[LoanedToID]\r\n                       ,[LocationID]\r\n                       ,[WhoLoanedID]\r\n                       )\r\n                 VALUES\r\n                       (@duedate\r\n                       ,@loannotes\r\n                       ,@loanedtoid\r\n                       ,@locationid\r\n                       ,@wholoanedid)\r\n\r\n            SET @loangroupid=SCOPE_IDENTITY()";

		// Token: 0x04000293 RID: 659
		internal const string UQ_UPDATE_LOAN_GROUP = "UPDATE [InventoryV2_LoanGroup]\r\n                   SET [DueDate] = @duedate\r\n                      ,[LoanNotes] = @loannotes\r\n                      ,[LocationID] = @locationid\r\n                 WHERE LoanGroupId = @loangroupid";

		// Token: 0x04000294 RID: 660
		internal const string UQ_UPDATE_LOAN = "if ((select count(*) from InventoryV2_ActiveLoan where LoanGroupId=@loangroupid) > 1)\r\n\t            begin\r\n\t\t            BEGIN TRANSACTION\r\n\t\t            INSERT INTO [InventoryV2_LoanGroup]\r\n                                    ([LoanedDate]\r\n                                    ,[DueDate]\r\n                                    ,[LoanNotes]\r\n                                    ,[LoanedToID]\r\n                                    ,[LocationID]\r\n                                    ,[WhoLoanedID]\r\n                                    )\r\n                                VALUES\r\n                                    (@loaneddate\r\n                                    ,@duedate\r\n                                    ,@loannotes\r\n                                    ,@loanedtoid\r\n                                    ,@locationid\r\n                                    ,@wholoanedid)\r\n\t\t            set @rgroupid = SCOPE_IDENTITY()\r\n\t\t            UPDATE [InventoryV2_ActiveLoan]\r\n\t\t\t\t            SET\tLoanGroupId = @rgroupid\r\n\t\t\t\t            where LoanID = @loanid\r\n\t\t            COMMIT TRANSACTION\r\n\t            end\r\n            else\r\n\t            begin\r\n\t\t            UPDATE [InventoryV2_LoanGroup]\r\n                                SET [DueDate] = @duedate\r\n                                    ,[LoanNotes] = @loannotes\r\n                                    ,[LocationID] = @locationid\r\n                                WHERE LoanGroupId = @loangroupid\r\n\t\t            set @rgroupid = @loangroupid\r\n\t            end";
	}
}
