using System;

namespace TechnoPro.Common.DAO.Impl.Inventory.QueryStorage
{
	// Token: 0x020000C2 RID: 194
	internal static class QueryStorageInventoryProduct
	{
		// Token: 0x040002A0 RID: 672
		internal const string SQ_PRODUCT_AVAILABILITY = "select r.ProductUniqueId, r.ReservationID as [Id], rg.ReservationStartDate as [StartDate], rg.ReservationEndDate as [EndDate], 'Reservation' as BookedType,\r\n\t\t                rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n\t\t                rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid\r\n                from InventoryV2_Reservation r\r\n                inner join InventoryV2_ReservationGroup rg on rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                where r.IsCompleted=0 and r.ProductUniqueId=@productuniqueid and (@sdate < rg.ReservationEndDate and @edate > rg.ReservationStartDate)\r\n                UNION\r\n                select l.ProductUniqueID, l.LoanID as [Id], lg.LoanedDate as [StartDate], lg.DueDate as [EndDate], 'Active_Loan' as BookedType,\r\n\t\t                lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n\t\t                lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid\r\n                from InventoryV2_ActiveLoan l\r\n                inner join InventoryV2_LoanGroup lg on lg.LoanGroupId=l.LoanGroupId\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where l.ProductUniqueID=@productUniqueId and (@sdate < lg.DueDate and @edate > lg.LoanedDate)";

		// Token: 0x040002A1 RID: 673
		internal const string SQ_PRODUCT_AVAILABILITY_WITH_PARAMETERS = "select r.ProductUniqueId, r.ReservationID as [Id], rg.ReservationStartDate as [StartDate], rg.ReservationEndDate as [EndDate], 'Reservation' as BookedType,\r\n\t\t                rg.WhoMadeReservationId as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n\t\t                rg.WhoReservedStaffPersonId as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid\r\n                from InventoryV2_Reservation r\r\n                inner join InventoryV2_ReservationGroup rg on rg.ReservationGroupId=r.ReservationGroupId\r\n                LEFT JOIN people pto ON pto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=rg.WhoMadeReservationId\r\n                LEFT JOIN people pfrom ON pfrom.personid=rg.WhoReservedStaffPersonId\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=rg.WhoReservedStaffPersonId\r\n                where @includereservations=1 AND ((@reservationid=0 OR r.ReservationID <> @reservationid) AND (r.IsCompleted=0 and r.ProductUniqueId=@productuniqueid and (@sdate < rg.ReservationEndDate and @edate > rg.ReservationStartDate)))\r\n                UNION\r\n                select l.ProductUniqueID, l.LoanID as [Id], lg.LoanedDate as [StartDate], lg.DueDate as [EndDate], 'Active_Loan' as BookedType,\r\n\t\t                lg.LoanedToID as topersonid, pto.firstname as tofirstname, pto.lastname as tolastname, pto.middlename as tomiddlename, pto.student_no as tostudent_no, pgto.mingroupid AS togroupid,\r\n\t\t                lg.WhoLoanedID as frompersonid, pfrom.firstname as fromfirstname, pfrom.lastname as fromlastname, pfrom.middlename as frommiddlename, pfrom.student_no as fromstudent_no, pgfrom.mingroupid AS fromgroupid\r\n                from InventoryV2_ActiveLoan l\r\n                inner join InventoryV2_LoanGroup lg on lg.LoanGroupId=l.LoanGroupId\r\n                LEFT JOIN people pto ON pto.personid=lg.LoanedToID\r\n                LEFT JOIN peoplemingroup pgto ON pgto.personid=lg.LoanedToID\r\n                LEFT JOIN people pfrom ON pfrom.personid=lg.WhoLoanedID\r\n                LEFT JOIN peoplemingroup pgfrom ON pgfrom.personid=lg.WhoLoanedID\r\n                where @includeloans=1 AND ((@loanid=0 OR l.LoanID <> @loanid) AND (l.ProductUniqueID=@productUniqueId and (@sdate < lg.DueDate and @edate > lg.LoanedDate)))";

		// Token: 0x040002A2 RID: 674
		internal const string SQ_GET_PRODUCTS_BY_ROOT_CATEGORY_NAME = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND (CategoryName=@rootcategoryname OR CategoryName LIKE @rootcategoryname + '.%')";

		// Token: 0x040002A3 RID: 675
		internal const string SQ_GET_PRODUCTS_BY_CATEGORY_NAME = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND CategoryName=@categoryname";

		// Token: 0x040002A4 RID: 676
		internal const string SQ_GET_PRODUCTS_BY_LOAN_GROUP_ID = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            INNER JOIN InventoryV2_ActiveLoan al ON al.ProductUniqueID=p.ProductUniqueID\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND al.LoanGroupId=@loangroupid AND\r\n\t              CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002A5 RID: 677
		internal const string SQ_GET_PRODUCTS_BY_RESERVATION_GROUP_ID = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            INNER JOIN InventoryV2_Reservation r ON r.ProductUniqueID=p.ProductUniqueID\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND r.IsCompleted=0 AND r.ReservationGroupId=@reservationgroupid AND\r\n\t              CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002A6 RID: 678
		internal const string SQ_GET_PRODUCTS_BY_GROUP = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND GroupID=@groupid AND\r\n\t              CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002A7 RID: 679
		internal const string SQ_GET_PRODUCTS_BY_CATEGORIES = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND CategoryName in (select OrderID as CategoryName from SplitStrings2(@categories, ','))";

		// Token: 0x040002A8 RID: 680
		internal const string SQ_GET_PRODUCT_BY_UNIQUE_ID = "select p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where ProductUniqueID=@productuniqueid AND\r\n                    CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002A9 RID: 681
		internal const string SQ_GET_PRODUCTS_BY_SEARCH_TEXT_USING_LIKE = "select top(100)\r\n                    p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n                    p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n                    p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n                    pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ',')) \r\n                AND ( p.ProductName like '%' + @searchtext + '%'\r\n\t            OR    p.SerialNumber like '%' + @searchtext + '%'\r\n\t            OR    p.BarCode like '%' + @searchtext + '%'\r\n\t            OR    p.CategoryName like '%' + @searchtext + '%'\r\n\t            OR\t  pg.GroupName like '%' + @searchtext + '%')";

		// Token: 0x040002AA RID: 682
		internal const string SQ_GET_PRODUCTS_BY_SEARCH_TEXT_USING_FULL_TEXT_SEARCH = "select top(100)\r\n                    p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n                    p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n                    p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n                    pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ',')) \r\n                AND (contains((ProductName,SerialNumber,BarCode,CategoryName), @searchtext) OR\r\n\t\t            contains(GroupName, @searchtext))";

		// Token: 0x040002AB RID: 683
		internal const string SQ_GET_LOANED_PRODUCTS_BY_SEARCH_TEXT_USING_LIKE = "select top(100)\r\n                    p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n                    p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n                    p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n                    pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND p.LoanID is not NULL AND CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ',')) \r\n                AND ( p.ProductName like '%' + @searchtext + '%'\r\n\t            OR    p.SerialNumber like '%' + @searchtext + '%'\r\n\t            OR    p.BarCode like '%' + @searchtext + '%'\r\n\t            OR    p.CategoryName like '%' + @searchtext + '%'\r\n\t            OR\t  pg.GroupName like '%' + @searchtext + '%')";

		// Token: 0x040002AC RID: 684
		internal const string SQ_GET_LOANED_PRODUCTS_BY_SEARCH_TEXT_USING_FULL_TEXT_SEARCH = "select top(100)\r\n                    p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n                    p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n                    p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n                    pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where p.IsActive=1 AND p.LoanID is not NULL AND CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ',')) \r\n                AND (contains((ProductName,SerialNumber,BarCode,CategoryName), @searchtext) OR\r\n\t\t            contains(GroupName, @searchtext))";

		// Token: 0x040002AD RID: 685
		internal const string SQ_GET_PRODUCT_BY_UNIQUE_ID2 = "select TOP(1) p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where ProductUniqueID=@productuniqueid";

		// Token: 0x040002AE RID: 686
		internal const string SQ_GET_PRODUCT_BY_UNIQUE_ID3 = "select TOP(1) p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where ProductDynamicDataID=@productid";

		// Token: 0x040002AF RID: 687
		internal const string SQ_GET_PRODUCT_BY_SERIAL_NUMBER = "select TOP(1) p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where SerialNumber=@serialnumber AND\r\n\t              CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002B0 RID: 688
		internal const string SQ_GET_PRODUCT_BY_BARCODE = "select TOP(1) p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where BarCode=@barcode AND\r\n\t              CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002B1 RID: 689
		internal const string SQ_GET_PRODUCT_BY_BARCODE2 = "select TOP(1) p.ProductUniqueID, p.ProductName, p.SerialNumber, p.LoanID, p.ProductStatusID, ProductStatusName, ps.ProductStatusDescription,\r\n\t                p.ProductDescription, p.ProductNotes, p.Thumbnail, p.Vendor, p.PurchaseDate, p.PurchaseAmount, p.WarrantyExpirationDate, p.PurchaseInfo,\r\n\t                p.LocationID, loc.Campus, loc.Building, loc.RoomNumber, loc.Seat, loc.LocationNotes, p.LocationDate,\r\n\t                pg.ProductGroupID, pg.GroupName, pg.GroupNotes, p.CategoryName, p.BarCode, p.ProductDynamicDataID, p.Accessories,\r\n                    p.InChargePersonID as personid, peo.firstname as firstname, peo.lastname as lastname, peo.middlename as middlename, peo.student_no as student_no, peog.mingroupid AS groupid\r\n            from InventoryV2_Product p\r\n            LEFT JOIN InventoryV2_ProductStatus ps ON p.ProductStatusID=ps.ProductStatusID\r\n            LEFT JOIN InventoryV2_Location loc ON p.LocationID=loc.LocationID\r\n            LEFT JOIN InventoryV2_ProductGroup pg ON p.GroupID=pg.ProductGroupID\r\n            LEFT JOIN people peo ON peo.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup peog ON peog.personid=p.InChargePersonID\r\n            where BarCode=@barcode";

		// Token: 0x040002B2 RID: 690
		internal const string SQ_GET_PRODUCT_SNAPSHOT_BY_PRODUCT_ID = "select OrderID as Reason into #temp from SplitStrings(@reason)\r\n\r\n                select ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t                            p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t                            GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t                            p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t                            p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t                            LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t                            p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t                            p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t                            ModifiedDate, Reason, Accessories\r\n                            from [InventoryV2_ProductSnapshot] p\r\n                            LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n                            LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n                            LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n                            LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n                            LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n                            LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n                            LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n                            LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n                            LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n                            LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n                            where p.ProductDynamicDataID=@productid and Reason in (select Reason from #temp)\r\n\r\n                drop table #temp";

		// Token: 0x040002B3 RID: 691
		internal const string SQ_GET_PRODUCT_SNAPSHOT_BY_PRODUCT_UNIQUE_ID = "select OrderID as Reason into #temp from SplitStrings(@reason)\r\n\r\n                select ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t                            p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t                            GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t                            p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t                            p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t                            LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t                            p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t                            p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t                            ModifiedDate, Reason, Accessories\r\n                            from [InventoryV2_ProductSnapshot] p\r\n                            LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n                            LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n                            LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n                            LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n                            LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n                            LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n                            LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n                            LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n                            LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n                            LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n                            where p.ProductUniqueID=@productuniqueid and Reason in (select Reason from #temp)\r\n\r\n                drop table #temp";

		// Token: 0x040002B4 RID: 692
		internal const string SQ_GET_PRODUCT_SNAPSHOT_BY_PRODUCT_BARCODE = "select OrderID as Reason into #temp from SplitStrings(@reason)\r\n\r\n            select ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t                        p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t                        GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t                        p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t                        p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t                        LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t                        p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t                        p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t                        ModifiedDate, Reason, Accessories\r\n                        from [InventoryV2_ProductSnapshot] p\r\n                        LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n                        LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n                        LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n                        LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n                        LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n                        LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n                        LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n                        LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n                        LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n                        LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n                        where p.BarCode=@barcode and Reason in (select Reason from #temp)\r\n\r\n            drop table #temp";

		// Token: 0x040002B5 RID: 693
		internal const string SQ_GET_PRODUCT_SNAPSHOT = "select top(1) ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t            p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t            GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t            p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t            p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t            LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t            p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t            p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t            ModifiedDate, Reason, Accessories\r\n            from [InventoryV2_ProductSnapshot] p\r\n            LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n            LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n            LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n            LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n            LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n            where ProductUniqueID=@productuniqueid and ReturnLoanID=@loanid\r\n            order by ModifiedDate";

		// Token: 0x040002B6 RID: 694
		internal const string SQ_GET_PRODUCT_SNAPSHOT_BY_REASON = "select top(1) ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t            p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t            GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t            p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t            p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t            LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t            p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t            p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t            ModifiedDate, Reason, Accessories\r\n            from [InventoryV2_ProductSnapshot] p\r\n            LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n            LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n            LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n            LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n            LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n            where ProductUniqueID=@productuniqueid and ReturnLoanID=@loanid and Reason=@reason\r\n            order by ModifiedDate";

		// Token: 0x040002B7 RID: 695
		internal const string SQ_GET_PRODUCT_SNAPSHOT_BY_LOAN_GROUP_AND_REASON = "select top(1) ProductSnapshotID, ProductUniqueID, ProductDynamicDataID, ProductName, Barcode, SerialNumber, CategoryName, Location, LocationDate,\r\n\t\t            p.InChargePersonID as icpersonid, pic.firstname as icfirstname, pic.lastname as iclastname, pic.middlename as icmiddlename, pic.student_no as icstudent_no, pgic.mingroupid AS icgroupid,\r\n\t\t            GroupName, ProductStatus, ReturnLoanID, LoanGroupId, LoanedDate, DueDate, ReturnedDate,\r\n\t\t            p.WhoLoanedPersonId as wlpersonid, pwl.firstname as wlfirstname, pwl.lastname as wllastname, pwl.middlename as wlmiddlename, pwl.student_no as wlstudent_no, pgwl.mingroupid AS wlgroupid,\r\n\t\t            p.WhoReturnedPersonId as wrpersonid, pwr.firstname as wrfirstname, pwr.lastname as wrlastname, pwr.middlename as wrmiddlename, pwr.student_no as wrstudent_no, pgwr.mingroupid AS wrgroupid,\r\n\t\t            LoanLocation, LoanNotes, ReturnedStatus, ReturnedNotes,\r\n\t\t            p.LoanedToPersonId as ltpersonid, plt.firstname as ltfirstname, plt.lastname as ltlastname, plt.middlename as ltmiddlename, plt.student_no as ltstudent_no, pglt.mingroupid AS ltgroupid,\r\n\t\t            p.WhoModifiedPersonId as wmpersonid, pwm.firstname as wmfirstname, pwm.lastname as wmlastname, pwm.middlename as wmmiddlename, pwm.student_no as wmstudent_no, pgwm.mingroupid AS wmgroupid,\r\n\t\t            ModifiedDate, Reason, Accessories\r\n            from [InventoryV2_ProductSnapshot] p\r\n            LEFT JOIN people pic ON pic.personid=p.InChargePersonID\r\n            LEFT JOIN peoplemingroup pgic ON pgic.personid=p.InChargePersonID\r\n            LEFT JOIN people pwl ON pwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN peoplemingroup pgwl ON pgwl.personid=p.WhoLoanedPersonId\r\n            LEFT JOIN people pwr ON pwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN peoplemingroup pgwr ON pgwr.personid=p.WhoReturnedPersonId\r\n            LEFT JOIN people plt ON plt.personid=p.LoanedToPersonId\r\n            LEFT JOIN peoplemingroup pglt ON pglt.personid=p.LoanedToPersonId\r\n            LEFT JOIN people pwm ON pwm.personid=p.WhoModifiedPersonId\r\n            LEFT JOIN peoplemingroup pgwm ON pgwm.personid=p.WhoModifiedPersonId\r\n            where ProductUniqueID=@productuniqueid and LoanGroupId=@loangroupid and Reason=@reason\r\n            order by ModifiedDate";

		// Token: 0x040002B8 RID: 696
		internal const string DQ_DELETE_PRODUCT_BY_ID = "if not exists (select 1 from InventoryV2_Reservation r\r\n\t\t\t\t                inner join InventoryV2_ReservationGroup rg on rg.ReservationGroupId=r.ReservationGroupId\r\n\t\t\t\t                where r.ProductUniqueID=@productuniqueid and r.IsCompleted=0 and rg.ReservationEndDate > GETDATE())\r\n                begin\r\n\t                update InventoryV2_Product set IsActive=0, Barcode='' where ProductUniqueID=@productuniqueid AND LoanID is NULL\r\n                end";

		// Token: 0x040002B9 RID: 697
		internal const string UQ_ASSIGN_PRODUCT_BARCODE = "update [InventoryV2_Product] set BarCode=@barcode where ProductUniqueID=@productuniqueid";

		// Token: 0x040002BA RID: 698
		internal const string UQ_UPDATE_PRODUCT = "update InventoryV2_Product set\r\n            ProductName = @productname,\r\n            SerialNumber = @serialnumber,\r\n            ProductStatusID = @productstatusid,\r\n            CategoryName = @categoryname,\r\n            ProductDescription = @productdescription,\r\n            ProductNotes = @productnotes,\r\n            Thumbnail = @thumbnail,\r\n            Vendor = @vendor,\r\n            PurchaseDate = @purchasedate,\r\n            PurchaseAmount = @purchaseamount,\r\n            WarrantyExpirationDate = @warrantyexpirationdate,\r\n            PurchaseInfo = @purchaseinfo,\r\n            LocationID = @locationid,\r\n            LocationDate = @locationdate,\r\n            InChargePersonID = @inchargepersonid,\r\n            GroupID = @groupid,\r\n            BarCode = @barcode,\r\n            Accessories = @accessories\r\n            where ProductUniqueID = @productuniqueid";

		// Token: 0x040002BB RID: 699
		internal const string UQ_CHANGE_PRODUCTS_CATEGORY = "update InventoryV2_Product\r\n                    set CategoryName=@categoryname\r\n                    where ProductDynamicDataID in (select OrderID as ProductDynamicDataID from SplitOrderIDs(@productids, ','))";

		// Token: 0x040002BC RID: 700
		internal const string UQ_ASSIGN_PRODUCT_TO_GROUP = "UPDATE InventoryV2_Product\r\n                SET GroupID=@groupid\r\n                WHERE ProductUniqueId=@productuniqueid AND\r\n\t                  CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002BD RID: 701
		internal const string UQ_ASSIGN_PRODUCTS_TO_GROUP = "UPDATE InventoryV2_Product\r\n                SET GroupID=@groupid\r\n                WHERE ProductDynamicDataID IN (select OrderID as ProductDynamicDataID from SplitOrderIDs(@productidlist, ',')) AND\r\n\t                  CategoryName in (select OrderID as CategoryName from SplitStrings2(@allowedcategories, ','))";

		// Token: 0x040002BE RID: 702
		internal const string IQ_NEW_PRODUCT = "insert into InventoryV2_Product\r\n            (ProductName, SerialNumber, ProductStatusID, CategoryName, ProductDescription, ProductNotes, Thumbnail, Vendor, PurchaseDate, PurchaseAmount, WarrantyExpirationDate, PurchaseInfo, LocationID, LocationDate, InChargePersonID, GroupID, BarCode, Accessories )\r\n            values (@productname, @serialnumber, @productstatusid, @categoryname, @productdescription, @productnotes, @thumbnail, @vendor, @purchasedate, @purchaseamount, @warrantyexpirationdate, @purchaseinfo, @locationid, @locationdate, @inchargepersonid, @groupid, @barcode, @accessories )\r\n            set @productdynamicdataid = Scope_Identity()\r\n            set @productuniqueid = (select top(1) ProductUniqueId from InventoryV2_Product where ProductDynamicDataID=@productdynamicdataid)";

		// Token: 0x040002BF RID: 703
		internal const string IQ_PRODUCT_SNAPSHOT = "insert into [InventoryV2_ProductSnapshot]\r\n                            (ProductUniqueID\r\n                            ,ProductDynamicDataID\r\n                            ,ProductName\r\n                            ,BarCode\r\n                            ,SerialNumber\r\n                            ,CategoryName\r\n                            ,Location\r\n                            ,LocationDate\r\n                            ,InChargePersonID\r\n                            ,GroupName\r\n                            ,ProductStatus\r\n                            ,WhoModifiedPersonId\r\n                            ,Reason\r\n                            ,Accessories)\r\n            Values\r\n                            (@productuniqueid\r\n                            ,@productdynamicdataid\r\n                            ,@productname\r\n                            ,@barcode\r\n                            ,@serialnumber\r\n                            ,@categoryname\r\n                            ,@location\r\n                            ,@locationdate\r\n                            ,@inchargepersonid\r\n                            ,@groupname\r\n                            ,@productstatus\r\n                            ,@whomodifiedpersonid\r\n                            ,@reason\r\n                            ,@accessories)\r\n            set @productsnapshotid = SCOPE_IDENTITY()";

		// Token: 0x040002C0 RID: 704
		internal const string IQ_CREATE_PRODUCT_SNAPSHOT = "insert into [InventoryV2_ProductSnapshot]\r\n                            (ProductUniqueID\r\n                            ,ProductDynamicDataID\r\n                            ,ProductName\r\n                            ,BarCode\r\n                            ,SerialNumber\r\n                            ,CategoryName\r\n                            ,Location\r\n                            ,LocationDate\r\n                            ,InChargePersonID\r\n                            ,GroupName\r\n                            ,ProductStatus\r\n\t\t\t\t            ,ReturnLoanID\r\n\t\t\t\t            ,LoanGroupId\r\n\t\t\t\t            ,LoanedDate\r\n\t\t\t\t            ,DueDate\r\n\t\t\t\t            ,ReturnedDate\r\n\t\t\t\t            ,LoanedToPersonId\r\n\t\t\t\t            ,LoanLocation\r\n\t\t\t\t            ,WhoLoanedPersonId\r\n\t\t\t\t            ,WhoReturnedPersonId\r\n\t\t\t\t            ,LoanNotes\r\n\t\t\t\t            ,ReturnedStatus\r\n\t\t\t\t            ,ReturnedNotes\r\n\t\t\t\t            ,WhoModifiedPersonId\r\n                            ,Reason\r\n                            ,Accessories)\r\n\t            Values\r\n                            (@productuniqueid\r\n                            ,@productdynamicdataid\r\n                            ,@productname\r\n                            ,@barcode\r\n                            ,@serialnumber\r\n                            ,@categoryname\r\n                            ,@productlocation\r\n                            ,@locationdate\r\n                            ,@inchargepersonid\r\n                            ,@groupname\r\n                            ,@productstatus\r\n\t\t\t\t            ,@loanid\r\n\t\t\t\t            ,@loangroupid\r\n\t\t\t\t            ,@loaneddate\r\n\t\t\t\t            ,@duedate\r\n\t\t\t\t            ,@returneddate\r\n\t\t\t\t            ,@loanedtopersonid\r\n\t\t\t\t            ,@loanlocation\r\n\t\t\t\t            ,@WhoLoanedPersonId\r\n\t\t\t\t            ,@whoreturnedid\r\n\t\t\t\t            ,@loannotes\r\n\t\t\t\t            ,@returnedstatus\r\n\t\t\t\t            ,@returnednotes\r\n\t\t\t\t            ,@whomodifiedpersonid\r\n\t\t\t\t            ,@reason\r\n                            ,@accessories)\r\n\r\n            set @productsnapshotid = SCOPE_IDENTITY()";
	}
}
