using System;

namespace TechnoPro.Common.DAO.Impl.StudentAccommodationRequests
{
	// Token: 0x02000042 RID: 66
	public class QueryStorageStudentAccommodationRequest
	{
		// Token: 0x1700004F RID: 79
		// (get) Token: 0x060001BE RID: 446 RVA: 0x00010068 File Offset: 0x0000E268
		public static string QS_REQUESTS_BY_STATUS
		{
			get
			{
				return string.Format("SET ARITHABORT ON\r\nSELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.isactive=1\r\n        AND (sar.status & @statuses)>0\r\n        {0}\r\nORDER BY sar.StudentCourseAccommodationRequestId,sar.personid,sar.lucourseid", "AND (@startdate IS NULL OR (NOT luc.lucourseid IS NULL AND NOT ( ( luc.enddate<@startdate ) OR (luc.startdate > @enddate ) ) ))");
			}
		}

		// Token: 0x17000050 RID: 80
		// (get) Token: 0x060001BF RID: 447 RVA: 0x00010079 File Offset: 0x0000E279
		public static string QS_REQUESTS_BY_STATUS_FUTURE
		{
			get
			{
				return string.Format("SET ARITHABORT ON\r\nSELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.isactive=1\r\n        AND (sar.status & @statuses)>0\r\n        {0}\r\nORDER BY sar.StudentCourseAccommodationRequestId,sar.personid,sar.lucourseid", "AND NOT luc.lucourseid IS NULL AND luc.enddate>@mindate");
			}
		}

		// Token: 0x040000BB RID: 187
		internal const string QS_REQUEST_BY_ID = "SELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.StudentCourseAccommodationRequestId=@id";

		// Token: 0x040000BC RID: 188
		internal const string QS_REQUEST_BY_STUDENT_AND_COURSE = "SELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.personid=@pid AND sar.lucourseid=@lucid";

		// Token: 0x040000BD RID: 189
		internal const string QS_REQUESTS_BY_STUDENT_AND_DATE = "SELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.personid=@pid AND sar.lucourseid IN\r\n        (SELECT lucourseid FROM lucourses WHERE NOT ( enddate <= @startdate OR startdate > @enddate))\r\n        AND sar.isactive=1\r\nORDER BY sar.StudentCourseAccommodationRequestId,sar.personid,sar.lucourseid";

		// Token: 0x040000BE RID: 190
		internal const string QS_REQUESTS_BY_STATUS_BASE = "SET ARITHABORT ON\r\nSELECT    sar.StudentCourseAccommodationRequestId,sar.personid,p.firstname,p.lastname,p.middlename,p.student_no,\r\n            sar.lucourseid,sar.status,sar.daterequested,\r\n            sar.accommodationchangesrequested,sar.additionalaccommodationsrequested,\r\n            sar.whoapprovedpersonid,sar.dateapproved,pa.firstname AS whoapprovedfirstname,pa.lastname AS whoapprovedlastname,pa.student_no AS whoapprovedstudent_no,\r\n            sar.whoenteredpersonid,sar.dateentered,pe.firstname AS whoenteredfirstname,pe.lastname AS whoenteredlastname,pe.student_no AS whoenteredstudent_no,\r\n            sar.note1,sar.note2,sar.isactive,\r\n            sari.StudentCourseAccommodationModificationRequestItemId,sari.controlid,\r\n            sari.modificationtype,sari.note1 AS sarinote1,sari.note2 AS sarinote2,\r\n            sari.status AS saristatus,sari.dateentered AS saridateentered,\r\n            sari.whoenteredpersonid AS sariwhoenteredpersonid,p2.firstname AS sariwhoenteredfirstname,p2.lastname AS sariwhoenteredlastname,p2.student_no AS sariwhoenteredstudent_no,\r\n            luc.startdate,luc.enddate,luc.duration,luc.term,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.section,luc.timeofday,\r\n            luc.campus,luc.department,luc.location,lucd.lookupstring AS subjectcode,\r\n            c.assignedcounsellorpid AS advisorpersonid,c.assignedcounsellorfirst AS advisorfirstname,\r\n            c.assignedcounsellorlast AS advisorlastname,c.assignedcounsellorfirst AS advisorstudent_no,\r\n            vp.instructorid,vp.instructorname,vp.instructoremail,vp.instructorphone,vp.instructorusername,vp.instructorexternalid,vp.instructoremployeeid\r\nFROM    StudentCourseAccommodationRequest sar LEFT JOIN StudentCourseAccommodationModificationRequestItem sari ON sari.StudentCourseAccommodationRequestId=sar.StudentCourseAccommodationRequestId\r\n        LEFT JOIN people p ON p.personid=sar.personid\r\n        LEFT JOIN people pa ON pa.personid=sar.whoapprovedpersonid\r\n        LEFT JOIN people pe ON pe.personid=sar.whoenteredpersonid\r\n        LEFT JOIN people p2 ON p2.personid=sari.whoenteredpersonid\r\n        LEFT JOIN lucourses luc ON luc.lucourseid=sar.lucourseid\r\n        LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n        LEFT JOIN common c ON c.personid=sar.personid\r\n        LEFT JOIN vinstructorprimarylist vp ON vp.lucourseid=sar.lucourseid\r\nWHERE   sar.isactive=1\r\n        AND (sar.status & @statuses)>0\r\n        {0}\r\nORDER BY sar.StudentCourseAccommodationRequestId,sar.personid,sar.lucourseid";

		// Token: 0x040000BF RID: 191
		internal const string QI_REQUEST = "DECLARE @existingid int\r\nSET @existingid=(SELECT TOP 1 StudentCourseAccommodationRequestId FROM StudentCourseAccommodationRequest WHERE personid=@pid AND lucourseid=@lucid)\r\n\r\nIF NOT @existingid IS NULL AND @existingid > 0\r\nBEGIN\r\n    SET @id=@existingid\r\n\r\n    UPDATE StudentCourseAccommodationRequest \r\n\tSET status=@status,note1=@note1,note2=@note2,accommodationchangesrequested=@AccommodationChangesRequested,additionalaccommodationsrequested=@AdditionalAccommodationsRequested,\r\n\tDateApproved=CASE WHEN NOT @status=8 THEN NULL WHEN DateApproved IS NULL THEN getdate() ELSE DateApproved END\r\n\tWHERE StudentCourseAccommodationRequestId=@id\r\n    SET @wasinserted=0\r\nEND\r\nELSE\r\nBEGIN\r\n    INSERT INTO StudentCourseAccommodationRequest (personid,lucourseid,status,accommodationchangesrequested,additionalaccommodationsrequested,whoenteredpersonid,note1,note2,dateapproved)\r\n        VALUES (@pid,@lucid,@status,@AccommodationChangesRequested,@AdditionalAccommodationsRequested,@whoenteredpersonid,@note1,@note2,CASE WHEN @status=8 THEN getdate() ELSE NULL END);\r\n    SET @id = (SELECT TOP 1 CAST(SCOPE_IDENTITY() AS int) AS StudentCourseAccommodationRequestId)\r\n    SET @wasinserted=1\r\nEND";

		// Token: 0x040000C0 RID: 192
		internal const string QI_ADD_ARCHIVE_ENTRY = "INSERT INTO archive_StudentCourseAccommodationRequest \r\n\t(HowModified,WhoModified,StudentCourseAccommodationRequestId,personid,lucourseid,[status],daterequested,\r\n\t AccommodationChangesRequested,AdditionalAccommodationsRequested,Note1,Note2)\r\nVALUES\r\n\t(@howmodified,@whomodified,@id,@pid,@lucid,@status,@daterequested,@changes,@additional,@note1,@note2)";

		// Token: 0x040000C1 RID: 193
		internal const string QU_REQUEST = "UPDATE StudentCourseAccommodationRequest \r\nSET     status=@status,note1=@note1,note2=@note2,\r\n        DateApproved=CASE WHEN NOT @status=8 THEN NULL WHEN DateApproved IS NULL THEN getdate() ELSE DateApproved END\r\nWHERE   StudentCourseAccommodationRequestId=@id";

		// Token: 0x040000C2 RID: 194
		internal const string QU_REQUEST_STATUS = "UPDATE    StudentCourseAccommodationRequest \r\nSET         status=@status,\r\n            DateApproved=CASE WHEN NOT @status=8 THEN NULL WHEN DateApproved IS NULL THEN getdate() ELSE DateApproved END\r\nWHERE       StudentCourseAccommodationRequestId=@id";

		// Token: 0x040000C3 RID: 195
		internal const string QD_DELETE_REQUEST = "UPDATE StudentCourseAccommodationRequest SET isactive=0 WHERE StudentCourseAccommodationRequestId=@id";
	}
}
