using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	// Token: 0x020003C1 RID: 961
	[Designer("System.Windows.Forms.Design.ToolStripMenuItemDesigner, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
	[DefaultProperty("DropDownItems")]
	public abstract class ToolStripDropDownItem : ToolStripItem
	{
		// Token: 0x060040EA RID: 16618 RVA: 0x00114D7B File Offset: 0x00112F7B
		protected ToolStripDropDownItem()
		{
		}

		// Token: 0x060040EB RID: 16619 RVA: 0x00114D8A File Offset: 0x00112F8A
		protected ToolStripDropDownItem(string text, Image image, EventHandler onClick) : base(text, image, onClick)
		{
		}

		// Token: 0x060040EC RID: 16620 RVA: 0x00114D9C File Offset: 0x00112F9C
		protected ToolStripDropDownItem(string text, Image image, EventHandler onClick, string name) : base(text, image, onClick, name)
		{
		}

		// Token: 0x060040ED RID: 16621 RVA: 0x00114DB0 File Offset: 0x00112FB0
		protected ToolStripDropDownItem(string text, Image image, params ToolStripItem[] dropDownItems) : this(text, image, null)
		{
			if (dropDownItems != null)
			{
				this.DropDownItems.AddRange(dropDownItems);
			}
		}

		// Token: 0x17000FD5 RID: 4053
		// (get) Token: 0x060040EE RID: 16622 RVA: 0x00114DCC File Offset: 0x00112FCC
		// (set) Token: 0x060040EF RID: 16623 RVA: 0x00114E28 File Offset: 0x00113028
		[TypeConverter(typeof(ReferenceConverter))]
		[SRCategory("CatData")]
		[SRDescription("ToolStripDropDownDescr")]
		public ToolStripDropDown DropDown
		{
			get
			{
				if (this.dropDown == null)
				{
					this.DropDown = this.CreateDefaultDropDown();
					if (!(this is ToolStripOverflowButton))
					{
						this.dropDown.SetAutoGeneratedInternal(true);
					}
					if (base.ParentInternal != null)
					{
						this.dropDown.ShowItemToolTips = base.ParentInternal.ShowItemToolTips;
					}
				}
				return this.dropDown;
			}
			set
			{
				if (this.dropDown != value)
				{
					if (this.dropDown != null)
					{
						this.dropDown.Opened -= this.DropDown_Opened;
						this.dropDown.Closed -= this.DropDown_Closed;
						this.dropDown.ItemClicked -= this.DropDown_ItemClicked;
						this.dropDown.UnassignDropDownItem();
					}
					this.dropDown = value;
					if (this.dropDown != null)
					{
						this.dropDown.Opened += this.DropDown_Opened;
						this.dropDown.Closed += this.DropDown_Closed;
						this.dropDown.ItemClicked += this.DropDown_ItemClicked;
						this.dropDown.AssignToDropDownItem();
					}
				}
			}
		}

		// Token: 0x17000FD6 RID: 4054
		// (get) Token: 0x060040F0 RID: 16624 RVA: 0x00114EF8 File Offset: 0x001130F8
		internal virtual Rectangle DropDownButtonArea
		{
			get
			{
				return this.Bounds;
			}
		}

		// Token: 0x17000FD7 RID: 4055
		// (get) Token: 0x060040F1 RID: 16625 RVA: 0x00114F00 File Offset: 0x00113100
		// (set) Token: 0x060040F2 RID: 16626 RVA: 0x00114FE0 File Offset: 0x001131E0
		[Browsable(false)]
		[SRDescription("ToolStripDropDownItemDropDownDirectionDescr")]
		[SRCategory("CatBehavior")]
		public ToolStripDropDownDirection DropDownDirection
		{
			get
			{
				if (this.toolStripDropDownDirection == ToolStripDropDownDirection.Default)
				{
					ToolStrip parentInternal = base.ParentInternal;
					if (parentInternal != null)
					{
						ToolStripDropDownDirection toolStripDropDownDirection = parentInternal.DefaultDropDownDirection;
						if (this.OppositeDropDownAlign || (this.RightToLeft != parentInternal.RightToLeft && this.RightToLeft != RightToLeft.Inherit))
						{
							toolStripDropDownDirection = this.RTLTranslateDropDownDirection(toolStripDropDownDirection, this.RightToLeft);
						}
						if (base.IsOnDropDown)
						{
							Rectangle dropDownBounds = this.GetDropDownBounds(toolStripDropDownDirection);
							Rectangle b = new Rectangle(base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords), this.Size);
							Rectangle rectangle = Rectangle.Intersect(dropDownBounds, b);
							if (rectangle.Width >= 2)
							{
								RightToLeft rightToLeft = (this.RightToLeft == RightToLeft.Yes) ? RightToLeft.No : RightToLeft.Yes;
								ToolStripDropDownDirection toolStripDropDownDirection2 = this.RTLTranslateDropDownDirection(toolStripDropDownDirection, rightToLeft);
								int width = Rectangle.Intersect(this.GetDropDownBounds(toolStripDropDownDirection2), b).Width;
								if (width < rectangle.Width)
								{
									toolStripDropDownDirection = toolStripDropDownDirection2;
								}
							}
						}
						return toolStripDropDownDirection;
					}
				}
				return this.toolStripDropDownDirection;
			}
			set
			{
				if (value > ToolStripDropDownDirection.Right && value != ToolStripDropDownDirection.Default)
				{
					throw new InvalidEnumArgumentException("value", (int)value, typeof(ToolStripDropDownDirection));
				}
				if (this.toolStripDropDownDirection != value)
				{
					this.toolStripDropDownDirection = value;
					if (this.HasDropDownItems && this.DropDown.Visible)
					{
						this.DropDown.Location = this.DropDownLocation;
					}
				}
			}
		}

		// Token: 0x14000334 RID: 820
		// (add) Token: 0x060040F3 RID: 16627 RVA: 0x00115041 File Offset: 0x00113241
		// (remove) Token: 0x060040F4 RID: 16628 RVA: 0x00115054 File Offset: 0x00113254
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownClosedDecr")]
		public event EventHandler DropDownClosed
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownClosed, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownClosed, value);
			}
		}

		// Token: 0x17000FD8 RID: 4056
		// (get) Token: 0x060040F5 RID: 16629 RVA: 0x00115068 File Offset: 0x00113268
		protected internal virtual Point DropDownLocation
		{
			get
			{
				if (base.ParentInternal == null || !this.HasDropDownItems)
				{
					return Point.Empty;
				}
				ToolStripDropDownDirection dropDownDirection = this.DropDownDirection;
				return this.GetDropDownBounds(dropDownDirection).Location;
			}
		}

		// Token: 0x14000335 RID: 821
		// (add) Token: 0x060040F6 RID: 16630 RVA: 0x001150A1 File Offset: 0x001132A1
		// (remove) Token: 0x060040F7 RID: 16631 RVA: 0x001150B4 File Offset: 0x001132B4
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpeningDescr")]
		public event EventHandler DropDownOpening
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownShow, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownShow, value);
			}
		}

		// Token: 0x14000336 RID: 822
		// (add) Token: 0x060040F8 RID: 16632 RVA: 0x001150C7 File Offset: 0x001132C7
		// (remove) Token: 0x060040F9 RID: 16633 RVA: 0x001150DA File Offset: 0x001132DA
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpenedDescr")]
		public event EventHandler DropDownOpened
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownOpened, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownOpened, value);
			}
		}

		// Token: 0x17000FD9 RID: 4057
		// (get) Token: 0x060040FA RID: 16634 RVA: 0x001150ED File Offset: 0x001132ED
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
		[SRCategory("CatData")]
		[SRDescription("ToolStripDropDownItemsDescr")]
		public ToolStripItemCollection DropDownItems
		{
			get
			{
				return this.DropDown.Items;
			}
		}

		// Token: 0x14000337 RID: 823
		// (add) Token: 0x060040FB RID: 16635 RVA: 0x001150FA File Offset: 0x001132FA
		// (remove) Token: 0x060040FC RID: 16636 RVA: 0x0011510D File Offset: 0x0011330D
		[SRCategory("CatAction")]
		public event ToolStripItemClickedEventHandler DropDownItemClicked
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDownItem.EventDropDownItemClicked, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDownItem.EventDropDownItemClicked, value);
			}
		}

		// Token: 0x17000FDA RID: 4058
		// (get) Token: 0x060040FD RID: 16637 RVA: 0x00115120 File Offset: 0x00113320
		[Browsable(false)]
		public virtual bool HasDropDownItems
		{
			get
			{
				return this.dropDown != null && this.dropDown.HasVisibleItems;
			}
		}

		// Token: 0x17000FDB RID: 4059
		// (get) Token: 0x060040FE RID: 16638 RVA: 0x00115137 File Offset: 0x00113337
		[Browsable(false)]
		public bool HasDropDown
		{
			get
			{
				return this.dropDown != null;
			}
		}

		// Token: 0x17000FDC RID: 4060
		// (get) Token: 0x060040FF RID: 16639 RVA: 0x00115144 File Offset: 0x00113344
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public override bool Pressed
		{
			get
			{
				if (this.dropDown != null && (this.DropDown.AutoClose || !base.IsInDesignMode || (base.IsInDesignMode && !base.IsOnDropDown)))
				{
					return this.DropDown.OwnerItem == this && this.DropDown.Visible;
				}
				return base.Pressed;
			}
		}

		// Token: 0x17000FDD RID: 4061
		// (get) Token: 0x06004100 RID: 16640 RVA: 0x00011A20 File Offset: 0x0000FC20
		internal virtual bool OppositeDropDownAlign
		{
			get
			{
				return false;
			}
		}

		// Token: 0x06004101 RID: 16641 RVA: 0x001151A0 File Offset: 0x001133A0
		internal virtual void AutoHide(ToolStripItem otherItemBeingSelected)
		{
			this.HideDropDown();
		}

		// Token: 0x06004102 RID: 16642 RVA: 0x001151A8 File Offset: 0x001133A8
		protected override AccessibleObject CreateAccessibilityInstance()
		{
			return new ToolStripDropDownItemAccessibleObject(this);
		}

		// Token: 0x06004103 RID: 16643 RVA: 0x001151B0 File Offset: 0x001133B0
		protected virtual ToolStripDropDown CreateDefaultDropDown()
		{
			return new ToolStripDropDown(this, true);
		}

		// Token: 0x06004104 RID: 16644 RVA: 0x001151BC File Offset: 0x001133BC
		private Rectangle DropDownDirectionToDropDownBounds(ToolStripDropDownDirection dropDownDirection, Rectangle dropDownBounds)
		{
			Point empty = Point.Empty;
			switch (dropDownDirection)
			{
			case ToolStripDropDownDirection.AboveLeft:
				empty.X = -dropDownBounds.Width + base.Width;
				empty.Y = -dropDownBounds.Height + 1;
				break;
			case ToolStripDropDownDirection.AboveRight:
				empty.Y = -dropDownBounds.Height + 1;
				break;
			case ToolStripDropDownDirection.BelowLeft:
				empty.X = -dropDownBounds.Width + base.Width;
				empty.Y = base.Height - 1;
				break;
			case ToolStripDropDownDirection.BelowRight:
				empty.Y = base.Height - 1;
				break;
			case ToolStripDropDownDirection.Left:
				empty.X = -dropDownBounds.Width;
				break;
			case ToolStripDropDownDirection.Right:
				empty.X = base.Width;
				if (!base.IsOnDropDown)
				{
					empty.X--;
				}
				break;
			}
			Point point = base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords);
			dropDownBounds.Location = new Point(point.X + empty.X, point.Y + empty.Y);
			dropDownBounds = WindowsFormsUtils.ConstrainToScreenWorkingAreaBounds(dropDownBounds);
			return dropDownBounds;
		}

		// Token: 0x06004105 RID: 16645 RVA: 0x001152DF File Offset: 0x001134DF
		private void DropDown_Closed(object sender, ToolStripDropDownClosedEventArgs e)
		{
			this.OnDropDownClosed(EventArgs.Empty);
		}

		// Token: 0x06004106 RID: 16646 RVA: 0x001152EC File Offset: 0x001134EC
		private void DropDown_Opened(object sender, EventArgs e)
		{
			this.OnDropDownOpened(EventArgs.Empty);
		}

		// Token: 0x06004107 RID: 16647 RVA: 0x001152F9 File Offset: 0x001134F9
		private void DropDown_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
		{
			this.OnDropDownItemClicked(e);
		}

		// Token: 0x06004108 RID: 16648 RVA: 0x00115304 File Offset: 0x00113504
		protected override void Dispose(bool disposing)
		{
			if (this.dropDown != null)
			{
				this.dropDown.Opened -= this.DropDown_Opened;
				this.dropDown.Closed -= this.DropDown_Closed;
				this.dropDown.ItemClicked -= this.DropDown_ItemClicked;
				if (disposing && this.dropDown.IsAutoGenerated)
				{
					this.dropDown.Dispose();
					this.dropDown = null;
				}
			}
			base.Dispose(disposing);
		}

		// Token: 0x06004109 RID: 16649 RVA: 0x00115388 File Offset: 0x00113588
		private Rectangle GetDropDownBounds(ToolStripDropDownDirection dropDownDirection)
		{
			Rectangle rectangle = new Rectangle(Point.Empty, this.DropDown.GetSuggestedSize());
			rectangle = this.DropDownDirectionToDropDownBounds(dropDownDirection, rectangle);
			Rectangle b = new Rectangle(base.TranslatePoint(Point.Empty, ToolStripPointType.ToolStripItemCoords, ToolStripPointType.ScreenCoords), this.Size);
			if (Rectangle.Intersect(rectangle, b).Height > 1)
			{
				bool flag = this.RightToLeft == RightToLeft.Yes;
				if (Rectangle.Intersect(rectangle, b).Width > 1)
				{
					rectangle = this.DropDownDirectionToDropDownBounds((!flag) ? ToolStripDropDownDirection.Right : ToolStripDropDownDirection.Left, rectangle);
				}
				if (Rectangle.Intersect(rectangle, b).Width > 1)
				{
					rectangle = this.DropDownDirectionToDropDownBounds((!flag) ? ToolStripDropDownDirection.Left : ToolStripDropDownDirection.Right, rectangle);
				}
			}
			return rectangle;
		}

		// Token: 0x0600410A RID: 16650 RVA: 0x00115430 File Offset: 0x00113630
		public void HideDropDown()
		{
			this.OnDropDownHide(EventArgs.Empty);
			if (this.dropDown != null && this.dropDown.Visible)
			{
				this.DropDown.Visible = false;
				if (AccessibilityImprovements.Level1)
				{
					base.AccessibilityNotifyClients(AccessibleEvents.StateChange);
					base.AccessibilityNotifyClients(AccessibleEvents.NameChange);
				}
			}
		}

		// Token: 0x0600410B RID: 16651 RVA: 0x00115486 File Offset: 0x00113686
		protected override void OnFontChanged(EventArgs e)
		{
			base.OnFontChanged(e);
			if (this.dropDown != null)
			{
				this.dropDown.OnOwnerItemFontChanged(EventArgs.Empty);
			}
		}

		// Token: 0x0600410C RID: 16652 RVA: 0x001154A7 File Offset: 0x001136A7
		protected override void OnBoundsChanged()
		{
			base.OnBoundsChanged();
			if (this.dropDown != null && this.dropDown.Visible)
			{
				this.dropDown.Bounds = this.GetDropDownBounds(this.DropDownDirection);
			}
		}

		// Token: 0x0600410D RID: 16653 RVA: 0x001154DC File Offset: 0x001136DC
		protected override void OnRightToLeftChanged(EventArgs e)
		{
			base.OnRightToLeftChanged(e);
			if (this.HasDropDownItems)
			{
				if (this.DropDown.Visible)
				{
					LayoutTransaction.DoLayout(this.DropDown, this, PropertyNames.RightToLeft);
					return;
				}
				CommonProperties.xClearPreferredSizeCache(this.DropDown);
				this.DropDown.LayoutRequired = true;
			}
		}

		// Token: 0x0600410E RID: 16654 RVA: 0x0011552E File Offset: 0x0011372E
		internal override void OnImageScalingSizeChanged(EventArgs e)
		{
			base.OnImageScalingSizeChanged(e);
			if (this.HasDropDown && this.DropDown.IsAutoGenerated)
			{
				this.DropDown.DoLayoutIfHandleCreated(new ToolStripItemEventArgs(this));
			}
		}

		// Token: 0x0600410F RID: 16655 RVA: 0x00115560 File Offset: 0x00113760
		protected virtual void OnDropDownHide(EventArgs e)
		{
			base.Invalidate();
			EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownHide];
			if (eventHandler != null)
			{
				eventHandler(this, e);
			}
		}

		// Token: 0x06004110 RID: 16656 RVA: 0x00115594 File Offset: 0x00113794
		protected virtual void OnDropDownShow(EventArgs e)
		{
			EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownShow];
			if (eventHandler != null)
			{
				eventHandler(this, e);
			}
		}

		// Token: 0x06004111 RID: 16657 RVA: 0x001155C4 File Offset: 0x001137C4
		protected internal virtual void OnDropDownOpened(EventArgs e)
		{
			if (this.DropDown.OwnerItem == this)
			{
				EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownOpened];
				if (eventHandler != null)
				{
					eventHandler(this, e);
				}
			}
		}

		// Token: 0x06004112 RID: 16658 RVA: 0x00115600 File Offset: 0x00113800
		protected internal virtual void OnDropDownClosed(EventArgs e)
		{
			base.Invalidate();
			if (this.DropDown.OwnerItem == this)
			{
				EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDownItem.EventDropDownClosed];
				if (eventHandler != null)
				{
					eventHandler(this, e);
				}
				if (!this.DropDown.IsAutoGenerated)
				{
					this.DropDown.OwnerItem = null;
				}
			}
		}

		// Token: 0x06004113 RID: 16659 RVA: 0x0011565C File Offset: 0x0011385C
		protected internal virtual void OnDropDownItemClicked(ToolStripItemClickedEventArgs e)
		{
			if (this.DropDown.OwnerItem == this)
			{
				ToolStripItemClickedEventHandler toolStripItemClickedEventHandler = (ToolStripItemClickedEventHandler)base.Events[ToolStripDropDownItem.EventDropDownItemClicked];
				if (toolStripItemClickedEventHandler != null)
				{
					toolStripItemClickedEventHandler(this, e);
				}
			}
		}

		// Token: 0x06004114 RID: 16660 RVA: 0x00115698 File Offset: 0x00113898
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
		protected internal override bool ProcessCmdKey(ref Message m, Keys keyData)
		{
			if (this.HasDropDownItems)
			{
				return this.DropDown.ProcessCmdKeyInternal(ref m, keyData);
			}
			return base.ProcessCmdKey(ref m, keyData);
		}

		// Token: 0x06004115 RID: 16661 RVA: 0x001156B8 File Offset: 0x001138B8
		[UIPermission(SecurityAction.LinkDemand, Window = UIPermissionWindow.AllWindows)]
		protected internal override bool ProcessDialogKey(Keys keyData)
		{
			Keys keys = keyData & Keys.KeyCode;
			if (this.HasDropDownItems)
			{
				bool flag = !base.IsOnDropDown || base.IsOnOverflow;
				if (flag && (keys == Keys.Down || keys == Keys.Up || keys == Keys.Return || (base.SupportsSpaceKey && keys == Keys.Space)))
				{
					if (this.Enabled || base.DesignMode)
					{
						this.ShowDropDown();
						if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
						{
							KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
						}
						this.DropDown.SelectNextToolStripItem(null, true);
					}
					return true;
				}
				if (!flag)
				{
					bool flag2 = (this.DropDownDirection & ToolStripDropDownDirection.AboveRight) == ToolStripDropDownDirection.AboveLeft;
					bool flag3 = keys == Keys.Return || (base.SupportsSpaceKey && keys == Keys.Space) || (flag2 && keys == Keys.Left) || (!flag2 && keys == Keys.Right);
					if (flag3)
					{
						if (this.Enabled || base.DesignMode)
						{
							this.ShowDropDown();
							if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
							{
								KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
							}
							this.DropDown.SelectNextToolStripItem(null, true);
						}
						return true;
					}
				}
			}
			if (base.IsOnDropDown)
			{
				bool flag4 = (this.DropDownDirection & ToolStripDropDownDirection.AboveRight) == ToolStripDropDownDirection.AboveLeft;
				bool flag5 = (flag4 && keys == Keys.Right) || (!flag4 && keys == Keys.Left);
				if (flag5)
				{
					ToolStripDropDown currentParentDropDown = base.GetCurrentParentDropDown();
					if (currentParentDropDown != null && !currentParentDropDown.IsFirstDropDown)
					{
						currentParentDropDown.SetCloseReason(ToolStripDropDownCloseReason.Keyboard);
						if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
						{
							KeyboardToolTipStateMachine.Instance.NotifyAboutLostFocus(this);
						}
						currentParentDropDown.SelectPreviousToolStrip();
						return true;
					}
				}
			}
			return base.ProcessDialogKey(keyData);
		}

		// Token: 0x06004116 RID: 16662 RVA: 0x00115830 File Offset: 0x00113A30
		private ToolStripDropDownDirection RTLTranslateDropDownDirection(ToolStripDropDownDirection dropDownDirection, RightToLeft rightToLeft)
		{
			switch (dropDownDirection)
			{
			case ToolStripDropDownDirection.AboveLeft:
				return ToolStripDropDownDirection.AboveRight;
			case ToolStripDropDownDirection.AboveRight:
				return ToolStripDropDownDirection.AboveLeft;
			case ToolStripDropDownDirection.BelowLeft:
				return ToolStripDropDownDirection.BelowRight;
			case ToolStripDropDownDirection.BelowRight:
				return ToolStripDropDownDirection.BelowLeft;
			case ToolStripDropDownDirection.Left:
				return ToolStripDropDownDirection.Right;
			case ToolStripDropDownDirection.Right:
				return ToolStripDropDownDirection.Left;
			default:
				if (base.IsOnDropDown)
				{
					if (rightToLeft != RightToLeft.Yes)
					{
						return ToolStripDropDownDirection.Right;
					}
					return ToolStripDropDownDirection.Left;
				}
				else
				{
					if (rightToLeft != RightToLeft.Yes)
					{
						return ToolStripDropDownDirection.BelowRight;
					}
					return ToolStripDropDownDirection.BelowLeft;
				}
				break;
			}
		}

		// Token: 0x06004117 RID: 16663 RVA: 0x00115880 File Offset: 0x00113A80
		public void ShowDropDown()
		{
			this.ShowDropDown(false);
		}

		// Token: 0x06004118 RID: 16664 RVA: 0x0011588C File Offset: 0x00113A8C
		internal void ShowDropDown(bool mousePush)
		{
			this.ShowDropDownInternal();
			ToolStripDropDownMenu toolStripDropDownMenu = this.dropDown as ToolStripDropDownMenu;
			if (toolStripDropDownMenu != null)
			{
				if (!mousePush)
				{
					toolStripDropDownMenu.ResetScrollPosition();
				}
				toolStripDropDownMenu.RestoreScrollPosition();
			}
		}

		// Token: 0x06004119 RID: 16665 RVA: 0x001158C0 File Offset: 0x00113AC0
		private void ShowDropDownInternal()
		{
			if (this.dropDown == null || !this.dropDown.Visible)
			{
				this.OnDropDownShow(EventArgs.Empty);
			}
			if (this.dropDown != null && !this.dropDown.Visible)
			{
				if (this.dropDown.IsAutoGenerated && this.DropDownItems.Count <= 0)
				{
					return;
				}
				if (this.DropDown == base.ParentInternal)
				{
					throw new InvalidOperationException(SR.GetString("ToolStripShowDropDownInvalidOperation"));
				}
				this.dropDown.OwnerItem = this;
				this.dropDown.Location = this.DropDownLocation;
				this.dropDown.Show();
				base.Invalidate();
				if (AccessibilityImprovements.Level1)
				{
					base.AccessibilityNotifyClients(AccessibleEvents.StateChange);
					base.AccessibilityNotifyClients(AccessibleEvents.NameChange);
				}
			}
		}

		// Token: 0x0600411A RID: 16666 RVA: 0x0011598D File Offset: 0x00113B8D
		private bool ShouldSerializeDropDown()
		{
			return this.dropDown != null && !this.dropDown.IsAutoGenerated;
		}

		// Token: 0x0600411B RID: 16667 RVA: 0x001159A7 File Offset: 0x00113BA7
		private bool ShouldSerializeDropDownDirection()
		{
			return this.toolStripDropDownDirection != ToolStripDropDownDirection.Default;
		}

		// Token: 0x0600411C RID: 16668 RVA: 0x001159B5 File Offset: 0x00113BB5
		private bool ShouldSerializeDropDownItems()
		{
			return this.dropDown != null && this.dropDown.IsAutoGenerated;
		}

		// Token: 0x0600411D RID: 16669 RVA: 0x001159CC File Offset: 0x00113BCC
		internal override void OnKeyboardToolTipHook(ToolTip toolTip)
		{
			base.OnKeyboardToolTipHook(toolTip);
			KeyboardToolTipStateMachine.Instance.Hook(this.DropDown, toolTip);
		}

		// Token: 0x0600411E RID: 16670 RVA: 0x001159E6 File Offset: 0x00113BE6
		internal override void OnKeyboardToolTipUnhook(ToolTip toolTip)
		{
			base.OnKeyboardToolTipUnhook(toolTip);
			KeyboardToolTipStateMachine.Instance.Unhook(this.DropDown, toolTip);
		}

		// Token: 0x0600411F RID: 16671 RVA: 0x00115A00 File Offset: 0x00113C00
		internal override void ToolStrip_RescaleConstants(int oldDpi, int newDpi)
		{
			base.RescaleConstantsInternal(newDpi);
			Stack<ToolStripDropDownItem> stack = new Stack<ToolStripDropDownItem>();
			stack.Push(this);
			while (stack.Count > 0)
			{
				ToolStripDropDownItem toolStripDropDownItem = stack.Pop();
				if (toolStripDropDownItem.dropDown != null)
				{
					toolStripDropDownItem.dropDown.deviceDpi = newDpi;
					toolStripDropDownItem.dropDown.ResetScaling(newDpi);
					foreach (object obj in toolStripDropDownItem.DropDown.Items)
					{
						ToolStripItem toolStripItem = (ToolStripItem)obj;
						if (toolStripItem != null)
						{
							Font font = toolStripItem.Font;
							object obj2 = font;
							ToolStripItem ownerItem = toolStripItem.OwnerItem;
							if (!obj2.Equals((ownerItem != null) ? ownerItem.Font : null))
							{
								float num = (float)newDpi / (float)oldDpi;
								toolStripItem.Font = new Font(font.FontFamily, font.Size * num, font.Style, font.Unit, font.GdiCharSet, font.GdiVerticalFont);
							}
							toolStripItem.DeviceDpi = newDpi;
							if (typeof(ToolStripDropDownItem).IsAssignableFrom(toolStripItem.GetType()) && ((ToolStripDropDownItem)toolStripItem).dropDown != null)
							{
								stack.Push((ToolStripDropDownItem)toolStripItem);
							}
						}
					}
				}
			}
			base.ToolStrip_RescaleConstants(oldDpi, newDpi);
		}

		// Token: 0x040024EE RID: 9454
		private ToolStripDropDown dropDown;

		// Token: 0x040024EF RID: 9455
		private ToolStripDropDownDirection toolStripDropDownDirection = ToolStripDropDownDirection.Default;

		// Token: 0x040024F0 RID: 9456
		private static readonly object EventDropDownShow = new object();

		// Token: 0x040024F1 RID: 9457
		private static readonly object EventDropDownHide = new object();

		// Token: 0x040024F2 RID: 9458
		private static readonly object EventDropDownOpened = new object();

		// Token: 0x040024F3 RID: 9459
		private static readonly object EventDropDownClosed = new object();

		// Token: 0x040024F4 RID: 9460
		private static readonly object EventDropDownItemClicked = new object();
	}
}
