using System;
using System.Collections;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	// Token: 0x020003B9 RID: 953
	[Designer("System.Windows.Forms.Design.ToolStripDropDownDesigner, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
	[ComVisible(true)]
	[ClassInterface(ClassInterfaceType.AutoDispatch)]
	public class ToolStripDropDown : ToolStrip
	{
		// Token: 0x06003FFA RID: 16378 RVA: 0x00112B88 File Offset: 0x00110D88
		public ToolStripDropDown()
		{
			if (DpiHelper.EnableToolStripHighDpiImprovements)
			{
				this.scaledDefaultPadding = DpiHelper.LogicalToDeviceUnits(ToolStripDropDown.defaultPadding, 0);
			}
			bool isRestrictedWindow = this.IsRestrictedWindow;
			base.SuspendLayout();
			this.Initialize();
			base.ResumeLayout(false);
		}

		// Token: 0x06003FFB RID: 16379 RVA: 0x00112C0C File Offset: 0x00110E0C
		internal ToolStripDropDown(ToolStripItem ownerItem) : this()
		{
			this.ownerItem = ownerItem;
		}

		// Token: 0x06003FFC RID: 16380 RVA: 0x00112C1B File Offset: 0x00110E1B
		internal ToolStripDropDown(ToolStripItem ownerItem, bool isAutoGenerated) : this(ownerItem)
		{
			this.isAutoGenerated = isAutoGenerated;
		}

		// Token: 0x17000FA0 RID: 4000
		// (get) Token: 0x06003FFD RID: 16381 RVA: 0x00112C2B File Offset: 0x00110E2B
		// (set) Token: 0x06003FFE RID: 16382 RVA: 0x00112C33 File Offset: 0x00110E33
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new bool AllowItemReorder
		{
			get
			{
				return base.AllowItemReorder;
			}
			set
			{
				base.AllowItemReorder = value;
			}
		}

		// Token: 0x17000FA1 RID: 4001
		// (get) Token: 0x06003FFF RID: 16383 RVA: 0x00112C3C File Offset: 0x00110E3C
		// (set) Token: 0x06004000 RID: 16384 RVA: 0x00112C50 File Offset: 0x00110E50
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		[SRDescription("ControlAllowTransparencyDescr")]
		public bool AllowTransparency
		{
			get
			{
				return this.state[ToolStripDropDown.stateAllowTransparency];
			}
			set
			{
				if (value != this.state[ToolStripDropDown.stateAllowTransparency] && OSFeature.Feature.IsPresent(OSFeature.LayeredWindows))
				{
					this.state[ToolStripDropDown.stateAllowTransparency] = value;
					this.state[ToolStripDropDown.stateLayered] = this.state[ToolStripDropDown.stateAllowTransparency];
					base.UpdateStyles();
					if (!value)
					{
						if (base.Properties.ContainsObject(ToolStripDropDown.PropOpacity))
						{
							base.Properties.SetObject(ToolStripDropDown.PropOpacity, 1f);
						}
						this.UpdateLayered();
					}
				}
			}
		}

		// Token: 0x17000FA2 RID: 4002
		// (get) Token: 0x06004001 RID: 16385 RVA: 0x00112CED File Offset: 0x00110EED
		// (set) Token: 0x06004002 RID: 16386 RVA: 0x00112CF5 File Offset: 0x00110EF5
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public override AnchorStyles Anchor
		{
			get
			{
				return base.Anchor;
			}
			set
			{
				base.Anchor = value;
			}
		}

		// Token: 0x17000FA3 RID: 4003
		// (get) Token: 0x06004003 RID: 16387 RVA: 0x00112CFE File Offset: 0x00110EFE
		// (set) Token: 0x06004004 RID: 16388 RVA: 0x00112D06 File Offset: 0x00110F06
		[DefaultValue(true)]
		public override bool AutoSize
		{
			get
			{
				return this.autoSize;
			}
			set
			{
				if (this.autoSize != value)
				{
					this.autoSize = value;
					LayoutTransaction.DoLayout(this, this, PropertyNames.AutoSize);
					this.OnAutoSizeChanged(EventArgs.Empty);
				}
			}
		}

		// Token: 0x17000FA4 RID: 4004
		// (get) Token: 0x06004005 RID: 16389 RVA: 0x00112D2F File Offset: 0x00110F2F
		// (set) Token: 0x06004006 RID: 16390 RVA: 0x00112D37 File Offset: 0x00110F37
		[DefaultValue(true)]
		[SRCategory("CatBehavior")]
		[SRDescription("ToolStripDropDownAutoCloseDescr")]
		public bool AutoClose
		{
			get
			{
				return this.autoClose;
			}
			set
			{
				if (this.autoClose != value)
				{
					this.autoClose = value;
					this.ApplyTopMost(!this.autoClose);
				}
			}
		}

		// Token: 0x14000317 RID: 791
		// (add) Token: 0x06004007 RID: 16391 RVA: 0x00011AA1 File Offset: 0x0000FCA1
		// (remove) Token: 0x06004008 RID: 16392 RVA: 0x00011AAA File Offset: 0x0000FCAA
		[Browsable(false)]
		public new event EventHandler BackgroundImageChanged
		{
			add
			{
				base.BackgroundImageChanged += value;
			}
			remove
			{
				base.BackgroundImageChanged -= value;
			}
		}

		// Token: 0x14000318 RID: 792
		// (add) Token: 0x06004009 RID: 16393 RVA: 0x00011AC4 File Offset: 0x0000FCC4
		// (remove) Token: 0x0600400A RID: 16394 RVA: 0x00011ACD File Offset: 0x0000FCCD
		[Browsable(false)]
		public new event EventHandler BackgroundImageLayoutChanged
		{
			add
			{
				base.BackgroundImageLayoutChanged += value;
			}
			remove
			{
				base.BackgroundImageLayoutChanged -= value;
			}
		}

		// Token: 0x14000319 RID: 793
		// (add) Token: 0x0600400B RID: 16395 RVA: 0x00112D58 File Offset: 0x00110F58
		// (remove) Token: 0x0600400C RID: 16396 RVA: 0x00112D61 File Offset: 0x00110F61
		[Browsable(false)]
		public new event EventHandler BindingContextChanged
		{
			add
			{
				base.BindingContextChanged += value;
			}
			remove
			{
				base.BindingContextChanged -= value;
			}
		}

		// Token: 0x17000FA5 RID: 4005
		// (get) Token: 0x0600400D RID: 16397 RVA: 0x000D8F84 File Offset: 0x000D7184
		// (set) Token: 0x0600400E RID: 16398 RVA: 0x000D8F8C File Offset: 0x000D718C
		[DefaultValue(false)]
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new bool CanOverflow
		{
			get
			{
				return base.CanOverflow;
			}
			set
			{
				base.CanOverflow = value;
			}
		}

		// Token: 0x1400031A RID: 794
		// (add) Token: 0x0600400F RID: 16399 RVA: 0x00112D6A File Offset: 0x00110F6A
		// (remove) Token: 0x06004010 RID: 16400 RVA: 0x00112D73 File Offset: 0x00110F73
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event UICuesEventHandler ChangeUICues
		{
			add
			{
				base.ChangeUICues += value;
			}
			remove
			{
				base.ChangeUICues -= value;
			}
		}

		// Token: 0x17000FA6 RID: 4006
		// (get) Token: 0x06004011 RID: 16401 RVA: 0x00011B2D File Offset: 0x0000FD2D
		// (set) Token: 0x06004012 RID: 16402 RVA: 0x0001A24D File Offset: 0x0001844D
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new ContextMenu ContextMenu
		{
			get
			{
				return base.ContextMenu;
			}
			set
			{
				base.ContextMenu = value;
			}
		}

		// Token: 0x1400031B RID: 795
		// (add) Token: 0x06004013 RID: 16403 RVA: 0x00112D7C File Offset: 0x00110F7C
		// (remove) Token: 0x06004014 RID: 16404 RVA: 0x00112D85 File Offset: 0x00110F85
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event EventHandler ContextMenuChanged
		{
			add
			{
				base.ContextMenuChanged += value;
			}
			remove
			{
				base.ContextMenuChanged -= value;
			}
		}

		// Token: 0x17000FA7 RID: 4007
		// (get) Token: 0x06004015 RID: 16405 RVA: 0x00011B4A File Offset: 0x0000FD4A
		// (set) Token: 0x06004016 RID: 16406 RVA: 0x00112D8E File Offset: 0x00110F8E
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new ContextMenuStrip ContextMenuStrip
		{
			get
			{
				return base.ContextMenuStrip;
			}
			set
			{
				base.ContextMenuStrip = value;
			}
		}

		// Token: 0x1400031C RID: 796
		// (add) Token: 0x06004017 RID: 16407 RVA: 0x00112D97 File Offset: 0x00110F97
		// (remove) Token: 0x06004018 RID: 16408 RVA: 0x00112DA0 File Offset: 0x00110FA0
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler ContextMenuStripChanged
		{
			add
			{
				base.ContextMenuStripChanged += value;
			}
			remove
			{
				base.ContextMenuStripChanged -= value;
			}
		}

		// Token: 0x17000FA8 RID: 4008
		// (get) Token: 0x06004019 RID: 16409 RVA: 0x00112DAC File Offset: 0x00110FAC
		protected override CreateParams CreateParams
		{
			[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
			get
			{
				CreateParams createParams = base.CreateParams;
				if (this.DropShadowEnabled)
				{
					createParams.ClassStyle |= 131072;
				}
				createParams.Style &= -79691777;
				createParams.ExStyle &= -262145;
				createParams.Style |= (this.TopLevel ? int.MinValue : 1073741824);
				createParams.ExStyle |= 65536;
				bool topLevel = this.TopLevel;
				if (topLevel && this.state[ToolStripDropDown.stateLayered])
				{
					createParams.ExStyle |= 524288;
				}
				else if (topLevel)
				{
					createParams.ClassStyle |= 2048;
				}
				else if (!topLevel)
				{
					createParams.Style |= 67108864;
				}
				return createParams;
			}
		}

		// Token: 0x17000FA9 RID: 4009
		// (get) Token: 0x0600401A RID: 16410 RVA: 0x00112E8E File Offset: 0x0011108E
		protected override Padding DefaultPadding
		{
			get
			{
				return this.scaledDefaultPadding;
			}
		}

		// Token: 0x17000FAA RID: 4010
		// (get) Token: 0x0600401B RID: 16411 RVA: 0x00013062 File Offset: 0x00011262
		protected override bool DefaultShowItemToolTips
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000FAB RID: 4011
		// (get) Token: 0x0600401C RID: 16412 RVA: 0x00011A20 File Offset: 0x0000FC20
		protected override DockStyle DefaultDock
		{
			get
			{
				return DockStyle.None;
			}
		}

		// Token: 0x17000FAC RID: 4012
		// (get) Token: 0x0600401D RID: 16413 RVA: 0x00112E96 File Offset: 0x00111096
		// (set) Token: 0x0600401E RID: 16414 RVA: 0x00112EB4 File Offset: 0x001110B4
		public override ToolStripDropDownDirection DefaultDropDownDirection
		{
			get
			{
				if (this.childDropDownDirection != ToolStripDropDownDirection.Default)
				{
					return this.childDropDownDirection;
				}
				if (this.RightToLeft != RightToLeft.Yes)
				{
					return ToolStripDropDownDirection.Right;
				}
				return ToolStripDropDownDirection.Left;
			}
			set
			{
				this.childDropDownDirection = value;
				base.DefaultDropDownDirection = value;
			}
		}

		// Token: 0x17000FAD RID: 4013
		// (get) Token: 0x0600401F RID: 16415 RVA: 0x001017C9 File Offset: 0x000FF9C9
		// (set) Token: 0x06004020 RID: 16416 RVA: 0x001017D1 File Offset: 0x000FF9D1
		[DefaultValue(DockStyle.None)]
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public override DockStyle Dock
		{
			get
			{
				return base.Dock;
			}
			set
			{
				base.Dock = value;
			}
		}

		// Token: 0x1400031D RID: 797
		// (add) Token: 0x06004021 RID: 16417 RVA: 0x00100028 File Offset: 0x000FE228
		// (remove) Token: 0x06004022 RID: 16418 RVA: 0x00100031 File Offset: 0x000FE231
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler DockChanged
		{
			add
			{
				base.DockChanged += value;
			}
			remove
			{
				base.DockChanged -= value;
			}
		}

		// Token: 0x17000FAE RID: 4014
		// (get) Token: 0x06004023 RID: 16419 RVA: 0x00112EC4 File Offset: 0x001110C4
		internal override NativeWindow DropDownOwnerWindow
		{
			get
			{
				if (this.ownerItem != null && this.ownerItem.Owner != null)
				{
					return this.ownerItem.Owner.DropDownOwnerWindow;
				}
				return base.DropDownOwnerWindow;
			}
		}

		// Token: 0x17000FAF RID: 4015
		// (get) Token: 0x06004024 RID: 16420 RVA: 0x00112EF2 File Offset: 0x001110F2
		// (set) Token: 0x06004025 RID: 16421 RVA: 0x00112F0B File Offset: 0x0011110B
		public bool DropShadowEnabled
		{
			get
			{
				return this.dropShadowEnabled && this.TopMost && DisplayInformation.IsDropShadowEnabled;
			}
			set
			{
				if (this.dropShadowEnabled != value)
				{
					this.dropShadowEnabled = value;
					if (base.IsHandleCreated && !base.DesignMode)
					{
						base.RecreateHandle();
					}
				}
			}
		}

		// Token: 0x1400031E RID: 798
		// (add) Token: 0x06004026 RID: 16422 RVA: 0x00112F33 File Offset: 0x00111133
		// (remove) Token: 0x06004027 RID: 16423 RVA: 0x00112F46 File Offset: 0x00111146
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownClosedDecr")]
		public event ToolStripDropDownClosedEventHandler Closed
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDown.EventClosed, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDown.EventClosed, value);
			}
		}

		// Token: 0x1400031F RID: 799
		// (add) Token: 0x06004028 RID: 16424 RVA: 0x00112F59 File Offset: 0x00111159
		// (remove) Token: 0x06004029 RID: 16425 RVA: 0x00112F6C File Offset: 0x0011116C
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownClosingDecr")]
		public event ToolStripDropDownClosingEventHandler Closing
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDown.EventClosing, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDown.EventClosing, value);
			}
		}

		// Token: 0x14000320 RID: 800
		// (add) Token: 0x0600402A RID: 16426 RVA: 0x000E35B4 File Offset: 0x000E17B4
		// (remove) Token: 0x0600402B RID: 16427 RVA: 0x000E35BD File Offset: 0x000E17BD
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler Enter
		{
			add
			{
				base.Enter += value;
			}
			remove
			{
				base.Enter -= value;
			}
		}

		// Token: 0x17000FB0 RID: 4016
		// (get) Token: 0x0600402C RID: 16428 RVA: 0x00112F7F File Offset: 0x0011117F
		// (set) Token: 0x0600402D RID: 16429 RVA: 0x00112FB2 File Offset: 0x001111B2
		public override Font Font
		{
			get
			{
				if (base.IsFontSet())
				{
					return base.Font;
				}
				if (this.IsAutoGenerated && this.OwnerItem != null)
				{
					return this.OwnerItem.Font;
				}
				return base.Font;
			}
			set
			{
				base.Font = value;
			}
		}

		// Token: 0x14000321 RID: 801
		// (add) Token: 0x0600402E RID: 16430 RVA: 0x0005AAE0 File Offset: 0x00058CE0
		// (remove) Token: 0x0600402F RID: 16431 RVA: 0x0005AAE9 File Offset: 0x00058CE9
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler FontChanged
		{
			add
			{
				base.FontChanged += value;
			}
			remove
			{
				base.FontChanged -= value;
			}
		}

		// Token: 0x14000322 RID: 802
		// (add) Token: 0x06004030 RID: 16432 RVA: 0x00112FBB File Offset: 0x001111BB
		// (remove) Token: 0x06004031 RID: 16433 RVA: 0x00112FC4 File Offset: 0x001111C4
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event EventHandler ForeColorChanged
		{
			add
			{
				base.ForeColorChanged += value;
			}
			remove
			{
				base.ForeColorChanged -= value;
			}
		}

		// Token: 0x14000323 RID: 803
		// (add) Token: 0x06004032 RID: 16434 RVA: 0x000F505C File Offset: 0x000F325C
		// (remove) Token: 0x06004033 RID: 16435 RVA: 0x000F5065 File Offset: 0x000F3265
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event GiveFeedbackEventHandler GiveFeedback
		{
			add
			{
				base.GiveFeedback += value;
			}
			remove
			{
				base.GiveFeedback -= value;
			}
		}

		// Token: 0x17000FB1 RID: 4017
		// (get) Token: 0x06004034 RID: 16436 RVA: 0x00112FCD File Offset: 0x001111CD
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new ToolStripGripDisplayStyle GripDisplayStyle
		{
			get
			{
				return base.GripDisplayStyle;
			}
		}

		// Token: 0x17000FB2 RID: 4018
		// (get) Token: 0x06004035 RID: 16437 RVA: 0x00112FD5 File Offset: 0x001111D5
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new Rectangle GripRectangle
		{
			get
			{
				return base.GripRectangle;
			}
		}

		// Token: 0x17000FB3 RID: 4019
		// (get) Token: 0x06004036 RID: 16438 RVA: 0x00112FDD File Offset: 0x001111DD
		// (set) Token: 0x06004037 RID: 16439 RVA: 0x00112FE5 File Offset: 0x001111E5
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public new Padding GripMargin
		{
			get
			{
				return base.GripMargin;
			}
			set
			{
				base.GripMargin = value;
			}
		}

		// Token: 0x17000FB4 RID: 4020
		// (get) Token: 0x06004038 RID: 16440 RVA: 0x000D904D File Offset: 0x000D724D
		// (set) Token: 0x06004039 RID: 16441 RVA: 0x000D9055 File Offset: 0x000D7255
		[DefaultValue(ToolStripGripStyle.Hidden)]
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new ToolStripGripStyle GripStyle
		{
			get
			{
				return base.GripStyle;
			}
			set
			{
				base.GripStyle = value;
			}
		}

		// Token: 0x14000324 RID: 804
		// (add) Token: 0x0600403A RID: 16442 RVA: 0x00112FEE File Offset: 0x001111EE
		// (remove) Token: 0x0600403B RID: 16443 RVA: 0x00112FF7 File Offset: 0x001111F7
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event HelpEventHandler HelpRequested
		{
			add
			{
				base.HelpRequested += value;
			}
			remove
			{
				base.HelpRequested -= value;
			}
		}

		// Token: 0x14000325 RID: 805
		// (add) Token: 0x0600403C RID: 16444 RVA: 0x0002410C File Offset: 0x0002230C
		// (remove) Token: 0x0600403D RID: 16445 RVA: 0x00024115 File Offset: 0x00022315
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler ImeModeChanged
		{
			add
			{
				base.ImeModeChanged += value;
			}
			remove
			{
				base.ImeModeChanged -= value;
			}
		}

		// Token: 0x17000FB5 RID: 4021
		// (get) Token: 0x0600403E RID: 16446 RVA: 0x00113000 File Offset: 0x00111200
		[Browsable(false)]
		public bool IsAutoGenerated
		{
			get
			{
				return this.isAutoGenerated;
			}
		}

		// Token: 0x17000FB6 RID: 4022
		// (get) Token: 0x0600403F RID: 16447 RVA: 0x00113008 File Offset: 0x00111208
		internal bool IsAssignedToDropDownItem
		{
			get
			{
				return this.IsAutoGenerated || this.countDropDownItemsAssignedTo > 0;
			}
		}

		// Token: 0x17000FB7 RID: 4023
		// (get) Token: 0x06004040 RID: 16448 RVA: 0x00113020 File Offset: 0x00111220
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal bool IsRestrictedWindow
		{
			get
			{
				if (!this.state[ToolStripDropDown.stateIsRestrictedWindowChecked])
				{
					this.state[ToolStripDropDown.stateIsRestrictedWindowChecked] = true;
					this.state[ToolStripDropDown.stateIsRestrictedWindow] = false;
					try
					{
						IntSecurity.WindowAdornmentModification.Demand();
					}
					catch
					{
						this.state[ToolStripDropDown.stateIsRestrictedWindow] = true;
					}
				}
				return this.state[ToolStripDropDown.stateIsRestrictedWindow];
			}
		}

		// Token: 0x17000FB8 RID: 4024
		// (get) Token: 0x06004041 RID: 16449 RVA: 0x001130A4 File Offset: 0x001112A4
		// (set) Token: 0x06004042 RID: 16450 RVA: 0x001130C8 File Offset: 0x001112C8
		internal override Size ImageScalingSizeInternal
		{
			get
			{
				if (this.IsAutoGenerated && this.OwnerToolStrip != null)
				{
					return this.OwnerToolStrip.ImageScalingSizeInternal;
				}
				return base.ImageScalingSizeInternal;
			}
			set
			{
				base.ImageScalingSizeInternal = value;
			}
		}

		// Token: 0x17000FB9 RID: 4025
		// (get) Token: 0x06004043 RID: 16451 RVA: 0x001130D4 File Offset: 0x001112D4
		// (set) Token: 0x06004044 RID: 16452 RVA: 0x001130F8 File Offset: 0x001112F8
		internal override bool KeyboardActive
		{
			get
			{
				ToolStrip ownerToolStrip = this.OwnerToolStrip;
				if (ownerToolStrip != null)
				{
					return ownerToolStrip.KeyboardActive;
				}
				return base.KeyboardActive;
			}
			set
			{
				base.KeyboardActive = value;
				ToolStrip ownerToolStrip = this.OwnerToolStrip;
				if (ownerToolStrip != null)
				{
					ownerToolStrip.KeyboardActive = value;
				}
			}
		}

		// Token: 0x14000326 RID: 806
		// (add) Token: 0x06004045 RID: 16453 RVA: 0x000B9392 File Offset: 0x000B7592
		// (remove) Token: 0x06004046 RID: 16454 RVA: 0x000B939B File Offset: 0x000B759B
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event KeyEventHandler KeyDown
		{
			add
			{
				base.KeyDown += value;
			}
			remove
			{
				base.KeyDown -= value;
			}
		}

		// Token: 0x14000327 RID: 807
		// (add) Token: 0x06004047 RID: 16455 RVA: 0x000B93A4 File Offset: 0x000B75A4
		// (remove) Token: 0x06004048 RID: 16456 RVA: 0x000B93AD File Offset: 0x000B75AD
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event KeyPressEventHandler KeyPress
		{
			add
			{
				base.KeyPress += value;
			}
			remove
			{
				base.KeyPress -= value;
			}
		}

		// Token: 0x14000328 RID: 808
		// (add) Token: 0x06004049 RID: 16457 RVA: 0x000B9380 File Offset: 0x000B7580
		// (remove) Token: 0x0600404A RID: 16458 RVA: 0x000B9389 File Offset: 0x000B7589
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event KeyEventHandler KeyUp
		{
			add
			{
				base.KeyUp += value;
			}
			remove
			{
				base.KeyUp -= value;
			}
		}

		// Token: 0x14000329 RID: 809
		// (add) Token: 0x0600404B RID: 16459 RVA: 0x000E35C6 File Offset: 0x000E17C6
		// (remove) Token: 0x0600404C RID: 16460 RVA: 0x000E35CF File Offset: 0x000E17CF
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler Leave
		{
			add
			{
				base.Leave += value;
			}
			remove
			{
				base.Leave -= value;
			}
		}

		// Token: 0x17000FBA RID: 4026
		// (get) Token: 0x0600404D RID: 16461 RVA: 0x000B184D File Offset: 0x000AFA4D
		// (set) Token: 0x0600404E RID: 16462 RVA: 0x000B1855 File Offset: 0x000AFA55
		[EditorBrowsable(EditorBrowsableState.Never)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		[Browsable(false)]
		public new Point Location
		{
			get
			{
				return base.Location;
			}
			set
			{
				base.Location = value;
			}
		}

		// Token: 0x1400032A RID: 810
		// (add) Token: 0x0600404F RID: 16463 RVA: 0x0011311D File Offset: 0x0011131D
		// (remove) Token: 0x06004050 RID: 16464 RVA: 0x00113130 File Offset: 0x00111330
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpeningDescr")]
		public event CancelEventHandler Opening
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDown.EventOpening, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDown.EventOpening, value);
			}
		}

		// Token: 0x1400032B RID: 811
		// (add) Token: 0x06004051 RID: 16465 RVA: 0x00113143 File Offset: 0x00111343
		// (remove) Token: 0x06004052 RID: 16466 RVA: 0x00113156 File Offset: 0x00111356
		[SRCategory("CatAction")]
		[SRDescription("ToolStripDropDownOpenedDescr")]
		public event EventHandler Opened
		{
			add
			{
				base.Events.AddHandler(ToolStripDropDown.EventOpened, value);
			}
			remove
			{
				base.Events.RemoveHandler(ToolStripDropDown.EventOpened, value);
			}
		}

		// Token: 0x17000FBB RID: 4027
		// (get) Token: 0x06004053 RID: 16467 RVA: 0x0011316C File Offset: 0x0011136C
		protected internal override Size MaxItemSize
		{
			get
			{
				return Screen.GetWorkingArea(base.Bounds).Size - base.Padding.Size;
			}
		}

		// Token: 0x17000FBC RID: 4028
		// (get) Token: 0x06004054 RID: 16468 RVA: 0x001131A0 File Offset: 0x001113A0
		// (set) Token: 0x06004055 RID: 16469 RVA: 0x001131D8 File Offset: 0x001113D8
		[SRCategory("CatWindowStyle")]
		[TypeConverter(typeof(OpacityConverter))]
		[SRDescription("FormOpacityDescr")]
		[DefaultValue(1.0)]
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double Opacity
		{
			get
			{
				object @object = base.Properties.GetObject(ToolStripDropDown.PropOpacity);
				if (@object != null)
				{
					return Convert.ToDouble(@object, CultureInfo.InvariantCulture);
				}
				return 1.0;
			}
			set
			{
				if (this.IsRestrictedWindow)
				{
					value = Math.Max(value, 0.5);
				}
				if (value > 1.0)
				{
					value = 1.0;
				}
				else if (value < 0.0)
				{
					value = 0.0;
				}
				base.Properties.SetObject(ToolStripDropDown.PropOpacity, value);
				bool flag = this.state[ToolStripDropDown.stateLayered];
				if (this.OpacityAsByte < 255 && OSFeature.Feature.IsPresent(OSFeature.LayeredWindows))
				{
					this.AllowTransparency = true;
					this.state[ToolStripDropDown.stateLayered] = true;
				}
				else
				{
					this.state[ToolStripDropDown.stateLayered] = false;
				}
				if (flag != this.state[ToolStripDropDown.stateLayered])
				{
					base.UpdateStyles();
				}
				this.UpdateLayered();
			}
		}

		// Token: 0x17000FBD RID: 4029
		// (get) Token: 0x06004056 RID: 16470 RVA: 0x001132BD File Offset: 0x001114BD
		private byte OpacityAsByte
		{
			get
			{
				return (byte)(this.Opacity * 255.0);
			}
		}

		// Token: 0x17000FBE RID: 4030
		// (get) Token: 0x06004057 RID: 16471 RVA: 0x001132D0 File Offset: 0x001114D0
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new ToolStripOverflowButton OverflowButton
		{
			get
			{
				return base.OverflowButton;
			}
		}

		// Token: 0x17000FBF RID: 4031
		// (get) Token: 0x06004058 RID: 16472 RVA: 0x001132D8 File Offset: 0x001114D8
		// (set) Token: 0x06004059 RID: 16473 RVA: 0x001132E0 File Offset: 0x001114E0
		[DefaultValue(null)]
		[Browsable(false)]
		public ToolStripItem OwnerItem
		{
			get
			{
				return this.ownerItem;
			}
			set
			{
				if (this.ownerItem != value)
				{
					Font font = this.Font;
					RightToLeft rightToLeft = this.RightToLeft;
					this.ownerItem = value;
					if (!font.Equals(this.Font))
					{
						this.OnOwnerItemFontChanged(EventArgs.Empty);
					}
					if (this.ownerItem != null && this.RightToLeftInherited && rightToLeft != this.RightToLeft)
					{
						using (new LayoutTransaction(this, this, PropertyNames.RightToLeft))
						{
							this.OnRightToLeftChanged(EventArgs.Empty);
						}
					}
				}
			}
		}

		// Token: 0x17000FC0 RID: 4032
		// (get) Token: 0x0600405A RID: 16474 RVA: 0x00113374 File Offset: 0x00111574
		internal ToolStripDropDownItem OwnerDropDownItem
		{
			get
			{
				return this.OwnerItem as ToolStripDropDownItem;
			}
		}

		// Token: 0x17000FC1 RID: 4033
		// (get) Token: 0x0600405B RID: 16475 RVA: 0x00113384 File Offset: 0x00111584
		internal ToolStrip OwnerToolStrip
		{
			get
			{
				if (this.ownerItem != null)
				{
					ToolStrip parentInternal = this.ownerItem.ParentInternal;
					if (parentInternal != null)
					{
						return parentInternal;
					}
					if (this.ownerItem.Placement == ToolStripItemPlacement.Overflow && this.ownerItem.Owner != null)
					{
						return this.ownerItem.Owner.OverflowButton.DropDown;
					}
					if (parentInternal == null)
					{
						return this.ownerItem.Owner;
					}
				}
				return null;
			}
		}

		// Token: 0x17000FC2 RID: 4034
		// (get) Token: 0x0600405C RID: 16476 RVA: 0x001133EB File Offset: 0x001115EB
		// (set) Token: 0x0600405D RID: 16477 RVA: 0x001133F3 File Offset: 0x001115F3
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new Region Region
		{
			get
			{
				return base.Region;
			}
			set
			{
				base.Region = value;
			}
		}

		// Token: 0x1400032C RID: 812
		// (add) Token: 0x0600405E RID: 16478 RVA: 0x001133FC File Offset: 0x001115FC
		// (remove) Token: 0x0600405F RID: 16479 RVA: 0x00113405 File Offset: 0x00111605
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler RegionChanged
		{
			add
			{
				base.RegionChanged += value;
			}
			remove
			{
				base.RegionChanged -= value;
			}
		}

		// Token: 0x17000FC3 RID: 4035
		// (get) Token: 0x06004060 RID: 16480 RVA: 0x00011A20 File Offset: 0x0000FC20
		// (set) Token: 0x06004061 RID: 16481 RVA: 0x000072B6 File Offset: 0x000054B6
		internal virtual bool RequiresScrollButtons
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		// Token: 0x17000FC4 RID: 4036
		// (get) Token: 0x06004062 RID: 16482 RVA: 0x0011340E File Offset: 0x0011160E
		// (set) Token: 0x06004063 RID: 16483 RVA: 0x000C619D File Offset: 0x000C439D
		[SRCategory("CatAppearance")]
		[Localizable(true)]
		[AmbientValue(RightToLeft.Inherit)]
		[SRDescription("ControlRightToLeftDescr")]
		public override RightToLeft RightToLeft
		{
			get
			{
				if (this.RightToLeftInherited)
				{
					if (this.SourceControlInternal != null)
					{
						return this.SourceControlInternal.RightToLeft;
					}
					if (this.OwnerItem != null)
					{
						return this.OwnerItem.RightToLeft;
					}
				}
				return base.RightToLeft;
			}
			set
			{
				base.RightToLeft = value;
			}
		}

		// Token: 0x17000FC5 RID: 4037
		// (get) Token: 0x06004064 RID: 16484 RVA: 0x00113446 File Offset: 0x00111646
		private bool RightToLeftInherited
		{
			get
			{
				return !this.ShouldSerializeRightToLeft();
			}
		}

		// Token: 0x1400032D RID: 813
		// (add) Token: 0x06004065 RID: 16485 RVA: 0x00113451 File Offset: 0x00111651
		// (remove) Token: 0x06004066 RID: 16486 RVA: 0x0011345A File Offset: 0x0011165A
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event ScrollEventHandler Scroll
		{
			add
			{
				base.Scroll += value;
			}
			remove
			{
				base.Scroll -= value;
			}
		}

		// Token: 0x17000FC6 RID: 4038
		// (get) Token: 0x06004067 RID: 16487 RVA: 0x000D90BB File Offset: 0x000D72BB
		// (set) Token: 0x06004068 RID: 16488 RVA: 0x000D90C3 File Offset: 0x000D72C3
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new bool Stretch
		{
			get
			{
				return base.Stretch;
			}
			set
			{
				base.Stretch = value;
			}
		}

		// Token: 0x1400032E RID: 814
		// (add) Token: 0x06004069 RID: 16489 RVA: 0x0005D6CB File Offset: 0x0005B8CB
		// (remove) Token: 0x0600406A RID: 16490 RVA: 0x0005D6D4 File Offset: 0x0005B8D4
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Always)]
		public new event EventHandler StyleChanged
		{
			add
			{
				base.StyleChanged += value;
			}
			remove
			{
				base.StyleChanged -= value;
			}
		}

		// Token: 0x17000FC7 RID: 4039
		// (get) Token: 0x0600406B RID: 16491 RVA: 0x00113463 File Offset: 0x00111663
		// (set) Token: 0x0600406C RID: 16492 RVA: 0x0011347A File Offset: 0x0011167A
		internal Control SourceControlInternal
		{
			get
			{
				return base.Properties.GetObject(ToolStripDropDown.PropSourceControl) as Control;
			}
			set
			{
				base.Properties.SetObject(ToolStripDropDown.PropSourceControl, value);
			}
		}

		// Token: 0x17000FC8 RID: 4040
		// (get) Token: 0x0600406D RID: 16493 RVA: 0x0011348D File Offset: 0x0011168D
		internal override int ShowParams
		{
			get
			{
				return 4;
			}
		}

		// Token: 0x1400032F RID: 815
		// (add) Token: 0x0600406E RID: 16494 RVA: 0x000B2622 File Offset: 0x000B0822
		// (remove) Token: 0x0600406F RID: 16495 RVA: 0x000B262B File Offset: 0x000B082B
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event EventHandler TabStopChanged
		{
			add
			{
				base.TabStopChanged += value;
			}
			remove
			{
				base.TabStopChanged -= value;
			}
		}

		// Token: 0x14000330 RID: 816
		// (add) Token: 0x06004070 RID: 16496 RVA: 0x00046771 File Offset: 0x00044971
		// (remove) Token: 0x06004071 RID: 16497 RVA: 0x0004677A File Offset: 0x0004497A
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event EventHandler TextChanged
		{
			add
			{
				base.TextChanged += value;
			}
			remove
			{
				base.TextChanged -= value;
			}
		}

		// Token: 0x17000FC9 RID: 4041
		// (get) Token: 0x06004072 RID: 16498 RVA: 0x00113490 File Offset: 0x00111690
		// (set) Token: 0x06004073 RID: 16499 RVA: 0x00113498 File Offset: 0x00111698
		[Browsable(false)]
		[DefaultValue(ToolStripTextDirection.Horizontal)]
		[SRDescription("ToolStripTextDirectionDescr")]
		[SRCategory("CatAppearance")]
		public override ToolStripTextDirection TextDirection
		{
			get
			{
				return base.TextDirection;
			}
			set
			{
				base.TextDirection = value;
			}
		}

		// Token: 0x17000FCA RID: 4042
		// (get) Token: 0x06004074 RID: 16500 RVA: 0x00013062 File Offset: 0x00011262
		protected virtual bool TopMost
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000FCB RID: 4043
		// (get) Token: 0x06004075 RID: 16501 RVA: 0x000B269E File Offset: 0x000B089E
		// (set) Token: 0x06004076 RID: 16502 RVA: 0x001134A1 File Offset: 0x001116A1
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public bool TopLevel
		{
			get
			{
				return base.GetTopLevel();
			}
			set
			{
				if (value != base.GetTopLevel())
				{
					base.SetTopLevelInternal(value);
					this.SetTopLevelStyle(value);
				}
			}
		}

		// Token: 0x17000FCC RID: 4044
		// (get) Token: 0x06004077 RID: 16503 RVA: 0x000B25EE File Offset: 0x000B07EE
		// (set) Token: 0x06004078 RID: 16504 RVA: 0x000B25F6 File Offset: 0x000B07F6
		[EditorBrowsable(EditorBrowsableState.Never)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		[Browsable(false)]
		public new int TabIndex
		{
			get
			{
				return base.TabIndex;
			}
			set
			{
				base.TabIndex = value;
			}
		}

		// Token: 0x14000331 RID: 817
		// (add) Token: 0x06004079 RID: 16505 RVA: 0x000B25FF File Offset: 0x000B07FF
		// (remove) Token: 0x0600407A RID: 16506 RVA: 0x000B2608 File Offset: 0x000B0808
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		[SRCategory("CatPropertyChanged")]
		[SRDescription("ControlOnTabIndexChangedDescr")]
		public new event EventHandler TabIndexChanged
		{
			add
			{
				base.TabIndexChanged += value;
			}
			remove
			{
				base.TabIndexChanged -= value;
			}
		}

		// Token: 0x14000332 RID: 818
		// (add) Token: 0x0600407B RID: 16507 RVA: 0x001134BA File Offset: 0x001116BA
		// (remove) Token: 0x0600407C RID: 16508 RVA: 0x001134C3 File Offset: 0x001116C3
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event EventHandler Validated
		{
			add
			{
				base.Validated += value;
			}
			remove
			{
				base.Validated -= value;
			}
		}

		// Token: 0x14000333 RID: 819
		// (add) Token: 0x0600407D RID: 16509 RVA: 0x001134CC File Offset: 0x001116CC
		// (remove) Token: 0x0600407E RID: 16510 RVA: 0x001134D5 File Offset: 0x001116D5
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new event CancelEventHandler Validating
		{
			add
			{
				base.Validating += value;
			}
			remove
			{
				base.Validating -= value;
			}
		}

		// Token: 0x17000FCD RID: 4045
		// (get) Token: 0x0600407F RID: 16511 RVA: 0x000FFFD1 File Offset: 0x000FE1D1
		// (set) Token: 0x06004080 RID: 16512 RVA: 0x000FFFD9 File Offset: 0x000FE1D9
		[SRCategory("CatBehavior")]
		[Localizable(true)]
		[SRDescription("ControlVisibleDescr")]
		[DefaultValue(false)]
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public new bool Visible
		{
			get
			{
				return base.Visible;
			}
			set
			{
				base.Visible = value;
			}
		}

		// Token: 0x17000FCE RID: 4046
		// (get) Token: 0x06004081 RID: 16513 RVA: 0x001134DE File Offset: 0x001116DE
		// (set) Token: 0x06004082 RID: 16514 RVA: 0x001134FC File Offset: 0x001116FC
		internal bool WorkingAreaConstrained
		{
			get
			{
				return !this.state[ToolStripDropDown.stateNotWorkingAreaConstrained] || this.IsRestrictedWindow;
			}
			set
			{
				bool value2 = !value;
				this.state[ToolStripDropDown.stateNotWorkingAreaConstrained] = value2;
			}
		}

		// Token: 0x06004083 RID: 16515 RVA: 0x0011351F File Offset: 0x0011171F
		internal void AssignToDropDownItem()
		{
			this.countDropDownItemsAssignedTo++;
		}

		// Token: 0x06004084 RID: 16516 RVA: 0x00113530 File Offset: 0x00111730
		internal void AdjustSize()
		{
			Size suggestedSize = this.GetSuggestedSize();
			if (suggestedSize != base.Size)
			{
				base.Size = suggestedSize;
			}
		}

		// Token: 0x06004085 RID: 16517 RVA: 0x0011355C File Offset: 0x0011175C
		private void ApplyTopMost(bool topMost)
		{
			if (this.TopMost)
			{
				HandleRef hWndInsertAfter = topMost ? NativeMethods.HWND_TOPMOST : NativeMethods.HWND_NOTOPMOST;
				SafeNativeMethods.SetWindowPos(new HandleRef(this, base.Handle), hWndInsertAfter, 0, 0, 0, 0, 19);
			}
		}

		// Token: 0x06004086 RID: 16518 RVA: 0x0011359A File Offset: 0x0011179A
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				this.SourceControlInternal = null;
			}
			base.Dispose(disposing);
		}

		// Token: 0x06004087 RID: 16519 RVA: 0x001135B0 File Offset: 0x001117B0
		private void CancelAutoExpand()
		{
			ToolStrip toplevelOwnerToolStrip = this.GetToplevelOwnerToolStrip();
			if (toplevelOwnerToolStrip != null)
			{
				toplevelOwnerToolStrip.MenuAutoExpand = false;
			}
		}

		// Token: 0x06004088 RID: 16520 RVA: 0x001135CE File Offset: 0x001117CE
		internal override bool CanProcessMnemonic()
		{
			return (!this.IsRestrictedWindow || Application.MessageLoop) && base.CanProcessMnemonic();
		}

		// Token: 0x06004089 RID: 16521 RVA: 0x001135E7 File Offset: 0x001117E7
		protected override AccessibleObject CreateAccessibilityInstance()
		{
			return new ToolStripDropDown.ToolStripDropDownAccessibleObject(this);
		}

		// Token: 0x0600408A RID: 16522 RVA: 0x001135F0 File Offset: 0x001117F0
		protected override LayoutSettings CreateLayoutSettings(ToolStripLayoutStyle style)
		{
			LayoutSettings layoutSettings = base.CreateLayoutSettings(style);
			if (style == ToolStripLayoutStyle.Flow)
			{
				FlowLayoutSettings flowLayoutSettings = layoutSettings as FlowLayoutSettings;
				flowLayoutSettings.FlowDirection = FlowDirection.TopDown;
				flowLayoutSettings.WrapContents = false;
				return flowLayoutSettings;
			}
			return layoutSettings;
		}

		// Token: 0x0600408B RID: 16523 RVA: 0x00113624 File Offset: 0x00111824
		protected override void CreateHandle()
		{
			base.CreateHandle();
			if (this.TopLevel)
			{
				this.ReparentToDropDownOwnerWindow();
				if (!this.AutoClose || !this.WorkingAreaConstrained)
				{
					this.ApplyTopMost(true);
				}
			}
			if (base.DesignMode)
			{
				base.SetStyle(ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer, false);
			}
		}

		// Token: 0x0600408C RID: 16524 RVA: 0x00113670 File Offset: 0x00111870
		public void Close()
		{
			this.SetCloseReason(ToolStripDropDownCloseReason.CloseCalled);
			this.Visible = false;
			if (ToolStripManager.ModalMenuFilter.GetActiveToolStrip() == null)
			{
				ToolStripManager.ModalMenuFilter.ExitMenuMode();
			}
		}

		// Token: 0x0600408D RID: 16525 RVA: 0x0011368C File Offset: 0x0011188C
		private void ResetCloseReason()
		{
			this.closeReason = ToolStripDropDownCloseReason.AppFocusChange;
		}

		// Token: 0x0600408E RID: 16526 RVA: 0x00113695 File Offset: 0x00111895
		internal void SetCloseReason(ToolStripDropDownCloseReason reason)
		{
			this.closeReason = reason;
		}

		// Token: 0x0600408F RID: 16527 RVA: 0x0011369E File Offset: 0x0011189E
		public void Close(ToolStripDropDownCloseReason reason)
		{
			this.SetCloseReason(reason);
			this.Visible = false;
		}

		// Token: 0x06004090 RID: 16528 RVA: 0x001136B0 File Offset: 0x001118B0
		internal override Rectangle ApplyBoundsConstraints(int suggestedX, int suggestedY, int proposedWidth, int proposedHeight)
		{
			Rectangle rectangle = base.ApplyBoundsConstraints(suggestedX, suggestedY, proposedWidth, proposedHeight);
			if (this.IsRestrictedWindow && this.TopMost)
			{
				rectangle = WindowsFormsUtils.ConstrainToScreenWorkingAreaBounds(rectangle);
			}
			return rectangle;
		}

		// Token: 0x06004091 RID: 16529 RVA: 0x001136E4 File Offset: 0x001118E4
		internal Rectangle GetDropDownBounds(Rectangle suggestedBounds)
		{
			Rectangle result;
			if (this.TopLevel)
			{
				Point location = Point.Empty;
				if (this.ownerItem != null && this.ownerItem is ToolStripDropDownItem)
				{
					location = ((ToolStripDropDownItem)this.ownerItem).DropDownLocation;
				}
				else
				{
					location = suggestedBounds.Location;
				}
				Rectangle bounds = new Rectangle(location, suggestedBounds.Size);
				if (this.WorkingAreaConstrained)
				{
					result = WindowsFormsUtils.ConstrainToScreenWorkingAreaBounds(bounds);
				}
				else
				{
					result = WindowsFormsUtils.ConstrainToScreenBounds(bounds);
				}
			}
			else
			{
				Point location2 = Point.Empty;
				if (this.ownerItem != null && this.ownerItem is ToolStripDropDownItem && this.ParentInternal != null)
				{
					location2 = this.ParentInternal.PointToClient(((ToolStripDropDownItem)this.ownerItem).DropDownLocation);
				}
				else
				{
					location2 = suggestedBounds.Location;
				}
				result = new Rectangle(location2, suggestedBounds.Size);
			}
			return result;
		}

		// Token: 0x06004092 RID: 16530 RVA: 0x001137B4 File Offset: 0x001119B4
		internal Rectangle CalculateDropDownLocation(Point start, ToolStripDropDownDirection dropDownDirection)
		{
			Point empty = Point.Empty;
			if (!base.IsHandleCreated)
			{
				LayoutTransaction.DoLayout(this, this, PropertyNames.PreferredSize);
			}
			Rectangle rectangle = new Rectangle(Point.Empty, this.GetSuggestedSize());
			switch (dropDownDirection)
			{
			case ToolStripDropDownDirection.AboveLeft:
				empty.X = -rectangle.Width;
				empty.Y = -rectangle.Height;
				break;
			case ToolStripDropDownDirection.AboveRight:
				empty.Y = -rectangle.Height;
				break;
			case ToolStripDropDownDirection.BelowLeft:
			case ToolStripDropDownDirection.Left:
				empty.X = -rectangle.Width;
				break;
			}
			rectangle.Location = new Point(start.X + empty.X, start.Y + empty.Y);
			if (this.WorkingAreaConstrained)
			{
				rectangle = WindowsFormsUtils.ConstrainToScreenWorkingAreaBounds(rectangle);
			}
			return rectangle;
		}

		// Token: 0x06004093 RID: 16531 RVA: 0x00113887 File Offset: 0x00111A87
		internal Size GetSuggestedSize()
		{
			if (this.AutoSize)
			{
				return this.GetPreferredSize(Size.Empty);
			}
			return base.Size;
		}

		// Token: 0x06004094 RID: 16532 RVA: 0x001138A4 File Offset: 0x00111AA4
		internal override ToolStrip GetToplevelOwnerToolStrip()
		{
			ToolStripDropDown firstDropDown = this.GetFirstDropDown();
			if (firstDropDown.OwnerItem != null)
			{
				return firstDropDown.OwnerToolStrip;
			}
			return null;
		}

		// Token: 0x06004095 RID: 16533 RVA: 0x001138C8 File Offset: 0x00111AC8
		internal ToolStripItem GetToplevelOwnerItem()
		{
			ToolStripDropDown firstDropDown = this.GetFirstDropDown();
			return firstDropDown.OwnerItem;
		}

		// Token: 0x06004096 RID: 16534 RVA: 0x001138E2 File Offset: 0x00111AE2
		internal override void HandleItemClicked(ToolStripItem dismissingItem)
		{
			if (!LocalAppContextSwitches.UseLegacyContextMenuStripSourceControlValue && base.ActiveDropDowns.Count == 0)
			{
				this.SourceControlInternal = null;
			}
			base.HandleItemClicked(dismissingItem);
		}

		// Token: 0x06004097 RID: 16535 RVA: 0x00113908 File Offset: 0x00111B08
		internal virtual void Initialize()
		{
			base.SetState(2, false);
			base.SetTopLevelInternal(true);
			base.SetState(32, true);
			base.SetStyle(ControlStyles.ResizeRedraw, true);
			base.UpdateStyles();
			this.GripStyle = ToolStripGripStyle.Hidden;
			this.CanOverflow = false;
			base.LayoutStyle = ToolStripLayoutStyle.Flow;
			base.MenuAutoExpand = true;
			this.AutoSize = true;
		}

		// Token: 0x06004098 RID: 16536 RVA: 0x00113960 File Offset: 0x00111B60
		protected virtual void OnClosed(ToolStripDropDownClosedEventArgs e)
		{
			if (base.IsHandleCreated && (this.ownerItem == null || !this.ownerItem.IsInDesignMode))
			{
				base.AccessibilityNotifyClients(AccessibleEvents.SystemMenuPopupEnd, -1);
			}
			ToolStripDropDownClosedEventHandler toolStripDropDownClosedEventHandler = (ToolStripDropDownClosedEventHandler)base.Events[ToolStripDropDown.EventClosed];
			if (toolStripDropDownClosedEventHandler != null)
			{
				toolStripDropDownClosedEventHandler(this, e);
			}
		}

		// Token: 0x06004099 RID: 16537 RVA: 0x001139B4 File Offset: 0x00111BB4
		protected virtual void OnClosing(ToolStripDropDownClosingEventArgs e)
		{
			ToolStripDropDownClosingEventHandler toolStripDropDownClosingEventHandler = (ToolStripDropDownClosingEventHandler)base.Events[ToolStripDropDown.EventClosing];
			if (toolStripDropDownClosingEventHandler != null)
			{
				toolStripDropDownClosingEventHandler(this, e);
			}
		}

		// Token: 0x0600409A RID: 16538 RVA: 0x001139E2 File Offset: 0x00111BE2
		protected override void OnHandleCreated(EventArgs e)
		{
			base.UpdateStyles();
			base.OnHandleCreated(e);
			this.UpdateLayered();
		}

		// Token: 0x0600409B RID: 16539 RVA: 0x001139F8 File Offset: 0x00111BF8
		protected override void OnItemClicked(ToolStripItemClickedEventArgs e)
		{
			try
			{
				base.OnItemClicked(e);
			}
			finally
			{
				ToolStripDropDownItem toolStripDropDownItem = e.ClickedItem as ToolStripDropDownItem;
				if (this.AutoClose && (toolStripDropDownItem == null || (toolStripDropDownItem is ToolStripSplitButton && !toolStripDropDownItem.DropDown.Visible) || !toolStripDropDownItem.HasDropDownItems))
				{
					this.Close(ToolStripDropDownCloseReason.ItemClicked);
				}
			}
		}

		// Token: 0x0600409C RID: 16540 RVA: 0x00113A5C File Offset: 0x00111C5C
		protected override void OnLayout(LayoutEventArgs e)
		{
			this.AdjustSize();
			base.OnLayout(e);
		}

		// Token: 0x0600409D RID: 16541 RVA: 0x00113A6C File Offset: 0x00111C6C
		protected virtual void OnOpening(CancelEventArgs e)
		{
			CancelEventHandler cancelEventHandler = (CancelEventHandler)base.Events[ToolStripDropDown.EventOpening];
			if (cancelEventHandler != null)
			{
				cancelEventHandler(this, e);
			}
		}

		// Token: 0x0600409E RID: 16542 RVA: 0x00113A9C File Offset: 0x00111C9C
		protected virtual void OnOpened(EventArgs e)
		{
			if (base.IsHandleCreated && (this.ownerItem == null || !this.ownerItem.IsInDesignMode))
			{
				base.AccessibilityNotifyClients(AccessibleEvents.SystemMenuPopupStart, -1);
			}
			EventHandler eventHandler = (EventHandler)base.Events[ToolStripDropDown.EventOpened];
			if (eventHandler != null)
			{
				eventHandler(this, e);
			}
		}

		// Token: 0x0600409F RID: 16543 RVA: 0x00113AF0 File Offset: 0x00111CF0
		protected override void OnVisibleChanged(EventArgs e)
		{
			if (this.Location != this.displayLocation)
			{
				this.Location = this.displayLocation;
				this.displayLocation = this.Location;
			}
			if (this.AutoScroll || base.LayoutRequired)
			{
				base.OnVisibleChanged(e);
				return;
			}
			base.SuspendLayout();
			try
			{
				base.OnVisibleChanged(e);
			}
			finally
			{
				base.ResumeLayout(false);
			}
		}

		// Token: 0x060040A0 RID: 16544 RVA: 0x00113B68 File Offset: 0x00111D68
		protected override void OnParentChanged(EventArgs e)
		{
			base.OnParentChanged(e);
			Rectangle bounds = base.Bounds;
			this.SetBoundsCore(bounds.X, bounds.Y, bounds.Width, bounds.Height, BoundsSpecified.Location);
		}

		// Token: 0x060040A1 RID: 16545 RVA: 0x00113BA8 File Offset: 0x00111DA8
		protected override void OnMouseUp(MouseEventArgs mea)
		{
			base.OnMouseUp(mea);
			if (!base.ClientRectangle.Contains(mea.Location))
			{
				bool flag = true;
				if (this.OwnerToolStrip != null && this.OwnerItem != null && this.OwnerItem.Bounds.Contains(WindowsFormsUtils.TranslatePoint(mea.Location, this, this.OwnerToolStrip)))
				{
					flag = false;
				}
				if (flag)
				{
					this.DismissAll();
					this.CancelAutoExpand();
				}
			}
		}

		// Token: 0x060040A2 RID: 16546 RVA: 0x00113C1C File Offset: 0x00111E1C
		internal void OnOwnerItemFontChanged(EventArgs e)
		{
			if (this.IsAutoGenerated)
			{
				using (new LayoutTransaction(this, this.OwnerItem, PropertyNames.Font))
				{
					this.OnFontChanged(e);
				}
			}
		}

		// Token: 0x060040A3 RID: 16547 RVA: 0x00113C68 File Offset: 0x00111E68
		internal void SelectPreviousToolStrip()
		{
			ToolStripItem toolStripItem = this.OwnerItem;
			base.Hide();
			if (toolStripItem != null)
			{
				toolStripItem.Select();
				if (!AccessibilityImprovements.UseLegacyToolTipDisplay)
				{
					KeyboardToolTipStateMachine.Instance.NotifyAboutGotFocus(toolStripItem);
				}
				if (this.OwnerToolStrip != null && !this.OwnerToolStrip.IsDropDown)
				{
					if (ToolStripManager.ModalMenuFilter.GetActiveToolStrip() != this.OwnerToolStrip)
					{
						ToolStripManager.ModalMenuFilter.SetActiveToolStrip(this.OwnerToolStrip);
					}
					this.OwnerToolStrip.MenuAutoExpand = false;
					if (this.OwnerToolStrip.CanSelect)
					{
						ToolStripManager.ModalMenuFilter.ExitMenuMode();
						return;
					}
				}
			}
			else
			{
				ToolStripManager.ModalMenuFilter.ExitMenuMode();
			}
		}

		// Token: 0x060040A4 RID: 16548 RVA: 0x00113CF0 File Offset: 0x00111EF0
		internal override bool ProcessArrowKey(Keys keyCode)
		{
			ToolStripMenuItem.MenuTimer.Cancel();
			if (keyCode == Keys.Left || keyCode == Keys.Right)
			{
				bool rightAlignedMenus = SystemInformation.RightAlignedMenus;
				bool flag = (keyCode == Keys.Left && rightAlignedMenus) || (keyCode == Keys.Right && !rightAlignedMenus);
				if (!this.IsFirstDropDown && !flag)
				{
					this.Visible = false;
					return true;
				}
				bool flag2 = false;
				if (base.LayoutStyle == ToolStripLayoutStyle.Flow)
				{
					flag2 = (FlowLayout.GetFlowDirection(this) == FlowDirection.TopDown && !FlowLayout.GetWrapContents(this));
				}
				if (flag2)
				{
					ToolStrip toplevelOwnerToolStrip = this.GetToplevelOwnerToolStrip();
					ToolStripItem toplevelOwnerItem = this.GetToplevelOwnerItem();
					bool flag3 = this.OwnerItem != null && this.OwnerItem.IsOnOverflow;
					if (flag || !flag3)
					{
						this.SetCloseReason(ToolStripDropDownCloseReason.Keyboard);
						this.DismissAll();
					}
					else if (flag3)
					{
						this.Visible = false;
					}
					if (toplevelOwnerToolStrip != null && toplevelOwnerItem != null)
					{
						if (ToolStripManager.ModalMenuFilter.GetActiveToolStrip() != toplevelOwnerToolStrip)
						{
							ToolStripManager.ModalMenuFilter.SetActiveToolStrip(toplevelOwnerToolStrip);
						}
						toplevelOwnerToolStrip.SelectNextToolStripItem(toplevelOwnerItem, flag);
					}
					return true;
				}
			}
			return base.ProcessArrowKey(keyCode);
		}

		// Token: 0x060040A5 RID: 16549 RVA: 0x00113DDC File Offset: 0x00111FDC
		[UIPermission(SecurityAction.LinkDemand, Window = UIPermissionWindow.AllWindows)]
		protected override bool ProcessDialogKey(Keys keyData)
		{
			if (this.OwnerItem != null && this.OwnerItem.IsInDesignMode)
			{
				return false;
			}
			if (this.AutoClose && this.Visible)
			{
				if (ToolStripManager.IsMenuKey(keyData))
				{
					this.SetCloseReason(ToolStripDropDownCloseReason.Keyboard);
					this.DismissAll();
					ToolStrip toplevelOwnerToolStrip = this.GetToplevelOwnerToolStrip();
					if (toplevelOwnerToolStrip != null)
					{
						toplevelOwnerToolStrip.RestoreFocusInternal();
						ToolStripManager.ModalMenuFilter.MenuKeyToggle = true;
					}
					ToolStripManager.ModalMenuFilter.ExitMenuMode();
					return true;
				}
				if ((keyData & Keys.KeyCode) == Keys.Escape)
				{
					this.SetCloseReason(ToolStripDropDownCloseReason.Keyboard);
					this.SelectPreviousToolStrip();
					return true;
				}
			}
			return base.ProcessDialogKey(keyData);
		}

		// Token: 0x060040A6 RID: 16550 RVA: 0x00113E63 File Offset: 0x00112063
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		[UIPermission(SecurityAction.LinkDemand, Window = UIPermissionWindow.AllWindows)]
		protected override bool ProcessDialogChar(char charCode)
		{
			return ((this.OwnerItem == null || this.OwnerItem.Pressed) && charCode != ' ' && this.ProcessMnemonic(charCode)) || base.ProcessDialogChar(charCode);
		}

		// Token: 0x060040A7 RID: 16551 RVA: 0x00113E91 File Offset: 0x00112091
		[UIPermission(SecurityAction.LinkDemand, Window = UIPermissionWindow.AllWindows)]
		protected internal override bool ProcessMnemonic(char charCode)
		{
			return this.CanProcessMnemonic() && base.ProcessMnemonic(charCode);
		}

		// Token: 0x060040A8 RID: 16552 RVA: 0x00113EA4 File Offset: 0x001120A4
		internal override void ProcessDuplicateMnemonic(ToolStripItem item, char charCode)
		{
			if (!this.CanProcessMnemonic())
			{
				return;
			}
			if (item != null)
			{
				if (this.IsRestrictedWindow)
				{
					item.ProcessMnemonic(charCode);
					return;
				}
				base.ProcessDuplicateMnemonic(item, charCode);
			}
		}

		// Token: 0x060040A9 RID: 16553 RVA: 0x00113ECB File Offset: 0x001120CB
		internal override void RecreateHandleCore()
		{
			if (this.Visible)
			{
				this.ReparentToDropDownOwnerWindow();
			}
			base.RecreateHandleCore();
			if (this.Visible)
			{
				this.ReparentToActiveToolStripWindow();
			}
		}

		// Token: 0x060040AA RID: 16554 RVA: 0x00113EEF File Offset: 0x001120EF
		private void ResetDropShadowEnabled()
		{
			this.DropShadowEnabled = true;
		}

		// Token: 0x060040AB RID: 16555 RVA: 0x00113EF8 File Offset: 0x001120F8
		private void ReparentToActiveToolStripWindow()
		{
			ToolStripManager.ModalMenuFilter.SetActiveToolStrip(this);
			UnsafeNativeMethods.SetWindowLong(new HandleRef(this, base.Handle), -8, ToolStripManager.ModalMenuFilter.ActiveHwnd);
		}

		// Token: 0x060040AC RID: 16556 RVA: 0x00113F1C File Offset: 0x0011211C
		private void ReparentToDropDownOwnerWindow()
		{
			NativeWindow dropDownOwnerWindow = this.DropDownOwnerWindow;
			HandleRef dwNewLong = new HandleRef(dropDownOwnerWindow, dropDownOwnerWindow.Handle);
			UnsafeNativeMethods.SetWindowLong(new HandleRef(this, base.Handle), -8, dwNewLong);
		}

		// Token: 0x060040AD RID: 16557 RVA: 0x00113F53 File Offset: 0x00112153
		internal override void ResetScaling(int newDpi)
		{
			base.ResetScaling(newDpi);
			CommonProperties.xClearPreferredSizeCache(this);
			this.scaledDefaultPadding = DpiHelper.LogicalToDeviceUnits(ToolStripDropDown.defaultPadding, newDpi);
		}

		// Token: 0x060040AE RID: 16558 RVA: 0x00113F74 File Offset: 0x00112174
		[EditorBrowsable(EditorBrowsableState.Never)]
		protected override void ScaleCore(float dx, float dy)
		{
			base.SuspendLayout();
			try
			{
				Size clientSize = base.ClientSize;
				Size minimumSize = this.MinimumSize;
				Size maximumSize = this.MaximumSize;
				base.ClientSize = base.ScaleSize(clientSize, dx, dy);
				if (!this.MinimumSize.IsEmpty)
				{
					this.MinimumSize = base.ScaleSize(minimumSize, dx, dy);
				}
				if (!this.MaximumSize.IsEmpty)
				{
					this.MaximumSize = base.ScaleSize(maximumSize, dx, dy);
				}
				base.ScaleDockPadding(dx, dy);
				foreach (object obj in base.Controls)
				{
					Control control = (Control)obj;
					if (control != null)
					{
						control.Scale(dx, dy);
					}
				}
			}
			finally
			{
				base.ResumeLayout();
			}
		}

		// Token: 0x060040AF RID: 16559 RVA: 0x00114060 File Offset: 0x00112260
		protected override void ScaleControl(SizeF factor, BoundsSpecified specified)
		{
			base.ScaleControl(factor, specified);
			Size minimumSize = this.MinimumSize;
			Size maximumSize = this.MaximumSize;
			if (!this.MinimumSize.IsEmpty)
			{
				this.MinimumSize = base.ScaleSize(minimumSize, factor.Width, factor.Height);
			}
			if (!this.MaximumSize.IsEmpty)
			{
				this.MaximumSize = base.ScaleSize(maximumSize, factor.Width, factor.Height);
			}
		}

		// Token: 0x060040B0 RID: 16560 RVA: 0x001140D9 File Offset: 0x001122D9
		internal void SetAutoGeneratedInternal(bool autoGenerated)
		{
			this.isAutoGenerated = autoGenerated;
		}

		// Token: 0x060040B1 RID: 16561 RVA: 0x001140E4 File Offset: 0x001122E4
		protected override void SetBoundsCore(int x, int y, int width, int height, BoundsSpecified specified)
		{
			Rectangle dropDownBounds = new Rectangle(x, y, width, height);
			dropDownBounds = this.GetDropDownBounds(dropDownBounds);
			base.SetBoundsCore(dropDownBounds.X, dropDownBounds.Y, dropDownBounds.Width, dropDownBounds.Height, specified);
		}

		// Token: 0x060040B2 RID: 16562 RVA: 0x0011412C File Offset: 0x0011232C
		private void SetTopLevelStyle(bool value)
		{
			if (base.IsHandleCreated)
			{
				int num = base.WindowStyle;
				if (value)
				{
					num &= -1073741825;
					num |= int.MinValue;
				}
				else
				{
					num &= int.MaxValue;
					num |= 1073741824;
				}
				base.WindowStyle = num;
			}
		}

		// Token: 0x060040B3 RID: 16563 RVA: 0x00114174 File Offset: 0x00112374
		protected override void SetVisibleCore(bool visible)
		{
			if (this.state[ToolStripDropDown.stateInSetVisibleCore])
			{
				return;
			}
			this.state[ToolStripDropDown.stateInSetVisibleCore] = true;
			try
			{
				if (visible)
				{
					if (base.LayoutRequired)
					{
						LayoutTransaction.DoLayout(this, this, PropertyNames.Visible);
					}
					bool flag = true;
					try
					{
						IntPtr foregroundWindow = UnsafeNativeMethods.GetForegroundWindow();
						CancelEventArgs cancelEventArgs = new CancelEventArgs(this.DisplayedItems.Count == 0);
						this.OnOpening(cancelEventArgs);
						flag = cancelEventArgs.Cancel;
						if (!flag)
						{
							if (this.TopLevel)
							{
								this.ReparentToActiveToolStripWindow();
							}
							if (this.OwnerToolStrip != null)
							{
								this.OwnerToolStrip.ActiveDropDowns.Add(this);
								this.OwnerToolStrip.SnapMouseLocation();
								if (this.OwnerToolStrip.CaptureInternal)
								{
									base.CaptureInternal = true;
								}
							}
							base.SetVisibleCore(visible);
							if (this.TopLevel)
							{
								this.ApplyTopMost(true);
							}
							else if (base.IsHandleCreated && SafeNativeMethods.IsWindowEnabled(new HandleRef(this, base.Handle)))
							{
								SafeNativeMethods.SetWindowPos(new HandleRef(this, base.Handle), NativeMethods.HWND_TOP, 0, 0, 0, 0, 19);
							}
						}
						return;
					}
					finally
					{
						if (!flag)
						{
							this.OnOpened(new EventArgs());
						}
					}
				}
				if (this.GetVisibleCore())
				{
					ToolStripDropDownCloseReason toolStripDropDownCloseReason = this.closeReason;
					this.ResetCloseReason();
					ToolStripDropDownClosingEventArgs toolStripDropDownClosingEventArgs = new ToolStripDropDownClosingEventArgs(toolStripDropDownCloseReason);
					if (toolStripDropDownClosingEventArgs.CloseReason != ToolStripDropDownCloseReason.CloseCalled)
					{
						toolStripDropDownClosingEventArgs.Cancel = !this.AutoClose;
					}
					else
					{
						toolStripDropDownClosingEventArgs.Cancel = false;
					}
					try
					{
						this.OnClosing(toolStripDropDownClosingEventArgs);
						return;
					}
					finally
					{
						if (!toolStripDropDownClosingEventArgs.Cancel || this.IsRestrictedWindow)
						{
							this.DismissActiveDropDowns();
							ToolStrip toplevelOwnerToolStrip = this.GetToplevelOwnerToolStrip();
							ToolStrip toolStrip = null;
							if (this.OwnerItem != null)
							{
								toolStrip = this.OwnerItem.ParentInternal;
							}
							if (toolStripDropDownCloseReason == ToolStripDropDownCloseReason.AppClicked || toolStripDropDownCloseReason == ToolStripDropDownCloseReason.ItemClicked || (toolStripDropDownCloseReason == ToolStripDropDownCloseReason.CloseCalled && toplevelOwnerToolStrip == toolStrip) || (toolStripDropDownCloseReason == ToolStripDropDownCloseReason.AppFocusChange && toplevelOwnerToolStrip == toolStrip))
							{
								this.CancelAutoExpand();
							}
							if (toolStripDropDownCloseReason == ToolStripDropDownCloseReason.ItemClicked)
							{
								this.saveSourceControl = true;
								this.DismissAll();
								ToolStripItem toplevelOwnerItem = this.GetToplevelOwnerItem();
								if (toplevelOwnerItem != null)
								{
									toplevelOwnerItem.Unselect();
								}
								ToolStripManager.ModalMenuFilter.RemoveActiveToolStrip(this);
								ToolStripManager.ModalMenuFilter.ExitMenuMode();
							}
							else
							{
								ToolStripManager.ModalMenuFilter.RemoveActiveToolStrip(this);
							}
							Rectangle bounds = base.Bounds;
							try
							{
								base.SetVisibleCore(visible);
							}
							finally
							{
								if (this.OwnerToolStrip != null)
								{
									this.OwnerToolStrip.ActiveDropDowns.Remove(this);
								}
								base.ActiveDropDowns.Clear();
								if (base.CaptureInternal)
								{
									base.CaptureInternal = false;
								}
							}
							ToolStripDropDownClosedEventArgs e = new ToolStripDropDownClosedEventArgs(toolStripDropDownCloseReason);
							this.OnClosed(e);
							if (this.TopLevel && (!base.IsDisposed || !base.Disposing))
							{
								this.ReparentToDropDownOwnerWindow();
							}
							if (!this.saveSourceControl)
							{
								this.SourceControlInternal = null;
							}
							if (!base.DesignMode && this.IsFirstDropDown && this.OwnerItem != null && this.TopLevel)
							{
								ToolStrip toplevelOwnerToolStrip2 = this.GetToplevelOwnerToolStrip();
								if (toplevelOwnerToolStrip2 != null && !toplevelOwnerToolStrip2.IsDisposed && !toplevelOwnerToolStrip2.Disposing)
								{
									bounds.Location = toplevelOwnerToolStrip2.PointToClient(bounds.Location);
									bounds.Intersect(toplevelOwnerToolStrip2.ClientRectangle);
									if (bounds.Width > 0 && bounds.Height > 0)
									{
										toplevelOwnerToolStrip2.Invalidate(bounds);
										toplevelOwnerToolStrip2.Update();
									}
								}
							}
						}
					}
				}
				ToolStripManager.ModalMenuFilter.RemoveActiveToolStrip(this);
			}
			finally
			{
				this.state[ToolStripDropDown.stateInSetVisibleCore] = false;
				this.saveSourceControl = false;
			}
		}

		// Token: 0x060040B4 RID: 16564 RVA: 0x00114510 File Offset: 0x00112710
		private bool ShouldSerializeDefaultDropDownDirection()
		{
			return this.childDropDownDirection != ToolStripDropDownDirection.Default;
		}

		// Token: 0x060040B5 RID: 16565 RVA: 0x00114520 File Offset: 0x00112720
		private void UpdateLayered()
		{
			if (this.state[ToolStripDropDown.stateLayered] && base.IsHandleCreated && this.TopLevel && OSFeature.Feature.IsPresent(OSFeature.LayeredWindows) && !UnsafeNativeMethods.SetLayeredWindowAttributes(new HandleRef(this, base.Handle), 0, this.OpacityAsByte, 2))
			{
				throw new Win32Exception();
			}
		}

		// Token: 0x060040B6 RID: 16566 RVA: 0x00114583 File Offset: 0x00112783
		[Browsable(false)]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public new void Show()
		{
			base.Show();
		}

		// Token: 0x060040B7 RID: 16567 RVA: 0x0011458C File Offset: 0x0011278C
		public void Show(Control control, Point position)
		{
			if (control == null)
			{
				throw new ArgumentNullException("control");
			}
			this.SourceControlInternal = control;
			if (this.OwnerItem == null && control.RightToLeft == RightToLeft.Yes)
			{
				this.AdjustSize();
				position.Offset(control.IsMirrored ? base.Width : (-base.Width), 0);
			}
			this.displayLocation = control.PointToScreen(position);
			this.Location = this.displayLocation;
			this.ShowCore();
		}

		// Token: 0x060040B8 RID: 16568 RVA: 0x00114604 File Offset: 0x00112804
		public void Show(Control control, Point position, ToolStripDropDownDirection direction)
		{
			if (control == null)
			{
				throw new ArgumentNullException("control");
			}
			this.SourceControlInternal = control;
			this.displayLocation = this.CalculateDropDownLocation(control.PointToScreen(position), direction).Location;
			this.Location = this.displayLocation;
			this.ShowCore();
		}

		// Token: 0x060040B9 RID: 16569 RVA: 0x00114654 File Offset: 0x00112854
		public void Show(Control control, int x, int y)
		{
			if (control == null)
			{
				throw new ArgumentNullException("control");
			}
			this.SourceControlInternal = control;
			this.Show(control, new Point(x, y));
		}

		// Token: 0x060040BA RID: 16570 RVA: 0x00114679 File Offset: 0x00112879
		public void Show(Point screenLocation)
		{
			this.displayLocation = screenLocation;
			this.Location = this.displayLocation;
			this.ShowCore();
		}

		// Token: 0x060040BB RID: 16571 RVA: 0x00114694 File Offset: 0x00112894
		public void Show(Point position, ToolStripDropDownDirection direction)
		{
			this.displayLocation = this.CalculateDropDownLocation(position, direction).Location;
			this.Location = this.displayLocation;
			this.ShowCore();
		}

		// Token: 0x060040BC RID: 16572 RVA: 0x001146C9 File Offset: 0x001128C9
		public void Show(int x, int y)
		{
			this.displayLocation = new Point(x, y);
			this.Location = this.displayLocation;
			this.ShowCore();
		}

		// Token: 0x060040BD RID: 16573 RVA: 0x001146EA File Offset: 0x001128EA
		private void ShowCore()
		{
			this.Show();
		}

		// Token: 0x060040BE RID: 16574 RVA: 0x001146F2 File Offset: 0x001128F2
		private bool ShouldSerializeDropShadowEnabled()
		{
			return !this.dropShadowEnabled;
		}

		// Token: 0x060040BF RID: 16575 RVA: 0x001146FD File Offset: 0x001128FD
		internal override bool ShouldSerializeLayoutStyle()
		{
			return base.LayoutStyle != ToolStripLayoutStyle.VerticalStackWithOverflow;
		}

		// Token: 0x060040C0 RID: 16576 RVA: 0x0011470C File Offset: 0x0011290C
		internal void UnassignDropDownItem()
		{
			int val = this.countDropDownItemsAssignedTo - 1;
			this.countDropDownItemsAssignedTo = val;
			this.countDropDownItemsAssignedTo = Math.Max(val, 0);
		}

		// Token: 0x060040C1 RID: 16577 RVA: 0x00114738 File Offset: 0x00112938
		[SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
		protected override void WndProc(ref Message m)
		{
			if (m.Msg >= 256 && m.Msg <= 264 && this.IsRestrictedWindow)
			{
				this.DefWndProc(ref m);
				return;
			}
			int msg = m.Msg;
			if (msg == 6)
			{
				if ((int)m.WParam == 1 && this.Visible && ToolStripManager.ModalMenuFilter.GetActiveToolStrip() != this)
				{
					ToolStripManager.ModalMenuFilter.SetActiveToolStrip(this);
				}
				base.WndProc(ref m);
				return;
			}
			if (msg == 134)
			{
				this.WmNCActivate(ref m);
				return;
			}
			base.WndProc(ref m);
		}

		// Token: 0x060040C2 RID: 16578 RVA: 0x001147C0 File Offset: 0x001129C0
		internal void DismissAll()
		{
			ToolStripDropDown firstDropDown = this.GetFirstDropDown();
			firstDropDown.closeReason = this.closeReason;
			firstDropDown.DismissActiveDropDowns();
			if (!LocalAppContextSwitches.UseLegacyContextMenuStripSourceControlValue)
			{
				firstDropDown.saveSourceControl = this.saveSourceControl;
			}
			firstDropDown.Visible = false;
		}

		// Token: 0x060040C3 RID: 16579 RVA: 0x00114800 File Offset: 0x00112A00
		private void DismissActiveDropDowns()
		{
			int count = base.ActiveDropDowns.Count;
			if (count == 1)
			{
				ToolStripDropDown toolStripDropDown = base.ActiveDropDowns[0] as ToolStripDropDown;
				if (toolStripDropDown != null)
				{
					toolStripDropDown.Visible = false;
					return;
				}
			}
			else
			{
				ArrayList arrayList = base.ActiveDropDowns.Clone() as ArrayList;
				for (int i = 0; i < arrayList.Count; i++)
				{
					ToolStripDropDown toolStripDropDown2 = arrayList[i] as ToolStripDropDown;
					if (toolStripDropDown2 != null)
					{
						toolStripDropDown2.Visible = false;
					}
				}
			}
		}

		// Token: 0x060040C4 RID: 16580 RVA: 0x00114878 File Offset: 0x00112A78
		private void WmNCActivate(ref Message m)
		{
			if (m.WParam != IntPtr.Zero)
			{
				if (!this.sendingActivateMessage)
				{
					this.sendingActivateMessage = true;
					try
					{
						HandleRef activeHwnd = ToolStripManager.ModalMenuFilter.ActiveHwnd;
						UnsafeNativeMethods.SendMessage(activeHwnd, 134, (IntPtr)1, NativeMethods.InvalidIntPtr);
						SafeNativeMethods.RedrawWindow(activeHwnd, null, NativeMethods.NullHandleRef, 1025);
						m.WParam = (IntPtr)1;
					}
					finally
					{
						this.sendingActivateMessage = false;
					}
				}
				this.DefWndProc(ref m);
				return;
			}
			base.WndProc(ref m);
		}

		// Token: 0x17000FCF RID: 4047
		// (get) Token: 0x060040C5 RID: 16581 RVA: 0x0011490C File Offset: 0x00112B0C
		internal bool IsFirstDropDown
		{
			get
			{
				return !(this.OwnerToolStrip is ToolStripDropDown);
			}
		}

		// Token: 0x060040C6 RID: 16582 RVA: 0x0011491C File Offset: 0x00112B1C
		internal ToolStripDropDown GetFirstDropDown()
		{
			ToolStripDropDown toolStripDropDown = this;
			for (ToolStripDropDown toolStripDropDown2 = toolStripDropDown.OwnerToolStrip as ToolStripDropDown; toolStripDropDown2 != null; toolStripDropDown2 = (toolStripDropDown.OwnerToolStrip as ToolStripDropDown))
			{
				toolStripDropDown = toolStripDropDown2;
			}
			return toolStripDropDown;
		}

		// Token: 0x060040C7 RID: 16583 RVA: 0x0011494C File Offset: 0x00112B4C
		internal static ToolStripDropDown GetFirstDropDown(ToolStrip start)
		{
			if (start == null || !start.IsDropDown)
			{
				return null;
			}
			ToolStripDropDown toolStripDropDown = start as ToolStripDropDown;
			return toolStripDropDown.GetFirstDropDown();
		}

		// Token: 0x040024BD RID: 9405
		private ToolStripItem ownerItem;

		// Token: 0x040024BE RID: 9406
		private bool isAutoGenerated;

		// Token: 0x040024BF RID: 9407
		private Point dropDownLocation = Point.Empty;

		// Token: 0x040024C0 RID: 9408
		private bool dropShadowEnabled = true;

		// Token: 0x040024C1 RID: 9409
		private bool autoClose = true;

		// Token: 0x040024C2 RID: 9410
		private bool autoSize = true;

		// Token: 0x040024C3 RID: 9411
		private int countDropDownItemsAssignedTo;

		// Token: 0x040024C4 RID: 9412
		private BitVector32 state;

		// Token: 0x040024C5 RID: 9413
		private Point displayLocation = new Point(0, 0);

		// Token: 0x040024C6 RID: 9414
		private bool saveSourceControl;

		// Token: 0x040024C7 RID: 9415
		private ToolStripDropDownDirection childDropDownDirection = ToolStripDropDownDirection.Default;

		// Token: 0x040024C8 RID: 9416
		private ToolStripDropDownCloseReason closeReason;

		// Token: 0x040024C9 RID: 9417
		private static readonly int PropOpacity = PropertyStore.CreateKey();

		// Token: 0x040024CA RID: 9418
		private static readonly int PropDDRightToLeft = PropertyStore.CreateKey();

		// Token: 0x040024CB RID: 9419
		private static readonly int PropSourceControl = PropertyStore.CreateKey();

		// Token: 0x040024CC RID: 9420
		private static readonly object EventOpening = new object();

		// Token: 0x040024CD RID: 9421
		private static readonly object EventOpened = new object();

		// Token: 0x040024CE RID: 9422
		private static readonly object EventClosed = new object();

		// Token: 0x040024CF RID: 9423
		private static readonly object EventClosing = new object();

		// Token: 0x040024D0 RID: 9424
		private static readonly object ToolStripParkingWindowKey = new object();

		// Token: 0x040024D1 RID: 9425
		private static readonly Padding defaultPadding = new Padding(1, 2, 1, 2);

		// Token: 0x040024D2 RID: 9426
		private Padding scaledDefaultPadding = ToolStripDropDown.defaultPadding;

		// Token: 0x040024D3 RID: 9427
		internal static TraceSwitch DropDownActivateDebug;

		// Token: 0x040024D4 RID: 9428
		internal static TraceSwitch DropDownDebugBounds;

		// Token: 0x040024D5 RID: 9429
		private static readonly int stateLayered = BitVector32.CreateMask();

		// Token: 0x040024D6 RID: 9430
		private static readonly int stateAllowTransparency = BitVector32.CreateMask(ToolStripDropDown.stateLayered);

		// Token: 0x040024D7 RID: 9431
		private static readonly int stateIsRestrictedWindow = BitVector32.CreateMask(ToolStripDropDown.stateAllowTransparency);

		// Token: 0x040024D8 RID: 9432
		private static readonly int stateIsRestrictedWindowChecked = BitVector32.CreateMask(ToolStripDropDown.stateIsRestrictedWindow);

		// Token: 0x040024D9 RID: 9433
		private static readonly int stateNotWorkingAreaConstrained = BitVector32.CreateMask(ToolStripDropDown.stateIsRestrictedWindowChecked);

		// Token: 0x040024DA RID: 9434
		private static readonly int stateInSetVisibleCore = BitVector32.CreateMask(ToolStripDropDown.stateNotWorkingAreaConstrained);

		// Token: 0x040024DB RID: 9435
		private bool sendingActivateMessage;

		// Token: 0x02000800 RID: 2048
		[ComVisible(true)]
		public class ToolStripDropDownAccessibleObject : ToolStrip.ToolStripAccessibleObject
		{
			// Token: 0x06006EE2 RID: 28386 RVA: 0x0019695E File Offset: 0x00194B5E
			public ToolStripDropDownAccessibleObject(ToolStripDropDown owner) : base(owner)
			{
				this.owner = owner;
			}

			// Token: 0x06006EE3 RID: 28387 RVA: 0x0019696E File Offset: 0x00194B6E
			internal override void ClearOwnerControlInternal()
			{
				this.owner = null;
				base.ClearOwnerControlInternal();
			}

			// Token: 0x17001837 RID: 6199
			// (get) Token: 0x06006EE4 RID: 28388 RVA: 0x00196980 File Offset: 0x00194B80
			// (set) Token: 0x06006EE5 RID: 28389 RVA: 0x001969F3 File Offset: 0x00194BF3
			public override string Name
			{
				get
				{
					if (base.IsOwnerControlDestroyed())
					{
						return string.Empty;
					}
					string text = this.owner.AccessibleName;
					if (text != null)
					{
						return text;
					}
					text = "DropDown";
					if (this.owner.OwnerItem != null && this.owner.OwnerItem.AccessibilityObject.Name != null)
					{
						text = this.owner.OwnerItem.AccessibilityObject.Name + text;
					}
					return text;
				}
				set
				{
					if (base.IsOwnerControlDestroyed())
					{
						return;
					}
					this.owner.AccessibleName = value;
				}
			}

			// Token: 0x17001838 RID: 6200
			// (get) Token: 0x06006EE6 RID: 28390 RVA: 0x00196A0C File Offset: 0x00194C0C
			public override AccessibleRole Role
			{
				get
				{
					if (base.IsOwnerControlDestroyed())
					{
						return AccessibleRole.MenuPopup;
					}
					AccessibleRole accessibleRole = base.Owner.AccessibleRole;
					if (accessibleRole != AccessibleRole.Default)
					{
						return accessibleRole;
					}
					return AccessibleRole.MenuPopup;
				}
			}

			// Token: 0x040042F9 RID: 17145
			private ToolStripDropDown owner;
		}
	}
}
