using System;
using System.Collections.Specialized;
using System.ComponentModel;

namespace System.Windows.Forms
{
	// Token: 0x020003FA RID: 1018
	internal class ToolStripRendererSwitcher
	{
		// Token: 0x06004664 RID: 18020 RVA: 0x00128418 File Offset: 0x00126618
		public ToolStripRendererSwitcher(Control owner, ToolStripRenderMode defaultRenderMode) : this(owner)
		{
			this.defaultRenderMode = defaultRenderMode;
			this.RenderMode = defaultRenderMode;
		}

		// Token: 0x06004665 RID: 18021 RVA: 0x00128430 File Offset: 0x00126630
		public ToolStripRendererSwitcher(Control owner)
		{
			this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
			this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			owner.Disposed += this.OnControlDisposed;
			owner.VisibleChanged += this.OnControlVisibleChanged;
			if (owner.Visible)
			{
				this.OnControlVisibleChanged(owner, EventArgs.Empty);
			}
		}

		// Token: 0x1700113A RID: 4410
		// (get) Token: 0x06004666 RID: 18022 RVA: 0x001284B4 File Offset: 0x001266B4
		// (set) Token: 0x06004667 RID: 18023 RVA: 0x00128500 File Offset: 0x00126700
		public ToolStripRenderer Renderer
		{
			get
			{
				if (this.RenderMode == ToolStripRenderMode.ManagerRenderMode)
				{
					return ToolStripManager.Renderer;
				}
				this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
				if (this.renderer == null)
				{
					this.Renderer = ToolStripManager.CreateRenderer(this.RenderMode);
				}
				return this.renderer;
			}
			set
			{
				if (this.renderer != value)
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = (value == null);
					this.renderer = value;
					this.currentRendererType = ((this.renderer != null) ? this.renderer.GetType() : typeof(Type));
					this.OnRendererChanged(EventArgs.Empty);
				}
			}
		}

		// Token: 0x1700113B RID: 4411
		// (get) Token: 0x06004668 RID: 18024 RVA: 0x00128564 File Offset: 0x00126764
		// (set) Token: 0x06004669 RID: 18025 RVA: 0x001285C8 File Offset: 0x001267C8
		public ToolStripRenderMode RenderMode
		{
			get
			{
				if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
				{
					return ToolStripRenderMode.ManagerRenderMode;
				}
				if (this.renderer != null && !this.renderer.IsAutoGenerated)
				{
					return ToolStripRenderMode.Custom;
				}
				if (this.currentRendererType == ToolStripManager.ProfessionalRendererType)
				{
					return ToolStripRenderMode.Professional;
				}
				if (this.currentRendererType == ToolStripManager.SystemRendererType)
				{
					return ToolStripRenderMode.System;
				}
				return ToolStripRenderMode.Custom;
			}
			set
			{
				if (!ClientUtils.IsEnumValid(value, (int)value, 0, 3))
				{
					throw new InvalidEnumArgumentException("value", (int)value, typeof(ToolStripRenderMode));
				}
				if (value == ToolStripRenderMode.Custom)
				{
					throw new NotSupportedException(SR.GetString("ToolStripRenderModeUseRendererPropertyInstead"));
				}
				if (value == ToolStripRenderMode.ManagerRenderMode)
				{
					if (!this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
					{
						this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
						this.OnRendererChanged(EventArgs.Empty);
						return;
					}
				}
				else
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
					this.Renderer = ToolStripManager.CreateRenderer(value);
				}
			}
		}

		// Token: 0x14000387 RID: 903
		// (add) Token: 0x0600466A RID: 18026 RVA: 0x00128660 File Offset: 0x00126860
		// (remove) Token: 0x0600466B RID: 18027 RVA: 0x00128698 File Offset: 0x00126898
		public event EventHandler RendererChanged;

		// Token: 0x0600466C RID: 18028 RVA: 0x001286CD File Offset: 0x001268CD
		private void OnRendererChanged(EventArgs e)
		{
			if (this.RendererChanged != null)
			{
				this.RendererChanged(this, e);
			}
		}

		// Token: 0x0600466D RID: 18029 RVA: 0x001286E4 File Offset: 0x001268E4
		private void OnDefaultRendererChanged(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
			{
				this.OnRendererChanged(e);
			}
		}

		// Token: 0x0600466E RID: 18030 RVA: 0x001286FF File Offset: 0x001268FF
		private void OnControlDisposed(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
			{
				ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
				this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			}
		}

		// Token: 0x0600466F RID: 18031 RVA: 0x00128738 File Offset: 0x00126938
		private void OnControlVisibleChanged(object sender, EventArgs e)
		{
			Control control = sender as Control;
			if (control != null)
			{
				if (control.Visible)
				{
					if (!this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
					{
						ToolStripManager.RendererChanged += this.OnDefaultRendererChanged;
						this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = true;
						return;
					}
				}
				else if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
				{
					ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
					this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
				}
			}
		}

		// Token: 0x06004670 RID: 18032 RVA: 0x001287C0 File Offset: 0x001269C0
		public bool ShouldSerializeRenderMode()
		{
			return this.RenderMode != this.defaultRenderMode && this.RenderMode > ToolStripRenderMode.Custom;
		}

		// Token: 0x06004671 RID: 18033 RVA: 0x001287DB File Offset: 0x001269DB
		public void ResetRenderMode()
		{
			this.RenderMode = this.defaultRenderMode;
		}

		// Token: 0x040026A5 RID: 9893
		private static readonly int stateUseDefaultRenderer = BitVector32.CreateMask();

		// Token: 0x040026A6 RID: 9894
		private static readonly int stateAttachedRendererChanged = BitVector32.CreateMask(ToolStripRendererSwitcher.stateUseDefaultRenderer);

		// Token: 0x040026A7 RID: 9895
		private ToolStripRenderer renderer;

		// Token: 0x040026A8 RID: 9896
		private Type currentRendererType = typeof(Type);

		// Token: 0x040026A9 RID: 9897
		private BitVector32 state;

		// Token: 0x040026AA RID: 9898
		private ToolStripRenderMode defaultRenderMode = ToolStripRenderMode.ManagerRenderMode;
	}
}
