using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	// Token: 0x020003F9 RID: 1017
	public abstract class ToolStripRenderer
	{
		// Token: 0x06004601 RID: 17921 RVA: 0x00127111 File Offset: 0x00125311
		protected ToolStripRenderer()
		{
		}

		// Token: 0x06004602 RID: 17922 RVA: 0x00127124 File Offset: 0x00125324
		internal ToolStripRenderer(bool isAutoGenerated)
		{
			this.isAutoGenerated = isAutoGenerated;
		}

		// Token: 0x17001136 RID: 4406
		// (get) Token: 0x06004603 RID: 17923 RVA: 0x00127140 File Offset: 0x00125340
		private static ColorMatrix DisabledImageColorMatrix
		{
			get
			{
				if (ToolStripRenderer.disabledImageColorMatrix == null)
				{
					float[][] array = new float[5][];
					array[0] = new float[]
					{
						0.2125f,
						0.2125f,
						0.2125f,
						0f,
						0f
					};
					array[1] = new float[]
					{
						0.2577f,
						0.2577f,
						0.2577f,
						0f,
						0f
					};
					array[2] = new float[]
					{
						0.0361f,
						0.0361f,
						0.0361f,
						0f,
						0f
					};
					float[][] array2 = array;
					int num = 3;
					float[] array3 = new float[5];
					array3[3] = 1f;
					array2[num] = array3;
					array[4] = new float[]
					{
						0.38f,
						0.38f,
						0.38f,
						0f,
						1f
					};
					float[][] array4 = new float[5][];
					float[][] array5 = array4;
					int num2 = 0;
					float[] array6 = new float[5];
					array6[0] = 1f;
					array5[num2] = array6;
					float[][] array7 = array4;
					int num3 = 1;
					float[] array8 = new float[5];
					array8[1] = 1f;
					array7[num3] = array8;
					float[][] array9 = array4;
					int num4 = 2;
					float[] array10 = new float[5];
					array10[2] = 1f;
					array9[num4] = array10;
					float[][] array11 = array4;
					int num5 = 3;
					float[] array12 = new float[5];
					array12[3] = 0.7f;
					array11[num5] = array12;
					array4[4] = new float[5];
					ToolStripRenderer.disabledImageColorMatrix = ControlPaint.MultiplyColorMatrix(array4, array);
				}
				return ToolStripRenderer.disabledImageColorMatrix;
			}
		}

		// Token: 0x17001137 RID: 4407
		// (get) Token: 0x06004604 RID: 17924 RVA: 0x00127224 File Offset: 0x00125424
		private EventHandlerList Events
		{
			get
			{
				if (this.events == null)
				{
					this.events = new EventHandlerList();
				}
				return this.events;
			}
		}

		// Token: 0x17001138 RID: 4408
		// (get) Token: 0x06004605 RID: 17925 RVA: 0x0012723F File Offset: 0x0012543F
		internal bool IsAutoGenerated
		{
			get
			{
				return this.isAutoGenerated;
			}
		}

		// Token: 0x17001139 RID: 4409
		// (get) Token: 0x06004606 RID: 17926 RVA: 0x00015ECC File Offset: 0x000140CC
		internal virtual ToolStripRenderer RendererOverride
		{
			get
			{
				return null;
			}
		}

		// Token: 0x14000373 RID: 883
		// (add) Token: 0x06004607 RID: 17927 RVA: 0x00127247 File Offset: 0x00125447
		// (remove) Token: 0x06004608 RID: 17928 RVA: 0x00127255 File Offset: 0x00125455
		public event ToolStripArrowRenderEventHandler RenderArrow
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderArrow, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderArrow, value);
			}
		}

		// Token: 0x14000374 RID: 884
		// (add) Token: 0x06004609 RID: 17929 RVA: 0x00127263 File Offset: 0x00125463
		// (remove) Token: 0x0600460A RID: 17930 RVA: 0x00127271 File Offset: 0x00125471
		public event ToolStripRenderEventHandler RenderToolStripBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
		}

		// Token: 0x14000375 RID: 885
		// (add) Token: 0x0600460B RID: 17931 RVA: 0x0012727F File Offset: 0x0012547F
		// (remove) Token: 0x0600460C RID: 17932 RVA: 0x0012728D File Offset: 0x0012548D
		public event ToolStripPanelRenderEventHandler RenderToolStripPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
		}

		// Token: 0x14000376 RID: 886
		// (add) Token: 0x0600460D RID: 17933 RVA: 0x0012729B File Offset: 0x0012549B
		// (remove) Token: 0x0600460E RID: 17934 RVA: 0x001272A9 File Offset: 0x001254A9
		public event ToolStripContentPanelRenderEventHandler RenderToolStripContentPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
		}

		// Token: 0x14000377 RID: 887
		// (add) Token: 0x0600460F RID: 17935 RVA: 0x001272B7 File Offset: 0x001254B7
		// (remove) Token: 0x06004610 RID: 17936 RVA: 0x001272C5 File Offset: 0x001254C5
		public event ToolStripRenderEventHandler RenderToolStripBorder
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderBorder, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderBorder, value);
			}
		}

		// Token: 0x14000378 RID: 888
		// (add) Token: 0x06004611 RID: 17937 RVA: 0x001272D3 File Offset: 0x001254D3
		// (remove) Token: 0x06004612 RID: 17938 RVA: 0x001272E1 File Offset: 0x001254E1
		public event ToolStripItemRenderEventHandler RenderButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
		}

		// Token: 0x14000379 RID: 889
		// (add) Token: 0x06004613 RID: 17939 RVA: 0x001272EF File Offset: 0x001254EF
		// (remove) Token: 0x06004614 RID: 17940 RVA: 0x001272FD File Offset: 0x001254FD
		public event ToolStripItemRenderEventHandler RenderDropDownButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
		}

		// Token: 0x1400037A RID: 890
		// (add) Token: 0x06004615 RID: 17941 RVA: 0x0012730B File Offset: 0x0012550B
		// (remove) Token: 0x06004616 RID: 17942 RVA: 0x00127319 File Offset: 0x00125519
		public event ToolStripItemRenderEventHandler RenderOverflowButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
		}

		// Token: 0x1400037B RID: 891
		// (add) Token: 0x06004617 RID: 17943 RVA: 0x00127327 File Offset: 0x00125527
		// (remove) Token: 0x06004618 RID: 17944 RVA: 0x00127335 File Offset: 0x00125535
		public event ToolStripGripRenderEventHandler RenderGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderGrip, value);
			}
		}

		// Token: 0x1400037C RID: 892
		// (add) Token: 0x06004619 RID: 17945 RVA: 0x00127343 File Offset: 0x00125543
		// (remove) Token: 0x0600461A RID: 17946 RVA: 0x00127351 File Offset: 0x00125551
		public event ToolStripItemRenderEventHandler RenderItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
		}

		// Token: 0x1400037D RID: 893
		// (add) Token: 0x0600461B RID: 17947 RVA: 0x0012735F File Offset: 0x0012555F
		// (remove) Token: 0x0600461C RID: 17948 RVA: 0x0012736D File Offset: 0x0012556D
		public event ToolStripItemImageRenderEventHandler RenderItemImage
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
		}

		// Token: 0x1400037E RID: 894
		// (add) Token: 0x0600461D RID: 17949 RVA: 0x0012737B File Offset: 0x0012557B
		// (remove) Token: 0x0600461E RID: 17950 RVA: 0x00127389 File Offset: 0x00125589
		public event ToolStripItemImageRenderEventHandler RenderItemCheck
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
		}

		// Token: 0x1400037F RID: 895
		// (add) Token: 0x0600461F RID: 17951 RVA: 0x00127397 File Offset: 0x00125597
		// (remove) Token: 0x06004620 RID: 17952 RVA: 0x001273A5 File Offset: 0x001255A5
		public event ToolStripItemTextRenderEventHandler RenderItemText
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemText, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemText, value);
			}
		}

		// Token: 0x14000380 RID: 896
		// (add) Token: 0x06004621 RID: 17953 RVA: 0x001273B3 File Offset: 0x001255B3
		// (remove) Token: 0x06004622 RID: 17954 RVA: 0x001273C1 File Offset: 0x001255C1
		public event ToolStripRenderEventHandler RenderImageMargin
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
		}

		// Token: 0x14000381 RID: 897
		// (add) Token: 0x06004623 RID: 17955 RVA: 0x001273CF File Offset: 0x001255CF
		// (remove) Token: 0x06004624 RID: 17956 RVA: 0x001273DD File Offset: 0x001255DD
		public event ToolStripItemRenderEventHandler RenderLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
		}

		// Token: 0x14000382 RID: 898
		// (add) Token: 0x06004625 RID: 17957 RVA: 0x001273EB File Offset: 0x001255EB
		// (remove) Token: 0x06004626 RID: 17958 RVA: 0x001273F9 File Offset: 0x001255F9
		public event ToolStripItemRenderEventHandler RenderMenuItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
		}

		// Token: 0x14000383 RID: 899
		// (add) Token: 0x06004627 RID: 17959 RVA: 0x00127407 File Offset: 0x00125607
		// (remove) Token: 0x06004628 RID: 17960 RVA: 0x00127415 File Offset: 0x00125615
		public event ToolStripItemRenderEventHandler RenderToolStripStatusLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
		}

		// Token: 0x14000384 RID: 900
		// (add) Token: 0x06004629 RID: 17961 RVA: 0x00127423 File Offset: 0x00125623
		// (remove) Token: 0x0600462A RID: 17962 RVA: 0x00127431 File Offset: 0x00125631
		public event ToolStripRenderEventHandler RenderStatusStripSizingGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
		}

		// Token: 0x14000385 RID: 901
		// (add) Token: 0x0600462B RID: 17963 RVA: 0x0012743F File Offset: 0x0012563F
		// (remove) Token: 0x0600462C RID: 17964 RVA: 0x0012744D File Offset: 0x0012564D
		public event ToolStripItemRenderEventHandler RenderSplitButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
		}

		// Token: 0x14000386 RID: 902
		// (add) Token: 0x0600462D RID: 17965 RVA: 0x0012745B File Offset: 0x0012565B
		// (remove) Token: 0x0600462E RID: 17966 RVA: 0x00127469 File Offset: 0x00125669
		public event ToolStripSeparatorRenderEventHandler RenderSeparator
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
		}

		// Token: 0x0600462F RID: 17967 RVA: 0x00127477 File Offset: 0x00125677
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void AddHandler(object key, Delegate value)
		{
			this.Events.AddHandler(key, value);
		}

		// Token: 0x06004630 RID: 17968 RVA: 0x00127486 File Offset: 0x00125686
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void RemoveHandler(object key, Delegate value)
		{
			this.Events.RemoveHandler(key, value);
		}

		// Token: 0x06004631 RID: 17969 RVA: 0x00127495 File Offset: 0x00125695
		public static Image CreateDisabledImage(Image normalImage)
		{
			return ToolStripRenderer.CreateDisabledImage(normalImage, null);
		}

		// Token: 0x06004632 RID: 17970 RVA: 0x001274A0 File Offset: 0x001256A0
		public void DrawArrow(ToolStripArrowRenderEventArgs e)
		{
			this.OnRenderArrow(e);
			ToolStripArrowRenderEventHandler toolStripArrowRenderEventHandler = this.Events[ToolStripRenderer.EventRenderArrow] as ToolStripArrowRenderEventHandler;
			if (toolStripArrowRenderEventHandler != null)
			{
				toolStripArrowRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004633 RID: 17971 RVA: 0x001274D8 File Offset: 0x001256D8
		public void DrawToolStripBackground(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBackground(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripBackground] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004634 RID: 17972 RVA: 0x00127510 File Offset: 0x00125710
		public void DrawGrip(ToolStripGripRenderEventArgs e)
		{
			this.OnRenderGrip(e);
			ToolStripGripRenderEventHandler toolStripGripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderGrip] as ToolStripGripRenderEventHandler;
			if (toolStripGripRenderEventHandler != null)
			{
				toolStripGripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004635 RID: 17973 RVA: 0x00127548 File Offset: 0x00125748
		public void DrawItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004636 RID: 17974 RVA: 0x00127580 File Offset: 0x00125780
		public void DrawImageMargin(ToolStripRenderEventArgs e)
		{
			this.OnRenderImageMargin(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderImageMargin] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004637 RID: 17975 RVA: 0x001275B8 File Offset: 0x001257B8
		public void DrawLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004638 RID: 17976 RVA: 0x001275F0 File Offset: 0x001257F0
		public void DrawButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004639 RID: 17977 RVA: 0x00127628 File Offset: 0x00125828
		public void DrawToolStripBorder(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBorder(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderBorder] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463A RID: 17978 RVA: 0x00127660 File Offset: 0x00125860
		public void DrawDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderDropDownButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderDropDownButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463B RID: 17979 RVA: 0x00127698 File Offset: 0x00125898
		public void DrawOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderOverflowButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderOverflowButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463C RID: 17980 RVA: 0x001276D0 File Offset: 0x001258D0
		public void DrawItemImage(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemImage(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemImage] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463D RID: 17981 RVA: 0x00127708 File Offset: 0x00125908
		public void DrawItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemCheck(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemCheck] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463E RID: 17982 RVA: 0x00127740 File Offset: 0x00125940
		public void DrawItemText(ToolStripItemTextRenderEventArgs e)
		{
			this.OnRenderItemText(e);
			ToolStripItemTextRenderEventHandler toolStripItemTextRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemText] as ToolStripItemTextRenderEventHandler;
			if (toolStripItemTextRenderEventHandler != null)
			{
				toolStripItemTextRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600463F RID: 17983 RVA: 0x00127778 File Offset: 0x00125978
		public void DrawMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderMenuItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderMenuItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004640 RID: 17984 RVA: 0x001277B0 File Offset: 0x001259B0
		public void DrawSplitButton(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderSplitButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSplitButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004641 RID: 17985 RVA: 0x001277E8 File Offset: 0x001259E8
		public void DrawToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderToolStripStatusLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripStatusLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004642 RID: 17986 RVA: 0x00127820 File Offset: 0x00125A20
		public void DrawStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			this.OnRenderStatusStripSizingGrip(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderStatusStripSizingGrip] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004643 RID: 17987 RVA: 0x00127858 File Offset: 0x00125A58
		public void DrawSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			this.OnRenderSeparator(e);
			ToolStripSeparatorRenderEventHandler toolStripSeparatorRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSeparator] as ToolStripSeparatorRenderEventHandler;
			if (toolStripSeparatorRenderEventHandler != null)
			{
				toolStripSeparatorRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004644 RID: 17988 RVA: 0x00127890 File Offset: 0x00125A90
		public void DrawToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			this.OnRenderToolStripPanelBackground(e);
			ToolStripPanelRenderEventHandler toolStripPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripPanelBackground] as ToolStripPanelRenderEventHandler;
			if (toolStripPanelRenderEventHandler != null)
			{
				toolStripPanelRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004645 RID: 17989 RVA: 0x001278C8 File Offset: 0x00125AC8
		public void DrawToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			this.OnRenderToolStripContentPanelBackground(e);
			ToolStripContentPanelRenderEventHandler toolStripContentPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripContentPanelBackground] as ToolStripContentPanelRenderEventHandler;
			if (toolStripContentPanelRenderEventHandler != null)
			{
				toolStripContentPanelRenderEventHandler(this, e);
			}
		}

		// Token: 0x06004646 RID: 17990 RVA: 0x00015ECC File Offset: 0x000140CC
		internal virtual Region GetTransparentRegion(ToolStrip toolStrip)
		{
			return null;
		}

		// Token: 0x06004647 RID: 17991 RVA: 0x000072B6 File Offset: 0x000054B6
		protected internal virtual void Initialize(ToolStrip toolStrip)
		{
		}

		// Token: 0x06004648 RID: 17992 RVA: 0x000072B6 File Offset: 0x000054B6
		protected internal virtual void InitializePanel(ToolStripPanel toolStripPanel)
		{
		}

		// Token: 0x06004649 RID: 17993 RVA: 0x000072B6 File Offset: 0x000054B6
		protected internal virtual void InitializeContentPanel(ToolStripContentPanel contentPanel)
		{
		}

		// Token: 0x0600464A RID: 17994 RVA: 0x000072B6 File Offset: 0x000054B6
		protected internal virtual void InitializeItem(ToolStripItem item)
		{
		}

		// Token: 0x0600464B RID: 17995 RVA: 0x00127900 File Offset: 0x00125B00
		protected static void ScaleArrowOffsetsIfNeeded()
		{
			if (ToolStripRenderer.isScalingInitialized)
			{
				return;
			}
			if (DpiHelper.IsScalingRequired)
			{
				ToolStripRenderer.Offset2X = DpiHelper.LogicalToDeviceUnitsX(ToolStripRenderer.OFFSET_2PIXELS);
				ToolStripRenderer.Offset2Y = DpiHelper.LogicalToDeviceUnitsY(ToolStripRenderer.OFFSET_2PIXELS);
				ToolStripRenderer.offset4X = DpiHelper.LogicalToDeviceUnitsX(ToolStripRenderer.OFFSET_4PIXELS);
				ToolStripRenderer.offset4Y = DpiHelper.LogicalToDeviceUnitsY(ToolStripRenderer.OFFSET_4PIXELS);
			}
			ToolStripRenderer.isScalingInitialized = true;
		}

		// Token: 0x0600464C RID: 17996 RVA: 0x00127960 File Offset: 0x00125B60
		protected static void ScaleArrowOffsetsIfNeeded(int dpi)
		{
			ToolStripRenderer.Offset2X = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_2PIXELS, dpi);
			ToolStripRenderer.Offset2Y = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_2PIXELS, dpi);
			ToolStripRenderer.offset4X = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_4PIXELS, dpi);
			ToolStripRenderer.offset4Y = DpiHelper.LogicalToDeviceUnits(ToolStripRenderer.OFFSET_4PIXELS, dpi);
		}

		// Token: 0x0600464D RID: 17997 RVA: 0x001279B0 File Offset: 0x00125BB0
		protected virtual void OnRenderArrow(ToolStripArrowRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderArrow(e);
				return;
			}
			Graphics graphics = e.Graphics;
			Rectangle arrowRectangle = e.ArrowRectangle;
			using (Brush brush = new SolidBrush(e.ArrowColor))
			{
				Point point = new Point(arrowRectangle.Left + arrowRectangle.Width / 2, arrowRectangle.Top + arrowRectangle.Height / 2);
				ToolStripItem item = e.Item;
				int? num = (item != null) ? new int?(item.DeviceDpi) : null;
				int num2 = this.previousDeviceDpi;
				if (!(num.GetValueOrDefault() == num2 & num != null) && DpiHelper.EnableToolStripPerMonitorV2HighDpiImprovements)
				{
					this.previousDeviceDpi = e.Item.DeviceDpi;
					ToolStripRenderer.ScaleArrowOffsetsIfNeeded(e.Item.DeviceDpi);
				}
				else
				{
					ToolStripRenderer.ScaleArrowOffsetsIfNeeded();
				}
				int num3 = DpiHelper.EnableToolStripHighDpiImprovements ? (ToolStripRenderer.offset4X - ToolStripRenderer.Offset2X) : ToolStripRenderer.Offset2X;
				ArrowDirection direction = e.Direction;
				Point[] points;
				if (direction <= ArrowDirection.Up)
				{
					if (direction == ArrowDirection.Left)
					{
						points = new Point[]
						{
							new Point(point.X + ToolStripRenderer.Offset2X, point.Y - ToolStripRenderer.offset4Y),
							new Point(point.X + ToolStripRenderer.Offset2X, point.Y + ToolStripRenderer.offset4Y),
							new Point(point.X - num3, point.Y)
						};
						goto IL_2E3;
					}
					if (direction == ArrowDirection.Up)
					{
						points = new Point[]
						{
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y + 1),
							new Point(point.X + ToolStripRenderer.Offset2X + 1, point.Y + 1),
							new Point(point.X, point.Y - ToolStripRenderer.Offset2Y)
						};
						goto IL_2E3;
					}
				}
				else
				{
					if (direction == ArrowDirection.Right)
					{
						points = new Point[]
						{
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y - ToolStripRenderer.offset4Y),
							new Point(point.X - ToolStripRenderer.Offset2X, point.Y + ToolStripRenderer.offset4Y),
							new Point(point.X + num3, point.Y)
						};
						goto IL_2E3;
					}
					if (direction != ArrowDirection.Down)
					{
					}
				}
				points = new Point[]
				{
					new Point(point.X - ToolStripRenderer.Offset2X, point.Y - 1),
					new Point(point.X + ToolStripRenderer.Offset2X + 1, point.Y - 1),
					new Point(point.X, point.Y + ToolStripRenderer.Offset2Y)
				};
				IL_2E3:
				graphics.FillPolygon(brush, points);
			}
		}

		// Token: 0x0600464E RID: 17998 RVA: 0x00127CD4 File Offset: 0x00125ED4
		protected virtual void OnRenderToolStripBackground(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBackground(e);
				return;
			}
		}

		// Token: 0x0600464F RID: 17999 RVA: 0x00127CEB File Offset: 0x00125EEB
		protected virtual void OnRenderToolStripBorder(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBorder(e);
				return;
			}
		}

		// Token: 0x06004650 RID: 18000 RVA: 0x00127D02 File Offset: 0x00125F02
		protected virtual void OnRenderGrip(ToolStripGripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderGrip(e);
				return;
			}
		}

		// Token: 0x06004651 RID: 18001 RVA: 0x00127D19 File Offset: 0x00125F19
		protected virtual void OnRenderItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemBackground(e);
				return;
			}
		}

		// Token: 0x06004652 RID: 18002 RVA: 0x00127D30 File Offset: 0x00125F30
		protected virtual void OnRenderImageMargin(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderImageMargin(e);
				return;
			}
		}

		// Token: 0x06004653 RID: 18003 RVA: 0x00127D47 File Offset: 0x00125F47
		protected virtual void OnRenderButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderButtonBackground(e);
				return;
			}
		}

		// Token: 0x06004654 RID: 18004 RVA: 0x00127D5E File Offset: 0x00125F5E
		protected virtual void OnRenderDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderDropDownButtonBackground(e);
				return;
			}
		}

		// Token: 0x06004655 RID: 18005 RVA: 0x00127D75 File Offset: 0x00125F75
		protected virtual void OnRenderOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderOverflowButtonBackground(e);
				return;
			}
		}

		// Token: 0x06004656 RID: 18006 RVA: 0x00127D8C File Offset: 0x00125F8C
		protected virtual void OnRenderItemImage(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemImage(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				bool flag = false;
				if (e.ShiftOnPress && e.Item.Pressed)
				{
					imageRectangle.X++;
				}
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image, e.ImageAttributes);
					flag = true;
				}
				if (e.Item.ImageScaling == ToolStripItemImageScaling.None)
				{
					e.Graphics.DrawImage(image, imageRectangle, new Rectangle(Point.Empty, imageRectangle.Size), GraphicsUnit.Pixel);
				}
				else
				{
					e.Graphics.DrawImage(image, imageRectangle);
				}
				if (flag)
				{
					image.Dispose();
				}
			}
		}

		// Token: 0x06004657 RID: 18007 RVA: 0x00127E58 File Offset: 0x00126058
		protected virtual void OnRenderItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemCheck(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image, e.ImageAttributes);
				}
				e.Graphics.DrawImage(image, imageRectangle, 0, 0, imageRectangle.Width, imageRectangle.Height, GraphicsUnit.Pixel, e.ImageAttributes);
			}
		}

		// Token: 0x06004658 RID: 18008 RVA: 0x00127ED8 File Offset: 0x001260D8
		protected virtual void OnRenderItemText(ToolStripItemTextRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemText(e);
				return;
			}
			ToolStripItem item = e.Item;
			Graphics graphics = e.Graphics;
			Color color = e.TextColor;
			Font textFont = e.TextFont;
			string text = e.Text;
			Rectangle textRectangle = e.TextRectangle;
			TextFormatFlags textFormat = e.TextFormat;
			color = (item.Enabled ? color : SystemColors.GrayText);
			if (e.TextDirection != ToolStripTextDirection.Horizontal && textRectangle.Width > 0 && textRectangle.Height > 0)
			{
				Size size = LayoutUtils.FlipSize(textRectangle.Size);
				using (Bitmap bitmap = new Bitmap(size.Width, size.Height, PixelFormat.Format32bppPArgb))
				{
					using (Graphics graphics2 = Graphics.FromImage(bitmap))
					{
						graphics2.TextRenderingHint = TextRenderingHint.AntiAlias;
						TextRenderer.DrawText(graphics2, text, textFont, new Rectangle(Point.Empty, size), color, textFormat);
						bitmap.RotateFlip((e.TextDirection == ToolStripTextDirection.Vertical90) ? RotateFlipType.Rotate90FlipNone : RotateFlipType.Rotate270FlipNone);
						graphics.DrawImage(bitmap, textRectangle);
						return;
					}
				}
			}
			TextRenderer.DrawText(graphics, text, textFont, textRectangle, color, textFormat);
		}

		// Token: 0x06004659 RID: 18009 RVA: 0x0012801C File Offset: 0x0012621C
		protected virtual void OnRenderLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderLabelBackground(e);
				return;
			}
		}

		// Token: 0x0600465A RID: 18010 RVA: 0x00128033 File Offset: 0x00126233
		protected virtual void OnRenderMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderMenuItemBackground(e);
				return;
			}
		}

		// Token: 0x0600465B RID: 18011 RVA: 0x0012804A File Offset: 0x0012624A
		protected virtual void OnRenderSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSeparator(e);
				return;
			}
		}

		// Token: 0x0600465C RID: 18012 RVA: 0x00128061 File Offset: 0x00126261
		protected virtual void OnRenderToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripPanelBackground(e);
				return;
			}
		}

		// Token: 0x0600465D RID: 18013 RVA: 0x00128078 File Offset: 0x00126278
		protected virtual void OnRenderToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripContentPanelBackground(e);
				return;
			}
		}

		// Token: 0x0600465E RID: 18014 RVA: 0x0012808F File Offset: 0x0012628F
		protected virtual void OnRenderToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripStatusLabelBackground(e);
				return;
			}
		}

		// Token: 0x0600465F RID: 18015 RVA: 0x001280A8 File Offset: 0x001262A8
		protected virtual void OnRenderStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderStatusStripSizingGrip(e);
				return;
			}
			Graphics graphics = e.Graphics;
			StatusStrip statusStrip = e.ToolStrip as StatusStrip;
			if (statusStrip != null)
			{
				Rectangle sizeGripBounds = statusStrip.SizeGripBounds;
				if (!LayoutUtils.IsZeroWidthOrHeight(sizeGripBounds))
				{
					Rectangle[] array = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					Rectangle[] array2 = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					for (int i = 0; i < ToolStripRenderer.baseSizeGripRectangles.Length; i++)
					{
						Rectangle rectangle = ToolStripRenderer.baseSizeGripRectangles[i];
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.X = sizeGripBounds.Width - rectangle.X - rectangle.Width;
						}
						rectangle.Offset(sizeGripBounds.X, sizeGripBounds.Bottom - 12);
						array[i] = rectangle;
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.Offset(1, -1);
						}
						else
						{
							rectangle.Offset(-1, -1);
						}
						array2[i] = rectangle;
					}
					graphics.FillRectangles(SystemBrushes.ButtonHighlight, array);
					graphics.FillRectangles(SystemBrushes.ButtonShadow, array2);
				}
			}
		}

		// Token: 0x06004660 RID: 18016 RVA: 0x001281C4 File Offset: 0x001263C4
		protected virtual void OnRenderSplitButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSplitButtonBackground(e);
				return;
			}
		}

		// Token: 0x06004661 RID: 18017 RVA: 0x001281DB File Offset: 0x001263DB
		internal bool ShouldPaintBackground(Control control)
		{
			return control.RawBackColor == Color.Empty && control.BackgroundImage == null;
		}

		// Token: 0x06004662 RID: 18018 RVA: 0x001281FC File Offset: 0x001263FC
		private static Image CreateDisabledImage(Image normalImage, ImageAttributes imgAttrib)
		{
			if (imgAttrib == null)
			{
				imgAttrib = new ImageAttributes();
			}
			imgAttrib.ClearColorKey();
			imgAttrib.SetColorMatrix(ToolStripRenderer.DisabledImageColorMatrix);
			Size size = normalImage.Size;
			Bitmap bitmap = new Bitmap(size.Width, size.Height);
			using (Graphics graphics = Graphics.FromImage(bitmap))
			{
				graphics.DrawImage(normalImage, new Rectangle(0, 0, size.Width, size.Height), 0, 0, size.Width, size.Height, GraphicsUnit.Pixel, imgAttrib);
			}
			return bitmap;
		}

		// Token: 0x04002684 RID: 9860
		private static readonly object EventRenderSplitButtonBackground = new object();

		// Token: 0x04002685 RID: 9861
		private static readonly object EventRenderItemBackground = new object();

		// Token: 0x04002686 RID: 9862
		private static readonly object EventRenderItemImage = new object();

		// Token: 0x04002687 RID: 9863
		private static readonly object EventRenderItemText = new object();

		// Token: 0x04002688 RID: 9864
		private static readonly object EventRenderToolStripBackground = new object();

		// Token: 0x04002689 RID: 9865
		private static readonly object EventRenderGrip = new object();

		// Token: 0x0400268A RID: 9866
		private static readonly object EventRenderButtonBackground = new object();

		// Token: 0x0400268B RID: 9867
		private static readonly object EventRenderLabelBackground = new object();

		// Token: 0x0400268C RID: 9868
		private static readonly object EventRenderMenuItemBackground = new object();

		// Token: 0x0400268D RID: 9869
		private static readonly object EventRenderDropDownButtonBackground = new object();

		// Token: 0x0400268E RID: 9870
		private static readonly object EventRenderOverflowButtonBackground = new object();

		// Token: 0x0400268F RID: 9871
		private static readonly object EventRenderImageMargin = new object();

		// Token: 0x04002690 RID: 9872
		private static readonly object EventRenderBorder = new object();

		// Token: 0x04002691 RID: 9873
		private static readonly object EventRenderArrow = new object();

		// Token: 0x04002692 RID: 9874
		private static readonly object EventRenderStatusStripPanelBackground = new object();

		// Token: 0x04002693 RID: 9875
		private static readonly object EventRenderToolStripStatusLabelBackground = new object();

		// Token: 0x04002694 RID: 9876
		private static readonly object EventRenderSeparator = new object();

		// Token: 0x04002695 RID: 9877
		private static readonly object EventRenderItemCheck = new object();

		// Token: 0x04002696 RID: 9878
		private static readonly object EventRenderToolStripPanelBackground = new object();

		// Token: 0x04002697 RID: 9879
		private static readonly object EventRenderToolStripContentPanelBackground = new object();

		// Token: 0x04002698 RID: 9880
		private static readonly object EventRenderStatusStripSizingGrip = new object();

		// Token: 0x04002699 RID: 9881
		private static ColorMatrix disabledImageColorMatrix;

		// Token: 0x0400269A RID: 9882
		private EventHandlerList events;

		// Token: 0x0400269B RID: 9883
		private bool isAutoGenerated;

		// Token: 0x0400269C RID: 9884
		private static bool isScalingInitialized = false;

		// Token: 0x0400269D RID: 9885
		internal int previousDeviceDpi = DpiHelper.DeviceDpi;

		// Token: 0x0400269E RID: 9886
		private static int OFFSET_2PIXELS = 2;

		// Token: 0x0400269F RID: 9887
		private static int OFFSET_4PIXELS = 4;

		// Token: 0x040026A0 RID: 9888
		protected static int Offset2X = ToolStripRenderer.OFFSET_2PIXELS;

		// Token: 0x040026A1 RID: 9889
		protected static int Offset2Y = ToolStripRenderer.OFFSET_2PIXELS;

		// Token: 0x040026A2 RID: 9890
		private static int offset4X = ToolStripRenderer.OFFSET_4PIXELS;

		// Token: 0x040026A3 RID: 9891
		private static int offset4Y = ToolStripRenderer.OFFSET_4PIXELS;

		// Token: 0x040026A4 RID: 9892
		private static Rectangle[] baseSizeGripRectangles = new Rectangle[]
		{
			new Rectangle(8, 0, 2, 2),
			new Rectangle(8, 4, 2, 2),
			new Rectangle(8, 8, 2, 2),
			new Rectangle(4, 4, 2, 2),
			new Rectangle(4, 8, 2, 2),
			new Rectangle(0, 8, 2, 2)
		};
	}
}
