using System;

namespace TechnoPro.Common.DAO.Impl.DynamicForms
{
	// Token: 0x020000E2 RID: 226
	public class QueryStorageDynamicField
	{
		// Token: 0x040003B7 RID: 951
		internal const string QS_CIDS_ON_FORMS = "SELECT screennum,controlid FROM dynamicscreencontrols WHERE screennum IN (SELECT orderid AS screennum FROM splitorderids(@screennums,',')) ORDER BY screennum,ordernum";

		// Token: 0x040003B8 RID: 952
		internal const string QS_ALL_LOOKUP_LISTS = "SELECT LookupGroupID,description,SortBy,childlist FROM LookupGroups WHERE isvisible=1 ORDER BY SortBy,description";

		// Token: 0x040003B9 RID: 953
		internal const string QS_LOOKUP_LIST_ITEM_EXISTS_IN_DATA = "DECLARE @dataexists bit\r\n\r\nIF EXISTS(SELECT TOP 1 dataid FROM perstudentdata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid))\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM perappdata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid))\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM accommodationdata WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM perinstructordata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM perinventorydata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM perinvigilatordata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM pjadata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM pjcdata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE IF EXISTS(SELECT TOP 1 dataid FROM pmdata2 WHERE (controlcode=3 AND setting3=0 AND valint=@lookuplistid) OR (controlcode=14 AND setting4=0 AND valint=@lookuplistid) )\r\n\tSET @dataexists=1\r\nELSE\r\n\tSET @dataexists=0\r\n\t\r\nSELECT @dataexists AS dataexists";

		// Token: 0x040003BA RID: 954
		internal const string QS_FIRST_FIELD_ON_FIRST_FORM_ON_APPTYPE = "DECLARE @screennums varchar(max)\r\nSET @screennums=COALESCE((SELECT TOP 1 perAppScreenNumsForTabs FROM AppointmentTypes WHERE AppTypeID=@apptypeid),'')\r\n\r\nDECLARE @screennum int\r\nSET @screennum=COALESCE((SELECT TOP 1 orderid AS screennum FROM splitorderids(@screennums,',')),0)\r\n\r\nSELECT    dc.controlid,0 AS ordernum,0 AS screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,'' AS description,0 AS typecode,dc.uniqueid,dc.specialcontroltype\r\nFROM dynamicscreencontrols dsc LEFT JOIN dynamiccontrols dc ON dc.controlid=dsc.controlid \r\nWHERE dsc.screennum=@screennum AND dc.controlcode=@controlcode\r\nORDER BY dsc.ordernum";

		// Token: 0x040003BB RID: 955
		internal const string QS_EXTENDED_ACCOMMODATION_INFO_BY_CIDS = "SELECT    acc.controlid,acc.accommodationid,acc.longdescription,acc.shortcode,acc.showonletter AS showonletter1,acc.showonemail,\r\n            acc.extratime,acc.isalone,acc.needscomputer,acc.needsreaderscribe,acc.availableinallrooms,acc.groupid,acc.isgroup,acc.tapedexams,\r\n            acc.other,acc.enlarged,acc.showonreport\r\nFROM    accommodations acc \r\nWHERE   acc.controlid IN (SELECT orderid AS controlid FROM splitorderids(@cids,','))";

		// Token: 0x040003BC RID: 956
		internal const string QS_FORMS_WITH_GROUPS_AND_FIELDS = "SELECT    s.screennum,s.typecode,s.description,s.shorttext,s.bottomless,s.columnwidth,\r\n            s.longdescription,s.showasbutton,s.iconindex,s.largeiconindex,s.isactive,\r\n            dsc.controlid,dsc.ordernum,\r\n            dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4,\r\n            dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers,\r\n            dc.controlname,COALESCE(dsc.controlgroup,dc.controlgroup) AS controlgroup,dc.helptext,dc.helptextdisplaymethod,\r\n            dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline,dc.uniqueid,dc.specialcontroltype\r\nFROM        screens s LEFT JOIN dynamicscreencontrols dsc ON dsc.screennum=s.screennum\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=dsc.controlid\r\nWHERE       (@excludescreennums='' OR NOT s.screennum IN (SELECT orderid AS screennum FROM splitorderids(@excludescreennums,',')))\r\n            AND\r\n            (@excludenondatafields=0 OR NOT dc.controlcode IN (SELECT controlcode FROM DynamicScreenNonDataControls))\r\n            AND NOT dc.controlid IS NULL\r\n            AND NOT dsc.screennum IS NULL\r\nORDER BY s.longdescription,s.description,dsc.ordernum";

		// Token: 0x040003BD RID: 957
		internal const string QS_DYNAMIC_LIST_ITEMS = "SELECT ll.lookupgroupid,lg.description,lg.sortby,lg.childlist,lg.isvisible\r\n            ,ll.lookuplistid,ll.lookuptext,ll.ordernum,ll.lookupvalue,ll.children\r\nFROM        lookuplists ll LEFT JOIN lookupgroups lg ON lg.lookupgroupid=ll.lookupgroupid\r\nWHERE       ll.lookupgroupid=@lookupgroupid AND ll.visible=1\r\nORDER BY    ll.ordernum,ll.lookuptext";

		// Token: 0x040003BE RID: 958
		internal const string SQ_FIELDS_BY_CIDS = "SELECT    dc.controlid,0 AS screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.[enabled],dc.[readonly],dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,'' AS [description],0 AS typecode,\r\n\t\t\tMAX(dsc.ordernum) AS ordernum,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamiccontrols dc LEFT JOIN dynamicscreencontrols dsc ON dsc.controlid=dc.controlid\r\nWHERE       dc.controlid IN (SELECT orderid AS controlid FROM splitorderids(@cids,','))\r\nGROUP BY\tdc.controlid,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.[enabled],dc.[readonly],dc.hidecaption,dc.fontsize,dc.dontwraptonextline,dc.uniqueid,dc.specialcontroltype\r\nORDER BY    dc.controlcaption";

		// Token: 0x040003BF RID: 959
		internal const string QS_FIELD_BY_NAME = "SELECT    dc.controlid,0 AS ordernum,0 AS screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,'' AS description,0 AS typecode,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamiccontrols dc \r\nWHERE       dc.controlname=@name\r\nORDER BY    dc.controlcaption";

		// Token: 0x040003C0 RID: 960
		internal const string QS_FIELD_BY_UNIQUE_ID = "SELECT    dc.controlid,0 AS ordernum,0 AS screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,'' AS description,0 AS typecode,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamiccontrols dc \r\nWHERE       dc.uniqueid=@id\r\nORDER BY    dc.controlcaption";

		// Token: 0x040003C1 RID: 961
		internal const string QS_FIELD_BY_CAPTION = "SELECT    dc.controlid,0 AS ordernum,0 AS screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,dc.controlgroup,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,'' AS description,0 AS typecode,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamiccontrols dc \r\nWHERE       dc.controlcaption=@caption\r\n            AND dc.enabled=1\r\n            AND (\r\n                @screennum=0 OR \r\n                dc.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum=@screennum AND isactive=1)\r\n            )\r\nORDER BY dc.controlid";

		// Token: 0x040003C2 RID: 962
		internal const string SQ_FIELDS_BY_FORM = "SELECT    dsc.controlid,dsc.ordernum,dsc.screennum\r\n            ,dc.controlcode,dc.controlcaption,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.mask,dc.actionhandlers\r\n            ,dc.controlname,COALESCE(dsc.controlgroup,dc.controlgroup) AS controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod\r\n            ,dc.enforce,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,s.description,s.typecode,dc.uniqueid,dc.specialcontroltype\r\nFROM        screens s LEFT JOIN dynamicscreencontrols dsc ON dsc.screennum=s.screennum\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=dsc.controlid\r\nWHERE       s.screennum=@screennum\r\nORDER BY    dsc.ordernum,dc.controlcaption";

		// Token: 0x040003C3 RID: 963
		internal const string SQ_FIELDS_BY_CONTROLIDS = "SELECT    dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamiccontrols dc\r\nWHERE       dc.controlid IN (SELECT orderid AS controlid FROM splitorderids(@cids,','))";

		// Token: 0x040003C4 RID: 964
		internal const string SQ_FIRST_FIELD_BY_CONTROLCODE_AND_SCREENNUM = "SELECT    TOP 1 dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname\r\n            ,COALESCE(dsc.controlgroup,dc.controlgroup) AS controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline,dc.uniqueid,dc.specialcontroltype\r\nFROM        dynamicscreencontrols dsc LEFT JOIN dynamiccontrols dc ON dc.controlid=dsc.controlid\r\nWHERE       dsc.screennum=@screennum AND dcs.isactive=1\r\n            AND dc.controlcode=@controlcode\r\nORDER BY dsc.ordernum";

		// Token: 0x040003C5 RID: 965
		internal const string QU_FIELD_NAME = "UPDATE dynamiccontrols SET controlname=@name WHERE controlid=@cid";

		// Token: 0x040003C6 RID: 966
		internal const string QI_FIELD_ON_FORM = "SET @dynamicscreencontrolid=(SELECT TOP 1 dynamicscreencontrolid FROM dynamicscreencontrols WHERE screennum=@screennum AND controlid=@controlid);\r\nIF NOT ( NOT @dynamicscreencontrolid IS NULL AND @dynamicscreencontrolid > 0 )\r\nBEGIN\r\n    INSERT INTO dynamicscreencontrols (screennum,controlid,ordernum,isactive) VALUES (@screennum,@controlid,@ordernum,1);\r\n    SET @dynamicscreencontrolid=(SELECT TOP 1 CAST(SCOPE_IDENTITY() AS int))\r\nEND";

		// Token: 0x040003C7 RID: 967
		internal const string QI_FIELD = "INSERT INTO dynamiccontrols (controlcode,controlcaption,setting1,setting2,setting3,setting4,\r\ndefaultvalue,controlname,controlgroup,helptext,helptextdisplaymethod,mask,enforce,actionhandlers,\r\nsetting4string,enabled,readonly,hidecaption,fontsize,dontwraptonextline,defaultvaluestring,uniqueid,specialcontroltype)\r\nVALUES (@controlcode,@controlcaption,@setting1,@setting2,@setting3,@setting4,\r\n@defaultvalue,@controlname,@controlgroup,@helptext,@helptextdisplaymethod,@mask,@enforce\r\n,@actionhandlers,@setting4string,@enabled,@readonly,@hidecaption,@fontsize\r\n,@dontwraptonextline,@defaultvaluestring,@uniqueid,@specialcontroltype);\r\nSELECT TOP 1 CAST(SCOPE_IDENTITY() AS int) AS controlid";

		// Token: 0x040003C8 RID: 968
		internal const string QI_CREATE_LIST_ITEM = "INSERT INTO lookuplists (lookupgroupid,lookuptext,ordernum,visible) VALUES (@lookupgroupid,@lookuptext,@ordernum,1)";

		// Token: 0x040003C9 RID: 969
		internal const string QI_CREATE_LIST_GROUP = "INSERT INTO lookupgroups (description,sortby,isvisible) VALUES (@description,@sortby,@isvisible)\r\nSET @lookupgroupid=(SELECT TOP 1 CAST(SCOPE_IDENTITY() AS INT))";
	}
}
