using System;
using System.Collections;
using System.ComponentModel;
using System.Data.Common;
using System.Globalization;

namespace System.Data
{
	// Token: 0x02000062 RID: 98
	[DefaultEvent("CollectionChanged")]
	[Editor("Microsoft.VSDesigner.Data.Design.ConstraintsCollectionEditor, Microsoft.VSDesigner, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Drawing.Design.UITypeEditor, System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
	public sealed class ConstraintCollection : InternalDataCollectionBase
	{
		// Token: 0x06000478 RID: 1144 RVA: 0x001E7DC8 File Offset: 0x001E71C8
		internal ConstraintCollection(DataTable table)
		{
			this.table = table;
		}

		// Token: 0x17000083 RID: 131
		// (get) Token: 0x06000479 RID: 1145 RVA: 0x001E7DF8 File Offset: 0x001E71F8
		protected override ArrayList List
		{
			get
			{
				return this.list;
			}
		}

		// Token: 0x17000084 RID: 132
		public Constraint this[int index]
		{
			get
			{
				if (index >= 0 && index < this.List.Count)
				{
					return (Constraint)this.List[index];
				}
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
		}

		// Token: 0x17000085 RID: 133
		// (get) Token: 0x0600047B RID: 1147 RVA: 0x001E7E58 File Offset: 0x001E7258
		internal DataTable Table
		{
			get
			{
				return this.table;
			}
		}

		// Token: 0x17000086 RID: 134
		public Constraint this[string name]
		{
			get
			{
				int num = this.InternalIndexOf(name);
				if (num == -2)
				{
					throw ExceptionBuilder.CaseInsensitiveNameConflict(name);
				}
				if (num >= 0)
				{
					return (Constraint)this.List[num];
				}
				return null;
			}
		}

		// Token: 0x0600047D RID: 1149 RVA: 0x001E7EB8 File Offset: 0x001E72B8
		public void Add(Constraint constraint)
		{
			this.Add(constraint, true);
		}

		// Token: 0x0600047E RID: 1150 RVA: 0x001E7ED8 File Offset: 0x001E72D8
		internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.FindConstraint(constraint) != null)
			{
				throw ExceptionBuilder.DuplicateConstraint(this.FindConstraint(constraint).ConstraintName);
			}
			if (1 < this.table.NestedParentRelations.Length && !this.AutoGenerated(constraint))
			{
				throw ExceptionBuilder.CantAddConstraintToMultipleNestedTable(this.table.TableName);
			}
			if (constraint is UniqueConstraint)
			{
				if (((UniqueConstraint)constraint).bPrimaryKey && this.Table.primaryKey != null)
				{
					throw ExceptionBuilder.AddPrimaryKeyConstraint();
				}
				this.AddUniqueConstraint((UniqueConstraint)constraint);
			}
			else if (constraint is ForeignKeyConstraint)
			{
				ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)constraint;
				if (addUniqueWhenAddingForeign && foreignKeyConstraint.RelatedTable.Constraints.FindKeyConstraint(foreignKeyConstraint.RelatedColumnsReference) == null)
				{
					if (constraint.ConstraintName.Length == 0)
					{
						constraint.ConstraintName = this.AssignName();
					}
					else
					{
						this.RegisterName(constraint.ConstraintName);
					}
					UniqueConstraint constraint2 = new UniqueConstraint(foreignKeyConstraint.RelatedColumnsReference);
					foreignKeyConstraint.RelatedTable.Constraints.Add(constraint2);
				}
				this.AddForeignKeyConstraint((ForeignKeyConstraint)constraint);
			}
			this.BaseAdd(constraint);
			this.ArrayAdd(constraint);
			this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, constraint));
			if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).bPrimaryKey)
			{
				this.Table.PrimaryKey = ((UniqueConstraint)constraint).ColumnsReference;
			}
		}

		// Token: 0x0600047F RID: 1151 RVA: 0x001E8038 File Offset: 0x001E7438
		public Constraint Add(string name, DataColumn[] columns, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, columns);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = columns;
			}
			return uniqueConstraint;
		}

		// Token: 0x06000480 RID: 1152 RVA: 0x001E8068 File Offset: 0x001E7468
		public Constraint Add(string name, DataColumn column, bool primaryKey)
		{
			UniqueConstraint uniqueConstraint = new UniqueConstraint(name, column);
			this.Add(uniqueConstraint);
			if (primaryKey)
			{
				this.Table.PrimaryKey = uniqueConstraint.ColumnsReference;
			}
			return uniqueConstraint;
		}

		// Token: 0x06000481 RID: 1153 RVA: 0x001E80A8 File Offset: 0x001E74A8
		public Constraint Add(string name, DataColumn primaryKeyColumn, DataColumn foreignKeyColumn)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumn, foreignKeyColumn);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		// Token: 0x06000482 RID: 1154 RVA: 0x001E80C8 File Offset: 0x001E74C8
		public Constraint Add(string name, DataColumn[] primaryKeyColumns, DataColumn[] foreignKeyColumns)
		{
			ForeignKeyConstraint foreignKeyConstraint = new ForeignKeyConstraint(name, primaryKeyColumns, foreignKeyColumns);
			this.Add(foreignKeyConstraint);
			return foreignKeyConstraint;
		}

		// Token: 0x06000483 RID: 1155 RVA: 0x001E80E8 File Offset: 0x001E74E8
		public void AddRange(Constraint[] constraints)
		{
			if (this.table.fInitInProgress)
			{
				this.delayLoadingConstraints = constraints;
				this.fLoadForeignKeyConstraintsOnly = false;
				return;
			}
			if (constraints != null)
			{
				foreach (Constraint constraint in constraints)
				{
					if (constraint != null)
					{
						this.Add(constraint);
					}
				}
			}
		}

		// Token: 0x06000484 RID: 1156 RVA: 0x001E8138 File Offset: 0x001E7538
		private void AddUniqueConstraint(UniqueConstraint constraint)
		{
			DataColumn[] columnsReference = constraint.ColumnsReference;
			for (int i = 0; i < columnsReference.Length; i++)
			{
				if (columnsReference[i].Table != this.table)
				{
					throw ExceptionBuilder.ConstraintForeignTable();
				}
			}
			constraint.ConstraintIndexInitialize();
			if (!constraint.CanEnableConstraint())
			{
				constraint.ConstraintIndexClear();
				throw ExceptionBuilder.UniqueConstraintViolation();
			}
		}

		// Token: 0x06000485 RID: 1157 RVA: 0x001E8198 File Offset: 0x001E7598
		private void AddForeignKeyConstraint(ForeignKeyConstraint constraint)
		{
			if (!constraint.CanEnableConstraint())
			{
				throw ExceptionBuilder.ConstraintParentValues();
			}
			constraint.CheckCanAddToCollection(this);
		}

		// Token: 0x06000486 RID: 1158 RVA: 0x001E81C8 File Offset: 0x001E75C8
		private bool AutoGenerated(Constraint constraint)
		{
			ForeignKeyConstraint foreignKeyConstraint = constraint as ForeignKeyConstraint;
			if (foreignKeyConstraint != null)
			{
				return XmlTreeGen.AutoGenerated(foreignKeyConstraint, false);
			}
			UniqueConstraint unique = (UniqueConstraint)constraint;
			return XmlTreeGen.AutoGenerated(unique);
		}

		// Token: 0x14000002 RID: 2
		// (add) Token: 0x06000487 RID: 1159 RVA: 0x001E81F8 File Offset: 0x001E75F8
		// (remove) Token: 0x06000488 RID: 1160 RVA: 0x001E8228 File Offset: 0x001E7628
		public event CollectionChangeEventHandler CollectionChanged
		{
			add
			{
				this.onCollectionChanged = (CollectionChangeEventHandler)Delegate.Combine(this.onCollectionChanged, value);
			}
			remove
			{
				this.onCollectionChanged = (CollectionChangeEventHandler)Delegate.Remove(this.onCollectionChanged, value);
			}
		}

		// Token: 0x06000489 RID: 1161 RVA: 0x001E8258 File Offset: 0x001E7658
		private void ArrayAdd(Constraint constraint)
		{
			this.List.Add(constraint);
		}

		// Token: 0x0600048A RID: 1162 RVA: 0x001E8278 File Offset: 0x001E7678
		private void ArrayRemove(Constraint constraint)
		{
			this.List.Remove(constraint);
		}

		// Token: 0x0600048B RID: 1163 RVA: 0x001E8298 File Offset: 0x001E7698
		internal string AssignName()
		{
			string result = this.MakeName(this.defaultNameIndex);
			this.defaultNameIndex++;
			return result;
		}

		// Token: 0x0600048C RID: 1164 RVA: 0x001E82C8 File Offset: 0x001E76C8
		private void BaseAdd(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.ConstraintName.Length == 0)
			{
				constraint.ConstraintName = this.AssignName();
			}
			else
			{
				this.RegisterName(constraint.ConstraintName);
			}
			constraint.InCollection = true;
		}

		// Token: 0x0600048D RID: 1165 RVA: 0x001E8318 File Offset: 0x001E7718
		private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength)
		{
			int num = 0;
			for (int i = 0; i < oldLength; i++)
			{
				bool flag = false;
				for (int j = num; j < newLength; j++)
				{
					if (oldArray[i] == newArray[j])
					{
						if (num == j)
						{
							num++;
						}
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					this.BaseRemove(oldArray[i]);
					this.List.Remove(oldArray[i]);
				}
			}
			for (int k = 0; k < newLength; k++)
			{
				if (!newArray[k].InCollection)
				{
					this.BaseAdd(newArray[k]);
				}
				this.List.Add(newArray[k]);
			}
		}

		// Token: 0x0600048E RID: 1166 RVA: 0x001E83A8 File Offset: 0x001E77A8
		private void BaseRemove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (constraint.Table != this.table)
			{
				throw ExceptionBuilder.ConstraintRemoveFailed();
			}
			this.UnregisterName(constraint.ConstraintName);
			constraint.InCollection = false;
			if (constraint is UniqueConstraint)
			{
				for (int i = 0; i < this.Table.ChildRelations.Count; i++)
				{
					DataRelation dataRelation = this.Table.ChildRelations[i];
					if (dataRelation.ParentKeyConstraint == constraint)
					{
						dataRelation.SetParentKeyConstraint(null);
					}
				}
				((UniqueConstraint)constraint).ConstraintIndexClear();
				return;
			}
			if (constraint is ForeignKeyConstraint)
			{
				for (int j = 0; j < this.Table.ParentRelations.Count; j++)
				{
					DataRelation dataRelation2 = this.Table.ParentRelations[j];
					if (dataRelation2.ChildKeyConstraint == constraint)
					{
						dataRelation2.SetChildKeyConstraint(null);
					}
				}
			}
		}

		// Token: 0x0600048F RID: 1167 RVA: 0x001E8488 File Offset: 0x001E7888
		public bool CanRemove(Constraint constraint)
		{
			return this.CanRemove(constraint, false);
		}

		// Token: 0x06000490 RID: 1168 RVA: 0x001E84A8 File Offset: 0x001E78A8
		internal bool CanRemove(Constraint constraint, bool fThrowException)
		{
			return constraint.CanBeRemovedFromCollection(this, fThrowException);
		}

		// Token: 0x06000491 RID: 1169 RVA: 0x001E84C8 File Offset: 0x001E78C8
		public void Clear()
		{
			if (this.table != null)
			{
				this.table.PrimaryKey = null;
				for (int i = 0; i < this.table.ParentRelations.Count; i++)
				{
					this.table.ParentRelations[i].SetChildKeyConstraint(null);
				}
				for (int j = 0; j < this.table.ChildRelations.Count; j++)
				{
					this.table.ChildRelations[j].SetParentKeyConstraint(null);
				}
			}
			if (this.table.fInitInProgress && this.delayLoadingConstraints != null)
			{
				this.delayLoadingConstraints = null;
				this.fLoadForeignKeyConstraintsOnly = false;
			}
			int count = this.List.Count;
			Constraint[] array = new Constraint[this.List.Count];
			this.List.CopyTo(array, 0);
			try
			{
				this.BaseGroupSwitch(array, count, null, 0);
			}
			catch (Exception e)
			{
				if (ADP.IsCatchableOrSecurityExceptionType(e))
				{
					this.BaseGroupSwitch(null, 0, array, count);
					this.List.Clear();
					for (int k = 0; k < count; k++)
					{
						this.List.Add(array[k]);
					}
				}
				throw;
			}
			this.List.Clear();
			this.OnCollectionChanged(InternalDataCollectionBase.RefreshEventArgs);
		}

		// Token: 0x06000492 RID: 1170 RVA: 0x001E8628 File Offset: 0x001E7A28
		public bool Contains(string name)
		{
			return this.InternalIndexOf(name) >= 0;
		}

		// Token: 0x06000493 RID: 1171 RVA: 0x001E8648 File Offset: 0x001E7A48
		internal bool Contains(string name, bool caseSensitive)
		{
			if (!caseSensitive)
			{
				return this.Contains(name);
			}
			int num = this.InternalIndexOf(name);
			return num >= 0 && name == ((Constraint)this.List[num]).ConstraintName;
		}

		// Token: 0x06000494 RID: 1172 RVA: 0x001E8698 File Offset: 0x001E7A98
		public void CopyTo(Constraint[] array, int index)
		{
			if (array == null)
			{
				throw ExceptionBuilder.ArgumentNull("array");
			}
			if (index < 0)
			{
				throw ExceptionBuilder.ArgumentOutOfRange("index");
			}
			if (array.Length - index < this.list.Count)
			{
				throw ExceptionBuilder.InvalidOffsetLength();
			}
			for (int i = 0; i < this.list.Count; i++)
			{
				array[index + i] = (Constraint)this.list[i];
			}
		}

		// Token: 0x06000495 RID: 1173 RVA: 0x001E8708 File Offset: 0x001E7B08
		internal Constraint FindConstraint(Constraint constraint)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (((Constraint)this.List[i]).Equals(constraint))
				{
					return (Constraint)this.List[i];
				}
			}
			return null;
		}

		// Token: 0x06000496 RID: 1174 RVA: 0x001E8768 File Offset: 0x001E7B68
		internal UniqueConstraint FindKeyConstraint(DataColumn[] columns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && ConstraintCollection.CompareArrays(uniqueConstraint.Key.ColumnsReference, columns))
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000497 RID: 1175 RVA: 0x001E87C8 File Offset: 0x001E7BC8
		internal UniqueConstraint FindKeyConstraint(DataColumn column)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				UniqueConstraint uniqueConstraint = this.List[i] as UniqueConstraint;
				if (uniqueConstraint != null && uniqueConstraint.Key.ColumnsReference.Length == 1 && uniqueConstraint.Key.ColumnsReference[0] == column)
				{
					return uniqueConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000498 RID: 1176 RVA: 0x001E8838 File Offset: 0x001E7C38
		internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				ForeignKeyConstraint foreignKeyConstraint = this.List[i] as ForeignKeyConstraint;
				if (foreignKeyConstraint != null && ConstraintCollection.CompareArrays(foreignKeyConstraint.ParentKey.ColumnsReference, parentColumns) && ConstraintCollection.CompareArrays(foreignKeyConstraint.ChildKey.ColumnsReference, childColumns))
				{
					return foreignKeyConstraint;
				}
			}
			return null;
		}

		// Token: 0x06000499 RID: 1177 RVA: 0x001E88A8 File Offset: 0x001E7CA8
		private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2)
		{
			if (a1.Length != a2.Length)
			{
				return false;
			}
			for (int i = 0; i < a1.Length; i++)
			{
				bool flag = false;
				for (int j = 0; j < a2.Length; j++)
				{
					if (a1[i] == a2[j])
					{
						flag = true;
						break;
					}
				}
				if (!flag)
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x0600049A RID: 1178 RVA: 0x001E88F8 File Offset: 0x001E7CF8
		public int IndexOf(Constraint constraint)
		{
			if (constraint != null)
			{
				int count = this.Count;
				for (int i = 0; i < count; i++)
				{
					if (constraint == (Constraint)this.List[i])
					{
						return i;
					}
				}
			}
			return -1;
		}

		// Token: 0x0600049B RID: 1179 RVA: 0x001E8938 File Offset: 0x001E7D38
		public int IndexOf(string constraintName)
		{
			int num = this.InternalIndexOf(constraintName);
			if (num >= 0)
			{
				return num;
			}
			return -1;
		}

		// Token: 0x0600049C RID: 1180 RVA: 0x001E8958 File Offset: 0x001E7D58
		internal int InternalIndexOf(string constraintName)
		{
			int num = -1;
			if (constraintName != null && 0 < constraintName.Length)
			{
				int count = this.List.Count;
				for (int i = 0; i < count; i++)
				{
					Constraint constraint = (Constraint)this.List[i];
					int num2 = base.NamesEqual(constraint.ConstraintName, constraintName, false, this.table.Locale);
					if (num2 == 1)
					{
						return i;
					}
					if (num2 == -1)
					{
						num = ((num == -1) ? i : -2);
					}
				}
			}
			return num;
		}

		// Token: 0x0600049D RID: 1181 RVA: 0x001E89D8 File Offset: 0x001E7DD8
		private string MakeName(int index)
		{
			if (1 == index)
			{
				return "Constraint1";
			}
			return "Constraint" + index.ToString(CultureInfo.InvariantCulture);
		}

		// Token: 0x0600049E RID: 1182 RVA: 0x001E8A08 File Offset: 0x001E7E08
		private void OnCollectionChanged(CollectionChangeEventArgs ccevent)
		{
			if (this.onCollectionChanged != null)
			{
				this.onCollectionChanged(this, ccevent);
			}
		}

		// Token: 0x0600049F RID: 1183 RVA: 0x001E8A38 File Offset: 0x001E7E38
		internal void RegisterName(string name)
		{
			int count = this.List.Count;
			for (int i = 0; i < count; i++)
			{
				if (base.NamesEqual(name, ((Constraint)this.List[i]).ConstraintName, true, this.table.Locale) != 0)
				{
					throw ExceptionBuilder.DuplicateConstraintName(((Constraint)this.List[i]).ConstraintName);
				}
			}
			if (base.NamesEqual(name, this.MakeName(this.defaultNameIndex), true, this.table.Locale) != 0)
			{
				this.defaultNameIndex++;
			}
		}

		// Token: 0x060004A0 RID: 1184 RVA: 0x001E8AD8 File Offset: 0x001E7ED8
		public void Remove(Constraint constraint)
		{
			if (constraint == null)
			{
				throw ExceptionBuilder.ArgumentNull("constraint");
			}
			if (this.CanRemove(constraint, true))
			{
				this.BaseRemove(constraint);
				this.ArrayRemove(constraint);
				if (constraint is UniqueConstraint && ((UniqueConstraint)constraint).IsPrimaryKey)
				{
					this.Table.PrimaryKey = null;
				}
				this.OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, constraint));
			}
		}

		// Token: 0x060004A1 RID: 1185 RVA: 0x001E8B48 File Offset: 0x001E7F48
		public void RemoveAt(int index)
		{
			Constraint constraint = this[index];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintOutOfRange(index);
			}
			this.Remove(constraint);
		}

		// Token: 0x060004A2 RID: 1186 RVA: 0x001E8B78 File Offset: 0x001E7F78
		public void Remove(string name)
		{
			Constraint constraint = this[name];
			if (constraint == null)
			{
				throw ExceptionBuilder.ConstraintNotInTheTable(name);
			}
			this.Remove(constraint);
		}

		// Token: 0x060004A3 RID: 1187 RVA: 0x001E8BA8 File Offset: 0x001E7FA8
		internal void UnregisterName(string name)
		{
			if (base.NamesEqual(name, this.MakeName(this.defaultNameIndex - 1), true, this.table.Locale) != 0)
			{
				do
				{
					this.defaultNameIndex--;
				}
				while (this.defaultNameIndex > 1 && !this.Contains(this.MakeName(this.defaultNameIndex - 1)));
			}
		}

		// Token: 0x060004A4 RID: 1188 RVA: 0x001E8C08 File Offset: 0x001E8008
		internal void FinishInitConstraints()
		{
			if (this.delayLoadingConstraints == null)
			{
				return;
			}
			for (int i = 0; i < this.delayLoadingConstraints.Length; i++)
			{
				if (this.delayLoadingConstraints[i] is UniqueConstraint)
				{
					if (!this.fLoadForeignKeyConstraintsOnly)
					{
						UniqueConstraint uniqueConstraint = (UniqueConstraint)this.delayLoadingConstraints[i];
						if (uniqueConstraint.columnNames == null)
						{
							this.Add(uniqueConstraint);
						}
						else
						{
							int num = uniqueConstraint.columnNames.Length;
							DataColumn[] array = new DataColumn[num];
							for (int j = 0; j < num; j++)
							{
								array[j] = this.table.Columns[uniqueConstraint.columnNames[j]];
							}
							if (uniqueConstraint.bPrimaryKey)
							{
								if (this.table.primaryKey != null)
								{
									throw ExceptionBuilder.AddPrimaryKeyConstraint();
								}
								this.Add(uniqueConstraint.ConstraintName, array, true);
							}
							else
							{
								UniqueConstraint constraint = new UniqueConstraint(uniqueConstraint.constraintName, array);
								if (this.FindConstraint(constraint) == null)
								{
									this.Add(constraint);
								}
							}
						}
					}
				}
				else
				{
					ForeignKeyConstraint foreignKeyConstraint = (ForeignKeyConstraint)this.delayLoadingConstraints[i];
					if (foreignKeyConstraint.parentColumnNames == null || foreignKeyConstraint.childColumnNames == null)
					{
						this.Add(foreignKeyConstraint);
					}
					else if (this.table.DataSet == null)
					{
						this.fLoadForeignKeyConstraintsOnly = true;
					}
					else
					{
						int num = foreignKeyConstraint.parentColumnNames.Length;
						DataColumn[] array = new DataColumn[num];
						DataColumn[] array2 = new DataColumn[num];
						for (int k = 0; k < num; k++)
						{
							if (foreignKeyConstraint.parentTableNamespace == null)
							{
								array[k] = this.table.DataSet.Tables[foreignKeyConstraint.parentTableName].Columns[foreignKeyConstraint.parentColumnNames[k]];
							}
							else
							{
								array[k] = this.table.DataSet.Tables[foreignKeyConstraint.parentTableName, foreignKeyConstraint.parentTableNamespace].Columns[foreignKeyConstraint.parentColumnNames[k]];
							}
							array2[k] = this.table.Columns[foreignKeyConstraint.childColumnNames[k]];
						}
						this.Add(new ForeignKeyConstraint(foreignKeyConstraint.constraintName, array, array2)
						{
							AcceptRejectRule = foreignKeyConstraint.acceptRejectRule,
							DeleteRule = foreignKeyConstraint.deleteRule,
							UpdateRule = foreignKeyConstraint.updateRule
						});
					}
				}
			}
			if (!this.fLoadForeignKeyConstraintsOnly)
			{
				this.delayLoadingConstraints = null;
			}
		}

		// Token: 0x040006D8 RID: 1752
		private readonly DataTable table;

		// Token: 0x040006D9 RID: 1753
		private readonly ArrayList list = new ArrayList();

		// Token: 0x040006DA RID: 1754
		private int defaultNameIndex = 1;

		// Token: 0x040006DB RID: 1755
		private CollectionChangeEventHandler onCollectionChanged;

		// Token: 0x040006DC RID: 1756
		private Constraint[] delayLoadingConstraints;

		// Token: 0x040006DD RID: 1757
		private bool fLoadForeignKeyConstraintsOnly;
	}
}
