(function(a,b,l){var f=a.extend;
var e=a.each;
var j=window.kendo;
var g="initialize",k="load",d="click",c="change",h="itemClick";
var i={0:"item",1:"rootitem",item:0,rootitem:1,};
a.registerEnum(b,"BreadcrumbItemType",{Item:0,RootItem:1});
b.RadBreadcrumb=function(m){var n=this;
b.RadBreadcrumb.initializeBase(n,[m]);
n._initialized=false;
n._options={};
n.kendoWidget=null;
n._skin=null;
};
b.RadBreadcrumb.prototype={initialize:function(){var n=this;
var m=n._options;
if(n._initialized){return;
}b.RadBreadcrumb.callBaseMethod(n,"initialize");
n.raiseEvent(g);
n._initializeKendoWidget();
if(this._skin){}n._initialized=true;
n.raiseEvent(k);
},dispose:function(){var m=this;
if(m.kendoWidget){m.kendoWidget.destroy();
}delete m.kendoWidget;
delete m._options;
b.RadBreadcrumb.callBaseMethod(m,"dispose");
},_initializeKendoWidget:function(){var p=this;
var m=$telerik.$.extend({},p._options,{click:function(r){var q=a.extendEventArgs(new Sys.CancelEventArgs(),{sender:r.sender,originalEvent:r.originalEvent,isRoot:r.isRoot,item:r.item});
if(a.raiseCancellableControlEvent(p,d,q)){r.preventDefault();
}},change:function(r){var q=a.extendEventArgs(new Sys.EventArgs(),{sender:r.sender,value:r.value});
a.raiseControlEvent(p,c,q);
}});
if(m.items!==l){for(var n=0;
n<m.items.length;
n++){var o=m.items[n];
if(o.type){o.type=i[o.type];
}}}p.kendoWidget=a(p._element).kendoBreadcrumb(m).getKendoBreadcrumb();
},get_kendoWidget:function(){return this.kendoWidget;
},get_items:function(){return this.kendoWidget.items();
},get_value:function(){return this.kendoWidget.value();
},set_value:function(m){return this.kendoWidget.value(m);
},repaint:function(m){this.kendoWidget.resize(m);
}};
b.RadBreadcrumb.registerClass("Telerik.Web.UI.RadBreadcrumb",b.RadWebControl);
a.registerControlEvents(b.RadBreadcrumb,[g,k,d,c]);
a.registerControlProperties(b.RadBreadcrumb,{skin:""});
})($telerik.$,Telerik.Web.UI);
