using System;

namespace TechnoPro.Common.DAO.Impl.OnlineForms
{
	// Token: 0x02000081 RID: 129
	public class QueryStorageOnlineForms
	{
		// Token: 0x0400016A RID: 362
		internal const string QS_ALL_ONLINEFORMS = "SELECT s.onlineformid,s.title AS onlineformtitle,s.[description] AS onlineformdescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.[description],sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    OnlineForm s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.isdeleted=0\r\nORDER BY s.title";

		// Token: 0x0400016B RID: 363
		internal const string QS_ACTIVE_ONLINEFORMS = "SELECT s.onlineformid,s.title AS onlineformtitle,s.[description] AS onlineformdescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.description,sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    OnlineForm s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.isdeleted=0 AND s.isdisabled=0 AND s.formnum > 0\r\n        AND \r\n        (\r\n            (s.startdate is NULL AND s.enddate IS NULL )\r\n\t\t\tOR\r\n            (NOT s.startdate IS NULL AND NOT s.enddate IS NULL AND getdate() BETWEEN s.startdate AND s.enddate)\r\n            OR\r\n            (NOT s.startdate IS NULL AND s.enddate IS NULL AND getdate() >= s.startdate)\r\n            OR\r\n            (s.startdate IS NULL AND NOT s.enddate IS NULL AND getdate() <= s.enddate)\r\n        )\r\nORDER BY s.title";

		// Token: 0x0400016C RID: 364
		internal const string QS_ONLINEFORM_BY_ID = "SELECT s.onlineformid,s.title AS onlineformtitle,s.[description] AS onlineformdescription,\r\n\t\ts.formnum AS screennum,s.usewizard,s.submitmessage,s.submitbuttontext,s.shortcode,s.startdate,s.enddate,s.requireslogin,s.canonlybefilledinonce,\r\n        s.captcha,s.studentemailconfirmationtemplateid,s.staffemailconfirmationtemplateid,s.restricttogroupid,s.isdeleted,s.isdisabled,s.whocreated AS whocreatedpersonid,s.wholastmodified AS wholastmodifiedpersonid,s.datecreated,s.datelastmodified,\r\n        p.firstname AS whocreatedfirstname,p.lastname AS whocreatedlastname,p.student_no AS whocreatedstudent_no,\r\n        p2.firstname AS wholastmodifiedfirstname,p2.lastname AS wholastmodifiedlastname,p2.student_no AS wholastmodifiedstudent_no,\r\n        g.[description] AS restricttodescription,g.isprimary AS restricttoisprimary,\r\n        sc.typecode,sc.description,sc.shorttext,sc.bottomless,sc.columnwidth,\r\n        sc.longdescription,sc.showasbutton,sc.iconindex,sc.largeiconindex,sc.isactive,sc.screenuniqueid\r\nFROM    OnlineForm s LEFT JOIN people p ON p.personid=s.whocreated\r\n        LEFT JOIN people p2 ON p2.personid=s.wholastmodified\r\n        LEFT JOIN screens sc ON sc.screennum=s.formnum\r\n        LEFT JOIN groups g ON g.GroupID=s.RestrictToGroupId\r\nWHERE   s.onlineformid=@onlineformid";

		// Token: 0x0400016D RID: 365
		internal const string QU_ONLINEFORM_DISABLED_STATUS = "UPDATE OnlineForm SET isdisabled=@newdisabled WHERE onlineformid=@id";

		// Token: 0x0400016E RID: 366
		internal const string QU_UPDATE_ONLINEFORM = "UPDATE OnlineForm SET title=@title,description=@description,formnum=@formnum,usewizard=@usewizard\r\n        ,submitmessage=@submitmessage,submitbuttontext=@submitbuttontext,shortcode=@shortcode\r\n        ,startdate=@startdate,enddate=@enddate,requireslogin=@requireslogin,canonlybefilledinonce=@canonlybefilledinonce\r\n        ,captcha=@captcha,studentemailconfirmationtemplateid=@studentemailconfirmationtemplateid,staffemailconfirmationtemplateid=@staffemailconfirmationtemplateid\r\n        ,restricttogroupid=@restricttogroupid,isdeleted=@isdeleted,isdisabled=@isdisabled\r\n        ,wholastmodified=@wholastmodified,datelastmodified=getdate()\r\nWHERE   onlineformid=@onlineformid";

		// Token: 0x0400016F RID: 367
		internal const string QI_CREATE_ONLINEFORM = "INSERT INTO OnlineForm (title,description,formnum,usewizard,submitmessage,submitbuttontext\r\n        ,shortcode,startdate,enddate,requireslogin,canonlybefilledinonce,captcha,studentemailconfirmationtemplateid,staffemailconfirmationtemplateid\r\n        ,restricttogroupid,isdeleted,isdisabled,whocreated)\r\nVALUES (@title,@description,@formnum,@usewizard,@submitmessage,@submitbuttontext\r\n        ,@shortcode,@startdate,@enddate,@requireslogin,@canonlybefilledinonce,@captcha,@studentemailconfirmationtemplateid,@staffemailconfirmationtemplateid\r\n        ,@restricttogroupid,@isdeleted,@isdisabled,@whocreated);\r\nSELECT CAST(SCOPE_IDENTITY() AS int) AS onlineformid";

		// Token: 0x04000170 RID: 368
		internal const string QD_ONLINEFORM = "UPDATE OnlineForm SET isdeleted=1 WHERE onlineformid=@id";
	}
}
