using System;

namespace TechnoPro.Common.DAO.Impl.Appointments
{
	// Token: 0x02000132 RID: 306
	internal static class QueryStorageBaseAppointment
	{
		// Token: 0x04000528 RID: 1320
		internal const string QS_GET_APPOINTMENT_EXTERNAL_ID = "select ExternalId from appointments where AppointmentId=@appid";

		// Token: 0x04000529 RID: 1321
		internal const string QS_DISTINCT_PERSONBASE_BY_STUDENT_AND_STAFF_GROUP = "SELECT DISTINCT a.appointmentid,att.personid,p.firstname,p.middlename,p.lastname,p.student_no,MIN(pg.groupid) AS groupid\r\nFROM    apps a LEFT JOIN attendees att ON att.appointmentid=a.appointmentid AND att.personid IN (SELECT personid FROM peoplegroups WHERE groupid IN (SELECT orderid AS groupid FROM splitorderids(@gids,',')))\r\n        LEFT JOIN people p ON p.personid=att.personid\r\n        LEFT JOIN peoplegroups pg ON pg.personid=att.personid\r\nWHERE   a.personid=@pid AND a.cancelled=0 AND a.noshow=0\r\nGROUP BY a.appointmentid,att.personid,p.firstname,p.middlename,p.lastname,p.student_no";

		// Token: 0x0400052A RID: 1322
		internal const string QS_FIND_EXISTING_MATCHING_APPOINTMENT = "DECLARE @numpids int\r\nSET @numpids=(SELECT COUNT(DISTINCT(orderid)) FROM SplitOrderIDs(@pids,','))\r\n\r\nSET @appointmentid=(SELECT TOP 1 appointmentid FROM\r\n(\r\nSELECT a.appointmentid,COUNT(DISTINCT(personid)) AS ct\r\nFROM apps a \r\nWHERE a.startdate=@startdatetime AND a.enddate=@enddatetime AND a.PersonID IN (SELECT orderid AS personid FROM SplitOrderIDs(@pids,','))\r\nGROUP BY a.AppointmentID \r\nHAVING COUNT(DISTINCT(personid))=@numpids\r\n) x\r\n)";

		// Token: 0x0400052B RID: 1323
		internal const string QS_BASEBASICAPPOINTMENT_BASE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\ta.AttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\n";

		// Token: 0x0400052C RID: 1324
		internal const string QS_BASEBASICAPPOINTMENT_BY_ID = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\ta.AttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.appointmentid=@appid ORDER BY a.AttendeeID";

		// Token: 0x0400052D RID: 1325
		internal const string QS_BASEBASICAPPOINTMENTS_BY_GROUPCODE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\ta.AttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.groupcode=@groupcode ORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x0400052E RID: 1326
		internal const string QS_BASEBASICAPPOINTMENTS_BY_DATE_AND_PERSON = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   a.startdate BETWEEN @startdate AND @enddate\r\nAND a.appointmentid IN (SELECT appointmentid FROM attendees WHERE personid IN (SELECT orderid AS personid FROM splitorderids(@pids,',')))\r\nAND (@hidecancelled=0 OR a.cancelled=0)\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x0400052F RID: 1327
		private const string QS_BASE_EXTENDEDAPPOINTMENT_BASE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\n";

		// Token: 0x04000530 RID: 1328
		internal const string QS_BASEEXTENDEDAPPOINTMENT_BY_ID = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.appointmentid=@appid\r\nORDER BY a.AttendeeID";

		// Token: 0x04000531 RID: 1329
		internal const string QS_BASEEXTENDEDAPPOINTMENTS_BY_DATE_AND_APPTYPE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   a.startdate BETWEEN @startdate AND @enddate\r\n        AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x04000532 RID: 1330
		internal const string QS_BASEEXTENDEDAPPOINTMENTS_BY_DATE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.startdate BETWEEN @startdate AND @enddate AND (@showcancelled=1 OR a.cancelled=0)\r\nORDER BY a.appointmentid,a.AttendeID";

		// Token: 0x04000533 RID: 1331
		internal const string QS_BASEEXTENDEDAPPOINTMENTS_BY_DATE_AND_PERSONIDS = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   a.startdate BETWEEN @startdate AND @enddate\r\n        AND a.appointmentid IN (SELECT appointmentid FROM attendees WHERE personid IN (SELECT orderid AS personid FROM splitorderids(@pids,',')))\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x04000534 RID: 1332
		internal const string QS_BASEEXTENDEDAPPOINTMENTS_BY_PERSONID = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE   a.appointmentid IN (SELECT appointmentid FROM attendees WHERE personid=@pid)\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x04000535 RID: 1333
		internal const string QS_BASEEXTENDEDAPPOINTMENT_BY_GROUPCODE = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.groupcode=@groupcode\r\nORDER BY a.AttendeeID";

		// Token: 0x04000536 RID: 1334
		internal const string QS_BASEEXTENDEDAPPOINTMENT_BY_APPOINTMENTIDS = "SELECT\ta.appointmentid,a.AppTypeID,a.[description] AS apptypedescription,\r\n        at.appointmenttypegroupid,atg.title AS apptypegrouptitle,\r\n\t\ta.appCode,a.startDate,a.endDate,a.[subject],a.location,\r\n\t\ta.cancelled,a.isLocked,a.isHidden,a.groupCode,a.extraattendeescount,\r\n\t\tAttendeeID,a.PersonID,a.firstName,a.lastName,a.student_no,a.miscCode,a.noShow,\r\n\t\tat.isCourse,at.isWorkshop,at.defaultColour,\r\n\t\tam.memoText,am.isEncrypted,\r\n\t\ta.whoadded AS wbpersonid,pwb.firstName AS wbfirstname,pwb.lastName AS wblastname,pwb.student_no AS wbstudent_no,\r\n\t\ta.dateAdded AS datebooked,a.overrideColour,a.actualstarttime,a.actualendtime,\r\n\t\tacr.cancelreasonid,cr.cancelreasongroupname,cr.cancelreasontitle,\r\n\t\tacr.cancelledbypersonid AS cbpersonid,pcb.firstName AS cbfirstname,pcb.lastName AS cblastname,pcb.student_no AS cbstudent_no,\r\n\t\tacr.cancelleddate,acr.cancelreasontext,\r\n\t\tpg.groupid,ast.appointmentshowtimeasid,ast.showtimeastitle,ast.extraiconid,ast.showtimeascolour\r\nFROM\tapps a LEFT JOIN peoplegroups pg ON pg.personid=a.personid AND pg.groupid<10 \r\n\t\tLEFT JOIN AppointmentTypes at ON at.apptypeid=a.AppTypeID \r\n\t\tLEFT JOIN AppointmentTypeGroups atg ON atg.AppointmentTypeGroupID=at.appointmentTypeGroupID \r\n\t\tLEFT JOIN AppointmentMemos am ON am.AppointmentID=a.AppointmentID \r\n\t\tLEFT JOIN People pwb ON pwb.PersonID=a.whoadded \r\n\t\tLEFT JOIN AppointmentCancelledReason acr ON acr.appointmentid=a.AppointmentID\r\n\t\tLEFT JOIN CancelReason cr ON cr.cancelreasonid=acr.cancelreasonid \r\n\t\tLEFT JOIN People pcb ON pcb.PersonID=acr.cancelledbypersonid \r\n        LEFT JOIN AppointmentShowTimeAs ast ON ast.extraiconid=a.appcode\r\nWHERE a.appointmentid IN (SELECT orderid AS appointmentid FROM splitorderids(@appids,','))\r\n        AND a.apptypeid IN (SELECT orderid AS apptypeid FROM splitorderids(@apptypeids,','))\r\nORDER BY a.appointmentid,a.AttendeeID";

		// Token: 0x04000537 RID: 1335
		internal const string QU_APPOINTMENT_EXTERNAL_ID = "update Appointments\r\nset\r\n\tExternalId = @externalid\r\nwhere AppointmentID = @appid";

		// Token: 0x04000538 RID: 1336
		internal const string QU_APPOINTMENT_APPCODE = "UPDATE appointments SET appcode=@appcode WHERE appointmentid=@appid";

		// Token: 0x04000539 RID: 1337
		internal const string QU_APPOINTMENT_CANCELLED = "UPDATE appointments SET cancelled=@cancelled WHERE appointmentid=@appid";

		// Token: 0x0400053A RID: 1338
		internal const string QU_INSERT_OR_UPDATE_CANCEL_INFO = "IF EXISTS(SELECT appointmentid FROM appointmentcancelledreason WHERE appointmentid=@appid)\r\nBEGIN\r\n    IF @isempty=1\r\n        DELETE FROM appointmentcancelledreason WHERE appointmentid=@appid\r\n    ELSE\r\n        UPDATE appointmentcancelledreason SET cancelreasonid=@cancelreasonid,cancelreasontext=@cancelreasontext\r\n        WHERE appointmentid=@appid\r\nEND\r\nELSE\r\nBEGIN\r\n    IF @isempty=0\r\n        INSERT INTO appointmentcancelledreason (appointmentid,cancelreasonid,cancelreasontext,cancelledbypersonid,cancelleddate)\r\n        VALUES (@appid,@cancelreasonid,@cancelreasontext,@cancelledbypersonid,getdate())\r\nEND";

		// Token: 0x0400053B RID: 1339
		internal const string QU_APPOINTMENT_DATE_AND_TIME = "UPDATE appointments SET startdate=@startdate,enddate=@enddate WHERE appointmentid=@appid";

		// Token: 0x0400053C RID: 1340
		internal const string QU_APPOINTMENT_BASIC = "UPDATE appointments SET \r\n\tAppTypeID=@apptypeid,appCode=@appcode,startDate=@startdate,endDate=@enddate,\r\n\t[Subject]=@subtitle,cancelled=@cancelled,isLocked=COALESCE(@islocked,isLocked),isHidden=COALESCE(@ishidden,isHidden),\r\n\tLocation=@location,groupCode=@groupcode\r\nWHERE AppointmentID=@appid";

		// Token: 0x0400053D RID: 1341
		internal const string QU_EXTENDED_APPOINTMENT = "UPDATE\tappointments SET \r\n\textraAttendeesCount=@extraattendeescount,overrideColour=@overridecolour,\r\n\tActualStartTime=@actualstarttime,ActualEndTime=@actualendtime\r\nWHERE\tAppointmentID=@appid ";

		// Token: 0x0400053E RID: 1342
		internal const string QU_APPOINTMENT_MEMO = "IF @memotext IS NULL\r\n\tDELETE FROM AppointmentMemos WHERE AppointmentID=@appid \r\nELSE\r\nBEGIN \r\n\tIF EXISTS(SELECT appmemoid FROM AppointmentMemos WHERE AppointmentID=@appid)\r\n\t\tUPDATE AppointmentMemos SET memoText=@memotext WHERE AppointmentID=@appid \r\n\telse \r\n\t\tINSERT INTO AppointmentMemos(AppointmentID,memoText,isEncrypted) VALUES (@appid,@memotext,1)\r\nEND\r\nSELECT appmemoid FROM AppointmentMemos WHERE AppointmentID=@appid ";

		// Token: 0x0400053F RID: 1343
		internal const string QI_INSERTORUPDATE_ROOM_BY_APPOINTMENTID = "IF @pid IS NULL OR @pid<1\r\n\tDELETE FROM attendees WHERE AppointmentID=@appid AND PersonID IN (SELECT PersonID FROM PeopleGroups WHERE GroupID=3)\r\nELSE \r\nBEGIN\r\n\tDECLARE @currattid int\r\n\tSET @currattid=(SELECT TOP 1 attendeeid FROM attendees WHERE AppointmentID=@appid AND PersonID=@pid)\r\n    IF @currattid IS NULL OR @currattid<1\r\n    BEGIN\r\n\t\tDELETE FROM attendees WHERE AppointmentID=@appid AND PersonID IN (SELECT PersonID FROM PeopleGroups WHERE GroupID=3);\r\n        INSERT INTO attendees (appointmentid,personid) VALUES (@appid,@pid)\r\n    END\r\nEND\r\nSET @attendeeid=(SELECT TOP 1 @attendeeid FROM attendees WHERE AppointmentID=@appid AND PersonID=@pid)";

		// Token: 0x04000540 RID: 1344
		internal const string QI_EXTENDED_APPOINTMENT_PREVENT_DOUBLE_BOOKING = "IF NOT EXISTS(SELECT a.appointmentid,att.personid FROM appointments a LEFT JOIN attendees att ON att.appointmentid=a.appointmentid WHERE a.cancelled=0 AND NOT ( ( a.enddate<=@startdate ) OR (a.startdate >= @enddate ) ) AND att.personid IN (SELECT orderid AS personid FROM splitorderids(@pids,',')) AND NOT att.personid IS NULL)\r\nBEGIN\r\n    INSERT INTO appointments\r\n        (AppTypeId,startDate,endDate,cancelled,personID,isHidden,isLocked,appCode,groupCode,[Subject],Location,dateAdded,extraattendeescount,overridecolour,actualstarttime,actualendtime)\r\n    VALUES\r\n        (@apptypeid,@startdate,@enddate,@cancelled,@pid,@ishidden,@islocked,@appcode,@groupcode,@subtitle,@location,getdate(),@extraattendeescount,@overridecolour,@actualstartdatetime,@actualenddatetime)\r\n    SET @appointmentid=SCOPE_IDENTITY()\r\nEND\r\nELSE\r\nBEGIN\r\n\tSET @appointmentid=0\r\nEND";

		// Token: 0x04000541 RID: 1345
		internal const string QI_EXTENDED_APPOINTMENT = "INSERT INTO appointments\r\n    (AppTypeId,startDate,endDate,cancelled,personID,isHidden,isLocked,appCode,groupCode,[Subject],Location,dateAdded,extraattendeescount,overridecolour,actualstarttime,actualendtime)\r\nVALUES\r\n    (@apptypeid,@startdate,@enddate,@cancelled,@pid,@ishidden,@islocked,@appcode,@groupcode,@subtitle,@location,getdate(),@extraattendeescount,@overridecolour,@actualstartdatetime,@actualenddatetime)\r\nSET @appointmentid=SCOPE_IDENTITY()";

		// Token: 0x04000542 RID: 1346
		internal const string QD_ROOM_BY_APPOINTMENTID = "DELETE FROM attendees WHERE AppointmentID=@appid AND PersonID IN (SELECT PersonID FROM PeopleGroups WHERE GroupID=3)";

		// Token: 0x04000543 RID: 1347
		internal const string QD_ROOM_BY_APPOINTMENTID2 = "DELETE FROM attendees WHERE AppointmentID=@appid AND PersonID IN (SELECT PersonID FROM PeopleGroups WHERE GroupID=3) AND NOT personid IN (SELECT orderid AS personid FROM splitorderids(@pids,','))";

		// Token: 0x04000544 RID: 1348
		internal const string QD_APPOINTMENT_DATA = "BEGIN TRANSACTION\r\nINSERT INTO AppointmentNotesArchive (dataid,personid,appointmentid,controlid,controlvalueint)\r\n    SELECT dataid,personid,appointmentid,controlid,controlvalue FROM maininfopa WHERE appointmentid=@appid;\r\nINSERT INTO AppointmentNotesArchive (dataid,personid,appointmentid,controlid,controlvaluebinary)\r\n    SELECT dataid,personid,appointmentid,controlid,controlvalue FROM otherinfopa WHERE appointmentid=@appid;\r\nINSERT INTO AppointmentNotesArchive (dataid,personid,appointmentid,controlid,controlvaluedatetime)\r\n    SELECT dataid,personid,appointmentid,controlid,controlvalue FROM datetimeinfopa WHERE appointmentid=@appid;\r\nINSERT INTO AppointmentNotesArchive (dataid,personid,appointmentid,controlid,controlvaluebinary)\r\n    SELECT dataid,personid,appointmentid,controlid,controlvalue FROM imageinfopa WHERE appointmentid=@appid;\r\n\r\nDELETE FROM maininfopa WHERE appointmentid=@appid;\r\nDELETE FROM otherinfopa WHERE appointmentid=@appid;\r\nDELETE FROM datetimeinfopa WHERE appointmentid=@appid;\r\nDELETE FROM imageinfopa WHERE appointmentid=@appid;\r\n\r\nCOMMIT TRANSACTION";

		// Token: 0x04000545 RID: 1349
		internal const string QD_ACCOMMODATION_FOR_TEST = "DELETE FROM accommodationstest WHERE appointmentid=@appointmentid AND controlid=@controlid AND personid=@personid";

		// Token: 0x04000546 RID: 1350
		internal const string QD_APPOINTMENT_COURSES = "DELETE FROM appointmentcourses WHERE appointmentid=@appid";

		// Token: 0x04000547 RID: 1351
		internal const string QD_APPOINTMENT_WORKSHOP = "DELETE FROM appointmentworkshops WHERE appointmentid=@appid";

		// Token: 0x04000548 RID: 1352
		internal const string QD_APPOINTMENT_CANCEL_REASON = "DELETE FROM appointmentcancelledreason WHERE appointmentid=@appid";

		// Token: 0x04000549 RID: 1353
		internal const string QD_APPOINTMENT_ICON = "DELETE FROM appointmenticons WHERE appointmentid=@appid AND iconnum=@iconnum";

		// Token: 0x0400054A RID: 1354
		internal const string QD_APPOINTMENT_APPOINTMENT_TESTINFO = "DELETE FROM appointmentcourses WHERE appointmentid=@appid";

		// Token: 0x0400054B RID: 1355
		internal const string QD_APPOINTMENT_APPOINTMENT_WORKSHOP = "DELETE FROM appointmentworkshops WHERE appointmentid=@appid";

		// Token: 0x0400054C RID: 1356
		internal const string QD_APPOINTMENT_ATTENDEES = "DELETE FROM attendees WHERE appointmentid=@appid";

		// Token: 0x0400054D RID: 1357
		internal const string QD_APPOINTMENT_APPOINTMENTICONS = "DELETE FROM appointmenticons WHERE appointmentid=@appid";

		// Token: 0x0400054E RID: 1358
		internal const string QD_APPOINTMENT_CANCELREASON = "DELETE FROM appointmentcancelledreason WHERE appointmentid=@appid";

		// Token: 0x0400054F RID: 1359
		internal const string QD_APPOINTMENT_MEMO = "DELETE FROM appointmentmemos WHERE appointmentid=@appid";

		// Token: 0x04000550 RID: 1360
		internal const string QD_APPOINTMENT_MAIN = "DELETE FROM appointments WHERE appointmentid=@appid";
	}
}
