using System;

namespace TechnoPro.Common.DAO.Impl.MailMerging
{
	// Token: 0x02000097 RID: 151
	public class QueryStorageMailMerging
	{
		// Token: 0x040001C2 RID: 450
		internal const string QS_ALL_PS_DATA = "SELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename\r\nFROM        perstudentdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid=@pid\r\n            AND ps.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum IN (SELECT screennum FROM screens))";

		// Token: 0x040001C3 RID: 451
		internal const string QS_ALL_PerApp_DATA = "SELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename\r\nFROM        perappdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid=@pid AND ps.appointmentid=@appid\r\n            AND ps.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum IN (SELECT screennum FROM screens))";

		// Token: 0x040001C4 RID: 452
		internal const string QS_ALL_PD_DATA = "SELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename\r\nFROM        pmdata2 ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid=@pid AND ps.appointmentid=@appid\r\n            AND ps.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum IN (SELECT screennum FROM screens))";

		// Token: 0x040001C5 RID: 453
		internal const string QS_ALL_ACCOMMODATIONTEMPLATE_DATA = "SELECT    ps.personid,ps.controlid,ps.valtext,ps.valbytes,ps.valimage,ps.valint,ps.valdate,ps.valbytesisencrypted\r\n            ,dc.controlid,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4\r\n            ,dc.setting4string,dc.defaultvalue,dc.defaultvaluestring,dc.controlname,dc.controlgroup\r\n            ,dc.helptext,dc.helptextdisplaymethod,dc.mask,dc.enforce,dc.actionhandlers\r\n            ,dc.enabled,dc.readonly,dc.hidecaption,dc.fontsize,dc.dontwraptonextline\r\n            ,p.firstname,p.lastname,p.student_no,p.middlename\r\nFROM        accommodationdata ps LEFT JOIN people p ON p.personid=ps.personid\r\n            LEFT JOIN dynamiccontrols dc ON dc.controlid=ps.controlid\r\nWHERE       ps.personid=@pid\r\n            AND ps.courseid=0\r\n            AND ps.controlid IN (SELECT controlid FROM dynamicscreencontrols WHERE screennum=4)";

		// Token: 0x040001C6 RID: 454
		internal const string QS_TEMPLATE_BY_ID = "SELECT * FROM emailtemplates WHERE templateid=@templateid";

		// Token: 0x040001C7 RID: 455
		internal const string QS_SAMPLE_MAILMERGE_CONTEXT_VALUES = "SELECT TOP 1 p.personid,c.luCourseID,att.AppointmentID,pl.instructorid,c.CoursesID,app.examid,ac.AppointmentCourseID \r\n\t\t,COALESCE(c.luCourseID,0)\r\n\t\t\t+ COALESCE(att.AppointmentID,0)\r\n\t\t\t+ COALESCE(pl.instructorid,0)\r\n\t\t\t+ COALESCE(app.examid,0) \r\n\t\t\t+ COALESCE(ac.AppointmentCourseID,0)\r\n\t\t\tAS bob\r\nFROM\tpeoplegroups pg LEFT JOIN people p ON p.personid=pg.personid \r\n\t\tLEFT JOIN courses c ON c.personID=pg.PersonID AND (c.registrationstatus is null OR NOT c.registrationstatus=2)\r\n\t\tLEFT JOIN vInstructorPrimaryList pl ON pl.lucourseid=c.luCourseID \r\n\t\tLEFT JOIN attendees att ON att.PersonID=pg.PersonID AND att.noShow=0 AND NOT att.AppointmentID IN (SELECT appointmentid FROM appointments WHERE cancelled=1)\r\n\t\tLEFT JOIN appointments app ON app.AppointmentID=att.AppointmentID \r\n\t\tLEFT JOIN appointmentcourses ac ON ac.AppointmentID=att.AppointmentID \r\nWHERE\t((@pid IS NULL OR @pid<1) OR @pid=pg.personid)\r\n\t\tAND ((@appid IS NULL OR @appid<1) OR @appid=att.AppointmentID)\r\n\t\tAND pg.groupid=1 AND p.isActive=1\r\nORDER BY bob DESC";
	}
}
