using System;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Design;
using System.Drawing;
using System.Web.UI.Design.Util;
using System.Web.UI.WebControls;
using System.Windows.Forms;
using System.Windows.Forms.Design;

namespace System.Web.UI.Design.WebControls
{
	// Token: 0x020004F2 RID: 1266
	internal partial class TreeViewBindingsEditorForm : DesignerForm
	{
		// Token: 0x06002D36 RID: 11574 RVA: 0x000FF97C File Offset: 0x000FE97C
		public TreeViewBindingsEditorForm(IServiceProvider serviceProvider, System.Web.UI.WebControls.TreeView treeView, TreeViewDesigner treeViewDesigner) : base(serviceProvider)
		{
			this._treeView = treeView;
			this._autoBindInitialized = false;
			this.InitializeComponent();
			this.InitializeUI();
			foreach (object obj in this._treeView.DataBindings)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)((ICloneable)treeNodeBinding).Clone();
				treeViewDesigner.RegisterClone(treeNodeBinding, treeNodeBinding2);
				this._bindingsListView.Items.Add(treeNodeBinding2);
			}
		}

		// Token: 0x1700087E RID: 2174
		// (get) Token: 0x06002D37 RID: 11575 RVA: 0x000FFA1C File Offset: 0x000FEA1C
		private IDataSourceSchema Schema
		{
			get
			{
				if (this._schema == null)
				{
					IDesignerHost designerHost = (IDesignerHost)base.ServiceProvider.GetService(typeof(IDesignerHost));
					if (designerHost != null)
					{
						HierarchicalDataBoundControlDesigner hierarchicalDataBoundControlDesigner = designerHost.GetDesigner(this._treeView) as HierarchicalDataBoundControlDesigner;
						if (hierarchicalDataBoundControlDesigner != null)
						{
							DesignerHierarchicalDataSourceView designerView = hierarchicalDataBoundControlDesigner.DesignerView;
							if (designerView != null)
							{
								try
								{
									this._schema = designerView.Schema;
								}
								catch (Exception ex)
								{
									IComponentDesignerDebugService componentDesignerDebugService = (IComponentDesignerDebugService)base.ServiceProvider.GetService(typeof(IComponentDesignerDebugService));
									if (componentDesignerDebugService != null)
									{
										componentDesignerDebugService.Fail(SR.GetString("DataSource_DebugService_FailedCall", new object[]
										{
											"DesignerHierarchicalDataSourceView.Schema",
											ex.Message
										}));
									}
								}
							}
						}
					}
				}
				return this._schema;
			}
		}

		// Token: 0x06002D38 RID: 11576 RVA: 0x000FFAE8 File Offset: 0x000FEAE8
		private void AddBinding()
		{
			System.Windows.Forms.TreeNode selectedNode = this._schemaTreeView.SelectedNode;
			if (selectedNode != null)
			{
				TreeNodeBinding treeNodeBinding = new TreeNodeBinding();
				if (selectedNode.Text != this._schemaTreeView.Nodes[0].Text)
				{
					treeNodeBinding.DataMember = selectedNode.Text;
					if (((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Duplicate)
					{
						treeNodeBinding.Depth = selectedNode.FullPath.Split(new char[]
						{
							this._schemaTreeView.PathSeparator[0]
						}).Length - 1;
					}
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = ((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Schema;
					int num = this._bindingsListView.Items.IndexOf(treeNodeBinding);
					if (num == -1)
					{
						this._bindingsListView.Items.Add(treeNodeBinding);
						this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
					}
					else
					{
						treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[num];
						this._bindingsListView.SetSelected(num, true);
					}
				}
				else
				{
					this._bindingsListView.Items.Add(treeNodeBinding);
					this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				this.UpdateEnabledStates();
			}
			this._bindingsListView.Focus();
		}

		// Token: 0x06002D39 RID: 11577 RVA: 0x000FFC55 File Offset: 0x000FEC55
		private void ApplyBindings()
		{
			ControlDesigner.InvokeTransactedChange(this._treeView, new TransactedChangeCallback(this.ApplyBindingsChangeCallback), null, SR.GetString("TreeViewDesigner_EditBindingsTransactionDescription"));
		}

		// Token: 0x06002D3A RID: 11578 RVA: 0x000FFC7C File Offset: 0x000FEC7C
		private bool ApplyBindingsChangeCallback(object context)
		{
			this._treeView.DataBindings.Clear();
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding binding = (TreeNodeBinding)obj;
				this._treeView.DataBindings.Add(binding);
			}
			PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(this._treeView)["AutoGenerateDataBindings"];
			propertyDescriptor.SetValue(this._treeView, this._autogenerateBindingsCheckBox.Checked);
			return true;
		}

		// Token: 0x06002D3C RID: 11580 RVA: 0x000FFD47 File Offset: 0x000FED47
		private IDataSourceViewSchema FindViewSchema(string viewName, int level)
		{
			return TreeViewBindingsEditorForm.FindViewSchemaRecursive(this.Schema, 0, viewName, level, null);
		}

		// Token: 0x06002D3D RID: 11581 RVA: 0x000FFD58 File Offset: 0x000FED58
		internal static IDataSourceViewSchema FindViewSchemaRecursive(object schema, int depth, string viewName, int level, IDataSourceViewSchema bestBet)
		{
			if (schema is IDataSourceSchema || schema is IDataSourceViewSchema)
			{
				IDataSourceViewSchema dataSourceViewSchema = schema as IDataSourceViewSchema;
				IDataSourceViewSchema[] array = (dataSourceViewSchema != null) ? dataSourceViewSchema.GetChildren() : ((IDataSourceSchema)schema).GetViews();
				if (array != null)
				{
					if (depth == level)
					{
						foreach (IDataSourceViewSchema dataSourceViewSchema2 in array)
						{
							if (string.Equals(dataSourceViewSchema2.Name, viewName, StringComparison.OrdinalIgnoreCase))
							{
								return dataSourceViewSchema2;
							}
							if (string.IsNullOrEmpty(dataSourceViewSchema2.Name) && bestBet == null)
							{
								bestBet = dataSourceViewSchema2;
							}
							bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema2, depth + 1, viewName, level, bestBet);
						}
						return bestBet;
					}
					foreach (IDataSourceViewSchema dataSourceViewSchema3 in array)
					{
						if (level == -1 && string.Equals(dataSourceViewSchema3.Name, viewName, StringComparison.OrdinalIgnoreCase) && bestBet == null)
						{
							return dataSourceViewSchema3;
						}
						bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema3, depth + 1, viewName, level, bestBet);
					}
					return bestBet;
				}
				return bestBet;
			}
			return null;
		}

		// Token: 0x1700087F RID: 2175
		// (get) Token: 0x06002D3E RID: 11582 RVA: 0x000FFE43 File Offset: 0x000FEE43
		protected override string HelpTopic
		{
			get
			{
				return "net.Asp.TreeView.BindingsEditorForm";
			}
		}

		// Token: 0x06002D40 RID: 11584 RVA: 0x001006C4 File Offset: 0x000FF6C4
		private void InitializeUI()
		{
			this._bindingsLabel.Text = SR.GetString("TreeViewBindingsEditor_Bindings");
			this._schemaLabel.Text = SR.GetString("TreeViewBindingsEditor_Schema");
			this._okButton.Text = SR.GetString("TreeViewBindingsEditor_OK");
			this._applyButton.Text = SR.GetString("TreeViewBindingsEditor_Apply");
			this._cancelButton.Text = SR.GetString("TreeViewBindingsEditor_Cancel");
			this._propertiesLabel.Text = SR.GetString("TreeViewBindingsEditor_BindingProperties");
			this._autogenerateBindingsCheckBox.Text = SR.GetString("TreeViewBindingsEditor_AutoGenerateBindings");
			this._addBindingButton.Text = SR.GetString("TreeViewBindingsEditor_AddBinding");
			this.Text = SR.GetString("TreeViewBindingsEditor_Title");
			Bitmap bitmap = new Icon(typeof(TreeViewBindingsEditor), "SortUp.ico").ToBitmap();
			bitmap.MakeTransparent();
			this._moveBindingUpButton.Image = bitmap;
			this._moveBindingUpButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingUpName");
			this._moveBindingUpButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingUpDescription");
			Bitmap bitmap2 = new Icon(typeof(TreeViewBindingsEditor), "SortDown.ico").ToBitmap();
			bitmap2.MakeTransparent();
			this._moveBindingDownButton.Image = bitmap2;
			this._moveBindingDownButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingDownName");
			this._moveBindingDownButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingDownDescription");
			Bitmap bitmap3 = new Icon(typeof(TreeViewBindingsEditor), "Delete.ico").ToBitmap();
			bitmap3.MakeTransparent();
			this._deleteBindingButton.Image = bitmap3;
			this._deleteBindingButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_DeleteBindingName");
			this._deleteBindingButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_DeleteBindingDescription");
			base.Icon = null;
		}

		// Token: 0x06002D41 RID: 11585 RVA: 0x00100892 File Offset: 0x000FF892
		private void OnApplyButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			this._applyButton.Enabled = false;
		}

		// Token: 0x06002D42 RID: 11586 RVA: 0x001008A6 File Offset: 0x000FF8A6
		private void OnAddBindingButtonClick(object sender, EventArgs e)
		{
			this._applyButton.Enabled = true;
			this.AddBinding();
		}

		// Token: 0x06002D43 RID: 11587 RVA: 0x001008BA File Offset: 0x000FF8BA
		private void OnAutoGenerateChanged(object sender, EventArgs e)
		{
			if (this._autoBindInitialized)
			{
				this._applyButton.Enabled = true;
			}
		}

		// Token: 0x06002D44 RID: 11588 RVA: 0x001008D0 File Offset: 0x000FF8D0
		private void OnBindingsListViewGotFocus(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		// Token: 0x06002D45 RID: 11589 RVA: 0x001008D8 File Offset: 0x000FF8D8
		private void OnBindingsListViewSelectedIndexChanged(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		// Token: 0x06002D46 RID: 11590 RVA: 0x001008E0 File Offset: 0x000FF8E0
		private void OnCancelButtonClick(object sender, EventArgs e)
		{
			base.DialogResult = DialogResult.Cancel;
			base.Close();
		}

		// Token: 0x06002D47 RID: 11591 RVA: 0x001008F0 File Offset: 0x000FF8F0
		private void OnDeleteBindingButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				this._bindingsListView.Items.RemoveAt(num);
				if (num >= this._bindingsListView.Items.Count)
				{
					num--;
				}
				if (num >= 0 && this._bindingsListView.Items.Count > 0)
				{
					this._bindingsListView.SetSelected(num, true);
				}
			}
		}

		// Token: 0x06002D48 RID: 11592 RVA: 0x0010097C File Offset: 0x000FF97C
		protected override void OnInitialActivated(EventArgs e)
		{
			base.OnInitialActivated(e);
			System.Windows.Forms.TreeNode selectedNode = this._schemaTreeView.Nodes.Add(SR.GetString("TreeViewBindingsEditor_EmptyBindingText"));
			if (this.Schema != null)
			{
				this.PopulateSchema(this.Schema);
				this._schemaTreeView.ExpandAll();
			}
			this._schemaTreeView.SelectedNode = selectedNode;
			this._autoBindInitialized = false;
			this._autogenerateBindingsCheckBox.Checked = this._treeView.AutoGenerateDataBindings;
			this._autoBindInitialized = true;
			this.UpdateEnabledStates();
		}

		// Token: 0x06002D49 RID: 11593 RVA: 0x00100A00 File Offset: 0x000FFA00
		private void OnMoveBindingUpButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num > 0)
				{
					TreeNodeBinding item = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num - 1, item);
					this._bindingsListView.SetSelected(num - 1, true);
				}
			}
		}

		// Token: 0x06002D4A RID: 11594 RVA: 0x00100A90 File Offset: 0x000FFA90
		private void OnMoveBindingDownButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num + 1 < this._bindingsListView.Items.Count)
				{
					TreeNodeBinding item = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num + 1, item);
					this._bindingsListView.SetSelected(num + 1, true);
				}
			}
		}

		// Token: 0x06002D4B RID: 11595 RVA: 0x00100B2E File Offset: 0x000FFB2E
		private void OnOKButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			base.DialogResult = DialogResult.OK;
			base.Close();
		}

		// Token: 0x06002D4C RID: 11596 RVA: 0x00100B44 File Offset: 0x000FFB44
		private void OnPropertyGridPropertyValueChanged(object s, PropertyValueChangedEventArgs e)
		{
			this._applyButton.Enabled = true;
			if (e.ChangedItem.PropertyDescriptor.Name == "DataMember")
			{
				string viewName = (string)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				this._bindingsListView.Items[this._bindingsListView.SelectedIndex] = treeNodeBinding;
				this._bindingsListView.Refresh();
				IDataSourceViewSchema dataSourceViewSchema = this.FindViewSchema(viewName, treeNodeBinding.Depth);
				if (dataSourceViewSchema != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = dataSourceViewSchema;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				return;
			}
			if (e.ChangedItem.PropertyDescriptor.Name == "Depth")
			{
				int level = (int)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				IDataSourceViewSchema dataSourceViewSchema2 = this.FindViewSchema(treeNodeBinding2.DataMember, level);
				if (dataSourceViewSchema2 != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding2).DataSourceViewSchema = dataSourceViewSchema2;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding2;
				this._propertyGrid.Refresh();
			}
		}

		// Token: 0x06002D4D RID: 11597 RVA: 0x00100C89 File Offset: 0x000FFC89
		private void OnSchemaTreeViewAfterSelect(object sender, TreeViewEventArgs e)
		{
			this.UpdateEnabledStates();
		}

		// Token: 0x06002D4E RID: 11598 RVA: 0x00100C91 File Offset: 0x000FFC91
		private void OnSchemaTreeViewGotFocus(object sender, EventArgs e)
		{
			this._propertyGrid.SelectedObject = null;
		}

		// Token: 0x06002D4F RID: 11599 RVA: 0x00100CA0 File Offset: 0x000FFCA0
		private void PopulateSchema(IDataSourceSchema schema)
		{
			if (schema == null)
			{
				return;
			}
			IDictionary duplicates = new Hashtable();
			IDataSourceViewSchema[] views = schema.GetViews();
			if (views != null)
			{
				for (int i = 0; i < views.Length; i++)
				{
					this.PopulateSchemaRecursive(this._schemaTreeView.Nodes, views[i], 0, duplicates);
				}
			}
		}

		// Token: 0x06002D50 RID: 11600 RVA: 0x00100CE8 File Offset: 0x000FFCE8
		private void PopulateSchemaRecursive(System.Windows.Forms.TreeNodeCollection nodes, IDataSourceViewSchema viewSchema, int depth, IDictionary duplicates)
		{
			if (viewSchema == null)
			{
				return;
			}
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode = new TreeViewBindingsEditorForm.SchemaTreeNode(viewSchema);
			nodes.Add(schemaTreeNode);
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode2 = (TreeViewBindingsEditorForm.SchemaTreeNode)duplicates[viewSchema.Name];
			if (schemaTreeNode2 != null)
			{
				schemaTreeNode2.Duplicate = true;
				schemaTreeNode.Duplicate = true;
			}
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				if (string.Compare(treeNodeBinding.DataMember, viewSchema.Name, StringComparison.OrdinalIgnoreCase) == 0)
				{
					IDataSourceViewSchemaAccessor dataSourceViewSchemaAccessor = treeNodeBinding;
					if (depth == treeNodeBinding.Depth || dataSourceViewSchemaAccessor.DataSourceViewSchema == null)
					{
						dataSourceViewSchemaAccessor.DataSourceViewSchema = viewSchema;
					}
				}
			}
			IDataSourceViewSchema[] children = viewSchema.GetChildren();
			if (children != null)
			{
				for (int i = 0; i < children.Length; i++)
				{
					this.PopulateSchemaRecursive(schemaTreeNode.Nodes, children[i], depth + 1, duplicates);
				}
			}
		}

		// Token: 0x06002D51 RID: 11601 RVA: 0x00100DE0 File Offset: 0x000FFDE0
		private void UpdateEnabledStates()
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				int num = this._bindingsListView.SelectedIndices[0];
				this._moveBindingDownButton.Enabled = (num + 1 < this._bindingsListView.Items.Count);
				this._moveBindingUpButton.Enabled = (num > 0);
				this._deleteBindingButton.Enabled = true;
			}
			else
			{
				this._moveBindingDownButton.Enabled = false;
				this._moveBindingUpButton.Enabled = false;
				this._deleteBindingButton.Enabled = false;
			}
			this._addBindingButton.Enabled = (this._schemaTreeView.SelectedNode != null);
		}

		// Token: 0x06002D52 RID: 11602 RVA: 0x00100E90 File Offset: 0x000FFE90
		private void UpdateSelectedBinding()
		{
			TreeNodeBinding selectedObject = null;
			if (this._bindingsListView.SelectedItems.Count > 0)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.SelectedItems[0];
				selectedObject = treeNodeBinding;
			}
			this._propertyGrid.SelectedObject = selectedObject;
			this._propertyGrid.Refresh();
			this.UpdateEnabledStates();
		}

		// Token: 0x04001ED7 RID: 7895
		private IDataSourceSchema _schema;

		// Token: 0x020004F3 RID: 1267
		private class SchemaTreeNode : System.Windows.Forms.TreeNode
		{
			// Token: 0x06002D53 RID: 11603 RVA: 0x00100EE8 File Offset: 0x000FFEE8
			public SchemaTreeNode(IDataSourceViewSchema schema) : base(schema.Name)
			{
				this._schema = schema;
			}

			// Token: 0x17000880 RID: 2176
			// (get) Token: 0x06002D54 RID: 11604 RVA: 0x00100EFD File Offset: 0x000FFEFD
			// (set) Token: 0x06002D55 RID: 11605 RVA: 0x00100F05 File Offset: 0x000FFF05
			public bool Duplicate
			{
				get
				{
					return this._duplicate;
				}
				set
				{
					this._duplicate = value;
				}
			}

			// Token: 0x17000881 RID: 2177
			// (get) Token: 0x06002D56 RID: 11606 RVA: 0x00100F0E File Offset: 0x000FFF0E
			public object Schema
			{
				get
				{
					return this._schema;
				}
			}

			// Token: 0x04001ED9 RID: 7897
			private IDataSourceViewSchema _schema;

			// Token: 0x04001EDA RID: 7898
			private bool _duplicate;
		}
	}
}
