using System;

namespace TechnoPro.Common.DAO.Impl.AlternativeFormat.QueryStorage
{
	// Token: 0x02000170 RID: 368
	public static class QueryStorageMediaContent
	{
		// Token: 0x04000674 RID: 1652
		internal const string SQ_GET_MEDIA_CONTENT_COURSES = "select FK_CourseId from [AlternativeFormat_MediaContent_x_Course] where FK_MediaContentID=@mediacontentid";

		// Token: 0x04000675 RID: 1653
		internal const string SQ_GET_MEDIA_CONTENT_THUMBNAIL_BY_ID = "select Thumbnail from [AlternativeFormat_MediaContentImage] where MediaContentId = @mediacontentid";

		// Token: 0x04000676 RID: 1654
		internal const string SQ_GET_MEDIA_CONTENT_COVER_BY_ID = "select BookCover from [AlternativeFormat_MediaContentImage] where MediaContentId = @mediacontentid";

		// Token: 0x04000677 RID: 1655
		internal const string SQ_IS_MEDIA_CONTENT_THUMBNAIL_AVAILABLE = "select MediaContentId from [AlternativeFormat_MediaContentImage] where MediaContentId = @mediacontentid";

		// Token: 0x04000678 RID: 1656
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_LIKE_BASE = "Select distinct TOP(100) \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course], \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (mc.ShortTitle like '%' + @searchtext + '%'\r\n                   OR mc.LongTitle like '%' + @searchtext + '%'\r\n                   OR mc.Authors like '%' + @searchtext + '%'\r\n                   OR mc.ISBN like '%' + @searchtext + '%'\r\n                   OR mc.MediaContentCategory like '%' + @searchtext + '%'\r\n                   OR luc.Course like '%' + @searchtext + '%') ";

		// Token: 0x04000679 RID: 1657
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_FULL_TEXT_SEARCH_BASE = "Select distinct TOP(100)  \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course],  \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (CONTAINS((mc.ShortTitle,mc.LongTitle,mc.Authors,mc.ISBN,mc.MediaContentCategory), @searchtext)\r\n                   OR CONTAINS(luc.Course, @searchtext)) ";

		// Token: 0x0400067A RID: 1658
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_LIKE_AND_COURSE = "Select distinct TOP(100) \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course], \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (mc.ShortTitle like '%' + @searchtext + '%'\r\n                   OR mc.LongTitle like '%' + @searchtext + '%'\r\n                   OR mc.Authors like '%' + @searchtext + '%'\r\n                   OR mc.ISBN like '%' + @searchtext + '%'\r\n                   OR mc.MediaContentCategory like '%' + @searchtext + '%'\r\n                   OR luc.Course like '%' + @searchtext + '%')  AND mcxc.FK_CourseId=@lucourseid";

		// Token: 0x0400067B RID: 1659
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_LIKE_AND_COURSE_WITH_EQUIVALENT_COURSES_FUNC = "Select distinct TOP(100) \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course], \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (mc.ShortTitle like '%' + @searchtext + '%'\r\n                   OR mc.LongTitle like '%' + @searchtext + '%'\r\n                   OR mc.Authors like '%' + @searchtext + '%'\r\n                   OR mc.ISBN like '%' + @searchtext + '%'\r\n                   OR mc.MediaContentCategory like '%' + @searchtext + '%'\r\n                   OR luc.Course like '%' + @searchtext + '%')  AND mcxc.FK_CourseId IN (SELECT lucourseid as FK_CourseId FROM {0}(@lucourseid))";

		// Token: 0x0400067C RID: 1660
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_FULL_TEXT_SEARCH_AND_COURSE = "Select distinct TOP(100)  \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course],  \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (CONTAINS((mc.ShortTitle,mc.LongTitle,mc.Authors,mc.ISBN,mc.MediaContentCategory), @searchtext)\r\n                   OR CONTAINS(luc.Course, @searchtext))  AND mcxc.FK_CourseId=@lucourseid";

		// Token: 0x0400067D RID: 1661
		internal const string SQ_GET_MEDIA_CONTENT_BY_SEARCH_TEXT_USING_FULL_TEXT_SEARCH_AND_COURSE_WITH_EQUIVALENT_COURSES_FUNC = "Select distinct TOP(100)  \r\n                        mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                        mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite,\r\n                        mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                        --mcxc.FK_CourseId as [CourseId], luc.[Course],  \r\n                        mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID],\r\n                        p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                        mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n                from AlternativeFormat_MediaContent as mc \r\n                LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n                LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]\r\n                LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID\r\n                LEFT JOIN LUCourses luc ON luc.LUCourseID=mcxc.FK_CourseId\r\n                where mc.IsActive=1 AND (CONTAINS((mc.ShortTitle,mc.LongTitle,mc.Authors,mc.ISBN,mc.MediaContentCategory), @searchtext)\r\n                   OR CONTAINS(luc.Course, @searchtext))  AND mcxc.FK_CourseId IN (SELECT lucourseid as FK_CourseId FROM {0}(@lucourseid))";

		// Token: 0x0400067E RID: 1662
		internal const string SQ_GET_MEDIA_CONTENT_BASE = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId]";

		// Token: 0x0400067F RID: 1663
		internal const string SQ_GET_MEDIA_CONTENT_BY_ID = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] where mc.MediaContentID=@mediaContentid";

		// Token: 0x04000680 RID: 1664
		internal const string SQ_GET_MEDIA_CONTENT_BY_ISBN = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] where ISBN=@isbn";

		// Token: 0x04000681 RID: 1665
		internal const string SQ_GET_MEDIA_CONTENT_BY_COURSE_WITH_EQUIVALENT_COURSES_FUNC = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID where mc.IsActive = 1 AND mcxc.FK_CourseId in (select lucourseid as FK_CourseId from {0}(@lucourseid))";

		// Token: 0x04000682 RID: 1666
		internal const string SQ_GET_MEDIA_CONTENT_BY_COURSE = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] LEFT JOIN [AlternativeFormat_MediaContent_x_Course] mcxc ON mcxc.FK_MediaContentID=mc.MediaContentID where mc.IsActive = 1 AND mcxc.FK_CourseId=@lucourseid";

		// Token: 0x04000683 RID: 1667
		internal const string SQ_GET_MEDIA_CONTENT_BY_PUBLISHER = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] where mc.IsActive=1 AND PublisherID=@publisherId";

		// Token: 0x04000684 RID: 1668
		internal const string SQ_GET_MEDIA_CONTENT_BY_TITLE = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] where mc.IsActive=1 AND (LongTitle=@title OR ShortTitle=@title)";

		// Token: 0x04000685 RID: 1669
		internal const string SQ_GET_MEDIA_CONTENT_BY_CATEGORY = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] where mc.IsActive=1 AND MediaContentCategory = @mediaCategoryId";

		// Token: 0x04000686 RID: 1670
		internal const string SQ_GET_MEDIA_CONTENT_FORMAT_BY_MEDIACONTENT = "Select [MediaContentFormat] from [AlternativeFormat_MediaContent_X_MediaContentFormat] where [FKMediaContentID] = @mediaContentId";

		// Token: 0x04000687 RID: 1671
		internal const string SQ_GET_ALL_MEDIA_CONTENT_ORDER_BY = "Select  mc.[MediaContentID], mc.[ShortTitle], mc.[LongTitle], mc.[Authors], mc.[Edition], mc.[Summary], \r\n                    mc.[PublisherID], pu.PublisherName, pu.PublisherDescription, pu.PublisherNotes, pu.PublisherPhone, pu.PublisherAddress, pu.PublisherFax, pu.PublisherEmail, pu.publisherWebsite, \r\n                    mc.[PublishedDate], mc.[ISBN], mc.[Length], mc.[WebSite], \r\n                    mc.[Notes], mc.[ProofOfPurchaseRequired], mc.[MediaContentCategory], mc.[WhoEnteredId], mc.[DateCreated], mc.[IsActive], mc.[MediaContentDataID], \r\n                    p.PersonID, p.firstname, p.lastname, p.middlename, p.student_no, pg.mingroupid as groupid,\r\n                    mc.ExternalId, mc.ExternalSourceProvider, mc.ThumbnailImageUrl\r\n            from AlternativeFormat_MediaContent as mc \r\n            LEFT JOIN AlternativeFormat_Publisher pu ON pu.PublisherID=mc.PublisherID\r\n            LEFT JOIN people p ON p.PersonID=mc.[WhoEnteredId]\r\n            LEFT JOIN peoplemingroup pg ON pg.PersonID=mc.[WhoEnteredId] WHERE mc.IsActive=1 ORDER BY ";

		// Token: 0x04000688 RID: 1672
		internal const string SQ_GET_MEDIA_CONTENT_DETAIL_BY_ID = "Select * from [AlternativeFormat_MediaContent_x_MediaContentFormat] \r\n                where MediaContentPerFormatID = @mediacontentperformatid";

		// Token: 0x04000689 RID: 1673
		internal const string SQ_GET_MEDIA_CONTENT_PER_FORMAT_INFO_BY_MEDIA_CONTENT = "Select * from [AlternativeFormat_MediaContent_x_MediaContentFormat] where [FKMediaContentID] = @mediacontentid";

		// Token: 0x0400068A RID: 1674
		internal const string SQ_GET_MEDIA_CONTENT_DETAIL_BY_CONTENT_ID_AND_FORMAT = "Select * from [AlternativeFormat_MediaContent_x_MediaContentFormat] where [FKMediaContentID] = @mediacontentid AND [MediaContentFormat] = @mediacontentformat";

		// Token: 0x0400068B RID: 1675
		internal const string SQ_GET_MEDIA_CONTENT_PER_FORMAT_ID_BY_MEDIA_CONTENT_AND_FORMAT = "select MediaContentPerFormatID from [AlternativeFormat_MediaContent_x_MediaContentFormat] where [FKMediaContentID] = @mediacontentid AND [MediaContentFormat] = @mediacontentformat";

		// Token: 0x0400068C RID: 1676
		internal const string DQ_DELETE_MEDIA_CONTENT_THUMBNAIL = "delete from AlternativeFormat_MediaContentImage where MediaContentId=@mediacontentid";

		// Token: 0x0400068D RID: 1677
		internal const string DQ_DELETE_MEDIA_CONTENT_COVER = "update AlternativeFormat_MediaContentImage set BookCover=NULL where MediaContentId=@mediacontentid";

		// Token: 0x0400068E RID: 1678
		internal const string UQ_INSERT_OR_UPDATE_MEDIA_CONTENT_THUMBNAIL = "IF EXISTS (SELECT 1 FROM [AlternativeFormat_MediaContentImage] where MediaContentId=@mediacontentid)\r\n                begin\r\n                    update [AlternativeFormat_MediaContentImage] set [Thumbnail]=@thumbnail where MediaContentId=@mediacontentid\r\n                end\r\n              ELSE\r\n                begin\r\n                    insert into [AlternativeFormat_MediaContentImage] (MediaContentId, [Thumbnail]) VALUES (@mediacontentid, @thumbnail)\r\n                end";

		// Token: 0x0400068F RID: 1679
		internal const string UQ_INSERT_OR_UPDATE_MEDIA_CONTENT_THUMBNAIL_AND_COVER = "IF EXISTS (SELECT 1 FROM [AlternativeFormat_MediaContentImage] where MediaContentId=@mediacontentid)\r\n                begin\r\n                    update [AlternativeFormat_MediaContentImage] set [BookCover]=@cover, [Thumbnail]=@thumbnail where MediaContentId=@mediacontentid\r\n                end\r\n              ELSE\r\n                begin\r\n                    insert into [AlternativeFormat_MediaContentImage] (MediaContentId, [Thumbnail], [BookCover]) VALUES (@mediacontentid, @thumbnail, @cover)\r\n                end";

		// Token: 0x04000690 RID: 1680
		internal const string IQ_GET_MEDIA_CONTENT_PER_FORMAT_ID_BY_MEDIA_CONTENT_AND_FORMAT = "if not exists (select 1 from AlternativeFormat_MediaContent_x_MediaContentFormat where MediaContentFormat = @mediacontentformat and FKMediaContentID = @mediacontentid)\r\n\t            begin\r\n\t\t            insert into AlternativeFormat_MediaContent_x_MediaContentFormat (MediaContentFormat, FKMediaContentID) values (@mediacontentformat, @mediacontentid)\r\n\t\t            set @mediacontentperformatid = SCOPE_IDENTITY()\r\n\t            end\r\n            else\r\n\t            begin\r\n\t\t            set @mediacontentperformatid = (select MediaContentPerFormatID from AlternativeFormat_MediaContent_x_MediaContentFormat where MediaContentFormat = @mediacontentformat and FKMediaContentID = @mediacontentid)\r\n\t            end";

		// Token: 0x04000691 RID: 1681
		internal const string IQ_NEW_MEDIA_CONTENT_FORMAT = "INSERT INTO [AlternativeFormat_MediaContent_X_MediaContentFormat]\r\n            ([FKMediaContentID], [MediaContentFormat]) \r\n            VALUES(@mediacontentid, @mediacontentformat) \r\n             set @mediacontentperformatid = SCOPE_IDENTITY()";

		// Token: 0x04000692 RID: 1682
		internal const string DQ_DELETE_MEDIA_CONTENT_BY_ID = "if not exists (select 1 from AlternativeFormat_StudentMediaRequestDetail where FKMediaContentID=@mediacontentid and IsCancelled = 0 and IsCompleted = 0)\r\nAND not exists (select 1 from AlternativeFormat_MediaJob mj left join AlternativeFormat_MediaContent_x_MediaContentFormat mcxf ON mcxf.MediaContentPerFormatID = mj.FKMediaContentPerFormatID\r\n\t\t\t\twhere mcxf.FKMediaContentID=@mediacontentid)\r\nbegin\r\n\tupdate [AlternativeFormat_MediaContent] set IsActive = 0 where [MediaContentID]=@mediacontentid\r\nend";

		// Token: 0x04000693 RID: 1683
		internal const string DQ_DELETE_MEDIA_CONTENT_DETAIL_BY_ID = "DELETE FROM [AlternativeFormat_MediaContent_x_MediaContentFormat] WHERE [MediaContentPerFormatID] = @mediacontentdetailid";

		// Token: 0x04000694 RID: 1684
		internal const string UQ_UPDATE_MEDIA_CONTENT_DETAIL = "UPDATE [AlternativeFormat_MediaContent_x_MediaContentFormat] \r\n                SET [FKMediaContentID] = @mediacontentid,\r\n                    [MediaContentFormat] = @mediacontentformat                   \r\n                WHERE [MediaContentPerFormatID] = @mediacontentdetailid";
	}
}
