using System;

namespace TechnoPro.Common.DAO.Impl.AppointmentsTestBooking.QueryStorageTests
{
	// Token: 0x02000155 RID: 341
	internal static class QueryStorageExamRequest
	{
		// Token: 0x040005F4 RID: 1524
		internal const string QS_EXAM_REQUESTS_BY_DATE_RANGE = "SELECT er.ExamRequestId,er.personid,er.lucourseid,er.startdate AS erstartdate,er.enddate AS erenddate,er.dateentered,er.instructorfirstname,er.instructorlastname,er.instructoremail,er.instructorphone,\r\n    era.ExamRequestAccommodationId,era.controlid,\r\n    e.examid,e.dateentered AS examdateentered,e.whoentered AS examwhoentered,e.description,e.dateoftest,e.visible,e.usercomment,e.testduration,e.lastmodified,e.wholastmodified,e.typecode,e.extendedproperties,e.testpickedupdate,e.testpickedupnote,\r\n    e.instructorcontacteddate,e.instructorcontactednote,e.privatenote,e.instructoracknowledged,e.filename\r\n    ,luc.startdate,luc.enddate\r\n    ,luc.term,luc.duration,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.timeofday,luc.section,v.instructorid,\r\n    lucd2.altlookupstring AS instructorname,lucd2.email AS instructoremail,lucd2.phone AS instructorphone,\r\n    lucd2.username AS instructorusername,lucd2.externalid AS instructorexternalid,lucd2.id AS instructoremployeeid,\r\n    p.firstname,p.lastname,p.middlename,p.student_no\r\n    ,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4,dc.defaultvalue\r\n    ,ad.valtext,ad.valint,ad.valbytes,ad.valdate,ad.valimage,ad.valbytesisencrypted,ad.dataid,ad.courseid\r\n    ,acc.longdescription\r\nFROM examrequest er LEFT JOIN examrequestaccommodations era ON era.examrequestid=er.examrequestid\r\n    LEFT JOIN exams e ON e.lucourseid=er.lucourseid AND e.dateoftest>=@startdate AND e.dateoftest<=@enddate AND e.typecode='F'\r\n    LEFT JOIN lucourses luc ON luc.lucourseid=er.lucourseid\r\n    LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n    LEFT JOIN people p ON p.personid=er.personid\r\n    LEFT JOIN dynamiccontrols dc ON dc.controlid=era.controlid\r\n    LEFT JOIN accommodationdata ad ON ad.controlid=era.controlid AND ad.personid=er.personid AND ad.courseid=0\r\n    LEFT JOIN accommodations acc ON acc.controlid=era.controlid\r\n    LEFT JOIN vInstructorPrimaryList v ON v.lucourseid=er.lucourseid\r\n    LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=v.instructorid\r\nWHERE er.dateentered>=@startdate AND er.dateentered<@enddate\r\nORDER BY er.examrequestid";

		// Token: 0x040005F5 RID: 1525
		internal const string QS_EXAM_REQUESTS_BY_COURSE = "SELECT er.ExamRequestId,er.personid,er.lucourseid,er.startdate AS erstartdate,er.enddate AS erenddate,er.dateentered,er.instructorfirstname,er.instructorlastname,er.instructoremail,er.instructorphone,\r\n    era.ExamRequestAccommodationId,era.controlid,\r\n    e.examid,e.dateentered AS examdateentered,e.whoentered AS examwhoentered,e.description,e.dateoftest,e.visible,e.usercomment,e.testduration,e.lastmodified,e.wholastmodified,e.typecode,e.extendedproperties,e.testpickedupdate,e.testpickedupnote,\r\n    e.instructorcontacteddate,e.instructorcontactednote,e.privatenote,e.instructoracknowledged,e.filename\r\n    ,luc.startdate,luc.enddate\r\n    ,luc.term,luc.duration,lucd.altlookupstring AS subject,luc.subjectid,luc.course,luc.timeofday,luc.section,v.instructorid,\r\n    lucd2.altlookupstring AS instructorname,lucd2.email AS instructoremail,lucd2.phone AS instructorphone,\r\n    lucd2.username AS instructorusername,lucd2.externalid AS instructorexternalid,lucd2.id AS instructoremployeeid,\r\n    p.firstname,p.lastname,p.middlename,p.student_no\r\n    ,dc.controlcaption,dc.controlcode,dc.setting1,dc.setting2,dc.setting3,dc.setting4,dc.defaultvalue\r\n    ,ad.valtext,ad.valint,ad.valbytes,ad.valdate,ad.valimage,ad.valbytesisencrypted,ad.dataid,ad.courseid\r\n    ,acc.longdescription\r\nFROM examrequest er LEFT JOIN examrequestaccommodations era ON era.examrequestid=er.examrequestid\r\n    LEFT JOIN exams e ON e.lucourseid=er.lucourseid AND e.typecode='F'\r\n    LEFT JOIN lucourses luc ON luc.lucourseid=er.lucourseid\r\n    LEFT JOIN lucoursedata lucd ON lucd.lucoursedataid=luc.subjectid\r\n    LEFT JOIN people p ON p.personid=er.personid\r\n    LEFT JOIN dynamiccontrols dc ON dc.controlid=era.controlid\r\n    LEFT JOIN accommodationdata ad ON ad.controlid=era.controlid AND ad.personid=er.personid AND ad.courseid=0\r\n    LEFT JOIN accommodations acc ON acc.controlid=era.controlid\r\n    LEFT JOIN vInstructorPrimaryList v ON v.lucourseid=er.lucourseid\r\n    LEFT JOIN lucoursedata lucd2 ON lucd2.lucoursedataid=v.instructorid\r\nWHERE er.lucourseid=@lucid\r\nORDER BY er.examrequestid";

		// Token: 0x040005F6 RID: 1526
		internal const string QI_EXAM_REQUEST = "DECLARE @name varchar(8000), @email varchar(8000)\r\nSET @name=(SELECT TOP 1 instructorname FROM vInstructorPrimaryList WHERE lucourseid=@lucid)\r\nSET @email=(SELECT TOP 1 instructoremail FROM vInstructorPrimaryList WHERE lucourseid=@lucid)\r\nINSERT INTO ExamRequest (personid,lucourseid,instructorfirstname,instructoremail) \r\nVALUES (@pid,@lucid,COALESCE(@name,''),COALESCE(@email,''));\r\n\r\nSET @examrequestid=(SELECT TOP 1 CAST(SCOPE_IDENTITY() AS int))";

		// Token: 0x040005F7 RID: 1527
		internal const string QI_EXAM_REQUEST_ACCOMMODATIONS = "INSERT INTO ExamRequestAccommodations (ExamRequestId,controlid) \r\n\tSELECT DISTINCT @id,controlid FROM accommodationdata WHERE personid=@pid AND courseid=dbo.AccommodationsCourseOrTemplate(@pid,@lucid) AND controlid IN (SELECT controlid FROM dynamicscreencontrols) AND controlid IN (SELECT controlid FROM accommodations WHERE (showonletter & 2)>0)";

		// Token: 0x040005F8 RID: 1528
		internal const string QD_EXAM_REQUEST = "DELETE FROM ExamRequestAccommodations WHERE ExamRequestId=@id;\r\nDELETE FROM ExamRequest WHERE ExamRequestId=@id";
	}
}
