using System;
using System.ComponentModel;
using System.Web.UI;
using Telerik.Charting.Styles;

namespace Telerik.Charting
{
	// Token: 0x02001741 RID: 5953
	public class ChartSeriesItemsCollection : ChartingStateManagedCollection<ChartSeriesItem>
	{
		// Token: 0x170046B8 RID: 18104
		// (get) Token: 0x0600E872 RID: 59506 RVA: 0x00342828 File Offset: 0x00340A28
		// (set) Token: 0x0600E873 RID: 59507 RVA: 0x00342830 File Offset: 0x00340A30
		[Browsable(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		public ChartSeries Parent
		{
			get
			{
				return this.seriesItemsCollectionParent;
			}
			set
			{
				this.seriesItemsCollectionParent = value;
				if (value != null)
				{
					foreach (ChartSeriesItem chartSeriesItem in this)
					{
						chartSeriesItem.Parent = this.Parent;
						chartSeriesItem.chartSeriesItemLabel.Marker.Appearance.styleChart = this.seriesItemsCollectionParent.Chart;
					}
				}
			}
		}

		// Token: 0x170046B9 RID: 18105
		[NotifyParentProperty(false)]
		[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
		[Browsable(false)]
		public override ChartSeriesItem this[int index]
		{
			get
			{
				return base.List[index];
			}
			set
			{
				base.List[index] = value;
				base.List[index].Parent = this.seriesItemsCollectionParent;
			}
		}

		// Token: 0x0600E876 RID: 59510 RVA: 0x003428DC File Offset: 0x00340ADC
		public ChartSeriesItemsCollection()
		{
		}

		// Token: 0x0600E877 RID: 59511 RVA: 0x003428E4 File Offset: 0x00340AE4
		public ChartSeriesItemsCollection(ChartSeries parent) : this()
		{
			this.seriesItemsCollectionParent = parent;
		}

		// Token: 0x0600E878 RID: 59512 RVA: 0x003428F4 File Offset: 0x00340AF4
		internal void DefineLabelText(ChartSeries series)
		{
			int num = 0;
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				if (chartSeriesItem.Empty)
				{
					if (series.Type == ChartSeriesType.CandleStick)
					{
						chartSeriesItem.YValue = series.GetEmptyPointYValue(chartSeriesItem, num, "YValue");
						chartSeriesItem.YValue2 = series.GetEmptyPointYValue(chartSeriesItem, num, "YValue2");
						chartSeriesItem.YValue3 = series.GetEmptyPointYValue(chartSeriesItem, num, "YValue3");
						chartSeriesItem.YValue4 = series.GetEmptyPointYValue(chartSeriesItem, num, "YValue4");
						chartSeriesItem.XValue = series.GetEmptyPointYValue(chartSeriesItem, num, "XValue");
						chartSeriesItem.XValue2 = series.GetEmptyPointYValue(chartSeriesItem, num, "XValue2");
					}
					else
					{
						chartSeriesItem.YValue = series.GetEmptyPointYValue(chartSeriesItem, num);
					}
				}
				num++;
				chartSeriesItem.DefineLabelText();
			}
		}

		// Token: 0x0600E879 RID: 59513 RVA: 0x003429E0 File Offset: 0x00340BE0
		internal void ClearAutoGeneratedLabelText()
		{
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				chartSeriesItem.ClearAutoGeneratedLabelText();
			}
		}

		// Token: 0x0600E87A RID: 59514 RVA: 0x00342A28 File Offset: 0x00340C28
		internal ChartSeriesItem GetItemWithMaxYValue(ChartSeriesItem notMoreItem)
		{
			if (base.Count <= 0)
			{
				return null;
			}
			ChartSeriesItem chartSeriesItem = new ChartSeriesItem();
			chartSeriesItem.YValue = double.MinValue;
			double num = (notMoreItem == null) ? double.MaxValue : notMoreItem.YValue;
			foreach (ChartSeriesItem chartSeriesItem2 in this)
			{
				if (chartSeriesItem.YValue < chartSeriesItem2.YValue && chartSeriesItem2.YValue < num)
				{
					chartSeriesItem = chartSeriesItem2;
				}
			}
			if (chartSeriesItem.YValue != -1.7976931348623157E+308)
			{
				return chartSeriesItem;
			}
			return null;
		}

		// Token: 0x0600E87B RID: 59515 RVA: 0x00342ACC File Offset: 0x00340CCC
		internal ChartSeriesItem GetItemWithMinYValue(ChartSeriesItem notMoreItem)
		{
			if (base.Count <= 0)
			{
				return null;
			}
			ChartSeriesItem chartSeriesItem = new ChartSeriesItem();
			chartSeriesItem.YValue = double.MaxValue;
			double num = (notMoreItem == null) ? double.MinValue : notMoreItem.YValue;
			foreach (ChartSeriesItem chartSeriesItem2 in this)
			{
				if (chartSeriesItem.YValue > chartSeriesItem2.YValue && chartSeriesItem2.YValue > num)
				{
					chartSeriesItem = chartSeriesItem2;
				}
			}
			if (chartSeriesItem.YValue != -1.7976931348623157E+308)
			{
				return chartSeriesItem;
			}
			return null;
		}

		// Token: 0x0600E87C RID: 59516 RVA: 0x00342B70 File Offset: 0x00340D70
		internal int ItemsInRange(double min, double max)
		{
			int num = 0;
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				if (chartSeriesItem.YValue >= min && chartSeriesItem.YValue <= max)
				{
					num++;
				}
			}
			return num;
		}

		// Token: 0x0600E87D RID: 59517 RVA: 0x00342BCC File Offset: 0x00340DCC
		internal double GetMinValue(double minValue, double maxValue)
		{
			double num = double.MaxValue;
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				if (chartSeriesItem.YValue >= minValue && chartSeriesItem.YValue < maxValue && chartSeriesItem.YValue < num)
				{
					num = chartSeriesItem.YValue;
				}
			}
			if (num == 1.7976931348623157E+308)
			{
				return minValue;
			}
			return num;
		}

		// Token: 0x0600E87E RID: 59518 RVA: 0x00342C48 File Offset: 0x00340E48
		internal double GetMaxValue(double minValue, double maxValue)
		{
			double num = double.MinValue;
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				if (chartSeriesItem.YValue > minValue && chartSeriesItem.YValue <= maxValue && chartSeriesItem.YValue > num)
				{
					num = chartSeriesItem.YValue;
				}
			}
			if (num == -1.7976931348623157E+308)
			{
				return maxValue;
			}
			return num;
		}

		// Token: 0x0600E87F RID: 59519 RVA: 0x00342CC4 File Offset: 0x00340EC4
		internal void Sort()
		{
			int count = base.Count;
			ChartSeriesItem[] array = new ChartSeriesItem[count];
			for (int i = 0; i < count; i++)
			{
				array[i] = this[i];
			}
			ChartSeriesItemComparer comparer = new ChartSeriesItemComparer();
			Array.Sort(array, comparer);
			base.Clear();
			for (int j = 0; j < count; j++)
			{
				this.Add(array[j]);
			}
		}

		// Token: 0x0600E880 RID: 59520 RVA: 0x00342D24 File Offset: 0x00340F24
		internal void Filter(ChartAxisVisibleValues chartAxisVisibleValues)
		{
			ChartSeriesItemsCollection chartSeriesItemsCollection = new ChartSeriesItemsCollection();
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				if (!chartSeriesItem.Empty)
				{
					switch (chartAxisVisibleValues)
					{
					case ChartAxisVisibleValues.All:
						chartSeriesItemsCollection.Add(chartSeriesItem);
						break;
					case ChartAxisVisibleValues.Positive:
						if (chartSeriesItem.YValue >= 0.0)
						{
							chartSeriesItemsCollection.Add(chartSeriesItem);
						}
						break;
					case ChartAxisVisibleValues.Negative:
						if (chartSeriesItem.YValue <= 0.0)
						{
							chartSeriesItemsCollection.Add(chartSeriesItem);
						}
						break;
					}
				}
			}
			base.Clear();
			foreach (ChartSeriesItem item in chartSeriesItemsCollection)
			{
				this.Add(item);
			}
		}

		// Token: 0x0600E881 RID: 59521 RVA: 0x00342E08 File Offset: 0x00341008
		internal void ResetActiveRegions()
		{
			foreach (ChartSeriesItem chartSeriesItem in this)
			{
				chartSeriesItem.ActiveRegion.activeRegionList.Clear();
				chartSeriesItem.ActiveRegion.activeRegionList.Add(null);
			}
		}

		// Token: 0x0600E882 RID: 59522 RVA: 0x00342E6C File Offset: 0x0034106C
		public override void Add(ChartSeriesItem chartSeriesItem)
		{
			if (this.seriesItemsCollectionParent != null)
			{
				chartSeriesItem.Parent = this.seriesItemsCollectionParent;
			}
			base.Add(chartSeriesItem);
		}

		// Token: 0x0600E883 RID: 59523 RVA: 0x00342E8C File Offset: 0x0034108C
		public void AddRange(ChartSeriesItemsCollection chartSeriesItems)
		{
			foreach (ChartSeriesItem item in chartSeriesItems)
			{
				this.Add(item);
			}
		}

		// Token: 0x0600E884 RID: 59524 RVA: 0x00342ED4 File Offset: 0x003410D4
		protected override void LoadViewState(object state)
		{
			if (state != null)
			{
				Pair pair = state as Pair;
				if (pair != null)
				{
					int num = (int)pair.First;
					object[] array = (object[])pair.Second;
					base.Clear();
					foreach (object state2 in array)
					{
						ChartSeriesItem chartSeriesItem = new ChartSeriesItem(this.Parent);
						((IChartingStateManager)chartSeriesItem).TrackViewState();
						((IChartingStateManager)chartSeriesItem).LoadViewState(state2);
						this.Add(chartSeriesItem);
					}
				}
			}
		}

		// Token: 0x040042A7 RID: 17063
		private ChartSeries seriesItemsCollectionParent;
	}
}
